'use strict';
// Names generated by immutable host, completed-cache caller and transport.
const NN=new Set(['OUTPUT_FINITE_RANGE','OUTPUT_SHAPE','FEATURE_FINITE','FEATURE_SHAPE','STRICT_VALUE','MODEL_HASH','MODEL_LENGTH','MODEL_SCHEMA','MODEL_BIND','MODEL_LOAD','NN_EMPTY_LEGAL','NN_ERROR','NN_FAILURE','INJECTED_NN_ERROR','NN_FALLBACK','model_failed','model_not_ready','no_onnx_session','feature_shape_finite','output_shape','output_finite_value','nn_empty_legal']);
const INFRA=new Set(['FINAL_IDENTITY','IDENTITY_MISMATCH','PIPE_PARSE','PIPE_ERROR','REFEREE_ERROR','OWNED_IDENTITY_MISMATCH','OWNED_CHECKPOINT_MISMATCH','PRODUCER_ECHO','PRODUCER_IDENTITY','PRODUCER_LIMITS','CLOCK_IDENTITY_MISSING']);
function classifyFailure(r){if(!['native','candidate','reference'].includes(r.engine)||INFRA.has(r.error))return {kind:'invalid_pair',category:'infra_invalid',reason:r.error||'engine identity missing'};
 if(r.engine==='reference'&&(r.fallback>0||NN.has(r.error)||/onnx|inference|tensor|session/i.test(r.error??'')))return {kind:'invalid_pair',category:'reference_NN_invalid',reason:'fixed reference model/NN/fallback failure'};
 return {kind:'engine_loss',category:'engine_loss',reason:r.error||(r.fallback>0?'NN_FALLBACK':'timeout/illegal/no checkpoint'),reason_pending:['NO_RESPONSE_TIMEOUT','BACKEND_EXIT'].includes(r.error)};}
module.exports={NN,INFRA,classifyFailure};
