// Derived from frozen continuation match-entry; real backend deliberately unconnected.
'use strict';const fs=require('fs'),path=require('path'),crypto=require('crypto'),G=require('./game-loop.cjs'),J=require('./judge.cjs'),{freeze}=require('./early-cache.cjs');
const ROOT=path.resolve(__dirname,'../..'),BASE=ROOT+'/.artifacts/ai-sigma/continuation-20261001/SIGMA-STREAMING-STARTUP-WATCHDOG',MOCK=Symbol('programmatic-diagnostic-only'),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b),clone=x=>JSON.parse(JSON.stringify(x)),now=()=>Number(process.hrtime.bigint())/1e6;
function compact(x){if(Array.isArray(x))return x.map(compact);if(x&&typeof x==='object'){const q={};for(const[k,v]of Object.entries(x)){if(['prefix','legal_prefix','history','tree','public_json','echo','identity'].includes(k)){if(v!=null)q[k+'_sha256']=J.hash(v);}else q[k]=compact(v);}return q;}return x;}
function readPlan(){return {prereg:JSON.parse(fs.readFileSync(BASE+'/preregister.json')),sha256:sha(BASE+'/preregister.json')}}
function schedule(p){const dict=JSON.parse(fs.readFileSync(BASE+'/prefix-dictionary.json'));if(p.issue!=='quoridor-4lc.73'||p.m!==32||p.total_games!==64||p.pairs.length!==32||p.clock.T_ms!==500||p.clock.reserve_ms!==89||p.clock.cutoff_ms!==402||p.clock.seal_ms!==411||sha(BASE+'/prefix-dictionary.json')!==p.prefix_dictionary.sha256)throw Error('FIXED_PLAN_REQUIRED');const seen=new Set();return p.pairs.map((b,i)=>{const d=dict[b.prefix_ref];if(!d||b.pair!==i+1||seen.has(b.pool_index)||p.excluded_sent8.includes(b.pool_index)||!eq([...b.candidate_color_order].sort(),[1,2])||d.pool_index!==b.pool_index||J.hash(d.legal_prefix)!==d.prefix_sha256||J.hash(d.context)!==d.context_sha256||!eq(J.context(J.state(d.legal_prefix)),d.context)||!eq(J.ids(d.legal_prefix),d.rust_prefix))throw Error('PAIR_IDENTITY');seen.add(b.pool_index);b.games.forEach((g,j)=>{if(g.game!==2*i+j+1||g.candidate_color!==b.candidate_color_order[j]||g.reference_color!==3-g.candidate_color||g.seed!==1979)throw Error('GAME_NUMBER')});return {...b,...d,platform:'browser',prefix:d.legal_prefix}})}
function verifyToken(t,purpose,diagnosticVerifier=false){if(!t||t.purpose!==purpose||t.issue!=='quoridor-4lc.75'||t.goal!=='quoridor-4lc'||!t.freeze_token||t.freeze_token!==process.env.SIGMA75_DIAGNOSTIC_TOKEN||!/^[a-zA-Z0-9_-]+$/.test(t.run_id??''))throw Error('EXPLICIT_PURPOSE_TOKEN_REQUIRED');const plan=readPlan(),m=JSON.parse(fs.readFileSync(BASE+'/entry-manifest.json'));if(t.preregister_sha256!==plan.sha256||t.entry_manifest_sha256!==sha(BASE+'/entry-manifest.json'))throw Error('FREEZE_HASH_MISMATCH');for(const c of m.checks)if(sha(c.path)!==c.sha256)throw Error('INPUT_MUTATED');if(purpose==='actual'){const fixed=diagnosticVerifier?BASE+'/diagnostic-verifier/freeze.json':BASE+'/coordinator-actual-freeze.json',accepted=diagnosticVerifier?BASE+'/diagnostic-verifier/acceptance.json':ROOT+'/.artifacts/ai-sigma/continuation-20261001/STARTUP-WATCHDOG-HANDOFF/independent75-acceptance.json';if(t.actual_go!==true||!fs.existsSync(fixed)||!fs.existsSync(accepted))throw Error('ACTUAL_GO_FALSE_NEW_FREEZE_REQUIRED');const proof=JSON.parse(fs.readFileSync(fixed));if(proof.actual_go!==true||proof.issued_by!==(diagnosticVerifier?'diagnostic-only-not-acceptance':'coordinator/01a0f31b-3409-75f2-a30e-453a50484f94')||t.coordinator_freeze_sha256!==sha(fixed)||proof.critic_acceptance_sha256!==sha(accepted)||proof.entry_manifest_sha256!==sha(BASE+'/entry-manifest.json')||proof.preregister_sha256!==plan.sha256||proof.dictionary_sha256!==sha(BASE+'/prefix-dictionary.json')||proof.independent_issue!=='quoridor-4lc.75'||proof.run_id!==t.run_id||Date.now()>Date.parse('2026-10-01T22:06:38.500Z'))throw Error('ACTUAL_FREEZE_ACCEPTANCE_DEADLINE_REQUIRED');return plan;}if(!['mock','golden'].includes(purpose)||t.actual_go!==false||m.actual_go!==false)throw Error('DIAGNOSTIC_ONLY');if(purpose==='golden'){const gate=JSON.parse(fs.readFileSync(BASE+'/phaseA-gates.json'));if(!gate.all_passed||t.phaseA_sha256!==sha(BASE+'/phaseA-gates.json'))throw Error('PHASE_A_GATE_REQUIRED');} return plan}
function score(table,p){const Xi=p.pairs.filter(b=>b.games.every(g=>table[g.game-1].status==='completed')).map(b=>b.games.reduce((n,g)=>n+table[g.game-1].result.score,0)/2),mean=Xi.length?Xi.reduce((a,b)=>a+b,0)/Xi.length:null;return {planned_m:32,completed_pairs:Xi.length,complete:Xi.length===32,Xi,mean,L:Xi.length===32?Math.max(0,mean-Math.sqrt(Math.log(20)/64)):null,formal_NI:false,old_results_pooled:false,W:table.filter(x=>x.status==='completed'&&x.result.score===1).length,D:table.filter(x=>x.status==='completed'&&x.result.score===.5).length,loss:table.filter(x=>x.status==='completed'&&x.result.score===0).length}}
function bounded(p,ms,clock,label){let timer;return new Promise(resolve=>{let done=false;const finish=x=>{if(done)return;done=true;clock.clear(timer);resolve(x)};timer=clock.delay(Math.max(0,ms),()=>finish({bounded_error:label}));Promise.resolve(p).then(x=>finish({value:x}),e=>finish({bounded_error:e.message}))})}
async function execute(o){require('./budget.cjs').gate(o.forecast??{profile_temp:50331648,trace_log:16777216,public_private_raw_clock:16777216,ending:6291456});if(o.key!==MOCK)throw Error('EXECUTE_DIAGNOSTIC_FACTORY_ONLY');const {prereg:p,out,createBackend,clock,control={}}=o;fs.mkdirSync(out,{recursive:false});const blocks=schedule(p),table=blocks.flatMap(b=>b.games.map(g=>({...g,pair:b.pair,pool_index:b.pool_index,status:'scheduled',attempts:[]}))),events=[],attempts=[],ownedPreparations=new Set();let backend=null,retries=0,sessions=0,generation=0,previousStamp=null,lastStop=null,pendingPreparation=null,stopReason='all_complete',signal=false,cleanupFailed=false;const save=(n,x)=>fs.writeFileSync(out+'/'+n+'.json',JSON.stringify(compact(x))+'\n'),guard=()=>{if(cleanupFailed)throw Error('OWNED_WORK_FAILED_RUN_STOP');if(signal||control.signal)throw Error('SIGNAL');if(control.pause?.())throw Error('PAUSED');if(clock.wall()>=o.deadline)throw Error('GLOBAL_DEADLINE')};
const signalFn=()=>{signal=true};process.once('SIGINT',signalFn);process.once('SIGTERM',signalFn);
const zero=x=>x&&((x.activeNN===0&&x.handles===0&&x.live_searches===0)||x.controlledPID0===true);
const cleanup=async()=>{if(!backend)return;const b=backend;backend=null;const r=await bounded(b.stop(),b.cleanupBudgetMs??100,clock,'CLEANUP_PENDING_FRESH_FORBIDDEN');events.push({kind:'cleanup',...r});if(r.bounded_error||!zero(r.value)){cleanupFailed=true;throw Error('CLEANUP_PENDING_FRESH_FORBIDDEN')}};
const start=async(lease)=>{await cleanup();guard();const b=await createBackend({session:++sessions,clock});if(lease?.closed){const r=await bounded(b.stop(),b.cleanupBudgetMs??100,clock,'LATE_FACTORY_CLEANUP_FAILED');events.push({kind:'late_factory_cleanup',session:sessions,...r});if(r.bounded_error||!zero(r.value)){cleanupFailed=true;throw Error('LATE_FACTORY_CLEANUP_FAILED')}return false;}if(!b.startup?.ready){backend=b;throw Error('BACKEND_READY_REQUIRED')}backend=b;if(previousStamp===null)previousStamp=clock.now();events.push({kind:'startup',session:sessions,wall:clock.wall()});return true;};
const choose=async(engine,input,meta)=>{
 const t0=previousStamp??clock.now(),lease={closed:false,prepared:false},prior=pendingPreparation;let context=null,used=null,id=null,sealTimer,deadlineTimer;
 // Arm before any cleanup, ACK, factory, or replay/conversion await.
 let publish;const publicPromise=new Promise(resolve=>publish=resolve);let publicOnce=false;
 const release=r=>{if(publicOnce)return;publicOnce=true;lease.closed=true;clock.clear(sealTimer);clock.clear(deadlineTimer);publish(r)};
 const discard=error=>release({accepted:false,checkpoint:false,action:null,error,local_timeout:true});
 sealTimer=clock.delay(Math.max(0,t0+411-clock.now()),()=>{try{guard();if(!lease.prepared)discard('NO_COMPLETED_SNAPSHOT')}catch(e){discard(e.message)}});
 deadlineTimer=clock.delay(Math.max(0,t0+500-clock.now()),()=>discard('NO_RESPONSE_TIMEOUT'));
 const active=()=>{if(lease.closed)return false;guard();return true};
 const work=(async()=>{await Promise.resolve();if(meta?.preparationDelayMs)await new Promise(resolve=>clock.delay(meta.preparationDelayMs,resolve));if(meta?.preparationNever)await new Promise(()=>{});if(prior){const q=await bounded(prior,1000,clock,'PREPARATION_UNREAPED_FRESH_FORBIDDEN');if(q.bounded_error)throw Error(q.bounded_error)}if(!active())return;
 if(meta?.fresh){await cleanup();lastStop=null;if(!active())return;if(!await start(lease))return;}if(lastStop){const q=await bounded(lastStop,backend.stopAckBudgetMs??100,clock,'OLD_WORK_NOT_ZERO_FRESH_FORBIDDEN');if(q.bounded_error||!zero(q.value))throw Error('OLD_WORK_NOT_ZERO_FRESH_FORBIDDEN')}if(!active())return;
 if(!backend)throw Error('BACKEND_READY_REQUIRED');used=backend;context=used.create({identity:id,meta});lease.prepared=true;
 const r=await used.submit(context);if(active())release(r);
 })();
 // Synchronous conversion also lies under the armed timer; OS blockage remains late.
 try{const ctx=J.context(J.state(input.legal_prefix));id={engine,request_id:o.runId+'-'+(++generation),generation,epoch:generation,fixture_id:input.id,fixture:null,legal_prefix:clone(input.legal_prefix),prefix:J.ids(input.legal_prefix),key:ctx.key,history:ctx.history,model:p.model.sha256,schema:'8x9x9-f32/136logits/value1/rust209',limits:{simulations:engine==='reference'?100000:4096,max_nodes:engine==='reference'?null:512,max_depth:engine==='reference'?null:24,seed:1979},t0_ms:t0,deadline_ms:t0+500,seal_ms:t0+411,commit_cutoff_ms:t0+402,request_token:o.runId+'-'+generation};freeze(id)}catch(e){discard(e.message);throw e;}
 ownedPreparations.add(work);work.then(()=>ownedPreparations.delete(work),()=>ownedPreparations.delete(work));pendingPreparation=work.catch(e=>{events.push({kind:'preparation_error',error:e.message});cleanupFailed=true;discard(e.message);});
 const r=await publicPromise,response=require('./final-envelope.cjs').finalize(r,id,clock,control);previousStamp=response.stamp_ms;
 if(context&&used){lastStop=used.finish(context,response);}events.push({kind:'public',identity:id,response,mock:used?.startup.mock===true,preparation_pending:!lease.prepared});if(control.afterPublic)control.afterPublic({meta,events,context,response});return response;
};
try{save('checkpoint',{table,attempts,retries,partial:true});await start();if(o.diagnosticRequests){for(const d of o.diagnosticRequests){if(o.diagnosticFaultGames){const turn=J.state(d.legal_prefix).getCurrentPlayer(),candidateColor=d.engine==='reference'?3-turn:turn;const result=await G.runGame({prefix:d.legal_prefix,candidateColor,platform:'browser',clock:clock.now,maxAddedPly:1,choose:(engine,input)=>choose(engine,input,d)});events.push({kind:'fault_game',id:d.id,result});}else{const response=await choose(d.engine,{id:d.id,legal_prefix:d.legal_prefix},d);const classification=G.classifyFailure(response);events.push({kind:'classified',id:d.id,response,classification});}}if(o.diagnosticFourPly){const result=await G.runGame({prefix:[],candidateColor:1,platform:'browser',clock:clock.now,maxAddedPly:4,choose:(engine,input)=>choose(engine,input,{diagnostic:true})});events.push({kind:'four_ply',result});}for(const d of o.diagnosticAfterRequests??[]){await choose(d.engine,{id:d.id,legal_prefix:d.legal_prefix},d);}}else for(const b of blocks){guard();let pairDone=false;for(let attempt=0;attempt<2;attempt++){const at={pair:b.pair,attempt,prefix_sha256:b.prefix_sha256,seed:1979,games:[],valid:false};attempts.push(at);let invalid=false,incomplete=false;for(const g of b.games){guard();const result=await G.runGame({prefix:clone(b.prefix),candidateColor:g.candidate_color,platform:'browser',clock:clock.now,choose:(engine,input)=>choose(engine,input,{pair:b.pair,game:g.game,attempt,candidateColor:g.candidate_color})});const row=table[g.game-1];row.attempts.push({attempt,result});row.status=result.kind==='invalid_pair'?'invalid':result.complete?'completed':'incomplete';row.result=result;at.games.push({game:g.game,result});save('checkpoint',{table,attempts,retries,partial:true});if(result.kind==='invalid_pair'){invalid=true;break}if(!result.complete){incomplete=true;break}}
if(!invalid&&!incomplete&&at.games.length===2){at.valid=true;pairDone=true;break}if(invalid&&attempt===0&&retries<2){retries++;for(const g of b.games){table[g.game-1].status='scheduled_retry';delete table[g.game-1].result}await cleanup();lastStop=null;await start();continue}stopReason=invalid?'retry_exhausted':'incomplete_game';break}if(!pairDone)break}}
catch(e){stopReason=e.message;events.push({kind:'entry_error',error:e.message})}finally{if(ownedPreparations.size){const q=await bounded(Promise.allSettled([...ownedPreparations]),2000,clock,'PREPARATION_UNREAPED_FRESH_FORBIDDEN');events.push({kind:'preparation_drain',...q});if(q.bounded_error){cleanupFailed=true;stopReason+=';'+q.bounded_error}}try{await cleanup()}catch(e){stopReason+=';'+e.message}process.removeListener('SIGINT',signalFn);process.removeListener('SIGTERM',signalFn)}const result={runId:o.runId,dry:true,actual_go:false,table,attempts,retries,sessions,stopReason,cleanupFailed,unrecovered_preparations:ownedPreparations.size,score:score(table,p),events,NN:o.realDiagnostic?'recorded in session raw':0,browser:o.realDiagnostic?'recorded in session raw':0,actual_games:0,holdout_sends:0};save('checkpoint',{table,attempts,retries,partial:!result.score.complete});save('summary',result);return compact(result)}
async function mainInternal(purpose,options={}){const argv=options.argv??process.argv.slice(2);if(argv[0]!== (purpose==='actual'?'--run':'--diagnostic')||!argv[1])throw Error('EXPLICIT_TOKEN_FILE_REQUIRED');const token=JSON.parse(fs.readFileSync(argv[1])),plan=verifyToken(token,purpose,options.diagnosticVerifier===true),out=BASE+'/diag-'+token.run_id;if(fs.existsSync(out))throw Error('RUN_ALREADY_EXISTS');if(!['mock','golden','actual'].includes(purpose)||options.key!==MOCK||typeof options.createBackend!=='function')throw Error('NO_FACTORY_IN_ACTUAL_CLI');return execute({...options,prereg:plan.prereg,out,runId:token.run_id,key:MOCK})}
const actualMain=o=>mainInternal('actual',{...o,key:MOCK});
const diagnosticGoldenMain=o=>mainInternal('golden',{...o,key:MOCK});
const diagnosticMockMain=o=>mainInternal('mock',{...o,key:MOCK});module.exports={schedule,readPlan,verifyToken,score,diagnosticMockMain,diagnosticGoldenMain,actualMain,diagnosticVerifierMain:o=>mainInternal('actual',{...o,key:MOCK,diagnosticVerifier:true})};if(require.main===module){const a=process.argv.slice(2);const run=a[0]==='--diagnostic-verifier'?require('./diagnostic-verifier.cjs').run(a):a[0]==='--diagnostic'?require('./golden-driver.cjs').run(a):require('./actual-driver.cjs').run(a);run.catch(e=>{console.error(e.stack);process.exitCode=1});}
