'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto');
const ROOT=path.resolve(__dirname,'../..'),O=ROOT+'/.artifacts/ai-sigma/resume-20261002/DIAGNOSTIC-ARENA-INDEPENDENT',U=ROOT+'/.artifacts/ai-sigma/resume-20261002/DIAGNOSTIC-ARENA',T=ROOT+'/tools/ai-sigma-actual-boundary-repair',J=require(T+'/judge.cjs'),G=require(T+'/game-loop.cjs'),F=require(T+'/final-envelope.cjs');
const inputHashes={};function read(p){const b=fs.readFileSync(p);inputHashes[p]=crypto.createHash('sha256').update(b).digest('hex');return JSON.parse(b)}function rows(p){if(!fs.existsSync(p))return[];const b=fs.readFileSync(p);inputHashes[p]=crypto.createHash('sha256').update(b).digest('hex');return b.toString().trim().split('\n').filter(Boolean).map(JSON.parse)}
const fixtures=read(ROOT+'/.artifacts/ai-sigma/reference-fixtures/SIGMA-PARITY-PLAN/fixtures.json').fixtures,refs=read(ROOT+'/.artifacts/ai-sigma/runs/SIGMA-INFERENCE-PROBE/ort-a.outputs.json'),runs=[];
const eq=(a,b)=>assert.equal(JSON.stringify(a),JSON.stringify(b));const near=(a,b)=>assert(Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a-b)<=1e-4+1e-4*Math.abs(b));
function pIndex(a,p1){let k=J.actionToIndex(a,9);if(p1)return k;if(k<8)return[1,0,2,3,6,7,4,5][k];const block=k<72?8:72,y=Math.floor((k-block)/8),x=(k-block)%8;return block+8*(7-y)+x;}
function numeric(s,n,cp,engine,ref,counts){assert.equal(n.features_bits.length,648);assert(n.features_bits.every(x=>Number.isInteger(x)&&x>=0&&x<=0xffffffff));const fl=s.toNNInput();eq(n.features_bits,Array.from(new Uint32Array(fl.buffer,fl.byteOffset,fl.length)));assert.equal(n.policy_logits.length,136);assert(n.policy_logits.every(Number.isFinite));assert(Number.isFinite(n.value)&&Math.abs(n.value)<=1);counts.featurebits+=648;counts.NNvalues+=137;counts.P2+=!s.isPlayer1Turn();if(ref){n.policy_logits.forEach((x,i)=>near(x,ref.policy_logits[i]));near(n.value,ref.value);counts.fixedNNroots++;}else counts.dynamicNNroots++;
 if(!cp){counts.noCP++;return;}assert.equal(cp.policy_fallbacks,0);assert.equal(cp.value_fallbacks,0);const actions=Array.from(s.getLegalActions()),order=actions.map(a=>J.rustAction(s,a)),expected=engine==='candidate'?order.slice().sort((a,b)=>a-b):order;assert.equal(new Set(expected).size,expected.length);eq(cp.root_edges.map(e=>e[0]),expected);const ix=new Map(actions.map(a=>[J.rustAction(s,a),pIndex(a,s.isPlayer1Turn())]));const max=Math.max(...expected.map(id=>n.policy_logits[ix.get(id)])),weights=new Map(expected.map(id=>[id,Math.exp(n.policy_logits[ix.get(id)]-max)])),sum=[...weights.values()].reduce((a,b)=>a+b,0);let vs=0,ps=0;
 for(const e of cp.root_edges){assert.equal(e.length,4);assert(e.every(Number.isFinite));assert(Number.isInteger(e[0])&&Number.isInteger(e[2])&&e[2]>=0&&e[1]>=0);near(e[1],weights.get(e[0])/sum);vs+=e[2];ps+=e[1];counts.priors++;}near(ps,1);assert.equal(vs,engine==='candidate'?cp.simulations-1:cp.simulations);if(engine==='reference')assert.equal(cp.root_visits,cp.simulations+1);counts.visits++;
}
async function main(){for(const base of [...fs.readdirSync(U).filter(n=>fs.existsSync(U+'/'+n+'/config.json')&&fs.existsSync(U+'/'+n+'/summary.json')).map(n=>U+'/'+n),O+'/critic95-golden-r1',O+'/critic95-four-ply-r1']){const c=read(base+'/config.json'),pub=rows(base+'/public.jsonl'),turn=rows(base+'/turns.jsonl'),moves=rows(base+'/moves.jsonl'),sum=read(base+'/summary.json');assert.equal(pub.length,turn.length);const states=new Map();const prefixByGame=new Map();let legalMoves=0;for(const m of moves){const g=m.game??0,current=prefixByGame.get(g)??fixtures.find(f=>f.id===c.fixture_id).legal_prefix;eq(m.prefix,current);const s=J.state(current);assert(!J.terminalResult(s));assert.equal(s.getCurrentPlayer(),m.color);const candidateColor=sum.games.find(x=>x.game===m.game)?.candidateColor??1;assert.equal(m.engine,m.color===candidateColor?'candidate':'reference');const r=m.response;assert.equal(r.referee_verified,true);if(r.accepted){const a=J.validate(current,r.action);eq(a,r.referee_action);prefixByGame.set(g,[...current,a]);legalMoves++;}states.set(JSON.stringify(current),s);}
 const counts={featurebits:0,NNvalues:0,priors:0,P2:0,fixedNNroots:0,dynamicNNroots:0,noCP:0,visits:0};for(let i=0;i<pub.length;i++){const {identity:id,response:r}=pub[i],tr=turn[i],s=states.get(JSON.stringify(id.legal_prefix))??J.state(id.legal_prefix);assert.equal(tr.request_id,id.request_id);eq(J.ids(id.legal_prefix),id.prefix);const ctx=J.context(s);eq(ctx.key,id.key);eq(ctx.history,id.history);assert.equal(id.generation,id.epoch);assert.equal(id.limits.seed,1979);assert.equal(id.model,c.model_sha256);eq(r.echo,id);for(const k of ['engine','request_id','generation','epoch','model','schema','limits'])eq(r[k],id[k]);assert.equal(typeof r.accepted,'boolean');assert.equal(typeof r.checkpoint,'boolean');assert.equal(r.public_bytes,Buffer.byteLength(r.public_json,'utf8'));const encoded=JSON.parse(r.public_json);assert.equal(encoded.action,r.action);assert.equal(encoded.referee_verified,true);if(r.accepted){assert(r.checkpoint&&r.action!==null&&r.fallback===0&&Number.isFinite(r.value)&&Math.abs(r.value)<=1);eq(J.validate(id.legal_prefix,r.action),r.referee_action);assert(r.stamp_ms<id.deadline_ms);}else assert.equal(r.action,null);const ref=refs.find(f=>f.id===id.fixture_id);if(tr.root_numeric)numeric(s,tr.root_numeric,tr.root_cp,id.engine,ref,counts);else counts.noCP++;}
 const games=[];for(const g of sum.games){const finalPrefix=prefixByGame.get(g.game??0);if(finalPrefix)eq(finalPrefix,g.result.prefix);const state=J.state(g.result.prefix),term=J.terminalResult(state);if(g.result.terminal){eq(term,g.result.terminal);assert.equal(G.terminalScore(term,g.candidateColor),g.result.score);}else if(g.result.kind==='engine_loss'){const last=moves.filter(m=>m.game===g.game).at(-1),fault=G.classifyFailure(last.response);assert.equal(last.response.accepted,false);assert.equal(fault.kind,g.result.kind);assert.equal(fault.category,g.result.category);assert.equal(last.engine,g.result.responsible_engine);assert.equal(g.result.score,last.color===g.candidateColor?0:1);}if(g.kind==='four-ply-diagnostic')assert(!term&&g.result.diagnostic_stop&&g.result.prefix.length===fixtures.find(f=>f.id===c.fixture_id).legal_prefix.length+4);games.push({game:g.game,candidateColor:g.candidateColor,terminal:term,score:g.result.score,ply:g.result.prefix.length,diagnostic_stop:g.result.diagnostic_stop});}
 runs.push({base,Git:c.git,public:pub.length,legalMoves,games,numeric:counts,declared_WDL:[sum.W,sum.D,sum.L]});}
 const mock=[];for(const engine of ['candidate','reference'])for(const error of ['OUTPUT_SHAPE','FINAL_IDENTITY','NO_RESPONSE_TIMEOUT']){let output;const result=await G.runGame({prefix:[],candidateColor:engine==='candidate'?1:2,platform:'browser',clock:()=>0,maxAddedPly:1,choose:async(e,input)=>{assert.equal(e,engine);output={engine,accepted:false,checkpoint:false,action:null,error,local_timeout:true};return output;}});const want=error==='FINAL_IDENTITY'||engine==='reference'&&error==='OUTPUT_SHAPE'?'invalid_pair':'engine_loss';assert.equal(result.kind,want);mock.push({engine,error,kind:result.kind,category:result.category,score:result.score});}
 const changed=Object.entries(inputHashes).filter(([p,h])=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')!==h);assert.equal(changed.length,0);fs.writeFileSync(O+'/replay-all-inputs.json',JSON.stringify(inputHashes,null,2)+'\n');fs.writeFileSync(O+'/legal-numeric-all-replay.json',JSON.stringify({UTC:new Date().toISOString(),runs,typed_same_game_loop_faults:mock,changed,scope:'fixed RuleA JS legal replay + root output/prior self-consistency; fixed ORT only fixture roots; not arbitrary NN/tree parity; no game or NN executed'},null,2)+'\n');console.log(JSON.stringify({runs,mock_cases:mock.length}));}
main().catch(e=>{fs.writeFileSync(O+'/replay-all-failure.json',JSON.stringify({UTC:new Date().toISOString(),name:e.name,message:e.message,stack:e.stack,inputHashes},null,2)+'\n');console.error(e.stack);process.exitCode=1});
