const {createRequire}=require('node:module'),fs=require('node:fs'),path=require('node:path');const {chromium}=createRequire('/workspaces/quoridor/package.json')('playwright');const root='/workspaces/quoridor/.worktree/ai-sigma',tool=path.join(root,'tools/ai-sigma-inference-release'),run=path.join(root,'.artifacts/ai-sigma/runs/SIGMA-INFERENCE-RELEASE');
const routes={'/probe.wasm':'/home/vscode/.cache/inference/research/ai-sigma/inference-release/target/wasm32-unknown-unknown/release/ai_sigma_inference_release.wasm','/model.onnx':path.join(root,'models/experiments/ai-sigma/reference/sigma-pcr250/best.onnx'),'/inputs.json':path.join(root,'.artifacts/ai-sigma/runs/SIGMA-INFERENCE-PROBE/inputs.json'),'/host.js':path.join(tool,'host.js'),'/worker.js':path.join(tool,'worker.js')};
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/workspaces/quoridor/artifacts/playwright/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox','--disable-gpu','--renderer-process-limit=1','--disable-dev-shm-usage']});try{let page=await browser.newPage();await page.route('http://localhost:5185/**',async route=>{let p=new URL(route.request().url()).pathname;if(p==='/')return route.fulfill({contentType:'text/html',body:'<!doctype html><script src="/host.js"></script>'});let file=routes[p];if(!file)throw Error(p);return route.fulfill({contentType:p.endsWith('.wasm')?'application/wasm':p.endsWith('.js')?'text/javascript':p.endsWith('.json')?'application/json':'application/octet-stream',body:fs.readFileSync(file)});});await page.goto('http://localhost:5185/');let result=await page.evaluate(async()=>{const inputs=await(await fetch('/inputs.json')).json(),out=[],timing=[];let h=await loadHost();const e=h.e,load_ms=h.load_ms,compile_ms=h.compile_ms,errors={};for(let f of inputs){let v=h.infer(f.features);out.push({id:f.id,policy_logits:v.policy_logits,value:v.value});if(['initial-p1','asym-hv-p2','straight-jump-p2'].includes(f.id)){h.infer(f.features);let a=[];for(let i=0;i<10;i++)a.push(h.infer(f.features).inference_ms);timing.push({id:f.id,cold_ms:v.inference_ms,feature_ms:v.feature_ms,samples_ms:a});}}
let short=h.floats(Array(647).fill(0));if(e.model_run(h.model,short)!==0)throw Error('short accepted');errors.short=e.error_code();h.free(short);let nan=h.floats(Array(648).fill(NaN));if(e.model_run(h.model,nan)!==0)throw Error('NaN accepted');errors.nan=e.error_code();h.free(nan);let b=h.bytes(new Uint8Array([1,2,3])),d=h.bytes(new TextEncoder().encode('bad'));if(e.model_load(b,d,1)!==0)throw Error('hash mismatch accepted');errors.hash=e.error_code();h.free(d);d=h.bytes(new TextEncoder().encode(h.digest));if(e.model_load(b,d,2)!==0)throw Error('schema accepted');errors.schema=e.error_code();if(e.model_load(b,d,1)!==0)throw Error('short model accepted');errors.broken=e.error_code();h.free(b);h.free(d);
let mem=[];for(let i=0;i<100;i++){h.infer(inputs[0].features);if(i%10===0)mem.push({i,linear:e.memory.buffer.byteLength,live:e.live_handles()});}let old=h.model;h.drop();if(e.release_handle(old)!==0||e.model_run(old,0)!==0||e.buffer_ptr(old)!==0)throw Error('stale handle accepted');errors.stale=e.error_code();if(e.live_handles()!==0)throw Error('leak');let hostReject=false;try{h.free(old)}catch(_){hostReject=true}if(!hostReject)throw Error('host doublefree accepted');let entropy=h.entropyCalls;
let reload=[];for(let i=0;i<3;i++){let x=await loadHost();x.infer(inputs[0].features);x.drop();reload.push({i,linear:x.e.memory.buffer.byteLength,live:x.e.live_handles(),load_ms:x.load_ms});}
// One same-module reload/drop sequence measures allocator reuse; separate instance
// reloads above measure cold module lifecycle only.
let raw=await(await fetch('/model.onnx')).arrayBuffer(),digest=new TextEncoder().encode(h.digest);for(let i=0;i<3;i++){let b=h.bytes(new Uint8Array(raw)),d=h.bytes(digest),m=h.adopt(e.model_load(b,d,1));h.free(b);h.free(d);h.free(m);mem.push({reload:i,linear:e.memory.buffer.byteLength,live:e.live_handles()});}
const workerResult=await new Promise((resolve,reject)=>{let w=new Worker('/worker.js'),events=[],epoch=0,cancelAt={},sentNew=false,accepted=[],discarded=[];let timer=setTimeout(()=>{w.terminate();reject(Error('worker diagnostic timeout'))},15000);const now=()=>performance.timeOrigin+performance.now();function send(q){events.push({type:'send-'+q.type,id:q.id,generation:q.generation,at:now()});w.postMessage(q)}function run(id,generation,count,yieldBetween){epoch=generation;send({type:'run',id,generation,count,yieldBetween,features:inputs[0].features})}function cancel(id,generation){cancelAt[id]=now();send({type:'cancel',id,generation})}
 w.onmessage=ev=>{let q=ev.data;events.push(q);if(q.type==='ready'){epoch=1;cancel(1,1)}if(q.type==='ack'&&q.id===1)run(1,1,1,true);if(q.type==='cancelled'&&q.id===1)run(2,2,3,true);if(q.type==='unit'&&q.id===2&&q.k===0){epoch=3;cancel(2,2)}if(q.type==='cancelled'&&q.id===2)run(3,3,20,false);if(q.type==='started'&&q.id===3&&!sentNew){sentNew=true;cancel(3,3);run(4,4,1,true)}if(q.type==='response'){if(q.generation!==epoch||cancelAt[q.id])discarded.push(q.id);else accepted.push(q.id);if(q.id===4)send({type:'drop'})}if(q.type==='dropped'){clearTimeout(timer);w.terminate();let response=events.find(x=>x.type==='response'&&x.id===3),ack=events.find(x=>x.type==='ack'&&x.id===3);resolve({events,accepted,discarded,cancelAt,during_single_nn:response?.spans.some(s=>s.start<=cancelAt[3]&&cancelAt[3]<=s.end),cancel_ack_delay_ms:ack?.at-cancelAt[3],remaining_compute_after_cancel:response?.spans.filter(s=>s.end>cancelAt[3]).length,live_after_drop:q.live,terminated:true,worker_load:events.find(x=>x.type==='ready')});}};w.onerror=ev=>{clearTimeout(timer);w.terminate();reject(Error(ev.message))}});
return{out,meta:{load_ms,compile_ms,timing,errors,mem,reload,live_after_drop:e.live_handles(),entropyCalls:entropy,hash_verified_by_browser_crypto:true,userAgent:navigator.userAgent,worker:workerResult}};});fs.writeFileSync(path.join(run,'wasm.outputs.json'),JSON.stringify(result.out)+'\n');fs.writeFileSync(path.join(run,'wasm.metadata.json'),JSON.stringify(result.meta,null,2)+'\n');console.log(JSON.stringify({cases:result.out.length,worker:result.meta.worker}));}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
