const SHA='d790dac68389f7602ff8a887a2385417d3c925fe22da7164c86e9226f943908d';
async function loadHost(){let inst,calls=0;const wasm=await(await fetch('/probe.wasm')).arrayBuffer();const t=performance.now();inst=await WebAssembly.instantiate(wasm,{env:{probe_entropy:(p,n)=>{calls++;if(!globalThis.crypto?.getRandomValues)return 1;let a=new Uint8Array(inst.instance.exports.memory.buffer,p,n);for(let i=0;i<n;i+=65536)crypto.getRandomValues(a.subarray(i,Math.min(i+65536,n)));return 0;}}});const compile_ms=performance.now()-t;let e=inst.instance.exports;let modelBytes=await(await fetch('/model.onnx')).arrayBuffer();let digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',modelBytes)),x=>x.toString(16).padStart(2,'0')).join('');if(digest!==SHA)throw Error('model hash mismatch');let alive=new Set();
function check(h){if(!alive.has(h))throw Error('stale host handle');return h}
function adopt(h){if(!h){let code=e.error_code(),kind=({1:'hash-attestation-mismatch',2:'schema',3:'model-length',4:'graph-load',5:'input-shape',6:'nonfinite-input',7:'inference',8:'output-shape',9:'output-finite-range',10:'stale-or-invalid-handle',12:'handle-exhausted'})[code]||'unknown';let x=Error(kind);x.code=code;x.kind=kind;throw x}alive.add(h);return h}
function bytes(u){let h=adopt(e.buffer_new(0,u.length));new Uint8Array(e.memory.buffer,e.buffer_ptr(h),u.length).set(u);return h}
function floats(u){let h=adopt(e.buffer_new(1,u.length));new Float32Array(e.memory.buffer,e.buffer_ptr(h),u.length).set(u);return h}
function free(h){check(h);if(!e.release_handle(h))throw Error('free error');alive.delete(h)}
let b=bytes(new Uint8Array(modelBytes)),d=bytes(new TextEncoder().encode(digest));let st=performance.now();let m=adopt(e.model_load(b,d,1));const load_ms=performance.now()-st;free(b);free(d);
function infer(features){let ft=performance.now(),f=floats(features),feature_ms=performance.now()-ft;let st=performance.now(),o;try{o=adopt(e.model_run(check(m),f));let ms=performance.now()-st;let v=Array.from(new Float32Array(e.memory.buffer,e.buffer_ptr(check(o)),137));return{policy_logits:v.slice(0,136),value:v[136],inference_ms:ms,feature_ms}}finally{if(o)free(o);free(f)}}
function drop(){free(m);m=0}
return {e,infer,free,bytes,floats,adopt,check,drop,get model(){return m},alive,load_ms,compile_ms,digest,get entropyCalls(){return calls}}}
