'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{spawn}=require('child_process'),{OwnedProcesses,boundedStop,table}=require('./cleanup.cjs');const BASE=path.resolve(__dirname,'../../.artifacts/ai-sigma/continuation-20261001/SIGMA-DETACHED-OWNERSHIP'),sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function run(){const proofs=[];
 // Managed external dummy: separate direct handle, deliberately never registered with this owner.
 const external=spawn('python3',['-c','import time;time.sleep(30)'],{stdio:'ignore'}),ext=table().get(external.pid);
 const owner=new OwnedProcesses({tracePath:BASE+'/dummy-detached-cleanup.jsonl'}),parent=owner.observeChild(spawn('python3',[__dirname+'/dummy-child.py','parent'],{stdio:['ignore','pipe','pipe']}));
 await sleep(150);owner.scan(true);await owner.registrationReceipt();const leaves=[...owner.ids].map(([pid,t])=>table().get(pid)).filter(p=>p&&p.pgid===p.pid&&p.pid!==parent.pid);assert.equal(leaves.length,1);assert(!owner.ids.has(external.pid));
 const backend={owner,stop:()=>new Promise(()=>{})};const stop=boundedStop(backend);assert.equal(boundedStop(backend),stop);const p=await stop;assert.equal(p.remaining_pids,0);assert.equal(p.registration_ack,true);assert(!table().has(leaves[0].pid));assert.equal(table().get(external.pid).starttick,ext.starttick);proofs.push({case:'detached_TERM_ignore_KILL_adoption_wait_PID0_and_external_exclusion',leaf:leaves[0],proof:p});
 // Explicit owner of the external dummy performs its recovery, outside the tested owner.
 const extOwner=new OwnedProcesses({tracePath:BASE+'/dummy-external-owner.jsonl'});extOwner.observeChild(external);proofs.push({case:'separate_external_owner_cleanup',proof:await boundedStop({owner:extOwner,stop:async()=>{external.kill('SIGTERM');return {remaining_pids:null}}})});
 const naturalOwner=new OwnedProcesses({tracePath:BASE+'/dummy-natural.jsonl'}),natural=naturalOwner.observeChild(spawn('python3',['-c','pass'],{stdio:'ignore'}));await sleep(100);assert(natural.exitCode!==null||natural.signalCode!==null);proofs.push({case:'natural_exit_and_idempotence',proof:await boundedStop({owner:naturalOwner,stop:async()=>({remaining_pids:0})})});
 // Lost receipt fails closed before signals; dedicated owner still has cleanup authority.
 const missing=new OwnedProcesses({tracePath:BASE+'/dummy-missing-receipt.jsonl'});missing.ledger.add({pid:987654321,starttick:123,ppid:process.pid},missing.rootIdentity);const ack=missing.ledger.ack;missing.ledger.ack=BASE+'/never-ack.json';let failed=false;try{await boundedStop({owner:missing,stop:async()=>{throw Error('UNREACHABLE')}})}catch(e){assert.equal(e.message,'OWNED_REGISTRATION_TIMEOUT');failed=true;}assert(failed);missing.ledger.ack=ack;proofs.push({case:'registration_missing_no_stop_no_fresh',public_action:null,fresh:false});
 fs.writeFileSync(BASE+'/dummy-summary.json',JSON.stringify({proofs,NN:0,actual_go:false},null,2)+'\n');console.log('dummy gates passed');}
run().catch(e=>{console.error(e);process.exitCode=1});
