/* Diagnostic-only final main. Actual matches are disabled in this contract. */
'use strict';const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict'),{open,BASE,ROOT}=require('./browser.cjs'),{boundedStop}=require('./cleanup.cjs');const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function verifyToken(argv=process.argv.slice(2)){if(argv[0]!=='--diagnostic'||!argv[1])throw Error('EXPLICIT_DIAGNOSTIC_TOKEN_REQUIRED');const t=JSON.parse(fs.readFileSync(argv[1]));if(t.issue!=='quoridor-4lc.59'||t.actual_go!==false||t.freeze_token!==process.env.SIGMA_MATCH_FREEZE_TOKEN||!t.freeze_token||t.preregister_sha256!==sha(BASE+'/preregister.json')||t.source_manifest_sha256!==sha(BASE+'/source-frozen.json')||t.run_id!=='STREAMING-59-02')throw Error('DIAGNOSTIC_TOKEN_BINDING');const m=JSON.parse(fs.readFileSync(BASE+'/source-frozen.json'));for(const c of m.checks)if(sha(c.path)!==c.sha256)throw Error('SOURCE_FROZEN_MISMATCH');for(const c of JSON.parse(fs.readFileSync(BASE+'/input-before.json')).checks)if(sha(c.path)!==c.sha256)throw Error('OLD_INPUT_MUTATED');if(Date.now()>=Date.parse('2026-10-01T15:13:11Z'))throw Error('NEW_JOB_CUTOFF');return t;}
async function main(){const token=verifyToken(),out=BASE+'/'+token.run_id;if(fs.existsSync(out))throw Error('RUN_ALREADY_EXISTS');fs.mkdirSync(out);const prereg=JSON.parse(fs.readFileSync(BASE+'/preregister.json')),fixtures=JSON.parse(fs.readFileSync(ROOT+'/.artifacts/ai-sigma/reference-fixtures/SIGMA-PARITY-PLAN/fixtures.json')).fixtures;const rows=[],stops=[];let active=null;const save=(n,x)=>fs.writeFileSync(out+'/'+n+'.json',JSON.stringify(x,null,2)+'\n');
 async function stop(){if(!active)return;const old=active;active=null;const start=Number(process.hrtime.bigint())/1e6,proof=await boundedStop(old);stops.push({...proof,stop_ms:Number(process.hrtime.bigint())/1e6,stop_cost_ms:Number(process.hrtime.bigint())/1e6-start});save('stop-before-document',stops);assert.equal(proof.remaining_pids,0);}
 try{for(const [index,spec]of prereg.cases.entries()){require('./pause-check.cjs').checkPause();const f=fixtures.find(x=>x.id===spec.fixture);assert(f&&(f.classification==='legal-replay'||spec.kind==='terminal-artificial'));assert(!active);const start=Number(process.hrtime.bigint())/1e6;active=await open(out+'/session-'+(index+1));const startup_ms=Number(process.hrtime.bigint())/1e6-start;let direct=null;if(spec.kind==='fixed_compare'){direct=await active.page.evaluate(({f,generation})=>directGolden(f,generation),{f,generation:spec.generation});assert.equal(direct.result.error,null);}
  const node_input_available_ms=Number(process.hrtime.bigint())/1e6;const r=await active.page.evaluate(({s,f})=>streamRequest(s,f),{s:{...spec,fixed_amount:spec.kind==='fixed_compare',caller_t0_ms:node_input_available_ms+active.clock.offset_ms},f});const node_received_ms=Number(process.hrtime.bigint())/1e6;
  assert.equal(r.sealed.request_id,spec.request_id);assert.equal(r.sealed.generation,spec.generation);if(r.sealed.action!==null)require('./judge.cjs').validate(f.legal_prefix,r.sealed.action);const finalEncoded=JSON.stringify(r.sealed),node_delivery_ms=Number(process.hrtime.bigint())/1e6;const obs=await active.page.evaluate(()=>collectObservation());Object.assign(r,obs);assert(r.postseal_unchanged);
  active.save('request-raw-before-validation',{spec,result:r,direct});let comparison=null;if(direct){const final=r.all_messages.find(x=>x.kind==='done')?.result;assert(final&&!final.error,'STREAM_FIXED_COMPLETE');const a=direct.result,b=final;comparison={final_cp_equal:JSON.stringify(a.cp)===JSON.stringify(b.cp),trace_cp_equal:a.trace.length===b.trace.length&&a.trace.every((x,i)=>JSON.stringify(x.cp)===JSON.stringify(b.trace[i].cp)),trace_length:a.trace.length,history_tree_exact:true};assert(comparison.final_cp_equal&&comparison.trace_cp_equal);}
  const row={spec,startup_ms,node_input_available_ms,node_received_ms,node_transport_elapsed_ms:node_received_ms-node_input_available_ms,node_delivery_ms,node_total_elapsed_ms:node_delivery_ms-node_input_available_ms,node_total_late:node_delivery_ms>=node_input_available_ms+spec.T_ms,node_total_overshoot_ms:Math.max(0,node_delivery_ms-node_input_available_ms-spec.T_ms),final_encoded_bytes:Buffer.byteLength(finalEncoded),clock:active.clock,comparison,direct:direct?.result??null,...r};rows.push(row);save('requests',rows);console.log(JSON.stringify({index:index+1,kind:spec.kind,fixture:f.id,action:r.sealed.action,error:r.sealed.error,simulations:r.sealed.owned?.cp.simulations??0,caller_late:r.caller_late,NN_crossings:r.actual_NN_crossings}));await stop();}
  save('summary',{planned:prereg.cases.length,completed:rows.length,fixed_exact:rows.filter(r=>r.comparison).every(r=>r.comparison.final_cp_equal&&r.comparison.trace_cp_equal),deadline_snapshot_count:rows.filter(r=>r.spec.kind==='deadline'&&r.sealed.checkpoint).length,all_actual_NN_crossings:rows.reduce((a,b)=>a+b.actual_NN_crossings,0),late_delivery_count:rows.filter(r=>r.caller_late).length,NO_COMPLETED_SNAPSHOT:rows.filter(r=>r.sealed.error==='NO_COMPLETED_SNAPSHOT').length,controlled_stops:stops.length,actual_go:false,games:0,holdout:0,formal_speed_or_clock_gate:false});
 }catch(e){save('failure',{error:e.message,stack:e.stack,rows_completed:rows.length});throw e;}finally{await stop();save('runtime-stop-before-document',{UTC:new Date().toISOString(),owned_PID0:stops.length>0&&stops.every(s=>s.remaining_pids===0),stops,all_requests_saved:rows.length,actual_go:false});}}
module.exports={verifyToken,main};if(require.main===module)main().catch(e=>{console.error(e.stack);process.exitCode=1});
