importScripts('/ort/ort.min.js','/host.js','/a-host.js','/game.js','/context.js','/checkpoint.js');
let b,a,generation=0,queue=Promise.resolve();const epoch=()=>performance.timeOrigin+performance.now(),yieldTask=()=>new Promise(r=>setTimeout(r,0));
async function run(d){if(d.backend&&d.backend!=='B')throw Error('B_ONLY');return runOwned(d,{b,epoch,yieldTask,getGeneration:()=>generation,notify:postMessage})}
onmessage=({data:d})=>{generation=d.generation??generation;
 if(d.kind==='cancel'){postMessage({kind:'cancel_ack',generation,request_id:d.request_id});return}
 queue=queue.then(async()=>{try{let result;if(d.kind==='load'){b=await loadOrtHost();result={B:{compile_ms:b.compile_ms,load_ms:b.load_ms,digest:b.digest,version:b.version,threads:b.threads,proxy:b.proxy},A:{loaded:false}}}
 else if(d.kind==='clock'){result={clock_ms:epoch()}}
 else if(d.kind==='numeric'){result=await b.numeric(d.fixture);const state=referenceState(d.fixture),fb=Array.from(new Uint32Array(state.toNNInput().buffer)),legal=state.getLegalActions().map(x=>rustAction(state,x)).sort((x,y)=>x-y),terminal=terminalResult(state)?.value??null;if(JSON.stringify(fb)!==JSON.stringify(result.features_bits)||JSON.stringify(legal)!==JSON.stringify(result.raw_legal)||terminal!==result.terminal)throw Error('REFERENCE_STATE_PARITY');result.reference_features_exact=true;result.reference_legal_exact=true;result.reference_terminal_equal=true}
 else if(d.kind==='control'){const s=b.create({fixture:d.fixture,diagnostic:true,simulations:4096,max_nodes:512,max_depth:24,generation:d.generation,seed:1979});try{for(let i=0;i<d.steps;i++){const q=b.call({op:'begin',handle:s,generation:d.generation});if(q.pending){const r=await b.infer(q.features_bits);b.call({op:'resume',handle:s,generation:d.generation,token:q.token,logits:r.logits,value:r.value})}await yieldTask()}result=b.call({op:'snapshot',handle:s,generation:d.generation})}finally{b.free(s)}}
 else if(d.kind==='fixed'||d.kind==='timed'){result=await run(d)}
 else if(d.kind==='model_faults'){result=await b.modelFaults()}
 else if(d.kind==='raw'){result=b.call({op:'raw',fixture:d.fixture})}
 else if(d.kind==='faults'){result={};for(const name of ['shape','null','range','duplicate','stale','token','cancel']){const g=100,s=b.create({prefix:[],generation:g,simulations:32});const q=b.call({op:'begin',handle:s,generation:g});const r={op:'resume',handle:s,generation:g,token:q.token,logits:Array(136).fill(0),value:0.25};if(name==='shape')r.logits.pop();if(name==='null')r.logits[0]=null;if(name==='range')r.value=1.001;if(name==='stale')r.generation++;if(name==='token')r.token++;try{if(name==='cancel')b.call({op:'cancel',handle:s,generation:g});if(name==='duplicate')b.call(r);b.call(r);result[name]={unexpected_success:true}}catch(e){result[name]={error:e.message};try{b.call({op:'checkpoint',handle:s,generation:g});result[name].checkpoint_published=true}catch{result[name].checkpoint_published=false}}finally{b.free(s)}}}
 else if(d.kind==='drop'){await b.drop();if(a)a.drop();result={dropped:true}}
 else throw Error('REQUEST_KIND');const serializeStart=epoch(),serialized=JSON.stringify(result),serializeEnd=epoch();if(d.serialize_delay_ms)await new Promise(r=>setTimeout(r,d.serialize_delay_ms));if(d.kind==='timed'&&!result.error&&epoch()>=d.t0+d.T_ms){result.cp=null;result.owned=null;result.error='DEADLINE_SERIALIZATION'}if(d.generation!==generation){result.cp=null;result.owned=null;result.error='STALE_GENERATION_SERIALIZATION'}postMessage({kind:'response',request_id:d.request_id,generation:d.generation,result,serialization_ms:serializeEnd-serializeStart,serialized_bytes:serialized.length,worker_delivery_send_ms:epoch()});}catch(e){postMessage({kind:'response',request_id:d.request_id,generation:d.generation,error:e.message})}});
};
