'use strict';
async function audit122(input,fixtures,refs){
 const runs=[],games=[],samples=[],issues=[];let totalNN=0,startup=0;
 const check=(x,tag,id)=>{if(!x)throw Error('C122_'+tag+' '+(id??''));};
 for(const run of input.runs){
  const c={public:run.rows.length,legal:0,late:0,cancel:0,initial_none:0,NN:0,discard:0,opposite_before_ACK:0,oldAPI_spans_newinput:0,own_ACK_violations:0,ACKover500:0,post_public_definite:0,post_public_possible:0,cutoff_definite:0,cutoff_possible:0,worker_by_engine:{candidate:{upper_le_D:0,lower_gt_D:0,straddles:0},reference:{upper_le_D:0,lower_gt_D:0,straddles:0}},max_public:0,max_own_wait:0,accepted_CP_sequences:0};
  const own=new Map(),map=new Map(),prior=[];
  check(run.started_games===2&&run.started_requests===run.rows.length,'STARTS');check(!run.external_abort&&!run.player_errors.length&&Array.isArray(run.waiting_messages)&&run.waiting_messages.length===0&&run.main_timer_count===0,'FINAL_MAIN_ZERO');
  for(const r of run.rows){
   const id=r.identity,p=r.response,b=p.body,d=r.diagnostic,s=fromPrefix(id.legal_prefix),rid=id.request_id;
   check(!map.has(rid),'DUP_REQUEST',rid);map.set(rid,r);
   check(id.limits.seed===run.seed&&id.model==='d790dac68389f7602ff8a887a2385417d3c925fe22da7164c86e9226f943908d','MODEL_SEED',rid);
   check(id.engine===b.engine&&id.engine===r.player_engine&&d.worker_engine===id.engine&&d.player_binding===id.engine,'ENGINE_ECHO',rid);
   check(id.request_id===b.request_id&&id.request_token===rid&&id.generation===b.generation&&id.epoch===id.generation,'ID_EPOCH',rid);
   eq109(d.identity,id,'PRODUCER_ECHO');check(id.key===s._positionKey(),'KEY',rid);eq109(id.history,Array.from(s.position_history).sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:0),'HISTORY');eq109(id.prefix,rustPrefix(id.legal_prefix),'ABI_PREFIX');
   check(id.limits.simulations===(id.engine==='candidate'?4096:100000)&&id.limits.max_nodes===(id.engine==='candidate'?512:null)&&id.limits.max_depth===(id.engine==='candidate'?24:null),'LIMITS');
   check(id.t0_ms==p.t0_ms&&id.seal_ms-id.t0_ms===411&&id.commit_cutoff_ms-id.t0_ms===402&&id.deadline_ms-id.t0_ms===500&&p.planned_ms===id.seal_ms,'T_CUTOFF');
   check(p.stamp_ms>=p.timer_ms&&p.public_elapsed_ms===p.stamp_ms-id.t0_ms&&p.bytes===new TextEncoder().encode(p.body_serialized).length,'FINAL_STAMP');eq109(b,JSON.parse(p.body_serialized),'SERIALIZED_BODY');
   check([b.completed,b.cancelled,b.late].every(x=>typeof x==='boolean'),'STRICT_BOOLEAN');check(b.late===(p.stamp_ms>=id.deadline_ms),'LATE_POLICY');check(r.postpublic_immutable&&p.public_did_not_await_ACK&&r.Node_per_CP_binding_calls===0&&p.Node_clock_referee_calls===0,'IMMUTABLE_BROWSER_ROUTE');
   if(b.completed){check(!b.late&&!b.cancelled&&s.getLegalActions().some(a=>sameAction(a,b.action)),'LEGAL',rid);check(p.classification==='completed_legal','CLASSIFICATION');const cp=d.sab_publications.find(x=>x.sequence===b.sequence);check(cp&&cp.action===rustAction(s,b.action),'COMPLETED_SAB_ACTION',rid);check(Number.isSafeInteger(b.sequence)&&b.sequence>0,'SEQUENCE');c.legal++;}else{check(b.action===null,'NULL');if(b.late)c.late++;if(b.cancelled)c.cancel++;if(!b.cancelled&&!b.late)c.initial_none++;}
   let seq=0;for(const pub of d.sab_publications){check(pub.sequence>seq&&Number.isSafeInteger(pub.sequence)&&pub.validation_end_ms>=pub.begin_ms,'MONOTONE_COMPLETION',rid);seq=pub.sequence;c.accepted_CP_sequences++;}
   check(id.t0_ms>=(own.get(id.engine)??-Infinity),'OWN_PREV_ACK_ZERO',rid);check(r.own_previous_wait.end_ms<=id.t0_ms&&r.own_previous_wait.wait_ms===r.own_previous_wait.end_ms-r.own_previous_wait.start_ms,'OWN_WAIT');c.max_own_wait=Math.max(c.max_own_wait,r.own_previous_wait.wait_ms);
   const ack=r.stop;check(ack&&ack.identity.request_id===rid&&ack.identity.limits.seed===run.seed&&ack.worker_engine===id.engine,'ACK_BINDING');check(!ack.stop.handles&&!ack.stop.activeNN&&!ack.stop.live_searches&&!ack.stop.active,'ACK_ZERO');own.set(id.engine,ack.main_received_ms);
   const k=r.worker_clock;check(k.lo_ms<=k.hi_ms,'CLOCK_INTERVAL');const lower=ack.stop.at_ms-k.hi_ms,upper=ack.stop.at_ms-k.lo_ms;const wc=c.worker_by_engine[id.engine];if(upper<=id.deadline_ms)wc.upper_le_D++;else if(lower>id.deadline_ms)wc.lower_gt_D++;else wc.straddles++;if(ack.main_received_ms-id.t0_ms>500)c.ACKover500++;
   const ev=d.NN_control_events;check(Array.isArray(ev)&&ev.length===r.hand_NN,'NN_DENOMINATOR');c.NN+=ev.length;
   for(const e of ev){check(e.request_id===rid&&e.engine===id.engine&&e.generation===id.generation,'API_BINDING');check(e.session_run_end_ms>=e.session_run_start_ms,'API_ORDER');const lo=e.session_run_start_ms-k.hi_ms,hi=e.session_run_start_ms-k.lo_ms;if(lo>p.stamp_ms)c.post_public_definite++;if(hi>p.stamp_ms)c.post_public_possible++;if(lo>id.commit_cutoff_ms)c.cutoff_definite++;if(hi>id.commit_cutoff_ms)c.cutoff_possible++;if(e.result_discarded)c.discard++;}
   const previous=prior.slice().reverse().find(x=>x.identity.engine!==id.engine);if(previous){check(id.t0_ms>=previous.response.stamp_ms,'NEXT_AFTER_PUBLIC');if(id.t0_ms<previous.stop.main_received_ms)c.opposite_before_ACK++;const pk=previous.worker_clock;if(previous.diagnostic.NN_control_events.some(e=>e.session_run_start_ms-pk.hi_ms<=id.t0_ms&&e.session_run_end_ms-pk.lo_ms>=id.t0_ms))c.oldAPI_spans_newinput++;}
   c.max_public=Math.max(c.max_public,p.public_elapsed_ms);if(r.selected_numeric)samples.push(numeric109(r,s,fixtures,refs));prior.push(r);
  }
  const local=[];for(const g of run.games){let prefix=structuredClone(g.initial_prefix),s=fromPrefix(prefix);check(g.seed===run.seed&&g.fixture_id===run.fixture,'GAME_SEED_FIXTURE');const f=fixtures.find(x=>x.id===g.fixture_id);eq109(prefix,f.legal_prefix,'FIXTURE_PREFIX');check(g.actions.length===g.turn_indices.length,'GAME_COUNT');for(let n=0;n<g.actions.length;n++){check(!terminalResult(s),'AFTER_TERMINAL');const r=map.get(g.turn_indices[n]);check(r,'MISSING_TURN');eq109(r.identity.legal_prefix,prefix,'REPLAY_PREFIX');check(r.identity.engine===(s.getCurrentPlayer()===g.candidate_color?'candidate':'reference'),'COLOR_PLAYER');eq109(r.response.body.action,g.actions[n],'PUBLIC_ACTION');check(s.getLegalActions().some(a=>sameAction(a,g.actions[n])),'REPLAY_LEGAL');s=s.next(g.actions[n]);prefix.push(g.actions[n]);}const end=terminalResult(s);check(end&&end.winner===g.winner&&g.reason==='goal'&&g.status==='terminal','GOAL_TERMINAL');check(s._positionKey()===g.final_key&&s.depth===g.total_ply,'FINAL_CONTEXT');local.push({id:g.id,fixture:g.fixture_id,seed:g.seed,color:g.candidate_color,winner:end.winner,newplies:g.actions.length,prefixply:g.initial_prefix.length,totalply:g.total_ply,score:end.winner===g.candidate_color?1:end.winner===0?.5:0});}
  check(local.map(x=>x.color).join(',')==='1,2','COLOR_ORDER');games.push(...local);
  const clocks={};for(const engine of ['candidate','reference']){const end=run.clock_end[engine];const lo=Math.max(...end.samples.map(x=>x.worker_ms-x.end_ms-.1)),hi=Math.min(...end.samples.map(x=>x.worker_ms-x.start_ms+.1));check(lo===end.lo_ms&&hi===end.hi_ms&&lo<=hi,'END_CLOCK');const initial=run.rows.find(x=>x.identity.engine===engine).worker_clock;const ilo=Math.max(...initial.samples.map(x=>x.worker_ms-x.end_ms-.1)),ihi=Math.min(...initial.samples.map(x=>x.worker_ms-x.start_ms+.1));check(ilo===initial.lo_ms&&ihi===initial.hi_ms,'START_CLOCK');clocks[engine]={initial:{lo:ilo,hi:ihi},end:{lo,hi},mid_shift:(lo+hi-ilo-ihi)/2,intermediate_drift_unmeasured:true};}
  const sn=run.startup_rows.reduce((a,x)=>a+x.NN,0);check(sn===6&&run.startup_rows.every(x=>x.zero),'STARTUP_SEPARATE');startup+=sn;totalNN+=c.NN;runs.push({run:run.run,seed:run.seed,fixture:run.fixture,counts:c,clocks,Xi:local.reduce((a,x)=>a+x.score,0)/2,startup_NN:sn});
 }
 return {runs,games,W:games.filter(x=>x.score===1).length,D:games.filter(x=>x.score===.5).length,L:games.filter(x=>x.score===0).length,public:runs.reduce((a,x)=>a+x.counts.public,0),legal:runs.reduce((a,x)=>a+x.counts.legal,0),hand_NN:totalNN,startup_NN:startup,numeric_samples:samples,shared_RuleA_independence_limit:true,browser_adjudicated:true,new_NN_model_load_games:0,formal_go:false,issues};
}
function typed122(){
 const rows=[];const base={completed:false,shared_state:SharedBestAction.STATE.FAULT};
 for(const error of ['NN_BACKEND:DIAGNOSTIC','MODEL_MISMATCH','FALLBACK','FINAL_IDENTITY'])for(const engine of ['candidate','reference']){const fault={error},c=classifyResponse(base,fault),r=gameFailureResult(c,1,engine,fault);const expected=/IDENTITY/.test(error)?'shared_identity_failure':engine==='reference'?'reference_NN_invalid':'engine_fault';must109(r.reason===expected,'FAULT_RULE');rows.push({engine,error,classification:c,result:r});}
 for(const extra of [{late:true},{judge_error:'diagnostic'},{external_abort:{code:'diagnostic'}}]){const r={...base,...extra},fault={error:'NN_BACKEND:diagnostic'},c=classifyResponse(r,fault),flags=responseCauses(r,fault);must109(c!=='engine_fault'&&flags.shared_fault&&flags.received_engine_fault,'SIMULTANEOUS_FLAGS');rows.push({classification:c,flags});}
 return {rows,NN:0};
}
function cache122(input){const runs=[],marker_examples=[];for(const run of input.runs){let accepted=0,rejected=0,selected=0,accepted_after_cutoff=0,selected_publish_definite_after=0,selected_publish_possible_after=0;for(const r of run.rows){const id=r.identity,b=r.response.body,k=r.worker_clock,d=r.diagnostic;for(const e of d.validation_events){if(e.accepted){accepted++;if(e.validation_finished_ms>=id.commit_cutoff_ms)accepted_after_cutoff++;}else rejected++;}const e=d.validation_events.find(e=>e.accepted&&e.sequence===b.sequence),pub=d.sab_publications.find(e=>e.sequence===b.sequence);must109(e&&pub&&e.validated_cache_ms===e.validation_finished_ms&&e.validation_finished_ms<id.commit_cutoff_ms,'ADOPTED_VALIDATED_CACHE');selected++;if(pub.validation_end_ms-k.hi_ms>id.commit_cutoff_ms){selected_publish_definite_after++;marker_examples.push({request:id.request_id,engine:id.engine,sequence:b.sequence,cache_validated_elapsed_ms:e.validation_finished_ms-id.t0_ms,publication_end_elapsed_interval_ms:[pub.validation_end_ms-k.hi_ms-id.t0_ms,pub.validation_end_ms-k.lo_ms-id.t0_ms],timer_elapsed_ms:r.response.timer_ms-id.t0_ms,stamp_elapsed_ms:r.response.stamp_ms-id.t0_ms,exact_Atomic_store_time_missing:true});}if(pub.validation_end_ms-k.lo_ms>id.commit_cutoff_ms)selected_publish_possible_after++;}runs.push({run:run.run,accepted,rejected,selected,accepted_after_cutoff,selected_publish_definite_after,selected_publish_possible_after,publish_end_is_saved_marker_not_exact_Atomic_store_time:true});}return {runs,marker_examples,browser_computed:true,NN:0};}

function prefix122(doc){
 const rows=[],keys=new Set();must109(doc.search_seed===1979&&doc.prefixes.length===8&&doc.attempts.length===8,'PREFIX_PLAN_DENOMINATOR');
 for(let i=0;i<8;i++){const n=doc.prefixes[i],f=n.fixture;let state=fromPrefix([]),z=31001+i;const next=()=>{z=(z^(z<<13))>>>0;z=(z^(z>>>17))>>>0;z=(z^(z<<5))>>>0;return z;},prefix=[];const ply=[4,5,8,9,12,13,16,17][i];must109(n.pair===i+1&&n.base_seed===31001+i&&n.attempt===0&&n.accepted,'PREFIX_SELECTION');for(let j=0;j<ply;j++){must109(!terminalResult(state),'PREFIX_ALREADY_TERMINAL');const legal=state.getLegalActions(),p=legal.filter(a=>a.type==='pawn'),w=legal.filter(a=>a.type==='wall');const draw=p.length&&w.length?next():null,choices=draw===null?(p.length?p:w):(draw<2147483648?p:w),a=choices[Math.floor(next()/4294967296*choices.length)];prefix.push(structuredClone(a));state=state.next(a);}eq109(prefix,f.legal_prefix,'INDEPENDENT_PRNG_REPLAY');must109(!terminalResult(state)&&state.depth===ply&&state._positionKey()===f.history_count_key&&state.getCurrentPlayer()===f.player,'PREFIX_END_CONTEXT');const h=[...state.position_history].sort((a,b)=>a[0].localeCompare(b[0]));eq109(h,f.history_counts,'PREFIX_HISTORY');eq109(state.getLegalActions().map(a=>rustAction(state,a)),f.legal_ids,'PREFIX_LEGAL_MAPPING');const features=state.toNNInput();eq109(Array.from(new Uint32Array(features.buffer,features.byteOffset,features.length)),f.features_bits,'PREFIX_648');const key=JSON.stringify(prefix);must109(!keys.has(key),'PREFIX_DUPLICATE');keys.add(key);rows.push({pair:i+1,seed:n.base_seed,ply,player:f.player,key:state._positionKey(),legal_actions:f.legal_ids.length});}
 return {rows,attempts:8,P1:rows.filter(x=>x.player===1).length,P2:rows.filter(x=>x.player===2).length,independent_PRNG:true,shared_RuleA:true,NN:0};
}
function summary122(input){const run=input.runs[0],med=a=>{const s=a.slice().sort((a,b)=>a-b);return s.length%2?s[(s.length-1)/2]:(s[s.length/2-1]+s[s.length/2])/2;},engines={};for(const e of ['candidate','reference']){const rr=run.rows.filter(r=>r.identity.engine===e);engines[e]={n:rr.length,hand_NN:rr.reduce((a,r)=>a+r.hand_NN,0),firstCP_median_ms:med(rr.map(r=>r.diagnostic.sab_publications[0].validation_end_ms-r.worker_clock.mid_ms-r.identity.t0_ms)),firstAPIawait_median_ms:med(rr.map(r=>{const x=r.diagnostic.NN_control_events[0];return x.session_run_end_ms-x.session_run_start_ms;})),max_timer_lateness_ms:Math.max(...rr.map(r=>r.response.timer_ms-r.response.planned_ms)),max_final_cost_ms:Math.max(...rr.map(r=>r.response.stamp_ms-r.response.timer_ms)),max_ACKwall_ms:Math.max(...rr.map(r=>r.stop.main_received_ms-r.identity.t0_ms))};}return {engines,public:run.rows.length,primary:null,secondary:[],NN_kernel_time_unobserved:true};}
function combine122(results){const audits=results.map(x=>x.audit),runs=audits.flatMap(x=>x.runs),games=audits.flatMap(x=>x.games),counts={};for(const r of runs)for(const [k,v]of Object.entries(r.counts))if(typeof v==='number')counts[k]=k.startsWith('max_')?Math.max(counts[k]??0,v):(counts[k]??0)+v;const workers={candidate:{upper_le_D:0,lower_gt_D:0,straddles:0},reference:{upper_le_D:0,lower_gt_D:0,straddles:0}};for(const r of runs)for(const e of Object.keys(workers))for(const k of Object.keys(workers[e]))workers[e][k]+=r.counts.worker_by_engine[e][k];const pairs=runs.map(r=>{const gg=games.filter(g=>g.fixture===r.fixture);return {pair:r.run,Xi:r.Xi,scores:gg.map(g=>g.score),winners:gg.map(g=>g.winner),same_side_winner:gg[0].winner===gg[1].winner,prefixply:gg[0].prefixply,newplies:gg.map(g=>g.newplies)};});return {counts,worker_stop_intervals:workers,W:games.filter(g=>g.score===1).length,D:games.filter(g=>g.score===.5).length,L:games.filter(g=>g.score===0).length,color1:games.filter(g=>g.color===1).map(g=>g.score),color2:games.filter(g=>g.color===2).map(g=>g.score),pairs,same_side_pairs:pairs.filter(p=>p.same_side_winner).length,startup_NN:audits.reduce((a,x)=>a+x.startup_NN,0),numeric_samples:audits.flatMap(x=>x.numeric_samples),cache:results.map(x=>x.cache),formal_go:false,NN0_browser_only:true};}
