'use strict';
function auditRow125(r,fixtures,refs){
 const f=fixtures.find(f=>f.id===r.fixture_id);must109(f,'INPUT_FIXTURE');const state=fromPrefix(f.legal_prefix),engine=r.condition==='A'?'candidate':'reference';must109(!r.primary&&!r.main_gate_error,'COMPLETED_ONLY');must109(r.K===32&&r.completed_backups===32&&r.NN_calls===r.spans.length&&r.terminal_noNN_backups===32-r.NN_calls,'BACKUP_NN_SEPARATE');must109(r.worker_engine===engine&&r.cp.generation===r.generation,'ROW_GENERATION_ENGINE');must109(r.zero.handles===0&&r.zero.activeNN===0&&r.zero.active===false&&r.zero.mode==='original','MODE_ZERO');must109(r.used_mode===(r.condition==='C'?'Q0':'original'),'USED_MODE');
 const row={identity:{engine,generation:r.generation,legal_prefix:f.legal_prefix},response:{body:{cancelled:false}},selected_numeric:{numeric:r.numeric[0],cp:r.cp}};const numeric=numeric109(row,state,fixtures,refs);must109(r.cp.root_edges.reduce((a,e)=>a+e[2],0)===31,'EDGE31');must109(state.getLegalActions().map(a=>rustAction(state,a)).includes(r.cp.action),'FINAL_ACTION_LEGAL');let selections=0;const close=(a,b)=>Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a-b)<=1e-10+1e-10*Math.abs(b);
 if(engine==='candidate'){must109(r.cp.simulations===32&&r.cp.tree[0].visits===32&&r.candidate_parentQ_missing,'CANDIDATE_TRUE_N_PARENT_MISSING');}
 else {const n=r.root_node;must109(n.truevisitCount===32&&r.cp.root_visits===32&&r.cp.simulations===31,'TRUE_REFERENCE_N');must109(close(n.parentQ,n.valueSum/n.truevisitCount),'PARENT_Q');const visited=n.children.filter(x=>x.visitCount>0),sum=visited.reduce((a,x)=>a+x.basePrior,0);must109(close(sum,n.visitedChildBasePriorSum),'VISITED_PRIOR_FINAL_SUM');must109(n.children.reduce((a,x)=>a+x.visitCount,0)===31,'TRUE_CHILD_VISITS');for(const child of n.children){must109(child.visitCount>=0&&Number.isSafeInteger(child.visitCount)&&Number.isFinite(child.basePrior)&&child.basePrior>=0&&child.basePrior<=1&&Number.isFinite(child.valueSum),'CHILD_FINITE');if(child.visitCount)must109(close(child.childQ,child.valueSum/child.visitCount),'VISITED_Q');}
 let prior=-1;for(const x of r.root_FPU_selections){must109(x.truevisitCount===++selections&&close(x.parentQ,x.valueSum/x.truevisitCount),'TRUE_NODE_SELECTION_Q');must109(x.visitedChildBasePriorSum>=prior-1e-10&&x.visitedChildBasePriorSum<=1+1e-5,'VISITED_PRIOR_RANGE_MONOTONE');prior=x.visitedChildBasePriorSum;const original=x.parentQ-.2*Math.sqrt(x.visitedChildBasePriorSum);must109(close(x.original_unvisitedQ,original)&&close(x.used_unvisitedQ,r.condition==='C'?0:original)&&x.mode===r.used_mode,'FPU_FORMULA');}must109(selections===31,'SELECTION31');}
 for(const s of r.spans)must109(s.wrapper_end_ms>=s.wrapper_start_ms&&s.API_end_ms>=s.API_start_ms,'SPAN_ORDER');const edge=r.cp.root_edges,entropy=edge.reduce((a,e)=>e[2]?a-e[2]/31*Math.log(e[2]/31):a,0);if(r.entropy!=null)must109(close(entropy,r.entropy),'ENTROPY');return {id:r.id,fixture:r.fixture_id,condition:r.condition,action:r.cp.action,visits:edge.map(e=>[e[0],e[2]]),root_N:32,edge_sum:31,backups:32,NN:r.NN_calls,terminal_noNN:r.terminal_noNN_backups,selections,parentQ_missing:engine==='candidate',depth:r.depth??r.reference_visited_depth??null,entropy,numeric,wrapper_ms:r.wrapper_end_ms-r.wrapper_start_ms,cleanup_independent_span_missing:true,perstep_visited_prior_input_not_full_child_trace:true};
}
function audit125(runs,fixtures,refs){const rows=[],failed=[],generations=[];let transports=0;for(const run of runs){const seen=new Set();for(const r of run.data.count_results){transports++;must109(!seen.has(r.generation),'GENERATION_DUPLICATE');seen.add(r.generation);if(r.primary||r.main_gate_error){must109(r.primary&&r.NN_calls===0&&r.completed_backups===0&&!r.cp&&!r.root_node,'PRESEARCH_NOT_NN_FAILURE');failed.push({id:r.id,condition:r.condition,fixture:r.fixture_id,primary:r.primary,NN:0,backups:0});continue;}rows.push(auditRow125(r,fixtures,refs));}}
 const comparisons=[],TV=(a,b)=>{const aa=new Map(a.visits),bb=new Map(b.visits);must109(aa.size===bb.size&&[...aa.keys()].every(k=>bb.has(k)),'TV_ACTION_DOMAIN');return [...aa.keys()].reduce((s,k)=>s+Math.abs(aa.get(k)-bb.get(k)),0)/62;};for(const f of [...new Set(rows.map(r=>r.fixture))]){const g=Object.fromEntries(rows.filter(r=>r.fixture===f).map(r=>[r.condition,r]));if(g.A&&g.B&&g.C){const actual=runs.flatMap(r=>r.data.count_results).filter(r=>r.fixture_id===f&&!r.primary);const nums=actual.map(r=>r.numeric[0]);must109(nums.every(n=>JSON.stringify(n.features_bits)===JSON.stringify(nums[0].features_bits)),'ABC_FEATURES');must109(nums.every(n=>JSON.stringify(n.policy_logits)===JSON.stringify(nums[0].policy_logits)&&n.value===nums[0].value),'ABC_NN_EXACT');comparisons.push({fixture:f,TV_AB:TV(g.A,g.B),TV_AC:TV(g.A,g.C),TV_BC:TV(g.B,g.C),actions:[g.A.action,g.B.action,g.C.action],distance_direction:TV(g.A,g.C)<TV(g.A,g.B)?'closer':TV(g.A,g.C)>TV(g.A,g.B)?'farther':'equal',root_NN_exact:true});}else if(g.B&&g.C)comparisons.push({fixture:f,TV_BC:TV(g.B,g.C),actions_BC:[g.B.action,g.C.action]});}
 return {rows,failed,transport_attempts:transports,completed_searches:rows.length,completed_backups:rows.reduce((a,r)=>a+r.backups,0),NN:rows.reduce((a,r)=>a+r.NN,0),terminal_noNN:rows.reduce((a,r)=>a+r.terminal_noNN,0),trueNode_selections:rows.reduce((a,r)=>a+r.selections,0),comparisons,fixed_reference_roots:rows.filter(r=>r.numeric.fixed_reference).length,dynamic_self_roots:rows.filter(r=>!r.numeric.fixed_reference).length,candidate_parentQ_not_reconstructed:true,browser_computed:true,formal_go:false};
}
