"""Observed budget, qualified-density targets and finite cost scenarios."""
from pathlib import Path
import datetime,gzip,hashlib,json,subprocess,time
R=Path.cwd();D=R/'research-data/ai-sigma/frame16-teacher-throughput';x=json.loads((D/'comparison.json').read_text());conds=x['conditions'];cs=conds['candidate'];bs=[conds[n]for n in['baseline','baseline-confirmation']if n in conds];bwall=sum(b['jobwall_s']for b in bs)/len(bs);density=cs['qualified_joint']/cs['completed_games'];delta_game=(bwall-cs['jobwall_s'])/48;methods={};archive=json.loads((D/'archive-manifest.json').read_text());n_generations=len(conds);pack_per48=archive['wall_s']/n_generations
for n,s in conds.items():
 qual=json.loads((D/(n+'-summary.json')).read_text())['qualify_wall_s'];save=json.loads((D/'save-timing.json').read_text());git_per48=save['measured_save_wall_s']/n_generations;unit=(s['jobwall_s']+qual+pack_per48+git_per48)/48
 rawbytes=sum(p.stat().st_size for p in(D/'jobs'/n).glob('core*/raw-rows.jsonl'));gzbytes=(D/(n+'-teacher-rows.jsonl.gz')).stat().st_size;archive_pergame=archive['archive_B']/(48*n_generations)
 methods[n]=dict(observed_completed_games=s['completed_games'],planned_games=48,observed_rows_per_completed_game=s['qualified_joint']/s['completed_games'],jobwall_seconds_per_completed_game=s['jobwall_s']/s['completed_games'],qualified_pipeline_s_per_game=unit,qualification_s=qual,sharedpack_per48_s=pack_per48,sharedGit_per48_s=git_per48,common_setup_not_amortized_here=True,scenarios={str(N):dict(games=N,projected_job_minutes=N*s['jobwall_s']/s['completed_games']/60,projected_qualification_pack_Git_included_minutes=N*unit/60,packed_evidence_B=N*archive_pergame,raw_runtime_B=N*rawbytes/48,qualified_gzip_B=N*gzbytes/48,Git_unique_plus_pack_approx_B=2*N*archive_pergame,whole_linear_extrapolation_not_measured_production=True)for N in[100,1000,10000]})
err=json.loads((D/'admission-failure-cost-erratum.json').read_text());proc=[json.loads(p.read_text())for p in(D/'jobs').glob('*/process.json')];measured=sum(p['jobwall_seconds']for p in proc if p['kind']!='admission_failed_before_science');NN=sum(p.get('sample_equivalent')or 0 for p in proc);intake=datetime.datetime.fromisoformat(json.loads((D/'intake.json').read_text())['UTC']);now=datetime.datetime.now(datetime.timezone.utc);elapsed=(now-intake).total_seconds();known_setup=json.loads((D/'jobs/parity-r2/process.json').read_text())['jobwall_seconds']+sum(json.loads((D/(n+'-summary.json')).read_text())['qualify_wall_s']for n in conds)+archive['wall_s']+save['measured_save_wall_s'];allprep_upper=elapsed-sum(p['jobwall_seconds']for p in proc if p['kind']=='generation');break_even=dict(observed_paired_saving_s_per_game=delta_game,known_validation_qualification_pack_save_cost_s=known_setup,known_cost_recovery_games=known_setup/delta_game if delta_game>0 else None,receipt_to_now_elapsed_s=elapsed,elapsed_less_generation_wall_s=allprep_upper,elapsed_includes_reasoning_natural_window_wait_other_helpers=True,elapsed_recovery_scenario_games=allprep_upper/delta_game if delta_game>0 else None,incremental_improvement_only_preparation_cost='UNKNOWN; common benchmark preparation and B24 work not separately timed',gain_small_and_order_uncertain=True)
result=dict(issue='quoridor-4lc.221',UTC=now.isoformat(),measured_allattempt_jobwall_s=measured,unmeasured_failed_admission_wall=err,conservative_heavy_charge_s=measured+5,NN_total=NN,NN_cap=900000,heavy_cap=1800,static_conservative_charge_s=45,static_cap_s=180,methods=methods,targets=dict(games=1000,initial_minutes=60,next_minutes=30,actual_1000_run=False,observed_candidate_density=density,required_Rjoint_s_at60min=density*1000/3600,required_Rjoint_s_at30min=density*1000/1800,example49_density_thresholds=dict(hour=49*1000/3600,half_hour=49*1000/1800),not_all_game_lengths_representative=True),comparison_to_two_baselines=dict(mean_B8_job_s=bwall,B24_job_s=cs['jobwall_s'],B24_rate_relative_to_mean_B8=bwall/cs['jobwall_s'],B8_job_range_s=[min(b['jobwall_s']for b in bs),max(b['jobwall_s']for b in bs)]),break_even=break_even,decision='No established practical adoption benefit for largerB alone; maintain existing B8 production pending next bounded efficiency unit',next_max1='Measure and test private CUDA graph replay of held folded forward at matched batches, with cold capture/sample/VRAM/finite parity costs; preserve model/math/K/tree/rules. This is a proposal, not authorized new221 generation.',limits=['three small sequential jobs, same48 sibling families','same resource allocation but hostwarm/cold/tail effects','linear scenarios do not establish1000 completion','short48 opening mix/length differs from old49-50 rows/game','K64 benchmark not Sigma publicK800 equalquality','no teachertruth/learning/playingstrength adoption'])
(D/'cost-target-scenarios.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(dict(NN=NN,heavy=measured,compare=result['comparison_to_two_baselines'],targets=result['targets'],break_even=break_even,thousand_minutes={n:m['scenarios']['1000']['projected_qualification_pack_Git_included_minutes']for n,m in methods.items()})))
