async function verifyModelBytes(owned){if(owned.length!==11663428)throw Error('MODEL_LENGTH');const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',owned)),x=>x.toString(16).padStart(2,'0')).join('');if(digest!=='d790dac68389f7602ff8a887a2385417d3c925fe22da7164c86e9226f943908d')throw Error('MODEL_HASH');return digest}
async function loadOrtHost(){
 const start=performance.now(),bytes=await(await fetch('/b.wasm')).arrayBuffer();const instance=(await WebAssembly.instantiate(bytes,{})).instance,e=instance.exports;
 const alive=new Set();const adopt=h=>{if(!h)throw Error('HANDLE');alive.add(h);return h};const check=h=>{if(!alive.has(h))throw Error('STALE_HANDLE');return h};
 function free(h){check(h);if(e.ort_free(h)!==1)throw Error('FREE');alive.delete(h)}
 function call(v){const b=new TextEncoder().encode(JSON.stringify(v)),h=adopt(e.ort_buffer(b.length));new Uint8Array(e.memory.buffer,e.ort_ptr(h),b.length).set(b);let out;try{out=adopt(e.ort_call(h));const a=new Uint8Array(e.memory.buffer,e.ort_ptr(out),e.ort_len(out)).slice();const r=JSON.parse(new TextDecoder().decode(a));if(!r.ok){const err=Error(r.error);err.discarded=r.discarded;throw err}return r.data}finally{free(h);if(out)free(out)}}
 const compile_ms=performance.now()-start;const owned=new Uint8Array(await(await fetch('/model.onnx')).arrayBuffer());const digest=await verifyModelBytes(owned);
 ort.env.wasm.wasmPaths=new URL('/ort/',self.location.href).href;ort.env.wasm.numThreads=1;ort.env.wasm.proxy=false;
 const t=performance.now(),model=await ort.InferenceSession.create(owned,{executionProviders:['wasm']});const load_ms=performance.now()-t;
 if(JSON.stringify(model.inputNames)!=='["input"]'||JSON.stringify(model.outputNames)!=='["policy_logits","value"]')throw Error('MODEL_SCHEMA');
 async function infer(bits){const whole_start_ms=performance.timeOrigin+performance.now();if(bits.length!==648)throw Error('FEATURE_SHAPE');const data=new Float32Array(new Uint32Array(bits).buffer);if(data.some(x=>!Number.isFinite(x)))throw Error('FEATURE_FINITE');const tensor_start_ms=performance.timeOrigin+performance.now();const tensor=new ort.Tensor('float32',data,[1,8,9,9]);const tensor_end_ms=performance.timeOrigin+performance.now();let result;const t=performance.now();try{const run_start_ms=performance.timeOrigin+performance.now();result=await model.run({input:tensor});const run_end_ms=performance.timeOrigin+performance.now();if(JSON.stringify(result.policy_logits.dims)!=='[1,136]'||JSON.stringify(result.value.dims)!=='[1,1]')throw Error('OUTPUT_SHAPE');const logits=Array.from(result.policy_logits.data),value=result.value.data[0];if(logits.some(x=>!Number.isFinite(x))||!Number.isFinite(value)||Math.abs(value)>1)throw Error('OUTPUT_FINITE_RANGE');const output_check_end_ms=performance.timeOrigin+performance.now();return {logits,value,nn_ms:performance.now()-t,spans:{whole_start_ms,tensor_start_ms,tensor_end_ms,run_start_ms,run_end_ms,output_check_end_ms}}}finally{tensor.dispose?.();if(result)for(const x of Object.values(result))x.dispose?.()}}
 function create(req){const h=adopt(call({op:'new',...req}).handle);return h}
 async function numeric(f){const raw=call({op:'raw',fixture:f});const r=await infer(raw.features_bits);const p=call({op:'raw_policy',fixture:f,logits:r.logits});return {...raw,...r,raw_prior:p.priors}}
 async function modelFaults(){const out={};for(const [name,data]of [["short",new Uint8Array([1])],["hash",(()=>{const v=owned.slice();v[0]^=1;return v})()]]){try{await verifyModelBytes(data);out[name]="UNEXPECTED_SUCCESS"}catch(e){out[name]=e.message}}return out}
 function drop(){for(const h of [...alive])free(h);return model.release()}
 return{e,call,infer,create,free,drop,numeric,modelFaults,compile_ms,load_ms,digest,version:ort.env.versions,threads:ort.env.wasm.numThreads,proxy:ort.env.wasm.proxy};
}
