 'use strict';
const has=(x,k)=>Object.prototype.hasOwnProperty.call(x,k);
function ensure(v,c){if(!v)throw Error(c)}
function object(x,c){ensure(x!==null&&typeof x==='object'&&!Array.isArray(x),c+'_TYPE');return x}
function need(x,keys,c){object(x,c);for(const k of keys)ensure(has(x,k),c+'_MISSING_'+k)}
function arr(x,n,c){ensure(Array.isArray(x)||ArrayBuffer.isView(x),c+'_TYPE');ensure(x.length===n,c+'_SHAPE');const a=Array.from(x);ensure(a.every(v=>typeof v==='number'&&Number.isFinite(v)),c+'_FINITE');return a}
function integer(v,lo,hi,c){ensure(Number.isInteger(v)&&v>=lo&&v<=hi,c);return v}
function value(v,c){ensure(typeof v==='number'&&Number.isFinite(v)&&v>=-1&&v<=1,c);return v}
function close(a,b,c){ensure(typeof a==='number'&&typeof b==='number'&&Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a-b)<=1e-4+1e-4*Math.abs(b),c)}
function equal(a,b,c){ensure(JSON.stringify(Array.from(a))===JSON.stringify(Array.from(b)),c)}
function bits(a){return Array.from(new Uint32Array(new Float32Array(a).buffer))}
function expected(f){return f.legal_actions.map(x=>x.rust209).sort((a,b)=>a-b)}
function terminalValue(f){return f.terminal.side_to_move_value}
function canonical(f,a){return f.board.turn===1?f.P2_permutation136[a.sigma136]:a.sigma136}
function rawPriors(f,logits){const ids=expected(f),map=new Map(f.legal_actions.map(a=>[a.rust209,canonical(f,a)]));if(ids.length===0)return [];const vals=ids.map(id=>logits[map.get(id)]);ensure(vals.every(Number.isFinite),'RAW_POLICY_MAPPING');const max=Math.max(...vals),w=vals.map(x=>Math.exp(x-max)),sum=w.reduce((a,b)=>a+b,0);ensure(Number.isFinite(sum)&&sum>0,'RAW_POLICY_SUM');return w.map(x=>x/sum)}
function fixtureSchema(f){need(f,['id','classification','legal_prefix','board','history_count_key','history_counts','current_key_count','legal_actions','legal_sigma136_mask','raw_features_float32','P2_permutation136','canonical_legal_indices','terminal'],'FIXTURE');ensure(typeof f.id==='string'&&f.id.length>0,'FIXTURE_ID');ensure(['legal-replay','synthetic-history-context','synthetic-total-ply-context'].includes(f.classification),'FIXTURE_CLASS');arr(f.raw_features_float32,648,'FIXTURE_FEATURE');arr(f.P2_permutation136,136,'P2');f.P2_permutation136.forEach(x=>integer(x,0,135,'P2_INDEX'));ensure(new Set(f.P2_permutation136).size===136,'P2_PERMUTATION');need(f.board,['turn','total_ply','pawns','h_anchors','v_anchors','walls_remaining'],'BOARD');integer(f.board.turn,0,1,'TURN');integer(f.board.total_ply,0,65535,'PLY');ensure(Array.isArray(f.legal_actions),'LEGAL_ACTIONS_TYPE');const r=[],s=[];
for(const a of f.legal_actions){need(a,['action','sigma136','rust209'],'ACTION');integer(a.sigma136,0,135,'SIGMA_ACTION');integer(a.rust209,0,208,'RUST_ACTION');ensure(a.action?.type==='pawn'||a.action?.type==='wall','ACTION_TYPE');r.push(a.rust209);s.push(a.sigma136)}ensure(new Set(r).size===r.length&&new Set(s).size===s.length,'ACTION_DUPLICATE');const mask=arr(f.legal_sigma136_mask,136,'MASK');mask.forEach(x=>integer(x,0,1,'MASK_BIT'));equal(mask,Array.from({length:136},(_,i)=>s.includes(i)?1:0),'MASK_MAPPING');equal(arr(f.canonical_legal_indices,s.length,'CANONICAL_LEGAL'),f.legal_actions.map(a=>canonical(f,a)),'CANONICAL_MAPPING');need(f.terminal,['winner','raw_is_drawn','raw_is_finished','effective_result','side_to_move_value'],'TERMINAL');integer(f.terminal.winner,0,2,'WINNER');ensure(typeof f.terminal.raw_is_drawn==='boolean'&&typeof f.terminal.raw_is_finished==='boolean','TERMINAL_BOOL');const winner=f.terminal.winner,ending=winner!==0||f.board.total_ply>=200||r.length===0;const effective=winner?`player${winner}-win`:ending?'draw':'ongoing';ensure(f.terminal.effective_result===effective,'TERMINAL_PRIORITY');if(ending){value(f.terminal.side_to_move_value,'TERMINAL_VALUE');ensure(f.terminal.side_to_move_value===(winner?(winner===f.board.turn+1?1:-1):0),'TERMINAL_SIDE_VALUE')}else ensure(f.terminal.side_to_move_value===null,'ONGOING_TERMINAL_NULL');ensure(Array.isArray(f.history_counts)&&typeof f.history_count_key==='string','HISTORY');return {id:f.id,classification:f.classification,feature_bits:648,output137:137,raw_legal:r.length,raw_order:'ascending Rust209; fixed Rust generator order',reference_order:'fixed Sigma action order',P2:f.board.turn===1,effective:effective,effective_terminal:ending,effective_prior_null:ending,raw_diagnostic_still_calls_NN:1}}
function referenceSchema(f,ref){fixtureSchema(f);need(ref,['id','classification','input_float32_sha256','policy_logits','value','shapes','canonical_legal_priors','terminal'],'REFERENCE');ensure(ref.id===f.id&&ref.classification===f.classification,'REFERENCE_ID');ensure(/^[0-9a-f]{64}$/.test(ref.input_float32_sha256),'REFERENCE_FEATURE_SHA');arr(ref.policy_logits,136,'REFERENCE_OUTPUT');value(ref.value,'REFERENCE_VALUE');ensure(JSON.stringify(ref.shapes)==='[[1,136],[1,1]]','REFERENCE_SHAPES');ensure(JSON.stringify(ref.terminal)===JSON.stringify(f.terminal),'REFERENCE_TERMINAL');const end=terminalValue(f)!==null;
if(end)ensure(ref.canonical_legal_priors===null,'EFFECTIVE_TERMINAL_PRIOR_NULL');else{ensure(Array.isArray(ref.canonical_legal_priors)&&ref.canonical_legal_priors.length===f.legal_actions.length,'REFERENCE_PRIOR_SHAPE');const ids=f.legal_actions.map(a=>canonical(f,a));equal(ref.canonical_legal_priors.map(a=>a.canonical136),ids,'REFERENCE_PRIOR_ORDER');const raw=rawPriors(f,ref.policy_logits),map=new Map(expected(f).map((id,i)=>[id,raw[i]]));ref.canonical_legal_priors.forEach((a,i)=>{need(a,['canonical136','prior'],'REFERENCE_PRIOR');ensure(typeof a.prior==='number'&&Number.isFinite(a.prior)&&a.prior>=0&&a.prior<=1,'REFERENCE_PRIOR_RANGE');close(a.prior,map.get(f.legal_actions[i].rust209),'REFERENCE_SOFTMAX')})}return {raw_prior_source:'raw softmax computed separately from fixed reference policy logits + Action mapping; effective prior field remains unchanged',effective_prior:ref.canonical_legal_priors===null?'null':'array',output_shape:137}}
function validate(f,r,ref,side){ensure(side==='A'||side==='B','SELECTED_BACKEND');referenceSchema(f,ref);need(r,['id','backend','features_bits','value','raw_legal','raw_prior','effective_legal'],'RAW_RESPONSE');ensure(r.id===f.id&&r.backend===side,'RESPONSE_ID_BACKEND');let logits;
if(side==='A'){need(r,['policy_logits','classification','search'],'A');ensure(!has(r,'logits'),'A_FOREIGN_LOGITS');ensure(r.classification===f.classification,'A_CLASSIFICATION');ensure(Array.isArray(r.search)&&r.search.length===0,'A_SEARCH_FORBIDDEN');logits=arr(r.policy_logits,136,'A_OUTPUT')}else{need(r,['logits','turn','terminal','nn_ms'],'B');ensure(!has(r,'policy_logits')&&!has(r,'search'),'B_FOREIGN_FIELDS');ensure(r.turn===f.board.turn&&r.terminal===terminalValue(f),'B_CONTEXT_TERMINAL');ensure(typeof r.nn_ms==='number'&&Number.isFinite(r.nn_ms)&&r.nn_ms>=0,'B_NN_MS');logits=arr(r.logits,136,'B_OUTPUT')}
const fb=arr(r.features_bits,648,'FEATURE_BITS');fb.forEach(x=>integer(x,0,4294967295,'FEATURE_UINT32'));equal(fb,bits(f.raw_features_float32),'FEATURE_BITS_PARITY');value(r.value,'STRICT_VALUE');logits.forEach((a,i)=>close(a,ref.policy_logits[i],'OUTPUT_PARITY'));close(r.value,ref.value,'VALUE_PARITY');const ids=expected(f),legal=arr(r.raw_legal,ids.length,'RAW_LEGAL');equal(legal,ids,'RAW_LEGAL_NATIVE_ORDER_SET');ensure(new Set(legal).size===legal.length,'RAW_LEGAL_DUPLICATE');const effective=terminalValue(f)!==null?[]:ids;equal(arr(r.effective_legal,effective.length,'EFFECTIVE_LEGAL'),effective,'EFFECTIVE_LEGAL_POLICY');const prior=arr(r.raw_prior,ids.length,'RAW_PRIOR');const self=rawPriors(f,logits),target=rawPriors(f,ref.policy_logits);prior.forEach((x,i)=>{ensure(x>=0&&x<=1,'RAW_PRIOR_RANGE');close(x,self[i],'ACTION_PRIOR');close(x,target[i],'RAW_REFERENCE_PRIOR')});if(ids.length)close(prior.reduce((a,b)=>a+b,0),1,'RAW_PRIOR_SUM');return {backend:side,features:648,outputs:137,priors:ids.length,strict:true,effective_terminal:terminalValue(f)!==null,raw_NN_semantics:'one raw inference even on diagnostic terminal',effective_search_NN_semantics:terminalValue(f)!==null?0:'not searched',effective_prior_schema:ref.canonical_legal_priors===null?'null':'array'}}
function effectiveTerminal(f,r){fixtureSchema(f);ensure(terminalValue(f)!==null,'NOT_TERMINAL');need(r,['id','kind','NN_calls','prior','value'],'EFFECTIVE_RESULT');ensure(r.id===f.id&&r.kind==='effective-terminal'&&r.NN_calls===0&&r.prior===null,'EFFECTIVE_TERMINAL_SCHEMA');ensure(!has(r,'logits')&&!has(r,'policy_logits'),'EFFECTIVE_NO_RAW_NN_OUTPUT');value(r.value,'EFFECTIVE_VALUE');ensure(r.value===terminalValue(f),'EFFECTIVE_VALUE_PARITY');return true}
if(typeof module!=='undefined')module.exports={equal,has,ensure,need,arr,close,bits,expected,canonical,rawPriors,fixtureSchema,referenceSchema,validate,effectiveTerminal};
