 'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto'),assert=require('assert'),N=require('./numeric.cjs');
const ROOT=path.resolve(__dirname,'../..'),OUT=ROOT+'/.artifacts/ai-sigma/continuation-20261001/SIGMA-NN-SCHEMA-COST',OLD=ROOT+'/.artifacts/ai-sigma/continuation-20261001/SIGMA-ISOLATED-NN-COST';
const write=(name,v)=>fs.writeFileSync(OUT+'/'+name+'.json',JSON.stringify(v,null,2)+'\n');
const digest=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const clone=x=>JSON.parse(JSON.stringify(x));
const fixtures=JSON.parse(fs.readFileSync(ROOT+'/.artifacts/ai-sigma/reference-fixtures/SIGMA-PARITY-PLAN/fixtures.json')).fixtures,refs=JSON.parse(fs.readFileSync(ROOT+'/.artifacts/ai-sigma/runs/SIGMA-INFERENCE-PROBE/ort-a.outputs.json')),rows=fs.readFileSync(OLD+'/calls.jsonl','utf8').trim().split('\n').map(JSON.parse),rm=new Map(refs.map(x=>[x.id,x]));
const type=x=>x===null?'null':Array.isArray(x)?'array':typeof x;
const shape=x=>({type:type(x),...(Array.isArray(x)?{length:x.length,element_types:[...new Set(x.map(type))]}:{})});
write('actual-schema-inventory',{reference28:refs.map(r=>({id:r.id,fields:Object.fromEntries(Object.entries(r).map(([k,v])=>[k,shape(v)]))})),fixture28:fixtures.map(f=>({id:f.id,fields:Object.fromEntries(Object.entries(f).map(([k,v])=>[k,shape(v)]))})),saved46:rows.map(r=>({id:r.id,backend:r.backend,ordinal:r.ordinal,fields:Object.fromEntries(Object.entries(r).map(([k,v])=>[k,shape(v)]))})),no_missing_output47_reconstruction:true});
const sandbox=vm.createContext({console});vm.runInContext(fs.readFileSync(__dirname+'/game.js','utf8')+'\n'+fs.readFileSync(__dirname+'/context.js','utf8'),sandbox);const sourceAPI=vm.runInContext('({referenceState,rustAction,terminalResult})',sandbox);
function fixedControl(f){const s=sourceAPI.referenceState(f),a=s.getLegalActions(),rust=a.map(x=>sourceAPI.rustAction(s,x));N.equal(rust.slice().sort((x,y)=>x-y),N.expected(f),'FIXED_NATIVE_ACTIONS');N.equal(Array.from(new Uint32Array(s.toNNInput().buffer)),N.bits(f.raw_features_float32),'FIXED_FEATURE_BITS');const fixed=a.map(x=>vm.runInContext('actionToIndex',sandbox)(x,9));N.equal(fixed,f.legal_actions.map(x=>x.sigma136),'FIXED_SIGMA_ORDER');N.ensure((sourceAPI.terminalResult(s)?.value??null)===f.terminal.side_to_move_value,'FIXED_TERMINAL');const buf=Buffer.from(new Float32Array(f.raw_features_float32).buffer);N.ensure(crypto.createHash('sha256').update(buf).digest('hex')===rm.get(f.id).input_float32_sha256,'FIXED_FEATURE_SHA');return {id:f.id,features648:true,Rust_order:'ascending209',Sigma_order:fixed.slice(0,6),Rust_first:rust.slice().sort((x,y)=>x-y).slice(0,6),raw_legal:rust.length,P2:f.board.turn===1}}
function mockRaw(f,ref,side){const common={id:f.id,backend:side,features_bits:N.bits(f.raw_features_float32),raw_legal:N.expected(f),effective_legal:f.terminal.side_to_move_value===null?N.expected(f):[],raw_prior:N.rawPriors(f,ref.policy_logits),value:ref.value};return side==='A'?{...common,classification:f.classification,policy_logits:[...ref.policy_logits],search:[]}:{...common,turn:f.board.turn,terminal:f.terminal.side_to_move_value,logits:[...ref.policy_logits],nn_ms:0}}
const states=[],schema28=[],mocks=[];for(const f of fixtures){states.push(fixedControl(f));schema28.push({fixture:N.fixtureSchema(f),reference:N.referenceSchema(f,rm.get(f.id))});for(const side of ['A','B'])mocks.push({id:f.id,backend:side,kind:'NN0 format mock from fixed reference values not raw inference',...N.validate(f,mockRaw(f,rm.get(f.id),side),rm.get(f.id),side)})}write('fixture-reference-preflight28',{pass:true,NN:0,states,schema28,format_mock56:mocks,raw_terminal_distinct_effective_NN0:true});
const validated=[];for(const r of rows){const f=fixtures.find(x=>x.id===r.id),ref=rm.get(r.id);validated.push({id:r.id,backend:r.backend,ordinal:r.ordinal,row_sha256:digest(r),...N.validate(f,r,ref,r.backend)})}write('saved46-validator-gate',{pass:true,NN:0,n:validated.length,A:validated.filter(x=>x.backend==='A').length,B:validated.filter(x=>x.backend==='B').length,rows:validated,old47_unsaved_not_filled:true,oldlatency36_not_measured:true});
const firstlast={};for(const b of ['A','B']){const rs=rows.filter(r=>r.backend===b);firstlast[b]=[rs[0],rs.at(-1)].map(r=>({id:r.id,backend:b,ordinal:r.ordinal,fields:Object.keys(r),output_field:b==='A'?'policy_logits':'logits',search_presence:N.has(r,'search'),gate:N.validate(fixtures.find(f=>f.id===r.id),r,rm.get(r.id),b),row_sha256:digest(r)}))}write('first-last-formats',firstlast);
const injections=[];function reject(name,fn){let error;try{fn()}catch(e){error=e.message}assert(error,'EXPECTED_REJECTION '+name);injections.push({name,rejected:true,error})}function pass(name,fn){fn();injections.push({name,passed:true})}
for(const b of ['A','B']){const f=fixtures[0],ref=rm.get(f.id),base=mockRaw(f,ref,b);for(const field of ['id','backend','features_bits','raw_legal','raw_prior','effective_legal','value',...(b==='A'?['policy_logits','search','classification']:['logits','terminal','turn','nn_ms'])])reject(b+' missing '+field,()=>{const r=clone(base);delete r[field];N.validate(f,r,ref,b)});for(const [name,mut]of [['null-features',r=>r.features_bits=null],['bits-length',r=>r.features_bits.pop()],['bits-range',r=>r.features_bits[0]=-1],['bits-change',r=>r.features_bits[0]^=1],['null-output',r=>r[b==='A'?'policy_logits':'logits']=null],['output-length',r=>r[b==='A'?'policy_logits':'logits'].pop()],['output-NaN',r=>r[b==='A'?'policy_logits':'logits'][0]=NaN],['output-Inf',r=>r[b==='A'?'policy_logits':'logits'][0]=Infinity],['output-null',r=>r[b==='A'?'policy_logits':'logits'][0]=null],['value-null',r=>r.value=null],['value-bool',r=>r.value=true],['value-NaN',r=>r.value=NaN],['value-upper',r=>r.value=1.0000001],['value-lower',r=>r.value=-1.0000001],['prior-null',r=>r.raw_prior=null],['prior-null-element',r=>r.raw_prior[0]=null],['prior-swap',r=>[r.raw_prior[0],r.raw_prior[1]]=[r.raw_prior[1],r.raw_prior[0]]],['legal-missing',r=>r.raw_legal.pop()],['legal-duplicate',r=>r.raw_legal[0]=r.raw_legal[1]],['legal-order',r=>[r.raw_legal[0],r.raw_legal[1]]=[r.raw_legal[1],r.raw_legal[0]]],['foreignID',r=>r.id='foreign'],['foreignBackend',r=>r.backend=b==='A'?'B':'A'],['foreignformat',r=>r[b==='A'?'logits':'policy_logits']=[...ref.policy_logits]]])reject(b+' '+name,()=>{const r=clone(base);mut(r);N.validate(f,r,ref,b)});
for(const v of [-1,1])pass(b+' strictvalue '+v,()=>{const r=clone(base),rr=clone(ref);r.value=v;rr.value=v;N.validate(f,r,rr,b)});const p2=fixtures.find(x=>x.id==='asym-hv-p2');pass(b+' P2 VM array',()=>{const r=mockRaw(p2,rm.get(p2.id),b);r.features_bits=vm.runInNewContext(JSON.stringify(r.features_bits));r[b==='A'?'policy_logits':'logits']=new Float32Array(r[b==='A'?'policy_logits':'logits']);N.validate(p2,r,rm.get(p2.id),b)});}
for(const f of fixtures.filter(f=>f.terminal.side_to_move_value!==null)){const ref=rm.get(f.id);pass(f.id+' terminal-null-reference',()=>N.referenceSchema(f,ref));reject(f.id+' effective-reference-empty-not-null',()=>N.referenceSchema(f,{...ref,canonical_legal_priors:[]}));const eff={id:f.id,kind:'effective-terminal',NN_calls:0,prior:null,value:f.terminal.side_to_move_value};pass(f.id+' effectiveNN0',()=>N.effectiveTerminal(f,eff));reject(f.id+' effectiveNN1',()=>N.effectiveTerminal(f,{...eff,NN_calls:1}));reject(f.id+' effectiveprior[]',()=>N.effectiveTerminal(f,{...eff,prior:[]}));}
const ongoing=fixtures[0],or=rm.get(ongoing.id);reject('ongoing-reference-null',()=>N.referenceSchema(ongoing,{...or,canonical_legal_priors:null}));for(const field of ['id','policy_logits','value','shapes','canonical_legal_priors','terminal','input_float32_sha256'])reject('reference missing '+field,()=>{const r=clone(or);delete r[field];N.referenceSchema(ongoing,r)});reject('fixture P2badperm',()=>{const f=clone(fixtures[1]);f.P2_permutation136[0]=f.P2_permutation136[1];N.fixtureSchema(f)});reject('fixture featuresnull',()=>N.fixtureSchema({...ongoing,raw_features_float32:null}));reject('fixed control order mutation',()=>{const f=clone(ongoing);[f.legal_actions[0],f.legal_actions[1]]=[f.legal_actions[1],f.legal_actions[0]];fixedControl(f)});write('same-validator-boundaries',{pass:true,NN:0,cases:injections.length,injections,mocks_not_inference_success:true});console.log(JSON.stringify({pass:true,preflight28:schema28.length,saved46:validated.length,format_mocks:mocks.length,boundaries:injections.length,NN:0}));
