'use strict';
function assert(condition) { if (!condition) throw Error('NUMERIC_ASSERT'); }
assert.equal=(a,b)=>assert(a===b);
const J={rustAction,actionToIndex};
const V={array(v,len,{bits=false,range=Infinity}={}) { assert(v&&v.length===len); const a=Array.from(v); for(const x of a) assert(typeof x==='number'&&Number.isFinite(x)&&Math.abs(x)<=range&&(!bits||(Number.isInteger(x)&&x>=0&&x<=4294967295))); return a; },equal(a,b,options={}) { const x=this.array(a,b.length,options),y=this.array(b,b.length,options); x.forEach((v,i)=>assert(v===y[i])); }};

const flip=[1,0,2,3,6,7,4,5];function canonical(k,p1){return p1?k:k<8?flip[k]:8+Math.floor((k-8)/64)*64+(7-Math.floor(((k-8)%64)/8))*8+(k-8)%8;}
function expected(s){const actions=Array.from(s.getLegalActions()),reference=actions.map(a=>J.rustAction(s,a));assert.equal(new Set(reference).size,reference.length);const candidate=reference.slice().sort((a,b)=>a-b);const indices=new Map(actions.map(a=>[J.rustAction(s,a),canonical(J.actionToIndex(a,9),s.isPlayer1Turn())]));return {candidate,reference,indices};}
function check({engine,state:s,numeric:n,cp,reference:ref}){assert(['candidate','reference'].includes(engine));const features=s.toNNInput(),bits=Array.from(new Uint32Array(features.buffer,features.byteOffset,features.length));assert.equal(bits.length,648);V.equal(n.features_bits,bits,{bits:true});const logits=V.array(n.policy_logits,136),value=V.array([n.value],1,{range:1})[0];if(ref){V.array(ref.policy_logits,136);V.array([ref.value],1,{range:1});for(const[a,r]of [...logits.map((a,i)=>[a,ref.policy_logits[i]]),[value,ref.value]])assert(Math.abs(a-r)<=1e-4+1e-4*Math.abs(r));}
 const e=expected(s);let priors=0;if(cp){assert(Array.isArray(cp.root_edges));const edges=cp.root_edges.map(x=>V.array(x,4));for(const x of edges){assert(Number.isInteger(x[0])&&x[0]>=0&&x[0]<209&&x[1]>=0&&Number.isInteger(x[2])&&x[2]>=0);}const ids=edges.map(x=>x[0]);assert.equal(new Set(ids).size,ids.length);assert.equal(JSON.stringify(ids.slice().sort((a,b)=>a-b)),JSON.stringify(e.candidate));V.equal(ids,e[engine]);const max=Math.max(...e.candidate.map(id=>logits[e.indices.get(id)])),weights=new Map(e.candidate.map(id=>[id,Math.exp(logits[e.indices.get(id)]-max)])),sum=[...weights.values()].reduce((a,b)=>a+b,0);assert(Number.isFinite(sum)&&sum>0);for(const [id,p]of edges){const want=weights.get(id)/sum;assert(Math.abs(p-want)<=1e-4+1e-4*Math.abs(want));priors++;}}
 return {features648_exact:true,NN137_finite_strict:true,fixed_reference:!!ref,prior_checked:!!cp,priors,engine_specific_order:cp?true:null,legal_set_exact:cp?true:null,P2canonical:!s.isPlayer1Turn(),missing_public_cp:!cp};}
globalThis.BrowserNumeric={canonical,expected,check};
