import json,statistics,hashlib,datetime
from pathlib import Path
R=Path(__file__).resolve().parents[2];A=R/'.artifacts/ai-sigma/resume-20261003/NATIVE-RUNTIME-READY';D=R/'research-data/ai-sigma/170-native-runtime-ready';load=lambda p:json.loads(p.read_text());stop=load(D/'science-stop.json');data={m:load(A/'runs'/('native170-'+m+'-r1')/'result.json') for m in ['solo','parallel']}
def stat(xs):
 xs=list(xs);return{'n':len(xs),'mean':statistics.mean(xs) if xs else None,'median':statistics.median(xs) if xs else None,'min':min(xs) if xs else None,'max':max(xs) if xs else None,'sum':sum(xs)}
modes={}
for mode,z in data.items():
 rows=z['rows'];percore=[]
 for core in sorted({x['core'] for x in rows}):
  for e in ['candidate','reference']:
   x=[r for r in rows if r['core']==core and r['engine']==e];steady=[r for r in x if r['request_index']%4>=2]
   percore.append({'core':core,'engine':e,'requests':len(x),'started_NN':sum(r['started_NN'] for r in x),'returned_NN':sum(r['returned_NN'] for r in x),'discarded_NN':sum(r['discarded_NN'] for r in x),'adopted_NN':sum(r['public_cp']['cp']['nn_calls'] for r in x),'completed_K':stat(r['completed_K'] for r in x),'adopted_K':stat(r['public_cp']['cp']['simulations'] for r in x),'firstCP_ms':stat(r['firstCP_ms'] for r in x),'steady_API_mean_of_request_means_ms':stat(r['API_steady_mean_ms'] for r in steady),'API_total_ms':stat(r['API_total_ms'] for r in x),'pipe_total_ms':stat(r['NN_pipe_total_ms'] for r in x),'cleanup_ms':stat(r['cleanup_after_public_ms'] for r in x),'terminal_noNN':sum(r['terminal_noNN'] for r in x)})
 modes[mode]={**stop['phases'][mode],'basic_runtime_supported':z['basic_runtime_supported'],'percore_engine':percore,'root_parity':z['root_parity'],'actual_admit_ms':stat(r['public_cp']['admit_ms'] for r in rows),'public_ms':stat(r['public_actual_ms'] for r in rows),'phase_start_offsets_ms':stat(r['phase_start_offset_ms'] for r in rows),'root_preparation_outside_t0_ms':stat(r['root_preparation_outside_t0_ms'] for r in rows),'init_warm':[{ 'core':a['core'],'engines':{e:{'session_init_ms':v['info']['init_ms'],'warm_pipe_ms':v['startup']['wall_ms'],'warm_API_ms':v['startup']['API_ms'],'affinity':v['info']['affinity'],'provider':v['info']['providers'],'intra':v['info']['intra'],'inter':v['info']['inter']} for e,v in a['init'].items()}} for a in z['init']]}
comparisons=[]
for e in ['candidate','reference']:
 for f in ['initial-p1','asym-hv-p2']:
  solo=next(x for x in data['solo']['rows'] if x['engine']==e and x['fixture']==f and x['request_index']%4>=2);parallel=next(x for x in data['parallel']['rows'] if x['core']==2 and x['engine']==e and x['fixture']==f and x['request_index']%4>=2);comparisons.append({'anchor_core':2,'engine':e,'fixture':f,'solo_adopted_K':solo['public_cp']['cp']['simulations'],'parallel_adopted_K':parallel['public_cp']['cp']['simulations'],'solo_adopted_NN':solo['public_cp']['cp']['nn_calls'],'parallel_adopted_NN':parallel['public_cp']['cp']['nn_calls'],'solo_firstCP_ms':solo['firstCP_ms'],'parallel_firstCP_ms':parallel['firstCP_ms'],'NN137_bits_exact':solo['NN_bits']==parallel['NN_bits']})
allrows=data['solo']['rows']+data['parallel']['rows'];crossroots=[]
for f in ['initial-p1','asym-hv-p2']:
 xs=[x for x in allrows if x['fixture']==f];crossroots.append({'fixture':f,'requests':len(xs),'all_modes_cores_root648_NN137bits_exact':all(x['features_bits']==xs[0]['features_bits'] and x['NN_bits']==xs[0]['NN_bits'] for x in xs)})
ratio_phase=4*modes['solo']['phase_work_s']/modes['parallel']['phase_work_s'];ratio_outer=4*modes['solo']['outer_wall_s']/modes['parallel']['outer_wall_s'];cost={m:sum((datetime.datetime.fromisoformat(q['end'])-datetime.datetime.fromisoformat(q['start'])).total_seconds() for q in [load(p) for p in (A/'runs').glob('*.process.json')] if q['phase']==m) for m in ['mock','solo','parallel']}
out={'issue':'quoridor-4lc.170','planned':40,'complete':40,'unknown':0,'startup_separate':10,'hand_NN':2491,'NN_quota_guard_hit':False,'mode_results':modes,'core2_steady_comparisons':comparisons,'cross_mode_root_exact':crossroots,'reference_parallel_batch_factor_phase':ratio_phase,'reference_parallel_batch_factor_outer':ratio_outer,'not_WDL_speed_or_causal_NN_ratio':True,'measured_wall_seconds':cost,'heavy_total_s':cost['solo']+cost['parallel'],'pending_return_discard_coverage':{'observed':32,'not_observed':8,'no_repetition_or_supplement':True},'realORT_terminal_only_cancel_coverage':'not established by these2roots;165NN0 artificial result separate','counter_definition':{'started_NN':'actual infer count before ORT ask','returned_NN':'completed infer spans including discarded returns','discarded_NN':'return after observed stop before backup; not reused','completed_K':'final worker backup count, may exceed adopted cache; not cutoff-valid alone','adopted_K_NN':'immutable cache certified after actual validation/clone/tentative assign <=402','zero':'source held process result after awaited infer and cancel/free; observed main receipt/gate','kernel_CPU':'unknown'},'formal_ready':False,'new_game_teacher_learning_GPU_build':0,'next_max1':'select single4arena native mode as candidate for separately budgeted minimal teacher generation and export with lineage; no automatic runtime experiment chain or formal1200games','unknown_costs':['all-team/unwrapped staticCPU aggregate','exactkernelCPU attribution','futureWDL multiplier','sampler/fullteacher pipeline expense']}
(D/'results.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({k:out[k] for k in ['reference_parallel_batch_factor_phase','reference_parallel_batch_factor_outer','heavy_total_s','planned','complete','hand_NN','startup_separate']}));print(comparisons)
