'use strict';const fs=require('fs'),assert=require('assert'),{ROOT,A,D,now,save,runControlled}=require('./common.cjs'),{Engine}=require('./controller.cjs'),{createReference}=require('../ai-sigma-native-baseline/reference.cjs'),{commitCP}=require('../ai-sigma-native-baseline/clock.cjs');
const c=JSON.parse(fs.readFileSync(process.argv[2])),fixed=JSON.parse(fs.readFileSync(D+'/inputs.json')),{r}=createReference(),sleep=ms=>new Promise(resolve=>setTimeout(resolve,Math.max(0,ms)));
async function request(arena,spec,check,barrier){check();const f=fixed.fixtures.find(x=>x.id===spec.fixture);const prep=now(),state=r.fromPrefix(f.legal_prefix),root=r.portState(state),legal=root.legal,legalMs=now()-prep,e=arena.engines[spec.engine],gen=spec.index+1,slot={cache:null};let finalized=false,seen=0,accepted=0,late=0,schema=0,first=null,out=null,error=null,receiveResult=null,pending=0;
 const t0=now();const work=e.request({op:'search',fixture_id:f.id,legal_prefix:f.legal_prefix,generation:gen,K:1000000,NN_limit:204,trace:false,watchdog_ms:10000},(x,receive)=>{seen++;if(first===null)first=receive-t0;const cp=x.cp;let v;if(!Number.isFinite(cp.root_mean)||!Number.isFinite(cp.root_valueSum)||!Number.isInteger(cp.nn_calls)||cp.nn_calls<1||!Array.isArray(cp.root_edges))v={accepted:false,code:'ILLEGAL_OR_SCHEMA'};else v=commitCP({slot,cp,receive,t0,cutoff:402,generation:gen,legal,finalized,clock:now});if(v.accepted)accepted++;else if(['LATE_CP','AFTER_PUBLIC'].includes(v.code))late++;else schema++;}).then(x=>{receiveResult=x.controller_receive_ms;out=x.data;if(out?.primary)error=out.primary.message},e=>{error=e.message});
 await sleep(t0+402-now());const cut=now()-t0;e.stopCurrent();await sleep(t0+411-now());const pub=now();finalized=true;const publicCP=pub-t0<=500?slot.cache:null;await work;const zeroObserved=now();check();
 const bitsOK=JSON.stringify(out?.root_state)===JSON.stringify(root),NNbits=out?.first_NN?.NN_bits??null,features=out?.first_NN?.features_bits??null;const returned=out?.spans?.length??null;
 const row={arena:arena.id,core:arena.core,request_index:spec.index,engine:spec.engine,fixture:f.id,generation:gen,controller_t0_ms:t0,phase_barrier_ms:barrier,phase_start_offset_ms:t0-barrier,root_preparation_outside_t0_ms:legalMs,root_state:root,root_state_exact:bitsOK,features_bits:features,NN_bits:NNbits,firstCP_ms:first,cut_actual_ms:cut,public_actual_ms:pub-t0,public_cp:publicCP,CP_received:seen,CP_admitted:accepted,CP_late_discarded:late,CP_schema_rejected:schema,result_IPC_receipt_ms:receiveResult===null?null:receiveResult-t0,quiescent_gate_observed_ms:zeroObserved-t0,cleanup_after_public_ms:zeroObserved-pub,started_NN:out?.NN_calls??null,returned_NN:returned,discarded_NN:out?.discardedNN??null,integrated_NN:out?out.NN_calls-out.discardedNN:null,pending_cancel_observed:!!out?.discardedNN,completed_K:out?.completed??null,terminal_noNN:out?.terminal_noNN??null,zero:out?.zero??null,error,API_first_ms:out?.spans?.[0]?.API_ms??null,API_total_ms:out?.spans?.reduce((s,x)=>s+x.API_ms,0)??null,NN_pipe_total_ms:out?.spans?.reduce((s,x)=>s+x.pipe_ms,0)??null,API_steady_mean_ms:out?.spans?.length>1?out.spans.slice(1).reduce((s,x)=>s+x.API_ms,0)/(out.spans.length-1):null,realORT:true,NN_limit:204};
 row.status=error==='NN_BUDGET'?'NN_BUDGET':error?'ENGINE_OR_INFRA_UNKNOWN':!bitsOK?'ROOT_INPUT_MISMATCH':!publicCP?'FIRSTNONE_OR_PUBLIC_LATE':!(out?.zero&&out.zero.activeNN===0&&out.zero.handles===0&&!out.zero.active)?'QUIESCENCE_UNKNOWN':'COMPLETE';row.adoption_actual_completion_observed=!!publicCP&&publicCP.admit_ms<=402;row.public_legal_observed=!!publicCP&&legal.includes(publicCP.cp.action);row.return_zero_observed=out?.zero?.activeNN===0&&out.zero.handles===0&&!out.zero.active;row.pending_at_public_exact='unknown';row.uncalibrated_crossprocess_epoch_not_used=true;
 return row;
}
runControlled(c,async check=>{const arenas=[],rows=[],closed=[];let primary=null;const start=now();
 try{
  // All held engine/session initializations complete before the group barrier.
  await Promise.all(c.mode.cores.map(async core=>{const a={id:core,core,engines:{},init:{}};arenas.push(a);for(const engine of ['candidate','reference']){check();a.engines[engine]=new Engine(engine,core);a.init[engine]=await a.engines[engine].init(false);const i=a.init[engine].info;assert.equal(i.version,'1.30.0');assert.deepStrictEqual(i.providers,['CPUExecutionProvider']);assert.equal(i.intra,1);assert.equal(i.inter,1);assert.equal(i.sequential,true);assert.deepStrictEqual(i.affinity,[core]);check();}}));arenas.sort((a,b)=>a.core-b.core);
  const group=now();
  for(const spec of fixed.requests){check();const barrier=now(),batch=await Promise.all(arenas.map(a=>request(a,spec,check,barrier)));rows.push(...batch);save(c.job_out+'/progress.json',{rows,group_start_ms:group});if(batch.some(x=>x.status!=='COMPLETE')){primary={code:'REQUEST_UNSETTLED',statuses:batch.map(x=>x.status)};break;}}
 }catch(e){primary={code:'CONTROL_OR_INFRA',message:e.message,stack:e.stack};}
 finally{for(const a of arenas)for(const [engine,e]of Object.entries(a.engines)){e.stopCurrent();try{closed.push({arena:a.id,engine,...await e.close()})}catch(error){closed.push({arena:a.id,engine,error:error.message})}}}
 const planned=c.mode.cores.length*8;for(const core of c.mode.cores)for(const spec of fixed.requests)if(!rows.some(x=>x.core===core&&x.request_index===spec.index))rows.push({arena:core,core,request_index:spec.index,engine:spec.engine,fixture:spec.fixture,status:'NOT_STARTED',started_NN:0});
 const roots=[];for(const core of c.mode.cores)for(const f of fixed.fixtures){const xs=rows.filter(x=>x.core===core&&x.fixture===f.id&&x.status==='COMPLETE');roots.push({core,fixture:f.id,n:xs.length,root_features648_NN137bits_exact:xs.length===4&&xs.every(x=>JSON.stringify(x.features_bits)===JSON.stringify(xs[0].features_bits)&&JSON.stringify(x.NN_bits)===JSON.stringify(xs[0].NN_bits))});}
 const next=[];for(const core of c.mode.cores){const xs=rows.filter(x=>x.core===core&&x.status==='COMPLETE').sort((a,b)=>a.request_index-b.request_index);for(let i=1;i<xs.length;i++)next.push(xs[i].controller_t0_ms-(xs[i-1].controller_t0_ms+xs[i-1].quiescent_gate_observed_ms));}
 const result={issue:c.issue,run:c.run_id,mode:c.kind,planned,rows,root_parity:roots,init:arenas.map(a=>({core:a.core,init:a.init})),closed,primary,hand_NN:rows.reduce((s,x)=>s+(x.started_NN??0),0),startup_NN:arenas.reduce((s,a)=>s+Object.values(a.init).reduce((s,x)=>s+(x.startup?.count??0),0),0),next_actualt0_gaps_ms:next,elapsed_ms:now()-start,clock:'single controller monotonic; actualend aftervalidate/clone/tentativecache;402rollback/411planned/500public; causecleanup before nextt0',pending_cancel_coverage:rows.filter(x=>x.pending_cancel_observed).length,formal_ready:false,kernel_CPU_exact_attribution:false};
 result.basic_runtime_supported=!primary&&rows.length===planned&&rows.every(x=>x.status==='COMPLETE'&&x.adoption_actual_completion_observed&&x.public_legal_observed&&x.return_zero_observed)&&roots.every(x=>x.root_features648_NN137bits_exact)&&next.every(x=>x>=0)&&closed.every(x=>!x.error&&x.exit.code===0);save(c.job_out+'/result.json',result);return{planned,hand_NN:result.hand_NN,startup:result.startup_NN,basic_runtime_supported:result.basic_runtime_supported};
}).catch(e=>{console.error(e.stack);process.exitCode=1});
