'use strict';
const equal=(a,b,label)=>{if(JSON.stringify(a)!==JSON.stringify(b))throw Error('PARITY:'+label)};
const arr=x=>Array.from(x), bits=x=>arr(new Uint32Array(x.buffer,x.byteOffset,x.length));
const hist=s=>[...s.position_history].sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:0);
function fullkey(s){return JSON.stringify({p:[s.player1pos,s.player2pos],remaining:[s.walls_p1,s.walls_p2],h:[...s.hwall_anchors].sort(),v:[...s.vwall_anchors].sort(),side:s.getCurrentPlayer(),ply:s.depth,history:hist(s),rules:RULE_SHA,geometry:9,evaluator:'unimplemented313-v1'});}
function full313(s){let f=new Uint8Array(313);f[s.player1pos[1]*9+s.player1pos[0]]=1;f[81+s.player2pos[1]*9+s.player2pos[0]]=1;for(let k of s.hwall_anchors){let [x,y]=k.split(',').map(Number);f[162+y*8+x]=1;}for(let k of s.vwall_anchors){let[x,y]=k.split(',').map(Number);f[226+y*8+x]=1;}f[290+s.walls_p1]=1;f[301+s.walls_p2]=1;f[312]=s.getCurrentPlayer()===2?1:0;return f;}
function delta313(p,s,f){let g=f.slice(),changed=[];function set(i,v){if(g[i]!==v){changed.push([i,g[i],v]);g[i]=v;}}for(let [old,nw,o] of [[p.player1pos,s.player1pos,0],[p.player2pos,s.player2pos,81]]){if(old[0]!==nw[0]||old[1]!==nw[1]){set(o+old[1]*9+old[0],0);set(o+nw[1]*9+nw[0],1);}}for(let [old,nw,o] of [[p.hwall_anchors,s.hwall_anchors,162],[p.vwall_anchors,s.vwall_anchors,226]]){for(let k of nw)if(!old.has(k)){let[x,y]=k.split(',').map(Number);set(o+y*8+x,1);}}for(let[old,nw,o]of[[p.walls_p1,s.walls_p1,290],[p.walls_p2,s.walls_p2,301]])if(old!==nw){set(o+old,0);set(o+nw,1);}set(312,s.getCurrentPlayer()===2?1:0);return {f:g,changed};}
function mapkey(s){return RULE_SHA+'|9|goals8,0|'+arr(s.hwalls).join('')+'|'+arr(s.vwalls).join('');}
let METRICS=null;const rawGrid=State._bfsDistGrid,rawBFS=State.prototype.BFS;
State._bfsDistGrid=function(...a){if(METRICS)METRICS.BFS_map_calls++;return rawGrid(...a)};
State.prototype.BFS=function(...a){if(METRICS)METRICS.reachability_calls++;return rawBFS.apply(this,a)};
function maps(s){let t=performance.now(),v=[State._bfsDistGrid(s.hwalls,s.vwalls,8,9),State._bfsDistGrid(s.hwalls,s.vwalls,0,9)];if(METRICS)METRICS.components_ms.map_BFS=(METRICS.components_ms.map_BFS||0)+performance.now()-t;return v;}
class GoalCache{constructor(){this.m=new Map();this.hits=0;this.misses=0;this.evictions=0;this.max=0;}get(s){let t=performance.now(),k=mapkey(s);if(METRICS)METRICS.components_ms.map_key=(METRICS.components_ms.map_key||0)+performance.now()-t;t=performance.now();let hit=this.m.has(k);if(METRICS)METRICS.components_ms.cache_lookup=(METRICS.components_ms.cache_lookup||0)+performance.now()-t;if(hit){let v=this.m.get(k);this.m.delete(k);this.m.set(k,v);this.hits++;return v;}this.misses++;let v=maps(s);this.m.set(k,v);if(this.m.size>32){this.m.delete(this.m.keys().next().value);this.evictions++;}this.max=Math.max(this.max,this.m.size);return v;}}
function distances(s,m){return [m[0][s.player1pos[1]*9+s.player1pos[0]],m[1][s.player2pos[1]*9+s.player2pos[0]]];}
function snapshot(s){return {key:fullkey(s),features:arr(full313(s)),legal:s.getLegalActions(),terminal:terminalResult(s),walls:[arr(s.hwalls),arr(s.vwalls)]};}
function replay(input){let f=input.fixture,s=fromPrefix(f.legal_prefix),n=input.measured_root;equal(s._positionKey(),f.history_count_key,f.id+' key');equal(hist(s),[...f.history_counts].sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:0),f.id+' history');equal(s.depth,f.board.total_ply,f.id+' ply');equal(s._positionKey(),n.key,f.id+' measuredkey');equal(hist(s),[...n.history].sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:0),f.id+' measuredhistory');equal(bits(s.toNNInput()),n.features_bits,f.id+' features648');if(f.board.pawns){equal([s.player1pos,s.player2pos],f.board.pawns,f.id+' pawns');equal([s.walls_p1,s.walls_p2],f.board.walls_remaining,f.id+' remaining');}if(n.ply!==s.depth||n.turn!==s.getCurrentPlayer()-1)throw Error('ROOTSIDE');if(terminalResult(s))throw Error('TERMINALINPUT');return s;}
function plan(inputs){return inputs.map((input,index)=>{let s=replay(input),legal=s.getLegalActions();return {id:input.fixture.id,index,order:index%2?'BA':'AB',actions:[...legal.filter(a=>a.type==='pawn').slice(0,8),...legal.filter(a=>a.type==='wall').slice(0,8)],replayed:{pawns:[s.player1pos,s.player2pos],remaining:[s.walls_p1,s.walls_p2],side:s.getCurrentPlayer(),ply:s.depth,key:s._positionKey(),history:hist(s),features648:bits(s.toNNInput()),fullkey:fullkey(s)},legal_count:legal.length};});}
function traversal(input,p,variant,cache,verify){const metric={BFS_map_calls:0,reachability_calls:0,components_ms:{prepare:0,legal:0,make:0,map:0,feature:0,key:0,terminal:0,unmake:0},branches:0,changed_entries:0,max_changed:0,full_entries_written:0,parity_rows:[]};METRICS=metric;const start=performance.now();const timed=(k,fn)=>{let t=performance.now(),v=fn();metric.components_ms[k]+=performance.now()-t;return v;};let root=timed('prepare',()=>fromPrefix(input.fixture.legal_prefix));timed('legal',()=>root.getLegalActions());let rf=timed('feature',()=>full313(root));let rm=timed('map',()=>variant==='A'?maps(root):cache.get(root));metric.full_entries_written+=313;const parentKey=timed('key',()=>fullkey(root));const original=verify?snapshot(root):null;let state=root,features=rf,handle=rm;
for(let action of p.actions){let saved={state,features,handle};let child=timed('make',()=>state.next(action));timed('legal',()=>child.getLegalActions());let cm=timed('map',()=>variant==='A'?maps(child):cache.get(child));let df=timed('feature',()=>variant==='A'?{f:full313(child),changed:null}:delta313(state,child,features));let ck=timed('key',()=>fullkey(child));let term=timed('terminal',()=>terminalResult(child));state=child;features=df.f;handle=cm;if(variant==='A')metric.full_entries_written+=313;const ds=timed('distance_lookup',()=>distances(child,cm));if(ds.some(x=>x>=1000000||x<0))throw Error('UNREACHABLE');if(df.changed){metric.changed_entries+=df.changed.length;metric.max_changed=Math.max(metric.max_changed,df.changed.length);if(df.changed.length>4)throw Error('DELTA_CAP');}
if(verify){equal(arr(features),arr(full313(child)),'313');let unc=maps(child);equal(cm.map(arr),unc.map(arr),'maps81');equal(ds,distances(child,unc),'distance2');equal(child.getLegalActions(),root.next(action).getLegalActions(),'legalorder');equal(ck,fullkey(root.next(action)),'context');equal(term,terminalResult(root.next(action)),'terminal');metric.parity_rows.push({action,child_key:ck,side:child.getCurrentPlayer(),ply:child.depth,distances:ds,maps:cm.map(arr),features313:arr(features),legal:child.getLegalActions(),terminal:term,changed:df.changed});if(action.type==='pawn'&&variant==='B'&&cm!==rm)throw Error('PAWN_MAP_NOT_REUSED');}
timed('unmake',()=>{state=saved.state;features=saved.features;handle=saved.handle;if(fullkey(state)!==parentKey)throw Error('UNMAKEKEY');});if(verify){equal(snapshot(state),original,'restore');equal(arr(features),arr(rf),'restore313');if(handle!==rm)throw Error('RESTORE_HANDLE');}metric.branches++;}
metric.total_ms=performance.now()-start;metric.cache=variant==='B'?{hits:cache.hits,misses:cache.misses,evictions:cache.evictions,max_pairs:cache.max,current_pairs:cache.m.size,numeric_payload_bytes:cache.m.size*2*81*4,object_overhead_bytes:null}:null;METRICS=null;return metric;}
function fixtures(){const checks=[];function ok(name,fn){fn();checks.push(name);}let initial=new State({boardsize:9,walls_p1:10,walls_p2:10});let c=new GoalCache(),h=c.get(initial);ok('pawn-side-history-map-reuse-TT-context-separate',()=>{let s=initial.next(initial.getLegalActions().find(a=>a.type==='pawn'));if(c.get(s)!==h||fullkey(s)===fullkey(initial))throw Error('REUSE');let t=s.copy();t.depth=200;t.position_history=new Map([['synthetic',3]]);if(c.get(t)!==h||fullkey(t)===fullkey(s)||!terminalResult(t))throw Error('CONTEXT');});ok('third-repetition-action-exclusion-same-map-different-legal',()=>{let a=initial.getLegalActions().find(x=>x.type==='pawn'),child=initial.next(a),t=initial.copy();t.position_history.set(child._positionKey(),2);if(t.getLegalActions().some(x=>sameAction(x,a)))throw Error('REPEAT_NOT_EXCLUDED');if(c.get(t)!==h||fullkey(t)===fullkey(initial))throw Error('HISTORY_ALIAS');});ok('H-V-invalidation-delta-restore',()=>{for(let o of ['h','v']){let a=initial.getLegalActions().find(a=>a.type==='wall'&&a.orientation===o),s=initial.next(a);if(c.get(s)===h)throw Error('INVALIDATION');equal(arr(delta313(initial,s,full313(initial)).f),arr(full313(s)),'wall313');if(c.get(initial)!==h)throw Error('PARENT');}});ok('P2-jump-diagonal',()=>{let s=new State({boardsize:9,depth:1,player1pos:[4,4],player2pos:[4,5],walls_p1:10,walls_p2:10});let legal=s.getLegalActions(),jump=legal.find(a=>a.type==='pawn'&&a.direction[1]===-1&&a.direction[0]===0);if(!jump||s.next(jump).player2pos[1]!==3)throw Error('JUMP');let blocked=new State({boardsize:9,depth:1,player1pos:[4,0],player2pos:[4,1],walls_p1:10,walls_p2:10});if(!blocked.getLegalActions().some(a=>a.type==='pawn'&&a.direction[0]!==0&&a.direction[1]===-1))throw Error('DIAGONAL');});ok('goal-before200draw',()=>{let s=new State({boardsize:9,depth:200,player1pos:[4,8],walls_p1:10,walls_p2:10});if(terminalResult(s).winner!==1)throw Error('GOAL');});ok('capacity32-immutable-live-parent',()=>{let e=new GoalCache(),parent=e.get(initial),copy=parent.map(arr);for(let a of initial.getLegalActions().filter(a=>a.type==='wall').slice(0,40))e.get(initial.next(a));if(e.max!==32||e.evictions<1||e.m.size>32)throw Error('CAPACITY');equal(parent.map(arr),copy,'evictedlivehandle');});return {classification:'artificial NN0 boundaries, not scientific history/teacher',checks};}
function measure(inputs,p){let out=[];for(let row of p){let input=inputs[row.index],correct={},warm={},science={};for(let v of row.order){let cache=new GoalCache();correct[v]=traversal(input,row,v,cache,true);warm[v]=traversal(input,row,v,cache,false);let totals={components_ms:{},BFS_map_calls:0,reachability_calls:0,branches:0,changed_entries:0,max_changed:0,full_entries_written:0};let start=performance.now();for(let rep=0;rep<64;rep++){let m=traversal(input,row,v,cache,false);for(let[k,x]of Object.entries(m.components_ms))totals.components_ms[k]=(totals.components_ms[k]||0)+x;for(let k of ['BFS_map_calls','reachability_calls','branches','changed_entries','full_entries_written'])totals[k]+=m[k];totals.max_changed=Math.max(totals.max_changed,m.max_changed);}totals.total_ms=performance.now()-start;totals.cache=v==='B'?{hits:cache.hits,misses:cache.misses,evictions:cache.evictions,max_pairs:cache.max,current_pairs:cache.m.size,payload_bytes:cache.m.size*648,object_overhead_bytes:null}:null;science[v]=totals;}out.push({id:row.id,order:row.order,actions:row.actions.length,correctness:correct,warm,repeat64:science,B_less_A:science.B.total_ms<science.A.total_ms});}return {all_parity:true,inputs:out,all_B_less_A:out.every(x=>x.B_less_A),NN:0,game:0,clock:'browser performance.now',JS_cost_not_Wasm_or_NNUE_throughput:true};}
