'use strict';const fs=require('fs'),path=require('path'),assert=require('assert/strict'),A=require('./arena.cjs'),N=require('../ai-sigma-actual-boundary-repair/numeric-order.cjs');
const records=p=>fs.existsSync(p)?fs.readFileSync(p,'utf8').trim().split('\n').filter(Boolean).map(JSON.parse):[];
const read=p=>JSON.parse(fs.readFileSync(p));const median=a=>{if(!a.length)return null;const x=a.slice().sort((a,b)=>a-b);return x.length%2?x[(x.length-1)/2]:(x[x.length/2-1]+x[x.length/2])/2};
function main(){const runs=process.argv.slice(2),refs=read(A.ROOT+'/.artifacts/ai-sigma/runs/SIGMA-INFERENCE-PROBE/ort-a.outputs.json'),outputs=[];let features=0,NN=0,priors=0;
 for(const run of runs){const dir=A.OUT+'/'+run,summary=read(dir+'/summary.json'),publics=records(dir+'/public.jsonl'),turns=records(dir+'/turns.jsonl'),moves=records(dir+'/moves.jsonl');assert.equal(publics.length,turns.length);let priorACK=-Infinity;const byEngine={};
  for(let i=0;i<turns.length;i++){const t=turns[i],p=publics[i],r=p.response,id=p.identity;assert.equal(t.request_id,id.request_id);assert(t.t0_ms>=priorACK);assert.equal(t.public_stamp_ms,r.stamp_ms);assert.equal(r.elapsed_ms,r.stamp_ms-id.t0_ms);assert.deepEqual(JSON.parse(r.public_json).referee_action,r.referee_action);assert.equal(Buffer.byteLength(r.public_json),r.public_bytes);assert.equal(typeof r.checkpoint,'boolean');assert.equal(t.budget_breach,t.cause_window_ms>500);assert(t.owned_zero.handles===0&&t.owned_zero.activeNN===0&&t.owned_zero.live_searches===0);priorACK=t.stop_ACK_ms;
   if(r.accepted&&r.action!==null){const a=A.J.validate(id.legal_prefix,r.action);assert.deepEqual(JSON.parse(JSON.stringify(a)),r.referee_action);assert.deepEqual(r.echo,id);}
   if(t.root_numeric){const f=A.fixtures().find(f=>f.legal_prefix&&A.J.hash(f.legal_prefix)===A.J.hash(id.legal_prefix)),ref=f?refs.find(r=>r.id===f.id):undefined;const gate=N.check({engine:t.engine,state:A.J.state(id.legal_prefix),numeric:t.root_numeric,cp:t.root_cp,reference:ref});features+=648;NN+=137;priors+=gate.priors;}
   if(t.root_cp&&!A.J.terminalResult(A.J.state(id.legal_prefix))){const s=t.root_cp.root_edges.reduce((n,e)=>n+e[2],0);assert.equal(s,t.root_cp.simulations-(t.engine==='candidate'?1:0));if(t.engine==='reference')assert.equal(t.root_cp.root_visits,t.root_cp.simulations+1);}
   for(const b of t.bindings??[])if(b.accepted&&b.kind==='snapshot')assert(b.node_validation_finished_ms<=id.commit_cutoff_ms);
   (byEngine[t.engine]??=[]).push(t);
  }
  for(const m of moves){const r=m.response;if(r.accepted){assert.deepEqual(JSON.parse(JSON.stringify(A.J.validate(m.prefix,r.action))),r.referee_action);assert.equal(m.color,A.J.state(m.prefix).getCurrentPlayer());}}
  const invalidCPU=turns.filter(t=>t.cpu.browser_public_ticks<0||t.cpu.browser_residual_ticks<0).map(t=>({request_id:t.request_id,raw_public_ticks:t.cpu.browser_public_ticks,raw_residual_ticks:t.cpu.browser_residual_ticks,invalid_counter:true}));const stats={};for(const[e,rows]of Object.entries(byEngine)){const accepted=rows.filter(t=>t.accepted);stats[e]={requests:rows.length,accepted:accepted.length,public_median_ms:median(accepted.map(t=>t.public_elapsed_ms)),public_max_ms:Math.max(...rows.map(t=>t.public_elapsed_ms)),cause_median_ms:median(rows.map(t=>t.cause_window_ms)),cause_max_ms:Math.max(...rows.map(t=>t.cause_window_ms)),budget_breaches:rows.filter(t=>t.budget_breach).length,residual_max_ms:Math.max(...rows.map(t=>t.residual_after_public_ms)),CPU_counter_scope:rows.every(t=>t.cpu.identity_residual)?'retained PID/starttick observed lower-bound; not causal exact CPU':'live process-sum differences invalid for causal CPU; ended/reused counter scope insufficient',negative_counter_rows:rows.filter(t=>t.cpu.browser_public_ticks<0||t.cpu.browser_residual_ticks<0).length,public_browser_CPU_ticks:rows.reduce((n,t)=>n+t.cpu.browser_public_ticks,0),residual_browser_CPU_ticks:rows.reduce((n,t)=>n+t.cpu.browser_residual_ticks,0),post_public_NN_start_definite:rows.reduce((n,t)=>n+t.post_public_NN_start_definite,0),post_public_NN_start_possible:rows.reduce((n,t)=>n+t.post_public_NN_start_possible,0),NN:rows.reduce((n,t)=>n+t.NN_completed,0)};}
  const process=read(A.OUT+'/nn-'+run+'.process.json');assert.equal(process.exit,0);assert.equal(process.stop_reason,null);assert.deepEqual(process.remaining,[]);assert.deepEqual(process.unknown_adopted,[]);const monitor=read(dir+'/pause-monitor-stop.json');assert.equal(monitor.all_owned_read_callbacks_waited,true);
  outputs.push({run,summary,stats,invalid_CPU_counters:invalidCPU,CPU_credit_allowed:false,process:{start:process.start,end:process.end,RSS_peak:process.peak_group_plus_runner_RSS,storage_peak:process.peak_allocated_bytes,tracked:process.tracked.length,all_observed_TID_CPU2:process.all_observed_TIDs_at_assigned_CPU,remaining:process.remaining,forced_is_not_natural_end:true}});
 }
 const result={pass:true,own_saved_arithmetic:true,independent_review:false,features_bits_checked:features,NN_elements_checked:NN,prior_elements_checked:priors,runs:outputs,formal_fairness:false,formal_NI:false,API_times_not_kernel_instruction_timestamps:true};fs.writeFileSync(A.OUT+'/analysis-'+runs.join('_')+'-cpu-scope-v2.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({pass:true,features,NN,priors,runs:outputs.map(x=>({run:x.run,W:x.summary.W,D:x.summary.D,L:x.summary.L,game_starts:x.summary.game_starts,completed:x.summary.completed_games,unfinished:x.summary.unfinished_games,stats:x.stats,process:x.process}))}));
}
main();
