'use strict';const fs=require('fs'),assert=require('assert/strict'),crypto=require('crypto'),A=require('./arena.cjs'),{createMonitor}=require('../ai-sigma-actual-boundary-repair/pause-check.cjs');
async function main(){const config=JSON.parse(fs.readFileSync(process.argv[2])),out=A.OUT+'/preflight-r1';fs.mkdirSync(out,{recursive:false});const save=(n,x)=>fs.writeFileSync(out+'/'+n+'.json',JSON.stringify(x)+'\n'),append=(n,x)=>fs.appendFileSync(out+'/'+n+'.jsonl',JSON.stringify(x)+'\n');
 A.validate(config);for(const [key,value]of [['holdout',true],['seed',123],['games_before',8],['model_sha256','foreign']]){const q={...config,[key]:value,stage:key==='games_before'?'pair':config.stage};assert.throws(()=>A.validate(q));}
 const checks=[];let stopped=0,drop=0;
 const monitor=createMonitor({out,subjectIssue:config.issue,deadlineUTC:config.processing_deadline,windowEndUTC:'2026-10-02T05:39:12Z'});await monitor.start();
 const createBackend=async()=>({startup:{ready:true,mock:true},create({identity}){return {identity}},submit(c){const s=A.J.state(c.identity.legal_prefix),id=A.J.rustAction(s,s.getLegalActions()[0]);return Promise.resolve({engine:c.identity.engine,echo:c.identity,accepted:true,checkpoint:true,action:id,value:0,fallback:0})},async finish(){await new Promise(r=>setTimeout(r,550));stopped++;return {handles:0,activeNN:0,live_searches:0}},async stop(){drop++;return{handles:0,activeNN:0,controlledPID0:true}}});
 const result=await A.execute({...config,stage:'four-ply',run_id:'NN0-mock'}, {createBackend,monitor,save,append,diagnosticMock:true});assert.equal(result.turns,4);assert.equal(stopped,4);assert.equal(drop,1);assert.equal(result.budget_breaches,4);assert.equal(result.actual_go,false);assert.equal(result.NN_hand,0);assert.equal(result.primary,null);
 const rows=fs.readFileSync(out+'/turns.jsonl','utf8').trim().split('\n').map(JSON.parse);for(let i=1;i<rows.length;i++)assert(rows[i].t0_ms>=rows[i-1].stop_ACK_ms);checks.push('same-game-loop-four-ply','cause-side-budget-breach-preserved','next-input-after-owned-ACK','no-NN','monitor-READY-stop');
 // Guardian ownership/PPID/TMP disappearing-file race, including dedicated adoption.
 const {OwnedProcesses,boundedStop}=require('../ai-sigma-actual-boundary-repair/cleanup.cjs'),CP=require('child_process');const owner=new OwnedProcesses({tracePath:out+'/guardian.jsonl'});assert.equal(owner.rootIdentity.ppid,process.ppid);
 try{const child=owner.observeChild(CP.spawn('python3',['-B','-c',"import os,time,pathlib\np=pathlib.Path(os.environ['TMPDIR'])\nfor i in range(50):\n f=p/('race'+str(i));f.write_bytes(b'x'*4096);f.unlink()\nif os.fork()==0:\n os.setsid()\n if os.fork()==0:time.sleep(.25);os._exit(0)\n os._exit(0)\ntime.sleep(.05)"]));await new Promise((r,j)=>{child.once('error',j);child.once('exit',r)});await new Promise(r=>setTimeout(r,450));await owner.registrationReceipt();}finally{save('guardian-stop',await boundedStop({owner,stop:async()=>({remaining_pids:0})}));}
 checks.push('owned-PPID-adoption-stop','TMP-file-disappearance-race');
 const model=A.ROOT+'/models/experiments/ai-sigma/reference/sigma-pcr250/best.onnx',wasm=A.ROOT+'/.artifacts/ai-sigma/runs/SIGMA-ORT-SEARCH/final.wasm',sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');assert.equal(fs.statSync(model).size,11663428);assert.equal(sha(model),config.model_sha256);assert.equal(sha(wasm),'1f54d0b8f0c6d3d7d51935886ed506e44376a2052506be62ca7a726c85a78a01');save('checks',{pass:true,checks,model_sha256:sha(model),wasm_sha256:sha(wasm),NN:0,Chromium:0});console.log('PREFLIGHT_PASS');}
main().catch(e=>{console.error(e.stack);process.exitCode=1});
