'use strict';const fs=require('fs'),assert=require('assert/strict'),A=require('./arena.cjs');
const read=p=>JSON.parse(fs.readFileSync(p)),records=p=>fs.readFileSync(p,'utf8').trim().split('\n').filter(Boolean).map(JSON.parse);
const median=a=>{const x=a.slice().sort((a,b)=>a-b);return x.length%2?x[(x.length-1)/2]:(x[x.length/2-1]+x[x.length/2])/2};
const all=[];
for(const run of process.argv.slice(2)){
 const dir=A.OUT+'/'+run,b=dir+'/real-'+run+'-session1',priv=read(b+'/private-after-public.json');
 const rows=records(dir+'/turns.jsonl'),monitor=read(dir+'/pause-monitor-stop.json'),process=read(A.OUT+'/nn-'+run+'.process.json');
 const childPIDs=new Set(monitor.rows.filter(r=>r.kind==='owned_observer_child').map(r=>r.pid));const observerRoots=process.tracked.filter(p=>childPIDs.has(p.pid)),known=new Set(childPIDs);let changed=true;while(changed){changed=false;for(const p of process.tracked)if(known.has(p.ppid)&&!known.has(p.pid)){known.add(p.pid);changed=true;}}
 const observer=process.tracked.filter(p=>known.has(p.pid));
 const perTurn=rows.map(t=>{const q=read(b+'/stopACK-'+t.request_id+'.json'),p=priv[t.request_id],offset=t.worker_clock,nn=p?.NN??[],last=nn.at(-1),stop=q.stop.at_ms,root=nn[0];assert.equal(q.identity.request_id,t.request_id);assert(Number.isFinite(stop));const stopEarly=stop-offset.hi_ms,stopLate=stop-offset.lo_ms;
  return {request_id:t.request_id,engine:t.engine,public_ms:t.public_elapsed_ms,cause_ms:t.cause_window_ms,budget_breach:t.budget_breach,root_API_await_ms:root?root.session_run_end_ms-root.session_run_start_ms:null,last_API_end_worker_ms:last?.session_run_end_ms??null,private_done_worker_ms:p?.worker_done_ms??null,stop_generated_worker_ms:stop,stop_generated_node_early_ms:stopEarly,stop_generated_node_late_ms:stopLate,Node_ACK_received_ms:q.node_received_ms,Node_ACK_confirmed_ms:t.stop_ACK_ms,last_API_end_to_stop_generated_ms:last?stop-last.session_run_end_ms:null,private_done_to_stop_generated_ms:p?.worker_done_ms?stop-p.worker_done_ms:null,stop_generation_to_Node_received_ms_interval:[q.node_received_ms-stopLate,q.node_received_ms-stopEarly],Node_received_to_confirmed_ms:t.stop_ACK_ms-q.node_received_ms,shared_adapter_before_dispatch_ms:t.shared_adapter_before_dispatch_ms??null,shared_Judge_clone_UTF8_ms:t.shared_final_Judge_clone_UTF8_ms??null,shared_public_log_ms:t.shared_public_log_ms??null,shared_inspect_ms:t.shared_diagnostic_inspection_ms,old_version_missing_shared_spans:t.shared_final_Judge_clone_UTF8_ms===undefined,intervals_overlap_not_additive:true,API_await_not_kernel_instruction:true};});
 const byEngine={};for(const e of ['candidate','reference']){const x=perTurn.filter(t=>t.engine===e);byEngine[e]={requests:x.length,breaches:x.filter(t=>t.budget_breach).length,worst:x.reduce((a,b)=>a.cause_ms>b.cause_ms?a:b),lastAPI_to_stop_median_ms:median(x.filter(t=>t.last_API_end_to_stop_generated_ms!==null).map(t=>t.last_API_end_to_stop_generated_ms)),received_to_confirmed_max_ms:Math.max(...x.map(t=>t.Node_received_to_confirmed_ms)),Judge_max_ms:Math.max(...x.map(t=>t.shared_Judge_clone_UTF8_ms??0)),log_max_ms:Math.max(...x.map(t=>t.shared_public_log_ms??0)),inspect_max_ms:Math.max(...x.map(t=>t.shared_inspect_ms))};}
 const r={run,byEngine,perTurn,monitor:{owned_read_roots:observerRoots.length,observed_root_plus_descendant_processes:observer.length,CPU_ticks:observer.reduce((n,p)=>n+p.utime_ticks+p.stime_ticks,0),tick_Hz:100,short_children_may_be_missing:true,includes_Beads_read_and_serialization:true,not_subtracted_from_turn_time:true},shared_final_cleanup:read(dir+'/summary.json').shared_final_cleanup??null};all.push(r);
}
fs.writeFileSync(A.OUT+'/tail-spans-'+process.argv.slice(2).join('_')+'.json',JSON.stringify(all,null,2)+'\n');console.log(JSON.stringify(all.map(({run,byEngine,monitor,shared_final_cleanup})=>({run,byEngine,monitor,shared_final_cleanup}))));
