'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
const s=require('./selector.cjs'),rows=[];
const id={t0:1000,generation:7,key:'history-bound-key',request:'mock7'};
const cp={stable:true,generation:7,key:id.key,sequence:9,action:41};
const ack={request:id.request,generation:7,active:0,activeNN:0,handles:0,live_searches:0,pending_eval:0,pending_publish:0,started:4,returned:4,mainReceived:1547.3};
function test(name,f){f();rows.push({name,pass:true});}
const admit=s.cpAdmission(cp,id,[41,60],0,{lo:1401.7,hi:1401.9});
test('same rule both engine labels',()=>{assert.equal(admit.accepted,true);for(const engine of ['candidate','reference'])assert.deepEqual(s.cpAdmission({...cp,engine},id,[41],0,{lo:1401.7,hi:1401.9}).type,admit.type);});
test('upper crossing no midpoint rescue',()=>assert.equal(s.cpAdmission(cp,id,[41],0,{lo:1401.87,hi:1402.09}).type,'CP_BOUNDARY_UNKNOWN'));
test('upper equal cutoff rejected',()=>assert.equal(s.cpAdmission(cp,id,[41],0,{lo:1401,hi:1402}).accepted,false));
test('all after cutoff determinate timing rejection',()=>assert.equal(s.cpAdmission(cp,id,[41],0,{lo:1402.1,hi:1402.3}).type,'CP_AFTER_CUTOFF'));
test('missing upper interval unknown',()=>assert.equal(s.cpAdmission(cp,id,[41],0,{lo:1401}).type,'CLOCK_INTERVAL_UNKNOWN'));
test('stale generation and illegal action',()=>{assert.equal(s.cpAdmission({...cp,generation:6},id,[41],0,{lo:1401,hi:1401.1}).type,'STALE_CP');assert.equal(s.cpAdmission(cp,id,[60],0,{lo:1401,hi:1401.1}).type,'ILLEGAL_PUBLIC_ACTION');});
test('late read retains previously admitted cache',()=>{const rejected=s.cpAdmission({...cp,sequence:10},id,[41],9,{lo:1402,hi:1402.1});const cached=rejected.accepted?rejected:admit;assert.equal(s.publicDecision(cached,id,{lo:1411,hi:1411.2}).sequence,9);});
test('public500 is separate from402',()=>{assert.equal(s.publicDecision(admit,id,{lo:1499.7,hi:1499.9}).valid,true);assert.equal(s.publicDecision(admit,id,{lo:1499.9,hi:1500.1}).quality[1],1);});
test('tail after500 but before1000 does not shorten next allowance',()=>{const r=s.nextCycle(id,ack,{lo:2000,hi:2000.2});assert.equal(r.start,true);assert.equal(r.nextTarget,2000);assert.equal(r.kernelCPU,null);assert.equal(r.formalReady,false);});
test('early ACK not a clock reset',()=>assert.equal(s.nextCycle(id,{...ack,mainReceived:1412},{lo:1413,hi:1414}).start,false));
test('missing ACK active tail or counter mismatch failclosed',()=>{assert.equal(s.nextCycle(id,null,{lo:2000,hi:2001}).start,false);for(const change of [{activeNN:1},{returned:3},{pending_publish:1}])assert.equal(s.nextCycle(id,{...ack,...change},{lo:2000,hi:2001}).start,false);});
test('tail cycle overrun and main lateness unknown quality',()=>{assert.equal(s.nextCycle(id,{...ack,mainReceived:2000.1},{lo:2001,hi:2002}).start,false);assert.equal(s.nextCycle(id,ack,{lo:2005,hi:2005.1}).start,false);});
test('worker-only crossing preserves uncertainty',()=>assert.equal(s.workerOnlyEvidence({lo:1401.87,hi:1402.09},1402),'BOUNDARY_UNKNOWN'));
test('real SAB atomic coherent read NN0',()=>{const a=new Int32Array(new SharedArrayBuffer(16));[2,7,9,41].forEach((v,i)=>Atomics.store(a,i,v));let t=1401;const r=s.readStable(a,()=>t+=.1,id.key);assert.equal(r.cp.stable,true);assert.equal(r.cp.sequence,9);Atomics.store(a,0,3);assert.equal(s.readStable(a,()=>t+=.1,id.key).cp.stable,false);});
const out={issue:'quoridor-4lc.161',UTC:new Date().toISOString(),rule:s.RULE,tests:rows,NN:0,Chrome:0,workers_created:0,kernelCPU_measured:false,teacher_or_AI_calls:0,source_SHA256:crypto.createHash('sha256').update(fs.readFileSync(__dirname+'/selector.cjs')).digest('hex'),formalReady:false};
fs.writeFileSync(process.argv[2],JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({tests:rows.length,all_pass:true,formalReady:false,NN:0}));
