'use strict';const crypto=require('crypto'),J=require('./judge.cjs'),{SnapshotCache,freeze}=require('./early-cache.cjs');const now=()=>Number(process.hrtime.bigint())/1e6,eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b),hash=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
function context(f){if(!f||typeof f.id!=='string')throw Error('FIXTURE_REQUIRED');let s,prefix,fixture;if(f.classification==='legal-replay'){if(!Array.isArray(f.legal_prefix))throw Error('LEGAL_PREFIX_ARRAY_REQUIRED');s=J.state(f.legal_prefix);prefix=J.ids(f.legal_prefix);fixture=null;}else{if(!['synthetic-total-ply-200'].includes(f.id))throw Error('ARTIFICIAL_DIAGNOSTIC_ONLY');s=J.referenceState(f);prefix=null;fixture=f;}const meta=J.context(s),terminal=J.terminalResult(s),legal=terminal?[]:s.getLegalActions().map(a=>J.rustAction(s,a));return {prefix,fixture,key:meta.key,history:meta.history,terminal,legal,legal_prefix:fixture?null:JSON.parse(JSON.stringify(f.legal_prefix))};}
function makeContext(f,spec,t0,clock,reserve,{calibration=false,control=false}={}){const root=context(f),D=t0+(control?5000:500),seal=calibration||control?D:D-reserve.reserve_ms,cutoff=calibration||control?D:seal-reserve.commit_margin_ms;
 const engine=spec.engine??'candidate';if(!['candidate','reference'].includes(engine))throw Error('ENGINE');const identity=freeze({engine,request_id:spec.request_id,generation:spec.generation,epoch:spec.generation,fixture_id:f.id,fixture:root.fixture,prefix:root.prefix,legal_prefix:root.legal_prefix,key:root.key,history:root.history,model:'d790dac68389f7602ff8a887a2385417d3c925fe22da7164c86e9226f943908d',schema:'8x9x9-f32/136logits/value1/rust209',limits:{simulations:control?8:(engine==='reference'?100000:4096),max_nodes:engine==='reference'?null:512,max_depth:engine==='reference'?null:24,seed:1979},t0_ms:t0,deadline_ms:D,seal_ms:seal,commit_cutoff_ms:cutoff});
 const c={identity,root,spec,t0,clock,generation:spec.generation,publicResult:null,stopped:null,bindings:[],private:null};let crossed=false;
 c.cache=new SnapshotCache(identity,{legal:root.legal,terminal:root.terminal,clock_error_ms:2*clock.worker.error_ms+.2,getGeneration:()=>c.generation,validationHook:()=>{if(spec.validation_cross&&!crossed){crossed=true;const until=cutoff+1;while(now()<until){}}}},now);return c;}
function convert(m,clock){const q=structuredClone(m);if(q.owned)q.owned.completed_at-=clock.worker.lo_ms;if(Number.isFinite(q.sent_ms))q.sent_ms-=clock.worker.lo_ms;return q;}
function receive(c,m){const at=now();let accepted=false;if(m.kind==='snapshot'||m.kind==='fault'||m.kind==='cancel')accepted=c.cache.receive(convert(m,c.clock));c.bindings.push({kind:m.kind,sequence:m.sequence??null,node_received_ms:at,node_validation_finished_ms:now(),accepted,last_gate:c.cache.events.at(-1),raw_source_times:{completed_at:m.owned?.completed_at,sent_ms:m.sent_ms,producer_fault_ms:m.producer_fault_ms??null}});return accepted;}
function deliver(c,reason){if(c.publicResult)return c.publicResult;const decision=(c.now?c.now():now()),sealed=c.cache.seal(reason);let error=sealed.error,action=sealed.action,checkpoint=sealed.checkpoint,value=c.cache.cache?.value??null;const cp=sealed.owned?.cp;
 try{if(c.generation!==c.identity.generation||!eq(c.cache.identity,c.identity)||!Number.isSafeInteger(c.identity.generation)||c.identity.epoch!==c.identity.generation)throw Error('FINAL_IDENTITY');if(checkpoint){if(!Number.isFinite(value)||Math.abs(value)>1)throw Error('FINAL_VALUE');if(c.root.terminal){if(action!==null||value!==c.root.terminal.value||cp.nn_calls!==0)throw Error('FINAL_TERMINAL');}else if(!Number.isInteger(action)||!c.root.legal.includes(action))throw Error('FINAL_LEGAL');if(cp.generation!==c.identity.generation||sealed.sequence<1||cp.policy_fallbacks||cp.value_fallbacks)throw Error('FINAL_CP');}}
 catch(e){error=e.message;action=null;checkpoint=false;value=null;}
 const base={engine:c.identity.engine,request_id:c.identity.request_id,generation:c.identity.generation,epoch:c.identity.epoch,fixture_id:c.identity.fixture_id,position_key:c.identity.key,prefix_sha256:hash(c.identity.legal_prefix),history_sha256:hash(c.identity.history),model:c.identity.model,schema:c.identity.schema,limits:c.identity.limits,action,checkpoint,error,value,completion_token:checkpoint?sealed.owned.completed_token:null,sequence:sealed.sequence,completed_simulations:checkpoint?cp.simulations:0,completed_NN:checkpoint?sealed.owned.completed_NN:0,fallback:0,decision_ms:decision,t0_ms:c.t0,deadline_ms:c.identity.deadline_ms};
 let body=base,encoded=JSON.stringify(body),stamp=(c.now?c.now():now());if(stamp>=c.identity.deadline_ms){body={...body,action:null,checkpoint:false,value:null,error:'LATE_FINAL_STAMP',completion_token:null,completed_simulations:0,completed_NN:0};encoded=JSON.stringify(body);stamp=(c.now?c.now():now());}
 const out={...body,public_json:encoded,stamp_ms:stamp,elapsed_ms:stamp-c.t0,late:stamp>=c.identity.deadline_ms,overshoot_ms:Math.max(0,stamp-c.identity.deadline_ms),public_bytes:Buffer.byteLength(encoded),final_validation_encoding_ms:stamp-decision,seal_timer_lateness_ms:Math.max(0,decision-c.identity.seal_ms),snapshot_age_ms:sealed.snapshot_age_ms,calibration_only:reason==='calibration'};

 c.publicResult=freeze(out);c.generation++;return c.publicResult;}
module.exports={now,context,makeContext,receive,deliver,hash};
