'use strict';const fs=require('fs'),path=require('path'),assert=require('assert/strict'),C=require('./caller.cjs'),J=require('./judge.cjs'),{SnapshotCache}=require('./early-cache.cjs'),{receiveHost}=require('./backend-envelope.cjs'),{boundedStop}=require('./cleanup.cjs'),{open}=require('./browser.cjs');
const {preserveAndClean}=require('./error-boundary.cjs');const A=path.resolve(__dirname,'../../.artifacts/ai-sigma/continuation-20261001/SIGMA-STREAMING-COMPLETE-CLOCK');
const wait=(p,ms,error)=>{let t;return Promise.race([p,new Promise((_,j)=>t=setTimeout(()=>j(Error(error)),ms))]).finally(()=>clearTimeout(t));};
function factory(runid){return async({session,clock})=>{const dir=A+'/real-'+runid+'-session'+session;fs.mkdirSync(dir,{recursive:false});const save=(n,x)=>fs.writeFileSync(dir+'/'+n+'.json',JSON.stringify(x)+'\n'),contexts=new Map();let b=null,fatal=null,drop=null,stopPromise=null,stage='open';
 const backend={startup:{ready:false,mock:false},cleanupBudgetMs:2000,stopAckBudgetMs:1000,create({identity,meta}){if(fatal)throw Error(fatal);const f={id:identity.fixture_id,classification:'legal-replay',legal_prefix:identity.legal_prefix},root=C.context(f);if(root.key!==identity.key||JSON.stringify(root.history)!==JSON.stringify(identity.history))throw Error('FINAL_IDENTITY');const c={identity,root,t0:identity.t0_ms,generation:identity.generation,clock:b.clock,bindings:[],spec:meta,publicResult:null};c.cache=new SnapshotCache(identity,{legal:root.legal,terminal:root.terminal,clock_error_ms:2*b.clock.worker.error_ms+.2,getGeneration:()=>c.generation},C.now);c.stopPromise=new Promise(r=>c.resolveStop=r);c.publicPromise=new Promise(r=>c.resolvePublic=r);contexts.set(identity.request_id,c);if(C.now()>=identity.deadline_ms)c.resolveStop({activeNN:0,handles:0,live_searches:0,expired_before_dispatch:true,request_was_never_submitted:true});return c;},
 submit(c){const wake=()=>{if(c.publicResult)return;const rem=c.identity.seal_ms-C.now();if(rem>0){c.timer=setTimeout(wake,Math.ceil(rem));return;}publish(c,'early_seal');};c.timer=setTimeout(wake,Math.max(0,Math.ceil(c.identity.seal_ms-C.now())));if(C.now()>=c.identity.deadline_ms){c.resolveStop({activeNN:0,handles:0,live_searches:0,expired_before_dispatch:true});publish(c,'expired_before_dispatch');}else void b.page.evaluate(d=>sendEarly(d),{kind:'request',identity:c.identity,...(c.spec.cancel_after_cp?{capture_tree:false}:{})}).catch(e=>{fatal='PIPE_ERROR';c.cache.invalidate(fatal);publish(c,'transport_fault');});return c.publicPromise;},
 finish(c,finalPublic){c.diagnostic={...(c.diagnostic??{}),identity:c.identity,response:finalPublic,request_was_never_submitted:!c.publicResult};save('public-'+c.identity.request_id,c.diagnostic);return c.stopPromise;},
 stop(){if(stopPromise)return stopPromise;stopPromise=(async()=>{for(const c of contexts.values()){clearTimeout(c.timer);const p=await wait(c.stopPromise,1000,'OLD_SEARCH_STOP_TIMEOUT');if(p.handles||p.activeNN||p.live_searches||p.ownership_error)throw Error('OLD_SEARCH_STOP_FAILED');}let primary=null;for(const [label,work]of [['numeric',async()=>{const priv=await b.page.evaluate(()=>privateEarly());save('private-after-public',priv);save('numeric-gates',checkNumeric(priv,contexts));}],['clock',async()=>{const ending=await b.reclock('end');save('clock-end-bound',ending);for(const k of ['page','worker'])if(ending[k].lo_ms>b.clock[k].hi_ms||ending[k].hi_ms<b.clock[k].lo_ms)throw Error('CLOCK_DRIFT_DISJOINT');}],['drop',async()=>{drop=await b.page.evaluate(()=>dropEarly());save('model-drop',drop);}]] ){try{await work()}catch(e){save('exception-'+label,require('./error-boundary.cjs').detail(e,label));if(!primary)primary=e;else save('secondary-'+label,require('./error-boundary.cjs').detail(e,label));}}const cleanup=await boundedStop(b);save('controlled-stop',{cleanup,drop,forced:cleanup.forced,controlledPID0:cleanup.remaining_pids===0});if(primary)throw primary;if(!drop||drop.handles||drop.activeNN)throw Error('MODEL_DROP_NOT_ZERO');return {activeNN:drop.activeNN,handles:drop.handles,live_searches:0,controlledPID0:cleanup.remaining_pids===0};})().catch(async e=>{await preserveAndClean(save,'stop',e,async()=>b?await boundedStop(b):{no_backend:true},{model_state:b?.loadState??null});});return stopPromise;}};
 function publish(c,reason){if(c.publicResult)return;clearTimeout(c.timer);const result=C.deliver(c,reason);const echo=c.producerEcho;const response={...result,echo,accepted:result.checkpoint,local_timeout:!echo&&!result.checkpoint};c.diagnostic={identity:c.identity,response,bindings:c.bindings,private_cp:c.cache.cache};c.resolvePublic(response);void b.page.evaluate(g=>cancelEarly(g),c.generation).catch(e=>{fatal='PIPE_ERROR';save('cancel-transport-failure',{error:e.message})});}
 const onSnapshot=m=>{if(m.kind==='unbound_worker_error'){fatal='PIPE_ERROR';for(const c of contexts.values())if(!c.publicResult){c.cache.invalidate(fatal);publish(c,'fault');}return;}const c=contexts.get(m.identity?.request_id);if(!c)return {ignored:'foreign_request'};const ok=receiveHost(c,m);if(ok&&m.kind==='snapshot'&&c.spec.cancel_after_cp&&!c.publicResult){receiveHost(c,{kind:'cancel',identity:c.identity,error:'CANCELLED',sent_ms:C.now()+b.clock.worker.lo_ms});publish(c,'cancel');}return {accepted:ok};};
 const onStopped=m=>{const c=contexts.get(m.identity?.request_id);if(!c)return;const z=m.stop;if(JSON.stringify(m.identity)!==JSON.stringify(c.identity)||z.handles!==0||z.activeNN!==0||z.live_searches!==0||z.active!==false){fatal='OLD_SEARCH_STOP_FAILED';c.resolveStop({ownership_error:fatal});return;}save('stopACK-'+c.identity.request_id,{identity:m.identity,stop:z,node_received_ms:C.now()});c.resolveStop({...z,ownership_error:null});};
 try{b=await open(dir+'/browser',onSnapshot,onStopped);stage='model-load';const ready=await b.load();save('ready-state',ready);stage='startup6';const startup=await require('./startup.cjs').run(b,save);save('startup6-ready',startup);backend.startup.ready=true;save('ready',{startUTC:new Date().toISOString(),session,clock:b.clock,model_loaded:true,actual_go:false});return backend;}catch(e){await preserveAndClean(save,stage,e,async()=>b?await boundedStop(b):{no_backend_opened:true},{model_state:b?.loadState??null});}
};}
function checkNumeric(priv,contexts){const refs=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../../.artifacts/ai-sigma/runs/SIGMA-INFERENCE-PROBE/ort-a.outputs.json')));const gates=[];for(const[id,c]of contexts){const p=priv[id];if(c.root.terminal){assert.equal(p?.NN?.length,0);continue;}if(!p?.numeric?.length){gates.push({id,missing:true});continue;}const n=p.numeric[0],s=J.state(c.identity.legal_prefix),features=s.toNNInput(),expected=Array.from(new Uint32Array(features.buffer,features.byteOffset,features.length));require('./array-elements.cjs').equal(n.features_bits,expected,{bits:true});assert.equal(n.policy_logits.length,136);assert(n.policy_logits.every(Number.isFinite));assert(Number.isFinite(n.value)&&Math.abs(n.value)<=1);const ref=refs.find(x=>x.id===c.identity.fixture_id);if(ref){for(const[a,r]of[...n.policy_logits.map((v,i)=>[v,ref.policy_logits[i]]),[n.value,ref.value]])assert(Math.abs(a-r)<=1e-4+1e-4*Math.abs(r));}
 const cp=c.cache.cache?.owned?.cp;let prior_checked=false;if(cp?.root_edges?.length){const legal=s.getLegalActions(),map=[1,0,2,3,6,7,4,5],indices=legal.map(a=>{let k=J.actionToIndex(a,9);if(!s.isPlayer1Turn())k=k<8?map[k]:8+Math.floor((k-8)/64)*64+(7-Math.floor(((k-8)%64)/8))*8+(k-8)%8;return k;});const max=Math.max(...indices.map(k=>n.policy_logits[k])),ex=indices.map(k=>Math.exp(n.policy_logits[k]-max)),sum=ex.reduce((a,b)=>a+b,0);assert.equal(JSON.stringify(cp.root_edges.map(e=>e[0])),JSON.stringify(Array.from(legal,a=>J.rustAction(s,a))));cp.root_edges.forEach((e,i)=>assert(Math.abs(e[1]-ex[i]/sum)<=1e-4+1e-4*Math.abs(ex[i]/sum)));prior_checked=true;}gates.push({id,features648_exact:true,NN137_finite_strict:true,fixed_reference:!!ref,prior_checked,missing_public_cp:!cp});}return gates;}
module.exports={factory};
