importScripts('/ort/ort.min.js','/candidate-host.js','/checkpoint.js','/game.js','/context.js');
let b,generation=0,active=false,activeNN=0;const epoch=()=>performance.timeOrigin+performance.now(),yieldTask=()=>new Promise(r=>setTimeout(r,0)),busy=ms=>{const end=epoch()+ms;while(epoch()<end){}};
function checkIdentity(id){const s=id.fixture?referenceState(id.fixture):fromPrefix(id.legal_prefix),h=Array.from(s.position_history).sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:0);let a=fromPrefix([]),p=[];for(const x of id.legal_prefix??[]){p.push(rustAction(a,x));a=a.next(x)}if(!id.fixture&&JSON.stringify(p)!==JSON.stringify(id.prefix)||s._positionKey()!==id.key||JSON.stringify(h)!==JSON.stringify(id.history)||id.epoch!==id.generation||id.model!=='d790dac68389f7602ff8a887a2385417d3c925fe22da7164c86e9226f943908d')throw Error('PRODUCER_IDENTITY');}
async function run(d,direct=false){if(active||activeNN||b.liveHandles())throw Error('SEARCH_OVERLAP_OR_OLD_HANDLE');checkIdentity(d.identity);if(b.digest!==d.identity.model)throw Error('MODEL_BIND');active=true;generation=d.identity.generation;let seq=0,rootValue=null;const nn=[],numeric=[],original=b.infer;
 b.infer=async bits=>{if(activeNN)throw Error('NN_OVERLAP');activeNN++;const start=epoch();try{if(d.before_first_nn_busy_ms&&!nn.length)busy(d.before_first_nn_busy_ms);const r=await original(bits),end=epoch();nn.push({awaiter_start_ms:start,awaiter_end_ms:end,session_run_start_ms:r.session_run_start_ms,session_run_end_ms:r.session_run_end_ms,nn_ms:r.nn_ms});if(!numeric.length){rootValue=r.value;numeric.push({features_bits:Array.from(bits),policy_logits:r.logits,value:r.value});}return r;}finally{activeNN--;}};
 let result;try{result=await runOwned({fixture:d.identity.fixture??undefined,prefix:d.identity.prefix??undefined,generation,request_id:d.identity.request_id,simulations:d.identity.limits.simulations,max_nodes:512,max_depth:24,capture_tree:!!d.capture_tree,capture_trace:!!d.capture_tree},{b,epoch,yieldTask,getGeneration:()=>generation,completed:o=>{if(direct)return;const publicOwned=JSON.parse(JSON.stringify(o));publicOwned.cp.tree=[];const m={kind:'snapshot',identity:d.identity,sequence:++seq,owned:publicOwned,value:o.cp.terminal_value??rootValue,sent_ms:epoch()};if(d.notify_delay_ms)setTimeout(()=>postMessage(m),d.notify_delay_ms);else postMessage(m);if(d.hardfault_after_cp===seq){postMessage({kind:'fault',identity:d.identity,error:'INJECTED_HARDFAULT',producer_fault_ms:epoch(),sent_ms:epoch()});throw Error('INJECTED_HARDFAULT');}}});
  if(result.error)postMessage({kind:'fault',identity:d.identity,error:result.error,producer_fault_ms:epoch(),sent_ms:epoch()});
  postMessage({kind:'private_done',identity:d.identity,result,NN:nn,numeric,worker_done_ms:epoch(),direct});
 }catch(e){postMessage({kind:'fault',identity:d.identity,error:e.message,producer_fault_ms:epoch(),sent_ms:epoch()});}finally{b.infer=original;active=false;postMessage({kind:'stopped',identity:d.identity,stop:{live_searches:result?.live_searches??null,handles:b.liveHandles(),activeNN,active,NN_attempts:result?.calls??null,completed_NN:result?.completed_NN??null,at_ms:epoch(),error:result?.error??null}});}}
onmessage=async({data:d})=>{if(d.kind==='cancel'){generation=d.generation;postMessage({kind:'cancel_ack',generation,at_ms:epoch()});return;}if(d.kind==='ping'){postMessage({kind:'ping',id:d.id,at_ms:epoch()});return;}
 try{if(d.kind==='load'){b=await loadOrtHost();postMessage({kind:'ready',digest:b.digest,threads:b.threads,proxy:b.proxy,model_load_ms:b.load_ms,compile_ms:b.compile_ms,handles:b.liveHandles(),activeNN});}
 else if(d.kind==='mock'){checkIdentity(d.identity);const o=structuredClone(d.owned);o.identity={request_id:d.identity.request_id,generation:d.identity.generation,fixture:d.identity.fixture,prefix:d.identity.prefix,seed:1979,simulations:d.identity.limits.simulations,max_nodes:512,max_depth:24};o.cp.generation=d.identity.generation;o.cp.tree=[];o.completed_at=epoch();postMessage({kind:'snapshot',identity:d.identity,sequence:1,owned:o,value:d.value,sent_ms:epoch(),mock_NN0:true});}
 else if(d.kind==='request')await run(d,false);else if(d.kind==='direct')await run(d,true);else if(d.kind==='drop'){if(active||activeNN||b.liveHandles())throw Error('DROP_ACTIVE');await b.drop();postMessage({kind:'dropped',handles:b.liveHandles(),activeNN,at_ms:epoch()});}
 }catch(e){postMessage(d.identity?{kind:'fault',identity:d.identity,error:e.message,producer_fault_ms:epoch(),sent_ms:epoch()}:{kind:'failed',error:e.message});}};
