'use strict';const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict'),{open,BASE,ROOT}=require('./browser.cjs'),{boundedStop}=require('./cleanup.cjs'),C=require('./caller.cjs');const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),sleep=ms=>new Promise(r=>setTimeout(r,ms));
function token(mode,p){if(!['calibration','suite'].includes(mode)||!p)throw Error('DIAGNOSTIC_PURPOSE_REQUIRED');const t=JSON.parse(fs.readFileSync(p));if(!(mode==='calibration'?['NN0-CAL-63-01','NN0-CAL-63-02'].includes(t.run_id):['NN-SUITE-63-01','NN-SUITE-63-02-REMAINDER'].includes(t.run_id)))throw Error('FIXED_RUN_ID_REQUIRED');if(t.issue!=='quoridor-4lc.63'||t.actual_go!==false||!t.freeze_token||t.freeze_token!==process.env.SIGMA_EARLY_DIAGNOSTIC_TOKEN||t.mode!==mode||t.source_manifest_sha256!==sha(BASE+'/source-frozen.json')||t.preregister_sha256!==sha(BASE+'/preregister.json'))throw Error('EXPLICIT_FROZEN_TOKEN_REQUIRED');for(const c of JSON.parse(fs.readFileSync(BASE+'/source-frozen.json')).checks)if(sha(c.path)!==c.sha256)throw Error('SOURCE_MUTATED');for(const c of JSON.parse(fs.readFileSync(BASE+'/input-before.json')).checks)if(sha(c.path)!==c.sha256)throw Error('OLD_INPUT_MUTATED');if(mode==='suite'&&(t.reserve_sha256!==sha(BASE+'/reserve.json')||!JSON.parse(fs.readFileSync(BASE+'/reserve.json')).gate))throw Error('RESERVE_GATE');if(Date.now()>=Date.parse('2026-10-01T16:50:24Z'))throw Error('NEWJOB_CUTOFF');return t;}
function timeout(p,ms,label){let timer;return Promise.race([p,new Promise((_,reject)=>timer=setTimeout(()=>reject(Error(label)),ms))]).finally(()=>clearTimeout(timer));}
function clockGate(a,b){for(const k of ['page','worker'])if(b[k].lo_ms>a[k].hi_ms||b[k].hi_ms<a[k].lo_ms)throw Error('CLOCK_DRIFT_DISJOINT');return Object.fromEntries(['page','worker'].map(k=>[k,{start_error:a[k].error_ms,end_error:b[k].error_ms,midpoint_drift_ms:b[k].offset_ms-a[k].offset_ms,early_remote_deadline_conversion:'Node deadline + offset lower bound'}]));}
async function execute(mode,t){const out=BASE+'/'+t.run_id;if(fs.existsSync(out))throw Error('RUN_ALREADY_EXISTS');fs.mkdirSync(out);const save=(n,v)=>fs.writeFileSync(out+'/'+n+'.json',JSON.stringify(v,null,2)+'\n'),fixtures=JSON.parse(fs.readFileSync(ROOT+'/.artifacts/ai-sigma/reference-fixtures/SIGMA-PARITY-PLAN/fixtures.json')).fixtures,pr=JSON.parse(fs.readFileSync(BASE+'/preregister.json')),contexts=new Map(),rows=[];let b=null,lastContext=null,globalFatal=null;const stopEvents=[];const resume=t.run_id==='NN-SUITE-63-02-REMAINDER'?JSON.parse(fs.readFileSync(BASE+'/continuation-bind.json')):null;if(resume){if(t.continuation_sha256!==sha(BASE+'/continuation-bind.json')||sha(resume.old_process_path)!==resume.old_process_sha256||sha(resume.old_public_path)!==resume.old_public_sha256||sha(resume.control_gates_path)!==resume.control_gates_sha256||resume.offset!==1||resume.physical_owned_controlled_PID0!==true)throw Error('IMMUTABLE_REMAINDER_BIND');}const reserve=mode==='suite'?JSON.parse(fs.readFileSync(BASE+'/reserve.json')):{reserve_ms:0,commit_margin_ms:0};
 function create(f,spec,t0,options){const c=C.makeContext(f,spec,t0,b.clock,reserve,options);c.stopPromise=new Promise(r=>c.resolveStop=r);c.deliverPromise=new Promise(r=>c.resolveDeliver=r);contexts.set(c.identity.request_id,c);return c;}
 function finish(c,reason){if(c.publicResult)return;c.resolveDeliver(C.deliver(c,reason));clearTimeout(c.timer);if(mode==='suite')void b.page.evaluate(g=>cancelEarly(g),c.generation).catch(e=>{globalFatal='CANCEL_TRANSPORT_'+e.message});}
 const onSnapshot=m=>{if(m.kind==='unbound_worker_error'){globalFatal='UNBOUND_WORKER_ERROR';if(lastContext&&!lastContext.publicResult)C.receive(lastContext,{kind:'fault',identity:lastContext.identity,error:globalFatal,sent_ms:C.now()+b.clock.worker.lo_ms});return;}const c=contexts.get(m.identity?.request_id);if(!c)return{ignored:'foreign_request'};const accepted=C.receive(c,m);if(accepted&&m.kind==='snapshot'){if(mode==='calibration')finish(c,'calibration');if(c.spec.cancel_after_cp&&!c.publicResult){C.receive(c,{kind:'cancel',identity:c.identity,error:'CANCELLED',sent_ms:C.now()+b.clock.worker.lo_ms});finish(c,'cancel');}}
 return{accepted,Node_generation:c.generation};};
 const onStopped=m=>{const c=contexts.get(m.identity?.request_id);if(!c)return;try{if(JSON.stringify(m.identity)!==JSON.stringify(c.identity)||m.stop.live_searches!==0||m.stop.handles!==0||m.stop.activeNN!==0||m.stop.active!==false)throw Error('SEARCH_STOP_NOT_PROVED');c.stopped=m.stop;stopEvents.push({identity:m.identity,node_received_ms:C.now(),raw_stop:m.stop,search_error:m.stop.error,ownership_error:null});save('search-stop-events',stopEvents);c.resolveStop({...m.stop,request_error:m.stop.error,ownership_error:null});}catch(e){globalFatal=e.message;c.resolveStop({ownership_error:e.message});}};
 let cleanup=null;try{b=await open(out+'/browser',onSnapshot,onStopped);if(mode==='calibration'){
 const reps=JSON.parse(fs.readFileSync(BASE+'/representative-payloads-NN0.json'));let count=0;for(const id of pr.calibration.fixtures){const f=fixtures.find(x=>x.id===id);for(const sample of [-1,0,1,2,3,4]){require('./pause-check.cjs').checkPause();const spec={request_id:'CAL63-'+(++count),generation:2000+count,sample},c=create(f,spec,C.now(),{calibration:true});lastContext=c;const command={kind:'mock',identity:c.identity,...reps[id]};c.timer=setTimeout(()=>finish(c,'calibration'),550);await b.page.evaluate(d=>sendEarly(d),command);const r=await timeout(c.deliverPromise,2000,'CALIBRATION_NO_RESPONSE');rows.push({fixture:id,sample,t0:c.t0,public:r,bindings:c.bindings,mock_NN0:true,real_NN:0});if(!r.checkpoint||r.late)throw Error('CALIBRATION_INVALID_OR_LATE');}}
 const ending=await b.reclock('end'),drift=clockGate(b.clock,ending);save('samples',rows);const steady=rows.filter(r=>r.sample>=0),maxSteady=Math.max(...steady.map(r=>r.public.elapsed_ms)),maxValidation=Math.max(...steady.flatMap(r=>r.bindings.filter(x=>x.accepted).map(x=>x.node_validation_finished_ms-x.node_received_ms))),maxError=Math.max(b.clock.page.error_ms,b.clock.worker.error_ms);const selected={UTC:new Date().toISOString(),selection_once:true,method:pr.calibration,reserve_ms:Math.ceil(maxSteady+2*maxError+25),commit_margin_ms:Math.ceil(maxValidation+2*maxError+5),max_steady_ms:maxSteady,max_validation_ms:maxValidation,max_clock_error_ms:maxError,samples:rows.length,steady:steady.length,warm:rows.length-steady.length,drift,NN:0,gate:false};selected.gate=selected.reserve_ms<500&&selected.commit_margin_ms<500-selected.reserve_ms;if(!selected.gate)throw Error('RESERVE_NOT_ELIGIBLE');fs.writeFileSync(BASE+'/reserve.json',JSON.stringify(selected,null,2)+'\n');save('reserve-selected',selected);console.log(JSON.stringify(selected));
 }else{
 await b.load();const refs=JSON.parse(fs.readFileSync(ROOT+'/.artifacts/ai-sigma/runs/SIGMA-INFERENCE-PROBE/ort-a.outputs.json')),controls=[];let ci=0;
 if(!resume)for(const id of pr.fixed_control.fixtures){require('./pause-check.cjs').checkPause();const f=fixtures.find(x=>x.id===id),g=3000+ci++;
 const direct=create(f,{request_id:'CONTROL-DIRECT-'+id,generation:g},C.now(),{control:true});lastContext=direct;await b.page.evaluate(d=>sendEarly(d),{kind:'direct',identity:direct.identity,capture_tree:true});await timeout(direct.stopPromise,12000,'DIRECT_STOP');if(globalFatal)throw Error(globalFatal);
 const stream=create(f,{request_id:'CONTROL-STREAM-'+id,generation:g},C.now(),{control:true});lastContext=stream;await b.page.evaluate(d=>sendEarly(d),{kind:'request',identity:stream.identity,capture_tree:true});await timeout(stream.stopPromise,12000,'STREAM_CONTROL_STOP');if(globalFatal)throw Error(globalFatal);
 const privateRows=await b.page.evaluate(()=>privateEarly()),d=privateRows[direct.identity.request_id],s=privateRows[stream.identity.request_id];save('control-'+id,{direct:d,stream:s,public_received:stream.cache.cache,bindings:stream.bindings});assert(d&&s);assert.equal(d.result.error,null);assert.equal(s.result.error,null);assert.equal(d.result.trace.length,8);assert.equal(s.result.trace.length,8);assert.equal(JSON.stringify(d.result.cp),JSON.stringify(s.result.cp));assert(d.result.trace.every((x,i)=>JSON.stringify(x.cp)===JSON.stringify(s.result.trace[i].cp)));
 const ref=refs.find(x=>x.id===id),expectedBits=Array.from(new Uint32Array(new Float32Array(f.raw_features_float32).buffer)),priorMap=new Map(ref.canonical_legal_priors.map(x=>[x.canonical136,x.prior])),P2=f.board.total_ply%2===1,canon=i=>{if(!P2)return i;if(i<8)return[1,0,2,3,6,7,4,5][i];const off=i<72?8:72,z=i-off;return off+(7-Math.floor(z/8))*8+z%8;};let numeric=0,prior=0,maxAbs=0;
 for(const q of[d,s]){const n=q.numeric[0];assert(n);assert.equal(n.features_bits.length,648);assert.equal(JSON.stringify(n.features_bits),JSON.stringify(expectedBits));assert.equal(n.policy_logits.length,136);for(const [a,r]of [...n.policy_logits.map((v,i)=>[v,ref.policy_logits[i]]),[n.value,ref.value]]){assert(Number.isFinite(a)&&Number.isFinite(r));assert(Math.abs(a-r)<=1e-4+1e-4*Math.abs(r));maxAbs=Math.max(maxAbs,Math.abs(a-r));numeric++;}assert(Math.abs(n.value)<=1);const root=new Map(q.result.cp.root_edges.map(e=>[e[0],e[1]]));for(const a of f.legal_actions){const v=root.get(a.rust209),r=priorMap.get(canon(a.sigma136));assert(Number.isFinite(v)&&Number.isFinite(r)&&Math.abs(v-r)<=1e-4+1e-4*Math.abs(r));prior++;}}
 controls.push({fixture:id,all8cp_tree_history_stats_exact:true,numeric,features_bits:1296,prior,maxAbs});}
 if(resume)controls.push(...JSON.parse(fs.readFileSync(resume.control_gates_path)));save('control-gates',controls);if(resume)save('original-controls-carried-readonly',resume);
 let previous=null,nextT0=resume?.predecessor_stamp_ms??null;for(const spec of pr.cases.slice(resume?.offset??0)){require('./pause-check.cjs').checkPause();if(globalFatal)throw Error(globalFatal);const f=fixtures.find(x=>x.id===spec.fixture);const t0=nextT0??C.now();let oldWait=0;if(previous){const start=C.now(),proof=await timeout(previous.stopPromise,1000,'OLD_SEARCH_STOP_TIMEOUT');oldWait=C.now()-start;if(proof.ownership_error||proof.handles||proof.activeNN||proof.live_searches)throw Error('OLD_SEARCH_STOP_FAILED');}
 const setupStart=C.now(),c=create(f,spec,t0,{});c.setup_start_ms=setupStart;c.setup_finished_ms=C.now();lastContext=c;const wake=()=>{if(c.publicResult)return;const remaining=c.identity.seal_ms-C.now();if(remaining>0){c.timer=setTimeout(wake,Math.ceil(remaining));return;}if(spec.caller_busy_at_seal){const until=c.identity.deadline_ms+10;while(C.now()<until){}}finish(c,'early_seal');};c.timer=setTimeout(wake,Math.max(0,Math.ceil(c.identity.seal_ms-C.now())));
 if(C.now()>=c.identity.deadline_ms){finish(c,'expired_before_dispatch');c.stopped={expired_before_dispatch:true,live_searches:0,handles:0,activeNN:0,active:false};c.resolveStop(c.stopped);}else await b.page.evaluate(d=>sendEarly(d),{...spec,kind:'request',identity:c.identity});const result=await timeout(c.deliverPromise,1500,'CALLER_NO_DELIVERY');assert.equal(JSON.parse(result.public_json).action,result.action);assert.equal(JSON.parse(result.public_json).checkpoint,result.checkpoint);if(result.late){assert.equal(result.action,null);assert.equal(result.checkpoint,false);}rows.push({spec,old_search_wait_ms:oldWait,next_input_available_at_previous_public_stamp:previous!=null,root_context_started_ms:c.setup_start_ms,root_context_finished_ms:c.setup_finished_ms,public:result,bindings:c.bindings,private_cache:c.cache.cache,cache_events:c.cache.events});save('public-requests',rows);console.log(JSON.stringify({id:spec.request_id,kind:spec.kind,fixture:spec.fixture,action:result.action,error:result.error,elapsed:result.elapsed_ms,late:result.late,sims:result.completed_simulations}));previous=c;nextT0=result.stamp_ms;}
 if(previous){const proof=await timeout(previous.stopPromise,1000,'FINAL_SEARCH_STOP_TIMEOUT');if(proof.ownership_error)throw Error(proof.ownership_error);}const privateRows=await b.page.evaluate(()=>privateEarly());save('private-diagnostics-after-public',privateRows);const end=await b.reclock('end');save('clock-drift',clockGate(b.clock,end));save('handle-drop',await b.page.evaluate(()=>dropEarly()));save('summary',{planned:20,public_this_segment:rows.length,original_completed:resume?.offset??0,public_combined:rows.length+(resume?.offset??0),normal:rows.filter(r=>r.spec.kind==='normal').length,normal_eligible:rows.filter(r=>r.spec.kind==='normal'&&r.public.checkpoint&&!r.public.late).length,late:rows.filter(r=>r.public.late).length,control:controls,actual_go:false,games:0,holdout:0,policy:'receive-order, producer faults separately recorded; afterseal unchanged'});
 }
 }catch(e){save('failure',{error:e.message,stack:e.stack,rows_completed:rows.length,rows});throw e;}finally{if(b){cleanup=await boundedStop(b);b=null;save('runtime-stop-before-document',{UTC:new Date().toISOString(),controlled_PID0:cleanup.remaining_pids===0,cleanup,forced:cleanup.forced,actual_go:false});}}
 return {rows:rows.length,cleanup};}
module.exports={token,execute};if(require.main===module){const [flag,mode,p]=process.argv.slice(2);if(flag!=='--diagnostic'){console.error('EXPLICIT_DIAGNOSTIC_TOKEN_REQUIRED');process.exitCode=1;}else{try{const t=token(mode,p);execute(mode,t).catch(e=>{console.error(e.stack);process.exitCode=1});}catch(e){console.error(e.message);process.exitCode=1;}}}
