'use strict';const fs=require('fs'),path=require('path'),{spawn}=require('child_process'),{performance}=require('perf_hooks'),{Broker}=require('../ai-sigma-teacher-throughput/codec-control/broker.cjs'),{Pipe}=require('../ai-sigma-teacher-throughput/pipe.cjs'),{createMonitor}=require('../ai-sigma-manygame-generation/pause-monitor.cjs');
const ROOT=process.cwd(),c=JSON.parse(fs.readFileSync(process.argv[2])),specs=JSON.parse(fs.readFileSync(c.openings_path)).games.filter(g=>g.job===c.job && c.game_ids.includes(g.game_id)),out=c.job_out;fs.mkdirSync(out,{recursive:true});const save=(n,x)=>fs.writeFileSync(out+'/'+n,JSON.stringify(x,null,2)+'\n');let broker,provider,workers=[],aborted=false,providerSeq=0,providerCost={codec:'singleencode-bits-only-v1',JSON_firstpass_NOT_APPLICABLE:true,batches:0,server_before_JSON_ms:0,JSON_encode_firstpass_ms:0,stages:{}};const start=performance.now();
function abort(reason){if(aborted)return;aborted=true;save('abort.json',{reason,UTC:new Date().toISOString()});broker?.stop();for(const w of workers)w.abort();}
class Worker{constructor(core){this.core=core;this.seq=0;this.pending=new Map;this.child=spawn('taskset',['-c',''+core,process.execPath,'--max-old-space-size=192',ROOT+'/tools/ai-sigma-teacher-throughput/worker.cjs',''+core,out+'/core'+core],{stdio:['ignore','inherit','inherit','ipc']});this.exit=new Promise(resolve=>this.child.on('exit',(code,signal)=>{for(const p of this.pending.values())p.reject(Error('WORKER_EXIT'));this.pending.clear();resolve({code,signal})}));this.child.on('message',q=>{if(q.kind==='infer'){if(aborted){this.child.send({kind:'reply',request_id:q.identity.request_id,error:'CONTROL_ABORT'});return;}broker.infer(q.identity,q.features_bits648).then(data=>this.child.send({kind:'reply',request_id:q.identity.request_id,data}),e=>{this.child.send({kind:'reply',request_id:q.identity.request_id,error:e.message});abort(e.message)});return;}if(q.kind==='cancel'){broker.cancel(q.worker,q.game,q.generation,q.run);return;}if(q.kind==='wait_game'){void broker.quiescentGame(q.worker,q.game,q.run).then(()=>this.child.send({kind:'drained',id:q.id}));return;}if(q.kind==='fault'){abort(q.error);return;}const p=this.pending.get(q.id);if(!p)return;this.pending.delete(q.id);q.error?p.reject(Error(q.error)):p.resolve(q.data);});}
 ask(op,x={}){const id=++this.seq;return new Promise((resolve,reject)=>{this.pending.set(id,{resolve,reject});this.child.send({id,op,...x})})}abort(){if(this.child.connected)this.child.send({kind:'abort'})}}
(async()=>{const m=createMonitor({out,subjectIssue:c.issue,deadlineUTC:c.science_deadline,windowEndUTC:'2026-10-04T14:33:18Z'}),closed=[],results=[];let primary=null,info=null,providerStop=null;const timer=setTimeout(()=>abort('BOUNDED_GENERATION_HARD_LIMIT_PRE_CLEANUP'),(c.job_seconds-8)*1000);
try{await m.start(e=>abort(e.message));save('registered-games.json',specs);if(c.mode.startsWith('GPU')){provider=new Pipe('/home/vscode/.cache/inference/envs/quoridor-training/bin/python',['-u',ROOT+'/tools/ai-sigma-teacher-throughput/codec-control/provider.py','--sample-cap',''+c.NN_cap,'--max-batch',''+c.max_batch],{timeoutMs:30000});const z=await provider.ask({op:'info',request_id:'init'});if(!z.ok||z.request_id!=='init')throw Error('PROVIDER_INIT');info=z.result;save('provider-init.json',info);broker=new Broker(async items=>{const request_id='batch.'+(++providerSeq),z=await provider.ask({op:'infer_batch',request_id,backend:'cuda',items});if(!z.ok||z.request_id!==request_id)throw Error(z.error?.message??'PROVIDER_ID');providerCost.batches++;providerCost.JSON_encode_firstpass_ms+=z.result.batchcost.JSON_encode_firstpass_ms??0;providerCost.server_before_JSON_ms+=z.result.batchcost.server_before_JSON_ms;for(const[k,v]of Object.entries(z.result.batchcost.stages))providerCost.stages[k]=(providerCost.stages[k]??0)+v;return z.result.items;},{replyCap:c.NN_cap,maxBatch:c.max_batch});}
 for(const core of [2,4,6])workers.push(new Worker(core));const init=await Promise.all(workers.map(w=>w.ask('init',{mode:c.mode.startsWith('GPU')?'GPU':c.mode,run:c.run_id,datasetMode:'frame18-independent-growth'})));save('init-all.json',init);m.check();if(aborted)throw Error('ABORT_BEFORE_GAMES');await Promise.all(workers.map(async w=>{const x=await w.ask('games',{games:specs.filter(g=>g.core===w.core).map(g=>g.split==='test'?{...g,split:'evaluation'}:g),active:c.active_per_worker});results.push(x)}));m.check();}
catch(e){primary={error:e.stack,provider_stderr:provider?.stderr??null};abort(e.message)}finally{clearTimeout(timer);for(const w of workers){w.abort();try{closed.push({core:w.core,...await w.ask('close'),exit:await w.exit})}catch(e){closed.push({core:w.core,error:e.stack})}}if(broker){broker.stop();await broker.quiescent();save('broker.json',{stats:broker.stats,providerCost,zero:broker.zero(),fault:broker.fault});}if(provider){try{const z=await provider.ask({op:'stop',request_id:'stop'});providerStop=z.result;save('provider-stop.json',z);}catch(e){providerStop={error:e.stack};}providerStop={...providerStop,pipe:{calls:provider.calls,requestBytes:provider.requestBytes,responseBytes:provider.responseBytes,timings:provider.timings},exit:await provider.close()};}await m.stop();}
save('result.json',{issue:c.issue,run_id:c.run_id,mode:c.mode,planned_games:specs.length,results,closed,primary,providerStop,aborted,elapsed_ms:performance.now()-start,monitor_state:m.state,NN:closed.reduce((s,x)=>s+(x.usedNN??0),0),startup_NN:closed.reduce((s,x)=>s+(x.startup_NN??0),0)});console.log(JSON.stringify({mode:c.mode,primary,aborted,NN:closed.reduce((s,x)=>s+(x.usedNN??0),0),games:results.reduce((s,x)=>s+x.results.length,0)}));if(primary||aborted)process.exitCode=1;
})().catch(e=>{abort(e.message);save('fatal.json',{error:e.stack});console.error(e.stack);process.exitCode=1;});
