'use strict';const fs=require('fs'),crypto=require('crypto'),path=require('path'),{r}=require('../ai-sigma-native-baseline/reference.cjs').createReference();const D=path.resolve(process.cwd(),'research-data/ai-sigma/frame18-data-learning'),MP=D+'/manifest-master.json';fs.mkdirSync(D,{recursive:true});let master;if(fs.existsSync(MP))master=JSON.parse(fs.readFileSync(MP)).master;else{master=crypto.randomBytes(32).toString('hex');fs.writeFileSync(MP,JSON.stringify({master,domain:'FRAME18_GROWTH228_V1',UTC:new Date().toISOString(),once_entropy:true},null,2)+'\n');}

function opening(slot,ply){const attempts=[];for(let a=0;a<256;a++){const seed=crypto.createHash('sha256').update('FRAME18_GROWTH228_OPENING_V1|'+master+'|'+slot+'|'+a).digest('hex');let x=parseInt(seed.slice(0,8),16)||1;const u=()=>{x^=x<<13;x^=x>>>17;x^=x<<5;x>>>=0;return x/4294967296};let state=r.fromPrefix([]),prefix=[],reason=null;for(let p=0;p<ply;p++){if(r.terminalResult(state)){reason='TERMINAL';break;}const category=u()<.5?'pawn':'wall';const legal=state.getLegalActions().filter(a=>a.type===category);if(!legal.length){reason='CHOSEN_EMPTY_CLASS';break;}const action=legal[Math.floor(u()*legal.length)];prefix.push(action);state=state.next(action);}if(!reason&&r.terminalResult(state))reason='TERMINAL';attempts.push({proposal:a+1,reason});if(!reason)return{generated:true,opening:{legal_prefix:prefix,key:state._positionKey(),side:state.getCurrentPlayer(),ply:state.depth,seed,proposal:a+1,root_state:r.portState(state)},attempts};}return{generated:false,opening:null,attempts};}

const jobs=['val96','test96','train01','train02','train03','train04','train05'],all=[];
for(let j=0;j<jobs.length;j++){const name=jobs[j],file=D+'/'+name+'-openings.json';if(fs.existsSync(file))throw Error('MANIFEST_EXISTS:'+name);const split=j===0?'validation':j===1?'test':'train';
 const games=Array.from({length:96},(_,i)=>{const global=j*96+i+1,family='frame18-228-'+master+'-'+global;return{game_id:'frame18-228-'+master.slice(0,12)+'-game-'+String(global).padStart(3,'0'),family,lineage:family,slot:i+1,global_slot:global,core:[2,4,6][i%3],target_ply:[8,12,16,20,24,28][i%6],sampling_seed:crypto.createHash('sha256').update('FRAME18_GROWTH228_ACTION_V1|'+family).digest('hex'),split_hash:crypto.createHash('sha256').update('FRAME18_GROWTH228_SPLIT_V1|'+family).digest('hex'),split,job:name,train_slot:split==='train'?96+(j-2)*96+i+1:null,...opening(global,[8,12,16,20,24,28][i%6])}});
 fs.writeFileSync(file,JSON.stringify({master,domain:'FRAME18_GROWTH228_OPENING_V1',max256:true,firstaccepted:true,class:'pawn/wall .5 once per ply; empty class rejects whole proposal',terminal:'whole proposal rejected',games,NN:0,formal173_read:0,oldteacher_input_reused:0,split,learning_selection:'newheldout partition fixed before labels',job:name},null,2)+'\n');all.push(...games);
}
if(new Set(all.map(g=>g.game_id)).size!==672||new Set(all.map(g=>g.family)).size!==672||new Set(all.map(g=>g.sampling_seed)).size!==672)throw Error('DUPLICATE_UID_SEED');
const old=JSON.parse(fs.readFileSync('research-data/ai-sigma/frame16-teacher-throughput/fresh96-stage/openings.json')).games;
if(all.some(g=>old.some(o=>o.family===g.family||o.sampling_seed===g.sampling_seed||o.opening.seed===g.opening?.seed)))throw Error('OLD_UID_SEED_REUSE');
fs.writeFileSync(D+'/generation-plan.json',JSON.stringify({jobs,registered_games:672,master,order:jobs,old96_newtrain_alias_planned:true,old_source_evaluation_preserved:true,manifests:Object.fromEntries(jobs.map(n=>[n,crypto.createHash('sha256').update(fs.readFileSync(D+'/'+n+'-openings.json')).digest('hex')])),gameUIDunique:true,seedunique:true,NN:0},null,2)+'\n');console.log(JSON.stringify({registered:672,generated:all.filter(g=>g.generated).length,NN:0}));
