'use strict';const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto'),zlib=require('zlib'),{performance}=require('perf_hooks');
const {target,validate}=require('../ai-sigma-manygame-generation/schema.cjs'),{r}=require('../ai-sigma-native-baseline/reference.cjs').createReference();const R=process.cwd(),c=JSON.parse(fs.readFileSync(process.argv[2])),D=c.job_out,specs=JSON.parse(fs.readFileSync(c.openings_path)).games.filter(g=>c.game_ids.includes(g.game_id)),mode=c.run_id,AD=D,out=D,start=performance.now();
const read=p=>fs.existsSync(p)?JSON.parse(fs.readFileSync(p)):null,lines=p=>fs.existsSync(p)?fs.readFileSync(p,'utf8').trim().split('\n').filter(Boolean).map(JSON.parse):[],save=(n,x)=>fs.writeFileSync(AD+'/'+n,JSON.stringify(x,null,2)+'\n');const proc=read(out+'/process.json'),result=read(out+'/result.json'),broker=read(out+'/broker.json');assert(proc&&proc.current_exact_absent&&proc.all_child_waited,'PROCESS_NOT_STOPPED');const raw=[],finals=[],starts=[],closed=[];
for(const core of[2,4,6]){raw.push(...lines(out+'/core'+core+'/raw-rows.jsonl'));finals.push(...lines(out+'/core'+core+'/games.jsonl'));starts.push(...lines(out+'/core'+core+'/starts.jsonl'));closed.push(read(out+'/core'+core+'/close.json'));}
const canon=x=>JSON.stringify([...x].sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:0)),eligible=[],games=[],by=new Map;
for(const row of raw){if(!by.has(row.game_id))by.set(row.game_id,[]);by.get(row.game_id).push(row);}
for(const spec of specs){const rr=(by.get(spec.game_id)??[]).sort((a,b)=>a.ply-b.ply),game=finals.find(g=>g.game_id===spec.game_id)??{game_id:spec.game_id,family:spec.family,split:spec.split,status:proc&&starts.some(g=>g.game_id===spec.game_id)?'REGISTERED_UNFINISHED_UNKNOWN':'NOT_STARTED',reason:proc?(proc.stop_reason??'ABORT_OR_BEFORE_SLOT'):'JOB_NOT_RUN',winner:null,rows:rr.length};games.push(game);if(!spec.generated){assert.equal(rr.length,0);continue;}let state=r.fromPrefix(spec.opening.legal_prefix);
for(const row of rr){assert.equal(row.family,spec.family);assert.equal(row.split,spec.split==='test'?'evaluation':spec.split);assert.equal(row.state_key,state._positionKey());assert.equal(row.side,state.getCurrentPlayer());assert.equal(row.ply,state.depth);const root=r.portState(state);assert.equal(JSON.stringify(row.features648_bits),JSON.stringify(root.features_bits));assert.equal(JSON.stringify(row.legal_order209),JSON.stringify(root.legal));assert.equal(canon(row.history_counts),canon(Array.from(state.position_history)));target(row,game.winner??null);validate(row,64);const expected=r.portState(state).legal;assert(row.mapping136.every(([a,k])=>expected.includes(a)&&k>=0&&k<136));const bits=new Uint32Array(new Float32Array(row.NN137_bits.map(b=>new Float32Array(new Uint32Array([b]).buffer)[0])).buffer);assert(bits.every((b,i)=>b===row.NN137_bits[i]));if(spec.split==='test')row.split='test';row.policy_eligible=true;row.joint_eligible=row.value_eligible;row.legal_mask136=Array(136).fill(0);for(const[a,k]of row.mapping136)row.legal_mask136[k]=1;eligible.push(row);const action=state.getLegalActions().find(a=>r.rustAction(state,a)===row.action209);assert(action,'REPLAY_ACTION');state=state.next(action);}
if(['GOAL','DRAW200','DRAW_NOLEGAL'].includes(game.status)){const terminal=r.terminalResult(state);assert(terminal&&terminal.winner===game.winner,'TERMINAL_REPLAY');}}
const completed=new Set(games.filter(g=>['GOAL','DRAW200','DRAW_NOLEGAL'].includes(g.status)).map(g=>g.game_id));
fs.writeFileSync(AD+'/effective-rows.jsonl.gz',zlib.gzipSync(eligible.filter(x=>completed.has(x.game_id)&&x.value_eligible).map(x=>JSON.stringify(x)).join('\n')+'\n'));
const status=Object.fromEntries([...new Set(games.map(g=>g.status))].map(s=>[s,games.filter(g=>g.status===s).length])),joint=eligible.filter(x=>x.value_eligible).length,wall=proc?.jobwall_seconds??null,done=games.filter(g=>['GOAL','DRAW200','DRAW_NOLEGAL'].includes(g.status)).length;
fs.writeFileSync(AD+'/teacher-rows.jsonl.gz',zlib.gzipSync(eligible.map(x=>JSON.stringify(x)).join('\n')+'\n'));save('all-status.json',games);
const ends=games.filter(g=>Number.isFinite(g.elapsed_ms)).map(g=>g.elapsed_ms),allEnd=finals.map(g=>g.elapsed_ms);const x={issue:'quoridor-4lc.228',mode,planned_games:specs.length,status_counts:status,Rpolicy:eligible.length,Rz:joint,Rjoint:joint,unknown_z_rows:eligible.length-joint,allattempt_jobwall_s:wall,rates:wall?{Rpolicy:eligible.length/wall,Rz:joint/wall,Rjoint:joint/wall,games:done/wall}:null,actual_NN:result?.providerStop?.single_sample_equivalent??null,logical_worker_NN:result?.NN??null,startup:result?.startup_NN??null,terminal_noNN:eligible.reduce((s,x)=>s+x.terminal_noNN,0),discarded:broker?.stats.discarded??null,batch:broker?.stats??null,providerCost:broker?.providerCost??null,providerStop:result?.providerStop??null,worker_spans:closed,sampled_peak_RSS:proc?.peak_aggregate_RSS??null,all_slot_plies:games.map(g=>({id:g.game_id,status:g.status,total_ply:g.plies??null,new_rows:g.rows??0,terminal:['GOAL','DRAW200','DRAW_NOLEGAL'].includes(g.status),unknown_z:g.winner==null})),qualification_replay_rows:eligible.length,qualify_wall_s:(performance.now()-start)/1000,mixed_into_learner:false,formal_holdout_read:false,teacher_truth_or_strength:false,process:proc?{exit:proc.exit,stop_reason:proc.stop_reason,current_exact_absent:proc.current_exact_absent}:null};save('summary.json',x);console.log(JSON.stringify({mode,status,Rpolicy:x.Rpolicy,Rjoint:joint,wall,Rjoint_per_s:x.rates?.Rjoint,qualify_wall_s:x.qualify_wall_s}));
