'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'../..'),BASE=ROOT+'/.artifacts/ai-sigma/runs/SIGMA-PAIRED-MATCHES',DEADLINE=Date.parse('2026-10-01T00:45:00Z');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function schedule(prereg,pool){if(prereg.version!==2||prereg.total_games!==32||prereg.block_order.length!==16)throw Error('PREREGISTER_V2_REQUIRED');return prereg.block_order.map((b,i)=>{const f=pool.pool[b.pool_index];if(!f||f.id!==b.id)throw Error('POOL_INDEX_ID');if(JSON.stringify([...b.candidate_color_order].sort())!=='[1,2]')throw Error('COLOR_PAIR');return {...b,block:i+1,prefix:f.legal_prefix,prefix_sha256:crypto.createHash('sha256').update(JSON.stringify(f.legal_prefix)).digest('hex'),games:b.candidate_color_order.map((color,j)=>({game:2*i+j+1,candidate_color:color,seed:1979}))};});}
function verifyToken(token,preregPath,manifestPath){if(manifestPath!==BASE+'/entry-ready-revision3.json')throw Error('FIXED_REVISION3_MANIFEST_REQUIRED');const m=JSON.parse(fs.readFileSync(manifestPath));if(!token||token.issue!=='quoridor-4lc.21'||token.actual_run!==true||token.critic_accepted!==true||token.coordinator_thread!=='01a0f31b-3409-75f2-a30e-453a50484f94'||token.critic_issue!=='quoridor-4lc.23'||!/^[a-f0-9]{64}$/.test(token.critic_report_sha256??'')||token.freeze_token!==process.env.SIGMA_MATCH_FREEZE_TOKEN||!token.freeze_token)throw Error('EXPLICIT_ACTUAL_RUN_FREEZE_TOKEN_REQUIRED');if(token.preregister_sha256!==sha(preregPath)||token.entry_manifest_sha256!==sha(manifestPath)||token.T_ms!==500||token.g_ms!==91)throw Error('FREEZE_MISMATCH');for(const x of m.checks)if(sha(x.path)!==x.sha256)throw Error('FINAL_INPUT_MUTATED '+x.path);if(token.processing_stop_utc!=='2026-10-01T00:45:00Z')throw Error('DEADLINE_MISMATCH');}
async function execute({prereg,pool,createBackend,out,checkPause=async()=>false,now=Date.now,deadline=DEADLINE,runId,dry=false}){
 fs.mkdirSync(out,{recursive:true});const append=(name,x)=>fs.appendFileSync(out+'/'+name+'.jsonl',JSON.stringify({utc:new Date().toISOString(),run_id:runId,...x})+'\n');const write=(name,x)=>{const tmp=out+'/'+name+'.tmp';fs.writeFileSync(tmp,JSON.stringify(x,null,2));fs.renameSync(tmp,out+'/'+name+'.json')};
 const blocks=schedule(prereg,pool),table=blocks.flatMap(b=>b.games.map(g=>({...g,block:b.block,platform:b.platform,pool_index:b.pool_index,prefix_sha256:b.prefix_sha256,status:'scheduled',attempt:0})));let backend=null,restarts=0,globalRetry=0,stopped=false,lastPause=-Infinity,stopping=Promise.resolve();
 const guard=async(force=false)=>{if(stopped||now()>=deadline)throw Error('PROCESSING_DEADLINE_OR_SIGNAL');if(force||now()-lastPause>=10000){lastPause=now();if(await checkPause())throw Error('PAUSED');}};
 const stop=()=>{if(!backend)return stopping;const old=backend;backend=null;stopping=stopping.then(async()=>{const proof=await old.stop();if(proof.remaining_pids!==0)throw Error('OWN_CLEANUP_PID_NOT_ZERO');append('lifecycle',{phase:'cleanup_PID0',...proof});});return stopping;};
 const start=async()=>{await stop();await guard(true);backend=await createBackend({session:++restarts,out:out+'/session-'+restarts});append('lifecycle',{phase:'restart_load_warm_recalibrate',session:restarts,startup:backend.startup,clock:backend.clock});};
 const checkpoint=()=>write('checkpoint',{runId,dry,table,globalRetry,restarts,processing_deadline:new Date(deadline).toISOString(),games_scheduled:32});
 const signal=()=>{stopped=true;void stop().catch(e=>append('stop-error',{error:e.message}));};process.once('SIGTERM',signal);process.once('SIGINT',signal);
 let stopReason='all_scheduled_complete';
 try{checkpoint();await start();
 for(const block of blocks){await guard(true);let pairDone=false;
  for(let attempt=0;attempt<2;attempt++){
   let invalid=false,incomplete=false;const attemptRows=[];
   for(const game of block.games){await guard(true);if(!backend)await start();const row=table[game.game-1];row.status='running';row.attempt=attempt;checkpoint();
    const choose=async(engine,input)=>{await guard();if(now()+1500>=deadline)throw Error('PROCESSING_STOP_RESERVE');const response=await backend.submit(engine,input,500,91,4096);append('all-ply',{game:game.game,block:block.block,attempt,engine,prefix:input.legal_prefix,seed:1979,response});return response};
    const result=await backend.play({prefix:JSON.parse(JSON.stringify(block.prefix)),candidateColor:game.candidate_color,platform:block.platform,choose,log:x=>append('judge-ply',{game:game.game,attempt,...x})});
    const priorAttempts=row.attempts??[];row.attempts=[...priorAttempts,{attempt,result}];Object.assign(row,{result,status:result.kind==='invalid_pair'?'invalid':result.complete?'completed':'incomplete'});attemptRows.push(row);append('results',{game:game.game,attempt,...row});checkpoint();
    if(backend.needsRestart()){await stop();if(result.complete&&result.kind!=='invalid_pair')await start();}
    if(result.kind==='invalid_pair'){invalid=true;break;}if(!result.complete){incomplete=true;break;}
   }
   if(!invalid&&!incomplete&&attemptRows.length===2){pairDone=true;write('pair-'+block.block,{block:block.block,attempt,Xi:attemptRows.reduce((s,x)=>s+x.result.score,0)/2,games:attemptRows.map(x=>x.game)});break;}
   if(invalid&&attempt===0&&globalRetry<2){globalRetry++;for(const g of block.games){table[g.game-1].status='scheduled_retry';delete table[g.game-1].result;}checkpoint();append('retry',{block:block.block,attempt_next:1,globalRetry,prefix_sha256:block.prefix_sha256});await stop();await start();continue;}
   stopReason=invalid?'invalid_pair_retry_exhausted':'incomplete_game';break;
  }
  if(!pairDone)break;
 }
 }catch(e){stopReason=e.message;append('entry-error',{error:e.message,stack:e.stack});}
 finally{try{await stop()}catch(e){stopReason+=';'+e.message;}process.removeListener('SIGTERM',signal);process.removeListener('SIGINT',signal);checkpoint();}
 const platforms={};for(const platform of ['native-local','browser']){const pairs=blocks.filter(b=>b.platform===platform).filter(b=>b.games.every(g=>table[g.game-1].status==='completed')).map(b=>b.games.reduce((s,g)=>s+table[g.game-1].result.score,0)/2);platforms[platform]={completed_pairs:pairs.length,scheduled_pairs:8,complete:pairs.length===8,Xi:pairs,mean:pairs.length?pairs.reduce((a,b)=>a+b,0)/pairs.length:null};if(pairs.length===8)platforms[platform].L=Math.max(0,platforms[platform].mean-Math.sqrt(Math.log(20)/16));}
 const summary={runId,dry,stopReason,table,platforms,globalRetry,restarts,scheduled:32,completed:table.filter(x=>x.status==='completed').length,real_holdout_sends:dry?0:'see all-ply',remaining_pids:0,formal_attainment:false};write('results-table',table);write('summary',summary);return summary;
}
function ownDescendants(){const table=new Map();for(const name of fs.readdirSync('/proc'))if(/^\d+$/.test(name)){try{const s=fs.readFileSync('/proc/'+name+'/stat','utf8').split(')').slice(1).join(')').trim().split(/\s+/);table.set(Number(name),{pid:Number(name),ppid:Number(s[1]),starttick:Number(s[19]),state:s[0]});}catch{}}const ids=new Set([process.pid]);let change=true;while(change){change=false;for(const x of table.values())if(ids.has(x.ppid)&&!ids.has(x.pid)){ids.add(x.pid);change=true;}}return [...ids].filter(x=>x!==process.pid).map(x=>table.get(x)).filter(x=>x&&x.state!=='Z');}
async function realBackend({out}){
 // Lazy import: importing match-entry never creates a model, Worker, browser or native child.
 const {withArena}=require('./arena.cjs'),{runGame}=require('./game-loop.cjs');let release,readyResolve,readyReject;const ready=new Promise((r,j)=>{readyResolve=r;readyReject=j}),done=withArena(async a=>{readyResolve(a);await new Promise(r=>release=r);},{outputDir:out,warmReference:true}).catch(e=>{readyReject(e);throw e});let a;try{a=await ready;}catch(e){await done.catch(()=>{});throw e;}
 return {startup:'models loaded/warmed by immutable adapters; startup outside hand',clock:a.clock,submit:(...args)=>a.submit(...args).promise,play:runGame,needsRestart:a.needsRestart,stop:async()=>{release();await done;const remaining=ownDescendants();if(remaining.length)throw Error('OWN_DESCENDANTS_REMAIN '+JSON.stringify(remaining));return {remaining_pids:0,descendants:remaining,proof:'browser close awaited + native/ping idempotent abort/exit awaited + own /proc descendant scan'};}};
}
async function main(){if(process.argv[2]!=='--run'||!process.argv[3])throw Error('USAGE --run ACTUAL_COORDINATOR_FREEZE_TOKEN_JSON');const token=JSON.parse(fs.readFileSync(process.argv[3])),preregPath=BASE+'/preregister-v2.json';verifyToken(token,preregPath,BASE+'/entry-ready-revision3.json');if(Date.now()>=DEADLINE)throw Error('PROCESSING_DEADLINE');const prereg=JSON.parse(fs.readFileSync(preregPath)),poolPath=ROOT+'/.artifacts/ai-sigma/runs/SIGMA-ARENA-PREFLIGHT/holdout-proposal.json';if(sha(poolPath)!==prereg.pool_sha256)throw Error('POOL_SHA');const pool=JSON.parse(fs.readFileSync(poolPath));let runId=token.run_id;if(!/^[A-Za-z0-9_-]+$/.test(runId??''))throw Error('RUN_ID');const out=BASE+'/execution-'+runId;if(fs.existsSync(out))throw Error('RUN_ALREADY_EXISTS_NO_SILENT_RESUME');
 const checkPause=async()=>{if(fs.existsSync(BASE+'/PAUSE'))return true;for(const id of ['quoridor-4lc','quoridor-4lc.21']){const x=JSON.parse(execFileSync('bash',[ROOT+'/scripts/dev/beads.sh','show',id,'--json'],{timeout:5000,encoding:'utf8',env:{...process.env,UV_OFFLINE:'1',UV_NO_SYNC:'1',PYTHONDONTWRITEBYTECODE:'1'}}))[0];if(x.status==='blocked'||x.status==='closed'||x.labels?.includes('paused-by-user'))return true;}return false;};
 const result=await execute({prereg,pool,out,runId,createBackend:realBackend,checkPause});console.log(JSON.stringify({completed:result.completed,stopReason:result.stopReason}));}
async function diagnosticRealBackend(options){if(!path.resolve(options.out).startsWith(BASE+'/revision3/'))throw Error('DIAGNOSTIC_OUTPUT_SCOPE');const b=await realBackend(options);return {...b,play:undefined,submit:(engine,f,T,g,sims)=>{if(f.id!=='initial-p1'||!Array.isArray(f.legal_prefix)||f.legal_prefix.length!==0||sims!==4096||!(T===500&&g===91||engine==='native'&&T===10&&g===0&&f.diagnostic_step_delay_ms===500))throw Error('DIAGNOSTIC_FIXED_GOLDEN_ONLY');return b.submit(engine,f,T,g,sims);}};}
module.exports={schedule,verifyToken,execute,diagnosticRealBackend};if(require.main===module)main().catch(e=>{console.error(e.message);process.exitCode=1});
