const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const R=path.resolve(__dirname,'../..'),O=R+'/.artifacts/ai-sigma/resume-20261002/CANDIDATE-TRUE-MEAN-FPU';
async function abi(p){const e=(await WebAssembly.instantiate(fs.readFileSync(p),{})).instance.exports;return value=>{const text=new TextEncoder().encode(JSON.stringify(value)),h=e.ort_buffer(text.length);new Uint8Array(e.memory.buffer,e.ort_ptr(h),text.length).set(text);let o;try{o=e.ort_call(h);const r=JSON.parse(new TextDecoder().decode(new Uint8Array(e.memory.buffer,e.ort_ptr(o),e.ort_len(o))));assert(r.ok,r.error);return r.data;}finally{e.ort_free(h);if(o)e.ort_free(o);}};}
(async()=>{
 const box=vm.createContext({Math,JSON,Uint32Array,Float32Array,Map,Set,structuredClone});for(const f of ['game.js','context.js'])vm.runInContext(fs.readFileSync(R+'/tools/ai-sigma-actual-boundary-repair/'+f,'utf8'),box);vm.runInContext(fs.readFileSync(R+'/tools/ai-sigma-deep-node-comparison/deep-input.js','utf8'),box);
 const fixtures=JSON.parse(fs.readFileSync(R+'/research-data/ai-sigma/140-candidate-true-mean-fpu/fixed-inputs.json')).fixtures;for(const f of fixtures)box.deepCheckedState(f);assert.deepEqual(fixtures.map(f=>f.board.total_ply),[13,21]);assert(fixtures.every(f=>f.board.turn===1));const bad=structuredClone(fixtures[0]);bad.history_counts=[];assert.throws(()=>box.deepCheckedState(bad));
 const probe=[];for(const v of ['q0','fpu']){const call=await abi(O+'/build/'+v+'.wasm'),r=call({op:'mean_probe',generation:1});assert(r.ok);assert.equal(r.FPU_enabled,v==='fpu');probe.push({variant:v,...r});}
 for(const n of ['main','worker','producer','checkpoint','cache','reference'])new vm.Script(require('./adapters.cjs').script(n));
 const config=JSON.parse(fs.readFileSync(R+'/research-data/ai-sigma/140-candidate-true-mean-fpu/config.json'));assert.deepEqual(config.searches.map(s=>s.variant),['original','q0','fpu','fpu','q0','original']);assert.equal(config.searches.length,6);
 vm.runInContext(fs.readFileSync(__dirname+'/mean-main.js','utf8'),box);
 const synthetic={trace:{nodes:[],selections:[],visits:[{node_index:0,preN:0,postN:1,preSum:0,postSum:-.1498291,value_own_side:-.1498291}]},cp:{tree:[{index:0,visits:1,true_value_sum:-.1498291}]},variant:'q0'};box.meanLedgerGate(synthetic);const corrupt=structuredClone(synthetic);corrupt.trace.visits[0].postN=2;assert.throws(()=>box.meanLedgerGate(corrupt));
 const result={NN0:true,browser:false,wasm_private_fixture:true,probe,fixture_ids:fixtures.map(f=>f.id),routing_single_candidate_idle_reference:true,sessions2_not_shared:true,mean_float_transport_f32_restore:true,corrupt_ledger_and_input_rejected:true,fixed_order:true};fs.writeFileSync(O+'/mock.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({NN0:true,private_probe_variants:probe.length,cases_per_variant:probe[0].cases.length,fixtures:2,syntax:true}));
})().catch(e=>{console.error(e.stack);process.exitCode=1});
