from pathlib import Path
import json,hashlib,difflib,datetime
T=Path(__file__).parent;R=T.parents[1];D=R/'research-data/ai-sigma/140-candidate-true-mean-fpu';O=R/'.artifacts/ai-sigma/resume-20261002/CANDIDATE-TRUE-MEAN-FPU'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
c=json.loads((D/'config.json').read_text());fixtures=json.loads((D/'fixed-inputs.json').read_text())['fixtures'];binding=json.loads((D/'source-input-binding.json').read_text());binding['new_private']={str(p.relative_to(R)):sha(p) for p in (T/'private').rglob('*') if p.is_file()};binding['private_builds']=[json.loads((O/f'build-{v}.json').read_text()) for v in ['q0','fpu']]
for b in binding['private_builds']:
 for p,h in b['source'].items():assert sha(Path(p))==h,'BUILT_SOURCE_CHANGED'
for n in ['kernel.rs','lib.rs','research.rs']:
 old=R/'tools/ai-sigma-deep-node-comparison/baseline/src'/n;new=T/'private/src'/n;(D/(n+'.patch')).write_text(''.join(difflib.unified_diff(old.read_text().splitlines(True),new.read_text().splitlines(True),fromfile=str(old.relative_to(R)),tofile=str(new.relative_to(R)))))
(D/'source-input-binding.json').write_text(json.dumps(binding,indent=2)+'\n')
readonly=[R/'tools/ai-sigma-deep-node-comparison/deep-input.js',R/'tools/ai-sigma-actual-boundary-repair/reference-core.js',R/'models/experiments/ai-sigma/reference/sigma-pcr250/best.onnx',R/'.artifacts/ai-sigma/reference/SIGMA-WEB-REFERENCE/ort.min.js',R/'.artifacts/ai-sigma/reference/SIGMA-WEB-REFERENCE/ort-wasm-simd-threaded.jsep.wasm',R/'.artifacts/ai-sigma/runs/SIGMA-ORT-SEARCH/final.wasm']
(D/'source-before.json').write_text(json.dumps({'UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'own':{str(p.relative_to(R)):sha(p) for p in T.rglob('*') if p.is_file()},'readonly':{str(p.relative_to(R)):sha(p) for p in readonly},'served':{v:sha(O/'build'/f'{v}.wasm') for v in ['q0','fpu']}},indent=2)+'\n')
r={'issue':'quoridor-4lc.140','before_new_NN':True,'inputs':[{k:f[k] for k in ['id','board','history_count_key','history_counts','legal_prefix','legal_ids']} for f in fixtures],'input_SHA256':sha(D/'fixed-inputs.json'),'source_binding_SHA256':sha(D/'source-input-binding.json'),'mechanism_order':c['searches'],'K_definition':'rootincluded32sim, observedrootN32/edge31, terminal-noNN separate','hand_NN_max':192,'startup_NN':6,'sessions':2,'mean_definition':'actualnode own-side sum once per visit; rootinitial included; pseudo leaf excluded; ancestry alternating','N0':'mean absent, no division; artificial scoreQ0; normal expanded select follows a completedbackup','factor_only':'unvisitedQ0 versus f32(trueMean-.2f32sqrt(visitedOriginalPriorSum)); visitedQ unchanged','parity':'rootfeatures/rawNN/prior/allcompletedrootedges/Action/NN/depth/cap exact; addedlayoutarena reportedseparately','quality_exit':'parity/meanunresolved or allActionunchanged or input3FPU133 =>endquality0; onlynewlegalAction outsideinput3[161,133],input4[32,42] eligible allsuchstates','quality_order':['baseline_rep1','FPU_rep1','FPU_rep2','baseline_rep2'],'quality_max_rollouts':8,'quality_job_max_seconds':180,'quality_policy':'bothfixedSigma C1/FPU.2/first/temp0/originalorder, T500 cutoff402 adopt411 bounded2sample seed1979 totaltotalply200 goalpriority','quality_denominator':'forcedP2score win1/draw.5/loss0, typedresponsibilityloss separateinvalid/unfinished; sharedJudge/automation/lateflagspriority, unknownsharedFAULTunfinished','no_scientific_success_replacement':True,'no_extra_parity_NN':True,'numeric_float_transport':'Rust JSON f32 restored byMath.fround formean/signformula gates; exactoriginal/Q0 JSON CP parity','finite_bounds':'postselected2lost-lineinputs; notIID/holdout/generaloracle/119cause/500mscandidateperformance','optional_nonroot_nodes_max':7,'static_fixture_ref':{'path':str((O/'mock.json').relative_to(R)),'SHA256':sha(O/'mock.json'),'actual_private_Wasm_NN0':True,'real_terminal_observed':False}}
(D/'preregister.json').write_text(json.dumps(r,indent=2)+'\n');print('registered6 beforeNN; binaries/source/input bound')
