'use strict';
const fs=require('fs'),assert=require('assert'),{D,now,save}=require('./common.cjs'),{Engine}=require('./controller.cjs'),{createReference}=require('../ai-sigma-native-baseline/reference.cjs'),{createMonitor}=require('./pause-monitor.cjs');
const c=JSON.parse(fs.readFileSync(process.argv[2])),mock=process.argv.includes('--mock'),fixtures=JSON.parse(fs.readFileSync(D+'/inputs.json')).fixtures,{r}=createReference();
fs.mkdirSync(c.job_out,{recursive:true});const engines={},rows=[],inits=[],closings=[];let qualification=null,gen=0,NN=0;
const monitor=createMonitor({out:c.job_out,subjectIssue:c.issue,deadlineUTC:c.processing_deadline,windowEndUTC:'2026-10-03T12:47:38Z'});
const specs=[];for(const f of fixtures){for(const e of ['old','new','reference'])specs.push({fixture:f.id,engine:e,phase:'warm'});for(const e of ['old','new','reference','reference','new','old'])specs.push({fixture:f.id,engine:e,phase:'steady'});}
const statuses=specs.map((s,i)=>({...s,slot:i,status:'NOT_STARTED'}));save(c.job_out+'/status.json',statuses);
(async()=>{try{await monitor.start(e=>{qualification={code:e.code,message:e.message};for(const x of Object.values(engines))x.stopCurrent()});let currentFixture=null;
 for(let i=0;i<specs.length;i++){
  monitor.check();if(qualification)throw Error('CONTROL_LOST');if(mock&&i>=3)break;
  if(Date.now()>=Date.parse(c.processing_deadline)-60000)break;
  const spec=specs[i],f=fixtures.find(x=>x.id===spec.fixture);if(currentFixture!==f.id){for(const [engine,x]of Object.entries(engines)){closings.push({fixture:currentFixture,engine,close:await x.close()});delete engines[engine];}currentFixture=f.id;for(const name of ['old','new','reference']){engines[name]=new Engine(name);const t=now();const init=await engines[name].init(mock);inits.push({fixture:f.id,engine:name,total_ms:now()-t,init});}save(c.job_out+'/init.json',inits);}const state=r.fromPrefix(f.legal_prefix),expected=r.portState(state);assert(r.terminalResult(state)===null);
  const legal=Array.from(state.getLegalActions?.()??[]);statuses[i].status='STARTED';save(c.job_out+'/status.json',statuses);
  let cps=0,certified=null,cpEnd=null;const t0=now();let timeout=setTimeout(()=>{qualification={code:'SEARCH_TIMEOUT'};engines[spec.engine].stopCurrent()},60000);
  const result=await engines[spec.engine].request({op:'search',fixture_id:f.id,legal_prefix:f.legal_prefix,K:mock?4:800,generation:++gen,final_only:true,trace:false,NN_limit:Math.min(800,240000-NN),watchdog_ms:60000,...(mock?{mock:{value:.25}}:{})},x=>{cps++;const cp=x.cp;assert(cp.generation===gen);assert(Array.from(expected.legal).includes(cp.action));assert(cp.root_visits===(mock?4:800));assert(cp.root_edges.reduce((s,x)=>s+x[2],0)===(mock?3:799));certified=structuredClone(cp);cpEnd=now();});clearTimeout(timeout);
  const z=result.data;NN+=z.NN_calls;assert(NN<=240000);assert(!z.primary,JSON.stringify(z.primary));assert(cps===1&&certified);assert(z.zero.activeNN===0&&z.zero.handles===0&&!z.zero.active);assert(JSON.stringify(z.root_state.features_bits)===JSON.stringify(expected.features_bits));assert(z.first_NN.features_bits.length===648&&z.first_NN.NN_bits.length===137);if(qualification)throw Error('QUALIFICATION_UNKNOWN');
  const row={...spec,slot:i,t0,final_CP_validation_end:cpEnd,elapsed_ms:cpEnd-t0,result_receipt_ms:result.controller_receive_ms,post_CP_cleanup_ms:result.controller_receive_ms-cpEnd,CP_count:cps,cp:certified,first_NN:z.first_NN,root_state:z.root_state,NN_actual:z.NN_calls,returned:z.returned_NN,discarded:z.discardedNN,terminal_noNN:z.terminal_noNN,cache_hits:z.cache_hits,bridge:z.bridge,NN_API_sum_ms:z.spans.reduce((s,x)=>s+x.API_ms,0),NN_pipe_sum_ms:z.spans.reduce((s,x)=>s+x.pipe_ms,0),worker_elapsed_ms:z.request_ms,zero:z.zero,host_load:fs.readFileSync('/proc/loadavg','utf8')};
  rows.push(row);fs.writeFileSync(c.job_out+'/rows.jsonl',JSON.stringify(row)+'\n',{flag:'a'});statuses[i].status='COMPLETE';save(c.job_out+'/status.json',statuses);console.log(JSON.stringify({slot:i,fixture:spec.fixture,engine:spec.engine,phase:spec.phase,elapsed_ms:row.elapsed_ms,NN:row.NN_actual,CP:cps}));
 }
 }catch(e){qualification=qualification??{code:e.message,stack:e.stack};console.error(e.stack)}finally{for(const [engine,x]of Object.entries(engines)){try{closings.push({engine,close:await x.close()})}catch(e){closings.push({engine,error:e.stack})}}await monitor.stop();save(c.job_out+'/stop.json',{UTC:new Date().toISOString(),qualification,closings,NN_actual:NN,rows:rows.length,monitor_state:monitor.state});}if(qualification)process.exitCode=1;})().catch(e=>{console.error(e);process.exitCode=1});
