'use strict';const assert=require('assert'),fs=require('fs'),{ROOT,Pipe,now,save}=require('./common.cjs'),{Engine}=require('./controller.cjs'),{createReference}=require('../ai-sigma-native-baseline/reference.cjs');const {r}=createReference(),c=JSON.parse(fs.readFileSync(process.argv[2]));fs.mkdirSync(c.job_out,{recursive:true});
(async()=>{const rows=[],closed=[],e=new Engine('new');try{await e.init(true);
for(const K of [1,4]){let n=0;const z=(await e.request({op:'search',legal_prefix:[],generation:K,K,final_only:true,mock:{value:.25}},()=>n++)).data;assert(!z.primary&&z.cp.root_visits===K&&z.cp.root_edges.reduce((s,x)=>s+x[2],0)===K-1&&n===1);assert(z.bridge.ops.checkpoint===1);rows.push({K,cp:z.cp,bridge:z.bridge,zero:z.zero});}
const t=now(),p=e.request({op:'search',legal_prefix:[],generation:9,K:1000000,final_only:true,mock:{delay_ms:10,value:.25}});const timer=setTimeout(()=>e.stopCurrent(),25);const z=(await p).data;clearTimeout(timer);assert(!z.primary&&z.zero.activeNN===0&&z.zero.handles===0);rows.push({artificial_pending_cancel:true,wall_ms:now()-t,completed:z.completed,discard:z.discardedNN,zero:z.zero});
}finally{closed.push(await e.close())}
const pipe=new Pipe(ROOT+'/.artifacts/ai-sigma/resume-20261003/NATIVE-BASELINE/build/target/release/faithful-native',[]);
try{const h=(await pipe.ask({op:'new',prefix:[],simulations:8,generation:21})).data.handle;assert(!(await pipe.ask({op:'begin',handle:h,generation:22})).ok);const q=(await pipe.ask({op:'begin',handle:h,generation:21})).data;assert(!(await pipe.ask({op:'resume',handle:h,generation:21,token:q.token+1,logits:Array(136).fill(0),value:.25})).ok);await pipe.ask({op:'free',handle:h});assert(!(await pipe.ask({op:'new',prefix:[],simulations:1000001,generation:1})).ok);rows.push({stale_generation_token_guard_typed:true});}finally{closed.push(await pipe.stop())}
const e2=new Engine('reference');try{await e2.init(true);let n=0;const z=(await e2.request({op:'search',legal_prefix:[],generation:31,K:4,final_only:true,mock:{value:.25,artificial_state:{boardsize:9,depth:199,player1pos:[4,0],player2pos:[4,8],walls_p1:0,walls_p2:0,walls_initial:10}}},()=>n++)).data;assert(!z.primary&&z.NN_calls===1&&z.terminal_noNN===3&&n===1);rows.push({NN0_artificial_terminal_noNN_reference:true,NN:z.NN_calls,terminal:z.terminal_noNN,CP:z.cp});}finally{closed.push(await e2.close())}
let st=r.fromPrefix([]),prefix=[];while(st.player1pos[1]<7||st.getCurrentPlayer()!==1){const pawns=st.getLegalActions().filter(a=>a.type==='pawn');const a=st.getCurrentPlayer()===1?pawns.find(a=>a.direction[0]===0&&a.direction[1]>0):pawns.find(a=>a.direction[0]===(st.player2pos[0]>=8?-1:1)&&a.direction[1]===0);assert(a);prefix.push(a);st=st.next(a);}const win=st.getLegalActions().find(a=>a.type==='pawn'&&a.direction[0]===0&&a.direction[1]===1);assert(win);const bias=r.actionToIndex(win,9);const e3=new Engine('new');try{await e3.init(true);const z=(await e3.request({op:'search',legal_prefix:prefix,generation:40,K:4,final_only:true,mock:{value:.25,bias}})).data;assert(!z.primary&&z.NN_calls===1&&z.terminal_noNN===3&&z.cp.root_visits===4&&z.bridge.ops.checkpoint===1);rows.push({actual_native_terminal_noNN:3,rootN:4,NN0_calls:z.NN_calls,bridge:z.bridge});const terminal=(await e3.request({op:'search',legal_prefix:[...prefix,win],generation:41,K:4,final_only:true,mock:{value:.25}})).data;save(c.job_out+'/native-root-terminal.json',terminal);assert(!terminal.primary&&terminal.NN_calls===0&&terminal.completed===0&&terminal.cp.action===null&&terminal.cp.root_edges.length===0);rows.push({native_root_terminal:true,typed_not_Kcomplete:true,completed:terminal.completed,NN0_calls:0,zero:terminal.zero});}finally{closed.push(await e3.close())}
save(c.job_out+'/mock.json',{NN_executed:0,rows,closed,terminal_reference_artificial_only:true,native_root_terminal_and_terminal_noNN:true});console.log(JSON.stringify({NN:0,cases:rows.length}));})().catch(e=>{save(c.job_out+'/mock-failure.json',{error:e.stack});console.error(e.stack);process.exitCode=1});
