'use strict';const fs=require('fs'),crypto=require('crypto'),assert=require('assert'),{ROOT,D,now,save}=require('./common.cjs'),{Engine}=require('./controller.cjs'),{createReference}=require('../ai-sigma-native-baseline/reference.cjs'),{target,validate}=require('./schema.cjs');const{r}=createReference(),core=+process.argv[2],out=process.argv[3];fs.mkdirSync(out,{recursive:true});let engine=null,usedNN=0,generation=0,aborted=false;const write=(name,x)=>fs.appendFileSync(out+'/'+name,JSON.stringify(x)+'\n');
const rng=seed=>{let x=parseInt(seed.slice(0,8),16)||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;x>>>=0;return x/4294967296}};
async function search(state,prefix,q){let cpCount=0;const t=now(),ans=await engine.request({op:'search',legal_prefix:prefix,fixture_id:q.id,generation:++generation,K:q.K??64,final_only:true,NN_limit:Math.max(0,q.NN_budget-usedNN),watchdog_ms:10000,trace:false,...(q.mock?{mock:{logit:0,value:.25}}:{})},()=>{cpCount++});const data=ans.data;usedNN+=data.NN_calls;assert(!data.primary,data.primary?.message);assert(data.zero.activeNN===0&&data.zero.handles===0&&!data.zero.active&&engine.pending.size===0,'ZERO');assert(data.NN_calls===data.spans.length,'NN_RETURN');assert(data.cp&&data.cp.simulations===(q.K??64)&&data.cp.root_visits===(q.K??64),'FIXED_K_INCOMPLETE');assert(cpCount===1,'FINAL_ONLY_CP');assert(JSON.stringify(data.root_state)===JSON.stringify(r.portState(state)),'ROOT_STATE');return{data,wall_ms:now()-t,cpCount};}
async function game(spec,q){const started=now(),rows=[];let result=null;write('game-starts.jsonl',{game_id:spec.game_id,UTC:new Date().toISOString(),lineage:spec.lineage});if(!spec.generated){result={status:'GENERATION_UNKNOWN',winner:null};write('games.jsonl',{...spec,...result,rows:0,elapsed_ms:now()-started});return{game_id:spec.game_id,...result,rows:0};}
let state=r.fromPrefix(spec.opening.legal_prefix),prefix=structuredClone(spec.opening.legal_prefix),newply=0;const random=rng(spec.sampling_seed);
try{while(true){if(aborted)throw Error('CONTROL_ABORT');const terminal=r.terminalResult(state);if(terminal){result={status:terminal.winner?'GOAL':state.depth>=200?'DRAW200':'DRAW_NOLEGAL',winner:terminal.winner};break;}
const z=await search(state,prefix,{...q,id:spec.game_id}),cp=z.data.cp,legal=state.getLegalActions(),mapping=legal.map(a=>{const real=r.actionToIndex(a,9);return[r.rustAction(state,a),state.getCurrentPlayer()===2?r.vertPolicyPermutation(9)[real]:real]}),visits=Array(136).fill(0);for(const [action,prior,N,sum]of cp.root_edges){const m=mapping.find(m=>m[0]===action);assert(m,'CP_ACTION_LEGAL');visits[m[1]]=N;}const edgeSum=visits.reduce((a,b)=>a+b,0),pi=visits.map(x=>x/edgeSum),order=mapping.map(m=>m[0]);let action;
if(q.temperature_mode===0||newply>=16){const max=Math.max(...cp.root_edges.map(e=>e[2]));action=cp.root_edges.find(e=>e[2]===max)[0];}else{let u=random()*edgeSum;action=cp.root_edges.at(-1)[0];for(const e of cp.root_edges){u-=e[2];if(u<0){action=e[0];break;}}}
const row={row_id:spec.game_id+'-ply-'+state.depth,game_id:spec.game_id,lineage:spec.lineage,split:spec.split,side:state.getCurrentPlayer(),ply:state.depth,new_ply:newply,state_key:state._positionKey(),history_counts:Array.from(state.position_history),features648_bits:z.data.first_NN.features_bits,NN137_bits:z.data.first_NN.NN_bits,legal_order209:order,mapping136:mapping,visits136:visits,pi136:pi,rootN:cp.root_visits,edgeSum,rootNN:z.data.first_NN.value,rootmean:cp.root_mean,leafNN:z.data.last_leafNN??null,rootNN_view:'root side-to-move',rootmean_view:'root side-to-move',NN_completed:z.data.NN_calls,terminal_noNN:z.data.terminal_noNN,NN_discarded:z.data.discardedNN,action209:action,action:legal[order.indexOf(action)],tau:q.temperature_mode===0||newply>=16?0:1,model:q.model??'d790',teacher_engine:q.engine??'reference',provider:'CPUORT1.30/intra-inter1/SEQUENTIAL',search:'C1/FPU.2/f64/firsttie/trueMean/visitfinish',seed:spec.sampling_seed,source:process.env.SIGMA77_GIT_COMMIT??null,wall_ms:z.wall_ms,API_ms:z.data.spans.reduce((s,x)=>s+x.API_ms,0),pipe_ms:z.data.spans.reduce((s,x)=>s+x.pipe_ms,0),CP_received:z.cpCount,z_p1:null,z_stm:null,value_eligible:false};validate(row,q.K??64);rows.push(row);write('raw-rows.jsonl',row);const actionObj=legal[order.indexOf(action)];prefix.push(actionObj);state=state.next(actionObj);newply++;
if(newply>=200){result={status:'NEWPLY_CAP_UNKNOWN',winner:null};break;}if(q.mock&&newply===2){result={status:'NN0_MOCK_UNFINISHED',winner:null};break;}
}}catch(e){result={status:e.message==='CONTROL_ABORT'?'CONTROL_UNKNOWN':'ENGINE_OR_SCHEMA_UNKNOWN',winner:null,error:e.stack};}
const final={game_id:spec.game_id,lineage:spec.lineage,split:spec.split,core,status:result.status,winner:result.winner,error:result.error??null,rows:rows.length,plies:prefix.length,legal_prefix:prefix,final_key:state._positionKey(),elapsed_ms:now()-started,used_arena_NN:usedNN};write('games.jsonl',final);for(const row of rows){target(row,result.winner);validate(row,q.K??64);write('rows.jsonl',row);}return final;}
process.on('message',q=>{if(q.op==='abort'){aborted=true;engine?.stopCurrent();return;}void(async()=>{if(q.op==='init'){engine=new Engine(q.engine??'reference',q.model??null);const init=await engine.init(q.mock);if(!q.mock){assert.equal(init.info.version,'1.30.0');assert.deepStrictEqual(init.info.providers,['CPUExecutionProvider']);assert.equal(init.info.intra,1);assert.equal(init.info.inter,1);assert(init.info.sequential);assert.deepStrictEqual(init.info.affinity,[core]);}save(out+'/init.json',init);return init;}if(q.op==='games'){const results=[];for(const g of q.games){if(aborted)break;results.push(await game(g,q));if(results.at(-1).status.includes('UNKNOWN'))break;}return{core,results,usedNN};}if(q.op==='close'){const closed=await engine.close();save(out+'/close.json',{closed,usedNN,zero:engine.pending.size===0});return{core,closed,usedNN};}})().then(data=>{process.send({id:q.id,data});if(q.op==='close')process.disconnect();}).catch(e=>process.send({id:q.id,error:e.stack}));});
