const nativePostMessage=postMessage.bind(globalThis);const producerMarkers=[];function emit(m){const begin=performance.timeOrigin+performance.now();m.producer_post_begin_ms=begin;nativePostMessage(m);producerMarkers.push({kind:m.kind,sequence:m.sequence??null,start_ms:begin,end_ms:performance.timeOrigin+performance.now()});}
// 97: same instrumentation in both conditions; only cooperative clock differs.
importScripts('/ort/ort.min.js','/candidate-host.js','/checkpoint.js','/game.js','/context.js','/reference-core.js','/reference-control-run.js');
let b,generation=0,active=false,activeNN=0;const epoch=()=>performance.timeOrigin+performance.now(),yieldTask=()=>new Promise(r=>setTimeout(r,0)),busy=ms=>{const end=epoch()+ms;while(epoch()<end){}};
function checkIdentity(id){if(!['candidate','reference'].includes(id.engine)||id.limits.seed!==1979||(id.engine==='candidate'?(id.limits.max_nodes!==512||id.limits.max_depth!==24):(id.limits.max_nodes!==null||id.limits.max_depth!==null)))throw Error('PRODUCER_LIMITS');const s=id.fixture?referenceState(id.fixture):fromPrefix(id.legal_prefix),h=Array.from(s.position_history).sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:0);let a=fromPrefix([]),p=[];for(const x of id.legal_prefix??[]){p.push(rustAction(a,x));a=a.next(x)}if(!id.fixture&&JSON.stringify(p)!==JSON.stringify(id.prefix)||s._positionKey()!==id.key||JSON.stringify(h)!==JSON.stringify(id.history)||id.epoch!==id.generation||id.model!=='d790dac68389f7602ff8a887a2385417d3c925fe22da7164c86e9226f943908d')throw Error('PRODUCER_IDENTITY');}
function cooperative(d){return d.tail_condition==='cooperative';}
async function run(d,direct=false){if(active||activeNN||b.liveHandles())throw Error('SEARCH_OVERLAP_OR_OLD_HANDLE');checkIdentity(d.identity);if(b.digest!==d.identity.model)throw Error('MODEL_BIND');active=true;generation=d.identity.generation;let seq=0,rootValue=null;producerMarkers.length=0;const nn=[],numeric=[],original=b.infer;
 b.infer=async bits=>{if(activeNN)throw Error('NN_OVERLAP');activeNN++;const start=epoch();try{if(d.before_first_nn_busy_ms&&!nn.length)busy(d.before_first_nn_busy_ms);const r=await original(bits),end=epoch();nn.push({awaiter_start_ms:start,awaiter_end_ms:end,session_run_start_ms:r.session_run_start_ms,session_run_end_ms:r.session_run_end_ms,nn_ms:r.nn_ms});if(!numeric.length){rootValue=r.value;numeric.push({features_bits:Array.from(bits),policy_logits:r.logits,value:r.value});}return r;}finally{activeNN--;}};
 let result;try{result=await runOwned({fixture:d.identity.fixture??undefined,prefix:d.identity.prefix??undefined,...(cooperative(d)?{cooperative_clock:true,t0:d.worker_limits.deadline_ms-500,T_ms:500,g_ms:98}:{}),generation,request_id:d.identity.request_id,simulations:d.identity.limits.simulations,max_nodes:512,max_depth:24,capture_tree:!!d.capture_tree,capture_trace:!!d.capture_tree},{b,epoch,yieldTask,getGeneration:()=>generation,completed:o=>{if(direct)return;const publicOwned=JSON.parse(JSON.stringify(o));publicOwned.cp.tree=[];const m={kind:'snapshot',identity:d.identity,producer_identity:d.identity,sequence:++seq,owned:publicOwned,value:o.cp.terminal_value??rootValue,sent_ms:epoch()};if(d.notify_delay_ms)setTimeout(()=>emit(m),d.notify_delay_ms);else emit(m);if(d.hardfault_after_cp===seq){emit({kind:'fault',identity:d.identity,error:'INJECTED_HARDFAULT',producer_fault_ms:epoch(),sent_ms:epoch()});throw Error('INJECTED_HARDFAULT');}}});
  if(result.error)emit({kind:'fault',identity:d.identity,error:result.error,producer_fault_ms:epoch(),sent_ms:epoch()});
  emit({kind:'private_done',identity:d.identity,result,NN:nn,numeric,producer_markers:producerMarkers.splice(0),worker_done_ms:epoch(),direct});
 }catch(e){emit({kind:'fault',identity:d.identity,error:e.message,producer_fault_ms:epoch(),sent_ms:epoch()});}finally{b.infer=original;active=false;emit({kind:'stopped',identity:d.identity,post_markers_tail:producerMarkers.splice(0),stop:{live_searches:result?.live_searches??null,handles:b.liveHandles(),activeNN,active,NN_attempts:result?.calls??null,completed_NN:result?.completed_NN??null,at_ms:epoch(),error:result?.error??null}});}}
onmessage=async({data:d})=>{if(d.kind==='cancel'){generation=d.generation;emit({kind:'cancel_ack',generation,at_ms:epoch()});return;}if(d.kind==='ping'){emit({kind:'ping',id:d.id,at_ms:epoch()});return;}
 try{if(d.kind==='load'){b=await loadOrtHost();emit({kind:'ready',digest:b.digest,threads:b.threads,proxy:b.proxy,model_load_ms:b.load_ms,compile_ms:b.compile_ms,handles:b.liveHandles(),activeNN});}
 else if(d.kind==='startup_root'){if(active||activeNN||b.liveHandles())throw Error('STARTUP_OVERLAP');activeNN++;let row;try{if(d.engine==='candidate'){const n=await b.numeric(d.fixture);row={features_bits:n.features_bits,policy_logits:n.logits,value:n.value,raw_prior:n.raw_prior};}else{const s=referenceState(d.fixture),f=s.toNNInput(),bits=Array.from(new Uint32Array(f.buffer,f.byteOffset,f.length)),n=await b.infer(bits);row={features_bits:bits,policy_logits:n.logits,value:n.value};}}finally{activeNN--;}emit({kind:'startup_root',engine:d.engine,fixture_id:d.fixture.id,row,handles:b.liveHandles(),activeNN,live_searches:0,active,at_ms:epoch()});}
 else if(d.kind==='mock'){checkIdentity(d.identity);const o=structuredClone(d.owned);o.identity={request_id:d.identity.request_id,generation:d.identity.generation,fixture:d.identity.fixture,prefix:d.identity.prefix,seed:1979,simulations:d.identity.limits.simulations,max_nodes:d.identity.limits.max_nodes,max_depth:d.identity.limits.max_depth};o.cp.generation=d.identity.generation;o.cp.tree=[];o.completed_at=epoch();if(d.identity.engine==='reference'){const terminal=!!terminalResult(d.identity.fixture?referenceState(d.identity.fixture):fromPrefix(d.identity.legal_prefix));o.cp.simulations=terminal?0:Math.max(0,o.cp.simulations-1);o.cp.root_visits=terminal?0:o.cp.simulations+1;if(!terminal)o.cp.action=o.cp.root_edges.reduce((best,e)=>e[2]>best[2]?e:best,o.cp.root_edges[0])[0];}emit({kind:'snapshot',identity:d.identity,producer_identity:d.identity,sequence:1,owned:o,value:d.value,sent_ms:epoch(),mock_NN0:true});}
 else if(d.kind==='numeric'){checkIdentity(d.identity);if(active||activeNN||b.liveHandles())throw Error('NN_OVERLAP');activeNN++;try{const r=await b.numeric(d.numeric_fixture);emit({kind:'private_done',identity:d.identity,numeric:[{features_bits:r.features_bits,policy_logits:r.logits,value:r.value,raw_prior:r.raw_prior,raw_legal:r.raw_legal,effective_legal:r.effective_legal}],NN:[{session_run_start_ms:r.session_run_start_ms,session_run_end_ms:r.session_run_end_ms}],result:{error:null},numeric_only:true});}finally{activeNN--;emit({kind:'stopped',identity:d.identity,post_markers_tail:producerMarkers.splice(0),stop:{live_searches:0,handles:b.liveHandles(),activeNN,active:false}});}}else if(d.kind==='request'||d.kind==='direct'){if(d.identity.engine==='reference')await runReference(d,d.kind==='direct');else await run(d,d.kind==='direct');}else if(d.kind==='drop'){if(active||activeNN||b.liveHandles())throw Error('DROP_ACTIVE');await b.drop();emit({kind:'dropped',handles:b.liveHandles(),activeNN,at_ms:epoch()});}
 }catch(e){postMessage(d.identity?{kind:'fault',identity:d.identity,error:e.message,producer_fault_ms:epoch(),sent_ms:epoch()}:{kind:'failed',error:e.message,error_detail:{name:e.name,message:e.message,code:e.code??null,stack:e.stack??null,stage:d.kind}});}};

// Same Sigma C1/FPU.2/first tie/temperature0 kernel, root expansion outside sims.
const stamp=epoch;let clockContext=null;function check(c,beforeNewWork=false){if(c&&c.generation!==generation)throw Error('STALE_GENERATION');if(beforeNewWork&&c?.cooperative&&epoch()>=c.nn_cutoff_ms)throw Error('guard');}
async function nnEvaluator(state,legal){if(!legal.length)throw Error('NN_EMPTY_LEGAL');check(clockContext,true);const features=state.toNNInput();const bits=Array.from(new Uint32Array(features.buffer,features.byteOffset,features.length));check(clockContext,true);const r=await b.infer(bits);check(clockContext);const perm=state.isPlayer1Turn()?null:vertPolicyPermutation(9),ix=legal.map(a=>{const k=actionToIndex(a,9);return perm?perm[k]:k}),max=Math.max(...ix.map(k=>r.logits[k])),ex=ix.map(k=>Math.exp(r.logits[k]-max)),sum=ex.reduce((a,b)=>a+b,0);return[ex.map(x=>x/sum),r.value];}
function referenceCP(root,c,id){const term=terminalResult(root.state),pick=term?null:pickFromVisits(root.children,0);return{generation:id.generation,action:pick?rustAction(root.state,pick.action):null,terminal_value:term?.value??null,simulations:c.simulations,nn_calls:c.nnCalls,root_visits:root.visitCount,root_edges:term?[]:root.children.map(n=>[rustAction(root.state,n.action),n.prior,n.visitCount,n.valueSum]),policy_fallbacks:0,value_fallbacks:0,tree:[]};}
function referenceTree(n){return{action:n.action,prior:n.prior,basePrior:n.basePrior,visitCount:n.visitCount,valueSum:n.valueSum,isExpanded:n.isExpanded,children:n.children.map(referenceTree)};}
async function runReference(d,direct){if(active||activeNN||b.liveHandles())throw Error('SEARCH_OVERLAP_OR_OLD_HANDLE');checkIdentity(d.identity);if(b.digest!==d.identity.model)throw Error('MODEL_BIND');active=true;generation=d.identity.generation;producerMarkers.length=0;const original=b.infer,nn=[],numeric=[],trace=[];let rootValue=null,seq=0,result,c={generation,cooperative:cooperative(d),nn_cutoff_ms:d.worker_limits?.nn_cutoff_ms,nnCalls:0,simulations:0,spans:[],steps:[],onComplete:null};clockContext=c;
 b.infer=async bits=>{if(activeNN)throw Error('NN_OVERLAP');activeNN++;const start=epoch();try{if(d.before_first_nn_busy_ms&&!nn.length)busy(d.before_first_nn_busy_ms);c.nnCalls++;const r=await original(bits);nn.push({awaiter_start_ms:start,awaiter_end_ms:epoch(),session_run_start_ms:r.session_run_start_ms,session_run_end_ms:r.session_run_end_ms,nn_ms:r.nn_ms});if(!numeric.length){rootValue=r.value;numeric.push({features_bits:bits,policy_logits:r.logits,value:r.value});}return r;}finally{activeNN--;}};
 function completed(root){check(c);const cp=referenceCP(root,c,d.identity),owned={identity:{request_id:d.identity.request_id,generation,fixture:d.identity.fixture,prefix:d.identity.prefix,seed:1979,simulations:d.identity.limits.simulations,max_nodes:null,max_depth:null},cp,completed_at:epoch(),completed_token:c.nnCalls||null,completed_NN:c.nnCalls,NN_attempts:c.nnCalls,pending_token:null};if(d.capture_tree)trace.push({cp:structuredClone(cp),tree:referenceTree(root)});result={cp,owned,trace,spans:c.spans,calls:c.nnCalls,completed_NN:c.nnCalls,error:null,fallback:0,live_searches:0};if(!direct){const m={kind:'snapshot',identity:d.identity,producer_identity:d.identity,sequence:++seq,owned:structuredClone(owned),value:cp.terminal_value??root.qValue,sent_ms:epoch()};if(d.notify_delay_ms)setTimeout(()=>emit(m),d.notify_delay_ms);else emit(m);if(d.hardfault_after_cp===seq){emit({kind:'fault',identity:d.identity,error:'INJECTED_HARDFAULT',producer_fault_ms:epoch(),sent_ms:epoch()});throw Error('INJECTED_HARDFAULT');}}}
 try{const state=d.identity.fixture?referenceState(d.identity.fixture):fromPrefix(d.identity.legal_prefix),term=terminalResult(state);if(term){const root=new MCTSNode(state);completed(root);}else if(direct){const root=await runMCTSControl(state,d.identity.limits.simulations,nnEvaluator,generation);completed(root);}else{c.onComplete=completed;await runMCTS(state,d.identity.limits.simulations,nnEvaluator,generation);}emit({kind:'private_done',identity:d.identity,result,NN:nn,numeric,producer_markers:producerMarkers.splice(0),worker_done_ms:epoch(),direct});}
 catch(e){result={error:e.message,calls:c.nnCalls,completed_NN:nn.length,live_searches:0};emit({kind:'fault',identity:d.identity,error:e.message,producer_fault_ms:epoch(),sent_ms:epoch()});emit({kind:'private_done',identity:d.identity,result,NN:nn,numeric,trace,producer_markers:producerMarkers.splice(0),worker_done_ms:epoch(),direct});}
 finally{c.onComplete=null;clockContext=null;b.infer=original;active=false;emit({kind:'stopped',identity:d.identity,post_markers_tail:producerMarkers.splice(0),stop:{live_searches:0,handles:b.liveHandles(),activeNN,active,NN_attempts:c.nnCalls,completed_NN:nn.length,at_ms:epoch(),error:result?.error??null}});}}
