'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{monitorEventLoopDelay}=require('perf_hooks');
const T=path.resolve(__dirname,'../ai-sigma-actual-boundary-repair'),C=require(T+'/caller.cjs'),J=require(T+'/judge.cjs'),F=require(T+'/final-envelope.cjs'),{freeze}=require(T+'/early-cache.cjs');
const ROOT=path.resolve(__dirname,'../..'),OUT=ROOT+'/.artifacts/ai-sigma/resume-20261002/TAIL-TRANSPORT';
const MODEL='d790dac68389f7602ff8a887a2385417d3c925fe22da7164c86e9226f943908d';
const clock={now:C.now,wall:Date.now,delay:(ms,fn)=>setTimeout(fn,ms),clear:clearTimeout};
function schedule(){const rows=[];for(const [fi,fixture]of ['initial-p1','asym-hv-p2','straight-jump-p2'].entries())for(const engine of fi%2?['reference','candidate']:['candidate','reference'])for(const [k,condition]of ['baseline','cooperative','cooperative','baseline','baseline','cooperative'].entries())rows.push({index:rows.length+1,fixture_id:fixture,engine,condition,sample:k<2?'warm':'steady',rep:k<2?0:(k<4?1:2)});return rows;}
function validate(c){assert.equal(c.issue,'quoridor-4lc.97');assert.equal(c.diagnostic,true);assert.equal(c.actual_go,false);assert.equal(c.holdout,false);assert.equal(c.model_sha256,MODEL);assert.equal(c.seed,1979);assert.deepEqual(c.affinity,[2]);assert.equal(c.NNthreads,1);assert.deepEqual(c.clock,{T:500,reserve:89,commit:9,cutoff:402,seal:411});assert.deepEqual(c.schedule,schedule());assert.equal(c.processing_deadline,'2026-10-02T03:44:25Z');assert(/^[A-Za-z0-9_-]+$/.test(c.run_id));return c;}
function bounded(p,ms,label){let t;return Promise.race([p,new Promise((_,reject)=>t=setTimeout(()=>reject(Error(label)),ms))]).finally(()=>clearTimeout(t));}
async function main(){assert.equal(process.argv[2],'--config');const c=validate(JSON.parse(fs.readFileSync(process.argv[3]))),dir=OUT+'/'+c.run_id;fs.mkdirSync(dir,{recursive:false});const save=(n,x)=>fs.writeFileSync(dir+'/'+n+'.json',JSON.stringify(x)+'\n'),append=(n,x)=>fs.appendFileSync(dir+'/'+n+'.jsonl',JSON.stringify(x)+'\n');save('config',c);
 const fixtures=JSON.parse(fs.readFileSync(ROOT+'/.artifacts/ai-sigma/reference-fixtures/SIGMA-PARITY-PLAN/fixtures.json')).fixtures,monitor=require(T+'/pause-check.cjs').createMonitor({out:dir,subjectIssue:c.issue,deadlineUTC:c.processing_deadline,windowEndUTC:'2026-10-02T05:39:12Z'});let backend=null,primary=null,secondary=[],signals=null,rows=[],previousACK=null;const signal=()=>{signals='SIGNAL'};process.once('SIGTERM',signal);process.once('SIGINT',signal);const guard=()=>{monitor.check();if(signals)throw Error(signals);if(Date.now()>=Date.parse(c.processing_deadline))throw Error('PROCESSING_DEADLINE');};
 const loop=monitorEventLoopDelay({resolution:10});loop.enable();
 try{await monitor.start();guard();backend=await require('./real-backend.cjs').factory(c.run_id,{base:dir,captureTree:false})({session:1,clock});assert(backend.startup.ready);save('startup-denominator',{session:1,root_NN:6,hand_NN:false});
 for(const spec of c.schedule){guard();if(previousACK)assert(previousACK.handles===0&&previousACK.activeNN===0&&previousACK.live_searches===0);const fixture=fixtures.find(f=>f.id===spec.fixture_id);assert(fixture);const t0=C.now();loop.reset();const node0=process.cpuUsage();const prefix=JSON.parse(JSON.stringify(fixture.legal_prefix)),state=J.state(prefix),ctx=J.context(state);const id=freeze({engine:spec.engine,request_id:c.run_id+'-'+spec.index,generation:spec.index,epoch:spec.index,fixture_id:fixture.id,fixture:null,legal_prefix:prefix,prefix:J.ids(prefix),key:ctx.key,history:ctx.history,model:MODEL,schema:'8x9x9-f32/136logits/value1/rust209',limits:{simulations:spec.engine==='reference'?100000:4096,max_nodes:spec.engine==='reference'?null:512,max_depth:spec.engine==='reference'?null:24,seed:1979},t0_ms:t0,deadline_ms:t0+500,seal_ms:t0+411,commit_cutoff_ms:t0+402,request_token:c.run_id+'-'+spec.index});
 // Condition resides in metadata, not producer identity. Both use same cache/public path.
 const context=backend.create({identity:id,meta:spec});context.spec.tail_condition=spec.condition;
 const raw=await bounded(backend.submit(context),2000,'PUBLIC_WATCHDOG_MISSING'),finalStart=C.now(),response=F.finalize(raw,id,clock),logStart=C.now();append('public',{spec,identity:id,response});const logEnd=C.now(),ack=await bounded(backend.finish(context,response),2000,'OWNED_ACK_MISSING'),ackStamp=C.now();assert(ack.handles===0&&ack.activeNN===0&&ack.live_searches===0&&!ack.ownership_error);previousACK=ack;
 const eventLoop={max_ms:loop.max/1e6,mean_ms:Number.isFinite(loop.mean)?loop.mean/1e6:null,p99_ms:loop.percentile(99)/1e6,scope:'Node event loop observed per hand, 10ms resolution; not exclusive engine CPU'};
 const inspectionStart=C.now(),diag=await backend.inspect(context),inspectionEnd=C.now(),offset=diag.clock.worker,privateRow=diag.private,nn=privateRow?.NN??[];
 const stopFile=JSON.parse(fs.readFileSync(dir+'/real-'+c.run_id+'-session1/stopACK-'+id.request_id+'.json'));const stop=stopFile.stop,workerInterval=Number.isFinite(stop.at_ms)?{early_ms:stop.at_ms-offset.hi_ms,late_ms:stop.at_ms-offset.lo_ms}:null;
 const api=nn.map(n=>({...n,node_start_early_ms:n.session_run_start_ms-offset.hi_ms,node_start_late_ms:n.session_run_start_ms-offset.lo_ms,node_end_early_ms:n.session_run_end_ms-offset.hi_ms,node_end_late_ms:n.session_run_end_ms-offset.lo_ms}));
 const row={...spec,identity:id,response,public_elapsed_ms:response.stamp_ms-t0,ACK_wall_ms:ackStamp-t0,ACK_wall_over500:ackStamp>id.deadline_ms,Worker_stop_interval:workerInterval,Worker_stop_class:!workerInterval?'missing':workerInterval.late_ms<=id.deadline_ms?'upper_le_D':workerInterval.early_ms>id.deadline_ms?'lower_gt_D':'straddles_D',stop_generated_worker_ms:stop.at_ms,stop_node_received_ms:stopFile.node_received_ms,stop_transport:stopFile.transport,producer_tail_markers:stopFile.post_markers_tail,stop_to_Node_interval:workerInterval?{lo_ms:stopFile.node_received_ms-workerInterval.late_ms,hi_ms:stopFile.node_received_ms-workerInterval.early_ms}:null,Node_received_to_confirm_ms:ackStamp-stopFile.node_received_ms,oldACK_before_t0:rows.length?rows.at(-1).ACK_stamp_ms<=t0:true,ACK_stamp_ms:ackStamp,owned_ACK:ack,API:api,NN:nn.length,post_public_NN_start_definite:api.filter(n=>n.node_start_early_ms>response.stamp_ms).length,post_public_NN_start_possible:api.filter(n=>n.node_start_late_ms>response.stamp_ms).length,NN_start_after_cutoff_worker:nn.filter(n=>n.awaiter_start_ms>=id.commit_cutoff_ms+offset.lo_ms).length,last_API_to_Worker_stop_ms:nn.length&&Number.isFinite(stop.at_ms)?stop.at_ms-nn.at(-1).session_run_end_ms:null,Worker_result:privateRow?.result??null,Worker_markers:privateRow?.producer_markers??null,page_markers:diag.page_markers,bindings:diag.bindings,root_cp:diag.cp,root_numeric:privateRow?.numeric?.[0]??null,worker_clock:offset,page_clock:diag.clock.page,node_event_loop:eventLoop,node_cpu_usage_us:process.cpuUsage(node0),public_Judge_clone_UTF8_ms:response.stamp_ms-finalStart,public_log_ms:logEnd-logStart,inspection_ms:inspectionEnd-inspectionStart};rows.push(row);append('turns',row);save('progress',{completed:rows.length,planned:36});
 }
 }catch(e){primary={name:e.name,message:e.message,stack:e.stack};save('primary',primary);}finally{if(backend)try{save('backend-stop',await bounded(backend.stop(),15000,'BACKEND_STOP_TIMEOUT'));}catch(e){secondary.push({stage:'backend-stop',message:e.message,stack:e.stack});}try{await monitor.stop();}catch(e){secondary.push({stage:'monitor-stop',message:e.message});}loop.disable();process.removeListener('SIGTERM',signal);process.removeListener('SIGINT',signal);}
 const summary={issue:c.issue,run:c.run_id,Git:c.git,diagnostic:true,actual_go:false,games:0,holdout_sends:0,planned:36,completed:rows.length,missing:36-rows.length,accepted:rows.filter(r=>r.response.accepted).length,late:rows.filter(r=>r.response.late).length,ACK_wall_over500:rows.filter(r=>r.ACK_wall_over500).length,Worker_stop_classes:rows.reduce((a,r)=>(a[r.Worker_stop_class]=(a[r.Worker_stop_class]??0)+1,a),{}),startup_NN:backend?6:0,hand_NN:rows.reduce((n,r)=>n+r.NN,0),primary,secondary,formal_fairness:false,formal_NI:false};save('summary',summary);console.log(JSON.stringify(summary));if(primary||secondary.length)process.exitCode=1;
}
module.exports={schedule,validate,clock};if(require.main===module)main().catch(e=>{console.error(e.stack);process.exitCode=1});
