'use strict';const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const T=path.resolve(__dirname,'../ai-sigma-actual-boundary-repair'),J=require(T+'/judge.cjs'),{clock:boundClock}=require('./browser.cjs');
const OUT=path.resolve(__dirname,'../../.artifacts/ai-sigma/resume-20261002/TAIL-TRANSPORT');
async function workerCase(engine,condition,{at=1000,hardfault=false}={}){
 let time=at,calls=0,sim=0,handle=0;const messages=[],clockStart=1000;
 const state=J.state([]),legal=state.getLegalActions().map(a=>J.rustAction(state,a)),id={engine,request_id:engine+'-'+condition+'-'+at,generation:1,epoch:1,fixture:null,legal_prefix:[],prefix:[],key:J.context(state).key,history:J.context(state).history,model:'d790dac68389f7602ff8a887a2385417d3c925fe22da7164c86e9226f943908d',limits:{seed:1979,simulations:3,max_nodes:engine==='candidate'?512:null,max_depth:engine==='candidate'?24:null}};
 const b={digest:id.model,e:{memory:{buffer:new ArrayBuffer(16)}},liveHandles:()=>handle,create(){handle=1;return 1},free(){handle=0},call(d){if(d.op==='raw')return {effective_legal:legal,terminal:null};if(d.op==='begin')return {pending:true,token:sim+1,features_bits:Array(648).fill(0)};if(d.op==='resume'){sim++;return{done:sim>=3}}if(d.op==='checkpoint')return {generation:1,action:legal[0],simulations:sim,root_edges:legal.map((a,i)=>[a,1/legal.length,i===0?Math.max(0,sim-1):0,0]),policy_fallbacks:0,value_fallbacks:0};if(d.op==='cancel')return {};throw Error('UNKNOWN_MOCK_OP')},async infer(){calls++;time+=210;return{logits:Array(136).fill(0),value:0,nn_ms:210,session_run_start_ms:time-210,session_run_end_ms:time}}};
 const context=vm.createContext({console,structuredClone,performance:{timeOrigin:0,now:()=>time},postMessage:m=>messages.push(structuredClone(m)),importScripts(){},setTimeout(fn){time++;fn();},clearTimeout(){},...J});
 vm.runInContext(fs.readFileSync(T+'/game.js','utf8')+'\n'+fs.readFileSync(T+'/context.js','utf8')+'\n'+fs.readFileSync(__dirname+'/checkpoint.js','utf8')+'\n'+fs.readFileSync(T+'/reference-core.js','utf8')+'\n'+fs.readFileSync(T+'/reference-control-run.js','utf8')+'\n'+fs.readFileSync(__dirname+'/early-worker.js','utf8')+'\nglobalThis.testB=x=>{b=x};',context);context.testB(b);
 context.d={kind:'request',identity:id,tail_condition:condition,worker_limits:{deadline_ms:clockStart+500,nn_cutoff_ms:clockStart+402},hardfault_after_cp:hardfault?1:null};await vm.runInContext('onmessage({data:d})',context);
 const stop=messages.findLast(m=>m.kind==='stopped');assert(stop&&stop.stop.handles===0&&stop.stop.activeNN===0&&stop.stop.live_searches===0);return {engine,condition,at,calls,messages,stop};
}
async function pageCase(){let time=0,handler,callbacks=[],published=[];const s=vm.createContext({performance:{timeOrigin:0,now:()=>++time},Worker:class{constructor(){this.postMessage=()=>{};this.terminate=()=>{}}},publishCompleted:async m=>{published.push(['snapshot',m.transport.page_binding_begin_ms])},publishStopped:async m=>{published.push(['stopped',m.transport.page_binding_begin_ms])}});vm.runInContext(fs.readFileSync(__dirname+'/early-page.js','utf8')+'\nglobalThis.fire=m=>worker.onmessage({data:m});',s);vm.runInContext('setupEarly()',s);s.fire({kind:'snapshot',identity:{request_id:'r'}});s.fire({kind:'private_done',identity:{request_id:'r'}});s.fire({kind:'stopped',identity:{request_id:'r'},stop:{handles:0,activeNN:0,live_searches:0}});await new Promise(r=>setImmediate(r));const rows=vm.runInContext("tailBindingMarkers('r')",s);assert.equal(rows.length,2);assert(rows.every(x=>x.page_binding_end_ms>=x.page_binding_begin_ms));assert.deepEqual(published.map(x=>x[0]),['snapshot','stopped']);return{rows,published};}
async function main(){const rows=[];for(const e of ['candidate','reference']){const a=await workerCase(e,'baseline'),b=await workerCase(e,'cooperative');assert(b.calls<a.calls);assert(!b.messages.some(m=>m.kind==='fault'),'NORMAL_BUDGET_STOP_FAULT');rows.push({engine:e,baseline_calls:a.calls,cooperative_calls:b.calls,cooperative_stop:b.stop.stop,producer_kind_order:b.messages.map(m=>m.kind)});for(const at of [1401,1402,1403]){const r=await workerCase(e,'cooperative',{at});assert(at<1402?r.calls===1:r.calls===0);if(at<1402)assert(!r.messages.some(m=>m.kind==='fault'),'BUDGET_DEADLINE_MUST_NOT_HARDFAULT');rows.push({engine:e,at,calls:r.calls,zero_owned:r.stop.stop});}const f=await workerCase(e,'cooperative',{hardfault:true});assert(f.messages.some(m=>m.kind==='fault'&&m.error==='INJECTED_HARDFAULT'));}
 const page=await pageCase();const b=boundClock([{start:10,end:12,remote:100}]);const nodeCutoff=402,early=nodeCutoff+b.lo_ms;assert(early-b.lo_ms===nodeCutoff);assert(early-b.hi_ms<=nodeCutoff);
 const result={NN:0,Chromium:0,tests:rows,page,clock:{offset:b,early_worker_cutoff:early,node_deadline_early:early-b.hi_ms,node_deadline_late:early-b.lo_ms},source:{candidate_defaults:'T_ms=1e9 without t0/T parameters',reference_defaults:'generation check only',notifications:'snapshot/private_done/stopped same FIFO order; page bindings not awaited by onmessage'},single_factor:'Worker cooperative new work cutoff=Node402 transformed with worker lo offset; same instrumentation in A/B',normal_budget_stop_keeps_completed_cp:true,hardfault_distinct:true};fs.writeFileSync(OUT+'/phaseA-gates.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({NN:0,tests:rows.length,page_markers:page.rows.length,passed:true}));}
if(require.main===module)main().catch(e=>{console.error(e.stack);process.exitCode=1});module.exports={workerCase};
