'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto'),{performance}=require('perf_hooks');
const {Pipe}=require('./pipe.cjs'),{Broker}=require('./broker.cjs'),{GamePool}=require('./gamepool.cjs');
const ROOT=path.resolve(__dirname,'../..'),out=process.argv[2],rawPath=ROOT+'/.artifacts/ai-sigma/resume-20261003/NATIVE-BASELINE/runs/native165-mechanism-r1/result.json',inputPath=ROOT+'/research-data/ai-sigma/165-native-baseline/stageA-inputs.json',binary=ROOT+'/.artifacts/ai-sigma/resume-20261003/NATIVE-BASELINE/build/target/release/faithful-native';
const saved=JSON.parse(fs.readFileSync(rawPath)),fixtures=JSON.parse(fs.readFileSync(inputPath)).fixtures,{r}=require('../ai-sigma-native-baseline/reference.cjs').createReference(),names=['initial-p1','asym-hv-p2'],models=new Map;let pipe=null,provider=null,broker=null,returned=0;
const save=(n,v)=>fs.writeFileSync(path.join(out,n),JSON.stringify(v,null,2)+'\n');
class Registry{
 constructor(){this.models=new Map;this.events=[];}
 async call(q){const z=await pipe.ask(q);if(!z.ok)throw Error(z.error);return z.data;}
 async new(f,g,K){const savedRow=saved.rows.find(x=>x.engine==='candidate'&&x.fixture_id===f.id);const nativePrefix=[];let state=r.fromPrefix([]);for(const a of f.legal_prefix){nativePrefix.push(r.rustAction(state,a));state=state.next(a)}const raw=await this.call({op:'raw',fixture:{prefix:nativePrefix}});assert.deepStrictEqual(raw.features_bits,savedRow.root_state.features_bits);const h=(await this.call({op:'new',prefix:nativePrefix,simulations:K,generation:g,trace:false})).handle;this.models.set(h,{fixture:f.id,row:savedRow,index:0,generation:g,root_features:raw.features_bits});return h;}
 async begin(h,g){const z=await this.call({op:'begin',handle:h,generation:g}),m=this.models.get(h);if(z.pending){const n=m.row.numeric[m.index];assert(n);for(const k of ['features_bits','key','history','legal','turn','ply','path','token'])assert.deepStrictEqual(z[k],n[k],k);this.events.push({handle:h,fixture:m.fixture,token:z.token,tape_index:m.index});}return z;}
 async resume(h,g,token,NN){const m=this.models.get(h),n=m.row.numeric[m.index];assert.deepStrictEqual(NN.f32bits137,n.NN_bits);const z=await this.call({op:'resume',handle:h,generation:g,token,logits:NN.logits,value:NN.value});m.index++;return z;}
 async checkpoint(h,g){return this.call({op:'checkpoint',handle:h,generation:g});}
 async cancel(h,g){return this.call({op:'cancel',handle:h,generation:g});}
 async free(h){return this.call({op:'free',handle:h});}
}
(async()=>{const start=performance.now();pipe=new Pipe(binary,[]);provider=new Pipe(process.execPath,['--max-old-space-size=192',__dirname+'/tape-provider.cjs',rawPath]);const backend=new Registry();let seq=0;
 broker=new Broker(async items=>{const enriched=items.map(x=>{const b=broker.inflight.find(b=>b.wire_id===x.id),m=backend.models.get(b.identity.handle);return{...x,tape_fixture:m.fixture,tape_index:m.index}});const request_id='tape.'+(++seq),z=await provider.ask({op:'infer_batch',request_id,items:enriched});if(!z.ok||z.request_id!==request_id)throw Error(z.error?.message??'TAPE_PROVIDER_ID');returned+=z.result.items.length;return z.result.items},{replyCap:64});
 const pool=new GamePool('rust-tape-worker',backend,broker,{run:'native185-tape-r1',maxHandles:4});
 const results=await Promise.all(names.map(name=>{const f=fixtures.find(x=>x.id===name),row=saved.rows.find(x=>x.engine==='candidate'&&x.fixture_id===name);return pool.search(name,{K:32,generation:row.cp.generation,fixture:f})}));
 const checks=[];for(const x of results){const old=saved.rows.find(n=>n.engine==='candidate'&&n.fixture_id===x.game_id);assert.equal(x.status,'MOCK_OR_TAPE_COMPLETE');for(const k of ['action','root_visits','simulations','root_mean','root_valueSum','root_edges'])assert.deepStrictEqual(x.cp[k],old.cp[k],k);checks.push({fixture:x.game_id,Action:x.cp.action,rootN:x.cp.root_visits,edgeSum:x.cp.root_edges.reduce((s,e)=>s+e[2],0),rootmean:x.cp.root_mean,saved_features_NNbits_path_exact:true,final_edges_exact:true,tape_entries:32});}
 await broker.quiescent();assert.equal(returned,64);broker.stop();const stopped=await provider.ask({op:'stop',request_id:'stop'});assert(stopped.ok);const exits=[await provider.close(),await pipe.close()];assert(exits.every(x=>x.code===0));
 save('result.json',{issue:'quoridor-4lc.185',NN:0,model_sessions:0,GPU:0,saved_tape_evaluations:64,mock_reply_equivalents:64,checks,results,interleaving:backend.events,batch_statistics:broker.stats,zero:broker.zero(),exits,wall_seconds:(performance.now()-start)/1000,bindings:{raw_SHA256:crypto.createHash('sha256').update(fs.readFileSync(rawPath)).digest('hex'),input_SHA256:crypto.createHash('sha256').update(fs.readFileSync(inputPath)).digest('hex'),binary_SHA256:crypto.createHash('sha256').update(fs.readFileSync(binary)).digest('hex')},old_success_not_replaced:true,teacher_rows_for_training:0});console.log(JSON.stringify({tape64:returned,checks,NN:0}));
})().catch(async e=>{broker?.stop();if(provider)await provider.close();if(pipe)await pipe.close();save('failure.json',{error:e.stack,returned,NN:0});console.error(e.stack);process.exitCode=1});
