'use strict';
const fs=require('fs'),assert=require('assert'),crypto=require('crypto'),e=require('../ai-sigma-frame20-distance-arena/engine.cjs'),adapter=require('../ai-sigma-frame19-leaf-terminal/leaf.cjs'),{n,q}=e;
const c=JSON.parse(fs.readFileSync(process.argv[2]));assert.equal(c.task,'one-root-leaf-254-v1');assert.equal(c.schema,'one-root-leaf-v1');const inp=JSON.parse(fs.readFileSync(c.input));const begin=e.now();let processed=0,NN=0,fixtures=0;const results=c.conditions.map(x=>({...x,status:'NOT_RUN',values:[]}));const out={UTC:new Date().toISOString(),task:c.task,schema:c.schema,issue:'quoridor-4lc.254',input_SHA:crypto.createHash('sha256').update(fs.readFileSync(c.input)).digest('hex'),planned:6,unique_roots:1,processed:0,NN:0,fixtures:[],conditions:results,partial:true};
const save=()=>{out.processed=processed;out.NN=NN;out.wholewall_ms=e.now()-begin;fs.writeFileSync(c.output,JSON.stringify(out,null,2)+'\n');fs.writeFileSync(c.counter_file,JSON.stringify({all_samples:NN,processed,fixtures,conditions_complete:results.filter(x=>x.status==='COMPLETED').length})+'\n')};
function control(){if(e.now()-begin>=c.internal_ms)throw Error('INTERNAL_TIME_CAP');if(NN>c.NNcap)throw Error('NN_CAP')}
function enter(){control();if(processed>=c.processed_cap)throw Error('PROCESSED_CAP');processed++}
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
function terminal(s,depth){return depth===0?adapter.terminal(s):q.r.terminalResult(s)}
function negate(p){const origins={};for(const[k,v]of Object.entries(p.origins)){const kind=k==='terminalWin'?'terminalLoss':k==='terminalLoss'?'terminalWin':k;origins[kind]={...v,propagated:[-v.propagated[1],-v.propagated[0]],witness:{...v.witness,sign:-v.witness.sign,propagated_value:-v.witness.propagated_value}}}return{value:-p.value,origins}}
function merge(a,b){const out={...a};for(const[k,v]of Object.entries(b)){if(!out[k])out[k]=v;else{const z=out[k],t={...z,count:z.count+v.count};for(const field of ['propagated','raw_u_leaf_STM','clip_leaf_STM','tanh_leaf_STM','NNUE_leaf_STM'])if(z[field])t[field]=[Math.min(z[field][0],v[field][0]),Math.max(z[field][1],v[field][1])];out[k]=t}}return out}
function endpoint(s,acc,engine,t){
 const witness={ply:s.depth,side:s.getCurrentPlayer(),key:s._positionKey(),history_SHA:sha(n.history(s)),sign:1,terminal:t?{winner:t.winner,reason:s.winner()?'GOAL':s.depth>=200?'PLY200':'NO_LEGAL'}:null};let value,kind,extra={};
 if(t){value=t.value;kind=value===1?'terminalWin':value===-1?'terminalLoss':'terminalDraw'}
 else if(engine==='NNUE'){control();if(NN>=c.NNcap)throw Error('NN_CAP');NN++;value=n.valueScaled(acc,w,m);kind='nonterminalNNUE';extra.NNUE_leaf_STM=[value,value]}
 else{const clip=e.distanceNumeric(s,m,'clip'),tanh=Math.fround(Math.tanh(clip.u));value=engine==='Dclip'?clip.value:tanh;kind=Math.abs(clip.u)>=1?'nonterminalPretransformAbsUge1':'nonterminalPretransformAbsUlt1';extra={raw_u_leaf_STM:[clip.u,clip.u],clip_leaf_STM:[clip.value,clip.value],tanh_leaf_STM:[tanh,tanh]};Object.assign(witness,{raw_u_leaf_STM:clip.u,clip_leaf_STM:clip.value,tanh_leaf_STM:tanh})}
 assert(Number.isFinite(value)&&Math.abs(value)<=1,'VALUE_DOMAIN');witness.value_leaf_STM=value;witness.propagated_value=value;return{value,origins:{[kind]:{count:1,propagated:[value,value],...extra,witness}}}
function legal(s){return s.getLegalActions().map(action=>({action,Action:q.r.rustAction(s,action)})).sort((a,b)=>a.Action-b.Action)}
function visit(s,acc,depth,engine){enter();const t=terminal(s,depth);if(t||!depth)return endpoint(s,acc,engine,t);let best=null;for(const item of legal(s)){const child=s.next(item.action),ca=engine==='NNUE'?q.delta(acc,child,w):null;const p=negate(visit(child,ca,depth-1,engine));if(!best||p.value>best.value)best=p;else if(p.value===best.value)best={value:best.value,origins:merge(best.origins,p.origins)}}assert(best,'NO_LEGAL_NONTERMINAL');return best}
function check(name,fn){enter();fn();fixtures++;out.fixtures.push({name,PASS:true});save()}
let w,m,root,rootacc;
try{
 ({w,m}=n.load(c.weight_manifest));root=q.r.fromPrefix(inp.prefix);assert.equal(root._positionKey(),inp.before_key);assert.equal(root.getCurrentPlayer(),inp.side);assert.equal(root.depth,inp.ply);assert.equal(n.history(root),inp.before_history);assert.equal(sha(n.history(root)),inp.history_SHA);assert(!q.r.terminalResult(root));out.input_reconstruction={PASS:true,key:root._positionKey(),side:root.getCurrentPlayer(),ply:root.depth,history_SHA:sha(n.history(root)),full_prefix_SHA:sha(JSON.stringify(inp.prefix))};rootacc=q.full(root,w);save();
 check('extremal_union_and_sign_propagation',()=>{const p={value:1,origins:{terminalWin:{count:1,propagated:[1,1],witness:{sign:1,propagated_value:1}}}},v=negate(p);assert.equal(v.value,-1);assert.equal(v.origins.terminalLoss.count,1);assert.equal(negate(v).origins.terminalWin.witness.sign,1);assert.equal(merge(v.origins,v.origins).terminalLoss.count,2);const n={value:-.8,origins:{nonterminal:{count:1,propagated:[-.8,-.8],raw_u_leaf_STM:[-1.2,-1.2],witness:{sign:1,propagated_value:-.8}}}};assert.equal(negate(n).value,.8);assert.equal(negate(n).origins.nonterminal.raw_u_leaf_STM[0],-1.2)});
 check('terminal_priority_draw_and_no_pawn_full_fallback',()=>{const s=new q.r.State({boardsize:9,depth:200,player1pos:[4,8],player2pos:[4,1]});assert.equal(adapter.terminal(s).winner,1);const d=new q.r.State({boardsize:9,depth:200});assert.equal(adapter.terminal(d).value,0);const a={winner:()=>0,depth:0,_getLegalPawnActions:()=>[],getLegalActions:()=>[{}]},b={...a,getLegalActions:()=>[]};assert.equal(adapter.terminal(a),null);assert.equal(adapter.terminal(b).value,0)});
 check('actual_child_P2_full_delta_f32_and_parent_copy',()=>{const before=n.history(root);for(const item of legal(root)){const ch=root.next(item.action);assert.equal(ch.getCurrentPlayer(),3-root.getCurrentPlayer());const a=q.delta(rootacc,ch,w),b=q.full(ch,w);for(const acc of [a,b]){control();if(NN>=c.NNcap)throw Error('NN_CAP');NN++;const v=n.valueScaled(acc,w,m);assert(Number.isFinite(v))}const va=n.valueScaled(a,w,m),vb=n.valueScaled(b,w,m);NN+=2;assert(Math.abs(va-vb)<=1e-5+1e-4*Math.abs(vb));assert.equal(n.history(root),before)}assert.equal(root._positionKey(),inp.before_key)});
 const rootLegal=legal(root);assert(rootLegal.some(x=>x.Action===21)&&rootLegal.some(x=>x.Action===29));out.root_legal_Actions=rootLegal.map(x=>x.Action);out.root_order='Action ascending diagnostic; old rootbest sequence not reconstructed';out.model={weights_SHA:sha(fs.readFileSync(m.weights)),feature:m.feature,mu_f32:m.mu_f32,sigma_f32:m.sigma_f32,distance_fit:m.distance_fit};save();
 for(const row of results){row.status='STARTED';const st=e.now(),beforeNN=NN,beforeProcessed=processed;let childCurrent=null;
  try{enter();for(const item of rootLegal){childCurrent=item.Action;const ch=root.next(item.action),acc=row.engine==='NNUE'?q.delta(rootacc,ch,w):null,p=negate(visit(ch,acc,row.depth-1,row.engine));row.values.push({Action:item.Action,value:p.value,origins:p.origins,bound:'EXACT_FINITE_DEPTH_FULL_WINDOW',all_extremal_origins_complete:true})}
   assert.equal(n.history(root),inp.before_history);row.min_value=Math.min(...row.values.map(x=>x.value));row.max_value=Math.max(...row.values.map(x=>x.value));row.argmax_Actions=row.values.filter(x=>x.value===row.max_value).map(x=>x.Action);row.strict_first_Action=row.argmax_Actions[0];const below=row.values.map(x=>x.value).filter(v=>v<row.max_value);row.next_distinct_gap=below.length?row.max_value-Math.max(...below):null;row.next_distinct_gap_reason=below.length?'finite distinct second value':'ALL_VALUES_TIED';row.saved_actions=Object.fromEntries(inp.saved_Actions.map(Action=>[Action,{value:row.values.find(x=>x.Action===Action).value,argmax:row.argmax_Actions.includes(Action),gap:row.max_value-row.values.find(x=>x.Action===Action).value}]));row.root_extremum_origins=row.values.filter(x=>x.value===row.max_value).reduce((o,x)=>merge(o,x.origins),{});row.parent_copy_key_history_restored=true;row.status='COMPLETED';row.exact_values_adopted=true;
  }catch(x){row.status='INCOMPLETE';row.typed=x.message;row.incomplete_child=childCurrent;row.unprocessed_Actions=rootLegal.map(x=>x.Action).filter(x=>!row.values.some(v=>v.Action===x));row.partial_values=row.values;row.values=[];row.exact_values_adopted=false;throw x}finally{row.NN=NN-beforeNN;row.processed=processed-beforeProcessed;row.wall_ms=e.now()-st;save()}
 }
 out.status='COMPLETED';out.partial=false;out.all_extremal_origins_complete=true;out.truth_scope='exact under this immutable finite depth model/RuleA/input; no game truth/NI/teachertruth';
}catch(x){out.status='UNSETTLED';out.typed=x.message;out.error=x.stack}
save();console.log(JSON.stringify({task:c.task,schema:c.schema,status:out.status,planned:6,completed:results.filter(x=>x.status==='COMPLETED').length,NN,processed,wholewall_ms:out.wholewall_ms}));process.exitCode=out.status==='COMPLETED'?0:1;
