import pathlib,json,struct,datetime,hashlib
R=pathlib.Path(__file__).resolve().parents[2];D=R/'research-data/ai-sigma/163-fixed-cycle';A=R/'.artifacts/ai-sigma/resume-20261003/FIXED-CYCLE';old=json.loads((R/'.artifacts/ai-sigma/resume-20261003/SIGMA-WEB-PORT/runs/port151-stageA-r2/browser-result.json').read_text());fs=json.loads((D/'inputs.json').read_text())['fixtures'];rows=[];jobs=[];heavy=0;startup=0
f32=lambda x:struct.unpack('<I',struct.pack('<f',x))[0]
for p in sorted((A/'runs').glob('*.process.json')):
 z=json.loads(p.read_text());cost=(datetime.datetime.fromisoformat(z['end'])-datetime.datetime.fromisoformat(z['start'])).total_seconds();heavy+=cost;jobs.append({k:z[k] for k in ['name','start','end','exit','stop_reason','peak_group_plus_runner_RSS','remaining','unknown_adopted','affinity_violations']});jobs[-1]['wall_s']=cost
for index,name in enumerate(['cycle163-input0-r2','cycle163-input1-r1']):
 out=A/'runs'/name;x=json.loads((out/'result.json').read_text());startup+=json.loads((out/'startup.json').read_text())['startup_NN'];fixture=fs[index];root=next(r for r in old['rows'] if r['fixture_id']==fixture['id'] and r['engine']=='reference')['numeric'][0]
 for ordinal in range(6):
  r=next((r for r in x['rows'] if r['spec']['ordinal']==ordinal),None)
  if not r:rows.append({'input':fixture['id'],'ordinal':ordinal,'class':'unstarted','known':False});continue
  n=r['diagnostic']['numeric'][0];context=r['identity']['key']==fixture['history_count_key'] and r['identity']['history']==sorted(fixture['history_counts'],key=lambda x:x[0]) and r['identity']['legal_prefix']==fixture['legal_prefix'];numerical=n['features_bits']==root['features_bits'] and list(map(f32,n['policy_logits']+[n['value']]))==list(map(f32,root['policy_logits']+[root['value']]));cp=r['main_adopted'];reads=r['main_CP_reads'];admit=next((v for v in reversed(reads) if cp and v['sequence']==cp['sequence'] and v['accepted']),None);nn=r['diagnostic'].get('NN_control_events',[]);rows.append({'input':fixture['id'],'ordinal':ordinal,'engine':r['spec']['engine'],'phase':r['spec']['phase'],'class':r['fixed_cycle']['class'],'known':True,'root_context_exact':context,'features648_NN137_f32bits_exact':numerical,'main_admit':admit,'admit_offset_ms':admit['immutable_admit_end_ms']-r['identity']['t0_ms'] if admit else None,'admit_not_after402':bool(admit and admit['immutable_admit_end_ms']<=r['identity']['commit_cutoff_ms']),'chosen_action209':cp['action'] if cp else None,'main_adopt_sequence_equals_public':bool(cp and cp['sequence']==r['response']['body']['sequence']),'public_ms':r['response']['public_elapsed_ms'],'public_lt500':r['response']['stamp_ms']<r['identity']['deadline_ms'],'zero_ACK_by_D':r['fixed_cycle']['zero_ACK_received_by_D'],'ACK_wall_ms':r['ACK_wall_ms'],'zero_receipt':r['fixed_cycle']['zero_receipt'],'D_observe_offset_ms':r['fixed_cycle']['D_observation_ms']-r['identity']['deadline_ms'],'target_lateness_ms':r['identity']['t0_ms']-r['fixed_cycle']['target_ms'],'next_t0_not_before_previous_D':r['fixed_cycle']['previous_D_ms'] is None or r['identity']['t0_ms']>=r['fixed_cycle']['previous_D_ms'],'hand_API_starts':r['hand_NN'],'API_returns_logged':len(nn),'API_start_return_equal_saved':r['hand_NN']==len(nn),'kernelCPU':None,'exactAtomicstore':None,'worker_clock_interval':r['worker_clock'],'fixed_cycle':r['fixed_cycle'],'postpublic_discard_count':r['NN_returned_after_public'],'postpublic_NN_definite':r['post_public_NN_definite'],'completed_backup':r['completed_backup_convention'],'terminal_noNN':r['completed_without_NN']})
v={'issue':'quoridor-4lc.163','planned':12,'saved_started':len([r for r in rows if r['known']]),'classes':{c:sum(r['class']==c for r in rows) for c in set(r['class'] for r in rows)},'hand_NN':sum(r.get('hand_API_starts',0) for r in rows),'startup_NN':startup,'heavy_cumulative_s':heavy,'jobs':jobs,'rows':rows,'all_fixed12_functional':all(r['known'] and r['class']=='completed_legal' and r['root_context_exact'] and r['features648_NN137_f32bits_exact'] and r['admit_not_after402'] and r['main_adopt_sequence_equals_public'] and r['public_lt500'] and r['zero_ACK_by_D'] and r['next_t0_not_before_previous_D'] for r in rows),'formal_ready':False,'limitations':['fixed1000ms measurement adapter differs from normal opponent t0, idle second half is real wall cost','kernelCPU and ORT Worker TID attribution missing; source threads1/proxyfalse and main zero ACK only','main performance clock resolution/uncertainty not independently bounded against402; stable seqlock revision is verified in original reader but numeric revision not separately saved','notification_possible is main state availability, no early position-notice IPC receipt measured','NN/start-return totals saved, pending_publish and pending_eval not separately typed in stop receipt','private source repairs before NN; failedNN0 init attempt6 unstarted preserved outside12 scientific planned slots'],'same_writer_saved_arithmetic_not_independent':True,'NN0_failed_attempt_retained':'cycle163-input0-r1, 6 scientific unstarted, startup0/NN0, routing and UNKNOWN_PARENT cleanup; no scientific successful retry'}
(D/'results.json').write_text(json.dumps(v,indent=2)+'\n');print(json.dumps({k:v[k] for k in ['planned','saved_started','classes','hand_NN','startup_NN','heavy_cumulative_s','all_fixed12_functional','formal_ready']}))
