'use strict';
const fs=require('fs'),readline=require('readline'),{Pipe,ROOT,A,now,controlDrain,identity}=require('./common.cjs'),{createReference}=require('../ai-sigma-native-baseline/reference.cjs');
const engine=process.argv[2],{ctx,r}=createReference();let rust=null,ort=null,active=null,stopped=false,closing=false,nnTotal=0,startupTotal=0;
const emit=x=>process.stdout.write(JSON.stringify(x)+'\n');
const unpack=x=>{if(!x.ok)throw Error(x.error);return x.data};
const call=async x=>unpack(await rust.ask(x));
async function init(mock=false){if(engine==='candidate')rust=new Pipe(A+'/build/target/release/faithful-native',[]);if(!mock){ort=new Pipe('/home/vscode/.cache/inference/envs/quoridor-training/bin/python',['-u',ROOT+'/tools/ai-sigma-native-baseline/ort.py',process.env.SIGMA_MODEL_PATH??ROOT+'/models/experiments/ai-sigma/reference/sigma-pcr250/best.onnx']);const info=unpack(await ort.ask({op:'info'})),bits=r.portState(r.fromPrefix([])).features_bits,start=now();const warm=unpack(await ort.ask({op:'infer',features_bits:bits}));startupTotal++;return{info,startup:{count:1,wall_ms:now()-start,API_ms:warm.API_ms,root_NN_bits:warm.NN_bits},identities:[identity(process.pid),...(rust?[identity(rust.child.pid)]:[]),identity(ort.child.pid)]};}return{mock:true,identities:[identity(process.pid),...(rust?[identity(rust.child.pid)]:[])]};}
function cpShape(x,g,nn){return{generation:g,action:x.action,root_visits:x.root_visits,simulations:x.simulations,root_mean:x.root_mean,root_valueSum:x.root_valueSum,root_edges:x.root_edges,nn_calls:nn};}
async function search(q){const start=now();stopped=false;let handle=null,cp=null,trace=null,root=null,primary=null,discardedNN=0;const numeric=[],CPs=[],spans=[];let count=0,completed=0,firstNN=null,last_leafNN=null;
ctx.nativeStopped=()=>stopped||now()-start>(q.watchdog_ms??10000);r.reset(!!q.trace);
const state=q.mock?.artificial_state&&engine==='reference'?new r.State(q.mock.artificial_state):r.fromPrefix(q.legal_prefix),prefix=[];let cursor=r.fromPrefix([]);for(const a of q.legal_prefix){prefix.push(r.rustAction(cursor,a));cursor=cursor.next(a)}
const rootState=r.portState(state);
const infer=async bits=>{if(stopped)throw Error('guard');if(count>=(q.NN_limit??300000))throw Error('NN_BUDGET');const t=now();let n;if(q.mock?.tape){const row=q.mock.tape[count];if(!row||JSON.stringify(row.features_bits)!==JSON.stringify(bits))throw Error('NN0_TAPE_FEATURE_MISMATCH');n={logits:row.policy_logits,value:row.value,NN_bits:row.NN_bits,API_ms:0,process_CPU_ms:0};}else if(q.mock){if(q.mock.delay_ms)await new Promise(resolve=>setTimeout(resolve,q.mock.delay_ms));const logits=Array(136).fill(q.mock.logit??0);if(q.mock.bias!=null)logits[q.mock.bias]=4;n={logits,value:q.mock.value??.25,NN_bits:Array.from(new Uint32Array(new Float32Array([...logits,q.mock.value??.25]).buffer)),API_ms:0,process_CPU_ms:0};}else{nnTotal++;count++;n=unpack(await ort.ask({op:'infer',features_bits:bits}));}if(q.mock)count++;if(firstNN===null)firstNN={features_bits:bits,NN_bits:n.NN_bits,policy_logits:n.logits,value:n.value};spans.push({index:count,request_ms:t-start,return_ms:now()-start,pipe_ms:now()-t,API_ms:n.API_ms,process_CPU_ms:n.process_CPU_ms});if(stopped){discardedNN++;throw Error('guard')}return n;};
const progress=x=>{if(q.final_only&&!x.final_only_delivery){completed=x.simulations;return;}cp=cpShape(x,q.generation,count);completed=cp.simulations;if(q.trace)CPs.push(cp);emit({kind:'cp',id:q.id,engine,cp,worker_elapsed_ms:now()-start})};
try{
 if(engine==='candidate'){
  const raw=await call({op:'raw',fixture:{prefix}});if(JSON.stringify(raw.features_bits)!==JSON.stringify(rootState.features_bits)||JSON.stringify(raw.effective_legal)!==JSON.stringify(rootState.legal))throw Error('ROOT_INPUT_MISMATCH');
  handle=(await call({op:'new',prefix,simulations:q.K??1000000,generation:q.generation,trace:!!q.trace})).handle;
  while(!stopped){const z=await call({op:'begin',handle,generation:q.generation});if(stopped)break;if(z.pending){const n=await infer(z.features_bits);if(q.trace)numeric.push({...z,policy_logits:n.logits,value:n.value,NN_bits:n.NN_bits});if(stopped)break;await call({op:'resume',handle,generation:q.generation,token:z.token,logits:n.logits,value:n.value});}const x=await call({op:'checkpoint',handle,generation:q.generation});progress(x);await controlDrain();if(x.simulations===(q.K??1000000)||x.terminal_value!==null)break;}
  if(q.trace)trace=await call({op:'trace',handle,generation:q.generation});
 }else{
  const evaluator=async(s,legal)=>{const bits=r.portState(s).features_bits,n=await infer(bits);last_leafNN={value:n.value,side:s.getCurrentPlayer(),ply:s.depth,view:'last expanded NN leaf side-to-move; not necessarily final simulation'};if(q.trace)numeric.push({...r.portState(s),path:r.portPath(r.evaluationNode),node_index:vmEval('portId(portEvaluationNode)'),policy_logits:n.logits,value:n.value,NN_bits:n.NN_bits});const perm=s.isPlayer1Turn()?null:r.vertPolicyPermutation(9),ix=legal.map(a=>{const i=r.actionToIndex(a,9);return perm?perm[i]:i}),max=Math.max(...ix.map(i=>n.logits[i])),ex=ix.map(i=>Math.exp(n.logits[i]-max)),sum=ex.reduce((a,b)=>a+b,0);return[ex.map(v=>v/sum),n.value];};
  const c={simulations:0,spans:[],steps:[],onComplete:root=>{if(q.final_only)completed=root.visitCount;else progress(r.CP(root,q.generation))}};r.setClock(c);root=await r.runMCTS(state,(q.K??1000000)-1,evaluator,null);if(q.final_only&&root)progress({...r.CP(root,q.generation),final_only_delivery:true});if(q.trace)trace=r.trace();
 }
}catch(e){if(e.message!=='guard')primary={message:e.message,stack:e.stack};if(q.trace&&engine==='reference')trace=r.trace();}
finally{if(handle!==null){await call({op:'cancel',handle,generation:q.generation});await call({op:'free',handle});}r.setClock(null);r.reset(false);}
return{engine,fixture_id:q.fixture_id,K:q.K??null,cp,CPs,numeric,trace,spans,primary,root_state:rootState,first_NN:firstNN,last_leafNN,completed,NN_calls:count,discardedNN,terminal_noNN:completed-(count-discardedNN),zero:{activeNN:0,handles:0,active:false},request_ms:now()-start,NN_total:nnTotal,startup_separate:startupTotal,worker_stop_ms:now()-start};}
function vmEval(s){return require('vm').runInContext(s,ctx)}
readline.createInterface({input:process.stdin}).on('line',line=>{let q;try{q=JSON.parse(line)}catch(e){emit({kind:'fatal',error:'JSON_INPUT'});return}if(q.op==='stop'){if(active&&q.id===active.id)stopped=true;return}if(q.op==='init'){void init(q.mock).then(x=>emit({kind:'init',id:q.id,data:x})).catch(e=>emit({kind:'init',id:q.id,error:e.stack}));return}if(q.op==='search'){if(active){emit({kind:'result',id:q.id,primary:{message:'ACTIVE_OLD'}});return}active=q;void search(q).then(data=>{active=null;emit({kind:'result',id:q.id,data})}).catch(e=>emit({kind:'result',id:q.id,error:e.stack})).finally(()=>{active=null});return}if(q.op==='close'){closing=true;void(async()=>{if(active)throw Error('CLOSE_ACTIVE');const exit=[];if(rust)exit.push(await rust.stop());if(ort)exit.push(await ort.stop());emit({kind:'closed',id:q.id,data:{exit,NN_total:nnTotal,startup_separate:startupTotal}});process.stdin.destroy()})().catch(e=>{emit({kind:'closed',id:q.id,error:e.stack});process.exitCode=1});}});
