'use strict';const fs=require('fs'),crypto=require('crypto'),{ROOT,A,D,save}=require('./common.cjs'),{createReference}=require('../ai-sigma-native-baseline/reference.cjs');const{r}=createReference();
const master=crypto.randomBytes(32).toString('hex'),rows=[];
for(let i=0;i<24;i++){const target=[0,4,5,12,13][i%5],attempts=[];let opening=null;for(let a=0;a<64;a++){const seed=crypto.createHash('sha256').update('NATIVE176_TRAIN_OPENING_V1|'+master+'|'+i+'|'+a).digest('hex');let x=parseInt(seed.slice(0,8),16)||1;const u=()=>{x^=x<<13;x^=x>>>17;x^=x<<5;x>>>=0;return x/4294967296};let state=r.fromPrefix([]),prefix=[],reason=null;for(let ply=0;ply<target;ply++){if(r.terminalResult(state)){reason='terminal';break;}const all=state.getLegalActions(),list=all.filter(a=>a.type===(u()<.5?'pawn':'wall'));if(!list.length){reason='chosen_empty_category';break;}const action=list[Math.floor(u()*list.length)];prefix.push(action);state=state.next(action);}if(!reason&&r.terminalResult(state))reason='terminal';attempts.push({proposal:a+1,reason});if(!reason){opening={legal_prefix:prefix,key:state._positionKey(),ply:state.depth,side:state.getCurrentPlayer(),proposal:a+1,seed};break;}}
 const lineage='native176-train-'+master+'-game-'+(i+1),hash=crypto.createHash('sha256').update(lineage).digest('hex');rows.push({game_id:'native176-teacher-'+String(i+1).padStart(3,'0'),slot:i+1,job:Math.floor(i/8)+1,core:[2,4,6][i%3],target_ply:target,lineage,split:parseInt(hash.slice(0,8),16)%5===0?'validation':'train',sampling_seed:crypto.createHash('sha256').update('NATIVE176_ACTION_V1|'+lineage).digest('hex'),generated:!!opening,opening,attempts});}
const signatures=new Map();for(const g of rows){const key=JSON.stringify(g.opening?.legal_prefix);g.duplicate_prefix_of=signatures.get(key)??null;if(g.generated&&!signatures.has(key))signatures.set(key,g.game_id);}
save(D+'/openings.json',{entropy_master:master,domain:'NATIVE176_TRAIN_OPENING_V1',games:rows,teacher_holdout:false,formal_holdout:false,old173_data_read:0,chosen_empty_category:'reject entire proposal; no category redraw',max_proposals:64,NN:0});
const source=Object.fromEntries(fs.readdirSync(__dirname).filter(f=>/\.(py|cjs)$/.test(f)).map(f=>['tools/ai-sigma-native-teacher-pipeline/'+f,crypto.createHash('sha256').update(fs.readFileSync(__dirname+'/'+f)).digest('hex')]));
save(D+'/preregister.json',{issue:'quoridor-4lc.176',frame:12,UTC:new Date().toISOString(),StageA:{games:24,jobs:3,games_per_job:8,cores:[2,4,6],sessions_per_active_job:3,initializations_total_planned:9,K:64,rootN:64,edgeSum:63,first_new_plies_temperature1:16,remaining_temperature0:'strict first maximum original legal order',policy_target:'edge visits /63, not sampled action onehot',provider:'ORT1.30 CPUExecutionProvider intra/inter1 SEQUENTIAL',model_SHA:JSON.parse(fs.readFileSync(D+'/binding.json')).model_SHA256,final_only:true,parity:{inputs:'new own opening0/P2prefix5',K:64,modes:['allCP','finalOnly'],rounds:1,trace:false},max_hand_NN:300000,per_job_limit:300,unfinished:'quality/value z unknown; valid policy-only rows retained; no success supplementation'},StageB:{architecture:'flatten648->hidden32 ReLU->policy136/value1 tanh',init_seed:17680311,steps:200,minibatch:128,optimizer:'manual SGD lr.01 momentum0 decay0',loss:'legal-masked piCE + z_stm MSE',rootmean_auxiliary_weight:0,group_split:'SHA256 lineage modulo5==0 validation else train',duplicate_states:'count crossgame/split overlap; not independent-state validation',checkpoint:'weights_only reload',export:'ONNX opset17 legacy/dynamic batch, input Bx8x9x9',parity_fixed_rows:5,tolerance:'abs1e-5+rtol1e-4',CPU_threads:1,seconds:120,teacher_fit_is_not_strength:true},StageC:{conditional_on_export:true,new_fresh_lineage_domain:'NATIVE176_EVAL_V1',pairs:2,games:4,opening_ply:[12,13],both_color_same_input:true,K:32,temperature:0,models:['new student','fixedSigma d790'],purpose:'learning/ONNX/arena legal connection; not improvement or NI',faults_unknown:true,seconds:240},deadlines:{received:'2026-10-03T09:07:19Z',processing:'2026-10-03T10:47:19Z',newheavy:'2026-10-03T10:37:19Z',submission:'2026-10-03T11:02:19Z',parent:'2026-10-03T12:47:38Z'},resources:{CPU_pool:[2,4,6],RAM:4294967296,guard:3758096384,storage:268435456,storage_guard:234881024,experiment_effective_reservation:2143289344,heavy_total:1500,phase_seconds:{generate:900,learn:120,arena:240,repair:240}},source,openings_SHA256:crypto.createHash('sha256').update(fs.readFileSync(D+'/openings.json')).digest('hex'),old173_teacher_transfer:false});
console.log(JSON.stringify({generated:rows.filter(x=>x.generated).length,train:rows.filter(x=>x.split==='train').length,validation:rows.filter(x=>x.split==='validation').length,NN:0}));
