const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),readline=require('node:readline'),{spawn}=require('node:child_process'),{createRequire}=require('node:module'),J=require('./judge.cjs');const{chromium}=createRequire('/workspaces/quoridor/package.json')('playwright');const ROOT=path.resolve(__dirname,'../..'),TOOL=__dirname,RUN=ROOT+'/.artifacts/ai-sigma/runs/SIGMA-ARENA-PREFLIGHT',FIX=ROOT+'/.artifacts/ai-sigma/reference/SIGMA-WEB-REFERENCE',NN=ROOT+'/.artifacts/ai-sigma/runs/SIGMA-NN-SEARCH',MODEL=ROOT+'/models/experiments/ai-sigma/reference/sigma-pcr250/best.onnx';const now=()=>Number(process.hrtime.bigint())/1e6;const save=(name,v)=>fs.writeFileSync(RUN+'/'+name+'.json',JSON.stringify(v,null,2)+'\n');let generation=1000,owners={native:0,candidate:0,reference:0};const frozen=JSON.parse(fs.readFileSync(RUN+'/frozen-input.json'));
function verify(){for(const x of frozen.checks){const h=crypto.createHash('sha256').update(fs.readFileSync(x.path)).digest('hex');if(h!==x.sha256)throw Error('FROZEN_INPUT_MUTATED '+x.path);}if(crypto.createHash('sha256').update(fs.readFileSync(MODEL)).digest('hex')!=='d790dac68389f7602ff8a887a2385417d3c925fe22da7164c86e9226f943908d')throw Error('MODEL_HASH');}
function freeze(o){if(o&&typeof o==='object'){Object.freeze(o);for(const v of Object.values(o))freeze(v);}}
function pipe(cmd,args,log){const child=spawn(cmd,args,{stdio:['pipe','pipe',fs.openSync(RUN+'/'+log,'w')]});const queue=[],lines=[];let error;readline.createInterface({input:child.stdout}).on('line',l=>{let v;try{v=JSON.parse(l)}catch(e){v={parse_error:e.message,raw:l}}const r=queue.shift();if(r)r(v);else lines.push(v)});child.on('error',e=>error=e);return {child,next:()=>{if(error)return Promise.reject(error);if(lines.length)return Promise.resolve(lines.shift());return new Promise(r=>queue.push(r));},send:v=>child.stdin.write(JSON.stringify(v)+'\n'),close:()=>new Promise(resolve=>{child.on('exit',resolve);child.stdin.end();})};}
function offset(samples,resolution){let lo=-Infinity,hi=Infinity;for(const s of samples){lo=Math.max(lo,s.remote-s.end-resolution);hi=Math.min(hi,s.remote-s.start+resolution);}if(!(lo<=hi))throw Error('CLOCK_OFFSET_DISJOINT');return {offset_ms:(lo+hi)/2,error_ms:(hi-lo)/2+resolution,lo_ms:lo,hi_ms:hi,samples};}
function dist(v){v=[...v].sort((a,b)=>a-b);return v.length?{n:v.length,min:v[0],p50:v.length%2?v[(v.length-1)/2]:(v[v.length/2-1]+v[v.length/2])/2,p95:v[Math.ceil(v.length*.95)-1],max:v.at(-1)}:null;}
(async()=>{verify();const modelSha=crypto.createHash('sha256').update(fs.readFileSync(MODEL)).digest('hex');let browser,native,ping;try{
 ping=pipe('python3',[TOOL+'/clock-ping.py'],'clock-ping.stderr.log');const pingReady=await ping.next();if(!pingReady.implementation.includes('CLOCK_MONOTONIC'))throw Error('OS_CLOCK_UNVERIFIED');const linuxSamples=[];for(let i=0;i<12;i++){const start=now();ping.send({});const q=await ping.next();linuxSamples.push({start,end:now(),remote:q.monotonic_ms});}const linux=offset(linuxSamples,pingReady.resolution*1000);
 native=pipe(NN+'/final-native',['serve',MODEL],'native.stderr.log');const nativeReady=await native.next();if(!nativeReady.ready)throw Error('NATIVE_READY');
 browser=await chromium.launch({headless:true,executablePath:'/workspaces/quoridor/artifacts/playwright/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--disable-software-rasterizer','--use-gl=disabled','--renderer-process-limit=1']});const ctx=await browser.newContext();const routes={'/game.js':TOOL+'/game.js','/context.js':TOOL+'/context.js','/arena-page.js':TOOL+'/arena-page.js','/candidate-worker.js':TOOL+'/candidate-worker.js','/candidate-host.js':TOOL+'/candidate-host.js','/search.wasm':NN+'/final.wasm','/model.onnx':MODEL,'/models_9x9/best.onnx':MODEL,'/ref/game.js':TOOL+'/game.js','/ref/context.js':TOOL+'/context.js','/ref/reference-worker.js':TOOL+'/reference-worker.js','/ref/ort.min.js':FIX+'/ort.min.js','/ort/ort-wasm-simd-threaded.jsep.mjs':FIX+'/ort-wasm-simd-threaded.jsep.mjs','/ort/ort-wasm-simd-threaded.jsep.wasm':FIX+'/ort-wasm-simd-threaded.jsep.wasm'},network=[];
 await ctx.route('**/*',async r=>{const u=new URL(r.request().url());network.push(u.href);if(u.origin!=='http://localhost:5190'){await r.abort();return;}if(u.pathname==='/'){await r.fulfill({contentType:'text/html',body:'<!doctype html><script src="/game.js"></script><script src="/context.js"></script><script src="/arena-page.js"></script>'});return;}const p=routes[u.pathname];if(!p){console.error('UNKNOWN_ROUTE',u.href);await r.abort();return;}await r.fulfill({contentType:u.pathname.endsWith('.wasm')?'application/wasm':/\.m?js$/.test(u.pathname)?'text/javascript':'application/octet-stream',body:fs.readFileSync(p)});});const page=await ctx.newPage();page.on('console',m=>console.log('PAGE',m.text()));page.on('pageerror',e=>console.error('PAGE_ERROR',e));await page.goto('http://localhost:5190/');const browserReady=await page.evaluate(()=>loadArena());save('startup',{native:nativeReady,browser:browserReady,ping:pingReady,modelSha,browserVersion:browser.version(),startupClock:'not charged to request T',singleCPU:2});
 const clock={linux};const pp=[];for(let i=0;i<12;i++){const start=now(),remote=await page.evaluate(()=>performance.timeOrigin+performance.now());pp.push({start,end:now(),remote});}clock.page=offset(pp,.1);
 for(const engine of ['reference','candidate']){const samples=[];for(let i=0;i<12;i++){const g=++generation,start=now(),r=await page.evaluate(({engine,g})=>workerPing(engine,g),{engine,g});samples.push({start,end:now(),remote:r.clock_ms});}clock[engine]=offset(samples,.1);}
 save('clock-calibration',clock);
 const injections=[];for(const value of [1,-1,1.00005,-1.00005,'NaN','Infinity']){const g=++generation,r=await page.evaluate(({value,g})=>injection(value,g),{value,g});injections.push({value,response:r,expectedReject:![-1,1].includes(value),pass:![-1,1].includes(value)?r.error==='output_finite_value'&&r.fallback===0:!r.error&&r.fallback===0});}save('value-injections',injections);if(injections.some(x=>!x.pass))throw Error('STRICT_VALUE_GATE');
 const calibration=JSON.parse(fs.readFileSync(RUN+'/calibration.json')).fixtures;calibration.forEach(freeze);const samples=[];
 function submit(engine,f,T,g,simulations){const t0=now(),gen=++generation;owners[engine]=gen;const prefix=J.ids(f.legal_prefix),c=engine==='native'?clock.linux:clock[engine];const early=t0+c.offset_ms-c.error_ms,req={kind:'request',type:'search',id:f.id,prefix,legal_prefix:f.legal_prefix,seed:1979,generation:gen,clock_t0_ms:early,t0:early,T_ms:T,guard_ms:g,g_ms:g,simulations,max_nodes:512,max_depth:24,limits:{maxSimulations:simulations===1?0:100000},node_t0_ms:t0,node_deadline_ms:t0+T,page_offset_ms:clock.page.offset_ms,page_error_ms:clock.page.error_ms,terminal_diagnostic:!!J.terminalResult(J.state(f.legal_prefix))};
 const pending=engine==='native'?(native.send(req),native.next().then(payload=>({payload}))):page.evaluate(({engine,req})=>dispatch(engine,req),{engine,req});
 return {generation:gen,t0,promise:pending.then(q=>{let payload=q.payload?.payload??q.payload,data=engine==='reference'?payload:payload?.data,cp=engine==='reference'?data: data?.checkpoint;const action=engine==='reference'?data?.actionRust209:cp?.action;const error=q.host_adapter_error??(engine==='reference'?data?.error:payload?.ok===false?payload?.error?.code:null);let legal=false,terminal=J.terminalResult(J.state(f.legal_prefix)),illegal=false;try{if(terminal){legal=action==null&&(engine==='reference'?data?.terminal?.value===terminal.value:cp?.terminal_value===terminal.value);}else if(action!=null){J.validate(f.legal_prefix,action);legal=true;}}catch(e){illegal=true;}const fallback=engine==='reference'?data?.fallback:cp?cp.policy_fallbacks+cp.value_fallbacks:0;const stale=owners[engine]!==gen,checkpoint=engine==='reference'?!!(data?.time?.checkpoint||terminal):data?.status==='checkpoint';const t1=now(),late=t1>=t0+T;const accepted=!error&&!illegal&&legal&&!late&&!stale&&checkpoint&&fallback===0;
 const cpSpans=engine==='reference'?data?.stats?.nn??[]:cp?.spans??[],nn_ms=engine==='reference'?cpSpans.map(x=>x.end-x.start):cpSpans.map(x=>x.nn_end_ms-x.feature_end_ms),step_ms=engine==='reference'?data?.stats?.steps??[]:data?.steps?.map(x=>x.end_ms-x.start_ms)??[],root_ms=engine==='reference'?data?.time?.rootFinished-data?.time?.workerStart:data?.root_ms;const finish_ms=engine==='reference'?0:Math.max(0,...(data?.steps??[]).map(x=>x.finish_ms??0));const engineFinish=engine==='reference'?data?.time?.finish:data?.adapter_end_ms;const transport_ms=Number.isFinite(engineFinish)?Math.max(0,t1-(engineFinish-c.offset_ms)):null;
 return {engine,id:f.id,T_ms:T,g_ms:g,generation:gen,t0_ms:t0,received_after_validation_ms:t1,elapsed_ms:t1-t0,late,overshoot_ms:Math.max(0,t1-t0-T),stale,error,illegal,legal,accepted,fallback,checkpoint,terminal,action,nn_calls:engine==='reference'?data?.stats?.nnCalls:data?.nn_calls,nn_ms,step_ms,root_ms,finish_ms,transport_ms,clock_error_ms:c.error_ms,raw:q};})};}
 for(const engine of ['native','candidate','reference'])for(const f of calibration)for(let i=-1;i<5;i++){const x=await submit(engine,f,5000,0,1).promise;samples.push({...x,phase:i<0?'warmup':'sample',sample:i});save('unit-calibration',samples);if(!x.accepted||x.nn_calls!==1||x.fallback!==0)throw Error('UNIT_GATE '+engine+' '+f.id+' '+x.error);}
 const maxStep=Math.max(...samples.flatMap(x=>[...x.step_ms,...x.nn_ms,Number.isFinite(x.root_ms)?x.root_ms:0]));const maxFinishTransport=Math.max(...samples.map(x=>x.finish_ms+(x.transport_ms??0)));const clockError=Math.max(...Object.values(clock).map(x=>x.error_ms));const guard=Math.ceil(maxStep+maxFinishTransport+clockError+5);const rule={version:1,include_warmup:true,formula:'ceil(max indivisible unit incl root/NN/step + max(finish+transport) + max clock error bound +5ms)',maxStep,maxFinishTransport,clockError,guard_ms:guard,tail_guarantee:false};save('guard',rule);
 const allfixtures=JSON.parse(fs.readFileSync(ROOT+'/.artifacts/ai-sigma/reference-fixtures/SIGMA-PARITY-PLAN/fixtures.json')).fixtures,pilot=allfixtures.filter(f=>['initial-p1','asym-hv-p2','straight-jump-p2'].includes(f.id));pilot.forEach(freeze);const rows=[],gate=[];
 for(const T of [100,500,1000]){if(guard>T/4){gate.push({T_ms:T,guard_ms:guard,eligible:false,reason:'guard > T/4',pilot:false});save('pilot-gate',gate);continue;}const before=rows.length;
  for(const engine of ['native','candidate','reference'])for(const f of pilot)for(let i=-1;i<3;i++){const q=await submit(engine,f,T,guard,4096).promise;rows.push({...q,phase:i<0?'warmup':'sample',sample:i});save('pilot',rows);}
  const pp=rows.slice(before);gate.push({T_ms:T,guard_ms:guard,eligible:true,pilot:true,requests:pp.length,all_pass:pp.every(x=>x.accepted&&x.fallback===0&&!x.illegal),accepted:pp.filter(x=>x.accepted).length,timeouts:pp.filter(x=>x.late||!x.checkpoint).length,errors:pp.filter(x=>x.error).length});save('pilot-gate',gate);
 }
 const proposed=gate.find(x=>x.all_pass)?.T_ms??null;
 const terminalFixture=allfixtures.find(f=>f.id==='goal-win-legal-replay'),terminal=[];for(const engine of ['native','candidate','reference'])terminal.push(await submit(engine,terminalFixture,1000,guard,4096).promise);save('terminal',terminal);
 const cancellations=[];for(const engine of ['native','candidate','reference']){const f=pilot[0],old=submit(engine,f,1000,guard,4096);await new Promise(r=>setTimeout(r,2));const invalidAt=now(),invalidGeneration=++generation;owners[engine]=invalidGeneration;if(engine==='native')native.send({kind:'cancel',generation:invalidGeneration});else await page.evaluate(({engine,g})=>cancelEngine(engine,g),{engine,g:invalidGeneration});const fresh=submit(engine,f,1000,guard,4096);const previous=await old.promise,next=await fresh.promise;cancellations.push({engine,invalidAt,invalidGeneration,previous,next,old_rejected:previous.stale&&!previous.accepted,new_t0:fresh.t0,queue_counted_from_enqueue:true});save('cancellation',cancellations);}
 const backendFaults=[];for(const engine of ['native','candidate','reference']){const t0=now(),g=++generation,c=engine==='native'?clock.linux:clock[engine];owners[engine]=g;const req={kind:'request',type:'search',generation:g,prefix:[999],legal_prefix:[{type:'pawn',direction:[99,99]}],clock_t0_ms:t0+c.offset_ms-c.error_ms,t0:t0+c.offset_ms-c.error_ms,T_ms:500,guard_ms:guard,g_ms:guard,simulations:1,limits:{maxSimulations:0},node_t0_ms:t0,node_deadline_ms:t0+500,page_offset_ms:clock.page.offset_ms,page_error_ms:clock.page.error_ms};const q=engine==='native'?(native.send(req),{payload:await native.next()}):await page.evaluate(({engine,req})=>dispatch(engine,req),{engine,req});const v=q.payload?.payload??q.payload;backendFaults.push({engine,error:engine==='reference'?v?.error:v?.error?.code,rejected:engine==='reference'?!!v?.error:v?.ok===false,elapsed_ms:now()-t0,raw:q});}save('backend-faults',backendFaults);
 const invalid=[];const bad={id:'invalid-prefix',legal_prefix:[{type:'pawn',direction:[99,99]}]};for(const engine of ['native','candidate','reference']){try{await submit(engine,bad,500,guard,1).promise;invalid.push({engine,error:'not rejected'});}catch(e){invalid.push({engine,error:e.message,callerRejected:true});}}save('invalid-prefix',invalid);
 const drift=[];for(const engine of ['reference','candidate']){const start=now(),q=await page.evaluate(({engine,g})=>workerPing(engine,g),{engine,g:++generation}),end=now();const c=clock[engine],expected=start+c.offset_ms;drift.push({engine,start,end,remote:q.clock_ms,within_initial_interval:q.clock_ms>=start+c.lo_ms-.1&&q.clock_ms<=end+c.hi_ms+.1});}const pstart=now();ping.send({});const p=await ping.next(),pend=now();drift.push({engine:'linux',start:pstart,end:pend,remote:p.monotonic_ms,within_initial_interval:p.monotonic_ms>=pstart+clock.linux.lo_ms&&p.monotonic_ms<=pend+clock.linux.hi_ms});save('clock-drift',drift);
 const calibrationStats=[];for(const engine of ['native','candidate','reference'])for(const f of calibration){const rr=samples.filter(x=>x.engine===engine&&x.id===f.id&&x.phase==='sample');calibrationStats.push({engine,id:f.id,elapsed_ms:dist(rr.map(x=>x.elapsed_ms)),NN_ms:dist(rr.flatMap(x=>x.nn_ms)),step_ms:dist(rr.flatMap(x=>x.step_ms)),root_ms:dist(rr.map(x=>x.root_ms).filter(Number.isFinite)),finish_ms:dist(rr.map(x=>x.finish_ms)),transport_ms:dist(rr.map(x=>x.transport_ms).filter(Number.isFinite)),nn_calls:rr.map(x=>x.nn_calls)});}
 const stats=[];for(const engine of ['native','candidate','reference'])for(const T of [100,500,1000]){const r=rows.filter(x=>x.engine===engine&&x.T_ms===T&&x.phase==='sample');if(r.length)stats.push({engine,T_ms:T,guard_ms:guard,elapsed_ms:dist(r.map(x=>x.elapsed_ms)),NN_ms:dist(r.flatMap(x=>x.nn_ms)),step_ms:dist(r.flatMap(x=>x.step_ms)),root_ms:dist(r.map(x=>x.root_ms).filter(Number.isFinite)),finish_ms:dist(r.map(x=>x.finish_ms)),transport_ms:dist(r.map(x=>x.transport_ms).filter(Number.isFinite)),nn_calls:r.map(x=>x.nn_calls),accepted:r.filter(x=>x.accepted).length,timeout:r.filter(x=>x.late||!x.checkpoint).length});}
 save('summary',{guard:rule,proposed_T_ms:proposed,formal_no_go:true,proposal_scope:'single-step calibration and pilots only; independent arena verification/official contract still required',native_label:'Rust-native vs fixed Sigma-Web local CPU',browser_label:'Rust-Wasm vs same fixed Sigma-Web',calibration_requests:samples.length,calibration_stats:calibrationStats,pilot_requests:rows.length,pilot_gate:gate,stats,strict_value_injection_all_pass:injections.every(x=>x.pass),terminal_NN0:terminal.every(x=>x.accepted&&x.nn_calls===0),clock_drift:drift,cancel_old_all_rejected:cancellations.every(x=>x.old_rejected),backend_faults_all_rejected:backendFaults.every(x=>x.rejected),formal_matches:0,holdout_games:0,backend_originals:frozen.checks});save('network',network);verify();await page.evaluate(()=>stopArena());console.log(JSON.stringify({proposed_T_ms:proposed,guard_ms:guard,calibration:samples.length,pilots:rows.length}));
 }finally{if(browser)await browser.close();if(native){native.child.stdin.end();await new Promise(r=>{if(native.child.exitCode!==null)return r();native.child.once('exit',r);});}if(ping){ping.child.stdin.end();await new Promise(r=>{if(ping.child.exitCode!==null)return r();ping.child.once('exit',r);});}}})().catch(e=>{console.error(e);save('failure',{at_ms:now(),error:e.message,stack:e.stack,formal_no_go:true});process.exitCode=1;});
