const {OwnedProcesses,boundedStop}=require('./cleanup.cjs');
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{execFileSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'../..'),BASE=ROOT+'/.artifacts/ai-sigma/continuation-20261001/SIGMA-DETACHED-OWNERSHIP',DEADLINE=Date.parse('2026-10-01T13:15:00Z');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function readPlan(){const b=JSON.parse(fs.readFileSync(BASE+'/plan-bind.json'));for(const name of ['preregister','final_manifest','stop','handoff'])if(sha(b[name+'_path'])!==b[name+'_sha256'])throw Error('PLAN_BIND_MUTATED');if(sha(b.coordinator_static_acceptance_path)!==b.coordinator_static_acceptance_sha256)throw Error('STATIC_ACCEPTANCE_MUTATED');const st=JSON.parse(fs.readFileSync(b.stop_path)),m=JSON.parse(fs.readFileSync(b.final_manifest_path));if(!st.source_write_stopped||!st.owned_runtime_PID0||!m.source_write_stopped||!m.PID0)throw Error('PLAN_NOT_FROZEN');return {prereg:JSON.parse(fs.readFileSync(b.preregister_path)),path:b.preregister_path,sha256:b.preregister_sha256};}
function schedule(p){if(p.issue!=='quoridor-4lc.48'||p.m!==48||p.total_games!==96||p.pairs?.length!==48||p.T_ms!==500||p.g_ms!==91||p.search_seed!==1979)throw Error('FIXED_48_PLAN_REQUIRED');const selected=new Set();return p.pairs.map((b,i)=>{if(b.pair!==i+1||b.platform!=='browser'||selected.has(b.pool_index)||p.old_executed_excluded_indices.includes(b.pool_index)||JSON.stringify([...b.candidate_color_order].sort())!=='[1,2]'||shaBuffer(JSON.stringify(b.legal_prefix))!==b.prefix_sha256||shaBuffer(JSON.stringify(b.context))!==b.context_sha256)throw Error('PLAN_PAIR_IDENTITY');selected.add(b.pool_index);for(let j=0;j<2;j++){const g=b.games[j];if(g.game!==2*i+j+1||g.candidate_color!==b.candidate_color_order[j]||g.seed!==1979)throw Error('PLAN_GAME_NUMBER');}return {...b,block:i+1,prefix:b.legal_prefix,games:b.games};});}
const shaBuffer=s=>crypto.createHash('sha256').update(s).digest('hex');
function verifyToken(token,purpose){if(!['actual','mock','golden'].includes(purpose))throw Error('PURPOSE');if(!token||token.purpose!==purpose||token.issue!=='quoridor-4lc.51'||token.goal!=='quoridor-4lc'||token.window!=='continuation-20261001'||token.coordinator_thread!=='01a0f31b-3409-75f2-a30e-453a50484f94'||!token.freeze_token||token.freeze_token!==process.env.SIGMA_MATCH_FREEZE_TOKEN||token.T_ms!==500||token.g_ms!==91||token.m!==48||token.global_stop_utc!=='2026-10-01T17:00:00Z'||!/^[A-Za-z0-9_-]+$/.test(token.run_id??''))throw Error('EXPLICIT_PURPOSE_FREEZE_REQUIRED');const mp=purpose==='actual'?BASE+'/entry-manifest.json':BASE+'/diagnostic/'+purpose+'-manifest.json',manifest=JSON.parse(fs.readFileSync(mp));if(purpose==='actual'&&manifest.actual_go!==true)throw Error('ACTUAL_RUN_NOT_AUTHORIZED_THIS_CONTRACT');if(purpose!=='actual'&&(token.actual_run!==false||manifest.actual_go!==false))throw Error('DIAGNOSTIC_ONLY');const plan=readPlan();if(token.preregister_sha256!==plan.sha256||token.entry_manifest_sha256!==sha(mp))throw Error('FREEZE_HASH_MISMATCH');for(const x of manifest.checks??[])if(sha(x.path)!==x.sha256)throw Error('FINAL_INPUT_MUTATED');if(purpose==='actual'){if(token.actual_run!==true||token.critic_accepted!==true||['quoridor-4lc.31','quoridor-4lc.39','quoridor-4lc.43','quoridor-4lc.47'].includes(token.critic_issue)||!/^quoridor-4lc\.\d+$/.test(token.critic_issue??'')||!manifest.entry_ready||!manifest.clock_gate)throw Error('NEW_INDEPENDENT_ENTRY_GATE_REQUIRED');if(!token.critic_report_path||sha(token.critic_report_path)!==token.critic_report_sha256||!token.acceptance_path||sha(token.acceptance_path)!==token.acceptance_sha256)throw Error('NEW_ACCEPTANCE_SHA_REQUIRED');const a=JSON.parse(fs.readFileSync(token.acceptance_path));if(a.issue!==token.critic_issue||a.accepted!==true||a.entry_manifest_sha256!==sha(mp)||a.preregister_sha256!==plan.sha256)throw Error('NEW_ACCEPTANCE_REQUIRED');if(token.processing_stop_utc!==plan.prereg.run_budget.processing_stop_UTC||(Date.parse(token.processing_stop_utc)-Date.now())/1000<11801.5)throw Error('INSUFFICIENT_FIXED_REMAINING_TIME');}else if(token.processing_stop_utc!=='2026-10-01T13:15:00Z'||token.critic_accepted===true)throw Error('DIAGNOSTIC_AUTHORITY_ONLY');return plan;}

async function execute({prereg,pool,createBackend,out,checkPause=async()=>false,now=Date.now,deadline=DEADLINE,runId,dry=false}){
 fs.mkdirSync(out,{recursive:true});const append=(name,x)=>fs.appendFileSync(out+'/'+name+'.jsonl',JSON.stringify({utc:new Date().toISOString(),run_id:runId,...x})+'\n');const write=(name,x)=>{const tmp=out+'/'+name+'.tmp';fs.writeFileSync(tmp,JSON.stringify(x,null,2));fs.renameSync(tmp,out+'/'+name+'.json')};
 const blocks=schedule(prereg,pool),table=blocks.flatMap(b=>b.games.map(g=>({...g,block:b.block,platform:b.platform,pool_index:b.pool_index,prefix_sha256:b.prefix_sha256,status:'scheduled',attempt:0})));let backend=null,restarts=0,globalRetry=0,stopped=false,lastPause=-Infinity,stopping=Promise.resolve();
 const guard=async(force=false)=>{if(stopped||now()>=deadline)throw Error('PROCESSING_DEADLINE_OR_SIGNAL');if(force||now()-lastPause>=10000){lastPause=now();if(await checkPause())throw Error('PAUSED');}};
 const stop=()=>{if(!backend)return stopping;const old=backend;backend=null;stopping=stopping.then(async()=>{const proof=await boundedStop(old);if(proof.remaining_pids!==0)throw Error('OWN_CLEANUP_PID_NOT_ZERO');append('lifecycle',{phase:'cleanup_PID0',...proof});});return stopping;};
 const start=async()=>{await stop();await guard(true);backend=await createBackend({session:++restarts,out:out+'/session-'+restarts});append('lifecycle',{phase:'restart_load_warm_recalibrate',session:restarts,startup:backend.startup,clock:backend.clock});};
 const checkpoint=()=>write('checkpoint',{runId,dry,table,globalRetry,restarts,processing_deadline:new Date(deadline).toISOString(),games_scheduled:prereg.total_games});
 const signal=()=>{stopped=true;void stop().catch(e=>append('stop-error',{error:e.message}));};process.once('SIGTERM',signal);process.once('SIGINT',signal);
 let stopReason='all_scheduled_complete',cleanupFailed=false;
 try{checkpoint();await start();
 for(const block of blocks){await guard(true);let pairDone=false;
  for(let attempt=0;attempt<2;attempt++){
   let invalid=false,incomplete=false;const attemptRows=[];
   for(const game of block.games){await guard(true);if(!backend)await start();const row=table[game.game-1];row.status='running';row.attempt=attempt;checkpoint();
    const choose=async(engine,input)=>{await guard();if(now()+1500>=deadline)throw Error('PROCESSING_STOP_RESERVE');const response=await backend.submit(engine,input,500,91,4096);append('all-ply',{game:game.game,block:block.block,attempt,engine,prefix:input.legal_prefix,seed:1979,response});return response};
    const result=await backend.play({prefix:JSON.parse(JSON.stringify(block.prefix)),candidateColor:game.candidate_color,platform:block.platform,choose,log:x=>append('judge-ply',{game:game.game,attempt,...x})});
    await guard();const priorAttempts=row.attempts??[];row.attempts=[...priorAttempts,{attempt,result}];Object.assign(row,{result,status:result.kind==='invalid_pair'?'invalid':result.complete?'completed':'incomplete'});attemptRows.push(row);append('results',{game:game.game,attempt,...row});checkpoint();
    if(backend.needsRestart()){await stop();if(result.complete&&result.kind!=='invalid_pair')await start();}
    if(result.kind==='invalid_pair'){invalid=true;break;}if(!result.complete){incomplete=true;break;}
   }
   if(!invalid&&!incomplete&&attemptRows.length===2){pairDone=true;write('pair-'+block.block,{block:block.block,attempt,Xi:attemptRows.reduce((s,x)=>s+x.result.score,0)/2,games:attemptRows.map(x=>x.game)});break;}
   if(invalid&&attempt===0&&globalRetry<2){globalRetry++;for(const g of block.games){table[g.game-1].status='scheduled_retry';delete table[g.game-1].result;}checkpoint();append('retry',{block:block.block,attempt_next:1,globalRetry,prefix_sha256:block.prefix_sha256});await stop();await start();continue;}
   stopReason=invalid?'invalid_pair_retry_exhausted':'incomplete_game';break;
  }
  if(!pairDone)break;
 }
 }catch(e){stopReason=e.message;append('entry-error',{error:e.message,stack:e.stack});}
 finally{try{await stop()}catch(e){cleanupFailed=true;stopReason+=';'+e.message;}process.removeListener('SIGTERM',signal);process.removeListener('SIGINT',signal);checkpoint();}
 const platforms={};for(const platform of ['browser']){const pairs=blocks.filter(b=>b.platform===platform).filter(b=>b.games.every(g=>table[g.game-1].status==='completed')).map(b=>b.games.reduce((s,g)=>s+table[g.game-1].result.score,0)/2);platforms[platform]={completed_pairs:pairs.length,scheduled_pairs:prereg.m,complete:pairs.length===prereg.m,Xi:pairs,mean:pairs.length?pairs.reduce((a,b)=>a+b,0)/pairs.length:null};if(pairs.length===prereg.m)platforms[platform].WDL={W:table.filter(x=>x.platform===platform&&x.status==='completed'&&x.result.score===1).length,D:table.filter(x=>x.platform===platform&&x.status==='completed'&&x.result.score===0.5).length,L:table.filter(x=>x.platform===platform&&x.status==='completed'&&x.result.score===0).length};if(pairs.length===prereg.m)platforms[platform].L=Math.max(0,platforms[platform].mean-Math.sqrt(Math.log(20)/(2*prereg.m)));}
 const summary={runId,dry,stopReason,table,platforms,globalRetry,restarts,scheduled:prereg.total_games,completed:table.filter(x=>x.status==='completed').length,real_holdout_sends:dry?0:'see all-ply',remaining_pids:cleanupFailed?null:0,cleanup_complete:!cleanupFailed,formal_attainment:false};write('results-table',table);write('summary',summary);return summary;
}
function ownDescendants(){const table=new Map();for(const name of fs.readdirSync('/proc'))if(/^\d+$/.test(name)){try{const s=fs.readFileSync('/proc/'+name+'/stat','utf8').split(')').slice(1).join(')').trim().split(/\s+/);table.set(Number(name),{pid:Number(name),ppid:Number(s[1]),starttick:Number(s[19]),state:s[0]});}catch{}}const ids=new Set([process.pid]);let change=true;while(change){change=false;for(const x of table.values())if(ids.has(x.ppid)&&!ids.has(x.pid)){ids.add(x.pid);change=true;}}return [...ids].filter(x=>x!==process.pid).map(x=>table.get(x)).filter(x=>x&&x.state!=='Z');}
async function realBackend({out}){
 // Lazy import: importing match-entry never creates a model, Worker, browser or native child.
 const watcher=new OwnedProcesses({tracePath:out+"/cleanup-trace.jsonl"});const CP=require("child_process"),originalSpawn=CP.spawn;CP.spawn=(...args)=>watcher.observeChild(originalSpawn(...args));const {withArena}=require('./arena.cjs'),{runGame}=require('./game-loop.cjs');let release,readyResolve,readyReject;const ready=new Promise((r,j)=>{readyResolve=r;readyReject=j}),done=withArena(async a=>{readyResolve(a);await new Promise(r=>release=r);},{outputDir:out,warmReference:true}).catch(e=>{readyReject(e);throw e});let a;try{a=await ready;CP.spawn=originalSpawn;}catch(e){CP.spawn=originalSpawn;await done.catch(()=>{});await boundedStop({owner:watcher,stop:async()=>({remaining_pids:ownDescendants().length})});throw e;}
 return {startup:'models loaded/warmed by immutable adapters; startup outside hand',clock:a.clock,reclock:a.reclock,page:a.page,submit:(...args)=>{const request=a.submit(...args);request.promise.cancel=request.cancel;return request.promise;},play:runGame,needsRestart:a.needsRestart,owner:watcher,stop:async()=>{release();await done;const remaining=ownDescendants();if(remaining.length)throw Error('OWN_DESCENDANTS_REMAIN '+JSON.stringify(remaining));return {remaining_pids:0,descendants:remaining,proof:'browser close awaited + native/ping idempotent abort/exit awaited + own /proc descendant scan'};}};
}
async function mainInternal(purpose,options={}){const argv=options.argv??process.argv.slice(2);const flag=purpose==='actual'?'--run':'--diagnostic';if(argv[0]!==flag||!argv[1])throw Error('USAGE '+flag+' PURPOSE_TOKEN_JSON');const token=JSON.parse(fs.readFileSync(argv[1])),plan=verifyToken(token,purpose);if(Date.now()>=Date.parse(token.processing_stop_utc))throw Error('PROCESSING_DEADLINE');const out=BASE+'/'+(purpose==='actual'?'actual':'diagnostic/'+purpose)+'-execution-'+token.run_id;if(fs.existsSync(out))throw Error('RUN_ALREADY_EXISTS_NO_SILENT_RESUME');fs.mkdirSync(out,{recursive:true});if(purpose==='golden'){if(token.diagnostic_mode!=='seal')throw Error('FIXED_GOLDEN_MODE_REQUIRED');return require('./golden-gates.cjs').run({out,mode:token.diagnostic_mode});}const checkPause=async()=>{try{require('./pause-check.cjs').checkPause(token.processing_stop_utc);return false}catch{return true}};return execute({prereg:plan.prereg,out,runId:token.run_id,createBackend:purpose==='mock'?options.createBackend:realBackend,checkPause:purpose==='mock'?(options.checkPause??(async()=>false)):checkPause,dry:purpose==='mock',deadline:Date.parse(token.processing_stop_utc)});}
async function diagnosticRealBackend(options){
 const out=path.resolve(options.out);if(!out.startsWith(BASE+'/diagnostic/')||out===BASE+'/diagnostic')throw Error('DIAGNOSTIC_OUTPUT_SCOPE');
 const fixtures=JSON.parse(fs.readFileSync(ROOT+'/.artifacts/ai-sigma/reference-fixtures/SIGMA-PARITY-PLAN/fixtures.json')).fixtures;
 const allowed=fixtures.filter(f=>f.classification==='legal-replay').map(f=>f.id);
 const b=await realBackend(options);return {...b,play:undefined,submit:(engine,f,T,g,sims)=>{const inputAvailable=require('./transaction.cjs').now();
  const gold=fixtures.find(x=>x.id===f.id&&allowed.includes(x.id));
  if(!['candidate','reference'].includes(engine)||!gold||JSON.stringify(f.legal_prefix)!==JSON.stringify(gold.legal_prefix)||![1,4096].includes(sims)||!(T===500&&g===91||engine==='candidate'&&f.id==='initial-p1'&&T===10&&g===0&&f.diagnostic_step_delay_ms===500))throw Error('DIAGNOSTIC_FIXED_GOLDEN_ONLY');
  return b.submit(engine,f,T,g,sims,inputAvailable);
 }};
}
const diagnosticMockMain=o=>mainInternal('mock',o),diagnosticGoldenMain=o=>mainInternal('golden',o);module.exports={schedule,readPlan,verifyToken,execute,diagnosticRealBackend,diagnosticMockMain,diagnosticGoldenMain};if(require.main===module)mainInternal('actual').catch(e=>{console.error(e.message);process.exitCode=1});
