const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),J=require('./judge.cjs');
const ROOT=path.resolve(__dirname,'../..'),P=ROOT+'/.artifacts/ai-sigma/plans/SIGMA-ORT-REMATCH',poolPath=ROOT+'/.artifacts/ai-sigma/runs/SIGMA-ARENA-PREFLIGHT/holdout-proposal.json',pool=JSON.parse(fs.readFileSync(poolPath));
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');assert.equal(sha(poolPath),'ac11691ffa521a86ffce2cff40dfdbebee5d283a83f70abfe36f43028b72ad9d');
function prng(seed){let s=seed>>>0;return n=>{let x,limit=Math.floor(4294967296/n)*n;do{s^=s<<13;s^=s>>>17;s^=s<<5;x=s>>>0;}while(x>=limit);return x%n;}}
function shuffle(a,r){a=a.slice();for(let i=a.length-1;i>0;i--){let j=r(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
const excluded=[25,4,51,0,47,44,56,31],eligible=pool.pool.map((_,i)=>i).filter(i=>!excluded.includes(i)),selected=shuffle(eligible,prng(2026100204)).slice(0,10),r=prng(2026100205),ordered=shuffle(selected,r),blocks=ordered.map(i=>({pool_index:i,id:pool.pool[i].id,platform:'browser',candidate_color_order:r(2)?[2,1]:[1,2]}));
const fixtures=JSON.parse(fs.readFileSync(ROOT+'/.artifacts/ai-sigma/reference-fixtures/SIGMA-PARITY-PLAN/fixtures.json')).fixtures,golden=new Set(fixtures.filter(f=>f.classification==='legal-replay').map(f=>J.hash(J.context(J.state(f.legal_prefix)))));let seen=new Set();
for(const f of pool.pool){const ctx=J.context(J.state(f.legal_prefix));assert.deepEqual(JSON.parse(JSON.stringify(ctx)),f.context);assert.equal(J.hash(ctx),f.context_sha256);assert.deepEqual(J.ids(f.legal_prefix),f.rust_prefix);assert.equal(ctx.terminal,null);assert(!seen.has(f.context_sha256));assert(!golden.has(f.context_sha256));seen.add(f.context_sha256);}
const prereg={issue:'quoridor-4lc.32',version:1,classification:'exploratory finite fixed population; never formal NI',platform:'browser',m:10,total_games:20,pool_sha256:sha(poolPath),eligible_indices:eligible,old_excluded_indices:excluded,selection_seed:2026100204,order_seed:2026100205,selection_rule:'ascending eligible; rejection xorshift32 Fisher-Yates; first10',order_rule:'shuffle selected with order seed, then draw each color order from same PRNG',selected_indices:selected,block_order:blocks,T_ms:500,g_ms:91,search_seed:1979,candidate:{PUCT:1.5,Q0:0,simulations:4096,max_nodes:512,max_depth:24,step:1,fallback:0},reference:{cpuct:1,FPU:0.2,temperature:0,order:'fixed upstream',fallback:0},scoring:{win:1,draw:0.5,loss:0,Xi:'mean same-prefix color pair',L:'max(0, meanXi-sqrt(log(20)/(2*10)))',old_results_pooling:false},retry:{pair_max:1,global_max:2,same_prefix_seed:true,replacement:false,all_attempts_retained:true},responsibility:{candidate_fault:'candidate loss',reference_timeout:'reference loss',reference_model_NN_fault:'pair invalid',identity_referee_infrastructure:'pair invalid',incomplete:'no complete result'},rules:{total_ply:200,prefix_included:true,goal_priority:true,third_repeat_forbidden:true,no_legal:'draw'},input_validation:{pool64:seen.size,golden_excluded:golden.size,calibration:'subset of excluded legal golden',unknown_training_overlap:'unverified'},future_stop_utc:'2026-10-01T03:55:00Z',worst_remaining_seconds:2760,NN_browser_game_holdout_sends:0};
fs.writeFileSync(P+'/preregister.json',JSON.stringify(prereg,null,2)+'\n');console.log(JSON.stringify({selected,blocks,pool64_valid:true}));
