import pathlib,json,hashlib,datetime,subprocess,time,os,tarfile,io
R=pathlib.Path('/workspaces/quoridor/.worktree/ai-sigma');O=R/'.artifacts/ai-sigma/resume-20261002/C-FACTOR-INDEPENDENT';P=R/'.artifacts/ai-sigma/resume-20261002/C-FACTOR-BROWSER';T=R/'tools/ai-sigma-c-factor-independent';D=R/'research-data/ai-sigma/111-c-factor-independent'
def utc():return datetime.datetime.now(datetime.timezone.utc).isoformat()
def sha(b):return hashlib.sha256(b).hexdigest()
def read(p):return json.loads(p.read_text())
def save(n,d):(O/n).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
def current(pid):
 try:
  z=pathlib.Path('/proc',str(pid),'stat').read_text().rsplit(')',1)[1].split();return {'pid':pid,'starttick':int(z[19]),'ppid':int(z[1]),'state':z[0]}
 except FileNotFoundError:return None
before=read(O/'input-before.json');changed=[];after={}
for p,h in before['important_checks'].items():
 b=(R/p).read_bytes();after[p]=sha(b)
 if after[p]!=h:changed.append(p)
assert not changed,changed
binding=read(O/'final-data-binding.json');rev=binding['Git'];base='research-data/ai-sigma/110-c-factor-browser/';git=lambda p:subprocess.check_output(['git','show',rev+':'+base+p]);archive=git('run-evidence.tar.gz');assert sha(archive)==binding['archiveSHA']
with tarfile.open(fileobj=io.BytesIO(archive),mode='r:gz') as tar:
 for p,x in binding['matched_initial_input_checks'].items():
  if 'archive_member' in x:assert sha(tar.extractfile(x['archive_member']).read())==x['sha256']
ledger=read(O/'saved-input-before.json')['checks'];rawafter={}
for p,w in ledger.items():
 b=(R/p).read_bytes();rawafter[p]=sha(b);assert rawafter[p]==w['sha256'],p
procs=[read(p) for p in sorted((O/'runs').glob('*.process.json'))];ids=set();receipts=[]
for p in procs:
 ids.add((p['runner_pid'],p['runner_starttick']));ids.update((x['pid'],x['start_ticks']) for x in p['tracked']);q=O/'runs'/p['name'];s=read(q/'summary.json');c=read(q/'config.json') if (q/'config.json').exists() else read(O/(p['name']+'.config.json'))
 assert not p['remaining'] and not p['unknown_adopted'];assert s['primary'] is None and not s['secondary']
 inner=read(q/'outer-controlled-stop.json');timers=read(q/'main-timers-stop.json');mon=read(q/'pause-monitor-stop.json');assert inner['remaining_pids']==0 and inner['waited'];assert timers['main_timers']==0 and not timers['pending_messages'];assert not mon['pending_children'] and mon['all_owned_read_callbacks_waited'] and not mon['active_monitor_timer'];drop=read(q/'finally-model-drop.json') if (q/'finally-model-drop.json').exists() else None
 if s['mode']=='NN':assert drop and drop['handles']==0 and drop['activeNN']==0
 receipts.append({'run':p['name'],'config_Git':c['Git'],'start':p['start'],'end':p['end'],'wall_seconds':(datetime.datetime.fromisoformat(p['end'])-datetime.datetime.fromisoformat(p['start'])).total_seconds(),'count_planned':len(c['count_searches']),'count_completed':s['completed'],'public':s['public_response_count'],'NN':s['hand_NN'],'startupNN':s['startup_NN'],'primary':s['primary'],'secondary':s['secondary'],'drop':drop,'timers':timers,'monitor_state':mon['state'],'monitor_failure':mon.get('failure'),'monitor_pending_children':mon['pending_children'],'all_monitor_callbacks_waited':mon['all_owned_read_callbacks_waited'],'inner_forced':inner['forced'],'inner_controlled_remaining':inner['remaining_pids'],'outer_remaining':p['remaining'],'outer_unknown':p['unknown_adopted'],'kernel_adoptions':len(p['kernel_adoptions']),'ledger_registered':p['ledger_registered_count'],'currentRSSpeak':p['peak_group_plus_runner_RSS'],'storagepeak':p['peak_allocated_bytes'],'observed_all_TIDs_CPU2':p['all_observed_TIDs_at_assigned_CPU'],'exit':p['exit'],'raw_summary_generic_denominator_not_used':'count requirements are not public responses'})
currentrows=[{'pid':pid,'starttick':tick,'current':current(pid)} for pid,tick in sorted(ids)];same=[x for x in currentrows if x['current'] and x['current']['starttick']==x['starttick']];assert not same
saved=read(O/'runs/c111-asym-baseline-r1/independent-saved-audit.json');own=read(O/'runs/c111-jump-baseline-r1/independent-four-comparison.json');clock=read(O/'runs/c111-clock-only-r1/independent-clock-audit.json');assert len(own['rows'])==4 and own['backups']==128
source={str(p.relative_to(R)):sha(p.read_bytes()) for p in T.iterdir() if p.is_file()}
summary={'issue':'quoridor-4lc.111','UTC':utc(),'decision':{'C_only_source_binary_and_equal_completed_sensitivity':'finite_support','exploratory_4game_W0L4':'saved_browser_replay_support; not_universal_C_worsening','whole500ms_compute_budget':'not_established','coefficient_adoption_formal_NI_Sigma':'not_certified'},'actual_go':False,'source_Git':before['sourceGit'],'original_data_Git':rev,'primary_checker_Git':'54c2d89003c4e21633c9d78986d35b5781abbcfa','clock_checker_Git':'8381563','primary_order_preserved':True,'own_count_searches':4,'own_backups_NN':128,'own_startupNN':18,'new_public_game_holdout':0,'saved_audit':saved,'independent_count_audit':own,'independent_clock_endpoints':clock,'receipts':receipts,'total_heavy_wall_seconds':sum(x['wall_seconds'] for x in receipts),'max_currentRSS':max(x['currentRSSpeak'] for x in receipts),'max_storage_sampled':max(x['storagepeak'] for x in receipts),'prelaunch_failure':read(O/'prelaunch-directory-failure.json'),'original_failures_separate':['build1 prerequisite failure','build2 same target C binary reuse; build3 distinct targets fixed','baseline-initial completedK32/modelzero with inner OWNED_REGISTRATION_REQUIRED_BEFORE_SIGNAL exit1; outer recovery not inner success'],'design_assessment':['Equal-completed comparison isolates finite C sensitivity; four diagnostic games do not establish coefficient improvement/worsening.','Initial visits unchanged but sum(root edge values) differs; visits equality is not full tree/value equality.','First eligible CP depends on root preparation, API await, request conversion and receipt/validation cost; finite NN output is not a completed eligible CP.','Worker500ms stop failure and API after402/public baseline counterexamples are retained; ACKwall is not CPU time.','Start/end clock intervals are endpoint evidence, not continuous drift or hard realtime guarantee.','RuleA and browser execution infrastructure shared; checker arithmetic separate; arbitrary deep/tree/rawview/entropy/training and true legal200/no-legal remain unproved.'],'source_hashes':source,'resources':{'CPU':2,'NNthreads':1,'RAM':4294967296,'RSSguard':3758096384,'new_scope_guard':29360128,'combined_guard':117440512,'instant_peak_background_CPU_not_guaranteed':True,'initial_short_static_commands_resources_incomplete':True,'default_Git_index_not_written':True}}
save('independent-summary.json',summary);save('input-after.json',{'UTC':utc(),'important_checks':after,'raw_read_initial_and_final_archive_checks':rawafter,'original_archiveSHA':sha(archive),'original_stop_SHA':sha((P/'runtime-source-stopped-before-report.json').read_bytes()),'same_original_stopped_input':True})
allocated=sum(p.stat().st_blocks*512 for root in [O,T,D] if root.exists() for p in root.rglob('*') if p.is_file());assert allocated<29360128
save('runtime-source-stopped-before-report.json',{'UTC':utc(),'monotonic':time.monotonic(),'issue':'quoridor-4lc.111','last_heavy_end':max(x['end'] for x in receipts),'last_NN_window_end':max(x['end'] for x in receipts if x['count_completed']),'heavy_remaining0':True,'same_identity_live':same,'identities_count':len(ids),'identity_current_rows':currentrows,'source_hashes':source,'all_managed_jobs_waited':True,'forced_not_natural':True,'own_scope_current_allocated':allocated,'guard':29360128,'no_new_NN_build_game_holdout':True,'metadata_helper':{'pid':os.getpid(),'identity':current(os.getpid()),'affinity':list(os.sched_getaffinity(0)),'currentRSS':int(pathlib.Path('/proc/self/statm').read_text().split()[1])*os.sysconf('SC_PAGE_SIZE'),'sourceSHA':sha(pathlib.Path(__file__).read_bytes())},'metadata_helper_exit_separate':True})
print(json.dumps({'count':4,'NN':128,'startup':18,'identity':len(ids),'same_live':same,'allocation':allocated,'heavywall':summary['total_heavy_wall_seconds'],'RAMpeak':summary['max_currentRSS'],'storagepeak':summary['max_storage_sampled']}))
