import pathlib
R=pathlib.Path('/workspaces/quoridor/.worktree/ai-sigma');T=R/'tools/ai-sigma-c-factor-independent';s=(R/'tools/ai-sigma-browser-sab-independent/independent-browser.js').read_text()
s=s.replace("must109(game.actions.length===game.turn_indices.length,'GAME_MOVE_COUNT');","must109(game.actions.length+(game.status==='responsibility_loss'?1:0)===game.turn_indices.length,'GAME_MOVE_COUNT');")
s=s.replace("const t=terminalResult(state);must109(t&&t.winner===game.winner&&game.status==='terminal'&&game.reason==='goal','GOAL_RESULT');", "let t=terminalResult(state);if(game.status==='responsibility_loss'){must109(!t,'LOSS_ON_TERMINAL');const bad=map.get(game.turn_indices.at(-1));eq109(bad.identity.legal_prefix,prefix,'LOSS_PREFIX');must109(!bad.response.body.completed&&bad.response.body.action===null&&bad.response.classification==='initial_no_completed_cp','LOSS_CLASS');must109(bad.identity.engine===(state.getCurrentPlayer()===game.candidate_color?'candidate':'reference'),'LOSS_COLOR');const outcome=gameFailureResult(bad.response.classification,state.getCurrentPlayer(),bad.identity.engine);must109(outcome.status==='responsibility_loss'&&outcome.winner===game.winner&&game.reason===outcome.reason,'LOSS_RESPONSIBILITY');t={winner:outcome.winner};}else must109(t&&t.winner===game.winner&&game.status==='terminal'&&game.reason==='goal','GOAL_RESULT');")
s=s.replace("score:t.winner===game.candidate_color?1:t.winner===0?.5:0,prefixSHA", "status:game.status,reason:game.reason,score:t.winner===game.candidate_color?1:t.winner===0?.5:0,prefixSHA")
(T/'independent-browser.js').write_text(s+'\n'+r'''
function independentClassification111(){
 const f=SharedBestAction.STATE.FAULT;const cases=[
 [{late:true,shared_state:f},{error:'NN_FAIL'},'browser_deadline_processing_late'],
 [{judge_error:'typedJudge',shared_state:f},{error:'NN_FAIL'},'browser_judge_failure'],
 [{cancelled:true,late:true,shared_state:f},{error:'NN_FAIL'},'cancel_null'],
 [{external_abort:{code:'BEADS_READ_ERROR'},late:true,cancelled:true,shared_state:f},{error:'NN_FAIL'},'external_automation_failure'],
 [{shared_state:f},null,'ambiguous_shared_fault'],
 [{shared_state:f},{error:'NN_FAIL'},'engine_fault'],
 [{completed:false},null,'initial_no_completed_cp'],
 [{completed:true},null,'completed_legal']];
 return cases.map(([body,fault,expected])=>{const actual=classifyResponse(body,fault),causes=responseCauses(body,fault),outcome=gameFailureResult(actual,1,'candidate');must109(actual===expected,'CLASSIFICATION111');must109(causes.shared_fault===(body.shared_state===f),'CAUSE_SHARED');must109(causes.browser_late===!!body.late&&causes.cancelled===!!body.cancelled&&causes.external_abort===!!body.external_abort,'CAUSE_FLAGS');if(actual==='ambiguous_shared_fault')must109(outcome.status==='unfinished'&&outcome.winner===null,'UNKNOWN_FAULT_UNFINISHED');return{body,fault,expected,actual,causes,outcome};});
}
function f32bits111(v){const b=new ArrayBuffer(4),d=new DataView(b);d.setFloat32(0,v,true);return d.getUint32(0,true)}
function auditCounts111(rows,fixtures,refs){
 const details=rows.map(r=>{const fixture=fixtures.find(f=>f.id===r.fixture_id);must109(fixture&&r.K===32&&r.primary===null,'COUNT_BINDING');const c=r.cp,state=referenceState(fixture);must109(c.simulations===32&&c.tree[0].visits===32&&c.nn_calls===32&&r.NN_calls===32&&r.noNN_backups===0&&!c.cap&&c.terminal_value===null,'K_NN_CAP');must109(r.zero.handles===0&&r.zero.activeNN===0&&r.zero.active===false,'COUNT_ACK_ZERO');eq109(r.backup_counts.map(v=>[v.simulations,v.NN]),Array.from({length:32},(_,i)=>[i+1,i+1]),'ALL_BACKUPS');const edges=c.root_edges,sum=edges.reduce((n,e)=>n+e[2],0);must109(sum===31,'EDGE31');const entropy=-edges.reduce((n,e)=>n+(e[2]?e[2]/31*Math.log(e[2]/31):0),0);must109(Math.abs(entropy-r.entropy)<1e-12,'ENTROPY');eq109(edges.map(e=>[e[0],f32bits111(e[1]),e[2],f32bits111(e[3])]),c.tree[0].edges,'ROOT_TREE_BITS');must109(edges.some(e=>e[0]===c.action),'COUNT_ACTION');let depth=Math.max(...c.tree.map(n=>n.ply))-c.tree[0].ply;must109(depth===c.max_depth,'DEPTH');for(const node of c.tree){must109(Number.isInteger(node.visits)&&node.visits>=1&&node.visits===1+node.edges.reduce((n,e)=>n+e[2],0),'NODE_VISIT_CONSERVATION');}const numeric=numeric109({identity:{engine:'candidate',generation:c.generation,request_id:r.id,legal_prefix:fixture.legal_prefix},response:{body:{cancelled:false}},selected_numeric:{numeric:r.numeric[0],cp:c}},state,fixtures,refs);return {id:r.id,run:r.run,fixture:r.fixture_id,variant:r.variant,K:32,rootN:c.tree[0].visits,edge_sum:sum,NNcalls:r.NN_calls,noNN_backups:r.noNN_backups,cap:c.cap,action:c.action,depth,entropy,root_edge_value_sum:edges.reduce((n,e)=>n+e[3],0),visits:edges.map(e=>[e[0],e[2]]),numeric,wrapper_ms:r.wrapper_end_ms-r.wrapper_start_ms};});
 const compare=[];for(const f of [...new Set(details.map(d=>d.fixture))]){const b=details.find(d=>d.fixture===f&&d.variant==='baseline'),c=details.find(d=>d.fixture===f&&d.variant==='c1');if(!b||!c)continue;eq109(b.visits.map(v=>v[0]),c.visits.map(v=>v[0]),'PAIR_ORDER');const changed=b.visits.filter((v,i)=>v[1]!==c.visits[i][1]).map((v,i)=>({Action:v[0],baseline:v[1],c1:c.visits.find(w=>w[0]===v[0])[1]}));const l1=b.visits.reduce((n,v,i)=>n+Math.abs(v[1]-c.visits[i][1]),0);compare.push({fixture:f,baseline_action:b.action,c1_action:c.action,changed_edges:changed.length,changed,TV:l1/62,L1visit:l1,baseline_entropy:b.entropy,c1_entropy:c.entropy,baseline_depth:b.depth,c1_depth:c.depth,baseline_root_edge_value_sum:b.root_edge_value_sum,c1_root_edge_value_sum:c.root_edge_value_sum});}
 return {rows:details,comparison:compare,backups:details.length*32,NN:details.length*32,rootN_direct_observed:true,browser_executed:true,not_500ms_or_pure_NN_cost_comparison:true};
}
async function auditAll111(input,fixtures,refs){
 const publicAudit=await auditSaved109({runs:input.runs},fixtures,refs),counts=auditCounts111(input.counts,fixtures,refs);const parity=[];
 for(const f of ['initial-p1','asym-hv-p2','straight-jump-p2']){const a=input.parity.find(r=>r.variant==='original'&&r.fixture_id===f),b=input.parity.find(r=>r.variant==='baseline'&&r.fixture_id===f);must109(a&&b&&a.K===8&&b.K===8,'PARITY_CONTEXT');eq109(a.cp,b.cp,'K8_CP_EXACT');eq109(a.numeric[0].features_bits,b.numeric[0].features_bits,'K8_FEATURE_EXACT');const aa=[...a.numeric[0].policy_logits,a.numeric[0].value],bb=[...b.numeric[0].policy_logits,b.numeric[0].value];must109(aa.length===137&&aa.every((v,i)=>Number.isFinite(v)&&Math.abs(v-bb[i])<=1e-4+1e-4*Math.abs(bb[i])),'K8_NN');must109(a.NN_calls===8&&b.NN_calls===8,'K8_NNCOUNT');parity.push({fixture:f,CP_exact:true,features648_exact:true,NN137_mixed:true});}
 const nullCases=[];for(const run of input.runs)for(const row of run.rows){if(row.response.body.completed)continue;const raw=row.null_timing_raw,root=raw.result.spans.find(v=>v.kind==='root'),NN=raw.result.spans.find(v=>v.kind==='NN'),ev=raw.validation_events[0];must109(ev&&!ev.accepted&&ev.error==='AFTER_CUTOFF','NULL_CP_CUTOFF');const clock=row.worker_clock,low=ev.received_ms-clock.hi_ms-row.identity.t0_ms,high=ev.received_ms-clock.lo_ms-row.identity.t0_ms;must109(low>402&&!row.response.body.late&&row.selected_numeric.cp===null,'FIRST_ELIGIBLE_NONE');nullCases.push({request:row.identity.request_id,root_preparation_ms:root.end-root.start,APIawait_ms:row.diagnostic.NN[0].session_run_end_ms-row.diagnostic.NN[0].session_run_start_ms,first_received_interval_elapsed:[low,high],public_elapsed:row.response.public_elapsed_ms,classification:row.response.classification,finite_root_numeric_only:true,eligible_cp:false,prior_missing_not_fabricated:true});}
 return {publicAudit,counts,parity,nullCases,goal_games:publicAudit.runs.flatMap(r=>r.games).filter(g=>g.status==='terminal').length,responsibility_games:publicAudit.runs.flatMap(r=>r.games).filter(g=>g.status==='responsibility_loss').length,original_end_clock:input.runs.map(r=>({run:r.run,clock:r.clock_end})),browser_executed:true,Node_referee:false};
}
''')
