'use strict';
const must109=(x,m)=>{if(!x)throw Error('CRITIC109_'+m)};
const eq109=(a,b,m)=>must109(JSON.stringify(a)===JSON.stringify(b),m);
async function digest109(x){const b=new TextEncoder().encode(JSON.stringify(x)),h=await crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(h),v=>v.toString(16).padStart(2,'0')).join('');}
function numeric109(row,state,fixtures,refs){const x=row.selected_numeric;if(!x)return null;const n=x.numeric;must109(n&&Array.isArray(n.features_bits)&&n.features_bits.length===648,'FEATURE_SHAPE');must109(n.policy_logits.length===136&&n.policy_logits.every(Number.isFinite)&&Number.isFinite(n.value)&&Math.abs(n.value)<=1,'NN_FINITE_STRICT');const f=state.toNNInput();eq109(n.features_bits,Array.from(new Uint32Array(f.buffer,f.byteOffset,f.length)),'FEATURE_BITS');const acts=Array.from(state.getLegalActions()),ids=acts.map(a=>rustAction(state,a));must109(new Set(ids).size===ids.length,'ACTION_INJECTIVE');const p1=state.isPlayer1Turn(),flip=[1,0,2,3,6,7,4,5];const canonical=k=>p1?k:k<8?flip[k]:8+Math.floor((k-8)/64)*64+(7-Math.floor(((k-8)%64)/8))*8+(k-8)%8;const ix=acts.map(a=>canonical(actionToIndex(a,9))),mx=Math.max(...ix.map(k=>n.policy_logits[k])),weights=ix.map(k=>Math.exp(n.policy_logits[k]-mx)),sum=weights.reduce((a,b)=>a+b,0),by=new Map(ids.map((id,i)=>[id,weights[i]/sum]));let priors=0,maxPrior=0;if(x.cp){const c=x.cp;must109(c.generation===row.identity.generation&&c.policy_fallbacks===0&&c.value_fallbacks===0,'CP_GEN_FALLBACK');eq109(c.root_edges.map(e=>e[0]),row.identity.engine==='candidate'?ids.slice().sort((a,b)=>a-b):ids,'ENGINE_ORDER');let visits=0,total=0;for(const e of c.root_edges){must109(e.length===4&&e.every(Number.isFinite)&&e[1]>=0&&Number.isSafeInteger(e[2])&&e[2]>=0&&Math.abs(e[3])<=e[2]+1e-5,'EDGE_RANGE');const want=by.get(e[0]);must109(Number.isFinite(want)&&Math.abs(e[1]-want)<=1e-4+1e-4*Math.abs(want),'PRIOR');maxPrior=Math.max(maxPrior,Math.abs(e[1]-want));total+=e[1];visits+=e[2];priors++;}must109(Math.abs(total-1)<1e-4,'PRIOR_SUM');must109(visits===(row.identity.engine==='candidate'?c.simulations-1:c.simulations),'VISIT_RULE');if(row.identity.engine==='reference')must109(c.root_visits===c.simulations+1,'REF_ROOT_VISITS');}
const fixture=fixtures.find(v=>JSON.stringify(v.legal_prefix)===JSON.stringify(row.identity.legal_prefix)),ref=fixture?refs.find(v=>v.id===fixture.id):null;let maxNN=null;if(ref){maxNN=0;for(const[a,r]of [...n.policy_logits.map((v,i)=>[v,ref.policy_logits[i]]),[n.value,ref.value]]){must109(Number.isFinite(r)&&Math.abs(a-r)<=1e-4+1e-4*Math.abs(r),'EXTERNAL_NN');maxNN=Math.max(maxNN,Math.abs(a-r));}}return {request:row.identity.request_id,engine:row.identity.engine,P2:!p1,cancelled:row.response.body.cancelled,features:648,NN:137,priors,maxNN,maxPrior,fixed_reference:!!ref,valueMeaning:row.identity.engine==='candidate'?'rootNN':'rootQ'};}
async function auditSaved109(input,fixtures,refs){let runs=[],allGames=[],samples=[];for(const r of input.runs){let counts={public:r.rows.length,normal:0,cancel:0,late:0,NN:0,ACKover500:0,Worker_stop:{upper_le_D:0,lower_gt_D:0,straddles_D:0,missing:0},API_after402_definite:0,API_after402_possible:0,API_after_public_definite:0,API_after_public_possible:0},lastACK=-Infinity,markers=[],boundaries=[];const map=new Map(r.rows.map(v=>[v.identity.request_id,v]));for(const row of r.rows){const id=row.identity,p=row.response,b=p.body,state=fromPrefix(id.legal_prefix);must109(id.t0_ms>=lastACK,'NEXT_BEFORE_OLD_ACK');must109(p.t0_ms===id.t0_ms&&p.planned_ms===id.seal_ms&&id.seal_ms-id.t0_ms===411&&id.commit_cutoff_ms-id.t0_ms===402&&id.deadline_ms-id.t0_ms===500,'CLOCK_BINDING');must109(typeof b.completed==='boolean'&&typeof b.cancelled==='boolean'&&typeof b.late==='boolean','BOOLEAN');must109(b.request_id===id.request_id&&b.generation===id.generation&&b.engine===id.engine&&id.epoch===id.generation&&id.model==='d790dac68389f7602ff8a887a2385417d3c925fe22da7164c86e9226f943908d','PUBLIC_IDENTITY');must109(id.key===state._positionKey(),'POSITION_KEY');eq109(id.history,Array.from(state.position_history).sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:0),'HISTORY');must109(id.limits.seed===1979,'SEED');must109(id.limits.simulations===(id.engine==='candidate'?4096:100000),'LIMITS');eq109(b,JSON.parse(p.body_serialized),'PUBLIC_IMMUTABLE');must109(p.bytes===new TextEncoder().encode(p.body_serialized).length,'UTF8_SIZE');must109(p.stamp_ms>=p.timer_ms&&p.public_elapsed_ms===p.stamp_ms-id.t0_ms,'STAMP');must109(b.late===(p.stamp_ms>=id.deadline_ms),'LATE');must109(p.public_did_not_await_ACK&&p.Node_clock_referee_calls===0&&row.Node_per_CP_binding_calls===0,'MAIN_BOUNDARY');if(b.completed){must109(b.action&&!b.cancelled&&!b.late,'COMPLETED');const legal=state.getLegalActions();must109(legal.some(a=>sameAction(a,b.action)),'LEGAL_PUBLIC');const selected=rustAction(state,b.action);const proof=row.diagnostic.sab_publications.find(v=>v.sequence===b.sequence);must109(proof&&proof.action===selected,'COMPLETED_SAB_PUBLIC');counts.normal++;}else{must109(b.action===null,'NULL_ACTION');if(b.cancelled)counts.cancel++;if(b.late)counts.late++;}
const stop=row.stop.stop;must109(stop.handles===0&&stop.activeNN===0&&stop.live_searches===0&&stop.active===false,'ACK_ZERO');lastACK=row.stop.main_received_ms;must109(row.ACK_wall_ms===lastACK-id.t0_ms,'ACKWALL');counts.ACKover500+=lastACK-id.t0_ms>500;const c=row.worker_clock;if(c?.measured&&Number.isFinite(stop.at_ms)){must109(c.samples.length===8,'CALIBRATION_SAMPLES');let lo=Math.max(...c.samples.map(v=>v.worker_ms-v.end_ms-.1)),hi=Math.min(...c.samples.map(v=>v.worker_ms-v.start_ms+.1));must109(lo===c.lo_ms&&hi===c.hi_ms&&lo<=hi,'CLOCK_INTERVAL');let low=stop.at_ms-hi,up=stop.at_ms-lo,klass=up<=id.deadline_ms?'upper_le_D':low>id.deadline_ms?'lower_gt_D':'straddles_D';eq109(row.worker_stop_interval_main,{lower_ms:low,upper_ms:up},'WORKER_STOP');must109(klass===row.worker_stop_class,'STOP_CLASS');counts.Worker_stop[klass]++;if(klass!=='upper_le_D')boundaries.push({request:id.request_id,engine:id.engine,WorkerLower:low-id.t0_ms,WorkerUpper:up-id.t0_ms,ACKwall:lastACK-id.t0_ms});for(const span of row.diagnostic.NN){const low=span.session_run_start_ms-hi,up=span.session_run_start_ms-lo;counts.API_after402_definite+=low>id.commit_cutoff_ms;counts.API_after402_possible+=up>id.commit_cutoff_ms;counts.API_after_public_definite+=low>p.stamp_ms;counts.API_after_public_possible+=up>p.stamp_ms;}}else counts.Worker_stop.missing++;must109(row.hand_NN===row.diagnostic.NN.length,'NN_COUNT');counts.NN+=row.hand_NN;const n=numeric109(row,state,fixtures,refs);if(n)samples.push(n);markers.push({request:id.request_id,timer_late_ms:p.timer_ms-id.seal_ms,adoption_elapsed:p.stamp_ms-id.t0_ms,ACKwall:lastACK-id.t0_ms,adopted_sequence:b.sequence});}
let games=[];for(const game of r.games??[]){let prefix=structuredClone(game.initial_prefix),state=fromPrefix(prefix);must109([1,2].includes(game.candidate_color)&&game.seed===1979,'GAME_SEED_COLOR');must109(game.actions.length+(game.status==='responsibility_loss'?1:0)===game.turn_indices.length,'GAME_MOVE_COUNT');for(let i=0;i<game.actions.length;i++){must109(!terminalResult(state),'TERMINAL_CONTINUATION');const row=map.get(game.turn_indices[i]);must109(row,'MISSING_PUBLIC');eq109(row.identity.legal_prefix,prefix,'PREFIX');must109(row.identity.engine===(state.getCurrentPlayer()===game.candidate_color?'candidate':'reference'),'ENGINE_COLOR');eq109(row.response.body.action,game.actions[i],'GAME_PUBLIC_ACTION');must109(state.getLegalActions().some(a=>sameAction(a,game.actions[i])),'GAME_LEGAL');prefix.push(game.actions[i]);state=state.next(game.actions[i]);}let t=terminalResult(state);if(game.status==='responsibility_loss'){must109(!t,'LOSS_ON_TERMINAL');const bad=map.get(game.turn_indices.at(-1));eq109(bad.identity.legal_prefix,prefix,'LOSS_PREFIX');must109(!bad.response.body.completed&&bad.response.body.action===null&&bad.response.classification==='initial_no_completed_cp','LOSS_CLASS');must109(bad.identity.engine===(state.getCurrentPlayer()===game.candidate_color?'candidate':'reference'),'LOSS_COLOR');const outcome=gameFailureResult(bad.response.classification,state.getCurrentPlayer(),bad.identity.engine);must109(outcome.status==='responsibility_loss'&&outcome.winner===game.winner&&game.reason===outcome.reason,'LOSS_RESPONSIBILITY');t={winner:outcome.winner};}else must109(t&&t.winner===game.winner&&game.status==='terminal'&&game.reason==='goal','GOAL_RESULT');must109(state._positionKey()===game.final_key&&state.depth===game.total_ply,'FINAL_CONTEXT');games.push({game:game.id,color:game.candidate_color,legal_publics:game.actions.length,winner:t.winner,status:game.status,reason:game.reason,score:t.winner===game.candidate_color?1:t.winner===0?.5:0,prefixSHA:await digest109(prefix)});}allGames.push(...games);runs.push({run:r.run,counts,games,late_markers:markers.filter(v=>v.timer_late_ms>10),Worker_stop_exceeds_or_straddles:boundaries,clock_end_measured:false,source_shared_RuleA_logic_independence_limit:true});}return {runs,games:allGames.length,W:allGames.filter(v=>v.score===1).length,D:allGames.filter(v=>v.score===.5).length,L:allGames.filter(v=>v.score===0).length,numeric_samples:samples,browser_executed:true,Node_adjudication:false,saved_original_only:true};}
function independentMock109(){let rows=[],s=fromPrefix([]),acts=s.getLegalActions().map(a=>rustAction(s,a)),context={generation:333,key:s._positionKey(),legalActions:acts},mem=SharedBestAction.create(context),w=SharedBestAction.bind(mem,context,context),r=SharedBestAction.bind(mem,context,context);must109(r.readLatest()===null,'FIRST_NULL');w.publish({completed:true,sequence:1,action:acts[0],value:.25,visits:3});const first=r.readLatest();must109(first.sequence===1&&Object.isFrozen(first),'FROZEN_CP');Atomics.store(new Int32Array(mem),SharedBestAction.INDEX.revision,3);must109(r.readLatest()===first,'BOUNDED_READER_CACHE');Atomics.store(new Int32Array(mem),SharedBestAction.INDEX.revision,4);w.stop('budget');must109(r.readLatest().sequence===1,'BUDGET_KEEP');w.stop('cancel');must109(r.readLatest()===null,'CANCEL_NULL');must109(Object.isFrozen(first)&&first.sequence===1,'PUBLISHED_CP_UNCHANGED');rows.push('bounded_no_wait/cache_keep/cancel_null/old_public_immutable');for(const field of ['generation','key']){try{SharedBestAction.bind(mem,{...context,[field]:field==='key'?'foreign':334},context);throw Error('FOREIGN_ACCEPTED')}catch(e){must109(e.message!=='FOREIGN_ACCEPTED','FOREIGN_REJECT');}}rows.push('foreign_generation_key_rejected');const fresh=SharedBestAction.create(context),v=SharedBestAction.bind(fresh,context,context);for(const cp of [{completed:false,sequence:1,action:acts[0],value:0,visits:1},{completed:true,sequence:1,action:acts[0],value:1.00001,visits:1}]){let rejected=false;try{v.publish(cp)}catch{rejected=true}must109(rejected,'BAD_CP');}v.publish({completed:true,sequence:1,action:acts[0],value:0,visits:1});let failed=false;try{v.publish({completed:true,sequence:1,action:acts[0],value:0,visits:1})}catch{failed=true}must109(failed,'REVERSE_SEQ');Atomics.store(new Int32Array(fresh),SharedBestAction.INDEX.generation,334);must109(v.readLatest()===null,'STALE_GENERATION');rows.push('incomplete/range/duplicate/stale_rejected');for(const c of ['initial_no_completed_cp','engine_fault'])must109(gameFailureResult(c,1,'candidate').status==='responsibility_loss','AI_LOSS');for(const c of ['browser_deadline_processing_late','browser_judge_failure','external_automation_failure'])must109(gameFailureResult(c,1,'candidate').status==='unfinished','BROWSER_UNFINISHED');must109(terminalResult(new State({boardsize:9,depth:200})).winner===0,'DRAW200');must109(terminalResult(new State({boardsize:9,depth:200,player1pos:[4,8],player2pos:[4,7]})).winner===1,'GOAL_PRIORITY');return {rows,NN:0,browser_main_executed:true,actual_SharedBestAction:true,synthetic200_not_legal_reachability:true};}
async function calibrateEnd109(){const samples=[];for(let i=0;i<8;i++){const start_ms=epochMain(),reply=await pingEarly(),end_ms=epochMain();samples.push({start_ms,end_ms,worker_ms:reply.at_ms});}const lo_ms=Math.max(...samples.map(v=>v.worker_ms-v.end_ms-.1)),hi_ms=Math.min(...samples.map(v=>v.worker_ms-v.start_ms+.1));must109(lo_ms<=hi_ms,'END_CLOCK');return {lo_ms,hi_ms,error_ms:(hi_ms-lo_ms)/2+.1,samples,not_applied_to_original_run:true};}


function independentClassification111(){
 const f=SharedBestAction.STATE.FAULT;const cases=[
 [{late:true,shared_state:f},{error:'NN_FAIL'},'browser_deadline_processing_late'],
 [{judge_error:'typedJudge',shared_state:f},{error:'NN_FAIL'},'browser_judge_failure'],
 [{cancelled:true,late:true,shared_state:f},{error:'NN_FAIL'},'cancel_null'],
 [{external_abort:{code:'BEADS_READ_ERROR'},late:true,cancelled:true,shared_state:f},{error:'NN_FAIL'},'external_automation_failure'],
 [{shared_state:f},null,'ambiguous_shared_fault'],
 [{shared_state:f},{error:'NN_FAIL'},'engine_fault'],
 [{completed:false},null,'initial_no_completed_cp'],
 [{completed:true},null,'completed_legal']];
 return cases.map(([body,fault,expected])=>{const actual=classifyResponse(body,fault),causes=responseCauses(body,fault),outcome=gameFailureResult(actual,1,'candidate');must109(actual===expected,'CLASSIFICATION111');must109(causes.shared_fault===(body.shared_state===f),'CAUSE_SHARED');must109(causes.browser_late===!!body.late&&causes.cancelled===!!body.cancelled&&causes.external_abort===!!body.external_abort,'CAUSE_FLAGS');if(actual==='ambiguous_shared_fault')must109(outcome.status==='unfinished'&&outcome.winner===null,'UNKNOWN_FAULT_UNFINISHED');return{body,fault,expected,actual,causes,outcome};});
}
function f32bits111(v){const b=new ArrayBuffer(4),d=new DataView(b);d.setFloat32(0,v,true);return d.getUint32(0,true)}
function auditCounts111(rows,fixtures,refs){
 const details=rows.map(r=>{const fixture=fixtures.find(f=>f.id===r.fixture_id);must109(fixture&&r.K===32&&r.primary===null,'COUNT_BINDING');const c=r.cp,state=referenceState(fixture);must109(c.simulations===32&&c.tree[0].visits===32&&c.nn_calls===32&&r.NN_calls===32&&r.noNN_backups===0&&!c.cap&&c.terminal_value===null,'K_NN_CAP');must109(r.zero.handles===0&&r.zero.activeNN===0&&r.zero.active===false,'COUNT_ACK_ZERO');eq109(r.backup_counts.map(v=>[v.simulations,v.NN]),Array.from({length:32},(_,i)=>[i+1,i+1]),'ALL_BACKUPS');const edges=c.root_edges,sum=edges.reduce((n,e)=>n+e[2],0);must109(sum===31,'EDGE31');const entropy=-edges.reduce((n,e)=>n+(e[2]?e[2]/31*Math.log(e[2]/31):0),0);must109(Math.abs(entropy-r.entropy)<1e-12,'ENTROPY');eq109(edges.map(e=>[e[0],f32bits111(e[1]),e[2],f32bits111(e[3])]),c.tree[0].edges,'ROOT_TREE_BITS');must109(edges.some(e=>e[0]===c.action),'COUNT_ACTION');let depth=Math.max(...c.tree.map(n=>n.ply))-c.tree[0].ply;must109(depth===c.max_depth,'DEPTH');for(const node of c.tree){must109(Number.isInteger(node.visits)&&node.visits>=1&&node.visits===1+node.edges.reduce((n,e)=>n+e[2],0),'NODE_VISIT_CONSERVATION');}const numeric=numeric109({identity:{engine:'candidate',generation:c.generation,request_id:r.id,legal_prefix:fixture.legal_prefix},response:{body:{cancelled:false}},selected_numeric:{numeric:r.numeric[0],cp:c}},state,fixtures,refs);return {id:r.id,run:r.run,fixture:r.fixture_id,variant:r.variant,K:32,rootN:c.tree[0].visits,edge_sum:sum,NNcalls:r.NN_calls,noNN_backups:r.noNN_backups,cap:c.cap,action:c.action,depth,entropy,root_edge_value_sum:edges.reduce((n,e)=>n+e[3],0),visits:edges.map(e=>[e[0],e[2]]),numeric,wrapper_ms:r.wrapper_end_ms-r.wrapper_start_ms};});
 const compare=[];for(const f of [...new Set(details.map(d=>d.fixture))]){const b=details.find(d=>d.fixture===f&&d.variant==='baseline'),c=details.find(d=>d.fixture===f&&d.variant==='c1');if(!b||!c)continue;eq109(b.visits.map(v=>v[0]),c.visits.map(v=>v[0]),'PAIR_ORDER');const changed=b.visits.filter((v,i)=>v[1]!==c.visits[i][1]).map((v,i)=>({Action:v[0],baseline:v[1],c1:c.visits.find(w=>w[0]===v[0])[1]}));const l1=b.visits.reduce((n,v,i)=>n+Math.abs(v[1]-c.visits[i][1]),0);compare.push({fixture:f,baseline_action:b.action,c1_action:c.action,changed_edges:changed.length,changed,TV:l1/62,L1visit:l1,baseline_entropy:b.entropy,c1_entropy:c.entropy,baseline_depth:b.depth,c1_depth:c.depth,baseline_root_edge_value_sum:b.root_edge_value_sum,c1_root_edge_value_sum:c.root_edge_value_sum});}
 return {rows:details,comparison:compare,backups:details.length*32,NN:details.length*32,rootN_direct_observed:true,browser_executed:true,not_500ms_or_pure_NN_cost_comparison:true};
}
async function auditAll111(input,fixtures,refs){
 const publicAudit=await auditSaved109({runs:input.runs},fixtures,refs),counts=auditCounts111(input.counts,fixtures,refs);const parity=[];
 for(const f of ['initial-p1','asym-hv-p2','straight-jump-p2']){const a=input.parity.find(r=>r.variant==='original'&&r.fixture_id===f),b=input.parity.find(r=>r.variant==='baseline'&&r.fixture_id===f);must109(a&&b&&a.K===8&&b.K===8,'PARITY_CONTEXT');eq109(a.cp,b.cp,'K8_CP_EXACT');eq109(a.numeric[0].features_bits,b.numeric[0].features_bits,'K8_FEATURE_EXACT');const aa=[...a.numeric[0].policy_logits,a.numeric[0].value],bb=[...b.numeric[0].policy_logits,b.numeric[0].value];must109(aa.length===137&&aa.every((v,i)=>Number.isFinite(v)&&Math.abs(v-bb[i])<=1e-4+1e-4*Math.abs(bb[i])),'K8_NN');must109(a.NN_calls===8&&b.NN_calls===8,'K8_NNCOUNT');parity.push({fixture:f,CP_exact:true,features648_exact:true,NN137_mixed:true});}
 const nullCases=[];for(const run of input.runs)for(const row of run.rows){if(row.response.body.completed)continue;const raw=row.null_timing_raw,root=raw.result.spans.find(v=>v.kind==='root'),NN=raw.result.spans.find(v=>v.kind==='NN'),ev=raw.validation_events[0];must109(ev&&!ev.accepted&&ev.error==='AFTER_CUTOFF','NULL_CP_CUTOFF');const clock=row.worker_clock,low=ev.received_ms-clock.hi_ms-row.identity.t0_ms,high=ev.received_ms-clock.lo_ms-row.identity.t0_ms;must109(low>402&&!row.response.body.late&&row.selected_numeric.cp===null,'FIRST_ELIGIBLE_NONE');nullCases.push({request:row.identity.request_id,root_preparation_ms:root.end-root.start,APIawait_ms:row.diagnostic.NN[0].session_run_end_ms-row.diagnostic.NN[0].session_run_start_ms,first_received_interval_elapsed:[low,high],public_elapsed:row.response.public_elapsed_ms,classification:row.response.classification,finite_root_numeric_only:true,eligible_cp:false,prior_missing_not_fabricated:true});}
 return {publicAudit,counts,parity,nullCases,goal_games:publicAudit.runs.flatMap(r=>r.games).filter(g=>g.status==='terminal').length,responsibility_games:publicAudit.runs.flatMap(r=>r.games).filter(g=>g.status==='responsibility_loss').length,original_end_clock:input.runs.map(r=>({run:r.run,clock:r.clock_end})),browser_executed:true,Node_referee:false};
}
function auditClocks111(input){
 function calc(c){must109(c.samples.length===8,'END_CLOCK_SAMPLES');const lo=Math.max(...c.samples.map(v=>v.worker_ms-v.end_ms-.1)),hi=Math.min(...c.samples.map(v=>v.worker_ms-v.start_ms+.1));must109(lo<=hi&&lo===c.lo_ms&&hi===c.hi_ms,'END_CLOCK_RECALC');return{lo,hi};}
 return input.runs.map(run=>{const start=calc(run.rows[0].worker_clock),end=calc(run.clock_end),envelope={lo:Math.min(start.lo,end.lo),hi:Math.max(start.hi,end.hi)},counts={upper_le_D:0,lower_gt_D:0,straddles_D:0,API_after402_definite:0,API_after402_possible:0,API_afterpublic_definite:0,API_afterpublic_possible:0};let maxPublic=0,maxACK=0,maxTimerDelay=0;
 for(const row of run.rows){const id=row.identity,low=row.stop.stop.at_ms-envelope.hi,high=row.stop.stop.at_ms-envelope.lo;counts[high<=id.deadline_ms?'upper_le_D':low>id.deadline_ms?'lower_gt_D':'straddles_D']++;for(const v of row.diagnostic.NN){counts.API_after402_definite+=v.session_run_start_ms-envelope.hi>id.commit_cutoff_ms;counts.API_after402_possible+=v.session_run_start_ms-envelope.lo>id.commit_cutoff_ms;counts.API_afterpublic_definite+=v.session_run_start_ms-envelope.hi>row.response.stamp_ms;counts.API_afterpublic_possible+=v.session_run_start_ms-envelope.lo>row.response.stamp_ms;}maxPublic=Math.max(maxPublic,row.response.public_elapsed_ms);maxACK=Math.max(maxACK,row.ACK_wall_ms);maxTimerDelay=Math.max(maxTimerDelay,row.response.timer_ms-id.seal_ms);}
 return {run:run.run,public:run.rows.length,start,end,start_end_intersection:[Math.max(start.lo,end.lo),Math.min(start.hi,end.hi)],conservative_observed_endpoint_envelope:envelope,counts,maxPublic,maxACK,maxTimerDelay,endpoints_not_continuous_drift_guarantee:true,not_kernel_instruction_time:true};});
}
