'use strict';
// 238 saved-hand replay only. Shared RuleA, own joins/history/winner arithmetic.
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const args=process.argv.slice(2),get=k=>args[args.indexOf(k)+1];if(get('--task')!=='frame19-rule-replay-238-v1')throw Error('task');
const P=path.resolve('research-data/ai-sigma/frame19-native-arena'),read=n=>JSON.parse(fs.readFileSync(path.join(P,n),'utf8')),assert=(b,m)=>{if(!b)throw Error(m)},sig=x=>JSON.stringify(x);
const manifest=JSON.parse(fs.readFileSync(get('--input-manifest'),'utf8')),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');for(const[p,h]of Object.entries(manifest.SHA))assert(hash(p)===h,'changed '+p);
const {r}=require(path.resolve('tools/ai-sigma-native-baseline/reference.cjs')).createReference();const history=s=>JSON.stringify([s._positionKey(),s.getCurrentPlayer(),[...s.position_history].sort(([a],[b])=>a<b?-1:a>b?1:0)]),op=read('openings8-v1.json'),all=read('all-attempt-result-v1.json');const openings=new Map();
for(const o of op.openings){const s=r.fromPrefix(o.prefix);assert(!r.terminalResult(s),'opening terminal');assert(s.depth===o.opening_ply&&s._positionKey()===o.key&&history(s)===o.history&&s.getLegalActions().length===o.legal_count,'opening bind');openings.set(o.id,o)}
const hands=['pilot-r2-hands.jsonl','later4-r1-hands.jsonl'].flatMap(n=>fs.readFileSync(path.join(P,n),'utf8').trim().split('\n').filter(Boolean).map(JSON.parse)),by=new Map();for(const x of hands){if(!by.has(x.slot))by.set(x.slot,[]);by.get(x.slot).push(x)}let accepted=0,p2=0,jump=0,wall=0;const results=[];
function step(s,h){const c=h.clock;assert(!r.terminalResult(s),'pre terminal');assert(s.depth===h.ply&&s.getCurrentPlayer()===h.side,'ply side');if(c.status!=='RECEIVED')return null;const q=c.response.search;assert(q.root_key===s._positionKey()&&q.root_history===history(s),'input key/history');const legal=s.getLegalActions(),choices=legal.filter(a=>r.rustAction(s,a)===q.Action);assert(choices.length===1,'Action legality');const a=choices[0];const ds=q.depths.filter(d=>d.status==='COMPLETED');assert(ds.every(d=>d.root_all_legal_count===legal.length),'all root legal');accepted++;if(h.side===2)p2++;if(a.type==='wall')wall++;else if(Math.abs(a.direction[0])+Math.abs(a.direction[1])>1)jump++;return a}
for(const g of all.ledger){const o=openings.get(g.opening);let s=r.fromPrefix(o.prefix),prefix=[...o.prefix];for(const h of by.get(g.slot)){const a=step(s,h);if(a){prefix.push(a);s=s.next(a)}}assert(sig(prefix)===sig(g.prefix),'full prefix');const term=r.terminalResult(s);if(g.status==='UNKNOWN'){assert(!term,'unknown prefix terminal')}else{assert(term&&term.winner===g.winner,'winner');assert(g.status==='TERMINAL'&&g.result_NNUE===(term.winner===0?'D':term.winner===g.NNUE_side?'W':'L'),'WDL')}assert(s.depth===g.final_ply,'final ply');results.push({slot:g.slot,status:g.status,winner:term?term.winner:null,final_ply:s.depth,accepted_moves:prefix.length-o.prefix.length,legal_prefix:true,history_bound:true})}
const oldrows=fs.readFileSync(path.join(P,'pilot-r1-hands.jsonl'),'utf8').trim().split('\n').map(JSON.parse);let oldstate=r.fromPrefix(openings.get('opening0').prefix),oldaccepted=0;for(const h of oldrows){const a=step(oldstate,h);if(a){oldstate=oldstate.next(a);oldaccepted++}}assert(!r.terminalResult(oldstate),'old censored terminal');
for(const[p,h]of Object.entries(manifest.SHA))assert(hash(p)===h,'changed after '+p);const out={schema:'frame19-native-independent-v1',task:get('--task'),PASS:true,newNN:0,openings:4,slots:8,results,accepted_main:results.reduce((s,x)=>s+x.accepted_moves,0),old_censored_accepted:oldaccepted,total_replayed:accepted,P2_moves:p2,jumps:jump,walls:wall,old_censored_nonterminal:true,limits:['shared RuleA implementation, not independent rules oracle','saved adopted root actions only; no all deep/minimax truth','state copy/recorded history preservation, no universal mutable undo proof']};fs.writeFileSync(get('--out'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out));
