'use strict';const fs=require('fs'),{D,save,now,runControlled}=require('./common.cjs'),{Engine}=require('./controller.cjs'),{createReference}=require('./reference.cjs'),{admitCP}=require('./clock.cjs');const c=JSON.parse(fs.readFileSync(process.argv[2])),input=JSON.parse(fs.readFileSync(D+'/stageB-inputs.json')),{r}=createReference(),sleep=ms=>new Promise(resolve=>setTimeout(resolve,Math.max(0,ms)));
runControlled(c,async check=>{const engines={},init={},closed={},games=[],journal=[],attempted=[],primary=[];let generation=0;const begin=now();
try{
 if(!JSON.parse(fs.readFileSync(D+'/native165-mechanism-r1-analysis.json')).StageB_allowed)throw Error('STAGEA_NOT_SUPPORTED');
 for(const engine of ['candidate','reference']){check();engines[engine]=new Engine(engine);init[engine]=await engines[engine].init(false);check();}
 for(const spec of c.games){check();const opening=input.rows.find(x=>x.fixture?.id===spec.fixture_id);if(!opening?.accepted){games.push({...spec,status:'GENERATION_MISSING',unknown:true});continue}const gameStart=now();let state=r.fromPrefix(opening.fixture.legal_prefix),prefix=structuredClone(opening.fixture.legal_prefix),result=null,firstRoot=null;
 attempted.push(spec.game_id);
 while(!result){check();const term=r.terminalResult(state);if(term){result={status:term.winner?'GOAL':state.depth>=200?'DRAW200':'DRAW_NOLEGAL',winner:term.winner,score:term.winner?(term.winner===spec.candidate_player?1:0):.5,pure_terminal_quality:true};break}
 const player=state.getCurrentPlayer(),engine=player===spec.candidate_player?'candidate':'reference',legalObjects=state.getLegalActions(),legal=Array.from(legalObjects,a=>r.rustAction(state,a)),gen=++generation,e=engines[engine];let cache=null,finalized=false,firstCP=null,cpSeen=0,admitted=0,late=0,schema=0,publicMs=null,publicCP=null,runResult=null,runError=null,cutMs=null;
 // Both engines are quiescent here: prior search result awaited before leavingprevious loop.
 const t0=now();const work=e.request({op:'search',fixture_id:spec.fixture_id,legal_prefix:prefix,generation:gen,trace:false,K:1000000,watchdog_ms:10000},(x,receive)=>{cpSeen++;if(firstCP===null)firstCP=receive-t0;const end=now(),v=admitCP({cp:x.cp,receive,validateEnd:end,t0,cutoff:402,generation:gen,legal,finalized});if(v.accepted){admitted++;cache={cp:structuredClone(x.cp),receive_ms:receive-t0,admit_ms:end-t0};}else if(v.code==='LATE_CP'||v.code==='AFTER_PUBLIC')late++;else schema++;}).then(x=>{runResult=x.data;if(x.data?.primary)runError=x.data.primary.message},e=>{runError=e.message});
 await sleep(t0+402-now());cutMs=now()-t0;e.stopCurrent();await sleep(t0+411-now());publicMs=now()-t0;finalized=true;if(publicMs<=500&&cache)publicCP=cache;
 // Cause-side cleanup: receivequiescent result; nextactualt0 is alwaysafter thisreceipt.
 const publicTime=now();await work;const quiescent=now(),cleanupMs=quiescent-publicTime;check();
 const row={game_id:spec.game_id,pair:spec.pair,ply:state.depth,player,engine,generation:gen,key:state._positionKey(),root_history_count:state.position_history.get(state._positionKey()),controller_t0_ms:t0,firstCP_ms:firstCP,cut_actual_ms:cutMs,public_actual_ms:publicMs,public_cp:publicCP,CP_received:cpSeen,CP_admitted:admitted,CP_late_discarded:late,CP_schema_rejected:schema,quiescent_receive_ms:quiescent-t0,cleanup_after_public_ms:cleanupMs,NN_calls:runResult?.NN_calls??null,completed:runResult?.completed??null,NN_discarded:runResult?.discardedNN??null,terminal_noNN:runResult?.terminal_noNN??null,worker_elapsed_ms:runResult?.request_ms??null,zero:runResult?.zero??null,error:runError,API_total_ms:runResult?.spans.reduce((s,x)=>s+x.API_ms,0)??null,API_first_ms:runResult?.spans[0]?.API_ms??null,API_steady_mean_ms:runResult?.spans.length>1?runResult.spans.slice(1).reduce((s,x)=>s+x.API_ms,0)/(runResult.spans.length-1):null,NN_pipe_total_ms:runResult?.spans.reduce((s,x)=>s+x.pipe_ms,0)??null,NN_process_CPU_ms_aux:runResult?.spans.reduce((s,x)=>s+x.process_CPU_ms,0)??null,clock_scope:'controller only; APIprocessCPUaux not all kernelCPU'};
 if(state.depth===opening.fixture.target_ply)firstRoot={engine,key:row.key,side:player,features_bits:runResult?.first_NN?.features_bits??null,NN_bits:runResult?.first_NN?.NN_bits??null,NN_calls:row.NN_calls,completed:row.completed,publicCP,firstCP_ms:firstCP};
 journal.push(row);fs.appendFileSync(c.job_out+'/journal.jsonl',JSON.stringify(row)+'\n');
 if(runError){result={status:engine==='candidate'?'CANDIDATE_FAULT':'REFERENCE_FAULT',error:runError,score:engine==='candidate'?0:null,pure_terminal_quality:false,winner:null};break}
 if(!runResult?.zero||runResult.zero.activeNN||runResult.zero.handles||runResult.zero.active){result={status:'QUIESCENCE_UNKNOWN',score:null,pure_terminal_quality:false,winner:null};break}
 if(!publicCP){result={status:publicMs>500?'CLOCK_LATE':engine==='candidate'?'CANDIDATE_FIRSTNONE':'REFERENCE_FIRSTNONE',score:publicMs<=500&&engine==='candidate'?0:null,pure_terminal_quality:false,winner:null};break}
 const i=legal.indexOf(publicCP.cp.action);if(i<0){result={status:engine==='candidate'?'CANDIDATE_FAULT':'REFERENCE_FAULT',error:'ILLEGAL_PUBLIC',score:engine==='candidate'?0:null,pure_terminal_quality:false,winner:null};break}
 const a=legalObjects[i];prefix.push(a);state=state.next(a);
 }
 const game={...spec,...result,final_ply:state.depth,plies_played:state.depth-opening.fixture.target_ply,elapsed_ms:now()-gameStart,final_key:state._positionKey(),firstRoot,legal_prefix:prefix};games.push(game);save(c.job_out+'/games-progress.json',{games,attempted});
 }
}catch(e){primary.push({message:e.message,stack:e.stack})}finally{for(const [engine,e]of Object.entries(engines)){e.stopCurrent();try{closed[engine]=await e.close()}catch(error){closed[engine]={error:error.message}}}}
for(const spec of c.games)if(!games.some(x=>x.game_id===spec.game_id))games.push({...spec,status:'NOT_STARTED_OR_UNFINISHED',score:null,pure_terminal_quality:false,winner:null});
const result={issue:c.issue,run:c.run_id,init,closed,games,attempted,primary,planned:c.games.length,public_hand_requests:journal.length,hand_NN:journal.reduce((s,x)=>s+(x.NN_calls??0),0),startup_NN:Object.values(init).reduce((s,x)=>s+(x.startup?.count??0),0),elapsed_ms:now()-begin,clock_mode:'native-event-driven-quiescent;cut402/public411/deadline500;cleanupcause-side',formal_ready:false};save(c.job_out+'/result.json',result);if(primary.length)throw Error('ARENA_CONTROL_OR_INFRA_FAILURE');return{games:games.length,requests:journal.length,hand_NN:result.hand_NN,startup_NN:result.startup_NN};}).catch(e=>{console.error(e.stack);process.exitCode=1});
