"""All16 denominators and measured native route costs, no NI/strength inference."""
import json,hashlib,statistics,datetime,sys
from pathlib import Path
R=Path(__file__).resolve().parents[2];D=R/'research-data/ai-sigma/165-native-baseline';A=R/'.artifacts/ai-sigma/resume-20261003/NATIVE-BASELINE'
load=lambda p:json.loads(p.read_text());fixed=load(D/'stageB-inputs.json');games=[];jobs=[];journal=[]
for pair in range(1,9):
 name='native165-pair'+str(pair).zfill(2)+'-r1';folder=A/'runs'/name;p=folder/'result.json';z=load(p) if p.exists() else load(folder/'games-progress.json') if (folder/'games-progress.json').exists() else {'games':[]};proc=A/'runs'/(name+'.process.json');control=folder/'control-summary.json';jobs.append({'run':name,'process':load(proc) if proc.exists() else None,'result_SHA256':hashlib.sha256(p.read_bytes()).hexdigest() if p.exists() else None,'control':load(control) if control.exists() else None,'startup_NN':z.get('startup_NN'),'init':z.get('init'),'closed':z.get('closed'),'elapsed_ms':z.get('elapsed_ms')})
 for spec in fixed['games']:
  if spec['pair']!=pair:continue
  g=next((g for g in z['games'] if g['game_id']==spec['game_id']),None) or {**spec,'status':'NOT_STARTED_OR_UNFINISHED','score':None,'winner':None,'pure_terminal_quality':False}
  games.append(g)
 jp=folder/'journal.jsonl'
 if jp.exists():journal.extend({**json.loads(line),'run':name,'pair':pair} for line in jp.read_text().splitlines())
def interval(values):
 known=[v for v in values if v is not None];return{'denominator':len(values),'known':len(known),'unknown':len(values)-len(known),'mean_if_all_known':sum(known)/len(values) if len(known)==len(values) else None,'identified_lower':sum(known)/len(values),'identified_upper':(sum(known)+len(values)-len(known))/len(values),'complete_only_aux':sum(known)/len(known) if known else None}
def stat(xs):
 xs=[x for x in xs if x is not None];s=sorted(xs)
 return{'n':len(xs),'mean':statistics.mean(xs) if xs else None,'min':min(xs) if xs else None,'p50':statistics.median(xs) if xs else None,'p95':s[min(len(s)-1,int(.95*len(s)))] if xs else None,'max':max(xs) if xs else None,'sum':sum(xs)}
pairs=[]
for pair in range(1,9):
 gs=[g for g in games if g['pair']==pair];op=interval([g.get('score') for g in gs]);quality=interval([g.get('score') if g.get('pure_terminal_quality') else None for g in gs]);fr=[g.get('firstRoot') for g in gs];opening_root_exact=bool(all(fr) and fr[0].get('features_bits') is not None and fr[0].get('NN_bits') is not None and fr[0]['features_bits']==fr[1]['features_bits'] and fr[0]['NN_bits']==fr[1]['NN_bits']);pairs.append({'pair':pair,'game_ids':[g['game_id'] for g in gs],'operational_Xi':op['mean_if_all_known'],'operational_range':[op['identified_lower'],op['identified_upper']],'pure_quality_Xi':quality['mean_if_all_known'],'pure_quality_range':[quality['identified_lower'],quality['identified_upper']],'both_same_board_side_winner':gs[0].get('winner')==gs[1].get('winner') and gs[0].get('winner') in [1,2],'sameopening_backend_NN137bits_exact':opening_root_exact,'first_roots':[None if x is None else {k:x.get(k) for k in ['engine','side','NN_calls','completed','firstCP_ms']} for x in fr]})
engine_metrics={}
for engine in ['candidate','reference']:
 rows=[x for x in journal if x['engine']==engine];engine_metrics[engine]={'requests':len(rows),'started_NN':sum(x['NN_calls'] or 0 for x in rows),'adopted_NN':sum(x['public_cp']['cp']['nn_calls'] for x in rows if x['public_cp']),'NN_discarded':sum(x['NN_discarded'] or 0 for x in rows),'completed_K':stat(x['completed'] for x in rows),'adopted_K':stat(x['public_cp']['cp']['simulations'] for x in rows if x['public_cp']),'firstCP_ms':stat(x['firstCP_ms'] for x in rows),'API_first_ms':stat(x['API_first_ms'] for x in rows),'API_steady_mean_ms':stat(x['API_steady_mean_ms'] for x in rows),'API_total_ms':stat(x['API_total_ms'] for x in rows),'NN_pipe_total_ms':stat(x['NN_pipe_total_ms'] for x in rows),'NN_process_CPU_ms_aux_not_all_kernel':stat(x['NN_process_CPU_ms_aux'] for x in rows),'public_ms':stat(x['public_actual_ms'] for x in rows),'cleanup_after_public_ms':stat(x['cleanup_after_public_ms'] for x in rows),'CP_late_discarded':sum(x['CP_late_discarded'] for x in rows),'terminal_noNN':sum(x['terminal_noNN'] or 0 for x in rows)}
control_success=all(j['process'] and j['process']['exit']==0 and not j['process']['stop_reason'] and not j['process']['remaining'] and not j['process']['unknown_adopted'] and j['control'] and j['control']['control'] is None and j['control']['primary'] is None for j in jobs)
next_gate=[]
for pair in range(1,9):
 rows=[x for x in journal if x['pair']==pair]
 for left,right in zip(rows,rows[1:]):
  gate=left.get('quiescent_gate_observed_ms',left['quiescent_receive_ms']);next_gate.append(right['controller_t0_ms']-(left['controller_t0_ms']+gate))
assert not next_gate or min(next_gate)>=0,'NEXT_START_BEFORE_PRIOR_QUIESCENCE_GATE'
alljobs=[load(p) for p in (A/'runs').glob('*.process.json')];duration=lambda x:(datetime.datetime.fromisoformat(x['end'])-datetime.datetime.fromisoformat(x['start'])).total_seconds();cost={phase:sum(duration(x) for x in alljobs if x['phase']==phase) for phase in ['build','protocol','mechanism','arena']};game_ms=sum(g.get('elapsed_ms') or 0 for g in games);terminal=[g for g in games if g.get('pure_terminal_quality')];teacher=load(D/'opening-teacher-summary.json') if (D/'opening-teacher-summary.json').exists() else None
out={'issue':'quoridor-4lc.165','StageA':load(D/'native165-mechanism-r1-analysis.json'),'StageB':{'planned_games':16,'planned_pairs':8,'started':sum(len(load(A/'runs'/j['run']/'result.json')['attempted']) for j in jobs if (A/'runs'/j['run']/'result.json').exists()),'typed_status_counts':{s:sum(g['status']==s for g in games) for s in sorted({g['status'] for g in games})},'operational':interval([g.get('score') for g in games]),'pure_terminal_quality':interval([g.get('score') if g.get('pure_terminal_quality') else None for g in games]),'WDL_terminal':{'W':sum(g.get('score')==1 for g in terminal),'D':sum(g.get('score')==.5 for g in terminal),'L':sum(g.get('score')==0 for g in terminal)},'pairs':pairs,'games':games,'engine_metrics':engine_metrics,'public_requests':len(journal),'startup_NN':sum(j['startup_NN'] or 0 for j in jobs),'hand_NN':sum(x['NN_calls'] or 0 for x in journal),'source_clock_rule':'quiescent event-driven cut402/public411/deadline500','all_saved_prevalidation_admit_stamps_le402':all(x['public_cp'] and x['public_cp']['admit_ms']<=402 for x in journal),'all_public_le500':all(x['public_actual_ms']<=500 for x in journal),'nextt0_after_observed_zero':bool(next_gate) and min(next_gate)>=0,'next_start_gap_ms':stat(next_gate),'pair1_actual_result_receive_missing':True,'old_field_pair1_gate_observe_erratum_preserved':True,'job_control_success':control_success},'cost_seconds':cost,'heavy_total_s':sum(cost[p] for p in ['build','mechanism','arena']),'game_total_s':game_ms/1000,'game_per_s_game_section':len(terminal)/(game_ms/1000) if game_ms else None,'game_per_s_quality_job':len(terminal)/cost['arena'] if cost['arena'] else None,'opening_teachers':teacher,'valid_opening_teacher_rows_per_quality_s':teacher['valid_rows']/cost['arena'] if teacher and cost['arena'] else None,'peak_own_group_plus_guardian_RSS':max(x['peak_group_plus_runner_RSS'] for x in alljobs),'peak_own_allocated_bytes_observed':max(x['peak_allocated_bytes'] for x in alljobs),'currentidentity_fullperiod_allhost_not_claimed':True,'formal_ready':False,'NI_or_Sigma_strength_proof':False,'next_max1':'separately preregister finite realORT cancellation and samewall validation of repaired native adapter before larger native evaluation/teacher generation; no scientific replacement or NNUE expansion','jobs':jobs}
out['clock_erratum']={'old_admit_stamp_before_legal_clone_cache':True,'actual_adopt_completion_old16':'unknown','old_max_saved_stamp_ms':max(x['public_cp']['admit_ms'] for x in journal),'samewall_clock_established':False,'terminal_win_score_unchanged':True,'reference_late_CP_not_adopted':engine_metrics['reference']['CP_late_discarded'],'all_late_CP_not_adopted':sum(x['CP_late_discarded'] for x in journal),'terminal_cancel_defect_reference_cleanup_s':engine_metrics['reference']['cleanup_after_public_ms']['sum']/1000,'all_saved_stamps_le402_not_actual_completion_proof':True}
out['repair_NN0']={'source_git':'a78ea8336edc84c9716fee8972c86d94200941b6','run':'native165-control-repair-r1','new_ORT_NN':0,'tape_evaluations':320,'CP_path_visits_ledger_to_original_exact':True,'real_ORT_cancel_revalidated':False,'new_adapter_samewall_measured':False,'stop':'control-repair-stop.json'}
out['unmeasured_components']=['isolated feature generation','legal generation and history replay','all-engine kernel CPU','exact CP Atomic/store time (native JSON IPC)','init transport vs ORT isolated decomposition']
# Raw games/roots/threads/control snapshots belong to the immutable run archive;
# compact canonical arithmetic links those bytes without duplicating all traces.
out['StageB']['games']=[{k:g.get(k) for k in ['game_id','pair','fixture_id','candidate_player','color_order','status','winner','score','pure_terminal_quality','final_ply','plies_played','elapsed_ms','final_key']} for g in games]
out['jobs']=[{'run':j['run'],'result_SHA256':j['result_SHA256'],'startup_NN':j['startup_NN'],'elapsed_ms':j['elapsed_ms'],'source_git':load(A/'runs'/(j['run']+'.started.json')).get('git_commit'),'outer_exit':j['process']['exit'],'stop_reason':j['process']['stop_reason'],'outer_remaining':j['process']['remaining'],'unknown_adopted':j['process']['unknown_adopted'],'monitor_state':j['control']['monitor_state'],'primary':j['control']['primary'],'control_failure':j['control']['control'],'init':{e:{'ORT_init_ms':v['info']['init_ms'],'startup_wall_ms':v['startup']['wall_ms'],'startup_API_ms':v['startup']['API_ms'],'provider':v['info']['providers'],'ORT_version':v['info']['version']} for e,v in j['init'].items()}} for j in jobs]
(D/'results.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({k:out[k] for k in ['cost_seconds','heavy_total_s','game_total_s','game_per_s_game_section','game_per_s_quality_job','peak_own_group_plus_guardian_RSS','formal_ready']}));print(json.dumps(out['StageB']['WDL_terminal']));print(json.dumps(out['StageB']['operational']))
