"""NN0 train-only, game-equal population moments; no model/label load."""
from pathlib import Path
import datetime,hashlib,json,math,struct,sys,ast
R=Path.cwd();D=R/'research-data/ai-sigma/frame15-input-scale-control';T=R/'tools/ai-sigma-input-scale-control';sys.path.insert(0,str(R/'tools/nnue-training'))
from frame14_data import read_rows,canonical_model_input,bound_path
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();f32=lambda x:struct.unpack('<f',struct.pack('<f',x))[0]
stage=R/'research-data/ai-sigma/frame14-learning/stages/train96.stage.json';m=json.loads(stage.read_text());meta=read_rows(bound_path(m,'metadata'));train=[r for r in meta if r['split']=='train' and r['group']in m['train_groups']];groups={}
for r in train:groups.setdefault(r['group'],[]).append([struct.unpack('<f',struct.pack('<I',b))[0]for b in canonical_model_input(r)[3]])
assert len(train)==4653 and len(groups)==96
mu64=[math.fsum(math.fsum(x[c]for x in g)/len(g)for g in groups.values())/96 for c in range(2)]
var64=[math.fsum(math.fsum((x[c]-mu64[c])**2 for x in g)/len(g)for g in groups.values())/96 for c in range(2)]
mu=[f32(x)for x in mu64];sigma=[f32(math.sqrt(v))if v>0 else 1.0 for v in var64];assert all(math.isfinite(x)for x in mu+sigma)and all(x>0 for x in sigma)
scale={'version':'train96-gameequal-population-f32-v1','train_rows':4653,'train_games':96,'mu64':mu64,'population_var64':var64,'mu_f32':mu,'sigma_f32':sigma,'mu_bits':[struct.unpack('<I',struct.pack('<f',x))[0]for x in mu],'sigma_bits':[struct.unpack('<I',struct.pack('<f',x))[0]for x in sigma],'rule':'mu=mean_game(mean_row(d)); var=mean_game(mean_row((d-mu64)^2)); sigma=f32(sqrt(var)); actual mu=f32(mu64), z=(d-mu)/sigma in Torch f32','zero_variance':'sigma1; typed zero_variance_columns retained','zero_variance_columns':[i for i,v in enumerate(var64)if v==0],'STM_order':'shared canonical_model_input, no second rotation','labels_used':False,'test_excluded_before_moments':True,'stage_SHA':sha(stage),'metadata_SHA':m['metadata_sha256']};(D/'scale.json').write_text(json.dumps(scale,indent=2)+'\n')
base=R/'research-data/ai-sigma/frame15-learning-diagnostic';cfg=json.loads((base/'configs/lr1e-4.json').read_text());(D/'config.json').write_text(json.dumps(cfg,indent=2)+'\n')
reg209=json.loads((base/'preregister.json').read_text());sources={p:sha(R/p)for p in reg209['sources']};assert all(sources[k]==v for k,v in reg209['sources'].items())
initial=R/'models/experiments/nnue/frame15-learning-diagnostic-lr1e-4-r1/initial.pt';assert initial.is_file()
reg={'issue':'quoridor-4lc.211','UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'run_id':'frame15-input-scale-control-r1','stage_path':str(stage),'stage_SHA':sha(stage),'mask_SHA':m['mask_sha256'],'raw_initial_path':str(initial),'raw_initial_checkpoint_SHA':sha(initial),'raw_initial_tensor_SHA':reg209['initial_tensor_SHA'],'scale_SHA':sha(D/'scale.json'),'sources':sources,'private_sources':{str(p.relative_to(R)):sha(p)for p in T.glob('*.py')},'points':reg209['points'],'primary_step':200,'primary_baseline':.659847319505419,'distance_baseline':.48514681311997876,'constant_baseline':.6787804677332444,'parity_maxabs':1e-6,'parity_extra_raw_samples':5901,'trainer_samples':110210,'total_planned_samples':116111,'sample_cap':200000,'heavy_cap_s':180,'hard_job_s':120,'warm':0,'GPU':0,'newscience':'2026-10-04T05:05:00Z','science_stop':'2026-10-04T05:15:00Z','validation_reused_single_seed':True,'same_batch_order_400_SHA':'83eb87b84b93624cd96ff7fac2b860f8fe38af2b5015a86462377a06ffd17771','testlabels_read':False,'teacher_test_game_created':0,'initial_function_not_tensor_equal':True};(D/'preregister.json').write_text(json.dumps(reg,indent=2)+'\n');print(json.dumps({'NN':0,'mu_f32':mu,'sigma_f32':sigma,'planned_samples':116111,'test_beforemoments_excluded':True}))
