'use strict';const fs=require('fs'),path=require('path'),crypto=require('crypto'),CP=require('child_process'),{createRequire}=require('module'),{OwnedProcesses,boundedStop}=require('./cleanup.cjs'),{now}=require('./caller.cjs');const {preserveAndClean,detail}=require('./error-boundary.cjs');const ROOT=path.resolve(__dirname,'../..'),BASE=ROOT+'/.artifacts/ai-sigma/continuation-20261001/SIGMA-STREAMING-RUNTIME-FINAL',FIX=ROOT+'/.artifacts/ai-sigma/reference/SIGMA-WEB-REFERENCE';const{chromium}=createRequire('/workspaces/quoridor/package.json')('playwright');
function clock(samples){let lo=-Infinity,hi=Infinity;for(const x of samples){lo=Math.max(lo,x.remote-x.end-.1);hi=Math.min(hi,x.remote-x.start+.1);}if(lo>hi)throw Error('CLOCK_DISJOINT');return {lo_ms:lo,hi_ms:hi,offset_ms:(lo+hi)/2,error_ms:(hi-lo)/2+.1,samples};}
async function open(out,onSnapshot,onStopped){fs.mkdirSync(out,{recursive:true});const failureSave=(n,x)=>fs.writeFileSync(out+'/'+n+'.json',JSON.stringify(x)+'\n');let stage='browser-launch';const owner=new OwnedProcesses({tracePath:out+'/cleanup.jsonl'}),original=CP.spawn;CP.spawn=(...a)=>owner.observeChild(original(...a));let browser;try{browser=await chromium.launch({headless:true,executablePath:'/workspaces/quoridor/artifacts/playwright/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--disable-software-rasterizer','--use-gl=disabled','--renderer-process-limit=1']});}catch(e){await preserveAndClean(failureSave,stage,e,()=>boundedStop({owner,stop:async()=>({remaining_pids:0})}));}finally{CP.spawn=original;}
 const save=(name,v)=>fs.writeFileSync(out+'/'+name+'.json',JSON.stringify(v,null,2)+'\n');let page;const backend={owner,save,stop:async()=>{try{if(page)save('terminated-worker',await page.evaluate(()=>terminateEarly()));}finally{await browser.close();}return{remaining_pids:0}}};
 try{stage='routes-page-start';const routes={'/game.js':__dirname+'/game.js','/context.js':__dirname+'/context.js','/early-page.js':__dirname+'/early-page.js','/early-worker.js':__dirname+'/early-worker.js','/reference-core.js':__dirname+'/reference-core.js','/reference-control-run.js':__dirname+'/reference-control-run.js','/candidate-host.js':__dirname+'/host.js','/checkpoint.js':__dirname+'/checkpoint.js','/b.wasm':ROOT+'/.artifacts/ai-sigma/runs/SIGMA-ORT-SEARCH/final.wasm','/model.onnx':ROOT+'/models/experiments/ai-sigma/reference/sigma-pcr250/best.onnx','/ort/ort.min.js':FIX+'/ort.min.js','/ort/ort-wasm-simd-threaded.jsep.mjs':FIX+'/ort-wasm-simd-threaded.jsep.wasm'.replace('.wasm','.mjs'),'/ort/ort-wasm-simd-threaded.jsep.wasm':FIX+'/ort-wasm-simd-threaded.jsep.wasm'};
 const ctx=await browser.newContext(),network=[];await ctx.route('**/*',async r=>{const u=new URL(r.request().url());network.push(u.href);if(u.origin!=='http://localhost:5194')return r.abort();if(u.pathname==='/')return r.fulfill({contentType:'text/html',body:'<!doctype html><script src="/early-page.js"></script>'});const p=routes[u.pathname];if(!p)return r.abort();try{return await r.fulfill({contentType:u.pathname.endsWith('.wasm')?'application/wasm':/\.m?js$/.test(u.pathname)?'text/javascript':'application/octet-stream',body:fs.readFileSync(p)});}catch(e){save('HTTP-route-failure-'+Date.now(),detail(e,'route',{pathname:u.pathname,source:p}));throw e;}});
 page=await ctx.newPage();backend.page=page;await page.exposeBinding('publishCompleted',(source,m)=>{if(source.frame!==page.mainFrame())throw Error('FOREIGN_BINDING_FRAME');return onSnapshot(m);});await page.exposeBinding('publishStopped',(source,m)=>{if(source.frame!==page.mainFrame())throw Error('FOREIGN_BINDING_FRAME');return onStopped(m);});page.on('pageerror',e=>save('page-error',detail(e,'pageerror')));page.on('requestfailed',r=>save('HTTP-request-failure-'+Date.now(),{url:r.url(),failure:r.failure()}));await page.goto('http://localhost:5194/');await page.evaluate(()=>setupEarly());
 backend.reclock=async label=>{const p=[],w=[];for(let i=0;i<12;i++){let start=now(),remote=await page.evaluate(()=>performance.timeOrigin+performance.now());p.push({start,end:now(),remote});start=now();const r=await page.evaluate(()=>pingEarly());w.push({start,end:now(),remote:r.at_ms});}const c={page:clock(p),worker:clock(w)};save('clock-'+label,c);return c;};stage='startup-clock';backend.clock=await backend.reclock('start');backend.loadState={ready:false,attempted:false};backend.load=async()=>{backend.loadState.attempted=true;const t=now(),r=await page.evaluate(()=>loadEarly());save('model-load',{...r,wall_ms:now()-t,model_ready_outside_first_input_only:true});backend.loadState={...r,ready:r.kind==='ready',attempted:true};if(r.kind!=='ready'||r.threads!==1||r.proxy!==false||r.handles||r.activeNN){const e=Error(r.error??'MODEL_LOAD');e.source_error=r.error_detail??null;e.code=r.kind;throw e;}return r;};save('browser-startup',{version:browser.version(),network,CPU:[2],NN_loaded:false,real_port_bound:false});return backend;
 }catch(e){await preserveAndClean(save,stage,e,()=>boundedStop(backend),{model_state:backend.loadState??null});}}
module.exports={open,ROOT,BASE};
