// Derived from frozen continuation match-entry; real backend deliberately unconnected.
'use strict';const fs=require('fs'),path=require('path'),crypto=require('crypto'),G=require('./game-loop.cjs'),J=require('./judge.cjs'),{freeze}=require('./early-cache.cjs');
const ROOT=path.resolve(__dirname,'../..'),BASE=ROOT+'/.artifacts/ai-sigma/continuation-20261001/SIGMA-STREAMING-RUNTIME-FINAL',MOCK=Symbol('programmatic-diagnostic-only'),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b),clone=x=>JSON.parse(JSON.stringify(x)),now=()=>Number(process.hrtime.bigint())/1e6;
function compact(x){if(Array.isArray(x))return x.map(compact);if(x&&typeof x==='object'){const q={};for(const[k,v]of Object.entries(x)){if(['prefix','legal_prefix','history','tree','public_json','echo','identity'].includes(k)){if(v!=null)q[k+'_sha256']=J.hash(v);}else q[k]=compact(v);}return q;}return x;}
function readPlan(){return {prereg:JSON.parse(fs.readFileSync(BASE+'/preregister.json')),sha256:sha(BASE+'/preregister.json')}}
function schedule(p){if(p.issue!=='quoridor-4lc.67'||p.m!==48||p.total_games!==96||p.pairs.length!==48||p.T_ms!==500||p.search_seed!==1979||!eq(p.clock,{...p.clock,T_ms:500,reserve_ms:89,commit_margin_ms:9,commit_cutoff_ms:402,seal_ms:411}))throw Error('FIXED_PLAN_REQUIRED');const seen=new Set();return p.pairs.map((b,i)=>{if(b.pair!==i+1||b.platform!=='browser'||seen.has(b.pool_index)||p.old_executed_excluded_indices.includes(b.pool_index)||!eq([...b.candidate_color_order].sort(),[1,2])||J.hash(b.legal_prefix)!==b.prefix_sha256||J.hash(b.context)!==b.context_sha256||!eq(J.context(J.state(b.legal_prefix)),b.context)||!eq(J.ids(b.legal_prefix),b.rust_prefix))throw Error('PAIR_IDENTITY');seen.add(b.pool_index);b.games.forEach((g,j)=>{if(g.game!==2*i+j+1||g.candidate_color!==b.candidate_color_order[j]||g.reference_color!==3-g.candidate_color||g.seed!==1979)throw Error('GAME_NUMBER')});return {...b,prefix:b.legal_prefix}})}
function verifyToken(t,purpose){if(!t||t.purpose!==purpose||t.issue!=='quoridor-4lc.70'||t.goal!=='quoridor-4lc'||!t.freeze_token||t.freeze_token!==process.env.SIGMA70_DIAGNOSTIC_TOKEN||!/^[a-zA-Z0-9_-]+$/.test(t.run_id??''))throw Error('EXPLICIT_PURPOSE_TOKEN_REQUIRED');const plan=readPlan(),m=JSON.parse(fs.readFileSync(BASE+'/entry-manifest.json'));if(t.preregister_sha256!==plan.sha256||t.entry_manifest_sha256!==sha(BASE+'/entry-manifest.json'))throw Error('FREEZE_HASH_MISMATCH');for(const c of m.checks)if(sha(c.path)!==c.sha256)throw Error('INPUT_MUTATED');if(purpose==='actual')throw Error('ACTUAL_GO_FALSE_NEW_FREEZE_REQUIRED');if(!['mock','golden'].includes(purpose)||t.actual_go!==false||m.actual_go!==false)throw Error('DIAGNOSTIC_ONLY');if(purpose==='golden'){const gate=JSON.parse(fs.readFileSync(BASE+'/phaseA-gates.json'));if(!gate.all_passed||t.phaseA_sha256!==sha(BASE+'/phaseA-gates.json'))throw Error('PHASE_A_GATE_REQUIRED');} return plan}
function score(table,p){const Xi=p.pairs.filter(b=>b.games.every(g=>table[g.game-1].status==='completed')).map(b=>b.games.reduce((n,g)=>n+table[g.game-1].result.score,0)/2),mean=Xi.length?Xi.reduce((a,b)=>a+b,0)/Xi.length:null;return {planned_m:48,completed_pairs:Xi.length,complete:Xi.length===48,Xi,mean,L:Xi.length===48?Math.max(0,mean-Math.sqrt(Math.log(20)/96)):null,formal_NI:false,old_results_pooled:false,W:table.filter(x=>x.status==='completed'&&x.result.score===1).length,D:table.filter(x=>x.status==='completed'&&x.result.score===.5).length,loss:table.filter(x=>x.status==='completed'&&x.result.score===0).length}}
function bounded(p,ms,clock,label){let timer;return new Promise(resolve=>{let done=false;const finish=x=>{if(done)return;done=true;clock.clear(timer);resolve(x)};timer=clock.delay(Math.max(0,ms),()=>finish({bounded_error:label}));Promise.resolve(p).then(x=>finish({value:x}),e=>finish({bounded_error:e.message}))})}
async function execute(o){require('./budget.cjs').gate(o.forecast??{profile_temp:50331648,trace_log:16777216,public_private_raw_clock:16777216,ending:6291456});if(o.key!==MOCK)throw Error('EXECUTE_DIAGNOSTIC_FACTORY_ONLY');const {prereg:p,out,createBackend,clock,control={}}=o;fs.mkdirSync(out,{recursive:false});const blocks=schedule(p),table=blocks.flatMap(b=>b.games.map(g=>({...g,pair:b.pair,pool_index:b.pool_index,status:'scheduled',attempts:[]}))),events=[],attempts=[];let backend=null,retries=0,sessions=0,generation=0,previousStamp=null,lastStop=null,stopReason='all_complete',signal=false,cleanupFailed=false;const save=(n,x)=>fs.writeFileSync(out+'/'+n+'.json',JSON.stringify(compact(x))+'\n'),guard=()=>{if(signal||control.signal)throw Error('SIGNAL');if(control.pause?.())throw Error('PAUSED');if(clock.wall()>=o.deadline)throw Error('GLOBAL_DEADLINE')};
const signalFn=()=>{signal=true};process.once('SIGINT',signalFn);process.once('SIGTERM',signalFn);
const zero=x=>x&&((x.activeNN===0&&x.handles===0&&x.live_searches===0)||x.controlledPID0===true);
const cleanup=async()=>{if(!backend)return;const b=backend;backend=null;const r=await bounded(b.stop(),b.cleanupBudgetMs??100,clock,'CLEANUP_PENDING_FRESH_FORBIDDEN');events.push({kind:'cleanup',...r});if(r.bounded_error||!zero(r.value)){cleanupFailed=true;throw Error('CLEANUP_PENDING_FRESH_FORBIDDEN')}};
const start=async()=>{await cleanup();guard();backend=await createBackend({session:++sessions,clock});if(!backend.startup?.ready)throw Error('BACKEND_READY_REQUIRED');events.push({kind:'startup',session:sessions,wall:clock.wall()})};
const choose=async(engine,input,meta)=>{const t0=previousStamp??clock.now();guard();if(meta?.fresh){await cleanup();lastStop=null;await start();}if(lastStop){const proof=await bounded(lastStop,backend.stopAckBudgetMs??100,clock,'OLD_WORK_NOT_ZERO_FRESH_FORBIDDEN');if(proof.bounded_error||!zero(proof.value))throw Error('OLD_WORK_NOT_ZERO_FRESH_FORBIDDEN')}guard();const s=J.state(input.legal_prefix),ctx=J.context(s),id={engine,request_id:o.runId+'-'+(++generation),generation,epoch:generation,fixture_id:input.id,fixture:null,legal_prefix:clone(input.legal_prefix),prefix:J.ids(input.legal_prefix),key:ctx.key,history:ctx.history,model:p.model.sha256,schema:'8x9x9-f32/136logits/value1/rust209',limits:{simulations:engine==='reference'?100000:4096,max_nodes:engine==='reference'?null:512,max_depth:engine==='reference'?null:24,seed:1979},t0_ms:t0,deadline_ms:t0+500,seal_ms:t0+411,commit_cutoff_ms:t0+402,request_token:o.runId+'-'+generation};freeze(id);
const context=backend.create({identity:id,meta});let r;if(clock.now()>=id.deadline_ms)r={accepted:false,checkpoint:false,error:'LATE_RESPONSE',local_timeout:true};else{const res=await bounded(backend.submit(context),id.deadline_ms-clock.now(),clock,'NO_RESPONSE_TIMEOUT');r=res.bounded_error?{accepted:false,checkpoint:false,error:res.bounded_error,local_timeout:true}:res.value}
const response=require('./final-envelope.cjs').finalize(r,id,clock,control);previousStamp=response.stamp_ms;lastStop=backend.finish(context);events.push({kind:'public',identity:id,response,mock:backend.startup.mock===true});if(control.afterPublic)control.afterPublic({meta,events,context,response});return response};
try{save('checkpoint',{table,attempts,retries,partial:true});await start();if(o.diagnosticRequests){for(const d of o.diagnosticRequests){if(o.diagnosticFaultGames){const turn=J.state(d.legal_prefix).getCurrentPlayer(),candidateColor=d.engine==='reference'?3-turn:turn;const result=await G.runGame({prefix:d.legal_prefix,candidateColor,platform:'browser',clock:clock.now,maxAddedPly:1,choose:(engine,input)=>choose(engine,input,d)});events.push({kind:'fault_game',id:d.id,result});}else{const response=await choose(d.engine,{id:d.id,legal_prefix:d.legal_prefix},d);const classification=G.classifyFailure(response);events.push({kind:'classified',id:d.id,response,classification});}}if(o.diagnosticFourPly){const result=await G.runGame({prefix:[],candidateColor:1,platform:'browser',clock:clock.now,maxAddedPly:4,choose:(engine,input)=>choose(engine,input,{diagnostic:true})});events.push({kind:'four_ply',result});}}else for(const b of blocks){guard();let pairDone=false;for(let attempt=0;attempt<2;attempt++){const at={pair:b.pair,attempt,prefix_sha256:b.prefix_sha256,seed:1979,games:[],valid:false};attempts.push(at);let invalid=false,incomplete=false;for(const g of b.games){guard();const result=await G.runGame({prefix:clone(b.prefix),candidateColor:g.candidate_color,platform:'browser',clock:clock.now,choose:(engine,input)=>choose(engine,input,{pair:b.pair,game:g.game,attempt,candidateColor:g.candidate_color})});const row=table[g.game-1];row.attempts.push({attempt,result});row.status=result.kind==='invalid_pair'?'invalid':result.complete?'completed':'incomplete';row.result=result;at.games.push({game:g.game,result});save('checkpoint',{table,attempts,retries,partial:true});if(result.kind==='invalid_pair'){invalid=true;break}if(!result.complete){incomplete=true;break}}
if(!invalid&&!incomplete&&at.games.length===2){at.valid=true;pairDone=true;break}if(invalid&&attempt===0&&retries<2){retries++;for(const g of b.games){table[g.game-1].status='scheduled_retry';delete table[g.game-1].result}await cleanup();lastStop=null;await start();continue}stopReason=invalid?'retry_exhausted':'incomplete_game';break}if(!pairDone)break}}
catch(e){stopReason=e.message;events.push({kind:'entry_error',error:e.message})}finally{try{await cleanup()}catch(e){stopReason+=';'+e.message}process.removeListener('SIGINT',signalFn);process.removeListener('SIGTERM',signalFn)}const result={runId:o.runId,dry:true,actual_go:false,table,attempts,retries,sessions,stopReason,cleanupFailed,score:score(table,p),events,NN:o.realDiagnostic?'recorded in session raw':0,browser:o.realDiagnostic?'recorded in session raw':0,actual_games:0,holdout_sends:0};save('checkpoint',{table,attempts,retries,partial:!result.score.complete});save('summary',result);return compact(result)}
async function mainInternal(purpose,options={}){const argv=options.argv??process.argv.slice(2);if(argv[0]!== (purpose==='actual'?'--run':'--diagnostic')||!argv[1])throw Error('EXPLICIT_TOKEN_FILE_REQUIRED');const token=JSON.parse(fs.readFileSync(argv[1])),plan=verifyToken(token,purpose),out=BASE+'/diag-'+token.run_id;if(fs.existsSync(out))throw Error('RUN_ALREADY_EXISTS');if(!['mock','golden'].includes(purpose)||options.key!==MOCK||typeof options.createBackend!=='function')throw Error('NO_FACTORY_IN_ACTUAL_CLI');return execute({...options,prereg:plan.prereg,out,runId:token.run_id,key:MOCK})}
const diagnosticGoldenMain=o=>mainInternal('golden',{...o,key:MOCK});
const diagnosticMockMain=o=>mainInternal('mock',{...o,key:MOCK});module.exports={schedule,readPlan,verifyToken,score,diagnosticMockMain,diagnosticGoldenMain};if(require.main===module){const a=process.argv.slice(2);const run=a[0]==='--diagnostic'?require('./golden-driver.cjs').run(a):mainInternal('actual');run.catch(e=>{console.error(e.stack);process.exitCode=1});}
