'use strict';
const fs=require('fs'),assert=require('assert'),{ROOT,A,D,now,save}=require('./common.cjs'),{Engine}=require('./controller.cjs'),{createReference}=require('../ai-sigma-native-baseline/reference.cjs'),{commitCP}=require('../ai-sigma-native-baseline/clock.cjs');
const core=Number(process.argv[2]),out=process.argv[3],{r}=createReference(),sleep=ms=>new Promise(z=>setTimeout(z,Math.max(0,ms))),engines={},init={},closed={};let generation=0,usedNN=0,active=false,aborted=false,priorZero=null;
fs.mkdirSync(out,{recursive:true});const write=(name,x)=>fs.appendFileSync(out+'/'+name,JSON.stringify(x)+'\n');
async function start(mock){for(const name of ['candidate','reference']){engines[name]=new Engine(name,core);init[name]=await engines[name].init(mock);if(!mock){const i=init[name].info;assert.equal(i.version,'1.30.0');assert.deepStrictEqual(i.providers,['CPUExecutionProvider']);assert.equal(i.intra,1);assert.equal(i.inter,1);assert.equal(i.sequential,true);assert.deepStrictEqual(i.affinity,[core]);}}save(out+'/init.json',{core,init,UTC:new Date().toISOString()});return{core,init};}
async function turn(state,prefix,engine,fixture_id,mock){
 const preparation=now(),legalObjects=state.getLegalActions(),legal=Array.from(legalObjects,a=>r.rustAction(state,a)),preparationMs=now()-preparation,gen=++generation,e=engines[engine],slot={cache:null};let finalized=false,seen=0,accepted=0,late=0,schema=0,first=null,outData=null,error=null,receiveResult=null;
 if(aborted)throw Error('BLOCK_ABORT');if(e.pending.size||Object.values(engines).some(e=>e.pending.size))throw Error('PREVIOUS_NOT_ZERO');
 const t0=now();const work=e.request({op:'search',fixture_id,legal_prefix:prefix,generation:gen,K:mock?8:1000000,NN_limit:Math.max(0,666666-usedNN),trace:false,watchdog_ms:10000,...(mock?{mock:{delay_ms:2,value:.25}}:{})},(x,receive)=>{seen++;if(first===null)first=receive-t0;const cp=x.cp;let v;if(!Number.isFinite(cp.root_mean)||!Number.isFinite(cp.root_valueSum)||!Number.isInteger(cp.nn_calls)||cp.nn_calls<1||!Array.isArray(cp.root_edges))v={accepted:false,code:'ILLEGAL_OR_SCHEMA'};else v=commitCP({slot,cp,receive,t0,cutoff:402,generation:gen,legal,finalized,clock:now});if(v.accepted)accepted++;else if(['LATE_CP','AFTER_PUBLIC'].includes(v.code))late++;else schema++;}).then(x=>{receiveResult=x.controller_receive_ms;outData=x.data;if(outData?.primary)error=outData.primary.message},e=>{error=e.message});
 await sleep(t0+402-now());const cut=now()-t0;e.stopCurrent();await sleep(t0+411-now());const pub=now();finalized=true;const cp=pub-t0<=500?slot.cache:null;await work;const zero=now();usedNN+=outData?.NN_calls??0;
 const row={core,engine,generation:gen,player:state.getCurrentPlayer(),ply:state.depth,key:state._positionKey(),history_count:state.position_history.get(state._positionKey()),controller_t0_ms:t0,previous_zero_to_t0_ms:priorZero===null?null:t0-priorZero,common_legal_preparation_ms:preparationMs,firstCP_ms:first,cut_actual_ms:cut,public_actual_ms:pub-t0,public_cp:cp?{action:cp.cp.action,generation:cp.cp.generation,simulations:cp.cp.simulations,root_visits:cp.cp.root_visits,root_mean:cp.cp.root_mean,root_valueSum:cp.cp.root_valueSum,nn_calls:cp.cp.nn_calls,receive_ms:cp.receive_ms,admit_ms:cp.admit_ms}:null,CP_received:seen,CP_admitted:accepted,CP_late_discarded:late,CP_schema_rejected:schema,result_IPC_receipt_ms:receiveResult===null?null:receiveResult-t0,quiescent_gate_observed_ms:zero-t0,cleanup_after_public_ms:zero-pub,NN_calls:outData?.NN_calls??null,NN_returned:outData?.spans?.length??null,NN_discarded:outData?.discardedNN??null,completed_K:outData?.completed??null,terminal_noNN:outData?.terminal_noNN??null,zero:outData?.zero??null,error,API_first_ms:outData?.spans?.[0]?.API_ms??null,API_total_ms:outData?.spans?.reduce((s,x)=>s+x.API_ms,0)??null,pipe_total_ms:outData?.spans?.reduce((s,x)=>s+x.pipe_ms,0)??null,used_arena_NN:usedNN};
 row.status=outData&&row.NN_calls!==row.NN_returned?'NN_RETURN_UNKNOWN':schema?'CP_SCHEMA_UNKNOWN':error==='NN_BUDGET'?'NN_BUDGET':error?'ENGINE_FAULT':!cp?'CLOCK_OR_FIRSTNONE':!(outData?.zero?.activeNN===0&&outData.zero.handles===0&&!outData.zero.active&&e.pending.size===0)?'QUIESCENCE_UNKNOWN':'COMPLETE';priorZero=zero;
 return{row,cp,legalObjects,legal,firstNN:outData?.first_NN,rootState:outData?.root_state};
}
async function game(spec,opening,mock=false){
 const gameStart=now();let state=r.fromPrefix(opening.legal_prefix),prefix=structuredClone(opening.legal_prefix),result=null,initial=null,plies=0,requests=0;
 write('game-starts.jsonl',{...spec,UTC:new Date().toISOString(),monotonic_ms:gameStart});
 try{while(!result){if(aborted)throw Error('BLOCK_ABORT');const terminal=r.terminalResult(state);if(terminal){result={status:terminal.winner?'GOAL':state.depth>=200?'DRAW200':'DRAW_NOLEGAL',winner:terminal.winner,quality_score:terminal.winner?(terminal.winner===spec.candidate_player?1:0):.5,operational_score:terminal.winner?(terminal.winner===spec.candidate_player?1:0):.5};break;}
 const engine=state.getCurrentPlayer()===spec.candidate_player?'candidate':'reference',z=await turn(state,prefix,engine,opening.id,mock);requests++;
 z.row.game_id=spec.game_id;z.row.block=spec.block;z.row.pair=spec.pair;write('journal.jsonl',z.row);
 if(!initial&&(JSON.stringify(z.rootState)!==JSON.stringify(r.portState(state))||JSON.stringify(z.firstNN?.features_bits)!==JSON.stringify(r.portState(state).features_bits)||z.firstNN?.NN_bits?.length!==137)){z.row.status='ROOT_BITS_SCHEMA_UNKNOWN';aborted=true;}
 if(!initial)initial={side:state.getCurrentPlayer(),engine,key:state._positionKey(),legal_prefix:structuredClone(prefix),root_state:z.rootState,features648_bits:z.firstNN?.features_bits??null,NN137_bits:z.firstNN?.NN_bits??null,rootNN_leaf:z.firstNN?.value??null,rootmean:z.cp?.cp.root_mean??null,rootvisits:z.cp?.cp.root_edges??null,view:'side-to-move',teacher_budget:{nominal_ms:500,cut402:true,K:z.cp?.cp.simulations??null},holdout:true};
 if(z.row.status!=='COMPLETE'){const candidateFault=engine==='candidate'&&z.row.status==='ENGINE_FAULT';result={status:z.row.status,fault_engine:engine,error:z.row.error,winner:null,quality_score:null,operational_score:candidateFault?0:null};aborted=true;break;}
 const index=z.legal.indexOf(z.cp.cp.action);if(index<0){result={status:'ILLEGAL_PUBLIC',fault_engine:engine,winner:null,quality_score:null,operational_score:engine==='candidate'?0:null};aborted=true;break;}
 const prep=now(),action=z.legalObjects[index];prefix.push(action);state=state.next(action);plies++;write('common-cost.jsonl',{game_id:spec.game_id,generation:z.row.generation,advance_ms:now()-prep});
 if(mock&&requests===2){result={status:'NN0_MOCK_TRUNCATED',winner:null,quality_score:null,operational_score:null};break;}
 }}catch(e){result={status:'CONTROL_OR_INFRA_UNKNOWN',error:e.message,winner:null,quality_score:null,operational_score:null};aborted=true;}
 const x={...spec,...result,core,final_ply:state.depth,plies_played:plies,requests,elapsed_ms:now()-gameStart,legal_prefix:prefix,final_key:state._positionKey(),firstRoot:initial,used_arena_NN:usedNN};write('games.jsonl',x);return x;
}
async function block(q){if(active)throw Error('DOUBLE_BLOCK');active=true;const games=[];try{for(const spec of q.games){if(aborted)break;games.push(await game(spec,q.opening,q.mock));}}finally{active=false;}return{core,games,aborted,usedNN};}
async function close(){aborted=true;for(const [name,e]of Object.entries(engines)){e.stopCurrent();closed[name]=await e.close();}save(out+'/close.json',{core,closed,usedNN,all_zero:!active&&Object.values(engines).every(e=>!e.pending.size)});return{core,closed,usedNN};}
process.on('message',q=>{if(q.op==='abort'){aborted=true;for(const e of Object.values(engines))e.stopCurrent();return;}const fn=q.op==='init'?()=>start(q.mock):q.op==='block'?()=>block(q):q.op==='close'?close:null;if(!fn)return;void fn().then(x=>{process.send({id:q.id,data:x});if(q.op==='close')process.disconnect();}).catch(e=>{process.send({id:q.id,error:e.stack});});});
