'use strict';const fs=require('fs'),{spawn}=require('child_process'),{ROOT,A,D,now,save}=require('./common.cjs'),{createMonitor}=require('./pause-monitor.cjs');const c=JSON.parse(fs.readFileSync(process.argv[2])),inputs=JSON.parse(fs.readFileSync(D+(c.mock?'/mock-openings.json':'/openings-e2-seeds.json')));
class Arena{constructor(core){this.core=core;this.seq=0;this.pending=new Map();this.child=spawn('taskset',['-c',String(core),process.execPath,'--max-old-space-size=192',__dirname+'/arena.cjs',String(core),c.job_out+'/core'+core],{stdio:['ignore','inherit','inherit','ipc']});this.child.on('message',x=>{const p=this.pending.get(x.id);if(!p)return;this.pending.delete(x.id);x.error?p.reject(Error(x.error)):p.resolve(x.data);});this.exit=new Promise(resolve=>this.child.on('exit',(code,signal)=>{for(const p of this.pending.values())p.reject(Error('ARENA_EXIT '+code+' '+signal));this.pending.clear();resolve({code,signal});}));}ask(op,x={}){const id=++this.seq;return new Promise((resolve,reject)=>{this.pending.set(id,{resolve,reject});this.child.send({id,op,...x});});}abort(){if(this.child.connected)this.child.send({op:'abort'});}}
(async()=>{fs.mkdirSync(c.job_out,{recursive:true});const m=createMonitor({out:c.job_out,subjectIssue:c.issue,deadlineUTC:c.processing_deadline,windowEndUTC:'2026-10-03T08:15:21Z'}),arenas=[],blocks=[],closed=[];let primary=null,stop='CAPACITY',startup=0;const begin=now();
try{await m.start(()=>{for(const a of arenas)a.abort();});if(!c.mock){const p=JSON.parse(fs.readFileSync(D+'/preregister-e2.json'));if(!p.science_ready||p.statistics?.status!=='ADOPTED')throw Error('STATISTICS_NOT_ADOPTED');}
for(const core of c.mode.cores)arenas.push(new Arena(core));const init=await Promise.all(arenas.map(a=>a.ask('init',{mock:!!c.mock,NN_budget:c.NN_allocation?.[String(a.core)]??666666})));startup=init.reduce((s,x)=>s+Object.values(x.init).reduce((s,x)=>s+(x.startup?.count??0),0),0);save(c.job_out+'/init-all.json',init);
for(const b of inputs.blocks){m.check();if(c.mock&&b.block>1){stop='NN0_MOCK_DONE';break;}const elapsed=(now()-begin)/1000,remaining=3600-(c.prior_heavy_seconds??0)-elapsed,seconds=(Date.parse('2026-10-03T07:55:00Z')-Date.now())/1000;if(remaining<305||seconds<305){stop=remaining<305?'HEAVY_REMAINING':'SCIENCE_DEADLINE_HEADROOM';break;}
// No outcome-based admission: static resource/owner files are freshly read per block by the prelaunch helper.
const {execFileSync}=require('child_process');try{execFileSync('python3',[__dirname+'/block-ready.py',process.argv[2]],{stdio:'pipe',env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'}});}catch(e){stop='BLOCK_ADMISSION_UNKNOWN';primary={message:e.message,stderr:e.stderr?.toString()};break;}
const t=now();save(c.job_out+'/block-running.json',{block:b.block,start_UTC:new Date().toISOString(),deadline_unix:Date.now()/1000+300});fs.appendFileSync(c.job_out+'/block-starts.jsonl',JSON.stringify({block:b.block,planned:b.games,start_ms:t,UTC:new Date().toISOString()})+'\n');
let launched=b;if(!c.mock){const genStart=now();execFileSync(process.execPath,['--max-old-space-size=192',__dirname+'/generate-block.cjs',String(b.block),c.job_out],{stdio:'pipe',timeout:Math.max(1000,Math.floor(300000-(now()-t))),env:process.env});launched=JSON.parse(fs.readFileSync(c.job_out+'/block-inputs/block-'+b.block+'.json'));save(c.job_out+'/generation-cost-'+b.block+'.json',{block:b.block,wall_ms:now()-genStart});m.check();if(launched.pairs.some(p=>!p.generated||p.started_epoch1_reuse)){const unknown={block:b.block,elapsed_ms:now()-t,results:b.pairs.map(p=>({core:p.core,games:b.games.filter(g=>g.core===p.core).map(g=>({...g,status:'GENERATION_UNSETTLED_UNKNOWN',quality_score:null,operational_score:null})),aborted:false}))};blocks.push(unknown);fs.appendFileSync(c.job_out+'/blocks.jsonl',JSON.stringify(unknown)+'\n');save(c.job_out+'/block-running.json',{block:null,deadline_unix:null});stop='PLAN_GENERATION_UNSETTLED';break;}}
const tasks=arenas.map(a=>{const p=launched.pairs.find(p=>p.core===a.core),games=b.games.filter(g=>g.core===a.core);if(!p.generated)return Promise.resolve({core:a.core,games:games.map(g=>({...g,status:'GENERATION_MISSING',quality_score:null,operational_score:null})),aborted:false});return a.ask('block',{games,opening:p.opening,mock:!!c.mock});});const results=await Promise.all(tasks);const x={block:b.block,elapsed_ms:now()-t,results};blocks.push(x);fs.appendFileSync(c.job_out+'/blocks.jsonl',JSON.stringify(x)+'\n');save(c.job_out+'/block-running.json',{block:null,deadline_unix:null});
if(results.some(x=>x.aborted)){stop='CLOCK_ENGINE_OR_RECOVERY_UNKNOWN';break;}
if(!c.mock){const stats=require('./statistics.cjs').evaluate(blocks,JSON.parse(fs.readFileSync(D+'/preregister-e2.json')).statistics);save(c.job_out+'/inference-progress.json',stats);if(stats.stop){stop=stats.stop;break;}}
}
}catch(e){primary={message:e.message,stack:e.stack};stop='CONTROL_OR_INFRA_UNKNOWN';}
finally{for(const a of arenas){a.abort();try{closed.push({...await a.ask('close'),exit:await a.exit});}catch(e){closed.push({core:a.core,error:e.message});}}await m.stop();if(m.state!=='READY')primary={...(primary??{}),late_monitor:m.state};}
const result={issue:c.issue,run:c.run_id,blocks_completed:blocks.length,blocks,stop,primary,closed,startup_NN:startup,elapsed_ms:now()-begin,monitor_state:m.state,kernelCPU_exact:false};save(c.job_out+'/result.json',result);console.log(JSON.stringify({stop,blocks:blocks.length,startup_NN:startup,primary}));if(primary)process.exitCode=1;
})().catch(e=>{console.error(e.stack);process.exitCode=1});
