'use strict';//241 saved legal replay, no NN/model imports.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),argv=process.argv.slice(2),get=k=>argv[argv.indexOf(k)+1];if(get('--task')!=='frame19-leaf-replay-241-v1')throw Error('task');const P=path.resolve('research-data/ai-sigma/frame19-leaf-terminal'),read=n=>JSON.parse(fs.readFileSync(path.join(P,n),'utf8')),assert=(b,m)=>{if(!b)throw Error(m)},sign=x=>JSON.stringify(x),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');const inp=JSON.parse(fs.readFileSync(get('--input-manifest'),'utf8'));for(const[p,h]of Object.entries(inp.SHA))assert(hash(p)===h,'hash '+p);
const {r}=require(path.resolve('tools/ai-sigma-native-baseline/reference.cjs')).createReference(),history=s=>JSON.stringify([s._positionKey(),s.getCurrentPlayer(),[...s.position_history].sort(([a],[b])=>a<b?-1:a>b?1:0)]),manifest=read('openings4-v1.json'),opens=new Map();
for(const o of manifest.openings){const s=r.fromPrefix(o.prefix);assert(!r.terminalResult(s)&&s._positionKey()===o.key&&history(s)===o.history&&s.depth===o.opening_ply,'opening');opens.set(o.id,o)}
const allhands=['optional4-r1-hands.jsonl','remaining3-r1-hands.jsonl'].flatMap(n=>fs.readFileSync(path.join(P,n),'utf8').trim().split('\n').filter(Boolean).map(JSON.parse)),by=new Map();for(const h of allhands){if(!by.has(h.slot))by.set(h.slot,[]);by.get(h.slot).push(h)}const remaining=read('remaining3-r1.json'),censored=read('optional4-r1-censored-ledger.json');let total=0,p2=0;const slots=[];
for(const planned of manifest.slots){const g=planned.slot===1?censored.ledger.find(x=>x.slot===1):remaining.ledger.find(x=>x.slot===planned.slot),o=opens.get(planned.opening);let s=r.fromPrefix(o.prefix),prefix=[...o.prefix],adopted=0;
 for(const h of by.get(planned.slot)||[]){assert(!r.terminalResult(s)&&h.ply===s.depth&&h.side===s.getCurrentPlayer(),'ply/terminal');if(h.clock.status!=='RECEIVED')continue;const q=h.clock.response.search;assert(q.root_key===s._positionKey()&&q.root_history===history(s),'history/key');const legal=s.getLegalActions(),choices=legal.filter(a=>r.rustAction(s,a)===q.Action);assert(choices.length===1,'legal Action');assert(q.depths.filter(d=>d.status==='COMPLETED').every(d=>d.root_all_legal_count===legal.length),'root legal count');const a=choices[0];prefix.push(a);s=s.next(a);adopted++;total++;if(h.side===2)p2++}
 const term=r.terminalResult(s);if(planned.slot===1){assert(g.status==='UNKNOWN'&&adopted===19&&!term,'censor');assert((by.get(1)||[]).at(-1).ply===g.last_completed_received_ply,'last received ply')}else{assert(sign(prefix)===sign(g.prefix)&&s.depth===g.final_ply,'finalprefix');assert(g.status==='TERMINAL'&&term&&term.winner===g.winner,'winner');assert(g.result_NNUE===(term.winner===0?'D':term.winner===g.NNUE_side?'W':'L'),'WDL')}
 slots.push({slot:planned.slot,status:g.status,adopted,final_ply:s.depth,winner:term?term.winner:null,legal_prefix:true,history_bound:true})
}
const pr=read('exact-cases-preregister-v1.json'),exact=read('exact-cases-r1.json');const cases=[];
for(const [i,f]of pr.cases.entries()){const s=r.fromPrefix(f.before_prefix),h=history(s),hs=crypto.createHash('sha256').update(h).digest('hex');assert(s._positionKey()===f.before_position_key&&s.depth===f.ply&&s.getCurrentPlayer()===f.side&&hs===f.full_history_SHA_before,'case input');const legal=s.getLegalActions().map(a=>r.rustAction(s,a)).sort((a,b)=>a-b);for(const x of exact.results.filter(x=>x.caseIndex===i&&x.status==='COMPLETED'))assert(sign(x.values.map(z=>z.Action).sort((a,b)=>a-b))===sign(legal),'all rootchild legal set');cases.push({caseIndex:i,prefix_history_SHA_bound:true,legal_count:legal.length,source_Action_legal:legal.includes(f.Action)})}
for(const[p,h]of Object.entries(inp.SHA))assert(hash(p)===h,'changed '+p);const result={schema:'leaf-terminal-replay-v1',task:get('--task'),PASS:true,newNN:0,slots,adopted_total:total,P2_adopted:p2,cases,limits:['shared RuleA, not independent rule implementation','saved full-window value arithmetic; no re-evaluation of leaf or deep truth']};fs.writeFileSync(get('--out'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({PASS:true,slots:slots.length,adopted_total:total,P2_adopted:p2,cases:cases.length}));
