"""241 management-only scoped in-memory Git save, no scientific calculation."""
from pathlib import Path
import datetime,hashlib,json,subprocess,time
D=Path('research-data/ai-sigma/frame19-leaf-terminal-independent');R=Path('docs/reports/ai-sigma-critic-frame19-leaf-terminal.md');t=time.monotonic();sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();idx=Path(subprocess.check_output(['git','rev-parse','--git-path','index'],text=True).strip());before=sha(idx);assert before=='59880a1d93833b8a0ea250e9a2b1270c41ceb9f6666da9ab0edeb48991817072'
actual=sum(p.stat().st_size for p in D.iterdir()if p.is_file())+R.stat().st_size;allocated=sum(p.stat().st_blocks*512 for p in D.iterdir()if p.is_file())+R.stat().st_blocks*512;forecast=allocated+196608+32768+65536;assert forecast<524288 and forecast<786432
(D/'storage-final-admission.json').write_text(json.dumps({'UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'actual_file_bytes':actual,'allocated_bytes':allocated,'uniqueGit_forecast':196608,'temporary_forecast':32768,'metadata_forecast':65536,'forecast':forecast,'guard':786432,'forecast_guard':524288,'new_reserve':1048576,'existing_unused_before':49389568,'existing_unused_after':48340992,'old_critic_reserved_undiscounted':117420516,'oldunknown_discount0':True,'parentadd0':True},indent=2)+'\n')
s=Path('research-data/ai-sigma/frame16-raw-cv-independent/save.py').read_text().replace('research-data/ai-sigma/frame16-raw-cv-independent',str(D)).replace('docs/reports/ai-sigma-critic-raw-cv.md',str(R));ns={'__name__':'metadata_save'};exec(compile(s,'readonly-scoped-save-helper-inmemory','exec'),ns);cid,files=ns['commit']('critic241: finite leaf-terminal matched-work arithmetic and saved optional/case replay')
for p in files:assert subprocess.check_output(['git','show',cid+':'+str(p)])==p.read_bytes(),str(p)
assert sha(idx)==before;receipt={'commit':cid,'files':len(files),'byte_restore_PASS':True,'index_before':before,'index_after':sha(idx),'defaultindex_changed':False,'privateindex_used':False,'science_stop_SHA':sha(D/'science-stop.json'),'source_children_stopped':True,'management_wall_s':time.monotonic()-t};(D/'Git-byte-receipt.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
