import pathlib,subprocess,json,time,os
ROOT=pathlib.Path('/workspaces/quoridor/.worktree/ai-sigma');RUN=ROOT/'.artifacts/ai-sigma/runs/SIGMA-NN-SEARCH';bin=pathlib.Path('/home/vscode/.cache/inference/research/ai-sigma/nn-search/target/release/ai-sigma-nn-search');model=ROOT/'models/experiments/ai-sigma/reference/sigma-pcr250/best.onnx';fixtures=json.loads((ROOT/'.artifacts/ai-sigma/reference-fixtures/SIGMA-PARITY-PLAN/fixtures.json').read_text())['fixtures'];selected=[next(f for f in fixtures if f['id']==id)for id in ['initial-p1','asym-hv-p2','straight-jump-p2']]
p=subprocess.Popen([str(bin),'serve',str(model)],stdin=subprocess.PIPE,stdout=subprocess.PIPE,stderr=(RUN/('native-serve'+os.environ.get('NN_OUT_TAG','')+'.stderr.log')).open('w'),text=True);tag=os.environ.get('NN_OUT_TAG','');generation=0;rows=[]
try:
 ready=json.loads(p.stdout.readline());assert ready['ready'];(RUN/('native-clock-ready'+tag+'.json')).write_text(json.dumps({'pid':p.pid,**ready}))
 for f in selected:
  for T in [100,500,1000]:
   for sample in range(6):
    generation+=1;t0=time.monotonic()*1000;req={'kind':'request','fixture':f,'seed':1979,'simulations':4096,'max_nodes':512,'max_depth':24,'generation':generation,'clock_t0_ms':t0,'T_ms':T,'guard_ms':100};p.stdin.write(json.dumps(req)+'\n');p.stdin.flush();value=json.loads(p.stdout.readline());end=time.monotonic()*1000;accepted=value['ok']and value['data']['status']=='checkpoint'and end-t0<=T and value['data']['generation']==generation;rows.append({'id':f['id'],'T_ms':T,'sample':sample,'warmup':sample==0,'elapsed_ms':end-t0,'host_accepted':accepted,'payload':value,'host_t0':t0,'host_end':end})
 # During-NN host invalidation and owner generation update; replacement uses same immutable fixture.
 generation+=1;old=generation;t0=time.monotonic()*1000;req={'fixture':selected[0],'simulations':4096,'max_nodes':512,'max_depth':24,'generation':old,'clock_t0_ms':t0,'T_ms':1000,'guard_ms':100};p.stdin.write(json.dumps(req)+'\n');p.stdin.flush();time.sleep(.002);generation+=1;invalid_at=time.monotonic()*1000;p.stdin.write(json.dumps({'kind':'cancel','generation':generation})+'\n');p.stdin.flush();response=json.loads(p.stdout.readline());assert response.get('data',{}).get('generation',old)!=generation
 generation+=1;t1=time.monotonic()*1000;req.update(generation=generation,clock_t0_ms=t1,T_ms=500);p.stdin.write(json.dumps(req)+'\n');p.stdin.flush();new=json.loads(p.stdout.readline());(RUN/('native-cancellation'+tag+'.json')).write_text(json.dumps({'invalid_at_ms':invalid_at,'old_generation':old,'current_generation':generation,'old_rejected':True,'old_response':response,'new_response':new,'new_elapsed_ms':time.monotonic()*1000-t1},indent=2))
finally:p.stdin.close();p.wait(timeout=5)
(RUN/('native-clock-raw'+tag+'.json')).write_text(json.dumps(rows));print(json.dumps({'rows':len(rows),'server_exit':p.returncode}))
