const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict');const ROOT=path.resolve(__dirname,'../..'),RUN=path.join(ROOT,'.artifacts/ai-sigma/runs/SIGMA-NN-SEARCH');const sand={};vm.createContext(sand);vm.runInContext(fs.readFileSync(path.join(ROOT,'.artifacts/ai-sigma/runs/SIGMA-RULE-FEATURE-PARITY/reference-input/sources/docs/game.js'),'utf8')+'\nglobalThis.StateRef=State;',sand);const State=sand.StateRef,gold=JSON.parse(fs.readFileSync(path.join(ROOT,'.artifacts/ai-sigma/reference-fixtures/SIGMA-PARITY-PLAN/fixtures.json'))).fixtures,plain=v=>JSON.parse(JSON.stringify(v));
function rootState(f,n){const b=f.board,h=new Uint8Array(81),v=new Uint8Array(81);for(const a of b.rust_h_anchors){let x=a%8,y=Math.floor(a/8);h[y*9+x]=h[y*9+x+1]=1}for(const a of b.rust_v_anchors){let x=a%8,y=Math.floor(a/8);v[y*9+x]=v[(y+1)*9+x]=1}return new State({boardsize:9,depth:n.ply,player1pos:[b.rust_pawns[0]%9,Math.floor(b.rust_pawns[0]/9)],player2pos:[b.rust_pawns[1]%9,Math.floor(b.rust_pawns[1]/9)],walls_p1:b.walls_remaining[0],walls_p2:b.walls_remaining[1],walls_initial:10,hwalls:h,vwalls:v,hwall_anchors:new Set(b.rust_h_anchors.map(a=>`${a%8},${Math.floor(a/8)}`)),vwall_anchors:new Set(b.rust_v_anchors.map(a=>`${a%8},${Math.floor(a/8)}`)),position_history:new Map(n.history)})}
function toId(s,a){if(a.type==='pawn'){let[x,y]=s._pawnDest(a);return y*9+x}return(a.orientation==='h'?81:145)+a.y*8+a.x}
function legal(s){return s.isFinished()?[]:[...s.getLegalActions()].map(a=>toId(s,a)).sort((a,b)=>a-b)}
function term(s){const w=s.winner();return w?(w===s.getCurrentPlayer()?1:-1):s.isDrawn()?0:null}
function next(s,id){const a=[...s.getLegalActions()].find(a=>toId(s,a)===id);assert(a,'illegal edge');return s.next(a)}
const n=JSON.parse(fs.readFileSync(RUN+'/native-caps.json')),w=JSON.parse(fs.readFileSync(RUN+'/wasm-caps.json')).rows;assert.equal(n.length,27);assert.equal(w.length,27);const summary={};
for(const [platform,rows]of [['native',n],['wasm',w]]){let nodes=0,terminal=0,backup=0,patterns={},caps=0;for(const row of rows){const f=gold.find(f=>f.id===row.id),root=rootState(f,row.search.nodes[0]),table=new Map(row.search.nodes.map(n=>[n.index,n])),pending=[[0,root]];const cp=row.search.checkpoint;assert.equal(cp.policy_fallbacks,0);assert.equal(cp.value_fallbacks,0);if(term(root)!==null)assert.equal(cp.nn_calls,0);if(cp.cap)caps++;
while(pending.length){const[i,s]=pending.pop(),node=table.get(i);assert.equal(s._positionKey(),node.key);assert.deepEqual(plain([...s.position_history].sort()),[...node.history].sort());assert.deepEqual(legal(s),node.legal);assert.equal(term(s),node.terminal);if(term(s)!==null){terminal++;assert.equal(node.edges.length,0)}for(let j=0;j<node.children.length;j++)if(node.children[j]!==null)pending.push([node.children[j],next(s,node.edges[j][0])]);nodes++;}
for(const step of row.steps){let s=root;for(const edge of step.path)s=next(s,edge.action);const terminalValue=term(s),delta=step.result.nn_delta;let value;if(terminalValue!==null){assert.equal(delta,0);value=terminalValue}else{assert.equal(delta,1);value=platform==='native'?step.leaf_value:step.last_evaluation.value;const mask=platform==='native'?step.nn_evaluate_legal:step.last_evaluation.legal;assert.deepEqual(mask,legal(s));if(platform==='wasm')assert.equal(step.last_evaluation.board_key,s._positionKey())}assert(Number.isFinite(value)&&Math.abs(value)<=1);for(let j=0;j<step.path.length;j++){const e=step.path[j],expected=(step.path.length-j)%2?-value:value;assert(Math.abs(e.delta_value-expected)<=2e-6,'backup sign');backup++;}const pattern=step.path.map(e=>e.action<81?'pawn':'wall').join('/');patterns[pattern]=(patterns[pattern]||0)+1;}
}summary[platform]={nodes,terminal,backup_edges:backup,path_patterns:patterns,cap_flag_rows:caps,terminal_priority_and_effective_mask:true};}
let decisionDifferences=[];for(let i=0;i<n.length;i++){assert.equal(n[i].id,w[i].id);assert.deepEqual(n[i].config,w[i].config);for(const key of ['action','simulations','nodes','max_depth','cap','nn_calls','policy_fallbacks','value_fallbacks'])if(n[i].search.checkpoint[key]!==w[i].search.checkpoint[key])decisionDifferences.push({case:n[i].id,key,native:n[i].search.checkpoint[key],wasm:w[i].search.checkpoint[key]});assert.deepEqual(n[i].search.checkpoint.root_edges.map(e=>[e[0],e[2]]),w[i].search.checkpoint.root_edges.map(e=>[e[0],e[2]]));}summary.decisionDifferences=decisionDifferences;summary.arena_boundary_unverified=true;fs.writeFileSync(RUN+'/caps-summary.json',JSON.stringify(summary,null,2));console.log(JSON.stringify(summary));
