importScripts('/host.js');let host,ownerGeneration=0,active=false,queue=[];const epoch=()=>performance.timeOrigin+performance.now();const yieldTask=()=>new Promise(r=>setTimeout(r,0));
async function budget(req){let s,cp=null,steps=[],completed=0,nn=0,root_ms=0,overshoot=false;const g=req.generation,t0=req.clock_t0_ms,T=req.T_ms,guard=req.guard_ms;try{const st=epoch();s=host.create(req,false);root_ms=epoch()-st;
// terminal checkpoint is obtained only by explicitly terminal input detection below;
const terminal=!!req.terminal_diagnostic; // normal clock cases are nonterminal legal prefixes.
if(terminal)cp=host.checkpoint(s,g);else while(true){if(ownerGeneration!==g)throw Object.assign(Error('STALE_GENERATION'),{code:'STALE_GENERATION'});if(epoch()>=t0+T-guard)break;const a=epoch();const out=host.step(s,g);if(req.diagnostic_step_delay_ms){const until=epoch()+req.diagnostic_step_delay_ms;while(epoch()<until){}}const b=epoch();steps.push({start_ms:a,end_ms:b,step:out});completed=out.simulations;nn=out.nn_calls;if(ownerGeneration!==g)throw Error('STALE_GENERATION');if(b>t0+T){overshoot=true;break}const ft=epoch(),next=host.checkpoint(s,g),fe=epoch();steps.at(-1).finish_ms=fe-ft;if(fe<=t0+T)cp=next;else{overshoot=true;break}await yieldTask();if(ownerGeneration!==g)throw Object.assign(Error('STALE_GENERATION'),{code:'STALE_GENERATION'});if(out.done)break;}
let end=epoch();if(end>t0+T)cp=null;return {ok:true,data:{generation:g,status:cp?'checkpoint':'timeout',checkpoint:cp,t0_ms:t0,T_ms:T,guard_ms:guard,adapter_end_ms:end,elapsed_ms:end-t0,overshoot,steps,root_ms,nn_calls:nn,simulations_completed:completed}};
}catch(e){return {ok:false,error:{code:e.code||'SEARCH_ERROR',detail:e.message},result_discarded:true,diagnostics:{generation:g,steps,completed,nn,root_ms,discarded_at_ms:epoch()}}}finally{if(s)host.free(s)}}
async function run(req){active=true;const payload=await budget(req);const st=epoch(),serialized=JSON.stringify(payload),end=epoch();if(payload.ok&&end>req.clock_t0_ms+req.T_ms){payload.data.status='timeout';payload.data.checkpoint=null;payload.data.late_serialization=true;}postMessage({kind:'result',generation:req.generation,payload,serialization_ms:end-st,serialized_bytes:serialized.length,worker_delivery_send_ms:epoch()});active=false;if(queue.length){let next=queue.shift();void run(next)}}
async function parity(fixtures){const rows=[];for(const f of fixtures){const row=host.diagnose(f);row.search=[];await yieldTask();if(['initial-p1','asym-hv-p2','straight-jump-p2','repeat-before-third-return','goal-win-legal-replay','synthetic-total-ply-200','synthetic-no-legal-move-draw','synthetic-goal-at200'].includes(f.id)){for(const sims of [1,8,32]){const s=host.create({fixture:f,simulations:sims,generation:1},true);try{while(true){const r=host.step(s,1);await yieldTask();if(r.done)break}row.search.push(host.snapshot(s))}finally{host.free(s)}}}rows.push(row)}return{fixtures:rows,model_sha256:host.digest,no_NN_fallback:true}}
onmessage=async({data})=>{if(data.kind==='load'){host=await loadSearchHost();let s=host.create({prefix:[],simulations:1,generation:1});host.step(s,1);host.free(s);postMessage({kind:'ready',load_ms:host.load_ms,compile_ms:host.compile_ms,memory:host.e.memory.buffer.byteLength});}else if(data.kind==='parity'){const result=await parity(data.fixtures);postMessage({kind:'parity',result,memory:host.e.memory.buffer.byteLength});}else if(data.kind==='cancel'){ownerGeneration=data.generation;postMessage({kind:'cancel_ack',generation:ownerGeneration,at:epoch()});}else if(data.kind==='request'){ownerGeneration=data.request.generation;if(active)queue.push(data.request);else void run(data.request);}else if(data.kind==='faults'){postMessage({kind:'faults',result:host.faults()});}else if(data.kind==='drop'){host.drop();postMessage({kind:'dropped',live:host.alive.size,memory:host.e.memory.buffer.byteLength});}};
