'use strict';
const must109=(x,m)=>{if(!x)throw Error('CRITIC109_'+m)};
const eq109=(a,b,m)=>must109(JSON.stringify(a)===JSON.stringify(b),m);
async function digest109(x){const b=new TextEncoder().encode(JSON.stringify(x)),h=await crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(h),v=>v.toString(16).padStart(2,'0')).join('');}
function numeric109(row,state,fixtures,refs){const x=row.selected_numeric;if(!x)return null;const n=x.numeric;must109(n&&Array.isArray(n.features_bits)&&n.features_bits.length===648,'FEATURE_SHAPE');must109(n.policy_logits.length===136&&n.policy_logits.every(Number.isFinite)&&Number.isFinite(n.value)&&Math.abs(n.value)<=1,'NN_FINITE_STRICT');const f=state.toNNInput();eq109(n.features_bits,Array.from(new Uint32Array(f.buffer,f.byteOffset,f.length)),'FEATURE_BITS');const acts=Array.from(state.getLegalActions()),ids=acts.map(a=>rustAction(state,a));must109(new Set(ids).size===ids.length,'ACTION_INJECTIVE');const p1=state.isPlayer1Turn(),flip=[1,0,2,3,6,7,4,5];const canonical=k=>p1?k:k<8?flip[k]:8+Math.floor((k-8)/64)*64+(7-Math.floor(((k-8)%64)/8))*8+(k-8)%8;const ix=acts.map(a=>canonical(actionToIndex(a,9))),mx=Math.max(...ix.map(k=>n.policy_logits[k])),weights=ix.map(k=>Math.exp(n.policy_logits[k]-mx)),sum=weights.reduce((a,b)=>a+b,0),by=new Map(ids.map((id,i)=>[id,weights[i]/sum]));let priors=0,maxPrior=0;if(x.cp){const c=x.cp;must109(c.generation===row.identity.generation&&c.policy_fallbacks===0&&c.value_fallbacks===0,'CP_GEN_FALLBACK');eq109(c.root_edges.map(e=>e[0]),row.identity.engine==='candidate'?ids.slice().sort((a,b)=>a-b):ids,'ENGINE_ORDER');let visits=0,total=0;for(const e of c.root_edges){must109(e.length===4&&e.every(Number.isFinite)&&e[1]>=0&&Number.isSafeInteger(e[2])&&e[2]>=0&&Math.abs(e[3])<=e[2]+1e-5,'EDGE_RANGE');const want=by.get(e[0]);must109(Number.isFinite(want)&&Math.abs(e[1]-want)<=1e-4+1e-4*Math.abs(want),'PRIOR');maxPrior=Math.max(maxPrior,Math.abs(e[1]-want));total+=e[1];visits+=e[2];priors++;}must109(Math.abs(total-1)<1e-4,'PRIOR_SUM');must109(visits===(row.identity.engine==='candidate'?c.simulations-1:c.simulations),'VISIT_RULE');if(row.identity.engine==='reference')must109(c.root_visits===c.simulations+1,'REF_ROOT_VISITS');}
const fixture=fixtures.find(v=>JSON.stringify(v.legal_prefix)===JSON.stringify(row.identity.legal_prefix)),ref=fixture?refs.find(v=>v.id===fixture.id):null;let maxNN=null;if(ref){maxNN=0;for(const[a,r]of [...n.policy_logits.map((v,i)=>[v,ref.policy_logits[i]]),[n.value,ref.value]]){must109(Number.isFinite(r)&&Math.abs(a-r)<=1e-4+1e-4*Math.abs(r),'EXTERNAL_NN');maxNN=Math.max(maxNN,Math.abs(a-r));}}return {request:row.identity.request_id,engine:row.identity.engine,P2:!p1,cancelled:row.response.body.cancelled,features:648,NN:137,priors,maxNN,maxPrior,fixed_reference:!!ref,valueMeaning:row.identity.engine==='candidate'?'rootNN':'rootQ'};}
function independentMock109(){let rows=[],s=fromPrefix([]),acts=s.getLegalActions().map(a=>rustAction(s,a)),context={generation:333,key:s._positionKey(),legalActions:acts},mem=SharedBestAction.create(context),w=SharedBestAction.bind(mem,context,context),r=SharedBestAction.bind(mem,context,context);must109(r.readLatest()===null,'FIRST_NULL');w.publish({completed:true,sequence:1,action:acts[0],value:.25,visits:3});const first=r.readLatest();must109(first.sequence===1&&Object.isFrozen(first),'FROZEN_CP');Atomics.store(new Int32Array(mem),SharedBestAction.INDEX.revision,3);must109(r.readLatest()===first,'BOUNDED_READER_CACHE');Atomics.store(new Int32Array(mem),SharedBestAction.INDEX.revision,4);w.stop('budget');must109(r.readLatest().sequence===1,'BUDGET_KEEP');w.stop('cancel');must109(r.readLatest()===null,'CANCEL_NULL');must109(Object.isFrozen(first)&&first.sequence===1,'PUBLISHED_CP_UNCHANGED');rows.push('bounded_no_wait/cache_keep/cancel_null/old_public_immutable');for(const field of ['generation','key']){try{SharedBestAction.bind(mem,{...context,[field]:field==='key'?'foreign':334},context);throw Error('FOREIGN_ACCEPTED')}catch(e){must109(e.message!=='FOREIGN_ACCEPTED','FOREIGN_REJECT');}}rows.push('foreign_generation_key_rejected');const fresh=SharedBestAction.create(context),v=SharedBestAction.bind(fresh,context,context);for(const cp of [{completed:false,sequence:1,action:acts[0],value:0,visits:1},{completed:true,sequence:1,action:acts[0],value:1.00001,visits:1}]){let rejected=false;try{v.publish(cp)}catch{rejected=true}must109(rejected,'BAD_CP');}v.publish({completed:true,sequence:1,action:acts[0],value:0,visits:1});let failed=false;try{v.publish({completed:true,sequence:1,action:acts[0],value:0,visits:1})}catch{failed=true}must109(failed,'REVERSE_SEQ');Atomics.store(new Int32Array(fresh),SharedBestAction.INDEX.generation,334);must109(v.readLatest()===null,'STALE_GENERATION');rows.push('incomplete/range/duplicate/stale_rejected');for(const c of ['initial_no_completed_cp','engine_fault'])must109(gameFailureResult(c,1,'candidate').status==='responsibility_loss','AI_LOSS');for(const c of ['browser_deadline_processing_late','browser_judge_failure','external_automation_failure'])must109(gameFailureResult(c,1,'candidate').status==='unfinished','BROWSER_UNFINISHED');must109(terminalResult(new State({boardsize:9,depth:200})).winner===0,'DRAW200');must109(terminalResult(new State({boardsize:9,depth:200,player1pos:[4,8],player2pos:[4,7]})).winner===1,'GOAL_PRIORITY');return {rows,NN:0,browser_main_executed:true,actual_SharedBestAction:true,synthetic200_not_legal_reachability:true};}
async function audit113(input,fixtures,refs){
 const all=[],samples=[];let games=[];
 for(const run of input.runs){
  const rows=run.rows,map=new Map(rows.map(r=>[r.identity.request_id,r])),ownACK=new Map();
  const c={public:rows.length,legal:0,cancel:0,late:0,NN:0,discard:0,opposite_before_ACK:0,previous_API_spans_next_t0:0,post_public_API_definite:0,post_cutoff_API_definite:0,post_cutoff_API_possible:0,ACKover500:0,worker_upper_le_D:0,worker_lower_gt_D:0,worker_straddles_D:0,max_own_wait_ms:0,max_public_ms:0};
  for(let i=0;i<rows.length;i++){
   const r=rows[i],id=r.identity,p=r.response,b=p.body,s=fromPrefix(id.legal_prefix),d=r.diagnostic;
   must109(id.engine===b.engine&&id.request_id===b.request_id&&id.generation===b.generation&&id.generation===id.epoch,'BINDING');
   must109(id.key===s._positionKey(),'KEY');eq109(id.history,Array.from(s.position_history).sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:0),'HISTORY');
   must109(id.limits.seed===1979&&id.model==='d790dac68389f7602ff8a887a2385417d3c925fe22da7164c86e9226f943908d','MODEL_SEED');
   must109(id.t0_ms>= (ownACK.get(id.engine)??-Infinity),'OWN_ACK_BEFORE_NEXT');
   must109(p.t0_ms===id.t0_ms&&id.seal_ms-id.t0_ms===411&&id.commit_cutoff_ms-id.t0_ms===402&&id.deadline_ms-id.t0_ms===500,'CLOCK');
   must109(p.stamp_ms>=p.timer_ms&&p.public_elapsed_ms===p.stamp_ms-id.t0_ms&&p.bytes===new TextEncoder().encode(p.body_serialized).length,'FINAL_STAMP_ENCODING');eq109(b,JSON.parse(p.body_serialized),'IMMUTABLE_PUBLIC');
   must109([b.completed,b.cancelled,b.late].every(v=>typeof v==='boolean'),'BOOLEAN');must109(b.late===(p.stamp_ms>=id.deadline_ms),'LATE');
   if(b.completed){must109(!b.cancelled&&!b.late&&s.getLegalActions().some(a=>sameAction(a,b.action)),'LEGAL');const proof=d.sab_publications.find(v=>v.sequence===b.sequence);must109(proof&&proof.action===rustAction(s,b.action),'SAB_ACTION');c.legal++;}else {must109(b.action===null,'NULL');if(b.cancelled)c.cancel++;if(b.late)c.late++;}
   const ack=r.stop;must109(ack&&ack.identity.request_id===id.request_id&&ack.worker_engine===id.engine,'ACK_ENGINE');must109(!ack.stop.handles&&!ack.stop.activeNN&&!ack.stop.live_searches&&!ack.stop.active,'ACK_ZERO');ownACK.set(id.engine,ack.main_received_ms);
   const clock=r.worker_clock;must109(clock.lo_ms<=clock.hi_ms,'CLOCK_INTERVAL');const lo=ack.stop.at_ms-clock.hi_ms,hi=ack.stop.at_ms-clock.lo_ms;
   if(hi<=id.deadline_ms)c.worker_upper_le_D++;else if(lo>id.deadline_ms)c.worker_lower_gt_D++;else c.worker_straddles_D++;
   if(ack.main_received_ms-id.t0_ms>500)c.ACKover500++;
   c.max_public_ms=Math.max(c.max_public_ms,p.public_elapsed_ms);c.max_own_wait_ms=Math.max(c.max_own_wait_ms,r.own_previous_wait.wait_ms);
   const ev=d.NN_control_events??[];c.NN+=ev.length;c.discard+=ev.filter(x=>x.result_discarded).length;for(const x of ev){must109(x.engine===id.engine&&x.generation===id.generation&&x.request_id===id.request_id,'NN_ECHO');if(x.session_run_start_ms-clock.hi_ms>p.stamp_ms)c.post_public_API_definite++;if(x.session_run_start_ms-clock.hi_ms>id.commit_cutoff_ms)c.post_cutoff_API_definite++;if(x.session_run_start_ms-clock.lo_ms>id.commit_cutoff_ms)c.post_cutoff_API_possible++;}
   const previous=rows.slice(0,i).reverse().find(v=>v.identity.engine!==id.engine);
   if(previous){if(id.t0_ms<previous.stop.main_received_ms)c.opposite_before_ACK++;const k=previous.worker_clock;if((previous.diagnostic.NN_control_events??[]).some(x=>x.session_run_start_ms-k.hi_ms<=id.t0_ms&&x.session_run_end_ms-k.lo_ms>=id.t0_ms))c.previous_API_spans_next_t0++;}
   if(!r.selected_numeric&&d.numeric?.length)r.selected_numeric={numeric:d.numeric[0],cp:d.validated_cp};if(r.selected_numeric)samples.push(numeric109(r,s,fixtures,refs));
  }
  for(const g of run.games??[]){let prefix=structuredClone(g.initial_prefix),s=fromPrefix(prefix);must109(g.seed===1979&&g.actions.length===g.turn_indices.length,'GAME_COUNTS');for(let i=0;i<g.actions.length;i++){must109(!terminalResult(s),'CONTINUE_TERMINAL');const r=map.get(g.turn_indices[i]);must109(r,'ROW');eq109(r.identity.legal_prefix,prefix,'REPLAY_PREFIX');must109(r.identity.engine===(s.getCurrentPlayer()===g.candidate_color?'candidate':'reference'),'COLOR');eq109(r.response.body.action,g.actions[i],'PUBLIC_MOVE');must109(s.getLegalActions().some(a=>sameAction(a,g.actions[i])),'REPLAY_LEGAL');prefix.push(g.actions[i]);s=s.next(g.actions[i]);}const end=terminalResult(s);must109(end&&end.winner===g.winner&&g.reason==='goal'&&g.status==='terminal','GOAL');must109(s._positionKey()===g.final_key&&s.depth===g.total_ply,'END_CONTEXT');games.push({id:g.id,color:g.candidate_color,winner:end.winner,plies:g.actions.length,score:end.winner===g.candidate_color?1:0});}
  const clocks={};if(run.clock_end)for(const e of ['candidate','reference']){const end=run.clock_end[e];const lo=Math.max(...end.samples.map(x=>x.worker_ms-x.end_ms-.1)),hi=Math.min(...end.samples.map(x=>x.worker_ms-x.start_ms+.1));must109(lo<=hi&&lo===end.lo_ms&&hi===end.hi_ms,'END_CLOCK');clocks[e]={lo,hi,initial:rows.find(r=>r.identity.engine===e)?.worker_clock,continuous_drift_guarantee:false};}
  all.push({run:run.run,counts:c,clock_end:clocks});
 }
 return {runs:all,games,W:games.filter(g=>g.score===1).length,L:games.filter(g=>g.score===0).length,numeric_samples:samples,browser_adjudicated:true,shared_RuleA_independence_limit:true,API_await_not_kernel_CPU:true,formal_go:false};
}
