import json,pathlib,statistics,hashlib,itertools,datetime,math
R=pathlib.Path(__file__).resolve().parents[2];D=R/'research-data/ai-sigma/137-fixed-policy-cost';O=R/'.artifacts/ai-sigma/resume-20261002/FIXED-POLICY-COST/runs';rd=O/'cost137-r2'
def load(p):return json.loads(p.read_text())
def rnd(v):return round(v,5)
d=load(rd/'browser-result.json');saved=load(D/'fixed-input.json');threads=load(O/'cost137-r2.threads.json');process=load(O/'cost137-r2.process.json');samples=threads['samples']
chrome_ids=set();tidnames={}
for s in samples:
 for t in s['threads']:
  key=(t['pid'],t['pid_start_ticks'],t['TID'],t['tid_start_ticks']);tidnames[key]=t['comm']
  if t['pid']==t['TID'] and t['comm'] in ['chrome','chrome_crashpad']:chrome_ids.add((t['pid'],t['pid_start_ticks']))
def cpu_interval(start,end):
 # Samples wholly within boundary and same identity endpoints. No interpolation; tails are missing.
 inner=[s for s in samples if s['unix_ns']/1e6>=start and s['read_end_unix_ns']/1e6<=end]
 if len(inner)<2:return {'supported':False,'missing_reason':'fewer than two wholly inside samples'}
 first,last=inner[0],inner[-1]
 def mapping(s):return {(t['pid'],t['pid_start_ticks'],t['TID'],t['tid_start_ticks']):t for t in s['threads']}
 a,b=mapping(first),mapping(last);common=a.keys()&b.keys();rows=[]
 for k in sorted(common):
  x,y=a[k],b[k];diff={n:y[n]-x[n] for n in ['utime_ticks','stime_ticks','runtime_ns','runqueue_ns','timeslices']}
  if any(v<0 for v in diff.values()):raise AssertionError('NEGATIVE_THREAD_COUNTER')
  rows.append({'pid':k[0],'pid_start_ticks':k[1],'TID':k[2],'tid_start_ticks':k[3],'comm':y['comm'],'Chrome_main_comm_observed':k[:2] in chrome_ids,'Worker_NN_binding':None,**diff})
 chrome=[r for r in rows if r['Chrome_main_comm_observed']]
 return {'supported':True,'boundary_requested_start_ms':start,'boundary_requested_end_ms':end,'sample_first_ms':first['unix_ns']/1e6,'sample_last_end_ms':last['read_end_unix_ns']/1e6,'leading_missing_ms':first['unix_ns']/1e6-start,'trailing_missing_ms':end-last['read_end_unix_ns']/1e6,'sample_clock_read_span_ms':[first['read_end_unix_ns']/1e6-first['unix_ns']/1e6,last['read_end_unix_ns']/1e6-last['unix_ns']/1e6],'common_TIDs':len(common),'disappeared_TIDs':len(a.keys()-b.keys()),'new_TIDs':len(b.keys()-a.keys()),'Chrome_common_TIDs':len(chrome),'Chrome_runtime_ms':sum(r['runtime_ns'] for r in chrome)/1e6,'Chrome_runqueue_TIDsum_ms':sum(r['runqueue_ns'] for r in chrome)/1e6,'owned_nonChrome_runtime_ms':sum(r['runtime_ns'] for r in rows if not r['Chrome_main_comm_observed'])/1e6,'observed_TID_deltas':rows,'not_whole_interval_cpu':True,'main_comm_identification_exe_at_sample_missing':True,'runqueue_sum_not_wall_delay':True}
rows=[]
for r in d['rows']:
 nn=r['diagnostic']['NN_control_events'];pub=r['diagnostic']['sab_publications'];off=r['worker_clock']['mid_ms'];t0=r['identity']['t0_ms'];m=r['cost_markers'];sp=r['cost_spans'];a=r['adopted_stats'];dur=[x['return_ms']-x['start_ms'] for x in nn];spans=r['diagnostic']['result']['spans'];first=pub[0];reject=[x for x in r['diagnostic']['validation_events'] if not x['accepted']]
 assert len(r['diagnostic']['numeric'][0]['features_bits'])==648
 vals=[*r['diagnostic']['numeric'][0]['policy_logits'],r['diagnostic']['numeric'][0]['value']];assert len(vals)==137 and all(math.isfinite(x) for x in vals) and -1<=vals[-1]<=1
 # Completed public CP root_edges priors already checked by browser, preserve count checks and noNN separately.
 assert all(x['completed_backup']==x['loop_simulations']+1==x['edge_sum']+1 for x in pub)
 row={'sample':r['spec']['cost_sample'],'warm':r['spec']['warm'],'request_id':r['identity']['request_id'],'classification':r['response']['classification'],'adopted_eligible_completed_backup':a['completed_backup'],'rootN':a['rootN'],'loop_simulations':a['loop_simulations'],'edge_sum':a['edge_sum'],'Action209':a['action'],'sequence':a['sequence'],'API_NN_calls':len(nn),'NN_return_discarded':sum(x['result_discarded'] for x in nn),'accepted_CP_terminal_noNN':[x['completed_backup']-x['cp_NN_calls'] for x in pub],'completed_finish_spans_observed':sum(x['kind']=='finish' for x in spans),'rejected_CP_sequences':reject,'rejected_CP_full_body_missing':bool(reject),'input_replay_ms':rnd(sp['input_replay_end_ms']-sp['input_replay_start_ms']),'main_input_prepare_ms':rnd(m['input_prepare_end_ms']-m['input_prepare_start_ms']),'main_t0_to_dispatch_ms':rnd(m['dispatch_ms']-t0),'dispatch_to_Worker_enter_ms':rnd(r['diagnostic']['cost_worker_markers'][0]['at_ms']-off-m['dispatch_ms']),'Worker_enter_to_control_cache_ms':rnd(r['diagnostic']['cost_worker_markers'][1]['at_ms']-r['diagnostic']['cost_worker_markers'][0]['at_ms']),'t0_to_first_API_ms':rnd(nn[0]['start_ms']-off-t0),'first_API_await_ms':rnd(dur[0]),'t0_to_first_CP_validation_ms':rnd(first['validation_end_ms']-off-t0),'API_await_median_ms':rnd(statistics.median(dur)),'API_await_min_ms':rnd(min(dur)),'API_await_max_ms':rnd(max(dur)),'API_await_sum_ms':rnd(sum(dur)),'API_await_durations_ms':[rnd(x) for x in dur],'adopt_planned_elapsed_ms':r['response']['planned_ms']-t0,'adopt_actual_elapsed_ms':rnd(r['response']['public_elapsed_ms']),'post_public_API_overlap_ms':rnd(sum(max(0,x['return_ms']-max(x['start_ms'],r['response']['stamp_ms']+off)) for x in nn)),'public_to_both_zero_ms':rnd(sp['both_zero_after_ms']-sp['public_return_ms']),'ACK_wall_ms':rnd(r['ACK_wall_ms']),'detail_validation_after_zero_ms':rnd(sp['detail_validation_end_ms']-sp['both_zero_after_ms']),'both_previous_zero_wait_ms':rnd(sp['both_previous_zero_wait_end_ms']-sp['both_previous_zero_wait_start_ms']),'rootFinished_ms':r['diagnostic']['result'].get('rootFinished'),'CP_series':[{'K':x['completed_backup'],'Action':x['action'],'NN_calls':x['cp_NN_calls'],'sequence':x['sequence'],'worker_validation_end_ms':x['validation_end_ms'],'readonly_CPcopy_ms':rnd(x['readonly_copy_end_ms']-x['validation_end_ms'])} for x in pub],'API_kernel_CPU_conversion':False,'CPU_dispatch_to_public':cpu_interval(m['dispatch_ms'],r['response']['stamp_ms']),'CPU_public_to_ACK':cpu_interval(r['response']['stamp_ms'],r['stop']['main_received_ms'])}
 rows.append(row)
comparisons=[]
for i,j in itertools.combinations(range(4),2):
 a={p['completed_backup']:p for p in d['rows'][i]['diagnostic']['sab_publications']};b={p['completed_backup']:p for p in d['rows'][j]['diagnostic']['sab_publications']};K=sorted(a.keys()&b.keys());comparisons.append({'samples':[rows[i]['sample'],rows[j]['sample']],'same_K':K,'all_Action_same':all(a[k]['action']==b[k]['action'] for k in K),'all_root_edges_bit_equal':all(a[k]['root_edges']==b[k]['root_edges'] for k in K)})
saved_comp=[]
for row,r in zip(rows,d['rows']):
 p={x['completed_backup']:x for x in r['diagnostic']['sab_publications']}
 for rep,s in enumerate(saved['saved_CP_series'],1):
  q={x['completed_backup']:x for x in s};K=sorted(p.keys()&q.keys());saved_comp.append({'sample':row['sample'],'old_rep':rep,'common_K':K,'Action_equal_all_common_K':all(p[k]['action']==q[k]['action'] for k in K)})
mon=[json.loads(l) for l in (O/'cost137-r2.monitor.jsonl').read_text().splitlines()];cycles=[x['elapsed_seconds'] for x in mon if x['kind']=='monitor_cycle']
summary={'issue':'quoridor-4lc.137','measured_entry_Git':load(rd/'config.json')['Git'],'all_attempts':d['attempts'],'request_denominator':{'warm':1,'steady':3,'started':4,'completed_legal':4,'unstarted':0,'startup_NN':6,'session_count':2,'hand_NN':44,'games':0},'selected_state':{'side':1,'totalply':16,'features648_all_exact':all(r['diagnostic']['numeric'][0]['features_bits']==saved['numeric']['features_bits'] for r in d['rows']),'rootNN137_all_bit_equal':all(r['diagnostic']['numeric'][0]==saved['numeric'] for r in d['rows']),'fixed_golden_for_new_state':False},'samples':rows,'same_K_new_comparisons':comparisons,'exact_saved_K_Action_comparisons':saved_comp,'CP_body_capture_limit':'All accepted SAB CPs captured; AFTER_CUTOFF rejected CP10/sample2 and CP16/sample3 full bodies absent. Kernel finish markers and validation rejection are separate; do not impute Actions/statistics.','monitor':{'thread_samples':len(samples),'thread_binding':'unmapped, main comm Chrome process-group proxy only; executable-at-sample absent','CPU_tick_ms':1000/threads['clock_ticks_per_second'],'schedstat_units':'ns counter; not sampling accuracy','monitor_cycle_wall_ms_median':1000*statistics.median(cycles),'monitor_cycle_wall_ms_sum':1000*sum(cycles),'guardian_own_cpu_counter_last_missing':True,'lost_threads_terminal_tail_missing':True,'Node_and_Beads_observer_cpu_separate_from_Chrome':True},'resource':{'heavy_wall_seconds':(datetime.datetime.fromisoformat(process['end'])-datetime.datetime.fromisoformat(process['start'])).total_seconds(),'peak_current_RSS':process['peak_group_plus_runner_RSS'],'guard':5905580032,'affinity':[2],'all_observed_TIDs_CPU2':process['all_observed_TIDs_at_assigned_CPU'],'heavy_cap_seconds':180},'decision':{'classification':'finite support for completed quantity/Action and API-response boundary association; CPU cause unresolved','policy':'maintain current policy; no C/FPU/model change','same_state_repeat':'end this same-format branch','max_one_followup':{'proposal':'one bounded API response boundary experiment with guardian/Beads monitor sampling overhead measured or reduced, fixed same model/policy/input; only if separately allocated','needed_cost':'one new result-before-fixed control pair within explicit remaining budget; not started137','falsifier':'completed/API span variation persists with monitor cost controlled, or no boundary shift','next_decision':'if boundary effect supports, reduce monitoring/preparation overhead; otherwise stop cost attribution and reconsider broader evaluation question'},'not_proved':['CPU/scheduling causal source','pure inference CPU','119 loss cause','sameCPU/same effective cycles','performance or strength improvement','NI/Sigma']}}
(D/'analysis.json').write_text(json.dumps(summary,indent=2)+'\n')
print(json.dumps({'rows':[{k:r[k] for k in ['sample','adopted_eligible_completed_backup','Action209','API_await_median_ms','main_input_prepare_ms','first_API_await_ms','t0_to_first_CP_validation_ms','adopt_actual_elapsed_ms','API_NN_calls']} for r in rows],'CPU':[{k:r['CPU_dispatch_to_public'].get(k) for k in ['Chrome_runtime_ms','Chrome_runqueue_TIDsum_ms','owned_nonChrome_runtime_ms','leading_missing_ms','trailing_missing_ms']} for r in rows],'sameK':comparisons,'resource':summary['resource'],'monitor':summary['monitor']},indent=2))
