export const ja = {
  title: 'コリドール 3D', local: 'ローカル対局', loading: '対局を準備しています…',
  first: '先手・丸い駒', second: '後手・六角の駒', turn: 'の手番', winner: 'の勝ち！',
  animating: '着手を反映中…', error: '対局を開始できません。新しい対局を試してください。',
  move: '駒を動かす', wall: '壁を置く', horizontal: '横向き', vertical: '縦向き',
  undo: '1手戻す', newGame: '新しい対局', flip: '反対側から見る', resetCamera: '視点を戻す',
  restart: 'やり直す', more: '設定・保存', close: '閉じる', cancel: 'キャンセル',
  startMatch: 'この設定で開始', startNew: '新しい対局を始める',
  discardStart: '保存を破棄して開始', resumeHeading: '対局を選ぶ',
  newMatchHint: '対戦方式と先後を選び、開始してください。今の対局は開始するまで変わりません。',
  restartHint: '今の対局条件で最初から始めます。', confirmPlacement: 'この場所に置く',
  remainingWalls: '残りの壁', wallDirection: '壁の向き', ply: '手目', boardLabel: '3Dコリドール盤',
  controlsLabel: '対局操作',
  sound: 'サウンド', muteAll: 'すべての音を消す', unmuteAll: '消音を解除する',
  soundOn: '音あり', soundMuted: '消音中', soundSilent: '音なし',
  sfx: '効果音（SE）', bgm: '音楽（BGM）', sfxVolume: '効果音の音量', bgmVolume: '音楽の音量',
  soundPreview: '効果音を試聴', soundRetry: '音声を再試行', soundCredits: '音源クレジット',
  soundCreditText: '効果音：Kenney・el_boss ／ 音楽：MintoDog。無料のCC0素材を使用しています。',
  gameFinished: '対局終了', humanWon: 'あなたの勝ち', aiWon: 'AIの勝ち', reachedGoal: 'がゴールに到着',
  totalMoves: '総手数', review: '振り返る', reviewing: '振り返り', playAgain: 'もう一度遊ぶ',
  viewBoard: '盤面を見る', viewResult: '結果を見る', returnTitle: 'タイトルに戻る', backToResult: '結果に戻る',
  reviewFirst: '最初', reviewPrev: '前の手', reviewNext: '次の手', reviewLast: '最後',
  reviewLoading: '棋譜を準備しています…', reviewFailed: '振り返りを読み込めませんでした。対局と棋譜は保持しています。',
  reviewRetry: '振り返りを再試行',
  audioWaiting: '操作すると音が流れます。', audioLoading: '音声を準備しています…',
  audioBlocked: '音声を開始できませんでした。「音声を再試行」を押してください。',
  audioUnavailable: 'このブラウザでは音声を使えません。対局は続けられます。',
  audioFailed: '一部の音声を読み込めませんでした。対局は続けられます。',
  audioInvalid: '保存済みの音設定を読めないため、既定の設定を使います。',
  audioStorage: '音設定を保存できません。今回の設定は使えます。',
  environment: '環境', retryEnvironment: '環境を再読み込み', environmentReady: 'を表示中。',
  environmentLoading: 'を読み込んでいます…', environmentFailed: 'を読み込めませんでした。',
  environmentKept: 'を引き続き表示します。', environmentFallback: '簡易背景で対局を続けられます。',
  settings: '表示と操作の設定', noAnimation: '動きを省略する', diagnostics: '描画情報',
  guideMove: '光るマスをクリックして移動。矢印キーとEnterでも操作できます。',
  guideWall: '壁の位置へ合わせてクリック。Rキーで向きを変更。',
  guideKeyboard: '盤にフォーカスして矢印キーで候補、Enterで確定、Escで解除。右ドラッグで視点、ホイールで拡大縮小。',
  legal: 'ここに置けます。クリックまたはEnterで確定。',
  illegal: 'この場所には置けません。',
  giOff: 'GIオフ',
  matchSettings: '対局の設定', pvp: '2人で対戦', versusAi: 'AIと対戦',
  humanSide: 'あなたの手番', humanFirst: '先手', humanSecond: '後手',
  thoughtBudget: 'AIの思考量', thinking: 'AIが考えています…',
  aiProgress: '探索', cancelAi: '思考を中止', retryAi: 'AIを再試行', takeControl: '2人対戦に切り替える',
  aiStopped: 'AIを中止しました。再試行または2人対戦に切り替えられます。',
  aiFailed: 'AIが動作できません。再試行または2人対戦に切り替えられます。',
  aiInterrupted: 'AIの手番を再開できます',
  matchHeading: '対局', playersHeading: 'プレイヤー', actionHeading: '操作', cameraHeading: '視点',
  boardEyebrow: 'ローカル対局', preparing: '準備中', longThought: '長考',
  applyOnNew: '対局設定は「新しい対局」から反映されます。',
  activeMatch: '進行中',
  saveHeading: '保存と再開', resume: '前の対局を再開', saveNow: '今すぐ保存', clearSave: '保存を消す',
  resumePrompt: '前の対局があります。再開するか、新しい対局を選んでください。',
  noSave: '保存した対局はありません。', saved: 'この対局を保存しました。',
  saveCleared: '保存データを消しました。今の対局は続けられます。',
  saveClearedStartup: '保存データを消しました。対局の設定を選んで開始してください。',
  saveCorrupt: '保存した対局を読み込めません。データは残しています。新しい対局で上書きするか、保存を消してください。',
  restoreFailed: '対局を復元できません。今の対局と保存データはそのままです。',
  saveFailed: '対局を保存できませんでした。対局は続けられます。',
  storageUnavailable: 'ブラウザの保存領域を使えません。対局は続けられます。',
  storageQuota: '保存領域がいっぱいです。対局は続けられます。',
  settingsInvalid: '保存済みの設定を読めないため、既定の設定を使います。',
  settingsUnavailable: '設定を保存できません。今回の設定は使えます。',
  settingsQuota: '設定の保存領域がいっぱいです。',
  renderStopped: '描画を停止しました', renderRecovery: '対局の状態は保持しています。描画を再試行してください。改善しない場合はページを再読み込みしてください。',
  retryRenderer: '描画を再試行', rulesStopped: 'ルールエンジンを開始できません',
  rulesRecovery: '対局の開始を再試行してください。更新直後ならページを再読み込みし、開発中はWasmを再ビルドしてください。',
  retryRules: '対局の開始を再試行', reload: 'ページを再読み込み',
  reloadGuidance: 'ページを再読み込みしてください。開発中ならWasmとアプリを再ビルドしてください。',
  rulesUnavailable: 'ルールエンジンを利用できません。保存データは消していません。',
  buildMismatchTitle: 'AIの版が一致しません',
  buildMismatch: 'AIを動かせません。ページの再読み込み後も続く場合はアプリを再ビルドしてください。現在の対局は2人対戦に切り替えられます。',
  errorDetail: '技術的な詳細',
} as const;
