"use strict";
const fs=require('fs'),assert=require('assert'),crypto=require('crypto'),zlib=require('zlib');
const {createReference}=require('../ai-sigma-native-baseline/reference.cjs');const {r}=createReference();
const c=JSON.parse(fs.readFileSync(process.argv[2]));assert.equal(c.issue,'quoridor-4lc.239');assert.equal(c.task,'saved-arena-ruleA-diagnosis');
const load=p=>JSON.parse(fs.readFileSync(p)),hash=x=>crypto.createHash('sha256').update(x).digest('hex');
for(const[p,h]of Object.entries(c.input_SHA))assert.equal(hash(fs.readFileSync(p)),h,p);
const manifest=load(c.openings),pilot=load(c.pilot),later=load(c.later),all=load(c.allattempt),caseRule=load(c.case_rule);
assert.equal(caseRule.cases_max,4);const ledger=all.ledger;assert.equal(ledger.length,8);assert.equal(new Set(ledger.map(x=>x.slot)).size,8);
const lines=[c.pilot_hands,c.later_hands].flatMap(p=>fs.readFileSync(p,'utf8').trim().split('\n').filter(Boolean).map(s=>JSON.parse(s)));
const sum={};function group(engine,bucket){const k=engine+'/'+bucket;return sum[k]??= {engine,bucket,hands:0,depths:{},typed_stops:{},partial_discard:0,nodes:0,NN:0,D_evals:0,spans_inclusive_ms:{},search_wholewall_ms:0,elapsed_ms:0,elapsed_max_ms:0,obsolete:0,terminal_entries:0,recorded_completed_depths:0,recorded_incomplete_depths:0};}
function add(engine,bucket,h,s){const z=group(engine,bucket);z.hands++;if(h){z.elapsed_ms+=h.clock.elapsed_ms;z.elapsed_max_ms=Math.max(z.elapsed_max_ms,h.clock.elapsed_ms);z.obsolete+=(h.clock.obsolete??[]).length;}if(s){assert.equal(s.TT,0);assert.equal(s.policy_exclusion,false);assert(s.last_completed_only);const depth=s.completed_depth??'NONE';z.depths[depth]=(z.depths[depth]??0)+1;z.typed_stops[s.typed_stop??'NONE']=(z.typed_stops[s.typed_stop??'NONE']??0)+1;z.partial_discard+=s.partial_depth_discarded!==null?1:0;z.nodes+=s.stats?.processed??0;z.NN+=s.stats?.NN??0;z.D_evals+=s.stats?.D_evals??0;z.terminal_entries+=s.stats?.terminal??0;z.search_wholewall_ms+=s.wholewall_ms??0;for(const[k,v]of Object.entries(s.spans??{}))z.spans_inclusive_ms[k]=(z.spans_inclusive_ms[k]??0)+v;for(const d of s.depths??[]){if(d.status==='COMPLETED')z.recorded_completed_depths++;else{assert.equal(d.adopted,false);z.recorded_incomplete_depths++;}}}}
function history(s){return JSON.stringify([s._positionKey(),s.getCurrentPlayer(),[...s.position_history].sort(([a],[b])=>a<b?-1:a>b?1:0)]);}
function board(s){return JSON.stringify([s.boardsize,s.getCurrentPlayer(),s.player1pos,s.player2pos,[...s.hwall_anchors].sort(),[...s.vwall_anchors].sort(),s.walls_p1,s.walls_p2,Array.from(s.hwalls),Array.from(s.vwalls)]);}
function context(s){return JSON.stringify([board(s),s.depth,history(s)]);}
function dist(s){const i=s.player1pos[1]*9+s.player1pos[0],j=s.player2pos[1]*9+s.player2pos[0];return[s.p1_dist[i],s.p2_dist[j]];}
const compact=[],games=[],caseOptions={},WDL={W:0,L:0,D:0,UNKNOWN:0};let rulesChecks=0;
for(const slot of ledger.slice().sort((a,b)=>a.slot-b.slot)){
 const opening=manifest.openings.find(x=>x.id===slot.opening);assert(opening);let s=r.fromPrefix(opening.prefix),prefix=opening.prefix.slice();assert.equal(s._positionKey(),opening.key);assert.equal(history(s),opening.history);
 const rows=lines.filter(x=>x.slot===slot.slot);assert.equal(rows.length,slot.hands);const boards=new Map([[board(s),s.depth]]),full=new Map([[context(s),s.depth]]);
 const game={slot:slot.slot,opening:slot.opening,NNUE_side:slot.NNUE_side,status:slot.status,result_NNUE:slot.result_NNUE??'UNKNOWN',hands:rows.length,adopted:0,dropped:0,board_side_repeats:0,full_history_context_repeats:0,NNUE_walls:0,D_walls:0,NNUE_retreats:0,D_retreats:0,NNUE_goal_near_retreats:0,D_goal_near_retreats:0,fault:slot.fault??null};
 const events=[];
 for(const h of rows){assert.equal(h.ply,s.depth);assert.equal(h.side,s.getCurrentPlayer());assert.equal(h.engine,h.side===slot.NNUE_side?'NNUE':'distance');const response=h.clock.response,search=response?.search;const adopted=h.clock.status==='RECEIVED'&&response?.validation?.valid===true;
  add(h.engine,adopted?'adopted':'dropped',h,search);if(response?.type==='RESULT'){assert.equal(response.key,s._positionKey());assert.equal(response.history,history(s));assert.equal(response.id,h.id);assert.equal(response.generation,h.generation);}
  if(!adopted){game.dropped++;assert(slot.status==='UNKNOWN');continue;}
  assert(search?.status==='COMPLETED_ACTION'&&search.completed_depth>=1);assert.equal(r.terminalResult(s),null);
  const before=board(s),beforectx=context(s),d0=dist(s),legal=s.getLegalActions(),a=legal.find(a=>r.rustAction(s,a)===search.Action);assert(a);assert.equal(board(s),before);assert.equal(context(s),beforectx);const saved=slot.prefix[s.depth];assert(saved&&a.type===saved.type&&(a.type==='pawn'?a.direction[0]===saved.direction[0]&&a.direction[1]===saved.direction[1]:a.x===saved.x&&a.y===saved.y&&a.orientation===saved.orientation));rulesChecks++;
  const beforePrefix=prefix.slice(),beforeply=s.depth,next=s.next(a),d1=dist(next),k=board(next),fc=context(next),rep=boards.has(k),fullrep=full.has(fc),self=h.side-1;
  const event={slot:slot.slot,opening:slot.opening,ply:beforeply,engine:h.engine,side:h.side,Action:search.Action,action:a,completed_depth:search.completed_depth,value:search.value,partial_discarded:search.partial_depth_discarded,processed:search.stats.processed,NN:search.stats.NN,D_evals:search.stats.D_evals,elapsed_ms:h.clock.elapsed_ms,search_wholewall_ms:search.wholewall_ms,dist_before:d0,dist_after:d1,self_goal_distance_change:d1[self]-d0[self],wall:a.type==='wall',board_side_repeat:rep,board_side_prior_ply:boards.get(k)??null,full_history_context_repeat:fullrep,full_history_SHA_before:hash(history(s)),full_history_SHA_after:hash(history(next)),before_position_key:s._positionKey(),after_position_key:next._positionKey(),history_entries_after:next.position_history.size,source_hand_id:h.id};
  compact.push(event);events.push({...event,before_prefix:beforePrefix});game.adopted++;
  if(rep)game.board_side_repeats++;if(fullrep)game.full_history_context_repeats++;boards.set(k,next.depth);full.set(fc,next.depth);
  const tag=h.engine==='NNUE'?'NNUE':'D';if(a.type==='wall')game[tag+'_walls']++;if(d1[self]>d0[self]){game[tag+'_retreats']++;if(d0[self]<=2)game[tag+'_goal_near_retreats']++;}
  prefix.push(JSON.parse(JSON.stringify(a)));s=next;
 }
 assert.equal(JSON.stringify(prefix),JSON.stringify(slot.prefix));assert.equal(s.depth,slot.final_ply);rulesChecks++;
 const terminal=r.terminalResult(s);if(slot.status==='TERMINAL'){assert(terminal);assert.equal(terminal.winner,slot.winner);WDL[slot.result_NNUE]++;}else{WDL.UNKNOWN++;assert(slot.status==='UNKNOWN');}
 for(const late of slot.stop?.discarded_late_responses??[])if(late.search)add(slot.fault?.cause_side??'UNKNOWN','late_stop_discard',null,late.search);
 const options=caseOptions[slot.opening]??=[];
 for(const e of events){if(e.board_side_repeat)options.push({priority:0,reason:'first-board-side-repeat',...e});if(e.engine==='NNUE'&&e.wall)options.push({priority:1,reason:'first-NNUE-wall',...e});}
 const NN=events.filter(x=>x.engine==='NNUE');if(slot.status==='TERMINAL'&&NN.length)options.push({priority:2,reason:'last-NNUE-before-terminal',...NN[NN.length-1]});if(NN.length)options.push({priority:3,reason:'first-NNUE-adopted',...NN[0]});
 game.final_ply=s.depth;game.final_goal_distance=dist(s);game.winner=terminal?.winner??null;games.push(game);
}
assert.deepStrictEqual(WDL,all.WDL_NNUE);const cases=manifest.openings.slice(0,4).map(o=>{const options=(caseOptions[o.id]??[]).sort((a,b)=>a.priority-b.priority||a.slot-b.slot||a.ply-b.ply);return options.length?{status:'AVAILABLE',...options[0]}:{opening:o.id,status:'NOT_AVAILABLE'};});
const result={schema:'frame19-arena-diagnosis-v1',task:c.task,issue:c.issue,input_SHA:c.input_SHA,producer_stop:c.producer_stop,all8slots:games,WDL_NNUE:WDL,hands_logged:lines.length,ruleA_action_final_checks:rulesChecks,engine_summaries:Object.values(sum),cases,old_r1_failure:all.old_failure_attempt,old_NN_known:all.physical_NN_known,old_NN_conservative_charge:all.NN_conservative_charge,old_inflight_unknown:all.inflight_NN_actual,all_attempt_science_s:all.guardian_science_all_attempt_wall_s,route_walls:{pilot_ms:pilot.wholewall_ms,later_ms:later.wholewall_ms,pilot_init_ms:pilot.init_to_ready_ms,later_init_ms:later.init_to_ready_ms},NN_model_newarena_GPU:0,limits:['saved observed different-state depths are not paired evaluator causal effect','terminal seven slots exploratory, UNKNOWN/censor retained','same RuleA replay dependency; no independent universal rule proof','inclusive spans separately summed, never added as exclusive dominance','goal distance retreat/wall count not objectively bad action or excessive','complete history+draw context includes ply/counts; board-side repeat not identical legal context','all child exact value/argmax and leaf labels NOT_RECORDED','case priorities preregistered before reading logs but diagnostic after arena result; no fresh selection claim']};
fs.writeFileSync(c.output,JSON.stringify(result,null,2)+'\n');fs.writeFileSync(c.compact_gzip,zlib.gzipSync(Buffer.from(compact.map(x=>JSON.stringify(x)).join('\n')+'\n')));console.log(JSON.stringify({schema:result.schema,hands:lines.length,checks:rulesChecks,WDL,summary:result.engine_summaries.map(x=>({engine:x.engine,bucket:x.bucket,hands:x.hands,depths:x.depths,NN:x.NN,D:x.D_evals}))}));
