const fs=require('node:fs'),path=require('node:path'),{createRequire}=require('node:module');const{chromium}=createRequire('/workspaces/quoridor/package.json')('playwright');
const root='/workspaces/quoridor/.worktree/ai-sigma',tool=path.join(root,'tools/ai-sigma-web-reference'),ref=path.join(root,'.artifacts/ai-sigma/reference/SIGMA-WEB-REFERENCE'),run=path.join(root,'.artifacts/ai-sigma/runs/SIGMA-WEB-REFERENCE');
const routes={'/game.js':ref+'/game.js','/ref/game.js':ref+'/game.js','/context.js':tool+'/context.js','/ref/context.js':tool+'/context.js','/ref/mcts_worker.js':tool+'/mcts_worker.js','/ref/ort.min.js':ref+'/ort.min.js','/models_9x9/best.onnx':root+'/models/experiments/ai-sigma/reference/sigma-pcr250/best.onnx','/fixtures.json':root+'/.artifacts/ai-sigma/reference-fixtures/SIGMA-PARITY-PLAN/fixtures.json','/ort/ort-wasm-simd-threaded.jsep.mjs':ref+'/ort-wasm-simd-threaded.jsep.mjs','/ort/ort-wasm-simd-threaded.jsep.wasm':ref+'/ort-wasm-simd-threaded.jsep.wasm'};
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/workspaces/quoridor/artifacts/playwright/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox','--disable-gpu','--renderer-process-limit=1','--disable-dev-shm-usage']});try{const context=await browser.newContext();const network=[];await context.route('**/*',async r=>{const u=new URL(r.request().url());network.push(u.href);if(u.origin!=='http://localhost:5186'){await r.abort();return;}if(u.pathname==='/'){await r.fulfill({contentType:'text/html',body:'<!doctype html><script src="/game.js"></script><script src="/context.js"></script>'});return;}const f=routes[u.pathname];if(!f){console.error('UNEXPECTED_ROUTE',u.href);await r.abort();return;}await r.fulfill({contentType:u.pathname.endsWith('.wasm')?'application/wasm':/\.m?js$/.test(u.pathname)?'text/javascript':u.pathname.endsWith('.json')?'application/json':'application/octet-stream',body:fs.readFileSync(f)});});const page=await context.newPage();page.on('console',x=>console.log('BROWSER',x.type(),x.text()));page.on('pageerror',x=>console.error('PAGE',x));await page.exposeFunction('saveEvidence',(name,v)=>{if(!/^[a-z0-9.-]+$/.test(name))throw Error('filename');fs.writeFileSync(run+'/'+name,JSON.stringify(v,null,2)+'\n');});await page.goto('http://localhost:5186/'+(process.argv.includes('--boundary')?'?boundary':''));await page.evaluate(async()=>{
 const now=()=>performance.timeOrigin+performance.now(),data=await(await fetch('/fixtures.json')).json(),fixtures=data.fixtures||data.cases;const w=new Worker('/ref/mcts_worker.js?model=/models_9x9/best.onnx');let generation=0,pending=new Map(),events=[],notify=null;let readyResolve,readyReject;const ready=new Promise((a,b)=>{readyResolve=a;readyReject=b;});
 w.onerror=e=>readyReject(Error(e.message));w.onmessage=e=>{const q=e.data,receive=now();events.push({...q,receive});if(q.type==='model_loaded')readyResolve(q);if(q.type==='model_failed')readyReject(Error(q.reason));if(q.type==='nn_started'&&notify)notify(q);if(q.type==='response'){const p=pending.get(q.generation);if(p){pending.delete(q.generation);p({...q,receive});}}};
 function request(d){return new Promise(resolve=>{pending.set(d.generation,resolve);w.postMessage(d);});}
 const freeze=o=>{if(o&&typeof o==='object'){Object.freeze(o);for(const v of Object.values(o))freeze(v);}};fixtures.forEach(freeze);const model=await ready;await saveEvidence(location.search==='?boundary'?'boundary-model-ready.json':'model-ready.json',{...model,userAgent:navigator.userAgent,clock:'performance.timeOrigin+performance.now'});
 if(location.search==='?boundary'){
  const f=fixtures[0],t0=now(),q=await request({type:'search',generation:++generation,t0,T_ms:0,g_ms:25,limits:{maxSimulations:100000},id:f.id,legal_prefix:f.legal_prefix});
  await saveEvidence('boundary-zero.json',{...q,delivery:now(),expected:'timeout/no checkpoint/no NN',pass:q.error==='guard'&&q.stats?.nnCalls===0&&!q.action});
  const expiredEpoch=++generation,expired=await request({type:'search',generation:expiredEpoch,t0:now()-1000,T_ms:100,g_ms:25,limits:{maxSimulations:100000},id:f.id,legal_prefix:f.legal_prefix});
  await saveEvidence('boundary-expired.json',{...expired,expected:'expired input rejected before NN',pass:expired.error==='guard'&&expired.stats?.nnCalls===0&&!expired.action});
  let cancelAt=null,newJob=null,newGen=null;const old=++generation,begin=now();
  notify=x=>{if(x.generation!==old||cancelAt)return;cancelAt=now();newGen=++generation;w.postMessage({type:'cancel',generation:newGen});const n0=now();newJob=request({type:'search',generation:newGen,t0:n0,T_ms:500,g_ms:25,limits:{maxSimulations:100000},id:f.id,legal_prefix:f.legal_prefix}).then(y=>{const s=fromPrefix(f.legal_prefix),legal=!!y.action&&s.getLegalActions().some(a=>sameAction(a,y.action))&&rustAction(s,y.action)===y.actionRust209,delivery=now();return {...y,delivery,legal,accepted:y.generation===generation&&!y.error&&legal&&delivery<n0+500};});};
  const prev=await request({type:'search',generation:old,t0:begin,T_ms:1000,g_ms:25,limits:{maxSimulations:100000},id:f.id,legal_prefix:f.legal_prefix,notify:true});if(!newJob)throw Error('cancel-not-arrived');const next=await newJob;
  await saveEvidence('boundary-cancel.json',{cancelAt,old,newGen,previous:{...prev,rejected:prev.generation!==generation},next,cancelDuringNN:prev.stats?.nn?.some(x=>x.start<=cancelAt&&cancelAt<=x.end),pass:prev.generation!==generation&&next.accepted});
  w.terminate();return;
 }
 const numeric=[];for(const f of fixtures){numeric.push(await request({type:'numeric',generation:++generation,fixture:f}));await saveEvidence('numeric.outputs.json',numeric);if(numeric.at(-1).error)throw Error('numeric context failed '+f.id+': '+numeric.at(-1).error);}
 await saveEvidence('fallback.json',await request({type:'fallback_test',generation:++generation,fixture:fixtures[0]}));
 const timing=[];
 async function search(f,T,g,extra={}){const t0=now(),epoch=++generation;let q=await request({type:'search',generation:epoch,t0,T_ms:T,g_ms:g,seed:20261001,limits:{maxSimulations:100000},...(f.classification==='legal-replay'?{id:f.id,legal_prefix:f.legal_prefix}:{fixture:f}),...extra});let valid=false,validationError=null;
  if(q.action){try{const state=referenceState(f);valid=state.getLegalActions().some(a=>sameAction(a,q.action))&&rustAction(state,q.action)===q.actionRust209;}catch(e){validationError=e.message;}}
  const delivery=now(),late=delivery>=t0+T,stale=epoch!==generation;return {...q,T_ms:T,g_ms:g,delivery,elapsed_ms:delivery-t0,transport_ms:q.time?delivery-q.time.finish:null,overshoot_ms:Math.max(0,delivery-(t0+T)),valid,validationError,stale,late,accepted:!stale&&!late&&!q.error&&(q.terminal||valid),timeout:late||['deadline','guard','no_checkpoint'].includes(q.error)};
 }
 for(const id of ['initial-p1','asym-hv-p2','straight-jump-p2'])for(const T of [100,500,1000])for(let i=-1;i<5;i++){const q=await search(fixtures.find(f=>f.id===id),T,25);timing.push({...q,phase:i<0?'warmup':'sample',sample:i});await saveEvidence('timing.json',timing);}
 const terminal=[];for(const f of fixtures.filter(f=>f.terminal.effective_result!=='ongoing'))terminal.push(await search(f,500,25));await saveEvidence('terminal.json',terminal);
 const f=fixtures[0],t0=now(),old=++generation;let cancelAt=null,newRequest=null,newEpoch=null;
 notify=q=>{if(q.generation!==old||cancelAt)return;cancelAt=now();newEpoch=++generation;w.postMessage({type:'cancel',generation:newEpoch});const n0=now();newRequest=request({type:'search',generation:newEpoch,t0:n0,T_ms:1000,g_ms:25,seed:20261001,limits:{maxSimulations:100000},fixture:f}).then(x=>({...x,delivery:now(),t0:n0}));};
 const previous=await request({type:'search',generation:old,t0,T_ms:1000,g_ms:25,seed:20261001,limits:{maxSimulations:100000},fixture:f,notify:true});if(!newRequest)throw Error('cancel notification absent');const next=await newRequest;notify=null;
 await saveEvidence('cancel.json',{old,newEpoch,cancelAt,previous:{...previous,rejected:previous.generation!==generation},next,events:events.filter(x=>x.generation===old||x.generation===newEpoch),cancelDuringNN:previous.stats?.nn?.some(x=>x.start<=cancelAt&&cancelAt<=x.end),newQueueWait_ms:next.time?.workerStart-next.t0,remainingNNAfterCancel:previous.stats?.nn?.filter(x=>x.end>cancelAt).length,serialized:true});
 w.terminate();await saveEvidence('browser-summary.json',{numeric:numeric.length,timing:timing.length,terminal:terminal.length,workerTerminated:true,actualNNCalls:numeric.length+timing.reduce((n,x)=>n+(x.stats?.nnCalls||0),0)+terminal.reduce((n,x)=>n+(x.stats?.nnCalls||0),0)+(previous.stats?.nnCalls||0)+(next.stats?.nnCalls||0),fallback:0});
 });fs.writeFileSync(run+(process.argv.includes('--boundary')?'/boundary-network.json':'/network.json'),JSON.stringify(network,null,2)+'\n');console.log('DONE');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
