const fs=require('fs'),vm=require('vm'),cp=require('child_process');const D='research-data/ai-sigma/169-native-games-independent/',O='research-data/ai-sigma/165-native-baseline/',B='.artifacts/ai-sigma/resume-20261003/NATIVE-BASELINE/runs/';const read=p=>JSON.parse(fs.readFileSync(p)),eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b),check=(v,m)=>{if(!v)throw Error(m)};
const c=vm.createContext({Float32Array,Uint32Array,Uint8Array,Math,console});for(const n of ['game.js','context.js'])vm.runInContext(cp.execFileSync('git',['show','19275b3:tools/ai-sigma-native-baseline/'+n],{encoding:'utf8'}),c);vm.runInContext('globalThis.A={State,rustAction,actionToIndex,vertPolicyPermutation}',c);const A=c.A;
const out={source:'19275b3',new_NN:0,public:0,starts:0,startup:0,cleanup_by_engine_ms:{candidate:0,reference:0},pairs:[],root_teacher_mapping_checked:0,nearest_cutoff:null};let games={};
for(let pair=1;pair<=8;pair++){
 const dir=B+`native165-pair${String(pair).padStart(2,'0')}-r1/`,raw=read(dir+'result.json'),rows=fs.readFileSync(dir+'journal.jsonl','utf8').trim().split('\n').map(JSON.parse);check(eq(rows.map(r=>r.generation),rows.map((r,i)=>i+1)),'generation sequence');check(raw.hand_NN===rows.reduce((s,r)=>s+r.NN_calls,0)&&raw.startup_NN===2,'raw NN denominator');out.public+=rows.length;out.starts+=raw.hand_NN;out.startup+=2;
 for(const g of raw.games){games[g.game_id]=g;const r=rows.find(r=>r.game_id===g.game_id);check(eq(r.public_cp,g.firstRoot.publicCP)&&r.engine===g.firstRoot.engine&&r.NN_calls===g.firstRoot.NN_calls,'first root row');}
 for(const r of rows){out.cleanup_by_engine_ms[r.engine]+=r.cleanup_after_public_ms;const m=402-r.public_cp.admit_ms;if(!out.nearest_cutoff||m<out.nearest_cutoff.margin)out.nearest_cutoff={game:r.game_id,ply:r.ply,generation:r.generation,engine:r.engine,receive_ms:r.public_cp.receive_ms,prevalidation_stamp_ms:r.public_cp.admit_ms,margin:m,actual_end_unknown:true};}
 out.pairs.push({pair,NN:raw.hand_NN,startup:2,public:rows.length,CP_received:rows.reduce((s,r)=>s+r.CP_received,0),raw_bytes:fs.statSync(dir+'result.json').size});
}
for(const t of fs.readFileSync(O+'opening-teachers.jsonl','utf8').trim().split('\n').map(JSON.parse)){
 let s=new A.State({boardsize:9,walls_p1:10,walls_p2:10,walls_initial:10});for(const a of t.state.prefix)s=s.next(a);const perm=s.isPlayer1Turn()?null:A.vertPolicyPermutation(9);const map=Array.from(s.getLegalActions(),a=>{const ix=A.actionToIndex(a,9);return[A.rustAction(s,a),perm?perm[ix]:ix]}).sort((a,b)=>a[0]-b[0]);check(eq(map,t.mapping136),'independent RuleA vocabulary mapping');check(eq(Array.from(s.getLegalActions(),a=>A.rustAction(s,a)),t.legal_actions),'teacher legal order');
 const teacher=t.teacher,sign=s.isPlayer1Turn()?1:-1;check(teacher.root_nn_p1===teacher.root_nn_stm*sign&&teacher.rootmean_p1===teacher.rootmean_stm*sign,'p1 value orientation');out.root_teacher_mapping_checked++;
}
check(out.public===898&&out.starts===40378&&out.startup===16&&out.root_teacher_mapping_checked===16,'full denominators');fs.writeFileSync(D+'aux-result.json',JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out));
