import os,pathlib,json,subprocess,time,datetime,hashlib
os.sched_setaffinity(0,{0});R=pathlib.Path(__file__).resolve().parents[2];os.chdir(R);D=R/'research-data/ai-sigma/169-native-games-independent';T=R/'tools/ai-sigma-native-games-independent';REPORT=R/'docs/reports/ai-sigma-critic-native-games-independent.md';env={**os.environ,'BEADS_ACTOR':'codex:01a0f31d-8227-7e03-a7e6-915b4918c11b'};logs=[];begin=time.monotonic()
def call(a,extra=None):
 start=time.monotonic();p=subprocess.run(a,env={**env,**(extra or {})},capture_output=True,timeout=min(60,140-(time.monotonic()-begin)));rec={'command':a,'UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'elapsed_seconds':time.monotonic()-start,'exit':p.returncode,'stdout_bytes':len(p.stdout),'stdout_SHA256':hashlib.sha256(p.stdout).hexdigest(),'stderr':p.stderr.decode()[:2000]}
 if not any('beads.sh' in part for part in a):rec['stdout']=p.stdout.decode()[:2000]
 logs.append(rec);(D/'finalize-attempts.json').write_text(json.dumps(logs,indent=2)+'\n');assert p.returncode==0,rec;return p.stdout
call(['bash','scripts/dev/beads.sh','ready','--json']);compact=[]
for id in ['quoridor-4lc','quoridor-4lc.169']:
 x=json.loads(call(['bash','scripts/dev/beads.sh','show',id,'--json']))[0];assert x['status']=='in_progress' and 'paused-by-user' not in x.get('labels',[]);compact.append({k:x.get(k) for k in ['id','status','assignee','labels']})
assert compact[-1]['assignee']==env['BEADS_ACTOR'];(D/'final-admission.json').write_text(json.dumps({'UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'issues':compact,'pause':False,'owner_confirmed':True},indent=2)+'\n')
children=[]
for p in D.glob('*.process.json'):
 x=json.loads(p.read_text());assert x['wait_completed'] and x['exit']==0
 try:present=int(pathlib.Path(f"/proc/{x['PID']}/stat").read_text().rsplit(')',1)[1].split()[19])==int(x['start_ticks'])
 except FileNotFoundError:present=False
 assert not present;children.append({'run':x['run'],'PID':x['PID'],'start_ticks':x['start_ticks'],'exact_identity_current_absent':True,'exit':x['exit']})
(D/'source-stop.json').write_text(json.dumps({'UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'issue':'quoridor-4lc.169','source_edit_stopped':True,'static_children':children,'NN':0,'other_owner_signalled':False,'formal_ready':False,'management_persistence_only_remains':True,'manual_read_and_metadata_commands_prior_seconds_reserved':20,'checked_static_total_seconds':24.819637836975744},indent=2)+'\n')
ge={'GIT_INDEX_FILE':str(T/'private.index')};call(['git','read-tree','HEAD'],ge)
files=sorted([p for base in [D,T] for p in base.rglob('*') if p.is_file() and p.name not in ['private.index','private.index.lock','finalize-r1.log']]+[REPORT]);paths=[str(p.relative_to(R)) for p in files];call(['git','add','--',*paths],ge);call(['git','commit','-m','research: independently replay saved native games (169)'],ge);commit=call(['git','rev-parse','HEAD'],ge).decode().strip();restore=[]
for p in files:
 if p.name=='finalize-attempts.json':continue
 b=subprocess.check_output(['git','show',commit+':'+str(p.relative_to(R))],timeout=60);assert b==p.read_bytes();restore.append({'path':str(p.relative_to(R)),'SHA256':hashlib.sha256(b).hexdigest(),'Git_stream_equal':True})
(D/'git-restore.json').write_text(json.dumps({'data_commit':commit,'files':restore,'count':len(restore),'raw_not_copied':True},indent=2)+'\n')
call(['bash','scripts/dev/beads.sh','update','quoridor-4lc.169','--append-notes','169 self checker source/children stopped. Independent RuleA replay all16 planned/898 public legal GOAL, W6D0L10 mean.375; Xi=[0,.5,.5,0,.5,.5,1,0], same-board-side4/8, bothloss1/4/8 bothwin7. Initial16 roots648/137bits paired. Raw science stop9becd64/source19275b3/e6b42a3/f63e8b3 bound; StageA a09279c not replaced. Clock actualpublic<=500/nextt0 after zero-gate finite, pair1 actual receipt105 missing. end stamp BEFORE validation/clone/cache actual completion unknown; no proven violation/science replacement, formalreadyfalse. Reference cleanup35.927621sec/lateCP866733, recommends existing owner native cancellation/yield repair, no automatic second experiment. 16teachers8lineage pi/rootmean/z/side validated, no trainingready. Report docs/reports/ai-sigma-critic-native-games-independent.md dataGit '+commit+'. Coordinator acceptance/close pending. No new NN/game.'])
call(['bash','scripts/dev/beads.sh','backup','sync'])
size=sum(p.stat().st_blocks*512 for base in [D,T] for p in base.rglob('*') if p.is_file())+REPORT.stat().st_blocks*512;intake=json.loads((D/'intake.json').read_text());st=intake['storage'];total=st['old_conservative']+sum(st['prior_current'].values())+max(st['new_forecast'],size);assert size<st['new_forecast'] and total<st['guard']
summary={'issue':'quoridor-4lc.169','UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'data_commit':commit,'source_stopped':True,'children_stopped':True,'Git_stream_restore_count':len(restore),'Beadsnotes_exit':0,'backup_exit':0,'science_reexecution_NN':0,'formal_ready':False,'coordinator_acceptance_pending':True,'old_unknown_discount':0,'new_storage_current_allocated':size,'new_storage_forecast':st['new_forecast'],'current_plus_forecast':total,'storage_guard':st['guard'],'static_conservative_prior_seconds':24.819637836975744,'finalization_elapsed_seconds':time.monotonic()-begin,'commands_elapsed_seconds':sum(x['elapsed_seconds'] for x in logs),'all_scope_new_bytes_under_forecast':True}
(D/'handoff.json').write_text(json.dumps(summary,indent=2)+'\n');call(['git','add','--',str((D/'git-restore.json').relative_to(R)),str((D/'handoff.json').relative_to(R)),str((D/'finalize-attempts.json').relative_to(R))],ge);call(['git','commit','-m','research: save 169 stop restoration and backup handoff'],ge);h=call(['git','rev-parse','HEAD'],ge).decode().strip();matches=[]
for name in ['git-restore.json','handoff.json']:
 p=D/name;b=subprocess.check_output(['git','show',h+':'+str(p.relative_to(R))]);assert b==p.read_bytes();matches.append({'path':str(p.relative_to(R)),'SHA256':hashlib.sha256(b).hexdigest(),'equal':True})
(D/'handoff-stream-restore.json').write_text(json.dumps({'handoff_commit':h,'restored':matches},indent=2)+'\n');print(json.dumps({**summary,'handoff_commit':h}))
