'use strict';const fs=require('fs'),assert=require('assert'),{q,n,now}=require('./engine.cjs'),{Worker}=require('../ai-sigma-frame19-native-arena/protocol.cjs');
(async()=>{const c=JSON.parse(fs.readFileSync(process.argv[2])),manifest=JSON.parse(fs.readFileSync(c.openings)),ledger=manifest.slots.map(s=>({...s}));let NN=0,generation=0,globalHands=0;const begin=now(),w=new Worker(c.weight_manifest,__dirname+'/worker.cjs');const init=await w.take(3000);assert.equal(init.type,'READY');const ready=now(),hands=fs.createWriteStream(c.hands);const writeCounter=()=>fs.writeFileSync(c.counter_file,JSON.stringify({all_samples:NN,hands:globalHands})+'\n');writeCounter();
 for(const slot of ledger.filter(s=>c.slots.includes(s.slot))){const opening=manifest.openings.find(o=>o.id===slot.opening);let prefix=opening.prefix.map(a=>JSON.parse(JSON.stringify(a))),s=q.r.fromPrefix(prefix),fault=null;slot.status='STARTED';slot.startUTC=new Date().toISOString();slot.hands=0;
 while(true){const t=q.r.terminalResult(s);if(t){slot.status='TERMINAL';slot.winner=t.winner;slot.result_NNUE=t.winner===0?'D':t.winner===slot.NNUE_side?'W':'L';break}if(NN>=c.NNcap){fault={type:'GLOBAL_NN_CAP',category:'BUDGET_UNKNOWN'};break}
 const inputReady=now(),legal=s.getLegalActions(),engine=s.getCurrentPlayer()===slot.NNUE_side?'NNUE':'distance',id=c.run+':'+slot.slot+':'+(++generation);const req={kind:'SEARCH',id,generation,engine,prefix,key:s._positionKey(),history:n.history(s),node_cap:8192,maxdepth:64,ordering:'rootbest-first',NNcap:c.NNcap};
 let selected=null;const clock=await w.request(req,100,x=>{const r=x.search;const action=legal.find(a=>q.r.rustAction(s,a)===r.Action);const valid=r.status==='COMPLETED_ACTION'&&Number.isInteger(r.completed_depth)&&r.completed_depth>=1&&Number.isFinite(r.value)&&r.last_completed_only===true&&!!action&&r.parent_copy_key_history_restored===true;selected=valid?action:null;return{valid,completed_depth:r.completed_depth??null,legal:!!action,value_finite:Number.isFinite(r.value)}},inputReady);
 if(Number.isInteger(clock.response?.allNN))NN=clock.response.allNN;globalHands++;slot.hands++;writeCounter();hands.write(JSON.stringify({slot:slot.slot,ply:s.depth,side:s.getCurrentPlayer(),engine,generation,id,clock})+'\n');
 if(clock.status!=='RECEIVED'){fault={type:clock.status,cause_side:engine,category:['EOF','PROCESS_ERROR','SCHEMA_ERROR'].includes(clock.status)?'SHARED_HARNESS_UNKNOWN':'CLOCK_OR_ENGINE_UNKNOWN',elapsed_ms:clock.elapsed_ms};break}
 if(!clock.response?.validation?.valid){fault={type:clock.response?.search?.status??'INVALID_COMPLETED_ACTION',cause_side:engine,category:'ENGINE_UNKNOWN'};break}
 assert(selected);prefix.push(JSON.parse(JSON.stringify(selected)));s=s.next(selected);
 }
 if(fault){slot.status='UNKNOWN';slot.fault=fault;slot.last_prefix=prefix;slot.final_ply=s.depth;const stop=await w.stop(c.run+':stop:'+slot.slot);slot.stop=stop;if(Number.isInteger(stop.allNN))NN=stop.allNN;writeCounter();if(w.exit||stop.status!=='STOP_ACK'){for(const other of ledger.filter(a=>c.slots.includes(a.slot)&&a.status==='NOT_STARTED'))other.reason='SHARED_HARNESS_STOPPED';break}}
 slot.final_ply=s.depth;slot.endUTC=new Date().toISOString();slot.prefix=prefix;fs.writeFileSync(c.output,JSON.stringify({UTC:new Date().toISOString(),samples:NN,ledger,partial:true},null,2)+'\n');
 }
 const cleanup=await w.close();await new Promise(r=>hands.end(r));assert(cleanup.waited);const result={UTC:new Date().toISOString(),run:c.run,samples:NN,planned_all_slots:4,attempted_slots:c.slots,ledger,init_to_ready_ms:ready-begin,wholewall_ms:now()-begin,cleanup,clock_valid:ledger.filter(s=>c.slots.includes(s.slot)).every(s=>s.status==='TERMINAL'),WDL:ledger.reduce((a,s)=>{if(s.result_NNUE)a[s.result_NNUE]++;if(s.status==='UNKNOWN')a.unknown++;return a},{W:0,D:0,L:0,unknown:0}),strength_claim:false,formalNI:false,model_training:0,GPU:0};writeCounter();fs.writeFileSync(c.output,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({samples:NN,slots:c.slots,WDL:result.WDL,wholewall_ms:result.wholewall_ms,cleanup:cleanup.waited}));
})().catch(e=>{console.error(e);process.exit(1)});
