'use strict';const fs=require('fs'),assert=require('assert'),{n,q}=require('./engine.cjs'),leaf=require('./leaf.cjs');
const c=JSON.parse(fs.readFileSync(process.argv[2])),{w,m}=n.load(c.weight_manifest);let NN=0;const states=[],checks=[];
for(const f of q.fixtures()){states.push({id:f.id,state:f.state});const selected=f.state.getLegalActions().filter(a=>a.type==='pawn').concat(['h','v'].flatMap(o=>{const a=f.state.getLegalActions().find(a=>a.type==='wall'&&a.orientation===o);return a?[a]:[]}));selected.forEach((a,i)=>states.push({id:f.id+'/child'+i,state:f.state.next(a)}))}assert.equal(states.length,27);
let s=q.r.fromPrefix([]),rng=24019041;const step=()=>{rng^=rng<<13;rng^=rng>>>17;rng^=rng<<5;return(rng>>>0)/4294967296};for(let i=0;i<32;i++){if(q.r.terminalResult(s))s=q.r.fromPrefix([]);const legal=s.getLegalActions(),a=legal[Math.floor(step()*legal.length)];s=s.next(a);states.push({id:'legal-prefix-'+(i+1),state:s})}
function compare(id,s){const a=s.copy(),b=s.copy(),ka=a._positionKey(),ha=n.history(a),hb=n.history(b),stats={};const old=q.r.terminalResult(a),neo=leaf.terminal(b,stats);assert.deepStrictEqual(neo,old,id);assert.equal(a._positionKey(),ka);assert.equal(n.history(a),ha);assert.equal(n.history(b),hb);let dExact=null,outExact=null,parentBuffer=null;if(!old){const d=n.distance(a,m),e=leaf.distanceKnownNonterminal(b,m);assert.equal(Object.is(d,e),true,id+' Dbits');dExact=true;const acc=q.full(a,w),bytes=acc.a.map(z=>Buffer.from(z.buffer).toString('hex')),v=n.valueScaled(acc,w,m);NN++;leaf.terminal(a,{});const v2=n.valueScaled(acc,w,m);NN++;assert(Object.is(v,v2));assert.deepStrictEqual(acc.a.map(z=>Buffer.from(z.buffer).toString('hex')),bytes);outExact=true;parentBuffer=true}checks.push({id,terminal:old,stats,D_f32_bitexact:dExact,NNUE_same_input_bitexact:outExact,parent_key_history_unchanged:true,parent_buffer_unchanged:parentBuffer})}
for(const x of states)compare(x.id,x.state);
for(const side of[1,2]){const a=q.r.fromPrefix([]).copy();a.depth=side-1;if(side===1)a.player1pos=[4,8];else a.player2pos=[4,0];a._getLegalPawnActions=()=>{throw Error('TERMINAL_FIRST_PAWN_CALLED')};compare('goal-side'+side,a)}
const draw=q.r.fromPrefix([]).copy();draw.depth=200;draw._getLegalPawnActions=()=>{throw Error('DRAW_FIRST_PAWN_CALLED')};compare('draw-200',draw);
const blocked=q.r.fromPrefix([]);for(const a of blocked._getLegalPawnActions())blocked.position_history.set(blocked.next(a)._positionKey(),2);const withwalls=blocked.copy();assert.equal(withwalls._getLegalPawnActions().length,0);assert(withwalls.getLegalActions().some(a=>a.type==='wall'));compare('synthetic-history-no-pawn-wall-fallback',withwalls);const nolegal=blocked.copy();nolegal.walls_p1=0;assert.equal(nolegal._getLegalPawnActions().length,0);assert.equal(nolegal.getLegalActions().length,0);compare('synthetic-history-no-pawn-no-wall-draw',nolegal);
assert(NN<c.NNcap);fs.writeFileSync(c.counter_file,JSON.stringify({all_samples:NN})+'\n');fs.writeFileSync(c.fixture_output,JSON.stringify({UTC:new Date().toISOString(),PASS:true,samples:NN,tol:{abs:1e-5,rtol:1e-4},fixture27:27,legalprefix32:32,checks,newTorch:0,newGPU:0,synthetic_history_not_dataset:true},null,2)+'\n');console.log(JSON.stringify({fixturePASS:true,checks:checks.length,samples:NN}));
