use ai_sigma_inference_release::{Model,MODEL_SHA,SCHEMA};
use std::{time::Instant,fs};
fn main()->Result<(),Box<dyn std::error::Error>>{
 let a=std::env::args().collect::<Vec<_>>();let bytes=fs::read(&a[1])?;let t=Instant::now();let m=Model::load_verified(&bytes,MODEL_SHA,SCHEMA)?;let load_ms=t.elapsed().as_secs_f64()*1000.;let inputs:serde_json::Value=serde_json::from_slice(&fs::read(&a[2])?)?;let mut out=Vec::new();let mut timing=Vec::new();
 for f in inputs.as_array().unwrap(){let ft=Instant::now();let features=f["features"].as_array().unwrap().iter().map(|x|x.as_f64().unwrap() as f32).collect::<Vec<_>>();let feature_ms=ft.elapsed().as_secs_f64()*1000.;let start=Instant::now();let v=m.infer(&features)?;out.push(serde_json::json!({"id":f["id"],"policy_logits":v.policy.to_vec(),"value":v.value}));let cold_ms=start.elapsed().as_secs_f64()*1000.;if ["initial-p1","asym-hv-p2","straight-jump-p2"].contains(&f["id"].as_str().unwrap()){m.infer(&features)?;let mut samples=Vec::new();for _ in 0..10{let x=Instant::now();m.infer(&features)?;samples.push(x.elapsed().as_secs_f64()*1000.)}timing.push(serde_json::json!({"id":f["id"],"feature_ms":feature_ms,"cold_ms":cold_ms,"samples_ms":samples}));}}
 let errors=serde_json::json!({"hash_mismatch":Model::load_verified(&bytes,"bad",SCHEMA).err().unwrap().code,"schema_mismatch":Model::load_verified(&bytes,MODEL_SHA,"bad").err().unwrap().code,"broken_short_model":Model::load_verified(b"broken",MODEL_SHA,SCHEMA).err().unwrap().code,"short_features":m.infer(&[0.;647]).err().unwrap().code,"nan_features":m.infer(&[f32::NAN;648]).err().unwrap().code});
 let features=inputs[0]["features"].as_array().unwrap().iter().map(|v|v.as_f64().unwrap()as f32).collect::<Vec<_>>();for _ in 0..100{m.infer(&features)?;}drop(m);for _ in 0..3{let model=Model::load_verified(&bytes,MODEL_SHA,SCHEMA)?;model.infer(&features)?;drop(model);}
 fs::write(&a[3],serde_json::to_vec(&out)?)?;fs::write(&a[4],serde_json::to_vec_pretty(&serde_json::json!({"load_ms":load_ms,"timing":timing,"errors":errors,"inference_repeat":100,"reload_drop":3,"hash_verified_by_host_runner":true}))?)?;Ok(())
}
