'use strict';const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert'),zlib=require('zlib'),{performance}=require('perf_hooks'),{target,validate}=require('./schema.cjs'),{r}=require('../ai-sigma-native-baseline/reference.cjs').createReference();
const ROOT=path.resolve(__dirname,'../..'),D=ROOT+'/research-data/ai-sigma/187-manygame-generation',A=ROOT+'/.artifacts/ai-sigma/resume-20261003/MANYGAME-GENERATION',specs=JSON.parse(fs.readFileSync(D+'/openings.json')).games,cfg=JSON.parse(fs.readFileSync(D+'/preregister.json')),start=performance.now(),summary=[];
const read=p=>fs.existsSync(p)?JSON.parse(fs.readFileSync(p)):null,lines=p=>fs.existsSync(p)?fs.readFileSync(p,'utf8').trim().split('\n').filter(Boolean).map(JSON.parse):[],save=(n,x)=>fs.writeFileSync(D+'/'+n,JSON.stringify(x,null,2)+'\n');
for(const m of cfg.modes){const run='native187-'+m.mode.toLowerCase()+'-r1',out=A+'/'+run,proc=read(out+'/process.json'),raw=[],finals=[],overlap={position:new Map,fullstate:new Map,features:new Map,features_legal:new Map};
 if(proc)assert.equal(proc.remaining.length,0,'CHILD_NOT_STOPPED');for(const core of [2,4,6]){raw.push(...lines(out+'/core'+core+'/raw-rows.jsonl'));finals.push(...lines(out+'/core'+core+'/games.jsonl'));}const games=specs.map(s=>finals.find(g=>g.game_id===s.game_id)??{game_id:s.game_id,family:s.family,split:s.split,status:proc?'REGISTERED_UNFINISHED_UNKNOWN':'NOT_STARTED',reason:proc?.stop_reason??'NOT_ADMITTED_YET',winner:null,rows:raw.filter(x=>x.game_id===s.game_id).length}),eligible=[];
 for(const game of games){const spec=specs.find(s=>s.game_id===game.game_id);if(!spec.generated)continue;let state=r.fromPrefix(spec.opening.legal_prefix);const rows=raw.filter(x=>x.game_id===spec.game_id).sort((a,b)=>a.ply-b.ply);for(const row of rows){assert.equal(row.family,spec.family);assert.equal(row.split,spec.split);assert.equal(row.state_key,state._positionKey());assert.equal(row.side,state.getCurrentPlayer());assert.equal(row.ply,state.depth);assert.equal(JSON.stringify(row.features648_bits),JSON.stringify(r.portState(state).features_bits));assert.equal(JSON.stringify(row.legal_order209),JSON.stringify(r.portState(state).legal));assert.equal(JSON.stringify(row.history_counts),JSON.stringify(Array.from(state.position_history)));target(row,game.winner??null);validate(row,64);row.policy_eligible=true;row.joint_eligible=row.value_eligible;row.legal_mask136=Array(136).fill(0);for(const [a,k]of row.mapping136)row.legal_mask136[k]=1;
 const full=JSON.stringify({position:row.state_key,side:row.side,ply:row.ply,history:[...row.history_counts].sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:0)}),feat=JSON.stringify(row.features648_bits),fl=JSON.stringify({features:row.features648_bits,legalMask:row.legal_mask136});for(const[k,v]of [['position',row.state_key],['fullstate',full],['features',feat],['features_legal',fl]]){const map=overlap[k];if(!map.has(v))map.set(v,[]);map.get(v).push({game:row.game_id,split:row.split,family:row.family});}eligible.push(row);const action=state.getLegalActions().find(a=>r.rustAction(state,a)===row.action209);assert(action,'ACTION_REPLAY');state=state.next(action);}
 if(['GOAL','DRAW200','DRAW_NOLEGAL'].includes(game.status)){const terminal=r.terminalResult(state);assert(terminal&&terminal.winner===game.winner,'TERMINAL_REPLAY');}}
 function overlaps(map){const cross=[...map.values()].filter(x=>new Set(x.map(r=>r.game)).size>1),tv=cross.filter(x=>new Set(x.map(r=>r.split)).size>1);return{unique:map.size,crossgame_shared_keys:cross.length,crossgame_row_occurrences:cross.reduce((s,x)=>s+x.length,0),train_val_shared_keys:tv.length,train_val_row_occurrences:tv.reduce((s,x)=>s+x.length,0),independent_state_holdout:false};}
 const Rpolicy=eligible.length,Rz=eligible.filter(x=>x.value_eligible).length,Rjoint=eligible.filter(x=>x.joint_eligible).length,wall=proc?.jobwall_seconds??null;
 fs.writeFileSync(D+'/'+m.mode+'-teacher-rows.jsonl.gz',zlib.gzipSync(eligible.map(x=>JSON.stringify(x)).join('\n')+'\n'));save(m.mode+'-all-status.json',games);const broker=read(out+'/broker.json'),result=read(out+'/result.json');const x={mode:m.mode,run,planned24:24,status_counts:Object.fromEntries([...new Set(games.map(g=>g.status))].map(s=>[s,games.filter(g=>g.status===s).length])),Rpolicy,Rz,Rjoint,value_unknown_rows:Rpolicy-Rz,value_loss_unknown_mask:0,allattempt_jobwall_s:wall,rates_per_all_jobwall:wall?{Rpolicy:Rpolicy/wall,Rz:Rz/wall,Rjoint:Rjoint/wall,games:games.filter(g=>['GOAL','DRAW200','DRAW_NOLEGAL'].includes(g.status)).length/wall}:null,raw_saved_rows:raw.length,all24_ply_distribution:games.map(g=>({game_id:g.game_id,status:g.status,total_ply:g.plies??null,new_rows:g.rows??0,terminal:["GOAL","DRAW200","DRAW_NOLEGAL"].includes(g.status),censored:g.winner==null})),NN_calls_actual:result?.NN??null,NN_completed_on_eligible_rows:eligible.reduce((s,r)=>s+r.NN_completed,0),terminal_noNN:eligible.reduce((s,r)=>s+r.terminal_noNN,0),startup_NN:result?.startup_NN??null,batches:broker?.stats??null,providerCost:broker?.providerCost??null,RAM_peak_sampled:proc?.peak_aggregate_RSS??null,VRAM_peak_reserved:result?.providerStop?.GPU_peak_reserved_B??null,overlaps:Object.fromEntries(Object.entries(overlap).map(([k,v])=>[k,overlaps(v)])),train_policy:eligible.filter(x=>x.split==='train').length,val_policy:eligible.filter(x=>x.split==='validation').length,attempt_status:proc?{exit:proc.exit,stop_reason:proc.stop_reason}:null,model_teacher_truth_or_NI:false,old173_teacher:0,mixed_into_learner:false,datasetSHA:crypto.createHash('sha256').update(fs.readFileSync(D+'/'+m.mode+'-teacher-rows.jsonl.gz')).digest('hex')};summary.push(x);save(m.mode+'-summary.json',x);}
const attempts=fs.readdirSync(A).filter(x=>fs.existsSync(A+'/'+x+'/process.json')).map(x=>read(A+'/'+x+'/process.json'));save('comparison-summary.json',{issue:'quoridor-4lc.187',modes:summary,allattempt_job_seconds:attempts.reduce((s,p)=>s+p.jobwall_seconds,0),attempts:attempts.map(x=>({run:x.run,kind:x.kind,jobwall:x.jobwall_seconds,exit:x.exit,reason:x.stop_reason})),export_wall_s:(performance.now()-start)/1000,small_single_run_order_host_confounding:true,mode_siblings_samefamily:true,teacher_truth_or_chess_strength_not_proved:true,partial_rows_value_unknown_maskfalse:true});console.log(JSON.stringify(summary.map(x=>({mode:x.mode,Rjoint:x.Rjoint,wall:x.allattempt_jobwall_s,status:x.status_counts}))));
