'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),{fork}=require('child_process'),{performance}=require('perf_hooks');
const {Pipe}=require('./pipe.cjs'),{Broker}=require('./broker.cjs'),{GamePool,ArtificialRegistry}=require('./gamepool.cjs'),{record}=require('./teacher-interface.cjs');
const out=process.argv[2];const save=(n,v)=>fs.writeFileSync(path.join(out,n),JSON.stringify(v,null,2)+'\n');let consumed=0;const receipts=[],children=[];const features=()=>Array(648).fill(0);
const identity=(game,seq=1)=>({run_id:'native185-mock',worker_id:'w0',game_id:game,generation:1,handle:seq,token:seq,request_id:'r'+seq});
function create({delay=0,inject=null,cap=384}={}){const pipe=new Pipe(process.execPath,['--max-old-space-size=192',__dirname+'/fake-provider.cjs',String(cap)]);children.push(pipe.child.pid);let n=0;const broker=new Broker(async items=>{const request_id='batch.'+(++n),q={op:'infer_batch',request_id,items,backend:'cuda',delay_ms:delay,inject};const z=await pipe.ask(q);consumed+=items.length;if(z.request_id!==request_id||!z.ok)throw Error(z.error?.message??'PROVIDER_REQUEST_ID');return z.result.items},{replyCap:cap});return{pipe,broker,async close(){broker.stop();await broker.quiescent();const z=await pipe.ask({op:'stop',request_id:'stop'});assert(z.ok);const exit=await pipe.close();assert.equal(exit.code,0);receipts.push({stats:broker.stats,zero:broker.zero(),provider:z.result,exit});}};}
async function forks(ctx,count,maxHandles,run){const workers=[],results=[];for(let n=0;n<count;n++){const w=fork(__dirname+'/mock-worker.cjs',[String(n+1),String(maxHandles),run],{execArgv:['--max-old-space-size=192'],stdio:['ignore','ignore','pipe','ipc']});children.push(w.pid);const exit=new Promise(resolve=>w.once('exit',(code,signal)=>resolve({code,signal,pid:w.pid})));let finish;const done=new Promise(resolve=>finish=resolve);w.on('message',q=>{if(q.kind==='infer'){ctx.broker.infer(q.identity,q.features_bits648).then(data=>w.send({kind:'reply',request_id:q.identity.request_id,data}),e=>w.send({kind:'reply',request_id:q.identity.request_id,error:e.message}));}else if(q.kind==='cancel')ctx.broker.cancel(q.worker,q.game,q.generation,q.run);else if(q.kind==='wait_game')void ctx.broker.quiescentGame(q.worker,q.game,q.run).then(()=>w.send({kind:'drained',id:q.id}));else if(q.kind==='result'){results.push(q);finish()}else if(q.kind==='fatal')finish(q);} );workers.push({w,exit,done});w.send({kind:'run',games:Array.from({length:maxHandles},(_,i)=>'g'+(i+1))});}
 for(const w of workers){const error=await w.done;assert(!error,error?.error);}await ctx.broker.quiescent();for(const w of workers){w.w.send({kind:'close'});const e=await w.exit;assert.equal(e.code,0);}for(const x of results){assert.deepEqual(x.zero,{handles:0,pending:0,waits:0,active:0});assert.equal(x.resumes,maxHandles*4);assert(x.results.every(r=>r.status==='MOCK_OR_TAPE_COMPLETE'));}return results;
}
(async()=>{const t=performance.now(),cases=[],main=create();
 // Start cheaply with one artificial worker and three games.
 const registry=new ArtificialRegistry(),pool=new GamePool('w0',registry,main.broker,{maxHandles:4});const first=await Promise.all(['a','b','c'].map(x=>pool.search(x,{K:4})));assert(first.every(r=>r.cp.root_visits===4));assert.equal(registry.trees.size,0);cases.push({case:'one_worker_three_games',results:first});
 const partialSizes=[];for(let B=1;B<=8;B++){const p=Array.from({length:B},(_,i)=>main.broker.infer(identity('partial'+B+'_'+i,100+B*8+i),features()));await Promise.all(p);assert.equal(main.broker.stats.batches.at(-1).size,B);partialSizes.push(B);}cases.push({case:'partial_B1_to_B8',actual_sizes:partialSizes,real_GPU_shape_parity:'UNMEASURED_3_5_6_7'});
 await assert.rejects(async()=>{const p=main.broker.infer(identity('dup',500),features());p.catch(()=>{});await main.broker.infer(identity('dup',501),features());},/ONE_PENDING_PER_GAME/);await main.broker.quiescent();
 const twelve=await forks(main,3,4,'native185-artificial12'),twentyfour=await forks(main,3,8,'native185-artificial24');cases.push({case:'three_workers_four_handles',workers:twelve});cases.push({case:'three_workers_eight_handles',workers:twentyfour});await main.close();
 // In-flight cancellation retains the same-game owner until its provider reply is discarded.
 const late=create({delay:15}),lr=new ArtificialRegistry(),lp=new GamePool('w0',lr,late.broker,{maxHandles:4});const search=lp.search('cancel',{K:4});while(!late.broker.inflight)await new Promise(resolve=>setImmediate(resolve));const ack=lp.cancel('cancel',1);assert(ack.inflight);await assert.rejects(()=>late.broker.infer(identity('cancel',2),features()),/ONE_PENDING_PER_GAME/);const cancelled=await search;assert.equal(lr.resumes.length,0);assert.equal(cancelled.counters.discarded,1);assert.equal(lr.trees.size,0);await late.close();cases.push({case:'pending_cancel_and_samegame_reuse_denied',ack,result:cancelled});
 const queued=create(),qp=queued.broker.infer(identity('queued'),features());const qr=qp.catch(e=>e.message);queued.broker.cancel('w0','queued',1,'native185-mock');assert.equal(await qr,'CANCEL_QUEUED');await queued.close();cases.push({case:'queued_cancel',started:queued.broker.stats.started});
 const simultaneous=create({delay:10});const promises=Array.from({length:12},(_,i)=>simultaneous.broker.infer(identity('stop'+i,i+1),features()).then(()=> 'BAD',e=>e.message));while(!simultaneous.broker.inflight)await new Promise(resolve=>setImmediate(resolve));simultaneous.broker.stop();const stopped=await Promise.all(promises);await simultaneous.broker.quiescent();assert(stopped.every(s=>s==='CANCEL_RETURN_DISCARDED'||s==='STOPPED_QUEUED'));await simultaneous.close();cases.push({case:'simultaneous_stop_12_all_planned',statuses:stopped});
 for(const inject of ['swap','unknown','fault','nan']){const bad=create({inject});const pending=Array.from({length:12},(_,i)=>bad.broker.infer(identity(inject+i,i+1),features()).then(()=> 'BAD',e=>e.message));const statuses=await Promise.all(pending);await bad.broker.quiescent();assert(statuses.every(x=>x.startsWith('PROVIDER_OR_CONTROL_UNKNOWN')));await assert.rejects(()=>bad.broker.infer(identity('afterfault'),features()));await bad.close();cases.push({case:'all_impact_'+inject,planned:12,statuses,zero:bad.broker.zero()});}
 // Receiving a valid-looking result with a different token must not resume any tree.
 const wrongRegistry=new ArtificialRegistry(),wrongPool=new GamePool('w0',wrongRegistry,{infer:async(id,bits)=>({identity:{...id,token:id.token+1},NN:{logits:Array(136).fill(0),value:0}}),cancel:()=>{},quiescentGame:async()=>{}},{maxHandles:4});const wrong=await wrongPool.search('wrongtoken',{K:1});assert.equal(wrong.typed,'GENERATION_HANDLE_TOKEN_ATTRIBUTION');assert.equal(wrongRegistry.resumes.length,0);cases.push({case:'stale_token_return',result:wrong});
 const endings=create(),endRegistry=new ArtificialRegistry(),endPool=new GamePool('w0',endRegistry,endings.broker,{maxHandles:4});const K1=await endPool.search('K1',{K:1}),terminal=await endPool.search('terminal',{K:1,fixture:{terminal:true}});for(const r of [K1,terminal]){const row=record(r,{lineage:'native185-NN0-'+r.game_id});assert.equal(row.pi136,null);assert.equal(row.z_stm,null);assert(!row.joint_eligible&&!row.policy_eligible);}assert.equal(terminal.counters.started,0);await endings.close();cases.push({case:'K1_rootterminal_teacher_ineligible',K1,terminal});
 assert(consumed<=384);save('result.json',{issue:'quoridor-4lc.185',NN:0,model_sessions:0,GPU:0,mock_reply_equivalents:consumed,cap:384,cases,receipts,owned_child_PIDs:children,wall_seconds:(performance.now()-t)/1000,teacher_rows_for_training:0});console.log(JSON.stringify({passed:cases.length,mock_replies:consumed,NN:0,children:children.length}));})().catch(e=>{save('failure.json',{error:e.stack,consumed,children,NN:0});console.error(e.stack);process.exitCode=1;});
