'use strict';
const fs=require('fs'),path=require('path'),CP=require('child_process'),{createRequire}=require('module'),{OwnedProcesses,boundedStop}=require('../ai-sigma-actual-boundary-repair/cleanup.cjs');const{script,bindings}=require('../ai-sigma-local-move-quality/adapters.cjs');const{chromium}=createRequire('/workspaces/quoridor/package.json')('playwright');
const ROOT=path.resolve(__dirname,'../..'),O=ROOT+'/.artifacts/ai-sigma/resume-20261002/LOCAL-MOVE-INDEPENDENT';
async function main(){const cfg=JSON.parse(fs.readFileSync(process.argv[3]));if(cfg.issue!=='quoridor-4lc.135'||Date.now()>=Date.parse(cfg.newjob_deadline))throw Error('CONTRACT_CUTOFF');const dir=O+'/runs/'+cfg.run_id;fs.mkdirSync(dir,{recursive:false});const save=(n,x)=>fs.writeFileSync(dir+'/'+n+'.json',JSON.stringify(x,null,2)+'\n');const owner=new OwnedProcesses({tracePath:dir+'/cleanup.jsonl'}),original=CP.spawn;let browser,primary,secondary=[];const monitor=require('../ai-sigma-actual-boundary-repair/pause-check.cjs').createMonitor({out:dir,subjectIssue:'quoridor-4lc.135',deadlineUTC:cfg.processing_deadline,windowEndUTC:'2026-10-02T23:20:59Z'});
 try{await monitor.start();monitor.check();CP.spawn=(...args)=>owner.observeChild(original(...args));try{browser=await chromium.launch({headless:true,executablePath:'/workspaces/quoridor/artifacts/playwright/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--disable-software-rasterizer','--use-gl=disabled','--renderer-process-limit=1']});}finally{CP.spawn=original;}
 const routes={'/game.js':'tools/ai-sigma-actual-boundary-repair/game.js','/context.js':'tools/ai-sigma-actual-boundary-repair/context.js','/shared.js':'tools/ai-sigma-cp-frame/shared-best-action.cjs','/numeric.js':'tools/ai-sigma-local-move-independent/numeric.js','/checker.js':'tools/ai-sigma-local-move-independent/checker.js','/numeric-base.js':'tools/ai-sigma-cp-frame/numeric-browser.js'};const ctx=await browser.newContext(),network=[];await ctx.route('**/*',async r=>{const u=new URL(r.request().url());network.push(u.pathname);if(u.origin!=='http://localhost:5194')return r.abort();const h={'Cross-Origin-Opener-Policy':'same-origin','Cross-Origin-Embedder-Policy':'require-corp','Cross-Origin-Resource-Policy':'same-origin'};if(u.pathname==='/')return r.fulfill({headers:h,contentType:'text/html',body:'<script src="/game.js"></script><script src="/context.js"></script><script src="/shared.js"></script><script src="/numeric-base.js"></script><script src="/main.js"></script><script src="/numeric.js"></script><script src="/checkpoint.js"></script><script src="/cache.js"></script><script src="/checker.js"></script>'});if(u.pathname==='/checkpoint.js'||u.pathname==='/cache.js')return r.fulfill({headers:h,contentType:'text/javascript',body:script(u.pathname==='/checkpoint.js'?'checkpoint':'cache')});if(u.pathname==='/main.js')return r.fulfill({headers:h,contentType:'text/javascript',body:script('main')});if(!routes[u.pathname])return r.abort();return r.fulfill({headers:h,contentType:'text/javascript',body:fs.readFileSync(ROOT+'/'+routes[u.pathname])});});const page=await ctx.newPage();page.on('pageerror',e=>save('page-error',{message:e.message}));await page.goto('http://localhost:5194/');
 save('source-bindings',bindings());save('independent-typed',await page.evaluate(()=>typed135()));const text=fs.readFileSync(O+'/saved-input.json','utf8');save('all-independent',await page.evaluate(text=>audit135(JSON.parse(text)),text));
 save('browser-summary',{version:browser.version(),network,NN:0,model_load:0,Worker_created:0,Node_game_referee:0,compact_four_group_JSON_text:true});
 }catch(e){primary={message:e.message,stack:e.stack};save('primary',primary);}finally{try{save('browser-stop',await boundedStop({owner,stop:async()=>{if(browser)await browser.close();return {remaining_pids:0,Model_load:0,searches_started:0};}}));}catch(e){secondary.push({stage:'owned-stop',message:e.message});}try{save('pause-monitor-stop',await monitor.stop());}catch(e){secondary.push({stage:'monitor-stop',message:e.message});}save('finally',{primary,secondary,NN:0,model_load:0});}if(primary||secondary.length)process.exitCode=1;
}
main().catch(e=>{console.error(e.stack);process.exitCode=1});
