'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert/strict'),{spawn}=require('child_process');const R=path.resolve(__dirname,'../..'),P=R+'/.artifacts/ai-sigma/runs/SIGMA-ORT-ENTRY-FINAL',D=P+'/diagnostic',E=require('./match-entry.cjs'),{OwnedProcesses,boundedStop}=require('./cleanup.cjs'),{pipe}=require('./pipe.cjs');fs.mkdirSync(D,{recursive:true});const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),write=(p,v)=>fs.writeFileSync(p,JSON.stringify(v));let starts=0;const checks=[];
const mp=D+'/entry-final-manifest.json';write(mp,{entry_mock_complete:true,mock_only:true,checks:[{path:__dirname+'/match-entry.cjs',sha256:sha(__dirname+'/match-entry.cjs')}]});fs.writeFileSync(D+'/critic-mock.txt','mock-only .31 no actual acceptance');const ap=D+'/acceptance.json';write(ap,{issue:'quoridor-4lc.31',accepted:true,mock_only:true,entry_manifest_sha256:sha(mp)});process.env.SIGMA_MATCH_FREEZE_TOKEN=crypto.randomBytes(16).toString('hex');let token={issue:'quoridor-4lc.33',actual_run:true,critic_accepted:true,coordinator_thread:'01a0f31b-3409-75f2-a30e-453a50484f94',critic_issue:'quoridor-4lc.31',freeze_token:process.env.SIGMA_MATCH_FREEZE_TOKEN,preregister_sha256:sha(P+'/preregister.json'),entry_manifest_sha256:sha(mp),T_ms:500,g_ms:91,processing_stop_utc:'2026-10-01T03:55:00Z',global_stop_utc:'2026-10-01T04:00:00Z',critic_report_path:D+'/critic-mock.txt',critic_report_sha256:sha(D+'/critic-mock.txt'),acceptance_path:ap,acceptance_sha256:sha(ap),run_id:'POSITIVE-MOCK',mock_only:true};const tp=D+'/token.json';write(tp,token);
const factory=async()=>{starts++;return {startup:'mock',clock:{mock:true},stop:async()=>({remaining_pids:0,mock:true}),needsRestart:()=>false,play:async({candidateColor})=>({complete:true,score:candidateColor===1?1:0,mock:true})}};
(async()=>{
 const result=await E.diagnosticMockMain({argv:['--run',tp],createBackend:factory});assert.equal(result.completed,20);assert.equal(result.dry,true);checks.push('same main positive20 mock');assert.equal(starts,1);
 await assert.rejects(E.diagnosticMockMain({argv:['--run',tp],createBackend:factory}),/RUN_ALREADY_EXISTS/);assert.equal(starts,1);checks.push('existing run rejects before factory');
 await assert.rejects(E.diagnosticMockMain({argv:[],createBackend:factory}),/USAGE/);for(const change of [{issue:'quoridor-4lc.32'},{preregister_sha256:'0'.repeat(64)},{entry_manifest_sha256:'0'.repeat(64)},{critic_issue:'quoridor-4lc.30'}]){write(tp,{...token,...change,run_id:'REJECT'});await assert.rejects(E.diagnosticMockMain({argv:['--run',tp],createBackend:factory}));assert.equal(starts,1)}checks.push('missing old foreign hash reject no engine');assert.throws(()=>E.verifyToken(token,P+'/preregister.json',mp));checks.push('mock manifest forbidden actual verifier');
 const owner=new OwnedProcesses(),child=owner.register(spawn(process.execPath,['-e','process.on("SIGTERM",()=>{});console.log("ready");setInterval(()=>{},1000)'],{stdio:['ignore','pipe','ignore'],detached:true}));await new Promise(r=>child.stdout.once('data',r));const backend={owner,stop:()=>new Promise(()=>{})};const a=await boundedStop(backend);assert.equal(a.remaining_pids,0);assert.equal(await boundedStop(backend),a);assert.equal(child.signalCode,'SIGKILL');checks.push('detached owned pending cleanup TERM KILL wait PID0 idempotent');
 const c=pipe(process.execPath,['-e','setInterval(()=>{},1000)'],D+'/pipe.stderr');await c.abort();await c.abort();await c.close();assert(c.child.signalCode);checks.push('already signalled abort close idempotent');
 const bad={owner:{scan:()=>[{pid:-1}],signal:()=>{throw Error('KILL_FAILED')},finish:()=>{}},stop:()=>new Promise(()=>{})};await assert.rejects(boundedStop(bad),/KILL_FAILED/);checks.push('cleanup failure refuses fresh');
 const owner2=new OwnedProcesses(),c2=owner2.register(spawn(process.execPath,['-e','setInterval(()=>{},1000)'],{stdio:'ignore'}));let fresh=0;await boundedStop({owner:owner2,stop:()=>new Promise(()=>{})});assert.equal(owner2.scan().length,0);fresh++;assert.equal(fresh,1);checks.push('fresh only after PID0');
 fs.unlinkSync(tp);delete process.env.SIGMA_MATCH_FREEZE_TOKEN;write(P+'/final-gate.json',{mock_only:true,checks,starts,entry_positive_complete:true,dummy_PID0:true,NN_browser_build_games:0,actual_go:false});console.log(JSON.stringify({checks:checks.length,actual_go:false}));
})().catch(e=>{console.error(e);process.exitCode=1});
