'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{createRequire}=require('module');const {chromium}=createRequire('/workspaces/quoridor/package.json')('playwright');
const ROOT=path.resolve(__dirname),BASE=path.resolve(ROOT,'../..'),RUN=path.join(BASE,'.artifacts/ai-sigma/runs/SIGMA-ORT-SEARCH'),CACHE='/home/vscode/.cache/inference/research/ai-sigma/ort-search',OLD=path.join(BASE,'.artifacts/ai-sigma/runs/SIGMA-NN-SEARCH'),REF=path.join(BASE,'.artifacts/ai-sigma/reference/SIGMA-WEB-REFERENCE');
const mode=process.argv[2]||'numeric',tag=process.argv[3]||'';
async function main(){const browser=await chromium.launch({headless:true,executablePath:'/workspaces/quoridor/artifacts/playwright/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--disable-software-rasterizer','--use-gl=disabled']});try{
 const context=await browser.newContext();const routes={'/':'<!doctype html><title>ORT search research</title>','/game.js':fs.readFileSync(path.join(REF,'game.js')),'/context.js':fs.readFileSync(path.join(BASE,'tools/ai-sigma-arena-matches/context.js')),'/worker.js':fs.readFileSync(path.join(ROOT,'worker.js')),'/host.js':fs.readFileSync(path.join(ROOT,'host.js')),'/a-host.js':fs.readFileSync(path.join(BASE,'tools/ai-sigma-nn-search/host.js'),'utf8').replace("fetch('/search.wasm')","fetch('/a.wasm')"),'/a.wasm':fs.readFileSync(path.join(OLD,'final.wasm')),'/b.wasm':fs.readFileSync(CACHE+'/target/wasm32-unknown-unknown/release/ai_sigma_ort_search.wasm'),'/model.onnx':fs.readFileSync(path.join(BASE,'models/experiments/ai-sigma/reference/sigma-pcr250/best.onnx'))};for(const f of['ort.min.js','ort-wasm-simd-threaded.jsep.mjs','ort-wasm-simd-threaded.jsep.wasm'])routes['/ort/'+f]=fs.readFileSync(path.join(REF,f));
 await context.route('**/*',route=>{const p=new URL(route.request().url()).pathname;if(!routes[p])return route.abort();return route.fulfill({status:200,body:routes[p],contentType:p.endsWith('.js')||p.endsWith('.mjs')?'application/javascript':p.endsWith('.wasm')?'application/wasm':p.endsWith('.onnx')?'application/octet-stream':'text/html'});});const page=await context.newPage();page.on('console',m=>console.log(m.text()));page.on('pageerror',e=>console.error(e));await page.goto('http://localhost:5189/');
 const fixtures=JSON.parse(fs.readFileSync(path.join(BASE,'.artifacts/ai-sigma/reference-fixtures/SIGMA-PARITY-PLAN/fixtures.json'))).fixtures;
 const result=await page.evaluate(async({mode,fixtures})=>{const worker=new Worker('/worker.js'),pending=new Map(),events=[];let clock=null,onStart=null,id=0,g=0;const epoch=()=>performance.timeOrigin+performance.now();
 worker.onmessage=({data:d})=>{if(d.kind==='nn_started'){events.push(d);if(onStart)onStart();return}const p=pending.get(d.request_id);if(!p){events.push({old_rejected:true,...d});return}pending.delete(d.request_id);if(d.generation!==p.generation||d.generation!==g){events.push({old_rejected:true,...d});p.reject(Error('RESPONSE_GENERATION'));return}if(d.error)p.reject(Error(d.error));else p.resolve({...d.result,serialization_ms:d.serialization_ms,serialized_bytes:d.serialized_bytes,worker_delivery_send_ms:d.worker_delivery_send_ms})};
 function call(d,timeout=110000){const request_id=++id,generation=++g;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(request_id);worker.postMessage({kind:'cancel',generation:++g,request_id:++id});reject(Error('HOST_WATCHDOG'))},timeout);pending.set(request_id,{generation,resolve:v=>{clearTimeout(timer);resolve(v)},reject:e=>{clearTimeout(timer);reject(e)}});worker.postMessage({...d,t0:d.t0==null?undefined:d.t0+(clock?.offset_ms??0)-(clock?.error_ms??0),request_id,generation})})}
 const ready=await call({kind:'load'});console.log('ready');const rounds=[];for(let k=0;k<12;k++){const start=epoch(),r=await call({kind:'clock'});rounds.push({start,end:epoch(),remote:r.clock_ms})}let lo=-Infinity,hi=Infinity;for(const r of rounds){lo=Math.max(lo,r.remote-r.end-.1);hi=Math.min(hi,r.remote-r.start+.1)}if(lo>hi)throw Error('CLOCK_OFFSET_DISJOINT');clock={offset_ms:(lo+hi)/2,error_ms:(hi-lo)/2+.1,lo_ms:lo,hi_ms:hi,rounds};const rows=[];
 if(mode==='numeric'){for(const f of fixtures){rows.push({id:f.id,classification:f.classification,...await call({kind:'numeric',fixture:f})});}const faults=await call({kind:'faults'});await call({kind:'drop'});worker.terminate();return{ready,clock,rows,faults,events};}
 if(mode==='fixed'){const ids=['initial-p1','asym-hv-p2','straight-jump-p2','repeat-before-third-return','goal-win-legal-replay','synthetic-total-ply-200','synthetic-no-legal-move-draw','synthetic-goal-at200'];for(const fid of ids){const f=fixtures.find(f=>f.id===fid);for(const sims of[1,8,32])for(const [max_nodes,max_depth]of[[64,8],[1,8],[64,1]])for(const backend of['A','B'])rows.push({id:fid,sims,max_nodes,max_depth,backend,...await call({kind:'fixed',fixture:f,backend,simulations:sims,max_nodes,max_depth})});}await call({kind:'drop'});worker.terminate();return{ready,clock,rows,events};}

 if(mode==='boundary'){const f=fixtures.find(f=>f.id==='initial-p1');const modelFaults=await call({kind:'model_faults'});const failed=await call({kind:'fixed',backend:'B',fixture:f,simulations:8,inject_nn_error:true});const late=await call({kind:'timed',backend:'B',fixture:f,simulations:8,T_ms:500,g_ms:91,t0:epoch(),stepdelay_ms:550});let freshPromise;onStart=()=>{onStart=null;worker.postMessage({kind:'cancel',generation:++g,request_id:++id});freshPromise=call({kind:'fixed',backend:'B',fixture:f,simulations:8});};const oldPromise=call({kind:'fixed',backend:'B',fixture:f,simulations:32,notify:true}).then(r=>({unexpected_accepted:r}),e=>({rejected:e.message}));const old=await oldPromise;const fresh=await freshPromise;const drop=await call({kind:'drop'});worker.terminate();return{ready,clock,rows:[{modelFaults,failed,late,old,fresh,drop}],events};}
 if(mode==='latency'){const ids=['initial-p1','asym-hv-p2','straight-jump-p2'];for(let c=0;c<ids.length;c++){const f=fixtures.find(f=>f.id===ids[c]);for(let k=-3;k<10;k++){const order=(c+k+3)%2?['B','A']:['A','B'];for(const backend of order){const t0=epoch();const r=await call({kind:'timed',fixture:f,backend,T_ms:500,g_ms:91,t0,simulations:4096,max_nodes:512,max_depth:24},1500);const at=epoch();const valid=!r.error&&r.cp?.action!=null&&f.legal_actions.some(x=>x.rust209===r.cp.action)&&at-t0<=500;rows.push({id:f.id,backend,sample:k,warmup:k<0,...r,delivered:at,elapsed_ms:at-t0,valid,accepted_action:valid?r.cp.action:null,overshoot_ms:Math.max(0,at-t0-500)});}}}await call({kind:'drop'});worker.terminate();return{ready,clock,rows,events};}
 throw Error('MODE');}, {mode,fixtures});fs.writeFileSync(path.join(RUN,'browser-'+mode+(tag?'-'+tag:'')+'.json'),JSON.stringify(result));console.log(JSON.stringify({mode,rows:result.rows.length,browser:browser.version(),events:result.events.length}));
 }finally{await browser.close();}}
main().catch(e=>{console.error(e);process.exitCode=1});
