import pathlib,json,os,datetime
ROOT=pathlib.Path('../..').resolve();RUN=ROOT/'.artifacts/ai-sigma/runs/SIGMA-ORT-SEARCH';CACHE=pathlib.Path('/home/vscode/.cache/inference/research/ai-sigma/ort-search');jobs=[json.loads(p.read_text()) for p in RUN.glob('*.process.json')];seen=set();logical=allocated=files=0
for base in [ROOT/'tools/ai-sigma-ort-search',RUN,CACHE]:
 for parent,dirs,names in os.walk(base):
  for name in names:
   try:s=os.stat(os.path.join(parent,name))
   except FileNotFoundError:continue
   key=(s.st_dev,s.st_ino)
   if key in seen:continue
   seen.add(key);logical+=s.st_size;allocated+=s.st_blocks*512;files+=1
corrections=[{'job':j['name'],'pid':p['pid'],'corrections':p['affinity_corrections']} for j in jobs for p in j['tracked_processes'] if p.get('affinity_corrections')];assert not corrections
v={'UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'jobs':len(jobs),'peak_group_plus_runner_rss_bytes':max(j['peak_group_plus_runner_rss_bytes'] for j in jobs),'peak_observed_logical_storage_bytes':max(j['peak_storage_bytes'] for j in jobs),'unique_inode_current_logical_bytes':logical,'unique_inode_current_allocated_bytes':allocated,'files':files,'prior_owned_conservative_bytes':3676045312,'owned_conservative_allocated_bytes':3676045312+allocated,'owned_conservative_logical_bytes':3676045312+logical,'guard_stop_jobs':[j['name'] for j in jobs if j['stop_reason']],'affinity_corrections':corrections,'tracked_cpu_seconds':sum(j['tracked_cpu_seconds'] for j in jobs),'child_cpu_user_seconds':sum(j['children_usage']['user_s'] for j in jobs),'child_cpu_system_seconds':sum(j['children_usage']['system_s'] for j in jobs),'free_bytes_now':os.statvfs(ROOT).f_bavail*os.statvfs(ROOT).f_frsize,'network_acquired_bytes':0,'private_index_metadata_repair_bytes':757522,'GPU_training_games':0,'SMT_cpu2_siblings':pathlib.Path('/sys/devices/system/cpu/cpu2/topology/thread_siblings_list').read_text().strip(),'successful_runtime_remaining_PIDs':sum(len(j['remaining_pids']) for j in jobs),'violations_and_limits':['first native-test-build/native-test-repaired-build/terminal-cap-repaired-build executed diagnostics inside prep affinity2,4; final nine tests + timings CPU2 only','initial job RSS-start absent before later runner revision; peak conservatively sums descendant RSS and inherited runner ru_maxrss','RSS shared pages double-counted; 50ms sampling can miss transient PID/thread peaks','both resident models in browser; RSS not attributed separately to A/B; B Rust-linear excludes ORT heap','arena accounting copied tree estimate; continuation/legal/context/ABI allocation counter unmeasured','CPU0 hypothesis .27/.28 text/std-only short compile possible; SMT/background load observed; no formally idle window'], 'per_job_records':[p.name for p in RUN.glob('*.process.json')]};assert v['successful_runtime_remaining_PIDs']==0;(RUN/'resources-final.json').write_text(json.dumps(v,indent=2));print(json.dumps({k:v[k] for k in ['jobs','peak_group_plus_runner_rss_bytes','unique_inode_current_allocated_bytes','owned_conservative_allocated_bytes','guard_stop_jobs','tracked_cpu_seconds']}))
