importScripts('/ort/ort.min.js','/host.js','/a-host.js','/game.js','/context.js');
let b,a,generation=0,queue=Promise.resolve();const epoch=()=>performance.timeOrigin+performance.now(),yieldTask=()=>new Promise(r=>setTimeout(r,0));
async function run(d){const spans=[],t=d.t0??epoch(),deadline=t+(d.T_ms??1e9),stop=deadline-(d.g_ms??0),g=d.generation;let s,cp=null,calls=0;const check=(heavy=false)=>{if(g!==generation)throw Error('STALE_GENERATION');if(epoch()>=(heavy?stop:deadline))throw Error(heavy?'GUARD':'DEADLINE')};
 try{check(true);const req={fixture:d.fixture,diagnostic:true,simulations:d.simulations??4096,max_nodes:d.max_nodes??512,max_depth:d.max_depth??24,generation:g,seed:1979};const rootStart=epoch();s=d.backend==='A'?a.create(req,true):b.create(req);spans.push({kind:'root',start:rootStart,end:epoch()});
 while(true){if(epoch()>=stop)break;check(true);const begin=epoch();let done;
 if(d.backend==='A'){const st=a.step(s,g);calls+=st.nn_delta;spans.push({kind:'sync_step',start:begin,end:epoch(),step:st});check();done=st.done;const finishStart=epoch();cp=a.checkpoint(s,g);spans.push({kind:'finish',start:finishStart,end:epoch()});}
 else{const q=b.call({op:'begin',handle:s,generation:g});spans.push({kind:'begin_feature_request',start:begin,end:epoch()});if(q.pending){check(true);if(d.notify&&!calls)postMessage({kind:'nn_started',generation:g,request_id:d.request_id});const nnstart=epoch();calls++;let r;try{if(d.inject_nn_error)throw Error('INJECTED_NN_ERROR');r=await b.infer(q.features_bits);spans.push({kind:'NN',token:q.token,start:nnstart,end:epoch(),nn_ms:r.nn_ms})}catch(e){spans.push({kind:'NNerror',token:q.token,start:nnstart,end:epoch(),error:e.message});throw e}if(d.stepdelay_ms)await new Promise(r=>setTimeout(r,d.stepdelay_ms));check();const resumeStart=epoch();const st=b.call({op:'resume',handle:s,generation:g,token:q.token,logits:r.logits,value:r.value});spans.push({kind:'resume_policy_backup',start:resumeStart,end:epoch()});check();done=st.done;}else done=q.done;const finishStart=epoch();cp=b.call({op:'checkpoint',handle:s,generation:g});spans.push({kind:'finish',start:finishStart,end:epoch()});check();}
 spans.push({kind:'step',start:begin,end:epoch(),sims:cp.simulations});await yieldTask();check();if(done)break;}
 check();if(!cp)throw Error('NO_CHECKPOINT');return{cp,calls,spans,t0:t,worker_finish:epoch(),error:null,fallback:0,memory:d.backend==='A'?a.e.memory.buffer.byteLength:b.e.memory.buffer.byteLength};
 }catch(error){if(s&&d.backend!=='A')try{b.call({op:'cancel',handle:s,generation:g})}catch{}return{error:error.message,cp:null,calls,spans,t0:t,worker_finish:epoch(),fallback:0};}finally{if(s)(d.backend==='A'?a:b).free(s)}}
onmessage=({data:d})=>{generation=d.generation??generation;
 if(d.kind==='cancel'){postMessage({kind:'cancel_ack',generation,request_id:d.request_id});return}
 queue=queue.then(async()=>{try{let result;if(d.kind==='load'){b=await loadOrtHost();a=await loadSearchHost();result={B:{compile_ms:b.compile_ms,load_ms:b.load_ms,digest:b.digest,version:b.version,threads:b.threads,proxy:b.proxy},A:{compile_ms:a.compile_ms,load_ms:a.load_ms,digest:a.digest}}}
 else if(d.kind==='clock'){result={clock_ms:epoch()}}
 else if(d.kind==='numeric'){result=await b.numeric(d.fixture);const state=referenceState(d.fixture),fb=Array.from(new Uint32Array(state.toNNInput().buffer)),legal=state.getLegalActions().map(x=>rustAction(state,x)).sort((x,y)=>x-y),terminal=terminalResult(state)?.value??null;if(JSON.stringify(fb)!==JSON.stringify(result.features_bits)||JSON.stringify(legal)!==JSON.stringify(result.raw_legal)||terminal!==result.terminal)throw Error('REFERENCE_STATE_PARITY');result.reference_features_exact=true;result.reference_legal_exact=true;result.reference_terminal_equal=true}
 else if(d.kind==='fixed'||d.kind==='timed'){result=await run(d)}
 else if(d.kind==='model_faults'){result=await b.modelFaults()}
 else if(d.kind==='raw'){result=b.call({op:'raw',fixture:d.fixture})}
 else if(d.kind==='faults'){result={};for(const name of ['shape','null','range','duplicate','stale','token','cancel']){const g=100,s=b.create({prefix:[],generation:g,simulations:32});const q=b.call({op:'begin',handle:s,generation:g});const r={op:'resume',handle:s,generation:g,token:q.token,logits:Array(136).fill(0),value:0.25};if(name==='shape')r.logits.pop();if(name==='null')r.logits[0]=null;if(name==='range')r.value=1.001;if(name==='stale')r.generation++;if(name==='token')r.token++;try{if(name==='cancel')b.call({op:'cancel',handle:s,generation:g});if(name==='duplicate')b.call(r);b.call(r);result[name]={unexpected_success:true}}catch(e){result[name]={error:e.message};try{b.call({op:'checkpoint',handle:s,generation:g});result[name].checkpoint_published=true}catch{result[name].checkpoint_published=false}}finally{b.free(s)}}}
 else if(d.kind==='drop'){await b.drop();a.drop();result={dropped:true}}
 else throw Error('REQUEST_KIND');const serializeStart=epoch(),serialized=JSON.stringify(result),serializeEnd=epoch();if(d.kind==='timed'&&!result.error&&serializeEnd>=d.t0+d.T_ms){result.cp=null;result.error='DEADLINE_SERIALIZATION'}postMessage({kind:'response',request_id:d.request_id,generation:d.generation,result,serialization_ms:serializeEnd-serializeStart,serialized_bytes:serialized.length,worker_delivery_send_ms:epoch()});}catch(e){postMessage({kind:'response',request_id:d.request_id,generation:d.generation,error:e.message})}});
};
