'use strict';const fs=require('fs'),vm=require('vm'),assert=require('assert'),crypto=require('crypto');const R='/workspaces/quoridor/.worktree/ai-sigma',O=R+'/.artifacts/ai-sigma/resume-20261003/SIGMA-WEB-PORT';
async function main(){const binary=fs.readFileSync(O+'/build/faithful.wasm'),e=(await WebAssembly.instantiate(binary,{})).instance.exports;
 function call(v){const b=Buffer.from(JSON.stringify(v)),h=e.ort_buffer(b.length);new Uint8Array(e.memory.buffer,e.ort_ptr(h),b.length).set(b);let o;try{o=e.ort_call(h);const r=JSON.parse(Buffer.from(new Uint8Array(e.memory.buffer,e.ort_ptr(o),e.ort_len(o))));if(!r.ok)throw Error(r.error);return r.data;}finally{e.ort_free(h);if(o)e.ort_free(o);}}
 const ctx=vm.createContext({console});for(const n of ['game.js','context.js'])vm.runInContext(fs.readFileSync(R+'/tools/ai-sigma-actual-boundary-repair/'+n,'utf8'),ctx);vm.runInContext('globalThis.rules={fromPrefix,rustAction}',ctx);const f=JSON.parse(fs.readFileSync(R+'/research-data/ai-sigma/151-sigma-web-port/stageA-inputs.json')).fixtures.find(f=>f.id==='straight-jump-p2');let state=ctx.rules.fromPrefix([]),prefix=[];for(const a of f.legal_prefix){prefix.push(ctx.rules.rustAction(state,a));state=state.next(a);}
 const h=call({op:'new',prefix,simulations:16,generation:91,trace:true}).handle,logits=Array(136).fill(-20);logits[0]=20;let previous=0,cp,noNNsteps=[];
 while(true){const q=call({op:'begin',handle:h,generation:91});if(q.pending)call({op:'resume',handle:h,generation:91,token:q.token,logits,value:.25});cp=call({op:'checkpoint',handle:h,generation:91});if(!q.pending){assert.equal(cp.nn_calls,previous);noNNsteps.push(cp.simulations);}previous=cp.nn_calls;if(cp.simulations===16)break;}
 const trace=call({op:'trace',handle:h,generation:91}),terminal=trace.backups.filter(b=>b.terminal!==null),paths={};for(const b of terminal){const k=JSON.stringify(b.path);paths[k]=(paths[k]??0)+1;}assert(Object.values(paths).some(n=>n>=2),'REVISIT_NOT_REACHED');assert(terminal.length===noNNsteps.length);e.ort_free(h);
 const out={issue:'quoridor-4lc.151',NN_model:0,Chrome:0,artificial_NN:.25,actual_private_Wasm:true,binary_SHA256:crypto.createHash('sha256').update(binary).digest('hex'),fixture:f.id,K:16,completed_backups:cp.simulations,artificial_evaluator_calls:cp.nn_calls,terminal_noNN:cp.terminal_noNN,terminal_paths:paths,noNN_completed_K:noNNsteps,actual_terminal_revisit_noNN_supported:true,chronology:'post-science NN0 completion check; pre-AI oracle recorded one terminal arrival, not a demonstrated revisit; no retrospective preflight pass',actual_game_or_deep_general_or_model_success:false};fs.writeFileSync(R+'/research-data/ai-sigma/151-sigma-web-port/terminal-revisit-posthoc.json',JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out));
}main().catch(e=>{console.error(e.stack);process.exitCode=1});
