'use strict';require('./path-adapter.cjs');const fs=require('fs'),path=require('path'),CP=require('child_process'),assert=require('assert/strict');const root=path.resolve(__dirname,'../..'),tool=root+'/tools/ai-sigma-actual-boundary-repair',own=root+'/.artifacts/ai-sigma/continuation-20261001/CRITIC-ACTUAL-DRIVER-MINIMAL';const {make}=require(tool+'/make-diagnostic.cjs');const rows=[];let current='';const read=(id,n)=>JSON.parse(fs.readFileSync(own+'/upstream/diagnostic-actual/'+id+'/'+n+'.json'));
function cli(token,flag='--diagnostic-actual'){const cmd=[process.execPath,'--max-old-space-size=192','--max-semi-space-size=4','--no-node-snapshot','--require',__dirname+'/path-adapter.cjs',tool+'/match-entry.cjs',flag,token];const c=CP.spawnSync(cmd[0],cmd.slice(1),{env:{...process.env,SIGMA77_FREEZE_TOKEN:'DIAGNOSTIC77_ONLY_NOT_ACTUAL'},encoding:'utf8',timeout:12000});rows.push({case:current,command:cmd,exit:c.status,signal:c.signal,stdout:c.stdout,stderr:c.stderr});return c;}
function run(name,opt={},code=null,flag='--diagnostic-actual'){current=name;const id='critic87-'+name,token=make(id,{processing_deadline_UTC:'2026-10-02T00:30:33Z',...opt});const c=cli(token,flag);assert.equal(c.status,code?1:0,c.stderr);if(code)assert(c.stderr.includes(code),c.stderr);const file=own+'/upstream/diagnostic-actual/'+id+'/driver-monitor-stop.json';if(fs.existsSync(file)){const z=read(id,'driver-monitor-stop');assert.equal(z.owned_read_children_zero,true);if(code)assert.equal(z.factoryCalls,0);}return {id,token};}
try{
 const p=run('positive');const r=read(p.id,'driver-result').result;assert.equal(r.purpose,'actual');assert.equal(r.diagnostic,true);assert.equal(r.dry,true);assert.equal(r.actual_go,false);assert.equal(r.audit.backend_dispatches,2);assert.equal(r.audit.mock_dispatches,2);assert.equal(r.audit.real_engine_dispatches,0);assert.equal(r.audit.public_responses,2);assert.equal(r.audit.accepted_responses,1);assert.equal(r.actual_games,0);assert.equal(r.holdout_sends,0);assert.equal(r.NN,0);assert.equal(r.browser,0);assert.equal(r.audit.attempts,0);assert.equal(r.cleanupFailed,false);assert.equal(r.unrecovered_preparations,0);assert.equal(read(p.id,'monitor-ready').state,'READY');const m=read(p.id,'pause-monitor-stop');assert.equal(m.pending_children.length,0);assert(m.all_owned_read_callbacks_waited);assert(m.rows.some(x=>x.kind==='owned_observer_child'));assert(m.rows.some(x=>x.exitCode===0));
 current='duplicate';let c=cli(p.token);assert.equal(c.status,1);assert(c.stderr.includes('RUN_ALREADY_EXISTS'));
 current='real-reject-diagnostic';c=cli(p.token,'--run');assert.equal(c.status,1);assert(c.stderr.includes('ACTUAL_GO_FALSE_OR_DIAGNOSTIC_PROOF'));
 run('same-review',{acceptancePatch:{review_issue:'quoridor-4lc.77'},freezePatch:{review_issue:'quoridor-4lc.77'}},'SUBJECT_REVIEW_MEANING');
 run('read-error',{gate_case:'read-error'},'BEADS_READ_ERROR');run('expired',{gate_case:'expired-monitor'},'PROCESSING_DEADLINE');run('undispatched',{gate_case:'undispatched'},'DIAGNOSTIC_UNDISPATCHED');
 const q=run('partial',{gate_case:'after-public-pause'});const s=read(q.id,'driver-result').result;assert.equal(s.stopReason,'PAUSED');assert.equal(s.audit.backend_dispatches,1);assert.equal(s.audit.public_responses,1);assert.equal(s.actual_games,0);assert.equal(s.score.L,null);assert(read(q.id,'driver-monitor-stop').owned_read_children_zero);
 fs.writeFileSync(own+'/independent-gates.json',JSON.stringify({pass:true,Git:'ffb4559',cases:rows.length,positive:r.audit,partial:s.audit,monitor_positive:m,rows,NN:0,Chromium:0,real_games:0,holdout:0,actual_go:false,diagnostic_proof_is_not_acceptance:true},null,2)+'\n');console.log(JSON.stringify({pass:true,cases:rows.length,positive:r.audit,partial:s.audit}));
}catch(e){fs.writeFileSync(own+'/independent-failure.json',JSON.stringify({case:current,message:e.message,stack:e.stack,rows},null,2)+'\n');console.error(e);process.exitCode=1;}
