'use strict';
const {spawn}=require('child_process'),readline=require('readline'),{now}=require('./engine.cjs');
class Worker{
 constructor(manifest,script=__dirname+'/worker.cjs',extra=[]){this.queue=[];this.waiter=null;this.exit=null;this.stderr='';this.p=spawn('/home/vscode/.local/bin/node',[script,manifest,...extra],{stdio:['pipe','pipe','pipe']});this.p.stderr.on('data',b=>{this.stderr=(this.stderr+b).slice(-8192)});this.p.on('error',e=>this.push({type:'PROCESS_ERROR',reason:String(e)}));this.p.on('exit',(code,signal)=>{this.exit={code,signal};this.push({type:'EOF',...this.exit})});readline.createInterface({input:this.p.stdout}).on('line',line=>{try{this.push(JSON.parse(line))}catch(e){this.push({type:'SCHEMA_ERROR',reason:String(e)})}})}
 push(x){if(this.waiter){const f=this.waiter;this.waiter=null;f(x)}else this.queue.push(x)}
 async take(ms){if(this.queue.length)return this.queue.shift();return new Promise(resolve=>{const timer=setTimeout(()=>{if(this.waiter===f)this.waiter=null;resolve({type:'WAIT_TIMEOUT',timer_fired_ms:now()})},Math.max(0,ms));const f=x=>{clearTimeout(timer);resolve(x)};this.waiter=f})}
 send(x){this.p.stdin.write(JSON.stringify(x)+'\n')}
 async request(c,budget=100,validate=null,inputReady=null){const t0=inputReady??now(),obsolete=[];let timerFired=null;this.send({...c,deadline_ms:t0+90});let response=null;
 while(now()-t0<budget){const x=await this.take(budget-(now()-t0));if(x.type==='WAIT_TIMEOUT'){timerFired=x.timer_fired_ms;if(now()<t0+budget)continue;break;}if(x.type==='RESULT'&&(x.id!==c.id||x.generation!==c.generation||x.key!==c.key||x.history!==c.history||x.model_id!==c.model_id)){obsolete.push({type:x.type,id:x.id,reason:'STALE_IDENTITY_DISCARD'});continue}response=x;if(x.type==='RESULT'&&validate){try{x.validation=validate(x)}catch(e){x.validation={valid:false,reason:String(e)}}}break}
 const received=now(),elapsed=received-t0;return{t0_ms:t0,received_ms:received,elapsed_ms:elapsed,budget_ms:budget,margin_ms:10,timer_fired_ms:timerFired,timer_callback_delay_ms:timerFired===null?null:Math.max(0,timerFired-(t0+budget)),overshoot_ms:Math.max(0,elapsed-budget),t1_definition:'complete parse+generation/key/history+legal completed Action validation',obsolete,response,status:!response?'OUTER_DEADLINE':elapsed>budget?'OUTER_DEADLINE':response.type==='RESULT'?'RECEIVED':response.type};}
 async stop(id){const discarded=[];if(this.exit)return{status:'ALREADY_EXITED',...this.exit};this.send({kind:'STOP',id});const start=now();while(now()-start<2000){const x=await this.take(2000-(now()-start));if(x.type==='STOP_ACK'&&x.id===id)return{status:'STOP_ACK',allNN:x.allNN,wall_ms:now()-start,discarded_late_responses:discarded};if(x.type==='EOF')return{status:'EOF',...x,discarded_late_responses:discarded};discarded.push({received_ms:now(),...x,adopted:false,reason:'AFTER_DEADLINE_OR_STOP_DISCARD'})}this.p.kill('SIGTERM');return{status:'STOP_TIMEOUT_KILLED',discarded_late_responses:discarded}}
 async close(){const st=now();if(!this.exit){this.send({kind:'CLOSE'});while(!this.exit&&now()-st<2000){await this.take(Math.max(1,2000-(now()-st)))}if(!this.exit)this.p.kill('SIGKILL');}while(!this.exit&&now()-st<4000)await this.take(20);return{exit:this.exit,wall_ms:now()-st,stderr:this.stderr,waited:!!this.exit}}
}
module.exports={Worker};
