"use strict";
const fs=require('fs'),cp=require('child_process'),vm=require('vm'),assert=require('assert'),crypto=require('crypto');
const ROOT='/workspaces/quoridor/.worktree/ai-sigma',OUT=ROOT+'/.artifacts/ai-sigma/resume-20261002/SEARCH-POLICY',INPUT=JSON.parse(fs.readFileSync(OUT+'/small-input.json'));
const upstream=fs.readFileSync(ROOT+'/.artifacts/ai-sigma/reference-fixtures/SIGMA-PARITY-PLAN/sources/docs/mcts_worker.js','utf8');
const stopped=cp.execFileSync('git',['show','28d6feba:tools/ai-sigma-actual-boundary-repair/reference-core.js'],{cwd:ROOT,encoding:'utf8'});
function pieces(s){return {node:s.slice(s.indexOf('class MCTSNode'),s.indexOf('const C_PUCT')),backup:s.slice(s.indexOf('function backup('),s.indexOf('function selectLeaf(')),pick:s.slice(s.indexOf('function pickFromVisits('),s.indexOf('async function selectAction('))};}
const u=pieces(upstream),g=pieces(stopped);for(const k of Object.keys(u))assert.strictEqual(u[k].trim(),g[k].trim(),k+' stopped-vs-pristine');
// Only class selection, backup and temperature0 finish are evaluated. No worker/NN/full search.
const box=vm.createContext({});vm.runInContext(u.node+u.backup+u.pick+';globalThis.API={MCTSNode,backup,pickFromVisits}',box);const {MCTSNode,backup,pickFromVisits}=box.API;
const f=Math.fround,buf=new ArrayBuffer(4),dv=new DataView(buf),fb=x=>{dv.setFloat32(0,x,true);return dv.getUint32(0,true)},val=b=>{dv.setUint32(0,b,true);return dv.getFloat32(0,true)};
function tie(seed,a){let x=BigInt(seed)^BigInt(a);x=BigInt.asUintN(64,(x^(x>>30n))*0xbf58476d1ce4e5b9n);x=BigInt.asUintN(64,(x^(x>>27n))*0x94d049bb133111ebn);return x^(x>>31n);}
const cmpPrior=x=>{let i=fb(x)|0;return i<0?i^0x7fffffff:i};
function finish(edges,seed){return edges.reduce((best,e)=>e.visits>best.visits||e.visits===best.visits&&(cmpPrior(e.prior)>cmpPrior(best.prior)||cmpPrior(e.prior)===cmpPrior(best.prior)&&tie(seed,e.action)<tie(seed,best.action))?e:best).action;}
function choose(edges,N,C=1.5,plus=true,first=false,unseenQ=0){assert(edges.length&&Number.isInteger(N)&&N>=0);const sqrt=f(Math.sqrt(f(f(N)+(plus?1:0))));let best=null;const scored=edges.map(e=>{assert(Number.isFinite(e.prior)&&e.prior>=0&&Number.isFinite(e.value_sum)&&e.visits>=0);const q=e.visits?f(e.value_sum/f(e.visits)):f(unseenQ);const score=f(q+f(f(f(f(C)*e.prior)*sqrt)/f(e.visits+1)));const s={action:e.action,score_bits:fb(score),score};if(!best||score>best.score||score===best.score&&!first&&tie(1979,e.action)<tie(1979,best.action))best=s;return s});return {action:best.action,score_bits:best.score_bits,score:best.score,edges:scored};}
function decode(r){return r.edges.map(([action,p,visits,v,rank])=>({action,prior:val(p),visits,value_sum:val(v),reference_rank:rank}));}
const actual=[];
for(const r of INPUT.real_saved_roots){const edges=decode(r);assert.strictEqual(edges.reduce((s,e)=>s+e.visits,0),r.edge_sum);assert.strictEqual(r.N_restored,r.edge_sum+1);assert.strictEqual(finish(edges,r.seed),r.expected_finish);
 const variations={base:choose(edges,r.N_restored),C1:choose(edges,r.N_restored,1),sqrtN:choose(edges,r.N_restored,1.5,false),score_first:choose(edges,r.N_restored,1.5,true,true)};
 for(const [name,v]of Object.entries(variations)){assert.strictEqual(v.action,r.expected_selected[name].action);assert.strictEqual(v.score_bits,r.expected_selected[name].score_bits);}
 actual.push({id:r.id,accepted:r.metadata.accepted,private_late:r.metadata.private_late,engine:r.metadata.engine,finish:r.expected_finish,N_conditional:r.N_restored,parentQ:null,variations:Object.fromEntries(Object.entries(variations).map(([k,v])=>[k,{action:v.action,score_bits:v.score_bits}]))});}
function syntheticReference(edges,N,parentQ){const root=new MCTSNode(null);root.visitCount=N;root.valueSum=parentQ*N;for(const e of edges){const child=new MCTSNode(null,root,e.action,e.prior);child.visitCount=e.visits;child.valueSum=-e.value_sum;root.children.push(child);}return root;}
const artificial=[];
for(const [name,parentQ,visitedQ]of [['negative-parent',-.4,.2],['positive-parent',.7,.8]]){const es=[{action:3,prior:f(.8),visits:9,value_sum:f(visitedQ*9)},{action:5,prior:f(.2),visits:0,value_sum:0}];const root=syntheticReference(es,10,parentQ),pq=root.qValue,visitedPriorSum=root.children.filter(c=>c.visitCount>0).reduce((s,c)=>s+c.basePrior,0),fpu=pq-.2*Math.sqrt(visitedPriorSum);const expectedScores=es.map(e=>{const q=e.visits?e.value_sum/e.visits:fpu;return q+e.prior*Math.sqrt(10)/(1+e.visits)});assert.strictEqual(root.bestChild(1,.2).action,es[expectedScores.indexOf(Math.max(...expectedScores))].action);const q0=choose(es,10,1,false,false,0),fpuOnly=choose(es,10,1,false,false,fpu);artificial.push({name,artificial:true,parentQ:pq,visitedPriorSum,FPU:fpu,Q0_action:q0.action,FPU_only_action:fpuOnly.action,reference_source_action:root.bestChild(1,.2).action,other_factors_fixed:'C1/sqrt(N)/seed; only unvisited Q changes in f32 comparison'});}
const tieEdges=[{action:3,prior:.5,visits:0,value_sum:0},{action:5,prior:.5,visits:0,value_sum:0}];const min=tie(1979,3)<tie(1979,5)?3:5;const firstOpposite=[...tieEdges].sort((a,b)=>a.action===min?1:-1);const sr=syntheticReference(firstOpposite,1,0);const seedPick=choose(firstOpposite,1,1.5,true,false),firstPick=choose(firstOpposite,1,1.5,true,true);assert.strictEqual(seedPick.action,min);assert.notStrictEqual(seedPick.action,firstPick.action);assert.strictEqual(sr.bestChild(1,.2).action,firstOpposite[0].action);
artificial.push({name:'exact-score-tie',artificial:true,order:firstOpposite.map(x=>x.action),seed_action:seedPick.action,first_action:firstPick.action,Sigma_first:sr.bestChild(1,.2).action});
const finishEdges=[{action:3,prior:.2,visits:1,value_sum:0},{action:5,prior:.8,visits:1,value_sum:0}];const fr=syntheticReference(finishEdges,3,0);assert.strictEqual(finish(finishEdges,1979),5);assert.strictEqual(pickFromVisits(fr.children,0).action,3);artificial.push({name:'finish-visit-tie-prior',artificial:true,candidate:5,Sigma:3});
const zero=syntheticReference(finishEdges.map(x=>({...x,visits:0})),1,.25);assert.strictEqual(pickFromVisits(zero.children,0).action,3);assert.strictEqual(finish(finishEdges.map(x=>({...x,visits:0})),1979),5);artificial.push({name:'root-expansion-only',artificial:true,candidate_simulations:1,candidate_edge_visits:0,Sigma_simulations:0,Sigma_root_visits:1,Sigma_edge_visits:0,candidate_finish:5,Sigma_finish:3});
const backs=[];
for(const depth of [0,1,2,3])for(const value of [-1,0,.25,.75]){const nodes=Array.from({length:depth+1},()=>new MCTSNode(null));for(let i=1;i<=depth;i++){nodes[i].parent=nodes[i-1];nodes[i-1].children=[nodes[i]];}backup(nodes[depth],value);let v=value;const edgeSums=[];for(let d=depth-1;d>=0;d--){v=f(-v);edgeSums[d]=f(f(0)+v);}for(let i=0;i<depth;i++)assert(edgeSums[i]===-nodes[i+1].valueSum);assert(nodes[0].valueSum===(depth%2?-1:1)*value);backs.push({depth,leaf_value:value,node_values:nodes.map(n=>n.valueSum),parent_edge_values:edgeSums,visited_Q_agrees:true});}
// Parent Q incorporates root's initial evaluation; it is not the edge-only average.
const qr=new MCTSNode(null),qc=new MCTSNode(null,qr,3,.8);qr.children=[qc];backup(qr,.25);backup(qc,-.5);assert.strictEqual(qr.qValue,.375);assert.notStrictEqual(qr.qValue,-qc.qValue);artificial.push({name:'parent-Q-not-edge-average',artificial:true,root_initial_value:.25,edge_parent_Q:-qc.qValue,parentQ:qr.qValue,root_visits:qr.visitCount});
const result={issue:'quoridor-4lc.94',run:process.env.SIGMA_POLICY_RUN||'node-policy-unspecified',UTC:new Date().toISOString(),Git:cp.execFileSync('git',['rev-parse','HEAD'],{cwd:ROOT,encoding:'utf8'}).trim(),source_functions_match_pristine:true,real_saved_roots:actual,finish_gate:{n:actual.length,pass:actual.length},artificial,backup_cases:backs,backup_comparison:"numeric POV equivalence; signed zero not required bitwise identical",failures:[],NN:0,full_MCTS:0,games:0};
fs.writeFileSync(OUT+'/node-result.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({finish:result.finish_gate,artificial,backup_cases:backs.length,NN:0}));
