const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),readline=require('node:readline'),{spawn}=require('node:child_process'),{createRequire}=require('node:module'),J=require('./judge.cjs');const{chromium}=createRequire('/workspaces/quoridor/package.json')('playwright');const ROOT=path.resolve(__dirname,'../..'),TOOL=__dirname,RUN=ROOT+'/.artifacts/ai-sigma/runs/SIGMA-ORT-ENTRY-CONTINUE/diagnostic/default',FIX=ROOT+'/.artifacts/ai-sigma/reference/SIGMA-WEB-REFERENCE',NN=ROOT+'/.artifacts/ai-sigma/runs/SIGMA-NN-SEARCH',MODEL=ROOT+'/models/experiments/ai-sigma/reference/sigma-pcr250/best.onnx';const now=()=>Number(process.hrtime.bigint())/1e6;const save=(name,v)=>fs.writeFileSync(RUN+'/'+name+'.json',JSON.stringify(v,null,2)+'\n');let generation=1000,owners={native:0,candidate:0,reference:0};const frozen={checks:JSON.parse(fs.readFileSync(ROOT+'/.artifacts/ai-sigma/runs/SIGMA-ORT-ENTRY-CONTINUE/input-before.json')).checks};
function verify(){for(const x of frozen.checks){const h=crypto.createHash('sha256').update(fs.readFileSync(x.path)).digest('hex');if(h!==x.sha256)throw Error('FROZEN_INPUT_MUTATED '+x.path);}if(crypto.createHash('sha256').update(fs.readFileSync(MODEL)).digest('hex')!=='d790dac68389f7602ff8a887a2385417d3c925fe22da7164c86e9226f943908d')throw Error('MODEL_HASH');}
function freeze(o){if(o&&typeof o==='object'){Object.freeze(o);for(const v of Object.values(o))freeze(v);}}
function pipe(cmd,args,log){const child=spawn(cmd,args,{stdio:['pipe','pipe',fs.openSync(path.isAbsolute(log)?log:RUN+'/'+log,'w')]});const queue=[],lines=[];let failure,closePromise,abortPromise;
 const exited=()=>child.exitCode!==null||child.signalCode!==null;
 const fail=e=>{failure=e;while(queue.length)queue.shift().reject(e)};
 const wait=()=>exited()?Promise.resolve():new Promise(resolve=>{child.once('exit',resolve);if(exited()){child.removeListener('exit',resolve);resolve();}});
 readline.createInterface({input:child.stdout}).on('line',l=>{let v;try{v=JSON.parse(l)}catch(e){fail(Error('PIPE_PARSE'));return;}const r=queue.shift();if(r)r.resolve(v);else lines.push(v)});
 child.on('error',fail);child.on('exit',(code,signal)=>fail(Object.assign(Error('BACKEND_EXIT'),{code,signal})));child.stdin.on('error',fail);
 return {child,next:()=>{if(failure)return Promise.reject(failure);if(lines.length)return Promise.resolve(lines.shift());return new Promise((resolve,reject)=>queue.push({resolve,reject}));},send:v=>child.stdin.write(JSON.stringify(v)+'\n'),
 close:()=>{if(closePromise)return closePromise;if(exited())return Promise.resolve();closePromise=wait();child.stdin.end();return closePromise;},
 abort:()=>{if(abortPromise)return abortPromise;if(exited())return Promise.resolve();abortPromise=wait();child.kill('SIGTERM');const timer=setTimeout(()=>{if(!exited())child.kill('SIGKILL')},1000);abortPromise.finally(()=>clearTimeout(timer));return abortPromise;}};
}
function offset(samples,resolution){let lo=-Infinity,hi=Infinity;for(const s of samples){lo=Math.max(lo,s.remote-s.end-resolution);hi=Math.min(hi,s.remote-s.start+resolution);}if(!(lo<=hi))throw Error('CLOCK_OFFSET_DISJOINT');return {offset_ms:(lo+hi)/2,error_ms:(hi-lo)/2+resolution,lo_ms:lo,hi_ms:hi,samples};}
function dist(v){v=[...v].sort((a,b)=>a-b);return v.length?{n:v.length,min:v[0],p50:v.length%2?v[(v.length-1)/2]:(v[v.length/2-1]+v[v.length/2])/2,p95:v[Math.ceil(v.length*.95)-1],max:v.at(-1)}:null;}
async function withArena(run,options={}){const RUN=options.outputDir??path.join(__dirname,'../../.artifacts/ai-sigma/runs/SIGMA-ORT-ENTRY-CONTINUE/diagnostic/default');fs.mkdirSync(RUN,{recursive:true});const save=(name,v)=>fs.writeFileSync(RUN+'/'+name+'.json',JSON.stringify(v,null,2)+'\n');verify();const modelBytes=fs.readFileSync(MODEL),modelSha=crypto.createHash('sha256').update(modelBytes).digest('hex');if(modelSha!=='d790dac68389f7602ff8a887a2385417d3c925fe22da7164c86e9226f943908d')throw Error('MODEL_HASH');let browser,native,ping;try{
 browser=await chromium.launch({headless:true,executablePath:'/workspaces/quoridor/artifacts/playwright/chromium-1243/chrome-linux64/chrome',args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--disable-software-rasterizer','--use-gl=disabled','--renderer-process-limit=1']});const ctx=await browser.newContext();const routes={'/game.js':TOOL+'/game.js','/context.js':TOOL+'/context.js','/arena-page.js':TOOL+'/arena-page.js','/candidate-worker.js':TOOL+'/candidate-worker.js','/candidate-host.js':TOOL+'/host.js','/checkpoint.js':TOOL+'/checkpoint.js','/b.wasm':ROOT+'/.artifacts/ai-sigma/runs/SIGMA-ORT-SEARCH/final.wasm','/ort/ort.min.js':FIX+'/ort.min.js','/search.wasm':NN+'/final.wasm','/model.onnx':MODEL,'/models_9x9/best.onnx':MODEL,'/ref/game.js':TOOL+'/game.js','/ref/context.js':TOOL+'/context.js','/ref/reference-worker.js':TOOL+'/reference-worker.js','/ref/ort.min.js':FIX+'/ort.min.js','/ort/ort-wasm-simd-threaded.jsep.mjs':FIX+'/ort-wasm-simd-threaded.jsep.mjs','/ort/ort-wasm-simd-threaded.jsep.wasm':FIX+'/ort-wasm-simd-threaded.jsep.wasm'},network=[];
 await ctx.route('**/*',async r=>{const u=new URL(r.request().url());network.push(u.href);if(u.origin!=='http://localhost:5190'){await r.abort();return;}if(u.pathname==='/'){await r.fulfill({contentType:'text/html',body:'<!doctype html><script src="/game.js"></script><script src="/context.js"></script><script src="/arena-page.js"></script>'});return;}const p=routes[u.pathname];if(!p){console.error('UNKNOWN_ROUTE',u.href);await r.abort();return;}await r.fulfill({contentType:u.pathname.endsWith('.wasm')?'application/wasm':/\.m?js$/.test(u.pathname)?'text/javascript':'application/octet-stream',body:p===MODEL?modelBytes:fs.readFileSync(p)});});const page=await ctx.newPage();page.on('console',m=>console.log('PAGE',m.text()));page.on('pageerror',e=>console.error('PAGE_ERROR',e));await page.goto('http://localhost:5190/');const browserReady=await page.evaluate(()=>loadArena());save('startup',{native:{loaded:false},browser:browserReady,ping:{loaded:false},modelSha,browserVersion:browser.version(),startupClock:'not charged to request T',singleCPU:2});
 if(options.warmReference){const f=JSON.parse(fs.readFileSync(ROOT+'/.artifacts/ai-sigma/reference-fixtures/SIGMA-PARITY-PLAN/fixtures.json')).fixtures.find(x=>x.id==='initial-p1');const w=await page.evaluate(async f=>{const generation=900001,p=wait('ref-'+generation);ref.postMessage({type:'numeric',fixture:f,generation});return await p;},f);if(w.error||w.fallback!==0)throw Error('REFERENCE_WARM_FAILED');save('reference-warm',{fixed_golden:f.id,response:w,startup_only:true});}
 const clock={};const pp=[];for(let i=0;i<12;i++){const start=now(),remote=await page.evaluate(()=>performance.timeOrigin+performance.now());pp.push({start,end:now(),remote});}clock.page=offset(pp,.1);
 for(const engine of ['reference','candidate']){const samples=[];for(let i=0;i<12;i++){const g=++generation,start=now(),r=await page.evaluate(({engine,g})=>workerPing(engine,g),{engine,g});samples.push({start,end:now(),remote:r.clock_ms});}clock[engine]=offset(samples,.1);}
 save('clock-calibration',clock);
 const {guardTransaction}=require('./transaction.cjs');const stopped=new Set();
 function submit(engine,f,T,g,simulations){if(!['candidate','reference'].includes(engine))throw Error('DIAGNOSTIC_BROWSER_ONLY');if(stopped.has(engine))throw Error('BACKEND_RESTART_REQUIRED');const t0=now(),gen=++generation;owners[engine]=gen;freeze(f);const prefix=J.ids(f.legal_prefix),c=engine==='native'?clock.linux:clock[engine];const early=t0+c.offset_ms-c.error_ms,req={kind:'request',type:'search',id:f.id,request_id:process.pid+'-'+gen+'-'+crypto.randomUUID(),prefix,legal_prefix:f.legal_prefix,seed:1979,generation:gen,clock_t0_ms:early,t0:early,T_ms:T,guard_ms:g,g_ms:g,simulations,max_nodes:512,max_depth:24,limits:{maxSimulations:simulations===1?0:100000},node_t0_ms:t0,node_deadline_ms:t0+T,page_offset_ms:clock.page.offset_ms,page_error_ms:clock.page.error_ms,diagnostic_step_delay_ms:f.diagnostic_step_delay_ms,diagnostic_nn_error:f.diagnostic_nn_error===true,diagnostic_corrupt_echo:f.diagnostic_corrupt_echo,terminal_diagnostic:!!J.terminalResult(J.state(f.legal_prefix))};
 freeze(req);const pending=guardTransaction({engine,req,t0,T,event:e=>fs.appendFileSync(RUN+'/transport-discard.jsonl',JSON.stringify(e)+'\n'),send:()=>engine==='native'?(native.send(req),native.next().then(payload=>({payload}))):page.evaluate(({engine,req})=>dispatch(engine,req),{engine,req}),abort:async()=>{owners[engine]=++generation;stopped.add(engine);if(engine==='native')await native.abort();else await page.evaluate(e=>abortEngine(e),engine);}});
 return {generation:gen,t0,cancel:()=>pending.cancel(),promise:pending.then(q=>{let payload=q.payload?.payload??q.payload,data=engine==='reference'?payload:payload?.data,cp=engine==='reference'?data: data?.checkpoint;const action=engine==='reference'?data?.actionRust209:cp?.action;const error=q.transaction_error??q.host_adapter_error??(engine==='reference'?data?.error:payload?.ok===false?payload?.error?.code:null);let legal=false,terminal=J.terminalResult(J.state(f.legal_prefix)),illegal=false;try{if(terminal){legal=action==null&&(engine==='reference'?data?.terminal?.value===terminal.value:cp?.terminal_value===terminal.value);}else if(action!=null){J.validate(f.legal_prefix,action);legal=true;}}catch(e){illegal=true;}const fallback=engine==='reference'?data?.fallback:cp?cp.policy_fallbacks+cp.value_fallbacks:0;const stale=q.transaction_error==='IDENTITY_MISMATCH'||owners[engine]!==gen,checkpoint=engine==='reference'?!!(data?.time?.checkpoint||terminal):data?.status==='checkpoint';const t1=now(),late=t1>=t0+T;const owned=data?.owned;const ownedBinding=engine!=='candidate'||!!(owned&&owned.identity.request_id===req.request_id&&owned.identity.generation===gen&&JSON.stringify(owned.identity.prefix)===JSON.stringify(prefix)&&owned.identity.seed===req.seed&&owned.identity.simulations===req.simulations&&owned.identity.max_nodes===req.max_nodes&&owned.identity.max_depth===req.max_depth&&JSON.stringify(owned.cp)===JSON.stringify(data.original_checkpoint));const accepted=!!(ownedBinding&&!error&&!illegal&&legal&&!late&&!stale&&checkpoint&&fallback===0);
 const cpSpans=engine==='reference'?data?.stats?.nn??[]:cp?.spans??[],nn_ms=engine==='reference'?cpSpans.map(x=>x.end-x.start):cpSpans.map(x=>x.nn_end_ms-x.feature_end_ms),step_ms=engine==='reference'?data?.stats?.steps??[]:data?.steps?.map(x=>x.end_ms-x.start_ms)??[],root_ms=engine==='reference'?data?.time?.rootFinished-data?.time?.workerStart:data?.root_ms;const finish_ms=engine==='reference'?0:Math.max(0,...(data?.steps??[]).map(x=>x.finish_ms??0));const engineFinish=engine==='reference'?data?.time?.finish:data?.adapter_end_ms;const transport_ms=Number.isFinite(engineFinish)?Math.max(0,t1-(engineFinish-c.offset_ms)):null;
 const response={engine,transaction_bound:true,owned_binding:ownedBinding,reference_nn_failure:engine==='reference'&&!!error&& !['NO_RESPONSE_TIMEOUT','BACKEND_EXIT','LATE_RESPONSE','deadline','guard','no_checkpoint','cancelled','IDENTITY_MISMATCH','PIPE_PARSE','PIPE_ERROR','PAGE_DEADLINE'].includes(error),id:f.id,request_id:req.request_id,request:req,T_ms:T,g_ms:g,generation:gen,t0_ms:t0,received_after_validation_ms:t1,elapsed_ms:t1-t0,late,overshoot_ms:Math.max(0,t1-t0-T),stale,error,illegal,legal,accepted,fallback,checkpoint,terminal,action,nn_calls:engine==='reference'?data?.stats?.nnCalls:data?.nn_calls,nn_ms,step_ms,root_ms,finish_ms,transport_ms,clock_error_ms:c.error_ms,raw:q};const delivered=now();response.received_after_validation_ms=delivered;response.elapsed_ms=delivered-t0;response.late=delivered>=t0+T;response.overshoot_ms=Math.max(0,delivered-t0-T);response.accepted=response.accepted&&!response.late;return require('./delivery.cjs').finalize(response,req,J,now);})};}

 return await run({submit,page,clock,save,verify,network,needsRestart:()=>stopped.size>0});
 }finally{if(browser)await browser.close();if(native)await native.abort();if(ping)await ping.abort();}}

module.exports={withArena,pipe};
