'use strict';const fs=require('fs'),path=require('path'),assert=require('assert/strict'),D=require('./delivery.cjs'),J=require('./judge.cjs'),{runGame,classifyFailure}=require('./game-loop.cjs'),{now}=require('./transaction.cjs');const P=path.resolve(__dirname,'../../.artifacts/ai-sigma/runs/SIGMA-ORT-ENTRY-CONTINUE'),checks=[];
const clone=x=>JSON.parse(JSON.stringify(x)),req={request_id:'delivery-fixed',generation:7,prefix:[],legal_prefix:[],seed:1979,simulations:4096,max_nodes:512,max_depth:24,T_ms:500,g_ms:91};
function response(){const cp={action:13,terminal_value:null,simulations:1,policy_fallbacks:0,value_fallbacks:0,root_edges:[[13,1,0,0]]},owned={identity:{...req},cp:clone(cp)};return {engine:'candidate',transaction_bound:true,owned_binding:true,request:req,request_id:req.request_id,generation:7,t0_ms:1000,T_ms:500,error:null,accepted:true,checkpoint:true,legal:true,illegal:false,stale:false,action:13,nn_calls:1,fallback:0,terminal:null,raw:{payload:{kind:'result',transaction:{...req,engine:'candidate'},generation:7,payload:{ok:true,data:{checkpoint:{...cp,spans:[]},original_checkpoint:cp,owned}}}}};}
(async()=>{let r=D.finalize(response(),req,J,()=>1001);assert.equal(r.accepted,true);assert.equal(typeof r.accepted,'boolean');assert.equal(r.action,13);checks.push('valid owned response shape accepted boolean and legal action');
for(const mutate of [r=>r.accepted=1,r=>r.accepted={},r=>r.action='13',r=>r.nn_calls=NaN,r=>r.raw.payload.payload.data.checkpoint.root_edges[0][1]=NaN,r=>r.raw.payload.payload.data.checkpoint.root_edges[0][1]=-1,r=>r.raw.payload.payload.data.checkpoint.simulations=NaN,r=>r.owned_binding=undefined,r=>r.raw.payload.transaction.seed++,r=>r.raw.payload.payload.data.original_checkpoint.action=5]){r=response();mutate(r);r=D.finalize(r,req,J,()=>1001);assert.equal(r.accepted,false);assert.equal(r.action,null);assert.equal(r.checkpoint,false);}checks.push('coercive accepted/invalid shape/value/prior/owned transaction all discard public action');
r=D.finalize(response(),req,J,()=>1500);assert.equal(r.accepted,false);assert.equal(r.error,'LATE_RESPONSE');assert.equal(r.action,null);assert.equal(r.received_after_validation_ms,1500);assert.equal(r.final_validation_and_serialization_before_stamp,true);checks.push('exact deadline final stamp after required validity/encoding refuses action');
const game=await runGame({prefix:[],candidateColor:1,platform:'browser',maxAddedPly:1,choose:async(engine)=>({...response(),engine,t0_ms:now()-1000,T_ms:1})});assert.equal(game.kind,'engine_loss');assert.equal(game.reason,'LATE_CALLER_VALIDATION');assert.equal(game.prefix.length,0);checks.push('final game-loop referee validation late cannot apply action');
const typed=await runGame({prefix:[],candidateColor:1,platform:'browser',maxAddedPly:1,choose:async(engine)=>({...response(),engine,accepted:1,t0_ms:now(),T_ms:500})});assert.equal(typed.kind,'invalid_pair');assert.equal(typed.prefix.length,0);checks.push('game-loop accepted nonboolean rejected as infrastructure, no move');
const scope=require('./match-entry.cjs');await assert.rejects(scope.diagnosticRealBackend({out:P+'/not-diagnostic'}),/DIAGNOSTIC_OUTPUT_SCOPE/);checks.push('real entry diagnostic exporter cannot accept arbitrary output location');fs.writeFileSync(P+'/delivery-gate.json',JSON.stringify({checks,failures:0,NN_games:0,postvalidation_stamp:true},null,2)+'\n');console.log(JSON.stringify({checks:checks.length,failures:0}));})().catch(e=>{fs.writeFileSync(P+'/delivery-gate-failure.json',JSON.stringify({error:e.message,stack:e.stack,checks}));console.error(e);process.exitCode=1});
