'use strict';const fs=require('fs'),path=require('path'),assert=require('assert/strict'),E=require('./match-entry.cjs'),{boundedStop}=require('./cleanup.cjs'),{classifyFailure}=require('./game-loop.cjs');const ROOT=path.resolve(__dirname,'../..'),RUN=ROOT+'/.artifacts/ai-sigma/runs/SIGMA-ORT-ENTRY-CONTINUE',OUT=RUN+'/diagnostic/real-golden',F=JSON.parse(fs.readFileSync(ROOT+'/.artifacts/ai-sigma/reference-fixtures/SIGMA-PARITY-PLAN/fixtures.json')).fixtures,ids=['initial-p1','asym-hv-p2','straight-jump-p2'],fixtures=ids.map(id=>F.find(f=>f.id===id)),initial=fixtures[0],goal=F.find(f=>f.id==='goal-win-legal-replay');const references=JSON.parse(fs.readFileSync(ROOT+'/.artifacts/ai-sigma/runs/SIGMA-INFERENCE-PROBE/ort-a.outputs.json')),rows=[],stops=[],sessions=[];let active=null;fs.mkdirSync(OUT,{recursive:true});const write=(name,x)=>fs.writeFileSync(OUT+'/'+name+'.json',JSON.stringify(x,null,2)+'\n');
async function start(session){assert.equal(active,null);active=await E.diagnosticRealBackend({out:OUT+'/session-'+session});sessions.push({session,loaded_warmed_reclocked:true,clock:active.clock,startup:active.startup});write('sessions',sessions);}
async function stop(session){if(!active)return;const b=active;active=null;const proof=await boundedStop(b);assert.equal(proof.remaining_pids,0);stops.push({session,UTC:new Date().toISOString(),...proof});write('stops',stops);write('stop-session-'+session,stops.at(-1));}
async function hand(session,f,engine,sample,options={}){const T=options.T??500,g=options.g??91,p=active.submit(engine,f,T,g,4096);if(options.cancel)setTimeout(()=>p.cancel(),1);const r=await p;rows.push({session,id:f.id,engine,sample,phase:options.phase??'normal',...r});write('all-responses',rows);console.log(JSON.stringify({session,id:f.id,engine,phase:options.phase??'normal',accepted:r.accepted,error:r.error,action:r.action,NN:r.nn_calls}));return r;}
(async()=>{
 await start(1);
 const numeric=await active.page.evaluate(fs=>numericThree(fs),fixtures);const numericChecks=[];for(let i=0;i<fixtures.length;i++){const f=fixtures[i],c=numeric.wasm[i],r=numeric.reference[i],ref=references.find(x=>x.id===f.id);assert.equal(c.id,f.id);assert(!r.error);assert.equal(r.fallback,0);assert.deepEqual(c.features_bits,Array.from(new Uint32Array(new Float32Array(r.features).buffer)));const n=c.logits.concat([c.value]),nr=r.policy_logits.concat([r.value]),oracle=ref.policy_logits.concat([ref.value]);assert.equal(n.length,137);for(let k=0;k<137;k++){assert(Math.abs(n[k]-oracle[k])<=1e-4+1e-4*Math.abs(oracle[k]));assert(Math.abs(nr[k]-oracle[k])<=1e-4+1e-4*Math.abs(oracle[k]));}const pm=new Map(f.legal_actions.map((a,k)=>[a.rust209,r.priors[k]]));for(let k=0;k<c.raw_legal.length;k++){const a=c.raw_prior[k],b=pm.get(c.raw_legal[k]);assert(Number.isFinite(b));assert(Math.abs(a-b)<=1e-4+1e-4*Math.abs(b));}numericChecks.push({id:f.id,features648bits:true,NN137mixed:true,prior_mixed:true});}write('numeric-raw',numeric);write('numeric-gate',{checks:numericChecks,failures:0});
 const modelFaults=await active.page.evaluate(async()=>{const p=wait('model-faults','candidate');candidate.postMessage({kind:'model_faults'});return await p;});assert.equal(modelFaults.result.short,'MODEL_LENGTH');assert.equal(modelFaults.result.hash,'MODEL_HASH');write('model-faults',modelFaults);
 const referenceNaN=await active.page.evaluate(()=>injection('NaN',990099));assert.equal(referenceNaN.error,'output_finite_value');assert.equal(classifyFailure({engine:'reference',error:referenceNaN.error,fallback:0}).kind,'invalid_pair');write('reference-nan-fault',{raw:referenceNaN,classification:classifyFailure({engine:'reference',error:referenceNaN.error,fallback:0}),NN_diagnostic:true});
 for(const f of fixtures)for(const engine of ['candidate','reference'])for(const sample of[-1,0,1]){const r=await hand(1,f,engine,sample);assert.equal(r.accepted,true,JSON.stringify({id:f.id,engine,sample,error:r.error}));assert.equal(r.fallback,0);assert.equal(r.final_validation_and_serialization_before_stamp,true);}
 for(const engine of ['candidate','reference']){const r=await hand(1,goal,engine,0,{phase:'terminal'});assert.equal(r.accepted,true);assert.equal(r.nn_calls,0);assert.equal(r.action,null);}
 const fault=await hand(1,{...initial,diagnostic_nn_error:true},'candidate',0,{phase:'candidate-NN-fault'});assert.equal(fault.accepted,false);assert.equal(fault.error,'INJECTED_NN_ERROR');assert.equal(fault.action,null);assert.equal(classifyFailure(fault).kind,'engine_loss');
 const timeout=await hand(1,{...initial,diagnostic_step_delay_ms:500},'candidate',0,{T:10,g:0,phase:'T10-delay500'});assert.equal(timeout.accepted,false);assert.equal(timeout.action,null);assert.equal(classifyFailure(timeout).kind,'engine_loss');assert.equal(active.needsRestart(),true);await stop(1);
 await start(2);for(const f of fixtures)for(const engine of ['candidate','reference']){const r=await hand(2,f,engine,0,{phase:'fresh-after-timeout'});assert.equal(r.accepted,true);}await stop(2);
 await start(3);const cancel=await hand(3,initial,'candidate',0,{cancel:true,phase:'explicit-cancel'});assert.equal(cancel.accepted,false);assert.equal(cancel.error,'cancelled');assert.equal(cancel.action,null);assert.equal(active.needsRestart(),true);await stop(3);
 await start(4);for(const engine of ['candidate','reference']){const r=await hand(4,initial,engine,0,{phase:'fresh-after-cancel'});assert.equal(r.accepted,true);}const foreign=await hand(4,{...initial,diagnostic_corrupt_echo:'engine'},'candidate',0,{phase:'foreign-producer-engine'});assert.equal(foreign.accepted,false);assert.equal(foreign.error,'IDENTITY_MISMATCH');assert.equal(foreign.action,null);assert.equal(classifyFailure(foreign).kind,'invalid_pair');assert.equal(active.needsRestart(),true);await stop(4);
 assert.equal(rows.length,32);write('real-summary',{complete:true,requests:rows.length,accepted:rows.filter(r=>r.accepted).length,normal_gate_pass:true,stops,sessions,real_games:0,holdout_sends:0,formal_clock_tail_guarantee:false,adoption:false,native_not_executed:true});console.log(JSON.stringify({complete:true,requests:rows.length,PID0:true,real_games:0}));
})().catch(async e=>{let stopError=null;try{await stop('failure')}catch(x){stopError=x.message;}write('real-failure',{UTC:new Date().toISOString(),error:e.message,stack:e.stack,rows,stops,stopError,real_games:0,holdout_sends:0});console.error(e);process.exitCode=1});
