'use strict';
async function audit118(input,fixtures,refs){
 const runs=[],games=[],samples=[],issues=[];let totalNN=0,startup=0;
 const check=(x,tag,id)=>{if(!x)throw Error('C118_'+tag+' '+(id??''));};
 for(const run of input.runs){
  const c={public:run.rows.length,legal:0,late:0,cancel:0,initial_none:0,NN:0,discard:0,opposite_before_ACK:0,oldAPI_spans_newinput:0,own_ACK_violations:0,ACKover500:0,post_public_definite:0,post_public_possible:0,cutoff_definite:0,cutoff_possible:0,worker_by_engine:{candidate:{upper_le_D:0,lower_gt_D:0,straddles:0},reference:{upper_le_D:0,lower_gt_D:0,straddles:0}},max_public:0,max_own_wait:0,accepted_CP_sequences:0};
  const own=new Map(),map=new Map(),prior=[];
  check(run.started_games===2&&run.started_requests===run.rows.length,'STARTS');check(!run.external_abort&&!run.player_errors.length&&Array.isArray(run.waiting_messages)&&run.waiting_messages.length===0&&run.main_timer_count===0,'FINAL_MAIN_ZERO');
  for(const r of run.rows){
   const id=r.identity,p=r.response,b=p.body,d=r.diagnostic,s=fromPrefix(id.legal_prefix),rid=id.request_id;
   check(!map.has(rid),'DUP_REQUEST',rid);map.set(rid,r);
   check(id.limits.seed===run.seed&&id.model==='d790dac68389f7602ff8a887a2385417d3c925fe22da7164c86e9226f943908d','MODEL_SEED',rid);
   check(id.engine===b.engine&&id.engine===r.player_engine&&d.worker_engine===id.engine&&d.player_binding===id.engine,'ENGINE_ECHO',rid);
   check(id.request_id===b.request_id&&id.request_token===rid&&id.generation===b.generation&&id.epoch===id.generation,'ID_EPOCH',rid);
   eq109(d.identity,id,'PRODUCER_ECHO');check(id.key===s._positionKey(),'KEY',rid);eq109(id.history,Array.from(s.position_history).sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:0),'HISTORY');eq109(id.prefix,rustPrefix(id.legal_prefix),'ABI_PREFIX');
   check(id.limits.simulations===(id.engine==='candidate'?4096:100000)&&id.limits.max_nodes===(id.engine==='candidate'?512:null)&&id.limits.max_depth===(id.engine==='candidate'?24:null),'LIMITS');
   check(id.t0_ms==p.t0_ms&&id.seal_ms-id.t0_ms===411&&id.commit_cutoff_ms-id.t0_ms===402&&id.deadline_ms-id.t0_ms===500&&p.planned_ms===id.seal_ms,'T_CUTOFF');
   check(p.stamp_ms>=p.timer_ms&&p.public_elapsed_ms===p.stamp_ms-id.t0_ms&&p.bytes===new TextEncoder().encode(p.body_serialized).length,'FINAL_STAMP');eq109(b,JSON.parse(p.body_serialized),'SERIALIZED_BODY');
   check([b.completed,b.cancelled,b.late].every(x=>typeof x==='boolean'),'STRICT_BOOLEAN');check(b.late===(p.stamp_ms>=id.deadline_ms),'LATE_POLICY');check(r.postpublic_immutable&&p.public_did_not_await_ACK&&r.Node_per_CP_binding_calls===0&&p.Node_clock_referee_calls===0,'IMMUTABLE_BROWSER_ROUTE');
   if(b.completed){check(!b.late&&!b.cancelled&&s.getLegalActions().some(a=>sameAction(a,b.action)),'LEGAL',rid);check(p.classification==='completed_legal','CLASSIFICATION');const cp=d.sab_publications.find(x=>x.sequence===b.sequence);check(cp&&cp.action===rustAction(s,b.action),'COMPLETED_SAB_ACTION',rid);check(Number.isSafeInteger(b.sequence)&&b.sequence>0,'SEQUENCE');c.legal++;}else{check(b.action===null,'NULL');if(b.late)c.late++;if(b.cancelled)c.cancel++;if(!b.cancelled&&!b.late)c.initial_none++;}
   let seq=0;for(const pub of d.sab_publications){check(pub.sequence>seq&&Number.isSafeInteger(pub.sequence)&&pub.validation_end_ms>=pub.begin_ms,'MONOTONE_COMPLETION',rid);seq=pub.sequence;c.accepted_CP_sequences++;}
   check(id.t0_ms>=(own.get(id.engine)??-Infinity),'OWN_PREV_ACK_ZERO',rid);check(r.own_previous_wait.end_ms<=id.t0_ms&&r.own_previous_wait.wait_ms===r.own_previous_wait.end_ms-r.own_previous_wait.start_ms,'OWN_WAIT');c.max_own_wait=Math.max(c.max_own_wait,r.own_previous_wait.wait_ms);
   const ack=r.stop;check(ack&&ack.identity.request_id===rid&&ack.identity.limits.seed===run.seed&&ack.worker_engine===id.engine,'ACK_BINDING');check(!ack.stop.handles&&!ack.stop.activeNN&&!ack.stop.live_searches&&!ack.stop.active,'ACK_ZERO');own.set(id.engine,ack.main_received_ms);
   const k=r.worker_clock;check(k.lo_ms<=k.hi_ms,'CLOCK_INTERVAL');const lower=ack.stop.at_ms-k.hi_ms,upper=ack.stop.at_ms-k.lo_ms;const wc=c.worker_by_engine[id.engine];if(upper<=id.deadline_ms)wc.upper_le_D++;else if(lower>id.deadline_ms)wc.lower_gt_D++;else wc.straddles++;if(ack.main_received_ms-id.t0_ms>500)c.ACKover500++;
   const ev=d.NN_control_events;check(Array.isArray(ev)&&ev.length===r.hand_NN,'NN_DENOMINATOR');c.NN+=ev.length;
   for(const e of ev){check(e.request_id===rid&&e.engine===id.engine&&e.generation===id.generation,'API_BINDING');check(e.session_run_end_ms>=e.session_run_start_ms,'API_ORDER');const lo=e.session_run_start_ms-k.hi_ms,hi=e.session_run_start_ms-k.lo_ms;if(lo>p.stamp_ms)c.post_public_definite++;if(hi>p.stamp_ms)c.post_public_possible++;if(lo>id.commit_cutoff_ms)c.cutoff_definite++;if(hi>id.commit_cutoff_ms)c.cutoff_possible++;if(e.result_discarded)c.discard++;}
   const previous=prior.slice().reverse().find(x=>x.identity.engine!==id.engine);if(previous){check(id.t0_ms>=previous.response.stamp_ms,'NEXT_AFTER_PUBLIC');if(id.t0_ms<previous.stop.main_received_ms)c.opposite_before_ACK++;const pk=previous.worker_clock;if(previous.diagnostic.NN_control_events.some(e=>e.session_run_start_ms-pk.hi_ms<=id.t0_ms&&e.session_run_end_ms-pk.lo_ms>=id.t0_ms))c.oldAPI_spans_newinput++;}
   c.max_public=Math.max(c.max_public,p.public_elapsed_ms);if(r.selected_numeric)samples.push(numeric109(r,s,fixtures,refs));prior.push(r);
  }
  const local=[];for(const g of run.games){let prefix=structuredClone(g.initial_prefix),s=fromPrefix(prefix);check(g.seed===run.seed&&g.fixture_id===run.fixture,'GAME_SEED_FIXTURE');const f=fixtures.find(x=>x.id===g.fixture_id);eq109(prefix,f.legal_prefix,'FIXTURE_PREFIX');check(g.actions.length===g.turn_indices.length,'GAME_COUNT');for(let n=0;n<g.actions.length;n++){check(!terminalResult(s),'AFTER_TERMINAL');const r=map.get(g.turn_indices[n]);check(r,'MISSING_TURN');eq109(r.identity.legal_prefix,prefix,'REPLAY_PREFIX');check(r.identity.engine===(s.getCurrentPlayer()===g.candidate_color?'candidate':'reference'),'COLOR_PLAYER');eq109(r.response.body.action,g.actions[n],'PUBLIC_ACTION');check(s.getLegalActions().some(a=>sameAction(a,g.actions[n])),'REPLAY_LEGAL');s=s.next(g.actions[n]);prefix.push(g.actions[n]);}const end=terminalResult(s);check(end&&end.winner===g.winner&&g.reason==='goal'&&g.status==='terminal','GOAL_TERMINAL');check(s._positionKey()===g.final_key&&s.depth===g.total_ply,'FINAL_CONTEXT');local.push({id:g.id,fixture:g.fixture_id,seed:g.seed,color:g.candidate_color,winner:end.winner,newplies:g.actions.length,prefixply:g.initial_prefix.length,totalply:g.total_ply,score:end.winner===g.candidate_color?1:end.winner===0?.5:0});}
  check(local.map(x=>x.color).join(',')==='1,2','COLOR_ORDER');games.push(...local);
  const clocks={};for(const engine of ['candidate','reference']){const end=run.clock_end[engine];const lo=Math.max(...end.samples.map(x=>x.worker_ms-x.end_ms-.1)),hi=Math.min(...end.samples.map(x=>x.worker_ms-x.start_ms+.1));check(lo===end.lo_ms&&hi===end.hi_ms&&lo<=hi,'END_CLOCK');const initial=run.rows.find(x=>x.identity.engine===engine).worker_clock;const ilo=Math.max(...initial.samples.map(x=>x.worker_ms-x.end_ms-.1)),ihi=Math.min(...initial.samples.map(x=>x.worker_ms-x.start_ms+.1));check(ilo===initial.lo_ms&&ihi===initial.hi_ms,'START_CLOCK');clocks[engine]={initial:{lo:ilo,hi:ihi},end:{lo,hi},mid_shift:(lo+hi-ilo-ihi)/2,intermediate_drift_unmeasured:true};}
  const sn=run.startup_rows.reduce((a,x)=>a+x.NN,0);check(sn===6&&run.startup_rows.every(x=>x.zero),'STARTUP_SEPARATE');startup+=sn;totalNN+=c.NN;runs.push({run:run.run,seed:run.seed,fixture:run.fixture,counts:c,clocks,Xi:local.reduce((a,x)=>a+x.score,0)/2,startup_NN:sn});
 }
 return {runs,games,W:games.filter(x=>x.score===1).length,D:games.filter(x=>x.score===.5).length,L:games.filter(x=>x.score===0).length,public:runs.reduce((a,x)=>a+x.counts.public,0),legal:runs.reduce((a,x)=>a+x.counts.legal,0),hand_NN:totalNN,startup_NN:startup,numeric_samples:samples,shared_RuleA_independence_limit:true,browser_adjudicated:true,new_NN_model_load_games:0,formal_go:false,issues};
}
function typed118(){
 const rows=[];const base={completed:false,shared_state:SharedBestAction.STATE.FAULT};
 for(const error of ['NN_BACKEND:DIAGNOSTIC','MODEL_MISMATCH','FALLBACK','FINAL_IDENTITY'])for(const engine of ['candidate','reference']){const fault={error},c=classifyResponse(base,fault),r=gameFailureResult(c,1,engine,fault);const expected=/IDENTITY/.test(error)?'shared_identity_failure':engine==='reference'?'reference_NN_invalid':'engine_fault';must109(r.reason===expected,'FAULT_RULE');rows.push({engine,error,classification:c,result:r});}
 for(const extra of [{late:true},{judge_error:'diagnostic'},{external_abort:{code:'diagnostic'}}]){const r={...base,...extra},fault={error:'NN_BACKEND:diagnostic'},c=classifyResponse(r,fault),flags=responseCauses(r,fault);must109(c!=='engine_fault'&&flags.shared_fault&&flags.received_engine_fault,'SIMULTANEOUS_FLAGS');rows.push({classification:c,flags});}
 return {rows,NN:0};
}
async function seed118(row){
 const proof=[];
 for(const seed of [1979,2098]){
  let created;const cp={action:null,terminal_value:1,policy_fallbacks:0,value_fallbacks:0,simulations:0,nn_calls:0,root_edges:[]};const backend={create:req=>(created=req,1),free:()=>{},call:req=>req.op==='raw'?{effective_legal:[],terminal:{value:1}}:req.op==='begin'?{done:true}:cp,e:{memory:{buffer:{byteLength:1}}}};
  const result=await runOwned({generation:1,request_id:'independent-seed-'+seed,prefix:[],seed,simulations:4096,max_nodes:512,max_depth:24},{b:backend,epoch:()=>10,yieldTask:async()=>{},getGeneration:()=>1});must109(created.seed===seed&&result.owned.identity.seed===seed,'SEED_TO_ABI');
  const id=structuredClone(row.identity);id.limits.seed=seed;id.t0_ms=1000;id.deadline_ms=1500;id.commit_cutoff_ms=1402;
  const latest=row.selected_numeric.cp;const message={kind:'snapshot',identity:id,producer_identity:id,sequence:1,owned:{identity:{request_id:id.request_id,generation:id.generation,fixture:null,prefix:id.prefix,seed,simulations:4096,max_nodes:512,max_depth:24},cp:latest,completed_at:1001,completed_token:1,completed_NN:latest.nn_calls,NN_attempts:latest.nn_calls,pending_token:null},value:row.selected_numeric.numeric.value,sent_ms:1002};const expected={legal:latest.root_edges.map(x=>x[0]),terminal:null};const receiver=new SnapshotCache(id,expected,()=>1003);must109(receiver.receive(message),'CORRECT_SEED_CACHE');const foreign=structuredClone(message);foreign.owned.identity.seed=seed===1979?2098:1979;const reject=new SnapshotCache(id,expected,()=>1003);must109(!reject.receive(foreign)&&reject.events[0].error==='OWNED_IDENTITY','FOREIGN_SEED');proof.push({seed,ABI_seed:created.seed,owned_seed:result.owned.identity.seed,cache_accept:true,foreign_reject:true,NN:0});
 }
 return proof;
}
function aggregate118(input){
 const median=a=>{const x=a.slice().sort((a,b)=>a-b);return x.length%2?x[(x.length-1)/2]:(x[x.length/2-1]+x[x.length/2])/2;},engines={};
 for(const engine of ['candidate','reference']){const rows=input.runs.flatMap(x=>x.rows.filter(r=>r.identity.engine===engine));const cp=rows.map(r=>r.diagnostic.sab_publications[0].validation_end_ms-r.worker_clock.mid_ms-r.identity.t0_ms),api=rows.map(r=>r.diagnostic.NN_control_events[0]).map(x=>x.session_run_end_ms-x.session_run_start_ms),timer=rows.map(r=>r.response.timer_ms-r.response.planned_ms),final=rows.map(r=>r.response.stamp_ms-r.response.timer_ms);engines[engine]={n:rows.length,firstCP_median_ms:median(cp),firstAPIawait_median_ms:median(api),max_timer_lateness_ms:Math.max(...timer),max_timer_to_stamp_ms:Math.max(...final),max_ACKwall_ms:Math.max(...rows.map(r=>r.stop.main_received_ms-r.identity.t0_ms)),meanings:'firstCP includes preparation/root/scheduling; APIawait is not kernelCPU; ACKwall is not CPUtime'};}
 const traces=input.runs.map(r=>({run:r.run,seed:r.seed,action_trace:r.games.map(g=>JSON.stringify(g.actions))})),seedPairs=[];for(let i=0;i<3;i++)seedPairs.push({fixture:input.runs[i].fixture,same_color1_traces:traces[i].action_trace[0]===traces[i+3].action_trace[0],same_color2_traces:traces[i].action_trace[1]===traces[i+3].action_trace[1],different_seed_does_not_require_different_Action:true});return {engines,seedPairs,NN:0,browser_computed:true};
}

function cache118(input){const runs=[],marker_examples=[];for(const run of input.runs){let accepted=0,rejected=0,selected=0,accepted_after_cutoff=0,selected_publish_definite_after=0,selected_publish_possible_after=0;for(const r of run.rows){const id=r.identity,b=r.response.body,k=r.worker_clock,d=r.diagnostic;for(const e of d.validation_events){if(e.accepted){accepted++;if(e.validation_finished_ms>=id.commit_cutoff_ms)accepted_after_cutoff++;}else rejected++;}const e=d.validation_events.find(e=>e.accepted&&e.sequence===b.sequence),pub=d.sab_publications.find(e=>e.sequence===b.sequence);must109(e&&pub&&e.validated_cache_ms===e.validation_finished_ms&&e.validation_finished_ms<id.commit_cutoff_ms,'ADOPTED_VALIDATED_CACHE');selected++;if(pub.validation_end_ms-k.hi_ms>id.commit_cutoff_ms){selected_publish_definite_after++;marker_examples.push({request:id.request_id,engine:id.engine,sequence:b.sequence,cache_validated_elapsed_ms:e.validation_finished_ms-id.t0_ms,publication_end_elapsed_interval_ms:[pub.validation_end_ms-k.hi_ms-id.t0_ms,pub.validation_end_ms-k.lo_ms-id.t0_ms],timer_elapsed_ms:r.response.timer_ms-id.t0_ms,stamp_elapsed_ms:r.response.stamp_ms-id.t0_ms,exact_Atomic_store_time_missing:true});}if(pub.validation_end_ms-k.lo_ms>id.commit_cutoff_ms)selected_publish_possible_after++;}runs.push({run:run.run,accepted,rejected,selected,accepted_after_cutoff,selected_publish_definite_after,selected_publish_possible_after,publish_end_is_saved_marker_not_exact_Atomic_store_time:true});}return {runs,marker_examples,browser_computed:true,NN:0};}

function connect118(input){const result=[];for(const run of input.runs){let legal=0,NN=0;for(const r of run.rows){const id=r.identity,p=r.response,b=p.body,s=fromPrefix(id.legal_prefix);must109(id.engine===b.engine&&id.generation===b.generation&&id.request_id===b.request_id,'CONNECT_BIND');must109(b.completed&&!b.late&&!b.cancelled&&s.getLegalActions().some(a=>sameAction(a,b.action)),'CONNECT_LEGAL');must109(p.stamp_ms-id.t0_ms<500,'CONNECT_T');const ev=r.diagnostic.NN_control_events;must109(ev.length===r.hand_NN,'CONNECT_NN');NN+=ev.length;legal++;}const startup=run.startup_rows.reduce((a,r)=>a+r.NN,0);result.push({run:run.run,public:run.rows.length,legal,hand_NN:NN,startup_NN:startup,primary:run.primary,secondary:run.secondary,failed_checker_not_NN_negative:run.rows.length===0});}must109(result[0].public===0&&result[0].hand_NN===0&&result[1].public===2&&result[1].hand_NN===18&&result[1].startup_NN===6,'CONNECT_DENOMINATORS');return {runs:result,separate_from_game644:true,new_NN:0,browser_computed:true};}
