'use strict';
const ok133=(v,m)=>{if(!v)throw Error('INDEPENDENT133_'+m)},eq133=(a,b,m)=>ok133(JSON.stringify(a)===JSON.stringify(b),m),hist133=h=>[...h].sort((a,b)=>a[0].localeCompare(b[0]));
function close133(a,b){return Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a-b)<=1e-4+1e-4*Math.abs(b)}
function features133(s){const f=s.toNNInput();return Array.from(new Uint32Array(f.buffer,f.byteOffset,f.length))}
function nn133(n,s){ok133(n&&n.features_bits.length===648&&n.policy_logits.length===136&&n.policy_logits.every(Number.isFinite)&&Number.isFinite(n.value)&&Math.abs(n.value)<=1,'NN_SHAPE_FINITE');eq133(n.features_bits,features133(s),'FEATURE_BITS');return [ ...n.policy_logits,n.value ];}
function priors133(r,s){const acts=s.getLegalActions(),ids=acts.map(a=>rustAction(s,a)),flip=[1,0,2,3,6,7,4,5],canon=k=>s.isPlayer1Turn()?k:k<8?flip[k]:8+Math.floor((k-8)/64)*64+(7-Math.floor(((k-8)%64)/8))*8+(k-8)%8,ix=acts.map(a=>canon(actionToIndex(a,9))),n=r.numeric[0],mx=Math.max(...ix.map(i=>n.policy_logits[i])),w=ix.map(i=>Math.exp(n.policy_logits[i]-mx)),total=w.reduce((a,b)=>a+b,0),map=new Map(ids.map((id,i)=>[id,w[i]/total]));eq133(r.cp.root_edges.map(e=>e[0]),r.engine==='candidate'?ids.slice().sort((a,b)=>a-b):ids,'LEGAL_ORDER');let max=0;for(const e of r.cp.root_edges){ok133(e.length===4&&e.every(Number.isFinite)&&e[1]>=0&&Number.isSafeInteger(e[2])&&e[2]>=0&&Math.abs(e[3])<=e[2]+1e-4,'EDGE_FINITE');ok133(close133(e[1],map.get(e[0])),'ACTION_PRIOR');max=Math.max(max,Math.abs(e[1]-map.get(e[0])));}return max;}
function row133(r,f){ok133(!r.primary&&!r.main_gate_error&&r.worker_engine===r.engine&&r.cp.generation===r.generation,'ROW_BIND');const s=fromPrefix(f.legal_prefix);eq133(hist133(s.position_history),hist133(f.history_counts),'ROOT_HISTORY');ok133(s._positionKey()===f.history_count_key&&s.depth===f.board.total_ply,'ROOT_KEY_PLY');eq133(features133(s),f.features_bits,'FIXED_FEATURES');const K=r.spec.K,edge=r.cp.root_edges.reduce((a,e)=>a+e[2],0);ok133(r.completed_backups===K&&edge===K-1&&r.NN_calls===r.spans.length&&r.terminal_noNN_backups===K-r.NN_calls,'COUNT_DENOMINATORS');ok133((r.engine==='candidate'?r.cp.tree[0].visits:r.cp.root_visits)===K,'ROOT_N');ok133(r.zero.handles===0&&r.zero.activeNN===0&&!r.zero.active,'ZERO');ok133(s.getLegalActions().some(a=>rustAction(s,a)===r.cp.action),'ACTION_LEGAL');nn133(r.numeric[0],s);const maxPrior=priors133(r,s),nodes=[];
for(const n of r.trace??[]){const actions=r.engine==='candidate'?n.pre.path.map(e=>e.action):n.path_actions;let t=s;for(const id of actions){const a=t.getLegalActions().find(a=>rustAction(t,a)===id);ok133(a,'TRACE_PATH_LEGAL');t=t.next(a);}ok133(t._positionKey()===n.key&&t.depth===n.ply&&(t.isPlayer1Turn()?0:1)===n.turn,'TRACE_KEY_SIDE');eq133(hist133(t.position_history),hist133(n.history),'TRACE_HISTORY');eq133(features133(t),n.features_bits,'TRACE_FEATURES');const num=nn133(n.numeric,t);ok133(close133(n.leaf_side_value,n.numeric.value)&&n.terminal===null,'NONTERMINAL_VALUE');const before=r.engine==='candidate'?n.pre.path:n.pre_path,after=n.post_path;
for(let i=0;i<actions.length;i++){const dv=r.engine==='candidate'?after[i].edge_visits-before[i].edge_visits:after[i].child_visits-before[i].child_visits,delta=r.engine==='candidate'?after[i].edge_value_sum-before[i].edge_value_sum:-(after[i].child_valueSum-before[i].child_valueSum),want=n.leaf_side_value*((actions.length-i)%2?-1:1);ok133(dv===1&&close133(delta,want),'BACKUP_SIGN_DELTA');}
if(r.engine==='candidate')ok133(n.post_leaf_visits-n.pre.leaf_visits===1&&n.parentQ_missing,'LEAF_CANDIDATE');else ok133(n.post_leaf.visits-n.pre_leaf.visits===1&&close133(n.post_leaf.valueSum-n.pre_leaf.valueSum,n.leaf_side_value),'LEAF_REFERENCE');nodes.push({canonical:JSON.stringify([n.key,n.ply,hist133(n.history)]),root:actions.length===0,actions,turn:n.turn,num,features:n.features_bits});}
ok133(nodes.length<9,'TRACECAP8');for(const p of r.spans)ok133(p.wrapper_end_ms>=p.wrapper_start_ms&&p.API_end_ms>=p.API_start_ms,'SPAN');return {fixture:r.fixture_id,engine:r.engine,phase:r.spec.phase,K,action:r.cp.action,backups:K,NN:r.NN_calls,terminal_noNN:r.terminal_noNN_backups,rootN:K,edge,visits:r.cp.root_edges.map(e=>[e[0],e[2]]),entropy:r.cp.root_edges.reduce((a,e)=>e[2]?a-e[2]/edge*Math.log(e[2]/edge):a,0),maxPrior,nodes};}
function audit133(raw,fixed){const rs=raw.deep_results.map(r=>row133(r,fixed.fixtures.find(f=>f.id===r.fixture_id))),comparisons=[],parity=[];for(const f of fixed.fixtures){const pair=rs.filter(r=>r.fixture===f.id&&r.phase==='primary'),a=pair.find(r=>r.engine==='candidate'),b=pair.find(r=>r.engine==='reference');if(!a||!b)continue;const bm=new Map(b.visits);ok133(a.visits.length===b.visits.length&&a.visits.every(e=>bm.has(e[0])),'TV_DOMAIN');let L1=a.visits.reduce((sum,e)=>sum+Math.abs(e[1]-bm.get(e[0])),0),root=0,deep=0,maxNN=0;const matches=[];for(const x of a.nodes){const y=b.nodes.find(y=>y.canonical===x.canonical);if(!y)continue;eq133(x.features,y.features,'SHARED_FEATURES');eq133(x.actions,y.actions,'SHARED_PATH');ok133(x.turn===y.turn,'SHARED_SIDE');for(let i=0;i<137;i++){ok133(close133(x.num[i],y.num[i]),'SHARED_NN');maxNN=Math.max(maxNN,Math.abs(x.num[i]-y.num[i]));}if(x.root)root++;else deep++;matches.push({root:x.root,actions:x.actions});}comparisons.push({fixture:f.id,actions:[a.action,b.action],TV:L1/(2*a.edge),L1visits:L1,sharedroot:root,sharednonroot:deep,unsharedA:a.nodes.length-root-deep,unsharedB:b.nodes.length-root-deep,maxNN,matches});}
for(const e of ['candidate','reference']){const p=raw.deep_results.filter(r=>r.spec.phase==='parity'&&r.engine===e);if(!p.length)continue;ok133(p.length===2,'PARITY2');for(const k of ['action','simulations','root_edges','nn_calls','max_depth','cap','root_visits'])eq133(p[0].cp[k],p[1].cp[k],'PARITY_'+k);eq133(p[0].numeric[0],p[1].numeric[0],'PARITY_NUMERIC');parity.push({engine:e,K:8,exact_CP:true,load_effect_uncalibrated:true});}
return {browser_computed:true,rows:rs.map(({nodes,...r})=>({...r,selected:nodes.length})),comparisons,parity,searches:rs.length,backups:rs.reduce((a,r)=>a+r.K,0),NN:rs.reduce((a,r)=>a+r.NN,0),sharedroot:comparisons.reduce((a,r)=>a+r.sharedroot,0),sharednonroot:comparisons.reduce((a,r)=>a+r.sharednonroot,0),terminal_noNN:rs.reduce((a,r)=>a+r.terminal_noNN,0),fixedgolden_mid_reference:0,sharedRuleA:true,candidate_parentQ_unobserved:true,formal_go:false};}
async function run133(config,fixed){installDeepHandler();const errors=[];for(const spec0 of config.searches){const spec={...spec0,phase:'primary',instrumented:true},fixture=fixed.fixtures.find(f=>f.id===spec.fixture_id),id=config.run_id+'-'+(deepRows.length+1),generation=++generationCounter;try{await settlePlayerSearches();const waiting=waitingMessage('deep-'+id,config.count_timeout_ms+5000);slotFor(spec.engine).worker.postMessage({kind:'deep_search',id,engine:spec.engine,generation,fixture,K:spec.K,timeout_ms:config.count_timeout_ms,instrumented:true});const row=await waiting;row.spec=spec;deepRows.push(row);row133(row,fixture);}catch(e){errors.push({spec,message:e.message,stack:e.stack});break;}}return {deep_results:deepRows,errors,planned:4,completed:deepRows.filter(r=>!r.primary).length};}
