import pathlib,json,datetime,hashlib
R=pathlib.Path(__file__).resolve().parents[2];O=R/'.artifacts/ai-sigma/resume-20261002/DEEP-NODE-INDEPENDENT';T=R/'tools/ai-sigma-deep-node-independent';D=R/'research-data/ai-sigma/133-deep-node-independent';sha=lambda b:hashlib.sha256(b).hexdigest()
p=O/'runs/p133-count-r1.process.json';job=json.loads(p.read_text());ids=job['tracked']+[{'pid':job['runner_pid'],'start_ticks':job['runner_starttick']}];live=[]
for x in ids:
 try:
  s=pathlib.Path(f"/proc/{x['pid']}/stat").read_text().rsplit(')',1)[1].split()
  if int(s[19])==x['start_ticks']:live.append(x)
 except FileNotFoundError:pass
assert not live and not job['remaining'] and not job['unknown_adopted']
run=O/'runs/p133-count-r1';stop={'issue':'quoridor-4lc.133','UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'boot':pathlib.Path('/proc/sys/kernel/random/boot_id').read_text().strip(),'identities':ids,'current_same_identity':live,'currentabsence_not_natural_or_allperiod':True,'job':{k:job[k] for k in ['start','end','exit','stop_reason','peak_group_plus_runner_RSS','peak_allocated_bytes','remaining','unknown_adopted','all_observed_TIDs_at_assigned_CPU']},'Model2_drop':json.loads((run/'model-drop.json').read_text()),'main_timers':json.loads((run/'main-timers-stop.json').read_text()),'monitor_callback_stop':json.loads((run/'monitor-stop.json').read_text()),'inner_controlled_stop':json.loads((run/'controlled-stop.json').read_text()),'source_write_stopped':True,'source':{str(p.relative_to(R)):sha(p.read_bytes()) for p in T.iterdir() if p.is_file()},'new_primary_planned':4,'new_primary_completed':4,'NN':128,'startup_separate':6,'new_game':0,'launch_admission_incomplete':True,'launch_failure_detail':'exe permission/read race in own admission checker; sequential shell launched runner despite previous exit1; no saved successful launch admission, no retrospective completion','formal_go':False};(D/'runtime-source-stopped-before-report.json').write_text(json.dumps(stop,indent=2)+'\n')
(O/'heavy-stop-report.txt').write_text('目標quoridor-4lc / 本文133。heavy/Chrome/NN停止済み、指定4K32=128backup/128手NN、startup6別、対局0。入力3 A161/B133・TV20/31、入力4 A32/B42・TV26/31を再現。保存root4/nonroot9のNN/features/backup符号支持。Model2zero/main timer-message/monitor callback/innercontrolled/outerwaitと現在不在を別保存。現在identity '+str(len(ids))+'不在、outerremaining/unknown空。134は本人のheadroom/外heavy確認後heavyへ進めます。本起動前admission checker失敗後にも起動した不足は保存、過去gate成功にはしません。停止正本 research-data/ai-sigma/133-deep-node-independent/runtime-source-stopped-before-report.json SHA '+sha((D/'runtime-source-stopped-before-report.json').read_bytes())+'。正式公平性/NI/係数採用未認定。本文準備中。\n');print(json.dumps({'self_current0':len(ids),'stopSHA':sha((D/'runtime-source-stopped-before-report.json').read_bytes()),'peakRSS':job['peak_group_plus_runner_RSS']}))
