import json,pathlib,math,statistics,struct,hashlib,datetime
R=pathlib.Path(__file__).resolve().parents[2];A=R/'.artifacts/ai-sigma/resume-20261003/CPU-CONCURRENCY/runs';D=R/'research-data/ai-sigma/159-cpu-concurrency';reg=json.loads((D/'preregister.json').read_text());fixed=json.loads((D/'initial-input.json').read_text())['fixtures'][0];old=json.loads((R/'.artifacts/ai-sigma/resume-20261003/SIGMA-WEB-PORT/runs/port151-stageA-r2/browser-result.json').read_text());root=next(x for x in old['rows'] if x['fixture_id']=='initial-p1' and x['engine']=='reference')['numeric'][0]
def f32(v):return struct.unpack('<I',struct.pack('<f',v))[0]
def mean(xs):return statistics.mean(xs) if xs else None
rows=[];arenas=[];modes=[]
for mode in reg['modes']:
 job=A/('concurrency159-'+mode['id']+'-r1');processfile=A/(job.name+'.process.json');p=json.loads(processfile.read_text()) if processfile.exists() else None
 for core in mode['cores']:
  ad=job/('arena-'+str(core));resultfile=ad/'result.json';result=json.loads(resultfile.read_text()) if resultfile.exists() else {'rows':[],'hand_NN':None};startup=json.loads((ad/'startup.json').read_text()) if (ad/'startup.json').exists() else None;asummary=json.loads((ad/'summary.json').read_text()) if (ad/'summary.json').exists() else None
  for ordinal,engine in enumerate(reg['requests']):
   r=next((x for x in result['rows'] if x['spec']['ordinal']==ordinal),None)
   if r is None:rows.append({'mode':mode['id'],'core':core,'ordinal':ordinal,'engine':engine,'phase':'warm' if ordinal<2 else 'steady','class':'unstarted_or_missing','known':False});continue
   nn=r['diagnostic'].get('NN_control_events',[]);numeric=r['diagnostic'].get('numeric',[None])[0];clock=r['worker_clock'];first=r.get('firstCP');adopt=r.get('adoptedCP');cp=r['diagnostic'].get('validated_cp');parity=numeric is not None and numeric['features_bits']==root['features_bits'] and [f32(x) for x in numeric['policy_logits']+[numeric['value']]]==[f32(x) for x in root['policy_logits']+[root['value']]];context=r['identity']['key']==fixed['history_count_key'] and r['identity']['history']==sorted(fixed['history_counts'],key=lambda x:x[0]) and r['identity']['legal_prefix']==fixed['legal_prefix'];apis=[x['session_run_end_ms']-x['session_run_start_ms'] for x in nn];first_bounds=None
   if first:first_bounds={'lower_ms':first['begin_ms']-clock['hi_ms']-r['identity']['t0_ms'],'upper_ms':first['validation_end_ms']-clock['lo_ms']-r['identity']['t0_ms'],'actual_atomicstore_timestamp_missing':True}
   row={'mode':mode['id'],'core':core,'ordinal':ordinal,'engine':engine,'phase':r['request_phase'],'class':r['calibration_class'],'known':True,'root_features_NN137_f32bits_exact':parity,'root_context_exact':context,'hand_API_starts':len(nn),'API_returns':len(nn),'API_sum_ms':sum(apis),'first_API_ms':apis[0] if apis else None,'later_API_ms':apis[1:],'mean_API_ms':mean(apis),'firstCP_interval':first_bounds,'adopted_NN':adopt.get('completed_NN') if adopt else None,'adopted_backup':adopt.get('completed_backup') if adopt else None,'last_CP_backup':r['completed_backup_convention'].get('completed_backup'),'terminal_noNN_last_CP':r['completed_without_NN'].get('count'),'terminal_noNN_direct_vs_derived':r['completed_without_NN'],'public_elapsed_ms':r['response']['public_elapsed_ms'],'public_stamp_ms':r['response']['stamp_ms'],'t0_ms':r['identity']['t0_ms'],'public_late':r['response']['body']['late'],'chosen209':adopt.get('action') if adopt else None,'ACK_wall_ms':r['ACK_wall_ms'],'worker_stop_interval_main':r['worker_stop_interval_main'],'post_public_API_definite':r['post_public_NN_definite'],'returned_after_public_discard':r['NN_returned_after_public'],'selfwait_ms':r['own_previous_wait']['wait_ms'],'barrier':r['barrier'],'clock':{k:clock[k] for k in ['lo_ms','hi_ms','mid_ms','error_ms']},'residual_kernelCPU':None,'Worker_TID_binding':None};rows.append(row)
  steady=[x for x in rows if x['mode']==mode['id'] and x['core']==core and x['phase']=='steady' and x['known']];arenas.append({'mode':mode['id'],'core':core,'started':len(result['rows']),'planned':6,'startup_NN':startup['startup_NN'] if startup else None,'hand_NN':result['hand_NN'],'inner_summary':asummary,'steady_mean_API_ms':mean([x['mean_API_ms'] for x in steady]),'steady_adopted_backups':sum(x['adopted_backup'] or 0 for x in steady),'steady_API_starts':sum(x['hand_API_starts'] for x in steady),'steady_firstCP_mid_mean_ms':mean([(x['firstCP_interval']['lower_ms']+x['firstCP_interval']['upper_ms'])/2 for x in steady if x['firstCP_interval']]),'current_arena_RSS_samples':None,'initial_and_peak_per_PID_in_outer_process_file':True})
 mr=[x for x in rows if x['mode']==mode['id'] and x['known']];steady=[x for x in mr if x['phase']=='steady'];steady_span=max(x['t0_ms']+x['ACK_wall_ms'] for x in steady)-min(x['t0_ms'] for x in steady) if steady else None;skews=[]
 for ordinal in range(6):
  phase=[x for x in mr if x['ordinal']==ordinal]
  if phase:skews.append({'ordinal':ordinal,'release_skew_ms':max(x['barrier']['release_ms'] for x in phase)-min(x['barrier']['release_ms'] for x in phase),'t0_skew_ms':max(x['t0_ms'] for x in phase)-min(x['t0_ms'] for x in phase),'epoch_cross_browser_clock_not_independently_bound':True})
 modes.append({'mode':mode['id'],'cores':mode['cores'],'started':len(mr),'planned':len(mode['cores'])*6,'steady_span_until_ACK_ms':steady_span,'barrier_skews':skews,'process':{k:p[k] for k in ['start','end','exit','stop_reason','peak_group_plus_runner_RSS','remaining','unknown_adopted','affinity_violations','all_observed_TIDs_at_assigned_CPU','allowed_compute_pool']} if p else None})
comparisons=[]
for mode in ['mode2','mode4']:
 matches=[x for x in arenas if x['mode']==mode]
 for x in matches:
  solo=next(a for a in arenas if a['mode']=='solo'+str(x['core']));comparisons.append({'mode':mode,'core':x['core'],'steady_API_await_ratio_parallel_over_solo':x['steady_mean_API_ms']/solo['steady_mean_API_ms'] if solo['steady_mean_API_ms'] else None,'steady_adopted_backup_ratio':x['steady_adopted_backups']/solo['steady_adopted_backups'] if solo['steady_adopted_backups'] else None,'not_sameCPU_or_kernelNN_claim':True})
 p=next(x for x in modes if x['mode']==mode);solo_spans=sum(next(s['steady_span_until_ACK_ms'] for s in modes if s['mode']=='solo'+str(core)) for core in p['cores']);p['reference_parallel_coefficient_steady_batch_wall']=solo_spans/p['steady_span_until_ACK_ms'] if p['steady_span_until_ACK_ms'] else None;p['coefficient_includes_program_barriers_ACK_and_between_request_work_not_WDL_speedup']=True
summary={'issue':'quoridor-4lc.159','planned':60,'started_saved':sum(x['known'] for x in rows),'unstarted_or_missing':sum(not x['known'] for x in rows),'classes':{c:sum(x['class']==c for x in rows) for c in sorted(set(x['class'] for x in rows))},'hand_NN':sum(x['hand_API_starts'] for x in rows if x['known']),'startup_NN':sum(x['startup_NN'] or 0 for x in arenas),'root_numeric_all_exact':all(x['root_features_NN137_f32bits_exact'] and x['root_context_exact'] for x in rows if x['known']),'warm_steady_separate':True,'formal_ready':False,'formal_unresolved':['residual inference kernelCPU and workerTID binding missing; isolated requests wait bothzero so normal opponent overlap not tested','per-arena aggregate currentRSS time series missing; outer aggregate and perPID current-first-observation/max retained','exact Atomicstore timestamp missing; firstCP interval uses publication/validation envelope','solo2 inner registration/control failure retained, no scientific row retry'],'no_WDL_or_NI_samples':True,'rows':rows,'arenas':arenas,'modes':modes,'comparisons':comparisons,'same_writer_saved_arithmetic_not_independent':True}
(D/'results.json').write_text(json.dumps(summary,indent=2)+'\n');print(json.dumps({k:summary[k] for k in ['planned','started_saved','classes','hand_NN','startup_NN','root_numeric_all_exact','formal_ready']}));print(json.dumps(comparisons));print(json.dumps([{k:m.get(k) for k in ['mode','steady_span_until_ACK_ms','reference_parallel_coefficient_steady_batch_wall']} for m in modes]))
