'use strict';const fs=require('fs'),path=require('path'),{execFile}=require('child_process'),{Ledger}=require('../ai-sigma-actual-boundary-repair/owned-ledger.cjs');const ROOT=path.resolve(__dirname,'../..'); // Private read/late-failure adapter; shared original is read-only.
const identity=pid=>{const s=fs.readFileSync('/proc/'+pid+'/stat','utf8').split(')').at(-1).trim().split(/\s+/);return{pid,starttick:Number(s[19]),PPID:Number(s[1]),ppid:Number(s[1]),state:s[0]}};
function typed(code,cause){const e=new Error(code);e.code=code;if(cause)e.cause={name:cause.name,message:cause.message,code:cause.code??null,signal:cause.signal??null,killed:cause.killed??null};return e;}
function observerLedger(self){if(!process.env.SIGMA_OWNED_LEDGER)return null;let root=self;try{const a=JSON.parse(fs.readFileSync(process.env.SIGMA_OWNED_ACK));const k=a.kernel_boundary?.root;if(k&&a.kernel_boundary.valid&&a.kernel_boundary.sole_explicit_root&&a.boot_id===fs.readFileSync('/proc/sys/kernel/random/boot_id','utf8').trim()){let parent=self;const seen=new Set();while(parent.pid!==k.pid&&!seen.has(parent.pid)){seen.add(parent.pid);parent=identity(parent.PPID);}if(parent.pid!==k.pid||parent.starttick!==k.start_ticks)throw typed('OBSERVER_ROOT_ANCESTRY_REFUSED');root={pid:k.pid,starttick:k.start_ticks};}}catch(e){if(e.code!=='ENOENT')throw e;}const ledger=new Ledger(root);if(root.pid!==self.pid)ledger.add(self,identity(self.PPID));return ledger;}
function createMonitor({out,subjectIssue,deadlineUTC,diagnosticCase=null,windowEndUTC='2026-10-02T00:50:00Z'}){const deadline=Date.parse(deadlineUTC);if(!Number.isFinite(deadline)||!Number.isFinite(Date.parse(windowEndUTC))||deadline>Date.parse(windowEndUTC))throw typed('MONITOR_CONTROL_DEADLINE_INVALID');let state='UNREADY',failure=null,inflight=null,timer=null,closed=false;const rows=[],pending=new Map(),self=identity(process.pid),ledger=observerLedger(self);
const save=(name,data)=>fs.writeFileSync(out+'/'+name+'.json',JSON.stringify(data)+'\n');const snapshot=()=>({UTC:new Date().toISOString(),state,failure,deadlineUTC,subjectIssue,rows,pending_children:[...pending.keys()],clock_cost_not_subtracted:true});
function check(){if(Date.now()>=deadline)throw typed('PROCESSING_DEADLINE');if(fs.existsSync(out+'/PAUSE'))throw typed('PAUSED');if(failure)throw typed(failure.code,failure.cause);if(state!=='READY')throw typed('UNREADY');return true;}
function read(id,attempt=0){return new Promise((resolve,reject)=>{const startUTC=new Date().toISOString(),capture=out+'/beads-read-'+id+'.json',child=execFile('bash',['-c','bash "$1" show "$2" --json > "$3"','concurrency159-read',ROOT+'/scripts/dev/beads.sh',id,capture],{encoding:'utf8',timeout:5000,env:{...process.env,UV_NO_SYNC:'1',UV_OFFLINE:'1',PYTHONDONTWRITEBYTECODE:'1'}},(error,ignoredStdout)=>{let stdout='';const row={id,PID:child.pid,startUTC,endUTC:new Date().toISOString(),exitCode:child.exitCode,signalCode:child.signalCode,error:error?.message??null};pending.delete(child.pid);try{stdout=fs.readFileSync(capture,'utf8');row.output_bytes=Buffer.byteLength(stdout);row.output_SHA256=require('crypto').createHash('sha256').update(stdout).digest('hex');row.output_path=capture;row.attempt=attempt;if(error)throw typed('BEADS_READ_ERROR',error);let d;try{d=JSON.parse(stdout)[0]}catch(e){throw typed('BEADS_SCHEMA_ERROR',e)}row.status=d?.status;row.labels=d?.labels;rows.push(row);if(!d)throw typed('BEADS_SCHEMA_ERROR');if(['blocked','closed','deferred'].includes(d.status)||d.labels?.includes('paused-by-user'))throw typed('PAUSED');resolve(d);}catch(e){if(!rows.includes(row))rows.push(row);if(e.code==='BEADS_SCHEMA_ERROR'){fs.copyFileSync(capture,out+'/beads-read-failure-'+id+'-'+Date.now()+'-'+attempt+'.json');if(attempt===0&&Date.now()<deadline&&!closed&&!fs.existsSync(out+'/PAUSE')){state='BEADS_SCHEMA_ERROR_RETRY';rows.push({kind:'bounded_schema_read_retry',id,attempt:1,original_failure:e.code,UTC:new Date().toISOString()});resolve(read(id,1));return;}}reject(e);}});pending.set(child.pid,child);try{const z=identity(child.pid);ledger?.add(z,self);rows.push({...z,kind:'owned_observer_child',parent:self,startUTC,boot:fs.readFileSync('/proc/sys/kernel/random/boot_id','utf8').trim()});}catch(e){rows.push({PID:child.pid,identity_missing:true,error:e.message});}});}
async function poll(){if(closed)return;const job=(async()=>{try{if(Date.now()>=deadline)throw typed('PROCESSING_DEADLINE');if(fs.existsSync(out+'/PAUSE')||diagnosticCase==='pause')throw typed('PAUSED');if(diagnosticCase==='read-error')throw typed('BEADS_READ_ERROR',Object.assign(new Error('DIAGNOSTIC_READ_ERROR'),{code:'EIO'}));if(diagnosticCase==='unready')throw typed('UNREADY');await read('quoridor-4lc');await read(subjectIssue);state='READY';}catch(e){state=e.code??e.message;failure={code:e.code??e.message,cause:e.cause??null};rows.push({kind:'observer_failure',...failure,UTC:new Date().toISOString()});}finally{save('pause-monitor',snapshot())}})();inflight=job;await job;if(inflight===job)inflight=null;}
return{check,get ready(){return state==='READY'&&!failure},get state(){return state},async start(onFailure){closed=false;await poll();check();timer=setInterval(()=>{if(inflight||closed)return;void poll().then(()=>{if(failure)onFailure?.(typed(failure.code,failure.cause))})},1000);return this;},async stop(){closed=true;clearInterval(timer);if(inflight)await inflight;save('pause-monitor-stop',{...snapshot(),all_owned_read_callbacks_waited:pending.size===0,signal_unknown:0,active_monitor_timer:false});return pending.size===0;}};
}
module.exports={createMonitor,typed};
