'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');const adapters=require('./adapters.cjs'),R=path.resolve(__dirname,'../..'),O=R+'/.artifacts/ai-sigma/resume-20261003/SIGMA-WEB-PORT';
async function main(){
 const c=vm.createContext({console});vm.runInContext(adapters.script('cache'),c);
 const identity={engine:'candidate',request_id:'mock',generation:1,fixture:null,prefix:[],limits:{seed:1979,simulations:100000,max_nodes:200000,max_depth:200},deadline_ms:1000,commit_cutoff_ms:900};
 const cp={generation:1,action:13,terminal_value:null,simulations:1,root_visits:1,nn_calls:1,nodes:5000,nodes_count:5000,edges_count:4999,max_depth:30,arena_bytes:600000,high_water:700000,cap:false,guard_refusal:null,policy_fallbacks:0,value_fallbacks:0,root_edges:[[13,1,0,0]]};
 const owned={identity:{request_id:'mock',generation:1,fixture:null,prefix:[],seed:1979,simulations:100000,max_nodes:200000,max_depth:200},cp,completed_at:99,completed_token:1,pending_token:null,completed_NN:1,NN_attempts:1};
 const cache=new c.SnapshotCache(identity,{terminal:null,legal:[13]},()=>100),m={kind:'snapshot',identity,producer_identity:identity,sequence:1,owned,value:.25,sent_ms:100};assert(cache.receive(m));assert.equal(cache.cache.owned.cp.max_depth,30);
 const stale=structuredClone(m);stale.identity.generation=2;stale.sequence=2;assert(!cache.receive(stale));assert.equal(cache.events.at(-1).error,'IDENTITY_MISMATCH');cache.invalidate('CANCELLED');assert(!cache.receive({...m,sequence:3}));
 const e=(await WebAssembly.instantiate(fs.readFileSync(O+'/build/faithful.wasm'),{})).instance.exports;
 function call(v){const b=Buffer.from(JSON.stringify(v)),h=e.ort_buffer(b.length);new Uint8Array(e.memory.buffer,e.ort_ptr(h),b.length).set(b);let o;try{o=e.ort_call(h);const r=JSON.parse(Buffer.from(new Uint8Array(e.memory.buffer,e.ort_ptr(o),e.ort_len(o))));if(!r.ok)throw Error(r.error);return r.data;}finally{e.ort_free(h);if(o)e.ort_free(o);}}
 const ctx=vm.createContext({console});for(const n of ['game.js','context.js'])vm.runInContext(fs.readFileSync(R+'/tools/ai-sigma-actual-boundary-repair/'+n,'utf8'),ctx);vm.runInContext('globalThis.rules={fromPrefix,rustAction}',ctx);
 const raw=JSON.parse(fs.readFileSync(O+'/runs/port151-stageA-r2/browser-result.json')),inputs=JSON.parse(fs.readFileSync(R+'/research-data/ai-sigma/151-sigma-web-port/stageA-inputs.json'));let count=0;
 for(const row of raw.rows.filter(r=>r.engine==='candidate'&&r.fixture_id==='initial-p1')){const f=inputs.fixtures.find(f=>f.id===row.fixture_id);let state=ctx.rules.fromPrefix([]);const prefix=[];for(const a of f.legal_prefix){prefix.push(ctx.rules.rustAction(state,a));state=state.next(a);}const h=call({op:'new',prefix,simulations:32,generation:17,trace:false}).handle;let j=0;
  for(const cp of row.CPs){const q=call({op:'begin',handle:h,generation:17});if(q.pending){const saved=row.numeric[j++];assert.equal(q.key,saved.key);assert.deepStrictEqual(q.path,saved.path);assert.deepStrictEqual(q.features_bits,saved.features_bits);call({op:'resume',handle:h,generation:17,token:q.token,logits:saved.policy_logits,value:saved.value});}const after=call({op:'checkpoint',handle:h,generation:17});for(const n of ['action','root_visits','root_edges','root_valueSum','root_mean','nn_calls','max_depth','cap'])assert.deepStrictEqual(after[n],cp[n]);count++;}e.ort_free(h);
 }
 fs.writeFileSync(R+'/research-data/ai-sigma/159-cpu-concurrency/tape-parity.json',JSON.stringify({issue:'quoridor-4lc.159',NN:0,Chrome:0,actual_served_receiver_guard_above_old_caps:true,stale_generation_and_cancellation_rejection:true,actual_private_trace_off_saved_real_NN_parity_CPs:count,used_stopped_r2_outputs:true,new_NN_requests:0},null,2)+'\n');console.log(JSON.stringify({passed:true,CPs:count,NN:0}));
}main().catch(e=>{console.error(e.stack);process.exitCode=1});
