'use strict';const fs=require('fs'),vm=require('vm'),path=require('path');
const ROOT=path.resolve(__dirname,'../..'),OUT=ROOT+'/.artifacts/ai-sigma/resume-20261003/BASELINE-GAP/runs';
const adapters=require('./adapters.cjs');const files=['main','worker','producer','checkpoint','cache','reference'];for(const name of files)new vm.Script(adapters.script(name));
for(const name of ['static.cjs','diagnose.cjs','browser.cjs','input.js','main.js'])new vm.Script(fs.readFileSync(__dirname+'/'+name,'utf8'));
const fixtures=JSON.parse(fs.readFileSync(ROOT+'/.artifacts/ai-sigma/reference-fixtures/SIGMA-PARITY-PLAN/fixtures.json')).fixtures;
const ctx=vm.createContext({performance,structuredClone,SharedArrayBuffer,Atomics,fixtures});
for(const p of ['tools/ai-sigma-actual-boundary-repair/game.js','tools/ai-sigma-actual-boundary-repair/context.js','tools/ai-sigma-cp-frame/shared-best-action.cjs','tools/ai-sigma-cp-frame/numeric-browser.js','tools/ai-sigma-player-workers/player-control.cjs'])vm.runInContext(fs.readFileSync(ROOT+'/'+p,'utf8'),ctx);
vm.runInContext(adapters.script('main'),ctx);
const mock=vm.runInContext("gapMock({seed:1979,adopt_ms:411,sample_interval_ms:1},fixtures)",ctx);
ctx.oldDocument=JSON.parse(fs.readFileSync(ROOT+'/.artifacts/ai-sigma/resume-20261002/DIVERSE-PREFIX/runs/prefix119-generation-r1/generated-prefixes.json'));
const prefix=vm.runInContext("generateDiversePrefixes({issue:'quoridor-4lc.148',attempt_cap:8,slots:Array.from({length:32},(_,i)=>({slot:i+1,layer_ply:4+i%2,attempt_seeds:Array.from({length:8},(_,j)=>730001+i*8+j),search_seed_both:1979}))},oldDocument)",ctx);
if(prefix.prefixes.some(x=>!x.accepted))throw Error('MOCK_PREFIX_FAILURE');
const r={NN:0,Chrome:0,mock,prefix_test:'artificial 32 inputs; not registered scientific input collection',prefix_check:vm.runInContext('validateDiverseDocument('+JSON.stringify(prefix)+')',ctx),seed_request_producer_checkpoint_cache:'all1979 strict identity; actual runtime receipt gate separate',bindings:adapters.bindings()};
fs.writeFileSync(OUT+'/static-result.json',JSON.stringify(r,null,2)+'\n');console.log(JSON.stringify({pass:true,NN:0,Chrome:0}));
