"use strict";const fs=require('fs'),assert=require('assert');const q=require('./qf1.cjs');const D='research-data/ai-sigma/190-nnue-qf1-prototype',w=q.load(D+'/native.f32');const counter=JSON.parse(fs.readFileSync(D+'/counter.json'));let evaluated=0,maxDelta=0,maxTorch=0,cases=0;const selected=[],rootSnapshots=[];const clock=()=>Number(process.hrtime.bigint())/1e6;
function evaluate(a){counter.native++;counter.sample_total++;assert(counter.sample_total<=65536);evaluated++;return q.value(a,w)}
const torch=new Map(JSON.parse(fs.readFileSync(D+'/torch-fixtures.json')).map(f=>[f.id,f.value]));
const f32=JSON.stringify(Array.from(new Float32Array(new Uint32Array([0x3f800000]).buffer)));assert.equal(f32,'[1]');
let full_ms=0,delta_ms=0;const kinds=new Set();for(const f of q.fixtures()){const s=f.state,base=q.full(s,w),parentBytes=base.a.map(a=>Buffer.from(a.buffer).toString('hex')),key=s._positionKey(),history=JSON.stringify([...s.position_history]);const v=evaluate(base);assert(Math.abs(v-torch.get(f.id))<=1e-5+1e-4*Math.abs(torch.get(f.id)));maxTorch=Math.max(maxTorch,Math.abs(v-torch.get(f.id)));rootSnapshots.push({id:f.id,value:v});const legal=s.getLegalActions(),selectedActions=legal.filter(a=>a.type==='pawn').concat(['h','v'].flatMap(o=>{const a=legal.find(a=>a.type==='wall'&&a.orientation===o);return a?[a]:[]}));for(let i=0;i<selectedActions.length;i++){const child=s.next(selectedActions[i]),a=q.full(child,w),vv=evaluate(a),tv=torch.get(f.id+'/child'+i);assert(Number.isFinite(tv));assert(Math.abs(vv-tv)<=1e-5+1e-4*Math.abs(tv),'TORCH_NATIVE_PARITY');maxTorch=Math.max(maxTorch,Math.abs(vv-tv));selected.push({id:f.id+'/child'+i,diff:vv-tv})}
for(const action of legal){const child=s.next(action);let t=clock();const full=q.full(child,w),vf=evaluate(full);full_ms+=clock()-t;t=clock();const delta=q.delta(base,child,w),vd=evaluate(delta);delta_ms+=clock()-t;assert.deepStrictEqual(full.ids,delta.ids);assert(Math.abs(vf-vd)<=1e-5+1e-4*Math.abs(vf),'FULL_DELTA_PARITY');maxDelta=Math.max(maxDelta,Math.abs(vf-vd));assert.deepStrictEqual(base.a.map(a=>Buffer.from(a.buffer).toString('hex')),parentBytes,'PARENT_BUFFER');assert.equal(s._positionKey(),key);assert.equal(JSON.stringify([...s.position_history]),history);if(action.type==='pawn'){assert(delta.updates.every(n=>n===2));assert.strictEqual(q.maps(s),q.maps(child));const old=s.getCurrentPlayer()===1?s.player1pos:s.player2pos,newpos=s.getCurrentPlayer()===1?child.player1pos:child.player2pos;const dx=Math.abs(old[0]-newpos[0]),dy=Math.abs(old[1]-newpos[1]);kinds.add(dx&&dy?'diagonal':dx+dy===2?'jump':'pawn')}else{assert(delta.updates.every(n=>n===3));assert.notStrictEqual(q.maps(s),q.maps(child));kinds.add(action.orientation)}cases++}}
// Result-before fixed artificial NN0 diagonal geometry fixture: P2 blocked straight jump.
const jump=q.fixtures().find(f=>f.id==='straight-jump-p2').state;const move=jump.getLegalActions().find(a=>a.type==='wall'&&a.orientation==='h');if(move){const wall=jump.next(move);const hasDiagonal=wall.getLegalActions().some(a=>a.type==='pawn'&&a.direction[0]&&a.direction[1]);selected.push({NN0_diagonal_after_fixed_first_H:hasDiagonal})}
assert(kinds.has('pawn')&&kinds.has('jump')&&kinds.has('diagonal')&&kinds.has('h')&&kinds.has('v'),'FIXTURE_COVERAGE');
const searches=[];for(const f of q.fixtures().filter(f=>['initial-p1','asym-hv-p2'].includes(f.id))){let nodes=0,finishedDepth=0,best=null,lastValue=null;const root=f.state,rootKey=root._positionKey(),stack=q.full(root,w);const seen=[];function search(s,a,depth,alpha,beta){if(++nodes>1024)throw Error('NODE_CAP');const terminal=q.r.terminalResult(s);if(terminal){seen.push({side:s.getCurrentPlayer(),winner:terminal.winner,value:terminal.value});return terminal.value}if(depth===0)return evaluate(a);let v=-Infinity;for(const action of s.getLegalActions()){const child=s.next(action),cv=-search(child,q.delta(a,child,w),depth-1,-beta,-alpha);if(cv>v)v=cv;alpha=Math.max(alpha,cv);if(alpha>=beta)break}return v}let failure=null;for(let depth=1;depth<=2;depth++){let candidate=null,value=-Infinity;try{for(const action of root.getLegalActions()){const child=root.next(action),v=-search(child,q.delta(stack,child,w),depth-1,-Infinity,-value);if(v>value){value=v;candidate=action}}finishedDepth=depth;best=candidate;lastValue=value}catch(e){failure=e.message;break}}assert.equal(root._positionKey(),rootKey);searches.push({id:f.id,nodes,completed_depth:finishedDepth,requested_depth:2,action:best? q.r.rustAction(root,best):null,value:lastValue,partial_next_depth_discarded:failure!==null,typed_stop:failure,terminal_samples:seen.slice(0,4),all_legal_actions_considered_until_typed_cap:true,policy_exclusion:false,node_cap:1024})}
// Terminal sign and draw priority use the original RuleA state/history.
const term=q.r.fromPrefix([]).copy();term.player1pos=[4,8];term.player2pos=[0,1];term.depth=1;assert.equal(q.r.terminalResult(term).value,-1);const draw=q.r.fromPrefix([]).copy();draw.depth=200;assert.equal(q.r.terminalResult(draw).value,0);
fs.writeFileSync(D+'/counter.json',JSON.stringify(counter)+'\n');fs.writeFileSync(D+'/native-probe.json',JSON.stringify({status:'PASS',version:q.F,implementation:'Node native-hosted f32 scalar evaluator, not Rust/Wasm or SIMD',cases,kinds:[...kinds],selected,max_delta:maxDelta,max_torch:maxTorch,rootSnapshots,full_including_input_ms:full_ms,delta_including_input_ms:delta_ms,timing_condition:'one fixed parity pass, no warm; not validated speedup or samewall strength',map:q.stats(),evaluated,counter,searches,parent_undo:true,terminal_sign_draw_PRIORITY:true})+'\n');console.log(JSON.stringify({status:'PASS',cases,evaluated,counter,searches}));
