"use strict";
const fs=require('fs'),assert=require('assert');
const {createReference}=require('../ai-sigma-native-baseline/reference.cjs');const{r}=createReference();
const F='QF1-H32-f32-v1',cache=new Map();let hit=0,miss=0;
function features(s,p){assert.equal(s.boardsize,9);const rot=p===2,me=p===1?s.player1pos:s.player2pos,op=p===1?s.player2pos:s.player1pos;const square=a=>{const i=a[1]*9+a[0];return rot?80-i:i};const out=[square(me),81+square(op)];for(const[o,base]of[[s.hwall_anchors,162],[s.vwall_anchors,226]])for(const a of o){const[x,y]=a.split(',').map(Number);assert(x>=0&&x<8&&y>=0&&y<8);const i=8*y+x;out.push(base+(rot?63-i:i))}const rem=p===1?[s.walls_p1,s.walls_p2]:[s.walls_p2,s.walls_p1];assert(rem.every(x=>Number.isInteger(x)&&x>=0&&x<=10));out.push(290+rem[0],301+rem[1]);out.sort((a,b)=>a-b);assert.equal(new Set(out).size,out.length);assert(out.length<=24&&out.every(i=>i>=0&&i<312));return out}
function maps(s){const key=F+'|wallmap-graph1|9|goals8,0|'+[...s.hwall_anchors].sort().join(';')+'|'+[...s.vwall_anchors].sort().join(';');if(cache.has(key)){hit++;return cache.get(key)}miss++;const result=[];for(const goal of[8,0]){const a=Array(81).fill(-1),q=[];for(let x=0;x<9;x++){a[goal*9+x]=0;q.push(goal*9+x)}for(let h=0;h<q.length;h++){const i=q[h],x=i%9,y=Math.floor(i/9);for(const[dx,dy]of[[0,1],[0,-1],[1,0],[-1,0]]){const nx=x+dx,ny=y+dy,j=ny*9+nx;if(nx>=0&&nx<9&&ny>=0&&ny<9&&a[j]<0&&!s._isEdgeBlocked(x,y,dx,dy)){a[j]=a[i]+1;q.push(j)}}}result.push(Object.freeze(a))}Object.freeze(result);if(cache.size>=256)cache.clear();cache.set(key,result);return result}
function input(s){const m=maps(s),d=[m[0][s.player1pos[1]*9+s.player1pos[0]],m[1][s.player2pos[1]*9+s.player2pos[0]]];assert(d.every(x=>x>=0&&x<=80),'UNREACHABLE_PAWN');const side=s.getCurrentPlayer();return{ids:[features(s,1),features(s,2)],distance:side===1?d.map(x=>x/80):d.reverse().map(x=>x/80),side,maps:m}}
function fixtures(){const out=JSON.parse(fs.readFileSync('research-data/ai-sigma/151-sigma-web-port/stageA-inputs.json')).fixtures.filter(f=>['initial-p1','asym-hv-p2','straight-jump-p2'].includes(f.id)).map(f=>({id:f.id,state:r.referenceState(f)}));const prefix=[];for(let i=0;i<3;i++){prefix.push({type:'pawn',direction:[0,1]},{type:'pawn',direction:[0,-1]})}prefix.push({type:'pawn',direction:[0,1]},{type:'wall',x:4,y:5,orientation:'h'});out.push({id:'fixed-legal-diagonal-p1',state:r.fromPrefix(prefix)});return out}
function fixtureRows(){const out=[];for(const f of fixtures()){out.push({id:f.id,...input(f.state)});const legal=f.state.getLegalActions();const selected=legal.filter(a=>a.type==='pawn').concat(['h','v'].flatMap(o=>{const a=legal.find(a=>a.type==='wall'&&a.orientation===o);return a?[a]:[]}));for(let i=0;i<selected.length;i++)out.push({id:f.id+'/child'+i,...input(f.state.next(selected[i]))})}return out.map(({id,ids,distance,side})=>({id,ids,distance,side}))}
function load(file){const b=fs.readFileSync(file);assert.equal(b.length,48772);const w=new Float32Array(12193);for(let i=0;i<w.length;i++)w[i]=b.readFloatLE(i*4);assert(w.every(Number.isFinite));return{W:w.subarray(0,9984),b:w.subarray(9984,10016),H:w.subarray(10016,12128),hb:w.subarray(12128,12160),O:w.subarray(12160,12192),ob:w[12192]}}
const add=(a,b)=>Math.fround(a+b),mul=(a,b)=>Math.fround(a*b);
function full(s,w){const q=input(s);const a=q.ids.map(ids=>{const v=new Float32Array(w.b);for(const k of ids)for(let j=0;j<32;j++)v[j]=add(v[j],w.W[j*312+k]);return v});return{...q,a}}
function delta(parent,s,w){const q=input(s);const updates=[];const a=parent.a.map((v,p)=>{const out=new Float32Array(v),remove=parent.ids[p].filter(k=>!q.ids[p].includes(k)),insert=q.ids[p].filter(k=>!parent.ids[p].includes(k));for(const k of remove)for(let j=0;j<32;j++)out[j]=add(out[j],-w.W[j*312+k]);for(const k of insert)for(let j=0;j<32;j++)out[j]=add(out[j],w.W[j*312+k]);updates.push(remove.length+insert.length);return out});return{...q,a,updates}}
function value(q,w){const p=q.side-1,other=1-p,x=Array.from(q.a[p],v=>Math.max(0,v)).concat(Array.from(q.a[other],v=>Math.max(0,v)),q.distance);let out=w.ob;for(let j=0;j<32;j++){let h=w.hb[j];for(let k=0;k<66;k++)h=add(h,mul(w.H[j*66+k],x[k]));out=add(out,mul(w.O[j],Math.max(0,h)))}return Math.fround(Math.tanh(out))}
module.exports={F,r,features,maps,input,fixtures,fixtureRows,load,full,delta,value,stats:()=>({hits:hit,misses:miss,current:cache.size,max:256})};
