'use strict';
const fs=require('fs'),vm=require('vm'),path=require('path'),crypto=require('crypto');
const R=path.resolve(__dirname,'../..'),input=JSON.parse(fs.readFileSync(0,'utf8')),C=vm.createContext({structuredClone,TextEncoder});
for(const p of ['game.js','context.js'])vm.runInContext(fs.readFileSync(R+'/tools/ai-sigma-actual-boundary-repair/'+p,'utf8'),C);
C.data=input;
const result=vm.runInContext(`(()=>{
const must=(x,m)=>{if(!x)throw Error('INDEPENDENT131_'+m)},equal=(a,b,m)=>must(JSON.stringify(a)===JSON.stringify(b),m),sortHistory=h=>h.slice().sort((a,b)=>a[0]<b[0]?-1:a[0]>b[0]?1:0);
const inputs=data.labels.inputs,certs=data.labels.labels;let normalBackup=0,normalNN=0,terminal=0,hand=0,stressBackup=0,stressNN=0,retired=0,discard=0,postNN=0,beforeACK=0;const rows=[],contexts=[];
for(const i of inputs){let s=fromPrefix(i.legal_prefix);must(s._positionKey()===i.key&&s.depth===i.depth&&s.getCurrentPlayer()===i.player&&i.player===1,'INPUT_KEY_DEPTH_PLAYER');equal(sortHistory([...s.position_history]),sortHistory(i.history),'INPUT_HISTORY');const cert=certs.find(x=>x.case===i.case).certificate;must(cert.root_key===i.key&&cert.player===i.player,'LABEL_BIND');const legal=s.getLegalActions();must(legal.length===cert.root_legal_count,'LEGAL_COUNT');must(legal.every(a=>cert.root_legal.some(b=>sameAction(a,b))),'LABEL_LEGAL_SET');contexts.push({case:i.case,key:i.key,player:i.player,legal:legal.length,acceptable:i.case==='own-near-goal'||i.case==='both-near'?cert.immediate_wins.length:cert.next_ply_loss_avoid.length});}
const all=data.raw.rows;must(all.length===12&&data.raw.started_requests===12,'ALL12');const seen=new Set();
for(const [index,r]of all.entries()){
 const i=inputs.find(x=>x.case===r.spec.case),c=certs.find(x=>x.case===r.spec.case).certificate,s=fromPrefix(i.legal_prefix),id=r.identity,p=r.response,b=p.body,d=r.diagnostic,cp=d.validated_cp,ads=p.adopt_checkpoint;
 must(!seen.has(id.request_id),'UNIQUE_REQUEST');seen.add(id.request_id);must(id.generation===index+1&&id.epoch===id.generation&&id.request_token===id.request_id,'GEN_TOKEN');must(id.engine===r.spec.engine&&b.engine===id.engine&&b.request_id===id.request_id&&b.generation===id.generation,'PUBLIC_BIND');must(id.key===i.key&&id.limits.seed===1979,'KEY_SEED');equal(id.legal_prefix,i.legal_prefix,'PREFIX');equal(sortHistory(id.history),sortHistory(i.history),'ROW_HISTORY');must(id.deadline_ms-id.t0_ms===500&&id.commit_cutoff_ms-id.t0_ms===402&&id.seal_ms-id.t0_ms===411,'CLOCK_CONSTANT');
 const cond=r.spec.condition;must((cond==='A'||cond==='B')?index<8:index>=8&&cond==='S','ORDER');must(r.spec.engine===(cond==='B'?'reference':'candidate'),'ENGINE_CONDITION');must(id.limits.simulations===(cond==='S'?1:cond==='A'?4096:100000),'LIMITS');
 const legal=s.getLegalActions(),ids=legal.map(a=>rustAction(s,a));must(b.completed===true&&b.late===false&&b.cancelled===false&&legal.some(a=>sameAction(a,b.action)),'LEGAL_COMPLETION');equal(JSON.parse(p.body_serialized),b,'BODY_IMMUTABLE');must(new TextEncoder().encode(p.body_serialized).length===p.bytes,'UTF8_BYTES');must(cp.generation===id.generation&&b.sequence===ads.sequence&&ads.sequence===d.sab_publications.at(-1).sequence&&cp.action===ads.action&&rustAction(s,b.action)===cp.action,'COMPLETE_CP_ACTION');
 const accept=['own-near-goal','both-near'].includes(i.case)?c.immediate_wins:c.next_ply_loss_avoid;must(['own-near-goal','both-near'].includes(i.case)?c.immediate_wins_complete:c.next_ply_labels_complete,'LABEL_AVAILABLE');must(accept.some(a=>sameAction(a,b.action)),'CERTIFIED_ACTION');const isGoal=s.next(b.action).winner()===i.player;
 const nn=d.numeric[0];must(nn.features_bits.length===648&&nn.policy_logits.length===136&&nn.policy_logits.every(Number.isFinite)&&Number.isFinite(nn.value)&&Math.abs(nn.value)<=1,'NN_SHAPE_FINITE');const f=s.toNNInput();equal(nn.features_bits,Array.from(new Uint32Array(f.buffer,f.byteOffset,f.length)),'FEATURES');const edge=cp.root_edges.reduce((a,e)=>a+e[2],0),backup=cond==='B'?cp.simulations+1:cp.simulations;must(edge===(cond==='B'?cp.simulations:cp.simulations-1),'EDGE_VISITS');if(cond==='B')must(cp.root_visits===backup,'REFERENCE_ROOT');must(cp.nn_calls<=backup,'NN_BACKUP');
 const pubs=d.sab_publications;must(pubs.every((v,j)=>v.sequence>0&&(j===0||v.sequence>pubs[j-1].sequence)),'SEQUENCE_MONOTONIC');must(p.stamp_ms>=p.timer_ms&&p.stamp_ms<id.deadline_ms,'PUBLIC_CLOCK');must(Math.abs(p.public_elapsed_ms-(p.stamp_ms-id.t0_ms))<1e-8,'ELAPSED');const ack=r.stop.stop;must(ack.handles===0&&ack.activeNN===0&&ack.live_searches===0&&ack.active===false,'SEARCH_ACK_ZERO');const clock=r.worker_clock,stopLo=ack.at_ms-clock.hi_ms,stopHi=ack.at_ms-clock.lo_ms;must(stopHi<=id.deadline_ms,'WORKER_STOP_BOUND');must(Math.abs(r.ACK_wall_ms-(r.stop.main_received_ms-id.t0_ms))<1e-8,'ACK_WALL');
 const ev=d.NN_control_events,hn=ev.length;must(hn===r.hand_NN,'HAND_COUNT');hand+=hn;const dc=ev.filter(x=>x.result_discarded).length;discard+=dc;const privateError=d.result?.error??null;if(privateError==='STALE_GENERATION')retired++;must(Object.values(p.causes).every(v=>v===false||v===null),'PUBLIC_CAUSE_CLEAR');const after=ev.filter(x=>x.session_run_start_ms-clock.hi_ms>p.stamp_ms).length;postNN+=after;if(cond!=='S'&&p.stamp_ms<r.stop.main_received_ms)beforeACK++;
 if(cond==='S'){must(backup===1&&cp.nn_calls===1&&edge===0&&hn===1&&pubs.length===1&&pubs[0].sequence===1&&dc===0,'ROOT1');must(stopHi<p.planned_ms,'ROOT1_STOP_BEFORE_ADOPT');stressBackup+=backup;stressNN+=cp.nn_calls;}else{normalBackup+=backup;normalNN+=cp.nn_calls;terminal+=backup-cp.nn_calls;}
 rows.push({request:id.request_id,case:i.case,condition:cond,engine:id.engine,action:b.action,Action209:cp.action,label_pass_independent:true,immediate_goal:isGoal,backup,CP_NN:cp.nn_calls,terminal_noNN:backup-cp.nn_calls,hand_NN:hn,privateError,explicit_discard:dc,sequence:b.sequence,public_ms:p.stamp_ms-id.t0_ms,timer_vs_plan_ms:p.timer_ms-p.planned_ms,stamp_vs_plan_ms:p.stamp_ms-p.planned_ms,stopUpper_ms:stopHi-id.t0_ms,ACKwall_ms:r.stop.main_received_ms-id.t0_ms,post_public_newNN_definite:after,rootN_origin:cond==='B'?'raw reference':'candidate source convention; true node/parentQ unobserved'});
}
for(const i of inputs){const g=all.filter(x=>x.spec.case===i.case);must(g.length===3,'ABC_THREE');must(g.every(r=>sameAction(r.response.body.action,g[0].response.body.action)),'ABC_ACTION_SAME');const n=g.map(r=>r.diagnostic.numeric[0]);must(n.every(x=>JSON.stringify(x.features_bits)===JSON.stringify(n[0].features_bits)&&JSON.stringify(x.policy_logits)===JSON.stringify(n[0].policy_logits)&&x.value===n[0].value),'ABC_FIRST_ROOT_EXACT');}
must(data.raw.startup_rows.length===6&&data.raw.startup_rows.every(x=>x.NN===1&&x.zero),'STARTUP6');return {contexts,rows,normal_pass:rows.filter(r=>r.condition!=='S').length,root1_pass:rows.filter(r=>r.condition==='S').length,normalBackup,normalCPNN:normalNN,normalTerminalNoNN:terminal,handNN:hand,stressBackup,stressNN,startupNN:6,privateRetired:retired,explicitDiscard:discard,handMinusAdoptCP:hand-normalNN-stressNN,postPublicNewNNDefinite:postNN,normalBeforeACK:beforeACK,allP1:true,fixed_prefix_NN_reference:false,sharedRuleA:true,Chrome:0,newNN:0,newGame:0,depth2_reenumeration:0};})()`,C,{timeout:20000});
fs.writeFileSync(process.argv[2],JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({...result,rows:result.rows.map(x=>({case:x.case,condition:x.condition,action:x.Action209,backup:x.backup,CPNN:x.CP_NN})),contexts:result.contexts}));
