import pathlib,json,tarfile,datetime,hashlib
R=pathlib.Path(__file__).resolve().parents[2];D=R/'research-data/ai-sigma/131-tactical-saved-independent';L=json.loads((R/'research-data/ai-sigma/127-tactical-oracle/labels-and-inputs.json').read_text())
with tarfile.open(R/'research-data/ai-sigma/129-tactical-evaluation/runs-all-attempts.tar.gz') as a:raw=json.load(a.extractfile('runs/tactical129-measure-r1/browser-result.json'))
items=[]
for r in raw['rows']:
 if r['spec']['condition']!='S':continue
 cp=r['diagnostic']['validated_cp'];edges=cp['root_edges'];mx=max(e[1] for e in edges);selected=next(e for e in edges if e[0]==cp['action']);cert=next(x['certificate'] for x in L['labels'] if x['case']==r['spec']['case']);wins=cert['immediate_wins'] if cert['immediate_wins'] else cert['next_ply_loss_avoid'];assert selected[1]==mx and all(e[2]==0 for e in edges)
 items.append({'case':r['spec']['case'],'legal':cert['root_legal_count'],'label_accepts':len(wins),'label_acceptance_fraction':len(wins)/cert['root_legal_count'],'root1_chosen_is_max_legal_prior':True,'root1_edge_visits_all0':True,'prior':selected[1],'policy_rank':1,'not_a_uniform_random_success_probability_estimate':True})
stop=json.loads((D/'original-necessary-stop.json').read_text());drop=stop['runs/tactical129-measure-r1/finally-model-drop.json'];assert len(drop['players'])==2 and all(p['handles']==p['activeNN']==0 for p in drop['players']);timer=stop['runs/tactical129-measure-r1/main-timers-stop.json'];assert timer['main_timers']==0 and timer['pending_messages']==[]
processes=[v for k,v in stop.items() if k.endswith('.process.json')];assert all(p['remaining']==[] and p['unknown_adopted']==[] for p in processes)
monitor=stop['runs/tactical129-measure-r1/pause-monitor-stop.json'];inner=stop['runs/tactical129-measure-r1/outer-controlled-stop.json'];assert inner['remaining_pids']==0
fields={'UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'root1_policy_inspection':items,'Modeldrop_both_zero':True,'main_timer_message_zero':True,'outer_remainingunknown0':True,'inner_stop':inner,'monitor_callback_stop':monitor,'original_primary_secondary':stop['runs/tactical129-measure-r1/summary.json'],'new_NN':0,'new_browser':0,'label_reenumeration':0,'shared_RuleA_label_authentication_inherited':True,'timer_early_count':sum(r['response']['timer_ms']<r['response']['planned_ms'] for r in raw['rows']),'public_early_count':sum(r['response']['stamp_ms']<r['response']['planned_ms'] for r in raw['rows']),'timer_min_delta':min(r['response']['timer_ms']-r['response']['planned_ms'] for r in raw['rows']),'timer_max_delta':max(r['response']['timer_ms']-r['response']['planned_ms'] for r in raw['rows'])}
(D/'policy-sensitivity-and-stop.json').write_text(json.dumps(fields,indent=2)+'\n');print(json.dumps({'root1_max_prior_all4':True,'timer_early_count':fields['timer_early_count'],'public_early_count':fields['public_early_count'],'newNN':0}))
