"""251 dedicated saved NN0 arithmetic; no Torch, models, forward or old data checker."""
import argparse,collections,hashlib,json,math,pathlib,subprocess
ap=argparse.ArgumentParser();ap.add_argument('--task',required=True);ap.add_argument('--input-manifest',required=True);ap.add_argument('--out',required=True);a=ap.parse_args();assert a.task=='frame20-distance-arena-independent-251-v1'
P=pathlib.Path('research-data/ai-sigma/frame20-distance-arena');D=pathlib.Path(a.out).parent;T=pathlib.Path('tools/ai-sigma-frame20-distance-arena-independent');sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest();inp=json.loads(pathlib.Path(a.input_manifest).read_text());read=lambda n:json.loads((P/n).read_text())
for p,h in inp['SHA'].items():assert sha(p)==h,p
m=read('openings8-v1.json');partials=[read(n)for n in ['family0-r1-result.json','family1-r1-result.json']];ledger=sorted([g for q in partials for g in q['ledger']if g['slot']in q['attempted_slots']],key=lambda g:g['slot']);assert len(ledger)==8 and sorted(g['slot']for g in ledger)==list(range(1,9));planned={s['slot']:s for s in m['slots']};assert [s['distance_mode']for s in m['slots']]==['clip','tanh','tanh','clip','tanh','clip','clip','tanh'];old=json.loads(pathlib.Path(m['source_openings_path']).read_text());assert sha(m['source_openings_path'])==m['source_openings_SHA'];assert m['openings']==old['openings']and m['actionseed_initial']==old['actionseed_initial']and m['entropy']==old['entropy'];wd={v:collections.Counter()for v in ['clip','tanh']};statuses=collections.Counter();slots=[];rows=[];allrecords=[]
for g in ledger:
 s=planned[g['slot']];assert all(g[k]==s[k]for k in ['opening','family','distance_mode','NNUE_side','leaf_package']);assert g['leaf_package']is True;assert g['status']in ['TERMINAL','UNKNOWN','NOT_STARTED'];statuses[g['status']]+=1;o=next(o for o in m['openings']if o['id']==g['opening']);prefix=g.get('prefix',g.get('last_prefix'));assert prefix is None or prefix[:o['opening_ply']]==o['prefix'];
 if g['status']=='TERMINAL':wd[g['distance_mode']][g['result_NNUE']]+=1
 slots.append({k:g.get(k)for k in ['slot','opening','family','distance_mode','NNUE_side','status','hands','winner','result_NNUE','fault','reason']})
for name in ['family0-r1-hands.jsonl','family1-r1-hands.jsonl']:
 if not(P/name).exists():continue
 lastgen=0
 for line in (P/name).open():
  if not line.strip():continue
  h=json.loads(line);c=h['clock'];r=c.get('response');q=(r or{}).get('search');g=ledger[h['slot']-1];assert h['distance_mode']==g['distance_mode'];assert h['generation']>lastgen;lastgen=h['generation'];assert h['engine']==('NNUE'if h['side']==g['NNUE_side']else'distance');assert 0<=c['elapsed_ms']and abs(c['received_ms']-c['t0_ms']-c['elapsed_ms'])<1e-6;valid=bool(r and r.get('validation',{}).get('valid'));adopted=c['status']=='RECEIVED'and valid
  allrecords.append({'slot':h['slot'],'status':c['status'],'elapsed_ms':c['elapsed_ms'],'adopted':adopted,'late_valid':bool(valid and c['elapsed_ms']>100),'search_present':q is not None,'search_status':q.get('status')if q else None})
  if not adopted:continue
  assert c['elapsed_ms']<=100 and r['id']==h['id']and r['generation']==h['generation'];assert r['distance_mode']==q['distance_mode']==g['distance_mode'];assert r['leaf_package']==q['leaf_package']==True;assert r['validation']['legal']and r['validation']['value_finite'];assert q['status']=='COMPLETED_ACTION'and q['completed_depth']>=1 and q['last_completed_only']and q['parent_copy_key_history_restored'];assert math.isfinite(q['value']);assert q['node_cap']==32768 and q['stats']['processed']<=32768;assert r['key']==q['root_key']==h['before_key']and r['history']==q['root_history']==h['before_history'];ds=[d for d in q['depths']if d['status']=='COMPLETED'];assert ds[-1]['completed_depth']==q['completed_depth']and ds[-1]['Action']==q['Action']and ds[-1]['value']==q['value'];assert all(d.get('adopted')is False for d in q['depths']if d['status']=='INCOMPLETE');stats=q['stats'];assert 0<=stats['D_nonterminal_saturated']<=stats['D_evals'];rows.append({'slot':h['slot'],'side':h['side'],'engine':h['engine'],'mode':g['distance_mode'],'ply':h['ply'],'key':r['key'],'history':r['history'],'elapsed_ms':c['elapsed_ms'],'depth':q['completed_depth'],'Action':q['Action'],'value':q['value'],'depths':ds,'processed':stats['processed'],'NN':stats['NN'],'D_evals':stats['D_evals'],'raw_ge1':stats['D_nonterminal_saturated'],'terminal':stats['terminal'],'raw_min':stats['D_raw_min'],'raw_max':stats['D_raw_max'],'partial_discarded':q['partial_depth_discarded'],'whole_ms':q['wholewall_ms']})
metrics=[]
for mode in ['clip','tanh']:
 for engine in ['NNUE','distance']:
  hs=[h for h in rows if h['mode']==mode and h['engine']==engine];clocks=[h['elapsed_ms']for h in hs];rawmins=[h['raw_min']for h in hs if h['raw_min']is not None];rawmaxs=[h['raw_max']for h in hs if h['raw_max']is not None];metrics.append({'mode':mode,'engine':engine,'accepted_hands':len(hs),'completeddepth_counts':dict(collections.Counter(h['depth']for h in hs)),'depth_mean':sum(h['depth']for h in hs)/len(hs)if hs else None,'processed':sum(h['processed']for h in hs),'NN':sum(h['NN']for h in hs),'D_evals':sum(h['D_evals']for h in hs),'pretransform_abs_u_ge1':sum(h['raw_ge1']for h in hs),'terminal_nodes':sum(h['terminal']for h in hs),'D_raw_min':min(rawmins)if rawmins else None,'D_raw_max':max(rawmaxs)if rawmaxs else None,'nodecap_hands':sum(h['processed']==32768 for h in hs),'elapsed_mean_ms':sum(clocks)/len(clocks)if clocks else None,'elapsed_max_ms':max(clocks)if clocks else None,'slack_min_ms':100-max(clocks)if clocks else None,'partial_discarded_hands':sum(h['partial_discarded']is not None for h in hs),'searchwhole_sum_ms':sum(h['whole_ms']for h in hs)})
paired=[];common=[]
for opening in m['openings']:
 for side in [1,2]:
  gs=[g for g in ledger if g['opening']==opening['id']and g['NNUE_side']==side];assert len(gs)==2;base=next(g for g in gs if g['distance_mode']=='clip');cand=next(g for g in gs if g['distance_mode']=='tanh');index=collections.defaultdict(list);key=lambda h:(h['engine'],h['side'],h['key'],h['history'])
  for h in rows:
   if h['slot']==cand['slot']:index[key(h)].append(h)
  for b in [h for h in rows if h['slot']==base['slot']]:
   if not index[key(b)]:continue
   c=index[key(b)].pop(0);db={d['completed_depth']:d for d in b['depths']};dc={d['completed_depth']:d for d in c['depths']};cmp=[]
   for depth in sorted(db.keys()&dc.keys()):
    x,y=db[depth],dc[depth];entry={'engine':b['engine'],'depth':depth,'clip_value':x['value'],'tanh_value':y['value'],'maxabs':abs(x['value']-y['value']),'Action_equal':x['Action']==y['Action']};cmp.append(entry);common.append(entry)
   paired.append({'clip_slot':base['slot'],'tanh_slot':cand['slot'],'engine':b['engine'],'input_SHA':hashlib.sha256(repr(key(b)).encode()).hexdigest(),'clip_depth':b['depth'],'tanh_depth':c['depth'],'clip_Action':b['Action'],'tanh_Action':c['Action'],'processed_delta':c['processed']-b['processed'],'NN_delta':c['NN']-b['NN'],'elapsed_delta_ms':c['elapsed_ms']-b['elapsed_ms'],'common':cmp})
profiles=[]
for engine in ['NNUE','distance']:
 ps=[p for p in paired if p['engine']==engine];cs=[x for x in common if x['engine']==engine];profiles.append({'engine':engine,'sameinput_pairs':len(ps),'tanh_deeper':sum(p['tanh_depth']>p['clip_depth']for p in ps),'same_depth':sum(p['tanh_depth']==p['clip_depth']for p in ps),'shallower':sum(p['tanh_depth']<p['clip_depth']for p in ps),'final_Action_changed':sum(p['tanh_Action']!=p['clip_Action']for p in ps),'processed_delta_sum':sum(p['processed_delta']for p in ps),'NN_delta_sum':sum(p['NN_delta']for p in ps),'elapsed_delta_mean_ms':sum(p['elapsed_delta_ms']for p in ps)/len(ps)if ps else None,'commondepth_columns':len(cs),'common_value_maxabs':max((x['maxabs']for x in cs),default=None),'common_Action_changes':sum(not x['Action_equal']for x in cs),'D_value_Action_change_allowed':engine=='distance'})
processes=[]
for p in sorted((P/'guardians').glob('*/process.json')):
 x=json.loads(p.read_text());processes.append({'path':str(p),'startUTC':x['startUTC'],'endUTC':x['endUTC'],'exit':x['exit'],'reason':x.get('reason'),'wall_s':x['wall_s'],'actualNN':x['samples_actual'],'chargedNN':x['samples_charge'],'original_unknown':x.get('original_unknown'),'inflight_unknown':x.get('inflight_NN_unknown'),'inflight_upper':x.get('conservative_inflight_upper'),'wait':x['all_child_waited'],'current_exact_absent':x['current_exact_absent']})
known=sum(x['actualNN']for x in processes if x['actualNN']is not None);charged=sum(x['chargedNN']for x in processes);wall=sum(x['wall_s']for x in processes);stop=read('scientific-stop-v1.json');assert known==charged==stop['science_NN']and abs(wall-stop['science_wall_s'])<1e-8
engine=pathlib.Path('tools/ai-sigma-frame20-distance-arena/engine.cjs').read_text();oldengine=pathlib.Path('tools/ai-sigma-frame19-paired-leaf-arena/engine.cjs').read_text();controls=[' function terminal(',' function ordered(',' function child(',' function delta(',' function negamax('];core=[]
for f in controls:
 x=next(l for l in engine.splitlines()if l.startswith(f));y=next(l for l in oldengine.splitlines()if l.startswith(f));assert x==y;core.append(f.strip())
assert "return n.valueScaled(a,weights,manifest)"in engine;assert "ds=d.map(Math.fround),diff=Math.fround(ds[1]-ds[0]),u=Math.fround(Math.fround(m.distance_fit.a)+Math.fround(Math.fround(m.distance_fit.b)*diff))"in engine;assert "mode==='clip'?Math.max(-1,Math.min(1,u)):Math.fround(Math.tanh(u))"in engine

settings=[read(n)for n in ['family0-r1-settings.json','family1-r1-settings.json']];assert all(x['task']=='frame20-distance-arena-249-v1'and x['schema']=='distance-arena-v1'for x in settings);assert settings[0]['weight_manifest']==settings[1]['weight_manifest'];wm=json.loads(pathlib.Path(settings[0]['weight_manifest']).read_text());assert sha('research-data/ai-sigma/frame18-native-connection/candidate.f32')=='b81792d5ba00c6d79b58cada2fc81d84ea822db48c04420b4e269fb9b71841b3';weightbinding={'manifest_SHA':sha(settings[0]['weight_manifest']),'tensor_file_SHA':sha('research-data/ai-sigma/frame18-native-connection/candidate.f32'),'distance_fit':wm['distance_fit'],'same_settings_weight_path':True,'new_forward_certification':False}
preflight=read('preflight-r1-result.json');assert preflight['task']=='frame20-distance-arena-249-v1'and preflight['schema']=='distance-arena-v1'and preflight['PASS'];parity=[]
for x in preflight['actual_model_results']:
 oldd={d['completed_depth']:d for d in x['old']['depths']if d['status']=='COMPLETED'};newd={d['completed_depth']:d for d in x['new']['depths']if d['status']=='COMPLETED'}
 for depth in sorted(oldd.keys()&newd.keys()):
  v,w=oldd[depth],newd[depth];gap=abs(v['value']-w['value']);assert gap<=1e-7+1e-7*abs(v['value']);parity.append({'root':x['root'],'engine':x['engine'],'depth':depth,'maxabs':gap,'Action_equal':v['Action']==w['Action']})
assert sum(x['old']['stats']['NN']+x['new']['stats']['NN']for x in preflight['actual_model_results'])==preflight['samples']
if statuses['TERMINAL']==8:assert sum(x['NN']for x in metrics)+preflight['samples']==known
clockfixture=read('clock-fixture-r1.json');assert clockfixture['checks']==len(clockfixture['results'])==6 and clockfixture['PASS'];fixture=[]
for x in clockfixture['results']:
 c=x['clock'];adopted=c['status']=='RECEIVED'and bool((c.get('response')or{}).get('validation',{}).get('valid'));assert adopted==x['adopted'];assert abs(c['received_ms']-c['t0_ms']-c['elapsed_ms'])<1e-6;assert x['cleanup']['waited'];assert not adopted or c['elapsed_ms']<=100
 if x['mode']=='stale':assert len(c['obsolete'])>=1
 if c['elapsed_ms']>100:assert not adopted
 fixture.append({'mode':x['mode'],'adopted':adopted,'status':c['status'],'elapsed_ms':c['elapsed_ms'],'obsolete_discard_count':len(c['obsolete'])})

childcmd=['node','--max-old-space-size=384',str(T/'replay-distance.cjs'),'--task','frame20-distance-replay-251-v1','--out',str(D/'replay.json')];p=subprocess.Popen(childcmd,stdout=subprocess.PIPE,stderr=subprocess.PIPE);tick=pathlib.Path('/proc',str(p.pid),'stat').read_text().rsplit(')',1)[1].split()[19];stdout,stderr=p.communicate(timeout=35);assert p.returncode==0,stderr.decode();assert not pathlib.Path('/proc',str(p.pid)).exists();childrec={'argv':childcmd,'PID':p.pid,'tick':tick,'exit':0,'wait':True,'current_exact_absent':True};replay=json.loads((D/'replay.json').read_text());assert replay['PASS']and replay['task']=='frame20-distance-replay-251-v1'and replay['schema']=='distance-replay-v1'and replay['adopted']==len(rows)and replay['recorded']==len(allrecords)
for p,h in inp['SHA'].items():assert sha(p)==h,'changed '+p
result={'task':a.task,'schema':'distance-arena-independent-v1','PASS':True,'newNN':0,'planned8':8,'statuses':dict(statuses),'permodeWDL':{v:dict(wd[v])for v in wd},'slots':slots,'service_recorded':len(allrecords),'service_accepted':len(rows),'service_statuses':dict(collections.Counter(x['status']for x in allrecords)),'latevalid_discarded':sum(x['late_valid']for x in allrecords),'metrics':metrics,'sameinput':profiles,'pairwitness_first12':paired[:12],'all_pair_columns_SHA':hashlib.sha256(json.dumps(paired,sort_keys=True,separators=(',',':')).encode()).hexdigest(),'knownNN':known,'chargedNN':charged,'allattempt_guardian_wall_s':wall,'processes':processes,'static_source_core_exact':core,'frozen_weight_binding':weightbinding,'saved_preflight_commondepth_parity':parity,'saved_current_clock_fixture':fixture,'preflight_provenance194_owner_reference':preflight['provenance_child_comparisons'],'numeric_scope':'D nonterminal clip versus f32 tanh same f32 u; stats raw_ge1 not tanh endpoint','sharedRuleA':replay,'child':childrec,'all_exact_argmax':'NOT_RECORDED','limits':['2same original242 opening/family color swaps; not IID/new8opening','different reachedstates aggregates not matchedwork','Dtransform changes samehorizon value/action by design; not arithmetic fault','tanh evaluation cost and terminal-relative calibration also change','NNUE and deep leaf truth not reforward-certified; owner parity receipts finite','shared RuleA, saved monotonic clock; no independent full rules/timer proof','old244/229 NOT_RUN and oldtest173 unchanged/unread; no result-selection reopening','background/management unknown costs not additive exclusive spans']};pathlib.Path(a.out).write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({k:v for k,v in result.items()if k not in ['pairwitness_first12','slots','sharedRuleA']}))
