"""251 scoped Git management only; no scientific computation."""
from pathlib import Path
import datetime,hashlib,json,time,subprocess
D=Path('research-data/ai-sigma/frame20-distance-arena-independent');T=Path('tools/ai-sigma-frame20-distance-arena-independent');R=Path('docs/reports/ai-sigma-critic-frame20-distance-arena.md');sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();start=time.monotonic();process=json.loads((D/'process.json').read_text());result=json.loads((D/'result.json').read_text());assert process['exit']==0 and result['PASS']and process['output_identity_verified']
for q in [process,result['child']]:
 p=Path('/proc',str(q['PID']),'stat');assert not p.exists()or p.read_text().rsplit(')',1)[1].split()[19]!=str(q['tick'])
stop={'UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_science_stopped':True,'newNN':0,'source45_calc45_charge90_cap90':True,'MAX1_actual1':True,'parent_child_wait_exactabsent':True,'source_SHA':{str(p):sha(p)for p in T.iterdir()if p.is_file()and p.name!='save_git.py'},'payload_SHA':{str(D/n):sha(D/n)for n in ['result.json','process.json','replay.json','admission.json','stopped-inputs.json']},'old229_final_NOT_RUN_unchanged':True,'oldcapsreset':False};(D/'scientific-stop.json').write_text(json.dumps(stop,indent=2)+'\n')
idx=Path(subprocess.check_output(['git','rev-parse','--git-path','index'],text=True).strip());before=json.loads((D/'intake.json').read_text())['index_SHA'];assert sha(idx)==before
files=[p for scope in [D,T]for p in scope.iterdir()if p.is_file()]+[R];allocated=sum(p.stat().st_blocks*512 for p in files);forecast=allocated+176128+16384+40960;assert forecast<524288 and forecast<786432
(D/'storage-final.json').write_text(json.dumps({'scope_allocated':allocated,'uniqueGit_forecast':176128,'temp_forecast':16384,'remaining_metadata':40960,'forecast':forecast,'forecast_limit':524288,'guard':786432,'reserve':1048576,'existingunused_before':17932288,'existingunused_after':16883712,'parentadd0':True,'unknown_discount0':True},indent=2)+'\n')
s=Path('research-data/ai-sigma/frame16-raw-cv-independent/save.py').read_text();s=s[:s.index("if __name__=='__main__':")];s=s.replace('research-data/ai-sigma/frame16-raw-cv-independent',str(D)).replace('docs/reports/ai-sigma-critic-raw-cv.md',str(R));s=s.replace("files=[p for p in D.iterdir() if p.is_file() and p.name!='save.log']+[pathlib.Path('"+str(R)+"')]", "files=[p for scope in [D,pathlib.Path('"+str(T)+"')] for p in scope.iterdir() if p.is_file()]+[pathlib.Path('"+str(R)+"')]");s=s.replace("assert name.startswith(str(D)+'/') or name==", "assert name.startswith(str(D)+'/') or name.startswith('"+str(T)+"/') or name==");ns={'__name__':'metadata_save'};exec(s,ns);cid,files=ns['commit']('critic251: independently verify D clip/tanh delivery, same-input horizon, legal prefixes and all-attempt costs; no strength claim')
for p in files:assert subprocess.check_output(['git','show',cid+':'+str(p)])==p.read_bytes(),str(p)
assert sha(idx)==before;receipt={'commit':cid,'files':len(files),'byte_restore_PASS':True,'defaultindex_before':before,'defaultindex_after':sha(idx),'privateindex0':True,'source_science_stopped':True,'management_wall_s':time.monotonic()-start,'postcommit_receipt_not_in_samecommit':True};(D/'Git-byte-receipt.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt))
