from pathlib import Path
import json,datetime,hashlib
A=Path('.artifacts/ai-sigma/continuation-20261001/SIGMA-ROOT-FACTOR-CORRECT-N');new=json.loads((A/'selected-results.json').read_text());new={(x['id'],x['kind']):x for x in new};oldpath=Path('.artifacts/ai-sigma/analysis/SIGMA-ROOT-SELECTION-ABLATION/diagnostic-final.log');old={}
for line in oldpath.read_text().splitlines():
 p=line.split('\t')
 if len(p)==8 and p[1]=='select_base':old[p[0]]={'action':int(p[2]),'score_bits':int(p[3]),'margin_bits':int(p[4]),'ties':int(p[5]),'near':int(p[6]),'chosen_visits':int(p[7])}
meta=json.loads((A/'root-metadata.json').read_text());ids=[x['id']for x in meta['roots']];assert len(ids)==765;assert all(i in old for i in ids)
def diff(field):return [i for i in ids if old[i][field]!=new[i,'base'][field]]
s=json.loads((A/'summary.json').read_text());expected={'all765':765,'accepted764':764,'private_late1':1,'native371':371,'wasm394':394,'matched194':194,'matched_native97':97,'matched_wasm97':97};assert all(s['groups'][k]['denominator']==v for k,v in expected.items());late=[r for r in meta['roots'] if r['private_late']];assert len(late)==1 and late[0]['game']==5 and late[0]['ply']==34;assert meta['missing_noresponse']==1
r={'UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'old_v1_log_sha256':hashlib.sha256(oldpath.read_bytes()).hexdigest(),'corrected_new_sha256':hashlib.sha256((A/'selected-results.json').read_bytes()).hexdigest(),'v1_actual_roots':765,'old_formula':'N=edge_sum; sqrt(edge_sum+1)','corrected_formula':'N=sim=edge_sum+1; sqrt(edge_sum+2)','baseline_method_correction_changed':{k:{'count':len(diff(k)),'ids':diff(k)}for k in ['action','score_bits','ties','near','chosen_visits']},'singleton_old_Infinity_margin_not_finite_repaired_observation':False,'denominator_assertions_passed':True,'private_late_id':late[0]['id'],'source_count_restoration_not_direct_raw':True,'old_v1_and_v2_write':False,'FPU_real_application':False,'full_MCTS':False,'NN':0,'actual_go':False}
(A/'v1-baseline-method-difference.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps({'baseline_action_changed':len(diff('action')),'baseline_scorebits_changed':len(diff('score_bits')),'old765_and_denominators_exact':True,'private_late_id':late[0]['id']}))
