'use strict';const fs=require('fs'),assert=require('assert/strict'),crypto=require('crypto');const A='.artifacts/ai-sigma/continuation-20261001/SIGMA-ROOT-FACTOR-CORRECT-N';const buf=new ArrayBuffer(4),dv=new DataView(buf),F=Math.fround;const bits=x=>{dv.setFloat32(0,x,true);return dv.getUint32(0,true)},from=x=>{dv.setUint32(0,x,true);return dv.getFloat32(0,true)},cmp=(a,b)=>{let x=bits(a)|0,y=bits(b)|0;x^=(x>>31)>>>1;y^=(y>>31)>>>1;return x<y?-1:x>y?1:0};
function tie(seed,action){let x=BigInt(seed)^BigInt(action);x=BigInt.asUintN(64,(x^(x>>30n))*0xbf58476d1ce4e5b9n);x=BigInt.asUintN(64,(x^(x>>27n))*0x94d049bb133111ebn);return x^(x>>31n)}
const w=fs.readFileSync(A+'/roots-input.txt','utf8').trim().split(/\s+/);let at=0;const tok=()=>w[at++],num=()=>Number(tok()),n=num(),roots=[];assert.equal(n,765);
for(let k=0;k<n;k++){const r={id:tok(),seed:num(),expected:num(),edge_sum:num(),N:num(),edges:[]};const len=num();for(let j=0;j<len;j++){r.edges.push({action:num(),prior:from(num()),visits:num(),value:from(num()),rank:num()});}assert.equal(r.edge_sum,r.edges.reduce((s,e)=>s+e.visits,0));assert.equal(r.N,r.edge_sum+1);let b=r.edges[0];for(const e of r.edges.slice(1)){if(e.visits>b.visits||(e.visits===b.visits&&(cmp(e.prior,b.prior)>0||(cmp(e.prior,b.prior)===0&&tie(r.seed,e.action)<tie(r.seed,b.action)))))b=e;}assert.equal(b.action,r.expected,'independent JS finish exact');roots.push(r);}assert.equal(at,w.length);
const modes={base:[1.5,true,false,false],C1:[1,true,false,false],sqrtN:[1.5,false,false,false],score_first:[1.5,true,true,false],first_reforder:[1.5,true,true,true]};
function select(r,mode,rounded=true){const[c,plus,first,order]=modes[mode];const f=rounded?F:x=>x;const root=f(Math.sqrt(f(f(r.N)+(plus?1:0))));const es=order?[...r.edges].sort((a,b)=>a.rank-b.rank):r.edges;const scores=es.map(e=>{const q=e.visits?f(e.value/f(e.visits)):0;return f(q+f(f(f(c*e.prior)*root)/f(e.visits+1)))});let best=0;for(let i=1;i<es.length;i++)if(scores[i]>scores[best]||(scores[i]===scores[best]&&!first&&tie(r.seed,es[i].action)<tie(r.seed,es[best].action)))best=i;const score=scores[best],second=Math.max(...scores.filter((_,i)=>i!==best));return {action:es[best].action,score_bits:bits(score),margin_bits:es.length===1?null:bits(f(score-second)),ties:scores.filter(x=>x===score).length,near:scores.filter(x=>Math.abs(f(score-x))<=1e-6).length,chosen_visits:es[best].visits,all_score_bits:scores.map(bits)};}
const lines=fs.readFileSync(A+'/factors.log','utf8').split('\n').filter(x=>!x.startsWith('BOUNDARY')&&!x.startsWith('FINISH')&&x.trim());assert(lines[0].startsWith('id\tkind'));const map=new Map(roots.map(r=>[r.id,r]));const rows=[],precision={rows:0,edge_score_bits:0,failures:[],JSNumber_unrounded_selected_score_bits_different:0,JSNumber_unrounded_actions_different:0};
for(const line of lines.slice(1)){const[id,kind,a,s,m,t,near,v,all]=line.split('\t');const out={id,kind,action:+a,score_bits:+s,margin_bits:m==='null'?null:+m,ties:+t,near:+near,chosen_visits:+v,all_score_bits:all.split(',').map(Number)};const r=map.get(id);assert(r);const js=select(r,kind);for(const k of Object.keys(js))assert.deepEqual(out[k],js[k],`f32 precision ${id} ${kind} ${k}`);precision.rows++;precision.edge_score_bits+=out.all_score_bits.length;const d=select(r,kind,false);precision.JSNumber_unrounded_selected_score_bits_different+=d.score_bits!==out.score_bits;precision.JSNumber_unrounded_actions_different+=d.action!==out.action;delete out.all_score_bits;rows.push(out);}assert.equal(rows.length,765*5);
const meta=JSON.parse(fs.readFileSync(A+'/root-metadata.json'));const by=new Map(rows.map(x=>[x.id+':'+x.kind,x]));const matched=new Set(meta.matched_ids);const groups={all765:meta.roots,accepted764:meta.roots.filter(r=>r.accepted),private_late1:meta.roots.filter(r=>r.private_late),native371:meta.roots.filter(r=>r.engine==='native'),wasm394:meta.roots.filter(r=>r.engine==='wasm'),matched194:meta.roots.filter(r=>matched.has(r.id)),matched_native97:meta.roots.filter(r=>matched.has(r.id)&&r.engine==='native'),matched_wasm97:meta.roots.filter(r=>matched.has(r.id)&&r.engine==='wasm')};const contrasts={C_only:['base','C1'],sqrt_only:['base','sqrtN'],score_tie_only:['base','score_first'],order_only_given_first:['score_first','first_reforder'],tie_plus_order_bundle:['base','first_reforder']};const summaries={};
for(const[g,rs]of Object.entries(groups)){const stat={denominator:rs.length,contrasts:{}};for(const[name,[a,b]]of Object.entries(contrasts)){const ids=rs.filter(r=>by.get(r.id+':'+a).action!==by.get(r.id+':'+b).action).map(r=>r.id);stat.contrasts[name]={changed:ids.length,denominator:rs.length,changed_ids:ids};}stat.baseline={unvisited_chosen:rs.filter(r=>by.get(r.id+':base').chosen_visits===0).length,exact_tie_roots:rs.filter(r=>by.get(r.id+':base').ties>1).length,near_tie_roots:rs.filter(r=>by.get(r.id+':base').near>1).length,singletons:rs.filter(r=>by.get(r.id+':base').margin_bits===null).length};summaries[g]=stat;}
const old=JSON.parse(fs.readFileSync('.artifacts/ai-sigma/analysis/SIGMA-ROOT-SELECTION-ABLATION/summary.json'));const oldnames={C_only:'C_only',sqrt_only:'sqrt_only_contract_N',score_tie_only:'score_tie_only_candidate_order',order_only_given_first:'score_order_only_given_first'};const v1comparison={};for(const[k,ok]of Object.entries(oldnames)){const v=old.groups.all765.contrasts[ok],now=summaries.all765.contrasts[k];v1comparison[k]={old_N:'edge_sum',old_changed:v.changed_argmax,correct_N:'sim=edge_sum+1',correct_changed:now.changed,changed_membership_added:now.changed_ids.filter(x=>!v.changed_ids.includes(x)),changed_membership_removed:v.changed_ids.filter(x=>!now.changed_ids.includes(x)),not_same_denominator_formula:true};}
const finite=rows.filter(x=>x.kind==='base'&&x.margin_bits!==null).map(x=>from(x.margin_bits)).sort((a,b)=>a-b);const agree={};for(const mode of Object.keys(modes))agree[mode]=meta.matched97_pairs.filter(p=>by.get(`${p.A[0]}:${p.A[1]}:${mode}`).action===by.get(`${p.B[0]}:${p.B[1]}:${mode}`).action).length;
const result={UTC:new Date().toISOString(),issue:'quoridor-4lc.79',gate:{finish_Rust_exact:765,finish_JS_exact:765,N_source_stats_restored_not_direct_raw:true,parentQ_observed:0,synthetic_old_toy_included:0,normal:765,accepted:764,late_private:1,noresponse_missing:1},precision,groups:summaries,v1comparison,margin:{n:finite.length,null_singleton:765-finite.length,median:finite.length%2?finite[(finite.length-1)/2]:(finite[finite.length/2-1]+finite[finite.length/2])/2,min:finite[0],max:finite.at(-1)},matched97_action_agreement:agree,actual_select_observed:false,full_search_changed:false,NN:0,games:0,actual_go:false};fs.writeFileSync(A+'/selected-results.json',JSON.stringify(rows)+'\n');fs.writeFileSync(A+'/summary.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({finish:765,precision_rows:precision.rows,precision_edge_scores:precision.edge_score_bits,changed:summaries.all765.contrasts,margin:result.margin,NN:0}));
