'use strict';const fs=require('fs'),vm=require('vm'),path=require('path');const root=path.resolve(__dirname,'../..'),out=root+'/.artifacts/ai-sigma/resume-20261002/WALLLESS-AI-SENSITIVITY/runs';const input=JSON.parse(fs.readFileSync(root+'/research-data/ai-sigma/144-wallless-ai-sensitivity/inputs.json'));
const ctx=vm.createContext({performance,inputs:input.inputs,structuredClone});for(const file of ['tools/ai-sigma-actual-boundary-repair/game.js','tools/ai-sigma-actual-boundary-repair/context.js','tools/ai-sigma-cp-frame/numeric-browser.js','tools/ai-sigma-wallless-ai-sensitivity/input.js'])vm.runInContext(fs.readFileSync(root+'/'+file,'utf8'),ctx);
const result=vm.runInContext(`inputs.map(x=>{const s=walllessCheck(x),mapping=actionBindings(s),f=s.toNNInput(),features_bits=Array.from(new Uint32Array(f.buffer,f.byteOffset,f.length)),numeric={features_bits,policy_logits:Array(136).fill(0),value:0};for(const engine of ['candidate','reference']){const ids=BrowserNumeric.expected(s)[engine],cp={root_edges:ids.map(id=>[id,1/ids.length,0,0])};BrowserNumeric.check({engine,state:s,numeric,cp,reference:null});}return {id:x.id,legal_prefix_plies:x.prefix.length,exact_replay:true,action_mapping:mapping,artificial_numeric_mock:true};})`,ctx);
const scripts=require('./adapters.cjs');for(const name of ['main','worker','reference','producer','checkpoint','cache'])new vm.Script(scripts.script(name));for(const name of ['diagnose.cjs','browser.cjs','main.js','worker.js','input.js'])new vm.Script(fs.readFileSync(__dirname+'/'+name,'utf8'));
if(result.some(r=>r.action_mapping.length!==4||new Set(r.action_mapping.map(x=>x.rust_id)).size!==4))throw Error('ACTION_MAPPING');
// Mock classification, generation, routing and transport shape; no actual NN/terminal observation.
const Shared=require('../ai-sigma-cp-frame/shared-best-action.cjs'),PC=require('../ai-sigma-player-workers/player-control.cjs');
const context={generation:1,key:'mock',legalActions:[13,31]},sab=Shared.create(context),reader=Shared.bind(sab,context,context),control=PC.bind(PC.create(1),1);
if(reader.readLatest()!==null||!control.active())throw Error('MOCK_INITIAL');reader.publish({completed:true,sequence:1,action:13,value:.5,visits:1});if(reader.readLatest().action!==13)throw Error('MOCK_SAB');
let refused=false;try{Shared.bind(sab,{...context,generation:2},{...context,generation:2});}catch(e){refused=true;}if(!refused)throw Error('MOCK_GENERATION');reader.stop('cancel');if(reader.readLatest()!==null)throw Error('MOCK_CANCEL');control.close('adopt');if(control.active())throw Error('MOCK_RETIRED');
const classification=(interval,fault)=>fault?'unfinished':!interval?'unscored':interval[0]===1&&interval[1]===1?'certifiedwin':interval[0]===-1&&interval[1]===-1?'certifiedloss':'unscored';
if(classification(null,null)!=='unscored'||classification([1,1],'infra')!=='unfinished'||classification([-1,-1],null)!=='certifiedloss')throw Error('MOCK_CLASS');
const mock={SAB_completed:true,generation_stale_rejected:refused,retirement_closes_control:true,cancellation_unreadable:true,typed_fault_unfinished:true,unlabelled_unscored:true,artificial:true};
fs.writeFileSync(out+'/static-result.json',JSON.stringify({inputs:result,mock,NN:0,Chrome:0},null,2)+'\n');console.log(JSON.stringify({pass:true,inputs:result,NN:0}));
