//! B0: bounded, deterministic PUCT search over the authoritative Rust rules.
use quoridor_core::{Action, Position};
use std::mem::size_of;

pub const MAX_SIMULATIONS: u32 = 4096;
pub const MAX_NODES: u32 = 2048;
pub const MAX_DEPTH: u8 = 48;
pub const MAX_ARENA_BYTES: usize = 64 * 1024 * 1024;
const PUCT_C: f32 = 1.0;
#[cfg(feature = "research")]
use quoridor_core::research::SigmaContext;
#[cfg(feature = "research")]
type RuleCursor = Option<SigmaContext>;
#[cfg(not(feature = "research"))]
#[derive(Clone, Copy)]
struct RuleCursor;

fn cursor_terminal(position: Position, cursor: &RuleCursor) -> Option<f32> {
    #[cfg(feature = "research")]
    if let Some(context) = cursor {
        return context.terminal_value();
    }
    #[cfg(not(feature = "research"))]
    let _ = cursor;
    position
        .winner
        .map(|w| if w == position.turn { 1.0 } else { -1.0 })
}
fn cursor_legal(position: Position, cursor: &RuleCursor) -> Vec<u16> {
    #[cfg(feature = "research")]
    if let Some(context) = cursor {
        return context.legal_ids();
    }
    #[cfg(not(feature = "research"))]
    let _ = cursor;
    position.legal_action_ids()
}
fn cursor_next(position: Position, action: u16, cursor: &RuleCursor) -> (Position, RuleCursor) {
    #[cfg(feature = "research")]
    if let Some(context) = cursor {
        assert_eq!(position, context.position());
        let next = context.play(action).expect("context-legal edge");
        return (next.position(), Some(next));
    }
    let next = position.play(action).expect("edge was generated by core");
    #[cfg(not(feature = "research"))]
    let _ = cursor;
    (next, {
        #[cfg(feature = "research")]
        {
            None
        }
        #[cfg(not(feature = "research"))]
        {
            RuleCursor
        }
    })
}
fn cursor_follow(next: Position, action: u16, cursor: &RuleCursor) -> RuleCursor {
    #[cfg(feature = "research")]
    if let Some(context) = cursor {
        let c = context
            .play(action)
            .expect("context-legal reused tree edge");
        assert_eq!(next, c.position());
        return Some(c);
    }
    let _ = (next, action, cursor);
    #[cfg(feature = "research")]
    {
        None
    }
    #[cfg(not(feature = "research"))]
    {
        RuleCursor
    }
}
#[cfg(feature = "research-diagnostics")]
#[path = "research.rs"]
pub mod research;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SearchError {
    InvalidPosition,
    InvalidLimits,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SearchLimits {
    pub simulations: u32,
    pub max_nodes: u32,
    pub max_depth: u8,
}
impl SearchLimits {
    pub fn checked(self) -> Result<Self, SearchError> {
        if self.simulations > MAX_SIMULATIONS
            || self.max_nodes == 0
            || self.max_nodes > MAX_NODES
            || self.max_depth == 0
            || self.max_depth > MAX_DEPTH
        {
            return Err(SearchError::InvalidLimits);
        }
        Ok(self)
    }
}

#[derive(Debug, Clone)]
pub struct Evaluation {
    pub weights: Vec<f32>,
    pub value: f32,
}
pub trait Evaluator {
    fn evaluate(&self, position: Position, legal: &[u16]) -> Evaluation;
}

#[derive(Debug, Clone, Copy, Default)]
pub struct B0Evaluator;
impl Evaluator for B0Evaluator {
    fn evaluate(&self, position: Position, legal: &[u16]) -> Evaluation {
        if let Some(winner) = position.winner {
            return Evaluation {
                weights: Vec::new(),
                value: if winner == position.turn { 1.0 } else { -1.0 },
            };
        }
        let own = position.turn as usize;
        let other = own ^ 1;
        let own_distance = position.wall_distance(own).unwrap_or(81) as f32;
        let other_distance = position.wall_distance(other).unwrap_or(81) as f32;
        let wall_balance =
            position.walls_remaining[own] as f32 - position.walls_remaining[other] as f32;
        let value = ((other_distance - own_distance) / 6.0 + wall_balance / 20.0).tanh();
        let imminent_goal = other_distance <= 1.0;
        let weights = legal
            .iter()
            .map(|&id| {
                if imminent_goal {
                    let next = position.play(id).expect("legal action supplied by core");
                    if next.winner == Some(position.turn) {
                        return 1000.0;
                    }
                    let goal_row = if next.turn == 0 { 8 } else { 0 };
                    let opponent_wins_now = next
                        .legal_pawn_mask()
                        .iter()
                        .enumerate()
                        .any(|(cell, &open)| open != 0 && cell / 9 == goal_row);
                    if !opponent_wins_now {
                        return 1000.0;
                    }
                    return 0.01;
                }
                match Action::decode(id) {
                    Ok(Action::Pawn(cell)) => {
                        if cell / 9 == if own == 0 { 8 } else { 0 } {
                            return 1000.0;
                        }
                        let next = position.play(id).expect("legal action supplied by core");
                        let next_distance = next.wall_distance(own).unwrap_or(81) as f32;
                        (2.0 + own_distance - next_distance).max(0.2)
                    }
                    Ok(Action::Horizontal(_)) | Ok(Action::Vertical(_)) => 0.5,
                    Err(_) => 0.0,
                }
            })
            .collect();
        Evaluation { weights, value }
    }
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct SearchStats {
    pub simulations: u32,
    pub nodes: u32,
    pub edges: u32,
    pub arena_bytes: usize,
    pub high_water_bytes: usize,
    pub max_depth_reached: u8,
    pub policy_fallbacks: u32,
    pub value_fallbacks: u32,
    pub budget_exhausted: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SearchResult {
    pub action: Option<u16>,
    pub stats: SearchStats,
}

#[derive(Debug)]
struct Edge {
    action: u16,
    prior: f32,
    child: Option<usize>,
    visits: u32,
    value_sum: f32,
}
#[derive(Debug)]
struct Node {
    position: Position,
    edges: Vec<Edge>,
    expanded: bool,
    visits: u32,
}
impl Node {
    fn new(position: Position) -> Self {
        Self {
            position,
            edges: Vec::new(),
            expanded: false,
            visits: 0,
        }
    }
}

pub struct SearchSession<E: Evaluator = B0Evaluator> {
    nodes: Vec<Node>,
    evaluator: E,
    limits: SearchLimits,
    seed: u64,
    stats: SearchStats,
    #[cfg(feature = "research")]
    research_context: Option<SigmaContext>,
}
impl SearchSession<B0Evaluator> {
    pub fn b0(position: Position, limits: SearchLimits, seed: u64) -> Result<Self, SearchError> {
        Self::new(position, limits, seed, B0Evaluator)
    }
}
impl<E: Evaluator> SearchSession<E> {
    pub fn new(
        position: Position,
        limits: SearchLimits,
        seed: u64,
        evaluator: E,
    ) -> Result<Self, SearchError> {
        position
            .checked()
            .map_err(|_| SearchError::InvalidPosition)?;
        let limits = limits.checked()?;
        let mut nodes = Vec::with_capacity(limits.max_nodes as usize);
        nodes.push(Node::new(position));
        // Arena capacity plus one full temporary legal/policy buffer and one traversal path.
        let bytes = nodes.capacity() * size_of::<Node>()
            + 209 * (size_of::<u16>() + size_of::<f32>())
            + limits.max_depth as usize * size_of::<(usize, usize)>();
        if bytes > MAX_ARENA_BYTES {
            return Err(SearchError::InvalidLimits);
        }
        Ok(Self {
            nodes,
            evaluator,
            limits,
            seed,
            #[cfg(feature = "research")]
            research_context: None,
            stats: SearchStats {
                nodes: 1,
                arena_bytes: bytes,
                high_water_bytes: bytes,
                ..Default::default()
            },
        })
    }
    fn root_cursor(&self) -> RuleCursor {
        #[cfg(feature = "research")]
        {
            self.research_context.clone()
        }
        #[cfg(not(feature = "research"))]
        {
            RuleCursor
        }
    }
    #[cfg(feature = "research")]
    pub fn new_sigma(
        context: SigmaContext,
        limits: SearchLimits,
        seed: u64,
        evaluator: E,
    ) -> Result<Self, SearchError> {
        context
            .validate_normal()
            .map_err(|_| SearchError::InvalidPosition)?;
        Self::with_sigma(context, limits, seed, evaluator)
    }
    #[cfg(feature = "research-diagnostics")]
    pub fn new_sigma_diagnostic(
        context: SigmaContext,
        limits: SearchLimits,
        seed: u64,
        evaluator: E,
    ) -> Result<Self, SearchError> {
        Self::with_sigma(context, limits, seed, evaluator)
    }
    #[cfg(feature = "research")]
    fn with_sigma(
        context: SigmaContext,
        limits: SearchLimits,
        seed: u64,
        evaluator: E,
    ) -> Result<Self, SearchError> {
        let mut s = Self::new(context.position(), limits, seed, evaluator)?;
        // Immutable base plus worst-case old/new path overlay allocations.
        let bytes = context.history_counts().len()
            * size_of::<(quoridor_core::research::HistoryKey, u16)>()
            + 3 * limits.max_depth as usize * size_of::<quoridor_core::research::HistoryKey>()
            + 2 * size_of::<usize>();
        s.stats.arena_bytes = s
            .stats
            .arena_bytes
            .checked_add(bytes)
            .ok_or(SearchError::InvalidLimits)?;
        if s.stats.arena_bytes > MAX_ARENA_BYTES {
            return Err(SearchError::InvalidLimits);
        }
        s.stats.high_water_bytes = s.stats.arena_bytes;
        s.research_context = Some(context);
        Ok(s)
    }
    pub fn done(&self) -> bool {
        cursor_terminal(self.nodes[0].position, &self.root_cursor()).is_some()
            || self.stats.simulations >= self.limits.simulations
    }
    pub fn stats(&self) -> SearchStats {
        self.stats
    }
    pub fn root_edges(&self) -> Vec<(u16, f32, u32, f32)> {
        self.nodes[0]
            .edges
            .iter()
            .map(|edge| (edge.action, edge.prior, edge.visits, edge.value_sum))
            .collect()
    }
    pub fn step(&mut self, count: u32) -> bool {
        for _ in 0..count.min(32) {
            if self.done() {
                break;
            }
            self.simulate();
            self.stats.simulations += 1;
        }
        self.done()
    }
    pub fn finish(&mut self) -> SearchResult {
        let cursor = self.root_cursor();
        if cursor_terminal(self.nodes[0].position, &cursor).is_some() {
            return SearchResult {
                action: None,
                stats: self.stats,
            };
        }
        if !self.nodes[0].expanded {
            self.expand(0, &cursor);
        }
        let action = self.nodes[0]
            .edges
            .iter()
            .max_by(|a, b| {
                a.visits
                    .cmp(&b.visits)
                    .then_with(|| a.prior.total_cmp(&b.prior))
                    .then_with(|| tie(self.seed, b.action).cmp(&tie(self.seed, a.action)))
            })
            .map(|edge| edge.action);
        SearchResult {
            action,
            stats: self.stats,
        }
    }
    fn expand(&mut self, index: usize, cursor: &RuleCursor) -> f32 {
        #[cfg(feature = "profiling")]
        let _span = quoridor_core::profiling::span(quoridor_core::profiling::Kind::Expand);
        let position = self.nodes[index].position;
        if let Some(value) = cursor_terminal(position, cursor) {
            return value;
        }
        let legal = cursor_legal(position, cursor);
        let output = {
            #[cfg(feature = "profiling")]
            let _span = quoridor_core::profiling::span(quoridor_core::profiling::Kind::Evaluate);
            self.evaluator.evaluate(position, &legal)
        };
        self.expand_output(index, legal, output)
    }
    fn expand_output(&mut self, index: usize, legal: Vec<u16>, output: Evaluation) -> f32 {
        let value = if output.value.is_finite() && (-1.0..=1.0).contains(&output.value) {
            output.value
        } else {
            self.stats.value_fallbacks += 1;
            0.0
        };
        let weight_sum: f32 = output.weights.iter().sum();
        let valid_policy = output.weights.len() == legal.len()
            && output.weights.iter().all(|w| w.is_finite() && *w >= 0.0)
            && weight_sum.is_finite()
            && weight_sum > 0.0;
        if !valid_policy {
            self.stats.policy_fallbacks += 1;
        }
        let total = if valid_policy {
            weight_sum
        } else {
            legal.len() as f32
        };
        let mut edges = Vec::with_capacity(legal.len());
        for (i, action) in legal.into_iter().enumerate() {
            let prior = if valid_policy {
                output.weights[i] / total
            } else {
                1.0 / total
            };
            edges.push(Edge {
                action,
                prior,
                child: None,
                visits: 0,
                value_sum: 0.0,
            });
        }
        let edge_bytes = edges.capacity() * size_of::<Edge>();
        if self.stats.arena_bytes.saturating_add(edge_bytes) > MAX_ARENA_BYTES {
            #[cfg(feature = "profiling")]
            quoridor_core::profiling::arena_cap_hit();
            self.stats.budget_exhausted = true;
            return value;
        }
        self.stats.arena_bytes += edge_bytes;
        self.stats.high_water_bytes = self.stats.high_water_bytes.max(self.stats.arena_bytes);
        self.stats.edges += edges.len() as u32;
        self.nodes[index].edges = edges;
        self.nodes[index].expanded = true;
        value
    }
    fn simulate(&mut self) {
        let mut index = 0usize;
        let mut cursor = self.root_cursor();
        let mut path: Vec<(usize, usize)> = Vec::with_capacity(self.limits.max_depth as usize);
        let mut leaf_is_node = true;
        let mut value;
        loop {
            let position = self.nodes[index].position;
            if let Some(terminal) = cursor_terminal(position, &cursor) {
                value = terminal;
                break;
            }
            if path.len() >= self.limits.max_depth as usize {
                #[cfg(feature = "profiling")]
                quoridor_core::profiling::depth_cap_hit();
                value = self.safe_value(position, &cursor);
                break;
            }
            if !self.nodes[index].expanded {
                value = self.expand(index, &cursor);
                break;
            }
            if self.nodes[index].edges.is_empty() {
                value = self.safe_value(position, &cursor);
                break;
            }
            let edge_index = self.select(index);
            let child = self.nodes[index].edges[edge_index].child;
            path.push((index, edge_index));
            if let Some(child) = child {
                cursor = cursor_follow(
                    self.nodes[child].position,
                    self.nodes[index].edges[edge_index].action,
                    &cursor,
                );
                index = child;
                continue;
            }
            let action = self.nodes[index].edges[edge_index].action;
            let (next, next_cursor) = cursor_next(position, action, &cursor);
            cursor = next_cursor;
            if self.nodes.len() >= self.limits.max_nodes as usize {
                #[cfg(feature = "profiling")]
                quoridor_core::profiling::node_cap_hit();
                self.stats.budget_exhausted = true;
                value = self.safe_value(next, &cursor);
                leaf_is_node = false;
                break;
            }
            let child = self.nodes.len();
            self.nodes.push(Node::new(next));
            self.nodes[index].edges[edge_index].child = Some(child);
            self.stats.nodes += 1;
            index = child;
        }
        self.stats.max_depth_reached = self.stats.max_depth_reached.max(path.len() as u8);
        if leaf_is_node {
            self.nodes[index].visits += 1;
        }
        for (parent, edge_index) in path.into_iter().rev() {
            value = parent_value(value);
            let edge = &mut self.nodes[parent].edges[edge_index];
            edge.visits += 1;
            edge.value_sum += value;
            self.nodes[parent].visits += 1;
        }
    }
    fn safe_value(&mut self, position: Position, cursor: &RuleCursor) -> f32 {
        if let Some(value) = cursor_terminal(position, cursor) {
            return value;
        }
        #[cfg(feature = "research")]
        let fallback_legal = if cursor.is_some() {
            cursor_legal(position, cursor)
        } else {
            Vec::new()
        };
        #[cfg(not(feature = "research"))]
        let fallback_legal: Vec<u16> = Vec::new();
        let output = {
            #[cfg(feature = "profiling")]
            let _span = quoridor_core::profiling::span(quoridor_core::profiling::Kind::Evaluate);
            self.evaluator.evaluate(position, &fallback_legal)
        };
        if output.value.is_finite() && (-1.0..=1.0).contains(&output.value) {
            output.value
        } else {
            self.stats.value_fallbacks += 1;
            0.0
        }
    }
    fn select(&self, index: usize) -> usize {
        #[cfg(feature = "profiling")]
        let _span = quoridor_core::profiling::span(quoridor_core::profiling::Kind::Select);
        let node = &self.nodes[index];
        let root = (node.visits as f32 + 1.0).sqrt();
        let mut best = 0usize;
        let mut best_score = f32::NEG_INFINITY;
        for (i, edge) in node.edges.iter().enumerate() {
            let q = if edge.visits == 0 {
                0.0
            } else {
                edge.value_sum / edge.visits as f32
            };
            let score = q + PUCT_C * edge.prior * root / (edge.visits + 1) as f32;
            if score > best_score
                || (score == best_score
                    && tie(self.seed, edge.action) < tie(self.seed, node.edges[best].action))
            {
                best = i;
                best_score = score;
            }
        }
        best
    }
}

/// Every edge changes the side to move, for pawn and wall actions alike.
pub fn parent_value(child_side_value: f32) -> f32 {
    -child_side_value
}
fn tie(seed: u64, action: u16) -> u64 {
    let mut x = seed ^ action as u64;
    x = (x ^ (x >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
    x = (x ^ (x >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
    x ^ (x >> 31)
}

/// Owned continuation: no replay, no evaluator cache and no backup before reply.
struct Continuation {
    index: usize,
    path: Vec<(usize, usize)>,
    leaf_is_node: bool,
    expand: bool,
    request: Request,
}
#[derive(Clone)]
pub struct Request {
    pub token: u64,
    pub generation: u32,
    pub position: Position,
    pub legal: Vec<u16>,
    pub context: RuleCursor,
}
pub struct PendingSearch {
    pub(crate) search: SearchSession,
    pending: Option<Continuation>,
    generation: u32,
    next_token: u64,
    failed: bool,
    pub calls: u32,
}
impl PendingSearch {
    pub fn new(
        context: SigmaContext,
        limits: SearchLimits,
        seed: u64,
        generation: u32,
    ) -> Result<Self, SearchError> {
        let search = if context.is_synthetic() {
            SearchSession::new_sigma_diagnostic(context, limits, seed, B0Evaluator)?
        } else {
            SearchSession::new_sigma(context, limits, seed, B0Evaluator)?
        };
        Ok(Self {
            search,
            pending: None,
            generation,
            next_token: 0,
            failed: false,
            calls: 0,
        })
    }
    fn guard(&mut self, g: u32) -> Result<(), String> {
        if self.failed {
            return Err("SEARCH_DISCARDED".into());
        }
        if g != self.generation {
            self.cancel();
            return Err("STALE_GENERATION".into());
        }
        Ok(())
    }
    pub fn cancel(&mut self) {
        self.failed = true;
        self.pending = None;
    }
    pub fn begin(&mut self, g: u32) -> Result<Option<Request>, String> {
        self.guard(g)?;
        if self.pending.is_some() {
            self.cancel();
            return Err("PENDING_ALREADY_EXISTS".into());
        }
        if self.search.done() {
            return Ok(None);
        }
        let s = &mut self.search;
        let mut index = 0;
        let mut cursor = s.root_cursor();
        let mut path = Vec::with_capacity(s.limits.max_depth as usize);
        let mut leaf_is_node = true;
        let (position, expand) = loop {
            let p = s.nodes[index].position;
            if let Some(value) = cursor_terminal(p, &cursor) {
                Self::backup(s, index, path, leaf_is_node, value);
                s.stats.simulations += 1;
                return Ok(None);
            }
            if path.len() >= s.limits.max_depth as usize {
                break (p, false);
            }
            if !s.nodes[index].expanded {
                break (p, true);
            }
            if s.nodes[index].edges.is_empty() {
                break (p, false);
            }
            let ei = s.select(index);
            let child = s.nodes[index].edges[ei].child;
            path.push((index, ei));
            let a = s.nodes[index].edges[ei].action;
            if let Some(ci) = child {
                cursor = cursor_follow(s.nodes[ci].position, a, &cursor);
                index = ci;
                continue;
            }
            let (next, nc) = cursor_next(p, a, &cursor);
            cursor = nc;
            if s.nodes.len() >= s.limits.max_nodes as usize {
                s.stats.budget_exhausted = true;
                leaf_is_node = false;
                if let Some(value) = cursor_terminal(next, &cursor) {
                    Self::backup(s, index, path, leaf_is_node, value);
                    s.stats.simulations += 1;
                    return Ok(None);
                }
                break (next, false);
            }
            let ci = s.nodes.len();
            s.nodes.push(Node::new(next));
            s.nodes[index].edges[ei].child = Some(ci);
            s.stats.nodes += 1;
            index = ci;
        };
        self.next_token = TOKEN.with(|t| {
            let n = t.get() + 1;
            t.set(n);
            n
        });
        let request = Request {
            token: self.next_token,
            generation: g,
            position,
            legal: cursor_legal(position, &cursor),
            context: cursor,
        };
        self.pending = Some(Continuation {
            index,
            path,
            leaf_is_node,
            expand,
            request: request.clone(),
        });
        Ok(Some(request))
    }
    pub fn resume(&mut self, g: u32, token: u64, output: Evaluation) -> Result<(), String> {
        self.guard(g)?;
        let Some(c) = self.pending.take() else {
            self.cancel();
            return Err("NO_PENDING_OR_DUPLICATE".into());
        };
        if c.request.token != token {
            self.cancel();
            return Err("FOREIGN_TOKEN".into());
        }
        let sum: f32 = output.weights.iter().sum();
        if !output.value.is_finite()
            || !(-1.0..=1.0).contains(&output.value)
            || output.weights.len() != c.request.legal.len()
            || output.weights.iter().any(|w| !w.is_finite() || *w < 0.)
            || !sum.is_finite()
            || sum <= 0.
        {
            self.cancel();
            return Err("INVALID_EVALUATION".into());
        }
        let value = if c.expand {
            self.search.expand_output(c.index, c.request.legal, output)
        } else {
            output.value
        };
        Self::backup(&mut self.search, c.index, c.path, c.leaf_is_node, value);
        self.search.stats.simulations += 1;
        self.calls += 1;
        Ok(())
    }
    fn backup(
        s: &mut SearchSession,
        index: usize,
        path: Vec<(usize, usize)>,
        leaf_is_node: bool,
        mut value: f32,
    ) {
        s.stats.max_depth_reached = s.stats.max_depth_reached.max(path.len() as u8);
        if leaf_is_node {
            s.nodes[index].visits += 1
        }
        for (parent, ei) in path.into_iter().rev() {
            value = parent_value(value);
            let e = &mut s.nodes[parent].edges[ei];
            e.visits += 1;
            e.value_sum += value;
            s.nodes[parent].visits += 1;
        }
    }
    pub fn checkpoint(&mut self, g: u32) -> Result<SearchResult, String> {
        self.guard(g)?;
        if self.pending.is_some() {
            self.cancel();
            return Err("INCOMPLETE_EVALUATION".into());
        }
        if cursor_terminal(self.search.nodes[0].position, &self.search.root_cursor()).is_none()
            && !self.search.nodes[0].expanded
        {
            self.cancel();
            return Err("NO_COMPLETED_STEP".into());
        }
        // A terminal or already expanded root cannot start an evaluation in finish.
        Ok(self.search.finish())
    }
    pub fn root_terminal_value(&self) -> Option<f32> {
        cursor_terminal(self.search.nodes[0].position, &self.search.root_cursor())
    }
    pub fn is_pending(&self) -> bool {
        self.pending.is_some()
    }
    pub fn request(&self) -> Option<Request> {
        self.pending.as_ref().map(|c| c.request.clone())
    }
    #[cfg(test)]
    fn force_arena_cap(&mut self) {
        self.search.stats.arena_bytes = MAX_ARENA_BYTES;
    }
}

thread_local! {static TOKEN:std::cell::Cell<u64>=const {std::cell::Cell::new(0)};}
#[cfg(test)]
mod pending_arena_tests {
    use super::*;
    struct Spy;
    impl Evaluator for Spy {
        fn evaluate(&self, _: Position, l: &[u16]) -> Evaluation {
            Evaluation {
                weights: vec![1.; l.len()],
                value: 0.25,
            }
        }
    }
    #[test]
    fn arena_fallback_same_backup() {
        let c = SigmaContext::from_prefix(&[]).unwrap();
        let lim = SearchLimits {
            simulations: 32,
            max_nodes: 64,
            max_depth: 8,
        };
        let mut a = SearchSession::new_sigma(c.clone(), lim, 1979, Spy).unwrap();
        let mut b = PendingSearch::new(c, lim, 1979, 1).unwrap();
        a.step(1);
        let q = b.begin(1).unwrap().unwrap();
        b.resume(
            1,
            q.token,
            Evaluation {
                weights: vec![1.; q.legal.len()],
                value: 0.25,
            },
        )
        .unwrap();
        a.stats.arena_bytes = MAX_ARENA_BYTES;
        b.force_arena_cap();
        while !a.done() {
            a.step(1);
            if let Some(q) = b.begin(1).unwrap() {
                b.resume(
                    1,
                    q.token,
                    Evaluation {
                        weights: vec![1.; q.legal.len()],
                        value: 0.25,
                    },
                )
                .unwrap()
            }
            assert_eq!(a.root_edges(), b.search.root_edges());
            assert_eq!(a.stats, b.search.stats)
        }
        assert_eq!(a.finish(), b.checkpoint(1).unwrap());
    }
    #[test]
    fn unfinished_public_checkpoint_discards() {
        let c = SigmaContext::from_prefix(&[]).unwrap();
        let mut s = PendingSearch::new(
            c,
            SearchLimits {
                simulations: 32,
                max_nodes: 64,
                max_depth: 8,
            },
            1979,
            1,
        )
        .unwrap();
        s.begin(1).unwrap();
        assert!(s.checkpoint(1).is_err());
        assert!(s.begin(1).is_err());
    }
}
