import pathlib,json,datetime
D=pathlib.Path('research-data/ai-sigma/191-manygame-independent')
base=pathlib.Path('research-data/ai-sigma/184-checkpoint-teacher-independent/save.py').read_text().replace('184-checkpoint-teacher-independent','191-manygame-independent').replace('ai-sigma-critic-checkpoint-teacher-independent.md','ai-sigma-critic-manygame-independent.md')
D.joinpath('save.py').write_text(base)
a=json.loads((D/'arithmetic.json').read_text());cpu=a['modes'][0];gpu=a['modes'][-1]
v={'issue':'quoridor-4lc.191','classification':{'sameK_saved_teacher':'finite_support','GPU24_production_cost_vs_CPUJS':'finite_support','Rust_vs_Rust_completed_control':'insufficient_missing','unseen_state_validation':'not_supported_as_zero_overlap','full_pipeline_speed_multiplier':'insufficient','strength_NI':'not_claimed'},'all120':a['all120_status'],'allattempt_wall_s':a['allattempt_jobwall_s'],'GPU24_CPUJS_joint_rate_ratio':gpu['joint_per_s']/cpu['joint_per_s'],'GPU24_jobwall_reduction':1-gpu['allattempt_jobwall_s']/cpu['allattempt_jobwall_s'],'maximum_one_next_direction':'Future GPU24 teacher-to-learning registration: bind state/history group split or exposed/unexposed classification before learner outcomes; preserve original split/results.','old173_reused_as_teacher':False,'NN_new':0,'own_science_stopped':True,'coordinator_acceptance_pending':True,'report':'docs/reports/ai-sigma-critic-manygame-independent.md'}
D.joinpath('verdict.json').write_text(json.dumps(v,indent=2)+'\n')
files=[p for p in D.iterdir() if p.is_file()]+[pathlib.Path(v['report'])]
allocated=sum(p.stat().st_blocks*512 for p in files);logical=sum(p.stat().st_size for p in files);i=json.loads((D/'intake.json').read_text());forecast=i['storage']['known_allocated']+i['storage']['old_unknown']+4194304
assert logical*3+allocated<3670016 and forecast<117440512
D.joinpath('storage-before-Git.json').write_text(json.dumps({'UTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'newscope_logical':logical,'newscope_allocated':allocated,'unique_Git_and_metadata_conservative_remaining_forecast':logical*2+131072,'newscope_guard':3670016,'forecast_including_old_unknown':forecast,'existing_guard':117440512,'old_unknown_retained':i['storage']['old_unknown'],'discount':0,'parent_addition':0,'default_private_index_touched':False},indent=2)+'\n')
D.joinpath('handoff.txt').write_text('goal quoridor-4lc / 本人191 保存独立裁定。全120slot:96GOAL/3schemaunknown/21NOT_STARTED保持。各完走mode1132joint同root64edge63、原raw joinとsharedRuleA 4528手対応支持（共通審判/全deep/NN再認証なし）。CPUJS137.836401s/8.212635行秒、GPU3 247.139345s、GPU12 107.801322s、GPU24 88.334456s/12.814931行秒、行率比1.560392/生成jobwall35.9136%減。原RustCPU190NN/6.334307sは3fault+21notstarted、structural完走対照欠測を0品質/救済へ変換0。全11attempt630.587673s＋別export/prep/packを保存、APIpipe排他CPU加算0、全pipeline倍率/棋力NI認定0。重大差:game split train-val共有7state/20occ、次GPU24教師→学習登録でstate/historygroupまたは既露出区分を結果前固定する最大1案、旧split改変0。188保存502算術は新MSE1.663258→1.951053→1.706646、sign66→85→60/game015全0of70/低LRwrong saturation45→0を確認、原因/強さ0・176既定維持。188管理guard超過28086Bと未Gitstopを科学とは別保持。source/NN0科学子停止、計算5.544855s/RSSmax293982208B、静的累積保守charge90s<120、CPU0窓14:06:33解放。自域Git/必要byte復元/Beadsbackup後保存版を通知、原source結果編集/NN/GPU/game/train/build/委譲0。報告 docs/reports/ai-sigma-critic-manygame-independent.md、独立証拠 research-data/ai-sigma/191-manygame-independent/。受入closeはcoordinator、goal他者close0。\n')
print({'logical':logical,'allocated':allocated,'forecast':forecast})
