'use strict';
// Thin private evolution of 177's queue: game identity, cancellation drain and global quarantine.
const {performance}=require('perf_hooks'),I=require('../../ai-sigma-manygame-generation/identity.cjs');
class Broker{
 constructor(askBatch,{maxBatch=8,flushMs=.25,replyCap=512}={}){if(![8,24].includes(maxBatch)||flushMs<0||flushMs>1||!Number.isSafeInteger(replyCap)||replyCap<1||replyCap>307200)throw Error('BROKER_CONFIG');Object.assign(this,{askBatch,maxBatch,flushMs,replyCap});this.queue=[];this.owners=new Map;this.timer=null;this.inflight=null;this.next=0;this.stopped=false;this.fault=null;this.waiters=[];this.stats={started:0,returned:0,resumed:0,discarded:0,rejected_queued:0,batches:[],receipts:[],max_pending_games:0,batch_histogram:Array(maxBatch+1).fill(0),queue_ms_sum:0,queue_ms_max:0,provider_pipe_ms:0};}
 infer(identity,bits){let id;try{id=I.validate(identity);I.features(bits)}catch(e){return Promise.reject(e)}const o=I.owner(id);return new Promise((resolve,reject)=>{if(this.stopped)return reject(Error(this.fault??'STOPPED'));if(this.owners.has(o))return reject(Error('ONE_PENDING_PER_GAME'));if(this.owners.size>=24)return reject(Error('GAME_PENDING_CAP')); const entry={identity:id,wire_id:'nn0.'+(++this.next),bits,resolve,reject,cancelled:false,queued:performance.now(),sent:null};this.owners.set(o,entry);this.queue.push(entry);this.stats.max_pending_games=Math.max(this.stats.max_pending_games,this.owners.size);this.schedule();});}
 schedule(){if(this.stopped||this.inflight||!this.queue.length)return;if(this.queue.length>=this.maxBatch){if(this.timer)clearTimeout(this.timer);this.timer=null;void this.flush()}else if(!this.timer)this.timer=setTimeout(()=>{this.timer=null;void this.flush()},this.flushMs);}
 async flush(){if(this.stopped||this.inflight||!this.queue.length)return;const batch=this.queue.splice(0,this.maxBatch);this.inflight=batch;const sent=performance.now();for(const b of batch)b.sent=sent;this.stats.started+=batch.length;if(this.stats.started>this.replyCap){this.fail('SAMPLE_CAP');for(const b of batch)this.release(b);this.inflight=null;this.notify();return;}try{let rows=await this.askBatch(batch.map(b=>({id:b.wire_id,features_bits648:b.bits})));this.stats.returned+=Array.isArray(rows)?rows.length:0;if(!Array.isArray(rows)||rows.length!==batch.length||rows.some((r,i)=>r.id!==batch[i].wire_id))throw Error('BROKER_ID_ATTRIBUTION');rows=rows.map(require('./wire.cjs').decodeWireRow);const received=performance.now();this.stats.batch_histogram[batch.length]++;this.stats.provider_pipe_ms+=received-sent;for(const b of batch){this.stats.queue_ms_sum+=sent-b.queued;this.stats.queue_ms_max=Math.max(this.stats.queue_ms_max,sent-b.queued)}if(this.replyCap<=512||this.stats.batches.length<16)this.stats.batches.push({size:batch.length,sent_ms:sent,received_ms:received,queue_ms:batch.map(b=>sent-b.queued)});batch.forEach((b,i)=>{if(this.replyCap<=512||this.stats.receipts.length<16)this.stats.receipts.push({identity:b.identity,wire_id:b.wire_id,started_ms:b.sent,returned_ms:received,discarded:b.cancelled});if(b.cancelled){this.stats.discarded++;b.reject(Error('CANCEL_RETURN_DISCARDED'))}else{this.stats.resumed++;b.resolve({identity:b.identity,NN:rows[i]})}});}catch(e){this.fail(e.message)}finally{for(const b of batch)this.release(b);this.inflight=null;this.notify();this.schedule();}}
 release(b){const o=I.owner(b.identity);if(this.owners.get(o)===b)this.owners.delete(o);for(const f of b.drainWaiters??[])f();}
 cancel(worker,game,generation,run){const o=JSON.stringify([run,worker,game]),b=this.owners.get(o);if(!b)return{pending:false};if(b.identity.generation!==generation)return{pending:true,error:'STALE_CANCEL_GENERATION'};b.cancelled=true;if(b.sent===null){this.queue=this.queue.filter(x=>x!==b);this.stats.rejected_queued++;b.reject(Error('CANCEL_QUEUED'));this.release(b);this.notify()}return{pending:b.sent!==null,inflight:b.sent!==null};}
 fail(reason){this.fault=reason;this.stopped=true;if(this.timer)clearTimeout(this.timer);this.timer=null;for(const b of this.queue.splice(0)){b.cancelled=true;b.reject(Error('PROVIDER_OR_CONTROL_UNKNOWN:'+reason));this.release(b)}for(const b of this.inflight??[]){b.cancelled=true;b.reject(Error('PROVIDER_OR_CONTROL_UNKNOWN:'+reason))}this.notify();}
 stop(){if(this.timer)clearTimeout(this.timer);this.timer=null;this.stopped=true;for(const b of this.queue.splice(0)){this.stats.rejected_queued++;b.cancelled=true;b.reject(Error('STOPPED_QUEUED'));this.release(b)}for(const b of this.inflight??[])b.cancelled=true;this.notify();return this.zero();}
 zero(){return{pending_games:this.owners.size,inflight_batches:this.inflight?1:0,queued:this.queue.length,timer:this.timer!==null,started:this.stats.started,returned:this.stats.returned};}
 notify(){if(!this.owners.size&&!this.inflight){for(const f of this.waiters.splice(0))f();}}
 async quiescent(){if(!this.owners.size&&!this.inflight)return;await new Promise(resolve=>this.waiters.push(resolve));}
 async quiescentGame(worker,game,run){const b=this.owners.get(JSON.stringify([run,worker,game]));if(!b)return;await new Promise(resolve=>(b.drainWaiters??=[]).push(resolve));}
}
module.exports={Broker};
