from pathlib import Path
import datetime,hashlib,json
R=Path.cwd();T=R/'tools/ai-sigma-teacher-throughput';D=R/'research-data/ai-sigma/frame16-teacher-throughput';G=T/'architecture-control';C=T/'codec-control';O=D/'codec-control'
s=(G/'runner.py').read_text().replace("A=T/'architecture-control';O=D/'architecture-control'","A=T/'codec-control';O=D/'codec-control'")
s=s.replace("reg=json.loads((D/'preregister.json').read_text());binding=json.loads((O/'source-freeze.json').read_text())", "reg=json.loads((D/'preregister.json').read_text());binding=json.loads((O/'source-freeze.json').read_text())")
s=s.replace("schpath=Path('/workspaces/quoridor/.artifacts/research-team/scheduler-sigma-continuation-20261001/state.json');sch=json.loads(schpath.read_text());assert sch['phase']=='running' and sch['owned']is None and not sch.get('recovery_required');quiet=sch['next_at']-time.time();assert quiet>=c['job_seconds']+30,'SUPERVISOR_QUIET_SHORT'", "schpath=Path('/workspaces/quoridor/.artifacts/research-team/scheduler-sigma-continuation-20261001/state.json');sch=json.loads(schpath.read_text());assert sch['phase']=='running' and not sch.get('recovery_required');assert sch['owned']is None,'CURRENT_OWNED_REQUIRES_PHYSICAL_HANDOFF';quiet=sch['next_at']-time.time();assert quiet>=c['job_seconds']+30,'SUPERVISOR_QUIET_SHORT'")
a=s.index('monitor=R/');b=s.index('for role in',a)
s=s[:a]+"assert c.get('runtime_loaded'),'NEW_RUNTIME_BINDING_REQUIRED'\nloadedpath=Path(c['runtime_loaded']);loaded=json.loads(loadedpath.read_text());assert loaded['parent_version']==17\nmonitor=Path(c.get('runtime_monitor')or str(Path(loaded['run'])/'monitor-observation.json'));mon=json.loads(monitor.read_text());assert time.time()-monitor.stat().st_mtime<120,'CURRENT_MONITOR_STALE'\n"+s[b:]
s=s.replace("spent=355.917963652+", "spent=533.4066868470415+").replace("samples=243888+","samples=406620+")
s=s.replace("<=505000", "<=362000").replace("c['NN_cap']<=250000", "c['NN_cap']<=180000").replace("c['NN_cap']<=5000", "c['NN_cap']<=2000")
a=s.index("storage=json.loads((D/'storage-admission.json')");b=s.index("save('admission.json'",a)
s=s[:a]+"storage=json.loads((O/'storage-admission.json').read_text());assert storage['unused_after_reservation_B']>=0\ncodecusage=lambda:sum(p.stat().st_size for root in[A,O]for p in root.rglob('*')if p.is_file())\ngitupper=sum(p.stat().st_size for root in[A,O]for p in root.rglob('*')if p.is_file()and'/jobs/'not in str(p))\nforecast=codecusage()+gitupper+4*1024**2+(20*1024**2 if c['kind']=='generation'else 1*1024**2)\nassert forecast<56*1024**2,('NEW_STORAGE_FORECAST',forecast)\noldcurrent=sum(p.stat().st_size for root in[T,D]for p in root.rglob('*')if p.is_file()and'codec-control'not in str(p));assert oldcurrent<=storage['old_phase2_forecast_B'],'OLD_SCOPE_FORECAST_UNKNOWN'\n"+s[b:]
s=s.replace("storage_current_B=usage()", "storage_current_B=codecusage(),old_scope_actual_B=oldcurrent,new_runtime_loaded_path=str(loadedpath)")
s=s.replace("if usage()+gitupper+4*1024**2>=112*1024**2", "if codecusage()+gitupper+4*1024**2>=56*1024**2")
(C/'runner.py').write_text(s)
for name,kind,script,cap,seconds in [('parity-r1','parity','parity.cjs',432,50),('codec-r1','generation','generate.cjs',180000,300),('codec-confirmation','generation','generate.cjs',180000,300)]:
 c=json.loads((D/'architecture-control/graph-r1-config.json').read_text());c.update(run_id='throughput221-phase3-'+name,kind=kind,script=script,NN_cap=cap,job_seconds=seconds,job_out=str(O/'jobs'/name),science_deadline='2026-10-04T09:25:50Z',source_git='PENDING_FREEZE',runtime_loaded=None,runtime_monitor=None);(O/(name+'-config.json')).write_text(json.dumps(c,indent=2)+'\n')
files=list(C.glob('*'))+[T/f for f in['worker.cjs','pipe.cjs','adapter.py']]+[G/'provider.py',D/'openings.json',O/'preregister.json',R/'tools/ai-sigma-manygame-generation/pause-monitor.cjs']
b=dict(UTC=datetime.datetime.now(datetime.timezone.utc).isoformat(),files={str(p.relative_to(R)):hashlib.sha256(p.read_bytes()).hexdigest()for p in files if p.is_file()},old_source_immutable=True);(O/'source-freeze.json').write_text(json.dumps(b,indent=2)+'\n')
