from pathlib import Path
T=Path('tools/ai-sigma-teacher-throughput');G=T/'architecture-control';C=T/'codec-control'
s=(G/'qualify.cjs').read_text().replace("AD=D+'/architecture-control'","AD=D+'/codec-control'");(C/'qualify.cjs').write_text(s)
s=(G/'compare.py').read_text().replace("O=D/'architecture-control'", "O=D/'codec-control';GD=D/'architecture-control'")
s=s.replace("def load(n):return json.loads(((O/n)if(O/n).exists()else(D/n)).read_text())", "def load(n):\n p=(O/n)if(O/n).exists()else(GD/n)if(GD/n).exists()else(D/n)\n return json.loads(p.read_text())")
s=s.replace("p=p if p.exists()else D/(n+'-teacher-rows.jsonl.gz')", "p=p if p.exists()else GD/(n+'-teacher-rows.jsonl.gz')if(GD/(n+'-teacher-rows.jsonl.gz')).exists()else D/(n+'-teacher-rows.jsonl.gz')")
s=s.replace("else D/'jobs'/name;hist", "else(GD/'jobs'/name)if(GD/'jobs'/name).exists()else D/'jobs'/name;hist")
s=s.replace("['baseline','candidate','baseline-confirmation','graph-r1','graph-confirmation']", "['graph-r1','graph-confirmation','codec-r1','codec-confirmation']")
s=s.replace("if(D/(n+'-summary.json')).exists()or(O/(n+'-summary.json')).exists()", "if(GD/(n+'-summary.json')).exists()or(O/(n+'-summary.json')).exists()")
s=s.replace("a=rows('baseline');b=rows('graph-r1')", "a=rows('graph-r1');b=rows('codec-r1')")
s=s.replace("base=out['baseline'];cand=out['graph-r1']", "base=out['graph-r1'];cand=out['codec-r1']")
s=s.replace("for name in ['graph-r1','graph-confirmation']:", "for name in ['codec-r1','codec-confirmation']:")
s=s.replace("result['phase1_NN']=243888", "result['prior_phases_NN']=406620").replace("result['totalNN']=243888+", "result['totalNN']=406620+").replace("result['phase2_NN']", "result['phase3_NN']").replace("phase2_measuredwall", "phase3_measuredwall")
s=s.replace("if 'graph-confirmation'in out:", "if 'codec-confirmation'in out:")
s=s.replace("bm=(out['baseline']['jobwall_s']+out['baseline-confirmation']['jobwall_s'])/2;gm=(out['graph-r1']['jobwall_s']+out['graph-confirmation']['jobwall_s'])/2", "bm=(out['graph-r1']['jobwall_s']+out['graph-confirmation']['jobwall_s'])/2;gm=(out['codec-r1']['jobwall_s']+out['codec-confirmation']['jobwall_s'])/2")
s=s.replace("B8_baseline_meanwall=bm,graph_meanwall=gm", "graph_B8_baseline_meanwall=bm,codec_meanwall=gm")
s=s.replace("order='oldphase1B8/B24/B8 followedby graph/graph; sequential hostwarm and no newpairedB8 repetition; oldfailedwallUNKNOWN held5s'", "order='oldgraph/graph followedby newcodec andoptionalconfirmation; fixedsequence/hostwarm retained; codecpackage not singlecomponent cause'")
(C/'compare.py').write_text(s)
s=(G/'pack.py').read_text().replace("frame16-teacher-throughput/architecture-control", "frame16-teacher-throughput/codec-control").replace('graph-evidence-r1.tar.gz','codec-evidence-r1.tar.gz');(C/'pack.py').write_text(s)
