from pathlib import Path
import datetime,hashlib,json
R=Path.cwd();T=R/'tools/ai-sigma-teacher-throughput';D=R/'research-data/ai-sigma/frame16-teacher-throughput';G=T/'architecture-control';C=T/'codec-control';O=D/'codec-control';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
reg=dict(issue='quoridor-4lc.221',phase=3,UTC=datetime.datetime.now(datetime.timezone.utc).isoformat(),selected_package='Single actual response encoding + bits-only provider wire; broker reconstructs validated f32 logits/value',same_graph_math_source=True,graph_source_SHA=sha(G/'provider.py'),model_SHA='d790dac68389f7602ff8a887a2385417d3c925fe22da7164c86e9226f943908d',maxB=8,active=24,workers=[2,4,6],management=0,torch_ORT_BLAS_threads=1,K=64,rootN=64,edgeSum=63,tau='1 first16newply then argmax',newply_cap=200,games=48,openings_SHA=sha(D/'openings.json'),same_actionseed=True,expected_saving='Remove one discarded encode and redundant 136double/value output. Old stdout9-10s includes encode/pipewait, not all saving promised. Fixed graph forward/root bits reused.',easy_difference='Provider tail encode once and id+uint32[137]; broker rejects invalid length/uint32/nonfinite/value/ID and reconstructs f32. No tensor math/input/capture/worker/tree/rule changes.',broad_options={'binarywire_Rustpump':'new framing/restart/drain/IDs/nativebuild and interface parity; deferred beyond this small package, not process preservation goal','C++generation':'get_batch/put_results useful pattern but board/FPU/TT/noise/PCR/solver/teacher mapping require explicit correspondence; no simultaneous port'},effect_scope='Both codec changes packaged; no individual cause attribution',definitions={'old':'discarded JSON firstpass plus actual secondencode/write; firstpass perresponse cost included hotwire selfmeasurementfield','new':'exactly one transmitted response json.dumps; encode/write cumulative info/stop for priorresponses, no perresponse selfmeasurementfield; stopownencode/write not recursively included'},confirmation='Matched samecandidate second job only if remainingcap/storage/quiet and first timing/sequence ambiguity; preserve firstsuccess, no replacement.',numeric=dict(B=list(range(1,9)),fixtures_per_B=2,old_graph_startup=108,old_graph_requests=72,CPUORT_reference=72,new_graph_startup=108,new_graph_requests=72,total_NN=432,bitexact='old graph f32bits137 vs newcodec f32bits137; decoded reencodedf32 mustbitexact',CPUtol='abs1e-4+rtol1e-4'),caps=dict(phase3_NN=362000,parity_max=2000,generation_max_each=180000,jobs=2,each_s=300,phase3_heavy_s=650,phase3_static_s=60,phase3_management_s=180,old_NN=406620,original_NN=900000,old_static_charge_s=70,original_static_cap_s=180,old_heavy_conservative_s=533.4066868470415,original_heavy_s=1800,old_management_charge_s=150,original_management_cap_s=600),deadline=dict(newscience='2026-10-04T09:15:50Z',stop='2026-10-04T09:25:50Z',save='2026-10-04T09:38:50Z',submit='2026-10-04T09:43:50Z'),reservation_B=64*1024**2,guard_B=56*1024**2,forecast_B=48*1024**2,old_reserve_B=128*1024**2,old_forecast_B=116807935,old_source_results_immutable=True,benchmark_trainmix=False,oldtest_173_read=False)
(O/'preregister.json').write_text(json.dumps(reg,indent=2)+'\n')
unused=1179754496;storage=dict(UTC=reg['UTC'],experiment_pool_MiB=1980,prior_unused_B=unused,reservation_B=64*1024**2,unused_after_reservation_B=unused-64*1024**2,new_forecast_B=48*1024**2,new_guard_B=56*1024**2,old221_reservation_B=128*1024**2,old_phase2_forecast_B=116807935,old_phase2_actual_current_B=sum(p.stat().st_size for root in[T,D]for p in root.rglob('*')if p.is_file()and 'codec-control'not in str(p)),old_unknown_discount_B=0,parent_added_B=0,source_ledger='frame16-teacher-throughput/storage-admission.json; no later experiment allocation identified by current owner; otherrole pools distinct');assert storage['unused_after_reservation_B']>=0;(O/'storage-admission.json').write_text(json.dumps(storage,indent=2)+'\n')
wire="""'use strict';function decodeWireRow(r){if(!r||typeof r!=='object'||Array.isArray(r)||typeof r.id!=='string'||!r.id.length||r.id.length>128||Object.keys(r).some(k=>!['id','f32bits137'].includes(k)))throw Error('WIRE_SCHEMA');const bits=r.f32bits137;if(!Array.isArray(bits)||bits.length!==137||!bits.every(b=>Number.isInteger(b)&&b>=0&&b<=4294967295))throw Error('UINT32_SHAPE');if(bits.some(b=>(b&0x7f800000)===0x7f800000))throw Error('F32_NONFINITE');const u=new Uint32Array(bits),f=new Float32Array(u.buffer),logits=Array.from(f.subarray(0,136)),value=f[136];if(!logits.every(Number.isFinite)||!Number.isFinite(value)||Math.abs(value)>1)throw Error('VALUE_RANGE');if(!bits.every((b,i)=>new Uint32Array(new Float32Array([...logits,value]).buffer)[i]===b))throw Error('F32_ROUNDTRIP');return{id:r.id,f32bits137:bits.slice(),logits,value};}module.exports={decodeWireRow};\n"""
# Avoid137 repeated typedarray allocations: compute reconstructed words once, retain explicit roundtrip safeguard.
wire=wire.replace("if(!bits.every((b,i)=>new Uint32Array(new Float32Array([...logits,value]).buffer)[i]===b))", "const roundtrip=new Uint32Array(new Float32Array([...logits,value]).buffer);if(!bits.every((b,i)=>roundtrip[i]===b))")
(C/'wire.cjs').write_text(wire)
s=(T/'broker.cjs').read_text().replace("require('../ai-sigma-manygame-generation/identity.cjs')","require('../../ai-sigma-manygame-generation/identity.cjs')")
s=s.replace("const rows=await this.askBatch", "let rows=await this.askBatch");begin=s.index('for(const r of rows){');end=s.index('const received=performance.now();',begin);s=s[:begin]+"rows=rows.map(require('./wire.cjs').decodeWireRow);"+s[end:];(C/'broker.cjs').write_text(s)
s=(G/'provider.py').read_text().replace("Path(__file__).resolve().parents[1]", "Path(__file__).resolve().parents[1]")
s=s.replace("'torch-folded-CUDAgraph-B1to8-v1'","'torch-folded-CUDAgraph-bitswire-singleencode-v1'").replace("'json_encode_firstpass':json_encode_ms","'json_encode_once':json_encode_ms").replace("'stdout_write':stdout_write_ms","'actual_stdout_write':stdout_write_ms,'definition':'prior responses only; stop own encode/write excluded'")
s=s.replace("result.append({'id':id,'f32bits137':vals.view(np.uint32).tolist(),'logits':p[i].tolist(),'value':float(v[i,0])})","result.append({'id':id,'f32bits137':vals.view(np.uint32).tolist()})")
begin=s.index(" t=time.perf_counter_ns();json.dumps(response");end=s.index(" if req.get('op')=='stop':break",begin)
s=s[:begin]+" t=time.perf_counter_ns();payload=json.dumps(response,separators=(',',':'));json_encode_ms+=(time.perf_counter_ns()-t)/1e6\n wt=time.perf_counter_ns();print(payload,flush=True);stdout_write_ms+=(time.perf_counter_ns()-wt)/1e6\n"+s[end:];(C/'provider.py').write_text(s)
s=(G/'generate.cjs').read_text().replace("require('../broker.cjs')","require('./broker.cjs')");s=s.replace("providerCost={batches:0,", "providerCost={codec:'singleencode-bits-only-v1',JSON_firstpass_NOT_APPLICABLE:true,batches:0,");(C/'generate.cjs').write_text(s)
