from pathlib import Path
import datetime,hashlib,json
R=Path.cwd();C=R/'tools/ai-sigma-teacher-throughput/codec-control';O=R/'research-data/ai-sigma/frame16-teacher-throughput/codec-control';p=C/'runner.py';old=p.read_text();(C/'runner-before-unlimited-policy.py').write_text(old)
s=old.replace("assert sch['owned']is None,'CURRENT_OWNED_REQUIRES_PHYSICAL_HANDOFF';quiet=sch['next_at']-time.time();assert quiet>=c['job_seconds']+30,'SUPERVISOR_QUIET_SHORT'", "quiet=sch['next_at']-time.time()if sch.get('next_at')else None\nif sch['owned']is None:assert quiet is not None and quiet>=c['job_seconds']+30,'SUPERVISOR_QUIET_SHORT'\n# User withdrew LLM turn-time cap. An owned LLM turn alone is not a physical CPU job gate.\n# Existing actual script/process admission below must still show no foreign science/critic compute.\nif sch['owned']is not None:assert c.get('allow_owned_LLM_with_physical_guard')is True,'CURRENT_OWNED_PHYSICAL_POLICY_REQUIRED'")
s=s.replace("for z in members:\n   try:", "# If an actual foreign scientific script starts during the job, stop this owned job, never interrupt theirs.\n  for fp,fz in table().items():\n   if fp==os.getpid()or fz['state']=='Z'or(fp,fz['tick'])in tracked:continue\n   try:fa=Path(f'/proc/{fp}/cmdline').read_bytes().decode().split('\\0')\n   except(OSError,UnicodeError):continue\n   fs=next((a for a in fa[1:5]if a.endswith(('.py','.cjs','.js','.sh'))),'')\n   if ('tools/ai-sigma-'in fs or 'tools/nnue-training/'in fs or (fa and 'faithful-native'in fa[0]))and str(T)not in fs and not fs.endswith(('/save_git.py','/save.py','/pack.py')):reason='CURRENT_FOREIGN_COMPUTE_STARTED'\n  for z in members:\n   try:")
p.write_text(s)
b=json.loads((O/'source-freeze.json').read_text());b['UTC']=datetime.datetime.now(datetime.timezone.utc).isoformat();b['prospective_runtime_amendment']='User 180s supervisor turn cap removed; activeLLM alone not countgate. Fresh actual CPU/RSS/owner/newloaded needed; new foreign scientificprocess triggers ownjob stop.';b['files'][str(p.relative_to(R))]=hashlib.sha256(p.read_bytes()).hexdigest();b['files'][str((C/'runner-before-unlimited-policy.py').relative_to(R))]=hashlib.sha256(old.encode()).hexdigest();(O/'source-freeze-v2.json').write_text(json.dumps(b,indent=2)+'\n')
# Keep v1 source binding and adjust runner to read prospective v2. Bind final runtime policy source.
s=p.read_text().replace("(O/'source-freeze.json')","(O/'source-freeze-v2.json')");p.write_text(s);b['files'][str(p.relative_to(R))]=hashlib.sha256(p.read_bytes()).hexdigest();(O/'source-freeze-v2.json').write_text(json.dumps(b,indent=2)+'\n')
